### ISSUE TITLE
Download DS not working with Twilightmenu++

### ISSUE THREAD

**Issue by MasterLuke05** [DS-Homebrew/TWiLightMenu#1000]
**Your console configuration:**  
Nintendo DSi with HiyaCFW+Unlaunch
**TWiLight Menu++ Version:** 
14.0.0
**TWiLight Menu++ Theme:** AKMenu, but I have the same problem even with other themes

### Expected behaviour

Download DS works and I can play

### Actual behaviour

Screen freezes and connection gets lost

### Steps to reproduce

1.Open download Ds on one DSi
2. Open a download Ds play on any game 
3. Screen freezes and connection gets lost

**Comment by RocketRobz** [comment]
DS Download Play doesn't work, if the game uses Cloneboot for it.
Also, this is an nds-bootstrap issue.
