### ISSUE TITLE
Nintendo 3DS Error when opening gamr

### ISSUE THREAD

**Issue by Jake919** [DS-Homebrew/TWiLightMenu#1001]
**Your console configuration:**  
**TWiLight Menu++ Version:** Nintendo 3DS 11.13 with Luma3DS 14.0
**TWiLight Menu++ Theme:**  AKmenu

### Expected behaviour

The game runs normally

### Actual behaviour

After some time the game crashes and the console gives an error telling: "Hold the power button to turn off the console"

### Steps to reproduce

1.Turn on the console
2.Open twilight menu
3.Boot the game

**Comment by NightYoshi370** [comment]
This isn't an error with twilight. Rather, nds-bootstrap.
Also, please be more specific. Which game?

Closing....
