### ISSUE TITLE
Having trouble changing themes on DSi theme

### ISSUE THREAD

**Issue by bobtheepicgamer** [DS-Homebrew/TWiLightMenu#1003]
I wanted to change the DSi theme color on both my 2ds and DSi to match the look of the systems. But i can't find anything to change them to those themes.

**Comment by RocketRobz** [comment]
As stated on the top screen, press A to change the sub theme.

**Comment by bobtheepicgamer** [comment]
Ohhhhh. Now i see it. I should have payed more attention.. heheh... Anyways, thanks for the help
