### ISSUE TITLE
Problem when SEGA Saturn is selected as theme

### ISSUE THREAD

**Issue by Jake919** [DS-Homebrew/TWiLightMenu#1005]
**Your console configuration:**  3DS with Luma 3DS
**TWiLight Menu++ Version:** 14.0
**TWiLight Menu++ Theme:** SEGA Saturn

### Expected behaviour

Open the Twilight Menu ++ normally.

### Actual behaviour

 Twilight Menu ++ doesn't boot.

### Steps to reproduce

1. Open the Twilight Menu ++

**Comment by NightYoshi370** [comment]
I can't reproduce and it seems like GitHub is bugged so I'll reclose this
