### ISSUE TITLE
SLOT 1 launch error on retail Games

### ISSUE THREAD

**Issue by Ajlee24** [DS-Homebrew/TWiLightMenu#1008]
A Retail game launches but with missing sounds and strange buzzing noises
In this instance "More Brain Training"
**Your console configuration:**  
1 DSi 2 DSi XL all with unlauncher and memory pit hack

**TWiLight Menu++ Version:** Twilight Menu vers 14 and 14.1
**TWiLight Menu++ Theme:** 
DSI Theme
### Expected behaviour

Has always worked in the past, ie retail games run as intended
### Actual behaviour
4 colour blocks are displayed Red Red Yellow Green
Game launches with notable sound glitches

### Steps to reproduce
I have replicated this on 3 DSi Machines but it does not occur on any of my 3ds's
1.
2.
3.
I have temporarily fixed this by replacing the 14/14.01 version of  SLOT1LAUNCH.SRLDR with the 12.20 version, and it works as it should

**Comment by RocketRobz** [comment]
Unfortunately, I do not have this issue, on DSi and 3DS.
Can you test other Slot-1 cards?

**Comment by Ajlee24** [comment]
HiI've tested 3 more carts1 works fine top spin 22 don't original brain training and prof kageyama maths training.They both run, but it sounds like a sound channel is being blocked and replaced with noise and hiss.More braining is the only card I use as I could never dump an image that would run on the dsi.Hope this helpsOn 21 Apr 2020 20:47, RocketRobz <notifications@github.com> wrote:
Unfortunately, I do not have this issue, on DSi and 3DS.
Can you test other Slot-1 cards?

**Comment by RocketRobz** [comment]
Oh, I see what's wrong.
You have `Run in` set to `DSi mode`. Please switch back to `DS mode`.

**Comment by SleepyLark** [comment]
I had this problem happen when launching Kirby Superstar Ultra through Slot-1. Switching to DS Mode fixed it

**Comment by Ajlee24** [comment]
Yes switching back to DS mode fixed it, many thanks
