### ISSUE TITLE
Twilight menu not popping up

### ISSUE THREAD

**Issue by rool36** [DS-Homebrew/TWiLightMenu#1009]
(New 3ds XL)(Luma3DS)(theme is DSi)
(As of 4/21/2020 I am using v14.1.0)
 

### Expected behaviour

Pretty sure (according to multiple guides and yt vids) that a menu should pop up resembling a ds lite menu, complete with a game, gba slot, etc. And a settings button.
Also pretty sure it's supposed to ask for model type when you first start it up.
### Actual behaviour

However, that is not the case for me. The program does not ask for my model type, and will always open into the file select screen Everytime you open it.

### Steps to reproduce

1. I'm not sure
2. but...
3. I followed this vid:   https://youtu.be/BLyZbdWtQIs
By sthetix

Help please?
Much thanks-
Rool36

(Btw this was my first post)

**Comment by RocketRobz** [comment]
That info is out of date.
The model type and DS screens no longer appear at the beginning.
The DS screen has changed and now appears when pressing SELECT.

**Comment by rool36** [comment]
Ah I see, sorry. thanks for the info and it works fine.
