### ISSUE TITLE
Camera and XL launcher

### ISSUE THREAD

**Issue by AlejqueGB** [DS-Homebrew/TWiLightMenu#1011]
I think it would be a good idea to give the camera functionality within the twilight menu for dsi xl users.

The second thing I want to comment on is that I also see a possibility of doing a kind of optional redesign that can be activated from the twilight menu to give the user the experience of a dsi XL even for normal dsi users, I know this costs a lot of work to do but I think it's a good idea.

**Comment by Epicpkmn11** [comment]
What do you mean the "experience of a dsi XL"? The only difference between DSi and DSi XL is hardware things like the screens and battery being larger, the software is all exactly the same...
