### ISSUE TITLE
WarioWare DIY Not saving My micro game

### ISSUE THREAD

**Issue by Danibrit1159** [DS-Homebrew/TWiLightMenu#1013]
**Your console configuration:**  
**TWiLight Menu++ Version:** 
**TWiLight Menu++ Theme:** 

### Steps to reproduce

1.
2.
3.

**Comment by NightYoshi370** [comment]
1. This is a nds-bootstrap issue, not a TWiLight Menu++ one.
2. You haven't filled out ANYTHING. Give us more info
3. This is already known

Closing

**Comment by Danibrit1159** [comment]
sorry iam new to this
