### ISSUE TITLE
Individual configuration

### ISSUE THREAD

**Issue by MrGoned** [DS-Homebrew/TWiLightMenu#1014]
**Is your feature request related to a problem? Please describe.**
It is somewhat annoying that for example: I am playing Harvest Moon DS and I want to play Pokémon White, but before starting this game I have to go to the settings of the twilight menu and activate the TWL.

**Describe the solution you'd like**
It would be very good to add an individual configuration for each app, for example: by pressing select open the configuration of that game and once saved it should start with the configuration that I put (as it happens in usbloader gx).

**Comment by SleepyLark** [comment]
I believe this already exist, it's called the "per-game settings".  You can open it by pressing 'Y' before launching the game
