### ISSUE TITLE
Guru Meditation Error widescreen not working on any game. 

### ISSUE THREAD

**Issue by Aqee1** [DS-Homebrew/TWiLightMenu#1017]
I want to play Mario Kart DS in widescreen so I followed the steps and now it gives me and error message. I tried deleting the cxi file in the luma/sysmodules folder but every time I delete it and do the TWPatch process again it still gives me black bars and the red screen with it saying guru meditation error! data abort! And yes I have renamed the file to Widescreen and after the error pops up the file goes back into the luma/sysmodules folder and delete itself in the TwlBg folder. Now if I try to play Mario Kart DS it is pixelated and has black bars. Can someone help please?

**Comment by Doux91** [comment]
At least for me the file must be called TwlBg.cxi, you must put it inside sysmodules folder
SD:/luma/sysmodules 
Or in the ctr nand if you got luma file in the ctr nand, CTR NAND/rw/luma/sysmodules and enable the opcion in luma configuration

**Comment by Aqee1** [comment]
I have figured it out but the screen seems stretched and the aspect ratios don't do anything, is this normal?

**Comment by RocketRobz** [comment]
No. Delete `TwlBg.cxi` and re-do the widescreen steps.
If you still get the same issue after that, then wait for RTCom-activated widescreen to be added.

**Comment by Aqee1** [comment]
Ok will do, if it is possible do you have a picture of what it is meant to look like?

**Comment by Aqee1** [comment]
I repeated the steps and it still say Guru Meditation error and deletes the Widescreen.cxi file but places the TwlBg.cxi file back in the sysmodules and make the screen stretched in game and the menu aswell. Also just a note I had to create a twlBg folder because it wasn’t there before.

**Comment by Aqee1** [comment]
![Uploading 80847066...]()

**Comment by Aqee1** [comment]
![image](https://user-images.githubusercontent.com/64429404/80847124-60350000-8c06-11ea-8b1b-eac70e091bb0.jpeg)

**Comment by RocketRobz** [comment]
Starting with 277230e4, widescreen will be handled differently.
