### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by Doux91** [DS-Homebrew/TWiLightMenu#1019]
Please add the option of take screenshots even if is just for the menu, and would like to help with a full spanish translation if you allow me

**Comment by NightYoshi370** [comment]
Apparently, it's not possible.
![image](https://user-images.githubusercontent.com/18664762/84467076-d11cfe00-ac2f-11ea-92ee-003495668b09.png)

**Comment by G9-Dev** [comment]
does he know?
