### ISSUE TITLE
Soft resetting freezes physical DS games

### ISSUE THREAD

**Issue by Cotni** [DS-Homebrew/TWiLightMenu#1021]
**Your console configuration:** New 3DS XL with Luma; however, others on DSi have reported the same issue
**TWiLight Menu++ Version:** Release v14.2.0 and v14.2.0-440d5266
**TWiLight Menu++ Theme:** Appears to occur regardless of theme (tested on Acekard and DSi)

### Expected behaviour

While playing a physical DS game, pressing L+R+A+Start should cause the game to reset, and holding L+R+B+Down for two seconds should cause the system to return to TWLMenu.

### Actual behaviour

Once L+R+A+Start is pressed, or when two seconds have elapsed with L+R+B+Down held pressed, the game immediately mutes and will imminently freeze. In Pokemon Platinum, SoulSilver, White, and White 2, the game freezes immediately. In Mario Kart DS, the game seems to freeze within a couple seconds during a race, during fade-to-black transitions, or after an unpredictable period of time in menus.
Returning to TWLMenu is only possible via returning to the 3DS system menu with the Home Button, or on DS/DSi, only by power cycling the device.

### Steps to reproduce

1. Launch a physical DS game
2. Press L+R+A+Start or hold L+R+B+Down pressed for two seconds

**Comment by Elasder123** [comment]
Same here with Mario Party DS

**Comment by Peter0x44** [comment]
>  TWiLight Menu++ Version: Release v14.2.0 and v14.2.0-440d5266

this is very old verson, almost a year out of date - you should update and see if that is fixed to begin with

TWiLight  Menu++ is also... just a menu
It does not run games, it launches nds-bootstrap to do that.

Note that in the latest versions of nds-bootstrap that combination was removed, you must use the in game menu instead
You can access that by pressing l+r+select, and reset/return from there
I suggest reading the manual as well, you can either access that within TWiLight Menu++, or see https://manual.ds-homebrew.com

**Comment by RocketRobz** [comment]
This issue has been fixed for a while.
