### ISSUE TITLE
Loading the Manual icon overwrites the bips images

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/TWiLightMenu#1023]

**Comment by NightYoshi370** [comment]
Does this still happen now that rendering things has slightly changed?

**Comment by Epicpkmn11** [comment]
Has anyone tested if this is still a thing? A fair bit has changed since this started so it might've fixed itself

**Comment by Epicpkmn11** [comment]
Here's a build with the manual icon re-enabled: https://gist.github.com/Epicpkmn11/4647a7a8549722004a1b7f4690d17feb/raw/e37b6285fabc4d7a18852018c9d063073157ff5f/dsimenu.srldr

I don't have any problems on DSi (K) from internal SD, DSTT, Acekard 2i, and Datel Games n' Music so I think it'd be fine to re-enable it probably.
