### ISSUE TITLE
Always runs last game launched

### ISSUE THREAD

**Issue by DanyElAlgo** [DS-Homebrew/TWiLightMenu#1024]
**Your console configuration:** Old3ds with luma (latest luma and firmware versions) but it also happens in my dsi with MemoryPit 
**TWiLight Menu++ Version:** 13.0.0
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

When running twilight menu ++ it should load the menu

### Actual behaviour

When running twilight menu ++ it just runs my last played game...
The older version of the menu loads the menu itself correctly instead of the last played game...

### Steps to reproduce

1.launch twilight menu ++
2.wait some seconds
3.it just runs the last played game

**Comment by JonArcherII** [comment]
1. This is behavior that is able to be toggled in TWiLightMenu's settings menu (Under `Misc. Settings`; `Last played ROM on startup`).
2. If issues persist, please update to the latest version of TWiLightMenu.
