### ISSUE TITLE
Game cover art manual is outdated

### ISSUE THREAD

**Issue by JosiasElias** [DS-Homebrew/TWiLightMenu#1027]
**Your console configuration:** DSi XL
**TWiLight Menu++ Version:** 15.0
**TWiLight Menu++ Theme:** DSi

I already made a corrected image for no reason but you can use it if you want, its 680 height so it needs to change the ini file 
![theme1-DSi](https://user-images.githubusercontent.com/28114069/81323961-a1953780-906c-11ea-9cb8-c04c2ab25708.png)

### Expected behaviour

Should tell to use PNG

### Actual behaviour

it's still the BMP instructions

### Steps to reproduce

1.go into manual
2.about the DSi theme
3.?????
4. no profit

**Comment by NightYoshi370** [comment]
Fixed in latest nightly
