### ISSUE TITLE
When "Last played ROM on startup" is enabled, booting while holding "B" always shows the splash screen, even if it's disabled in settings

### ISSUE THREAD

**Issue by jportoles** [DS-Homebrew/TWiLightMenu#1028]
### Expected behaviour

Splash screen, intro video, health warning should always be skipped if set to "hide" in settings.

### Actual behaviour

The splash screen and intro video play even if they are disabled in settings if booting with "Last played ROM on startup" while holding B.

### Steps to reproduce

1. Set splash screen, health warning etc to "hide" in settings
2. Enable "Last played ROM on startup" in settings
3. Boot a ROM
4. Power off, power on again holding the B button
5. Splash screen/intro plays

**Comment by eku** [comment]
See #908

**Comment by RocketRobz** [comment]
That's normal.
The splash screen is shown as an indicator that you skipped the last played ROM.

**Comment by jportoles** [comment]
Can you elaborate? Why is an indicator needed here?

**Comment by RocketRobz** [comment]
Because holding B could be done at the wrong time.

**Comment by jportoles** [comment]
Okay, so how about this: When TWiLight Menu starts, if last played ROM on startup is enabled, and the splash screen is set to hide, and the B button is being held, jump straight to the file navigation screen, but show a message on the top screen that says "YOU HAVE SKIPPED LAST ROM PLAYED AUTO START BECAUSE YOU WERE HOLDING THE B BUTTON", that disappears when you press a button. That would make everyone happy and shouldn't be too hard to implement.
