### ISSUE TITLE
Setting and manual icons don't display properly on ds classic screen

### ISSUE THREAD

**Issue by Darth-Koopa** [DS-Homebrew/TWiLightMenu#1030]
Console: New 3DS Sys11.13.0-45J with Luma3DS v10.1.3
TWiLight Menu++ Version:15.0.0
TWiLight Menu++ Theme: ds classic 
### Expected behaviour

The Setting and manual icons should look like what is on a real ds console

### Actual behaviour
![image](https://user-images.githubusercontent.com/45894930/81448916-2d7e9080-914d-11ea-98c1-e35f10ff45e3.png)
 The botton of the icons has an extra layer

### Steps to reproduce
Just turn to ds classic theme

**Comment by RocketRobz** [comment]
This is a TWL_FIRM bug.
Just close the lid and open it again.
