### ISSUE TITLE
anti delete option

### ISSUE THREAD

**Issue by Linkinworm** [DS-Homebrew/TWiLightMenu#1031]
because i gave my daughter of 5 a dsi and installed twilight on it she dont get the concept of what delete means or how to read entirely properly yet. she just presses buttons on the main screen and if something pops up she mashes more buttons till it goes away

would it be possible to maybe add some option within the settings to block games from being deleteable?

**Comment by JonArcherII** [comment]
Yeah, I actually like that idea. I could work on this, unless someone else wants to take a stab at it.
