### ISSUE TITLE
Custom titles.

### ISSUE THREAD

**Issue by MrGoned** [DS-Homebrew/TWiLightMenu#1032]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to add a personalized title to our games, it would give it a nice aesthetic touch.

**Describe the solution you'd like**
For this it would be ideal to add an option to personalize the title of the game like those of DS, apart from giving a better aesthetic touch to the menu, practically it would be correcting the problem of long names and hiding the file extension.

**Describe alternatives you've considered**
I can't think of one.

**Additional context**
For example, if I have Dragon Ball Z: Supersonic Warriors from Gameboy advance and I want to add a title to it like Nintendo DS games do:

![1example](https://user-images.githubusercontent.com/63927926/81484356-d9d67a80-9212-11ea-97cb-584956962fe7.png)

**Comment by Epicpkmn11** [comment]
Added in #1800/#1802
