### ISSUE TITLE
Clock on TWLMenu

### ISSUE THREAD

**Issue by zeroultima6** [DS-Homebrew/TWiLightMenu#1038]
**Your console configuration:**  
**TWiLight Menu++ Version:** 15.1.0
**TWiLight Menu++ Theme:** Any Theme 

### Expected behaviour
The clock works normally 

### Actual behaviour
The clock is out of sync 
P.S: Previous versions like v14 or lower didn't have this issue

### Steps to reproduce

1.
2.
3.

**Comment by JonArcherII** [comment]
Out of sync by how much?
Are you sure your system’s clock isn’t out of sync?

**Comment by zeroultima6** [comment]
Well, as the twlmenu boots it is in sync but as long as i am on DSi theme (or any theme for the matter) it just stops counting like it was frozen, a minor issue though.

**Comment by JonArcherII** [comment]
Ah, I see. I thought you meant it was off by a constant amount, like an hour or so. Yes, that’s an issue indeed

**Comment by RocketRobz** [comment]
It's probably because you're using the 12 hour clock, otherwise I don't have this issue.
Does changing the clock to 24 hours fix this?

**Comment by zeroultima6** [comment]
Nope, still have that problem and yes i checked

**Comment by RocketRobz** [comment]
Are you on a DSi or 3DS?

**Comment by zeroultima6** [comment]
3DS
