### ISSUE TITLE
Whitescreen on launch

### ISSUE THREAD

**Issue by Selisho** [DS-Homebrew/TWiLightMenu#1039]
**Your console**

Old 2DS

 **CFW and configuration**

Luma3DS [10.1.3]

**TWiLight Menu++ version**

Release [15.1.0]

Nightly [13be2734, a7bf9ca5]

**TWiLight Menu++ theme**

Not selectable

**Expected behaviour**

TWiLight Menu++ should start after loading. Settings.ini should be created.

**Actual behaviour**

TWiLight Menu++ wont start and instead both screens are white (waited >20min), no settings.ini will be generated. Application can be closed normally with home button. Tried installation via _TWiLight Menu++ Updater [v4.1.0]_  and manual.

I installled it on two other consoles (New 3DS XL / New 2DS XL) without problems.

**Steps to reproduce**

Evertime I launch.

**Comment by RocketRobz** [comment]
What are your SD card specs?

**Comment by Selisho** [comment]
I can play ds cartridge without a problem and I also did the fix with _TWLFix-CFW_ .

My sd card is the Samsung Evo 64gb.

**Comment by RocketRobz** [comment]
Try reformatting it to FAT32 with 32kb cluster size.

**Comment by Selisho** [comment]
Neat that did the trick, thanks man
