### ISSUE TITLE
TWiLight doesn't recognize the saves for some reason

### ISSUE THREAD

**Issue by PKTrainer** [DS-Homebrew/TWiLightMenu#1041]
I wanted to play some games today, but my saves had disappeared. I looked inside the saves folder and they were all there, but when trying to play the save is not recognized, as if it did not exist, it is very strange.
![f531e717cf85c37ea6a0ba5c07026b2a](https://user-images.githubusercontent.com/65673419/82472121-f488d900-9ac7-11ea-81b7-abeab908fcbf.png)
Look at the dates of the files

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, not a TWiLight Menu++ issue.
