### ISSUE TITLE
Problem encountered while attempting to boot DS Browser from SLOT1

### ISSUE THREAD

**Issue by tomrow** [DS-Homebrew/TWiLightMenu#1042]
**Your console configuration:** 
KTR-001, Luma3DS 10.0.1, Sys 11.13.0-45E, TWLMenu++ 13.1.0 NDSBootstrap 0.32.1
### Expected behaviour
Attempting to load this software results in the DS Browser presenting its user interface or an error stating that the Expansion Pak is missing

### Actual behavior ###
The boot process becomes stuck at this screen, unable to proceed.
![Image depicts 4 squares in a row, all of them red, except the third one from the left, which is yellow](https://user-images.githubusercontent.com/10169982/82731410-8712bd80-9cfe-11ea-823b-e0e51571b856.jpg)

### Steps to reproduce

1. Insert the aforementioned game card into SLOT1
2. Boot TWLMenu
3. Select the game card from the Quick Menu

**Comment by JonArcherII** [comment]
nds-bootstrap issue.

**Comment by RocketRobz** [comment]
@JonArcherII Nope.
TWiLight Menu++ boots Slot-1 games, not nds-bootstrap.

**Comment by JonArcherII** [comment]
> @JonArcherII Nope.
> 
> TWiLight Menu++ boots Slot-1 games, not nds-bootstrap.

Ah, I am mistaken 😄

**Comment by NightYoshi370** [comment]
This happens because of #1040
It's best we use that issue instead
