### ISSUE TITLE
Issue with cheat booting

### ISSUE THREAD

**Issue by StillANintendoUser** [DS-Homebrew/TWiLightMenu#1048]
**Your console configuration:** Regular 2DS (Sys11.13.0-45U) 
**TWiLight Menu++ Version:** version 15.1.1 (the Birthday release!)
**TWiLight Menu++ Theme:** 3DS theme (I like the music)

### Expected behaviour

Loading the cheats from the cheat menu is fine, no problems from there

### Actual behaviour

The problem is loading those cheats. Once I save which cheats I want to activate, and boot the game, the cheats don't load. Not sure if I'm missing anything, I have the usrcheat.dat and everything in place, its just an error with cheats not loading

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue.
