### ISSUE TITLE
"Cache box art to memory" can cause some issues with box art warning

### ISSUE THREAD

**Issue by CuteyCats1234** [DS-Homebrew/TWiLightMenu#1050]
**Is your feature request related to a problem? Please describe.**
Sometimes Cache box art to memory can cause problems with box art

**Describe the solution you'd like**
I don't know how it is caused so I won't ask to fix it but I think a warning should be added to turn it off if problems with box art happens

**Describe alternatives you've considered**
Fixing the bug is another thing that could be done but a warning would be good to solve people the problem if it is hard to fix before the next release

**Comment by NightYoshi370** [comment]
It's not the settings fault. It's rather the images themselves, as they're too big to be loaded into memory. Fix it up using TinyPNG which will trim it down.
Closing
