### ISSUE TITLE
Black Screens when you close the console

### ISSUE THREAD

**Issue by Kofurist** [DS-Homebrew/TWiLightMenu#1052]
**Is your feature request related to a problem? Please describe.**
The emulator goes fine in the start, it starts the games with no issues, the problem comes when i close the console for like 10 seconds, and when i open the console again there's no image, there is sound tho, the game still running, but there is no image at all.

**Describe the solution you'd like**
To be honest i have no idea of the reason it happens.

**Comment by RocketRobz** [comment]
Change the clock speed from TWL to NTR to fix this.
