### ISSUE TITLE
Cant load DSi Menu

### ISSUE THREAD

**Issue by Pigswipe** [DS-Homebrew/TWiLightMenu#1053]
**Your console configuration:** New 3DS with Luma3DS  
**TWiLight Menu++ Version:** Anything between Nightly d695548d and Release 15.1.1
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

The DSi menu boots up, and i can select my games and folders

### Actual behaviour

It gets stuck on the screen that says "If this takes a while, press HOME. then press B. Now Loading..."
It also seems to do a similar thing if i boot up my recent game on the classic DS menu (which boots up normally) where it gets stuck on "Creating RAM Dump..."

### Steps to reproduce

1. Open TwilightMenu++ 
2. Go to the DSi menu

**Comment by RocketRobz** [comment]
Hold B to skip starting the last-booted game, then turn off `Last-played ROM` in TWLMenu++ Settings.

**Comment by Pigswipe** [comment]
I didnt word it correctly, sorry.

**Comment by RocketRobz** [comment]
Then it's normal. The original DSi Menu cannot run on 3DS consoles.
It is also normal for it to show `If this takes a while, press HOME. then press B. Now Loading...` before the ROMs are shown.

**Comment by Pigswipe** [comment]
It hangs on the "If this takes a while, press HOME. then press B. Now Loading..." screen

**Comment by RocketRobz** [comment]
How many ROMs do you have?

**Comment by RocketRobz** [comment]
Also, do you do what's stated on that screen?

**Comment by Pigswipe** [comment]
Yes, and i have 6 NDS Roms, and 4k NES Roms

**Comment by RocketRobz** [comment]
> 4k NES Roms
That could be why it hangs.
Try moving them to separate folders.

**Comment by Pigswipe** [comment]
They are in seperate folders, all of my roms are, but i didnt load that folder _ever_.

**Comment by Pigswipe** [comment]
Ill remove the 4k nes roms and see what happens
