### ISSUE TITLE
How can I save on twlm++

### ISSUE THREAD

**Issue by 3DSFAN101** [DS-Homebrew/TWiLightMenu#1054]
NEW 3DS XL

NSMB

IDK how to save, I'm new to GitHub and this community please don't close this thread if it is in a wrong format. I'd just like to know how to save my current progress in a game.

**Comment by NightYoshi370** [comment]
Via the in game save functionality. There is no real time save for nds-bootstrap yet.
Also, please use discord for general communication

**Comment by CrystalSpore** [comment]
sorry to reopen this issue, but I have been having a horrible time finding the link to the discord server. Could a link to the discord be provided on the Wiki or the Readme?

Thanks!

**Comment by Kaisaan** [comment]
@CrystalSpore here you go: https://discord.gg/yD3spjv

**Comment by CrystalSpore** [comment]
@Kaisaan Many thanks : )
