### ISSUE TITLE
Launching Unlaunch Installer Black Screens

### ISSUE THREAD

**Issue by NightYoshi370** [DS-Homebrew/TWiLightMenu#1055]
**Your console configuration:** Stock Nintendo DSi
**TWiLight Menu++ Version:** 15.1.1
**TWiLight Menu++ Theme:** Nintendo DSi

### Steps to reproduce

1. Launch Unlaunch.dsi
2. Black screen

### Notes

This is not the fault of nds-bootstrap. That error was fixed about a month ago and we still get the black screen and to further prove this, Kaisaan replaced their nds-bootstrap files with copies of pkmn-chest and instead of launching pkmn-chest, it still blacked screen

**Comment by RocketRobz** [comment]
If `Last-played ROM` is enabled, the Unlaunch installer will start successfully, when booting TWLMenu++.

**Comment by RocketRobz** [comment]
Ok, so it seems the initialization of the graphics cause the black screen issue.

**Comment by RocketRobz** [comment]
So it's actually caused by using MaxMod, as it uses FIFO to pass values between each ARM CPU.
