### ISSUE TITLE
TWiLightMenu games not loading

### ISSUE THREAD

**Issue by kercsco** [DS-Homebrew/TWiLightMenu#1056]
Whenever I click on a game in my menu, it says "saving game" for a split second and then goes right back to the booting logo animation that plays before you enter TWiLightMenu. I clicked on the game again and it did the same thing. The game/ROM in question is Miles Edgeworth Investigations.

**Comment by NightYoshi370** [comment]
Please fill out the template we specified. We don't know what theme you used or console or anything of the sort.

**Comment by kercsco** [comment]
> Please fill out the template we specified. We don't know what theme you used or console or anything of the sort.

oh sorry. i didn't realize there was a template. I will create a new issue using it.

**Comment by NightYoshi370** [comment]
Huh, that's weird. It should have given you one.
I'll close this one when your new one is made

**Comment by kercsco** [comment]
> Huh, that's weird. It should have given you one.
> I'll close this one when your new one is made

https://github.com/DS-Homebrew/TWiLightMenu/issues/1057
