### ISSUE TITLE
Game playing the TWiLight Menu opening screen instead of opening whenever prompted to open

### ISSUE THREAD

**Issue by kercsco** [DS-Homebrew/TWiLightMenu#1057]
**Your console configuration:**
Old 3ds XL with Luma3ds and fbi
**TWiLight Menu++ Version:** 
v12.0.0
**TWiLight Menu++ Theme:** 
DSi
### Expected behaviour
The game should create a save file/state, and then start loading the game.
### Actual behaviour
When the game is pressed, it says "save file" for a split second, and then shows the TWiLightMenu++ opening screen again. This happens every time I press on the game.
### Steps to reproduce
1. old 3dsxl with TwiLight Menu++ v12.0.0 and get the edgeworth investigations I rom loaded onto there (w/ luma 3ds also installed as cfw)
2. have the twilightmenu theme be the default dsi theme
3. try to load up the game

It's really specific, so idk if someone could reproduce it.

**Comment by kercsco** [comment]
I can try updating to the latest version of TwiLightMenu, there's been patches after when i installed it.

**Comment by NightYoshi370** [comment]
Yeah, we don't really support the old TWiLight Menu++ version. Please update to the latest and try again.

**Comment by NightYoshi370** [comment]
After looking at it again, it seems like it's more of a support thing. Let's head on over to the Discord server for support.
However, do try to update
