### ISSUE TITLE
Games dont save

### ISSUE THREAD

**Issue by xmota** [DS-Homebrew/TWiLightMenu#1060]
**Your console configuration:**  
**TWiLight Menu++ Version:** 
**TWiLight Menu++ Theme:** 

### Expected behaviour
My games saves when i save in game

### Actual behaviour
The game shows the save. i turn off my DSI, when i turn on the game shows the save is corrupted.

### Steps to reproduce

1.
2.
3.

**Comment by NightYoshi370** [comment]
1. What game
2. Please fill out the issue template.

Please either make a new issue with a filled out template or edit this one. We have those for specification reasons.

**Comment by xmota** [comment]
It is a Nintendo DSI 
the Game is Inazuma eleven 1 and Inazuma eleven 2 Firestorm

**Comment by RocketRobz** [comment]
The bug will be fixed in the next version.
