### ISSUE TITLE
Cannot save game progress (all .nds games)

### ISSUE THREAD

**Issue by ewilly1** [DS-Homebrew/TWiLightMenu#1063]
I am having an issue with saving games progress while using twilight menu ++. None of my NDS games will save but I found the save files in the roms/nds/saves on the SD card. (They are in .sav file format) Also I am using a new 3DS XL with twilight menu version v15.1.1.  I attached a screen shot of the file location of the game saves. I am sorry if this is a noob question, I can't find any solutions. Any help would be much appreciated.
<img width="633" alt="nds" src="https://user-images.githubusercontent.com/63627003/84120103-afc5e180-aa78-11ea-85ba-05c7e3fcc2d3.PNG">

**Comment by RocketRobz** [comment]
Are you using the Acekard theme?

**Comment by ewilly1** [comment]
No, I am using the DSi theme.

**Comment by RocketRobz** [comment]
Please upload `sd:/_nds/nds-bootstrap.ini`

**Comment by ewilly1** [comment]
It is not there??
<img width="789" alt="nds bootstrap" src="https://user-images.githubusercontent.com/63627003/84121828-f7e60380-aa7a-11ea-909a-ad6dc68e655a.PNG">

**Comment by RocketRobz** [comment]
It's the one marked as `Configuration settings`.

**Comment by ewilly1** [comment]
<img width="620" alt="config settings" src="https://user-images.githubusercontent.com/63627003/84122164-5c08c780-aa7b-11ea-8717-df4caea44019.PNG">

**Comment by ewilly1** [comment]
Sorry, here is full screen.
<img width="604" alt="config settings" src="https://user-images.githubusercontent.com/63627003/84122240-7c388680-aa7b-11ea-9e41-0116ef12d15e.PNG">

**Comment by RocketRobz** [comment]
Try deleting the file.

**Comment by ewilly1** [comment]
Ok

**Comment by ewilly1** [comment]
I'll just be a minute while I check if this helps.

**Comment by ewilly1** [comment]
Still having the same issue :(

**Comment by RocketRobz** [comment]
Please turn on logging, re-launch the game, and upload `NDSBTSRP` from the SD root.

**Comment by ewilly1** [comment]
How do I turn on relogging?

**Comment by RocketRobz** [comment]
Go into TWLMenu++ Settings, then switch to Games/Apps page.

**Comment by ewilly1** [comment]
Ok

**Comment by ewilly1** [comment]
<img width="241" alt="part 1" src="https://user-images.githubusercontent.com/63627003/84123631-6d52d380-aa7d-11ea-8553-cbc53a396042.PNG">
<img width="266" alt="part 2" src="https://user-images.githubusercontent.com/63627003/84123752-9d01db80-aa7d-11ea-9f18-223b6fe7bd81.PNG">

**Comment by RocketRobz** [comment]
How are you trying to save the games?

**Comment by ewilly1** [comment]
Pressing save game and than exiting twilight menu ++.

**Comment by RocketRobz** [comment]
> Pressing save game and than exiting twilight menu ++.

Did you wait for the saving to complete?

**Comment by ewilly1** [comment]
Yes

**Comment by RocketRobz** [comment]
Try checking the SD card for errors.

**Comment by ewilly1** [comment]
Just says "You don't need to scan this drive."

**Comment by ewilly1** [comment]
Should I try deleting twilight menu ++ and reinstalling it again?

**Comment by RocketRobz** [comment]
Yes.

**Comment by ewilly1** [comment]
Ok if the issue persists I will get back to you. Thanks for your help much appreciated.

**Comment by scrungusman** [comment]
when i opened my game on the twilight menu for the first time, i lost all of my progress. please tell me there is a way to fix this

**Comment by RocketRobz** [comment]
If the .sav files are in the same location as the .nds files, then move the .sav files to the `saves` folder, also in the .nds file location.

**Comment by RocketRobz** [comment]
No, I mean the .nds files of your games.

**Comment by scrungusman** [comment]
i couldnt find any .sav files at all, is that supposed to happen?

**Comment by RocketRobz** [comment]
Actually, yes.
If you started a game for the first time using TWLMenu++, a new .sav file is created, because one never existed in the first place, so there'd be no way for progress to be lost.

If you already have existing .sav files somewhere, then add them to the `saves` folder on the SD card, replacing the existing .sav file, provided it does exist.

**Comment by scrungusman** [comment]
so, twilight menu is like a factory reset essentially?

**Comment by scrungusman** [comment]
because i launched a game on it that i had played before and i went back to 0

**Comment by RocketRobz** [comment]
No, it does not delete any data.
If you've formatted your SD card which still had the save data, before installing TWLMenu++, then that's why the progress is lost.
Situations like this is why backups of your SD data is recommended.

**Comment by scrungusman** [comment]
i think the issue is that i did not use an sd card before i got TWLMenu++

**Comment by RocketRobz** [comment]
If you used a flashcard to play the games, then you need to copy them to the console's SD card.
If you used the original cartridges, then you need to dump the save data using GodMode9/GodMode9**i**.

**Comment by scrungusman** [comment]
save data from where?

**Comment by scrungusman** [comment]
the files/sd or the dsi itself?

**Comment by RocketRobz** [comment]
1. Which game did you try?
2. Where did you previously play the games off of?

**Comment by scrungusman** [comment]
1. pokemon platinum
2. the cartridge

**Comment by RocketRobz** [comment]
Then you need to use either GodMode9 (for 3DS) or GodMode9i (for DS(i)) to get the save data.
Follow this guide: https://wiki.ds-homebrew.com/godmode9i/#dumping-functionality

**Comment by scrungusman** [comment]
alr thank you, i will come back if anything happens

**Comment by scrungusman** [comment]
"select the drive in the drives list" on the dsi, or computer?

**Comment by RocketRobz** [comment]
> "select the drive in the drives list" on the dsi, or computer?

On the DSi.

**Comment by scrungusman** [comment]
where is the drives list?

**Comment by RocketRobz** [comment]
Let's move this to the Discord server: https://discord.gg/yD3spjv

**Comment by scrungusman** [comment]
alr, ive been looking for it, thanks

**Comment by spiritomb8** [comment]
Hi I'm having the same issue with a rom of platinum on the latest version of twilight menu++ on my 2DS.
Even after saving, upon booting up again, the game starts up like it was I just started. I checked the sd card, there IS a .sav file for the game with the save file name. is there something wrong? Should I get a different rom? Could you recommend a place to get a working rom? (the rom is from the reddit megathread and is the encrypted version btw)

**Comment by RocketRobz** [comment]
> Hi I'm having the same issue with a rom of platinum on the latest version of twilight menu++ on my 2DS. Even after saving, upon booting up again, the game starts up like it was I just started. I checked the sd card, there IS a .sav file for the game with the save file name. is there something wrong? Should I get a different rom? Could you recommend a place to get a working rom? (the rom is the encrypted version btw)

Try reformatting the SD card using this guide: https://dsi.cfw.guide/sd-card-setup.html
If the issue persists, then try another SD card.

**Comment by spiritomb8** [comment]
My sd card is the one that came with the system, I've been thinking of getting a 32gb sd. Should I backup the contents of my 4gb sd and add those to the 32gb one?

**Comment by RocketRobz** [comment]
> My sd card is the one that came with the system, I've been thinking of getting a 32gb sd. Should I backup the contents of my 4gb sd and add those to the 32gb one? (sorry, I know this question is a bit irrelivent)

Yes.

**Comment by spiritomb8** [comment]
thanks I'll try that! If the problem STILL persists. I'll comment again. If not, it worked and I am grateful for your help.
