### ISSUE TITLE
Widescreen won't turn off again.

### ISSUE THREAD

**Issue by Ecthelon** [DS-Homebrew/TWiLightMenu#1065]
Title. I tried it out but wasn't a big fan of how the game seemed stretched. 

Changing the setting in the TWiLightMenu back to 4:3 doesn't seem to do anything even after restarting the device. It remains widescreen.

**Comment by RocketRobz** [comment]
Delete `TwlBg.cxi` at `sd:/luma/sysmodules/`.

**Comment by Ecthelon** [comment]
Okay thanks that worked. So if I want to get it back again I have to select a filter in TWPatcher again?
