### ISSUE TITLE
YSMenu can't boot games

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/TWiLightMenu#1069]
For a majority of TWLMenu++ versions, after launching YSMenu, retail/commercial games won't boot.
If you switch to the R4 theme, then only a few games boot, such as Bangai-O Spirits.

**Comment by Epicpkmn11** [comment]
Was this fixed by a96292a168020d99f42197ef7845b48848c65859? Or is this a different problem?

**Comment by RocketRobz** [comment]
Yup, it's fixed.
