### ISSUE TITLE
3DS theme: game title is above the area

### ISSUE THREAD

**Issue by eku** [DS-Homebrew/TWiLightMenu#1070]
**Your console configuration:** N3DS XL
**TWiLight Menu++ Version:** d74004cf
**TWiLight Menu++ Theme:**  3DS

### Expected behaviour

Game title in area

### Actual behaviour

Game title above area (see screencopy)

### Steps to reproduce

1. Configure 3DS theme
2. Navigate to NDS overview
3. 

![IMG_20200613_133524](https://user-images.githubusercontent.com/418685/84568395-827e7980-ad7f-11ea-8624-8c00c921b2f7.jpg)

**Comment by eku** [comment]
Might be caused by #1026

**Comment by RocketRobz** [comment]
Can be fixed by download the latest theme .ini file from the repo.

**Comment by eku** [comment]
@RocketRobz wrote:
> Can be fixed by downloading the latest theme .ini file from the repo.

Manually or would it also be updated with the ```Universal Updater```?

**Comment by RocketRobz** [comment]
You'll have to update to the latest version manually.
TWiLight Menu++ Updater and Universal Updater currently cannot update TWiLight Menu++.
