### ISSUE TITLE
Download play not working on some games

### ISSUE THREAD

**Issue by Segadude23** [DS-Homebrew/TWiLightMenu#1071]
**Your console configuration:**  New 2DS XL with 11.13.0-45 and Luma 3DS
**TWiLight Menu++ Version:**  15.1.1 Release Version
**TWiLight Menu++ Theme:** 
DSi
### Expected behaviour

 Mario Kart multiplayer mode should be downloading on the other system perfectly.

### Actual behaviour

When another DS goes into the game room, it detects it ok and starts downloading it but never gets out of that stage. The host DS shows no bars instead of all 3 bars. I tried Mario Party DS and Mario Basketball 3v3 but those games are either glitched on the other DS or crash on the Nintendo logo

### Steps to reproduce

1.Play Mario Kart DS, Mario Party DS, or Mario 3v3
2.Go to Multiplayer (Simple setting for Mario Kart DS)
3.DS Mode download play on other 3DS or DS system

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, not a TWiLight Menu++ issue.
