### ISSUE TITLE
Please update nds bootloader to support local multiplayer using only 1 rom. I hate tjat you have to have 2 of them.

### ISSUE THREAD

**Issue by TailsBuddy0** [DS-Homebrew/TWiLightMenu#1077]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NightYoshi370** [comment]
Not a TWiLight issue.
Nds-bootstrap repo already has this labeled as cloneboot

**Comment by TailsBuddy0** [comment]
Cookbook?

**Comment by TailsBuddy0** [comment]
Cloneboot?

**Comment by Epicpkmn11** [comment]
Cloneboot is described here: https://nightyoshi370.github.io/modding/ds-index#cloneboot

The relevant issue is here: https://github.com/ahezard/nds-bootstrap/issues/553
