### ISSUE TITLE
Blank icons in akmenu menu

### ISSUE THREAD

**Issue by Dsseed** [DS-Homebrew/TWiLightMenu#1078]
Your console configuration:
NDSILL
TWiLight Menu++ Version:
v15.2.0
TWiLight Menu++ Theme:
WoodUI

Format the SD card, copy TWiLightMenuv15.2.0, boot to the default DSI theme, set to WoodUI theme, run the GB game, crash, after running the NDS game, restart the game icon is blank, you need to return to the previous menu to display correctly !

**Comment by chyyran** [comment]
Cannot reproduce in https://github.com/DS-Homebrew/TWiLightMenu/pull/1109, @Aeuko please join the Discord and ping @chyyran when you can.
