### ISSUE TITLE
OLD 2DS BLACK SCREEN AT twilight menu ++ BOOT

### ISSUE THREAD

**Issue by CRAWLER-V** [DS-Homebrew/TWiLightMenu#1087]
Hello, i have no way to make a log of twilight... but i try to explain myself better than i can:

i have Nintendo old 2DS with **sysFW 11.8.0-41E** and **B9S 1.3** and **Luma 3DS 10.1.1**.
I've installed for the very first time T**wilight Menu++ 15.2.0**
extracting from archive:

_nds folder
DSi&3DS - SD card users/_nds folder
DSi&3DS - SD card users/BOOT.NDS file
3DS - CFW users/ two .cia files + _nds folder

Boot up the console and install both cia files.
Launching twilight menu ++ remain black screen. all buttons do nothing. the only way for exiting is power off the console.

Any suggestion?

**Comment by NightYoshi370** [comment]
Let's continue this on the Discord server. We prefer using that for support.

**Comment by CRAWLER-V** [comment]
and which is the server name? 
thanks.

**Comment by NightYoshi370** [comment]
"DS(i) Mode Hacking!" and an invite can be found in the ReadME
