### ISSUE TITLE
After booting into widescreen once, it is stuck that way unless you manually delete TwlBg.cxi from the Luma sysmodules folder.

### ISSUE THREAD

**Issue by Filo97** [DS-Homebrew/TWiLightMenu#1094]
**Your console configuration:**  
New 3DS XL 11.13.0-45E, Luma3DS 10.1.3 
**TWiLight Menu++ Version:** 
62e1be25d6ab85b24ec93831af9064925000e758
**TWiLight Menu++ Theme:** 
DSi

### Expected behaviour

After setting the aspect ratio back to 4:3, it should go back to 4:3
### Actual behaviour

After setting the aspect ratio back to 4:3, it remains permanently 16:10 everywhere.
### Steps to reproduce

1. Follow the Widescreen tutorial on the GBATemp post.
2. Set the Aspect Ratio to 16:10 and boot a game.
3. Go back to any TWL title whatsoever. They will all now be stuck in Widescreen. Setting it back to 4:3 does nothing.

**Comment by RocketRobz** [comment]
Install the latest TWLMenu++ CIAs using FBI, and then delete `TwlBg.cxi` in `sd:/luma/sysmodules/`, and rename `TwlBg_bak.cxi` to `TwlBg.cxi`.

**Comment by Filo97** [comment]
I had done so in the past and it didn't fix anything. Now i've tried a full uninstall then reinstall, and it's now saying "Failed to backup custom TwlBg."

**Comment by Filo97** [comment]
After re-making both the TwlBg.cxi and Widescreen.cxi it backups properly and the Widescreen issue is gone. I have little clue what exactly fixed it, all I know is that I had uninstalled and reinstalled in the past and it didn't work then.
