### ISSUE TITLE
ds wireless play

### ISSUE THREAD

**Issue by idchahahaha** [DS-Homebrew/TWiLightMenu#1100]
ive had twilightmenu for 6 months now (updated it yesterday) but ive realized that whenever someones hosting a game (or im hosting a game) i cant play with them. the game does show up on ds wireless play but whenever i click on it it connects and it disconnects right after showing a warning that it couldnt connect. please fix this. i really want to be able to play with other people!

**Comment by RocketRobz** [comment]
What console are you using?

**Comment by idchahahaha** [comment]
im using a dsi

**Comment by idchahahaha** [comment]
i also have a 3ds but it has the same problem

**Comment by RocketRobz** [comment]
Anyways, this isn't a TWiLight Menu++ issue, but an nds-bootstrap issue.

**Comment by idchahahaha** [comment]
do you know how to fix it

**Comment by RocketRobz** [comment]
Unfortunately, I don't, since I don't know what caused this.

**Comment by idchahahaha** [comment]
okay thanks anyway!
