### ISSUE TITLE
Loads Directly into NDS ROM, Cannot Go to Menu

### ISSUE THREAD

**Issue by BNCianciolo** [DS-Homebrew/TWiLightMenu#1101]
Everytime I open Twilight, it goes straight to GTA. The L+R+Down+B doesn't work (I enabled game patching in Luma), but the L+R+Start+Select Combo does work. I updated Twilight today, but that didn't fix it. Also, I can only use the menu in GTA. After selecting New Game, I go to a black screen. Thanks in advance!

**Comment by RocketRobz** [comment]
Hold B(skipping the ROM)+SELECT to go into TWLMenu++ Settings, then turn off `Last played ROM`.

**Comment by BNCianciolo** [comment]
Thank you so much!
