### ISSUE TITLE
Hope to restore WoodUI theme as soon as possible！

### ISSUE THREAD

**Issue by Dsseed** [DS-Homebrew/TWiLightMenu#1104]
Unfortunately, WoodUI has been stopped. Let me talk about my experience,
Among the many themes, I think WoodUI is the best theme for people with more games,
There is no bells and whistles of other themes, very good user experience, hope to recover soon!

Thank you for your work!

By the way, remind that in TWiLightMenu_v14.2.0 WoodUI is perfect! But his name is Ak, and I hope that users who need it can use this version.

**Comment by mjosephdelrosario** [comment]
+1, please fix WoodUI.

**Comment by YourKalamity** [comment]
Akmenu was removed (for now) because it was very buggy

**Comment by chyyran** [comment]
Fixes for akmenu is being worked on here: https://github.com/DS-Homebrew/TWiLightMenu/pull/1109

In need of testers, so please join the Discord if you're interested in helping out.

**Comment by chyyran** [comment]
This is blocking on porting FatFs/libelm due to critical deficiencies in libfat. ETA next week to late July.

**Comment by xpirad** [comment]
@chyyran Is there any update on this issue?

**Comment by chyyran** [comment]
No. There are issues with the current iteration of libslim. I have a theory on how to fix it but lack time. See https://github.com/DS-Homebrew/libslim for updates.

**Comment by DraconicNEO** [comment]
I hope this isn't abandoned, it would be nice to one day be able to use akmenu once again.

**Comment by chyyran** [comment]
I was the one who implemented the theme and it should be on me to maintain it, but I've been very busy for the past few years and never managed to bring this back successfully despite a few efforts once or twice a year.

The new SD driver is a bit of hope though, so maybe I'll take a look at that in a month or so. I can't promise anything myself though. I had (and still remember) some ideas I had to fix it without replacing the FAT driver though, so maybe I'll take a look at doing that instead.

**Comment by RocketRobz** [comment]
The theme is being re-written in the [aktheme-remade](https://github.com/DS-Homebrew/TWiLightMenu/tree/aktheme-remade) branch.

**Comment by RocketRobz** [comment]
Wood UI theme will return in the next version!
