### ISSUE TITLE
(IDEA) WIFI SOLUTION TO MANY THINGS

### ISSUE THREAD

**Issue by ByBaltron2005** [DS-Homebrew/TWiLightMenu#1105]
My idea is to add wifi because? they will say well here are some reasons UPDATE SYSTEM You launch an update and automatically if the ds is connected to wifi a notification will come out that a system update has come out this will leave behind it is cumbersome job of passing folders also you can put some option to add a video player and install it through wifi BROWSER AND TUBE WE WILL FINALLY HAVE A WORTHY BROWSER AND PLAY VIDEOS This will help since the 3ds will not be the only one capable of running YouTube videos. With the Wi-Fi connection, we will be able to enter web pages such as Facebook, Instagram, etc., I hope you accept the idea.

**Comment by NightYoshi370** [comment]
1) We're waiting for Nintendo DSi WiFi to be supported so that users do not need to weaken security
2) TWiLight will not get a web browser, because that's not TWiLights job
3) I don't even think the Nintendo DSi is even able to handle HTML5, CSS3 and JavaScript. Even the Old 3DS can't handle it.
