### ISSUE TITLE
TWiLightMenu++ upper screen shows wide since start up

### ISSUE THREAD

**Issue by Zkaven183** [DS-Homebrew/TWiLightMenu#1108]
**Your console configuration:** New 3DS ver. 11.13.0 with Luma 10.1.3
**TWiLight Menu++ Version:** v15.3.0
**TWiLight Menu++ Theme:** DSi, 3DS, R4, Saturn, Homebrew Launcher

### Expected behaviour

When accesing to the menu, the upper screen should shows at 4:3 aspect ratio instead of the 16:10 thats is programed only for some DS Games

### Actual behaviour

At the start up of the Menu, the upper screen shows for an instant, some vertical lines of zeros (0) at the right side of the screen before it turn out white, and then it appear the menu at full widescreen. This happens even if the Screen Aspect Ratio option its at 4:3 (Fullscreen). It can only be changed or disabled only by delete or rename the .cxi file inside **luma/sysmodules** folder

**Comment by RocketRobz** [comment]
Please re-follow the widescreen steps, as well as the preparation steps.

**Comment by Zkaven183** [comment]
Thanks for the help, the problem has been solved.
