### ISSUE TITLE
Unable to run gbarunner2, snes emulator, and genesis emulator

### ISSUE THREAD

**Issue by UnleashedFurai** [DS-Homebrew/TWiLightMenu#1111]
When I try to launch gbarunner2, a snes rom, or a genesis rom, it says:
Start failed. Error 1
nds-bootstrap (Release) not found.
Press B to return. 
![IMG_20200706_121150](https://user-images.githubusercontent.com/67919489/86620416-e7458200-bf81-11ea-8319-1f92ce96b8d6.jpg)

**Comment by NightYoshi370** [comment]
Download the homebrew version of nds-bootstrap.
By the way, for support, please join our discord server.
