### ISSUE TITLE
Does the Sega Saturn have background music?

### ISSUE THREAD

**Issue by Jerdo32** [DS-Homebrew/TWiLightMenu#1113]
**Your console configuration:**  It's a OLD 2DS version 11.13.0-45U with Luma3DS version 10.1.3
**TWiLight Menu++ Version:**  v15.3.0
**TWiLight Menu++ Theme:**  SEGA Saturn

### Expected behaviour

 Play a background music while selecting a game (according to what's new on that version)

### Actual behaviour

 It remains silent, except for sound effects.

### Steps to reproduce

1. Just select the SEGA Saturn theme in Settings.
2. Choose any Theme Music in the settings.

**Comment by RocketRobz** [comment]
The Saturn theme does not play any BGM.
