### ISSUE TITLE
The lose of game safe file

### ISSUE THREAD

**Issue by Hamateus** [DS-Homebrew/TWiLightMenu#1114]
When i take out the sd card "to do anything" and put it in, i lose the games save files.

**Comment by RocketRobz** [comment]
When did you take out the SD card?

**Comment by Hamateus** [comment]
I think like 3 or 4 versions before.
I want to know if i update it will be fixed.

**Comment by RocketRobz** [comment]
No, I mean we're you playing a game, or we're you in the TWLMenu++ ROM list?

**Comment by Hamateus** [comment]
In the TWLMenu++ ROM list

**Comment by RocketRobz** [comment]
This doesn't cause save data loss though.
I've tried it, and my saves are intact.

**Comment by RocketRobz** [comment]
Also, whether it'll fix your issue or not, you should update.

**Comment by Hamateus** [comment]
Ok, thanks for the help, also i love your creation i am so nostalgic with it, thanks
