### ISSUE TITLE
Remove Deleting

### ISSUE THREAD

**Issue by NightYoshi370** [DS-Homebrew/TWiLightMenu#1115]
**Is your feature request related to a problem? Please describe.**
Heavy SD card operations should not be done for a launcher. Let an SD card manager (GodMode9i) handle that instead. Plus, with chyyran's new commits, deleting has been removed from the Wood UI theme

**Describe the solution you'd like**
Remove the option to delete files

**Describe alternatives you've considered**
Keeping it, and then asking chyyran to reimplement it in Wood UI. I disagree though

**Additional context**
The setting for it would get removed too.

**Comment by eku** [comment]
When deleting a ROM I would also expect that box art, cheats, save games etc. are also deleted, so everything that belongs to it.

**Comment by NightYoshi370** [comment]
Oh, this is talking about removing the option outright. It doesn't fit within the scope of TWiLight Menu++

**Comment by eku** [comment]
> It doesn't fit within the scope of TWiLight Menu++

USB Loader GX for Wii is also just a loader but does exactly what I wrote. But the user can choose to delete only the ROM or everything else that belongs to it. So I would see that already in the scope of TWL-Menu++.

**Comment by NightYoshi370** [comment]
Just because another loader does it doesn't mean it fits here. There's also the fact that including said deletion code has led to many issues where people accidentally deleted the ROMs, the fact that the DS is way too limited to do any file management alongside all these graphics and the fact that it's inconsistent.
Besides, there's GM9i for this purpose

**Comment by Lv44EnderShaman** [comment]
My two cents as a frequent user of TWL++ across all three systems is that the delete function should stay. User agency is and should be paramount, first and foremost. Just because someone else might not realize the functionality's purpose in the first place is no reason to remove it when there are others who do understand how it works.

**Comment by urmum-69** [comment]
I personally agree with nightscript
gm9i handles file management much better, the function is really redundant

**Comment by Lv44EnderShaman** [comment]
Again, and I will say this implicitly, user agency is important. TwilightMenu++ is not just a launcher, it is a drop-in replacement for the DS/DSi's System Menu. It even specifically states this on the front page of the Git repository. Removing the ability to delete games from TWLM++ may make it more in line with the stock System Menus, but it removes user agency as a result, and I find myself disagreeing on principle with the removal of features that enhance user agency. There may be a portion of the user base that doesn't find the ability to hide and delete files all that useful, but by inference, there can be stated to be just as many who do use this feature.

If it is difficult to use or understand how to use a feature in an application by the majority, then that is not a failing of the feature, nor the application. That is a failure of the developer on their part to properly explain the usage of that feature and educate their user base effectively. The solution to these situations is never to remove a feature outright; that's like putting an adhesive bandage on a wound that needs proper dressing.

**Comment by urmum-69** [comment]
Well, how exactly should the user base be "educated", be more constructive than that
The option is pretty self explanatory, yet what nightscript says can and does happen (accidentally deleting roms)

You could also argue that there could be more people who would be better off without the feature, potentially people who have younger kids using TWiLight Menu++ accidentally deleting their roms, which I think is even more plausible than "I want to delete my roms just because". Good luck "educating" them.
For basic file management on the console, godmode9i is much more suited, and can also be hidden within TWiLight Menu++ so no one can delete files by accident.

Even if there was a large red """BRICK ME""" button, someone would still click it.

**Comment by chyyran** [comment]
My view is that TWiLight Menu is not suited to be a 'power user' tool like GodMode 9i is where user agency should be at the forefront. Instead, user friendliness is much more important given the target audience. Despite being a 'locked down' system there is a reason why iOS has a reputation for being easy to learn and use. 

We aren't taking away any agency, you can just as easily pop into GodMode 9i and delete files that way should you so wish. Avoiding accidental user error is much more important in a widely used, non-power user application like TWiLightMenu, especially given the support burden when users accidentally delete their files. Not to mention that fewer features = less bugs = less maintenance burden. 

It's much easier to teach someone to do something (i.e. use GodMode 9i) than to _not_ do something (i.e. don't accidentally press the delete button in TWiLightMenu). Should the use case be necessary there are safer ways to achieve the same goals. 

> If it is difficult to use or understand how to use a feature in an application by the majority, then that is not a failing of the feature, nor the application. 

I disagree. If an application is aimed at the 'uneducated' majority, and it has a feature that is potentially dangerous if someone who is 'not educated' uses the application, that is definitely a failure of the application. That is why text-based terminals are not the predominant user interface in modern computing, but graphical, widget based interfaces are; this is a failure of text-based UIs when presented to the average user. On the flip side, for advanced use cases, it is a failure of graphical user interfaces to present such power in a user-friendly manner, but do notice that the target user for each of these use cases are different. I would argue that TWiLightMenu is aimed at lesser informed user and dangerous features like file deletion should be removed and segregated into more powerful tools like GodMode 9i.

**Comment by RocketRobz** [comment]
After reading all of this, and considering that TWLMenu++ can be used as a DSi Menu replacement (which has a Settings app that can delete DSiWare), I'll just keep ROM deleting.
There's already an option to disable ROM deletion, if the user wants.

**Comment by NightYoshi370** [comment]
Then we should add it back in the upcoming PR in regards to the Acekard theme, to make it all consistent. (@chyyran)

**Comment by ArtificialNight** [comment]
Deletion already is bound to "X", which is a button that is very unlikely to be spammed, especially when trying to get through text, where "A" and "B" would be more common, and upon opening the delete/hide menu there's a delay where no inputs will be accepted for a short time, once again combating the "oops pressed the wrong button" scenario. I'll be honest and admit I didn't read any use guides before using the Twilight Menu, but at the same time I have never accidentally hidden or deleted anything and have had no issue using the software.
