### ISSUE TITLE
No funciona twilight menu en mi dsi xl

### ISSUE THREAD

**Issue by Bakalokka777** [DS-Homebrew/TWiLightMenu#1116]
Tengo una Nintendo DSi XL versión 1.4.5 USA con  2 juegos prinstalados con unlaunch que use para instalar Twilight Menu ++. La versión de Twilight menu es v15. 1.1. Lo que debería pasar es que al instalar Unlaunch, y meterme a opciones y a asignar los botones me debería aparecer la opción de twilight menu y al 
arrancarlo debería funcionar, pero al entrar a unlaunch no aparece la opción de elegir twilight y cuandoe meto a twilight menu desde la cámara, se congela todo.
 1.Los pasos que hice fue descargar twilight
2.Meterme a la cámara de la nintendo dsi
3.Meterme en la sd
4.Me envía a un menú y le doy en Unlaunch
5.Me lleva a unlaunch y apretó install now
6.Despues espero a que instale
7.Me voy a power down
8.Prendo la consola
9.Me voy a options
10.Me meto en "no button" 
11. No me aparece Twilight menu ++

**Comment by NightYoshi370** [comment]
You didn't copy it correctly. Also, please keep support related questions to the Discord server, preferably in English
