### ISSUE TITLE
I just discovered a system called wiimmfi that allows you to connect to games through the Nintendo CFW just by making some adjustments in the dns I wonder if they can put wifi for this type of thing here I leave the link I hope you do I am eager to play games in line as well as many more people

### ISSUE THREAD

**Issue by ByBaltron2005** [DS-Homebrew/TWiLightMenu#1117]
I just discovered a system called wiimmfi that allows you to connect to games through the Nintendo CFW just by making some adjustments in the dns I wonder if they can put wifi for this type of thing here I leave the link I hope you do I am eager to play games in line as well as many more people

Link https://github.com/KaeruTeam/nds-constraint

**Comment by NightYoshi370** [comment]
That's not up to TWiLight Menu
Also, please keep titles short

**Comment by ByBaltron2005** [comment]
But ... Can it be done?

**Comment by NightYoshi370** [comment]
I am not sure what you mean. Your original post wasn't worded the best.

**Comment by ByBaltron2005** [comment]
But ... Can it be done?

**Comment by ByBaltron2005** [comment]
It is a system they created, it works like this, you go to your game example Mario Kart you go to wifi configure wfc you connect to the wifi and change the dns and so you can play online again, well I ask if that can be done with tw

**Comment by NightYoshi370** [comment]
Again, this is something that is done in app, something that TWiLight Menu++ doesn't handle. It's just a graphical user interface.
Also, couldn't you just go into the game itself and change the DNS settings? We don't want to force people to use a specific DNS setting

**Comment by ByBaltron2005** [comment]
It is a system they created, it works like this, you go to your game example Mario Kart you go to wifi configure wfc you connect to the wifi and change the dns and so you can play online again, well I ask if that can be done with tw

**Comment by ByBaltron2005** [comment]
I'm not saying to change one dns for everyone, I'm just asking if tw can have a stable wifi connection
