### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Hamateus** [DS-Homebrew/TWiLightMenu#1120]
Sorry for using bug issue, i dont know other way to ask.
I got a problem, when i change to godmode or update something in the new 3ds, i lost some titles, a friend told me that the data may be corrupted, and i am asking you if you could help me with that, whenever you can,(theres a lot of memory i cant erease).

**Comment by RocketRobz** [comment]
Sounds like your SD card is dying.
Try another SD card.
After, you can re-download your lost titles using the Nintendo eShop.
