### ISSUE TITLE
An Error has occoured

### ISSUE THREAD

**Issue by Greenphx9** [DS-Homebrew/TWiLightMenu#1122]
**Your console configuration:** New 3DS XL with LumaCFW 
**TWiLight Menu++ Version:** 15.3.0 
**TWiLight Menu++ Theme:** 3DS

### Expected behaviour
Twilight Menu launches and I can play games.

### Actual behaviour
I get a black screen saying that an error has occurred and I have to hold the power button down.

### Steps to reproduce

1. Install TwilightMenu, using the wiki instructions.
2. Try and launch TwilightMenu
3. Error happens
Also happens with TwilightMenu Updater.

**Comment by RocketRobz** [comment]
Please explain how this happens.

**Comment by Greenphx9** [comment]
Yeah I accidently posted it without any steps, just edited it

**Comment by RocketRobz** [comment]
Let's bring this [here](https://discord.gg/yD3spjv), as this isn't the place for support.
