### ISSUE TITLE
Cartridge game touchscreen + sound not working

### ISSUE THREAD

**Issue by matteohs21** [DS-Homebrew/TWiLightMenu#1124]
**Your console configuration:** DSi with Unlaunch & HiyaCFW 
**TWiLight Menu++ Version:** v15.3.0 
**TWiLight Menu++ Theme:** DSi Theme (Tried them all, none made it work) 

### Expected behaviour

Both touch screen and sound in the game (cartdrige) should work, but they don't.
Affected game: Pokemon Black 2 - haven't tried with any other.
I also tried tweaking the TWMenu but nothing worked.

### Steps to reproduce

1. Boot into twmenu.
2. Switch to any menu.
3. Start game.

**Comment by takeshineale128** [comment]
have the same issue

**Comment by floppyD** [comment]
It's related to the "Direct" Slot-1 launch method, I have the same issue with my Acekard 2i and Pokemon Soul Silver.

**Comment by RocketRobz** [comment]
Fixed in cdc670c7
