### ISSUE TITLE
Add shorthand PictoChat and DLPlay icons to top of 3DS theme (if found)

### ISSUE THREAD

**Issue by unresolvedsymbol** [DS-Homebrew/TWiLightMenu#1126]

**Comment by Haxorzz** [comment]
Ive got the picto chat cia does that help at all?

**Comment by NightYoshi370** [comment]
The only reason why that exists in the DS Classic Menu is because that's part of the menu itself. Otherwise, they have no coorolation to TWiLight Menu++, and copying the .nds file in the menu itself would work fine.

That's why I disagree with this change, but it's up to Robz

**Comment by INFINITE-PIKA** [comment]
I'm pretty sure that I have both the download play and pictochat cias! So if you need my help I'll provide

**Comment by unresolvedsymbol** [comment]
> I'm pretty sure that I have both the download play and pictochat cias! So if you need my help I'll provide

Hi, thanks but that's not needed. This cosmetic feature request is about adding a small pictochat and dlp icon to either the very topmost row of the 3DS theme or perhaps the select menu on other dsimemu themes.

**Comment by unresolvedsymbol** [comment]
> The only reason why that exists in the DS Classic Menu is because that's part of the menu itself. Otherwise, they have no coorolation to TWiLight Menu++, and copying the .nds file in the menu itself would work fine.
> 
> That's why I disagree with this change, but it's up to Robz

@NightYoshi370 Very late reply but this is true; However since there's already a shortcut to the DSi system settings (in the main settings) and cartridge launcher, I think adding these two would contribute to making TWiLightMenu a more complete DSi menu replacement. Also these two system apps can be mixed in with your games, but they don't blend in well.

**Comment by INFINITE-PIKA** [comment]
On a side note, do you think it'd be possible to dump the SELECT/DS menu to a cia/nds file? I assume not, but I think it'd be cool if I could do it myself somehow.

**Comment by unresolvedsymbol** [comment]
Take a look in the _nds/TWiLightMenu folder, those srldr files are also known as nds. Can't remember which one contains the classic DS menu but one should be cmiiw.

**Comment by RocketRobz** [comment]
Implemented by 878d79dde
