### ISSUE TITLE
Booting games from flashcart using TWiLightMenu and B4DS results in white screen

### ISSUE THREAD

**Issue by SwareJonge** [DS-Homebrew/TWiLightMenu#1128]
**Your console configuration:**  DS Lite With R4i SDHC RTS (Firmware 2.8a)
**TWiLight Menu++ Version:**  v15.2.0
**TWiLight Menu++ Theme:** R4

### Expected behaviour

 Game should boot just like it does on a 3DS or DSi using TWiLightMenu

### Actual behaviour

 After selecting the game, the console freezes and both screens are white

### Steps to reproduce

1. Boot up TwiLightMenu via your flashcart
2. Start a NDS game

**Comment by NightYoshi370** [comment]
B4DS is at fault, not TWiLight Menu++. Please report this at the nds-bootstrap repository, including *which* game. Quite frankly, you haven't given us much info at all

**Comment by SwareJonge** [comment]
It didn't matter what game so that's why i didn't mention it
