### ISSUE TITLE
Use newer SNEmulDS on compatible devices

### ISSUE THREAD

**Issue by NightScript370** [DS-Homebrew/TWiLightMenu#1135]
**Is your feature request related to a problem? Please describe.**
The current SNEmulDS packed in with TWiLight Menu++ is incompatible with most SNES titles and there is a newer version out there, one with ARGV support. However, due to the DSi incompatibility, we do not use it.

**Describe the solution you'd like**
Use the new SNEmulDS on compatible devices (such as a flashcart). It's fine if we have a few builds for different platform (it's like nesDS, where we have one for flashcarts and one for DSi)

**Describe alternatives you've considered**
- Fixing nds-bootstrap for new SNEmulDS
- Fixing SNEmulDS for either native DSi compatibility or nds-bootstrap

**Additional context**
The latest builds will always be at Coto's BitBucket.

**Comment by lifehackerhansol** [comment]
Since this issue's creation, SNEmulDS was updated to support DSi Mode. I do not know how stable this is, so I think more testing is appreciated before making the switch.

**Comment by spellboundtriangle** [comment]
I don't think it's quite ready, touch doesn't seem to work on consoles (meaning you can't enable/disable saving anyways) and sound doesn't work either unless you use nds-bootstrap (and it's a little broken if you do). In my experience, anyways.
It also can't seem to load my Super Metroid ROM, but that may be a different issue?

**Comment by lifehackerhansol** [comment]
Implemented in v24.0.0.
