### ISSUE TITLE
The TWiLight Menu++ icon is static

### ISSUE THREAD

**Issue by Nicolas2k8** [DS-Homebrew/TWiLightMenu#1139]
**Your console configuration:** New 3DS XL ver: 11.13.0 with Luma3DS ver: 10.2  
**TWiLight Menu++ Version:** v16.0.0 
**TWiLight Menu++ Theme:** none

### Steps to reproduce

1. Install TWiLight Menu via updater.
2. See if it animates

**Comment by RocketRobz** [comment]
Unfortunately, with the current tools used, this is not possible at the moment.

**Comment by Nicolas2k8** [comment]
ok. that stinks. :/ plz let me know when its possible.

**Comment by sandwichwater** [comment]
sorry to dig up a dead issue , but im still having this issue . just updated everything today thinking that would fix it but its still a static icon , very odd issue and barely anything on the internet about it

**Comment by RocketRobz** [comment]
Delete TWiLight Menu++ from System Settings, then install it again.
