### ISSUE TITLE
Add a clang-format style to the project

### ISSUE THREAD

**Issue by Epicpkmn11** [DS-Homebrew/TWiLightMenu#1140]
**Is your feature request related to a problem? Please describe.**
- Not an in app problem, but the code formatting in TWiLight is incredibly inconsistent... [2 space](https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_dsimenutheme/arm9/source/cheat.cpp), [4 space](https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_dsimenutheme/arm9/source/common/nitrofs.c), [tabs](https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_dsimenutheme/arm9/source/ndsheaderbanner.cpp) indentation ([some a mix](https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_dsimenutheme/arm9/source/fileCopy.cpp)). Sometimes breaking [before brackets](https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_dsimenutheme/arm9/source/language.cpp#L76), sometimes [after](https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_dsimenutheme/arm9/source/language.cpp#L27), etc. It makes the code harder to read... (all of these just grabbed from a few seconds of looking in the dsimenu theme ;P)

**Describe the solution you'd like**
- Add a .clang-format file with a set style to use for the whole project, and format it by that. If there's another program that could work too, but I've used clang-format before.
- I just added clang-formatting to [pkmn-chest](https://github.com/Universal-Team/pkmn-chest/blob/master/arm9/.clang-format), so if y'all like my style it could be based on that, otherwise I found [this site](https://zed0.co.uk/clang-format-configurator/) helpful in creating the style
  - My main preferences roughly sorted by how strongly I feel are:
    - Indent size & tab width 4
    - Tabs for indentation
    - Pointer alignment right
    - No breaks before brackets
    - Column limit 120
    - Regroup include blocks
    - Never space before parenthesis
    - The rest of my pkmn-chest settings
  - But I'm making this issue instead of PR'ing directly since I know code formatting is one of the most subjective things ever so these are just my preferences, I'd like to know what everyone else thinks, then either I can PR it or if Robz or someone just wants to do it they can.

**Describe alternatives you've considered**
- Dunno, another code fomatter? Are there others?

**Additional context**
- *just look at this ;P*
![スクリーンショット 2020-07-29 20 48 26](https://user-images.githubusercontent.com/41608708/88871191-e0a2d700-d1dc-11ea-8b70-02a58aabb38c.png)

<details><summary>annotated</summary>

![スクリーンショット 2020-07-29 20 48 26](https://user-images.githubusercontent.com/41608708/88872544-05e51480-d1e0-11ea-87b9-93291a68127c.png)

</details>

**Comment by eku** [comment]
What about GNU indent combined with a Git pre commit hook for formatting the file?

**Comment by lifehackerhansol** [comment]
I think pkmn-chest's formatting is fine as it is. We should just add that.

It's been 2 years and I think we sorely need this.

**Comment by Epicpkmn11** [comment]
Closing as I've changed my opinion on chang-format since I opened this. I think more consistency is good, but clang-format just doesn't do a very good job imo.
