### ISSUE TITLE
Guru Mediation Error when scrolling through settings

### ISSUE THREAD

**Issue by KH1501** [DS-Homebrew/TWiLightMenu#1141]
**Your console configuration:** old 2ds Luma CFW ver.11.2 
**TWiLight Menu++ Version:** 16.0.0
**TWiLight Menu++ Theme:** Dsi

### Expected behaviour

Should be able to scroll down to reach more settings in TWL Settings menu
### Actual behaviour

Scrolls then crashes while scrolling down with an "Guru Mediation Error! data abort!" crash debug screen
### Steps to reproduce

1.open TWL settings
2.Scroll down in an Category like Gui settings 
3.crash
![IMG_20200730_202910 1](https://user-images.githubusercontent.com/46072236/88960164-64bf9200-d2a3-11ea-8e1b-9f73141c7b0b.jpg)
my New 2ds Xl also crashes when doing this.
It is identically configured except it's using the homebrew theme
Here's it's crash screen
![IMG_20200730_200520 1](https://user-images.githubusercontent.com/46072236/88960527-f202e680-d2a3-11ea-8e71-8d7a266fd0b6.jpg)

**Comment by Epicpkmn11** [comment]
This is because of a bug with printing text off screen happening in German and Polish on the latest release. It has been fixed in the latest [nighlies](https://github.com/TWLBot/Builds) or you can temporarily change your language until the next release

**Comment by Dhalian** [comment]
This problem also occurs when the TWiLight Menu is set to French language.

**Comment by NightYoshi370** [comment]
Since new release fixes this, I'm closing this issue
