### ISSUE TITLE
Problems with TwilightMenu++ Handling Switching from 16:10 to 4:3 in DS Games

### ISSUE THREAD

**Issue by Drazini** [DS-Homebrew/TWiLightMenu#1142]
### System Information

**New 3DS with Luma3DS - System Firmware Version:** 11.13.0-45U | Luma Version: 10.2
**TWiLight Menu++ Version:** v16.0.0 (Release)
**TwilightMenu Theme:** DSi Dark

### Expected behavior

When I Open a game set to use the 16:10 aspect ratio, the game will boot in 16:10, then when i close it, and open another ds game which is either outside twilightmenu, or in twilightmenu and set to use the 4:3 aspect ratio, that game will use a 4:3 aspect ratio. 

### Actual behavior

Once a game set to use a 16:10 aspect ratio is launched, once closing the game, and launching any other DS game within or outside of twilight menu, regardless of settings, it will be in a 16:10 ratio instead of a 4:3 one. This will Persist in all DS Games, including the TWiLight Menu Interface, Until TwlBg.cxi is manually deleted in sd:/luma/sysmodules

### Steps to reproduce

1.Set a game to open in 16:10 aspect ratio within the game specific settings
2.Open the game
3.Close the game at any point
4.Open any other DS game on the 3ds system
5.It will be using the 16:10 ratio instead of 4:3 (this happens for twilight menu, any game launched by twilight menu that is set to specifically use a 4:3 ratio, as well as all non-twilight menu games on the 3ds system)
6. What happens is Twilightmenu makes a Twlbg.cxi in the sd:/luma/sysmodules directory when a game with 16:10 enabled is opened. It should be deleted at a point, and manually deleting it after the game is closed will make things go back to 4:3, however once another game set to be 16:10 is opened the file will be recreated, and have to be manually deleted again. Twilightmenu does not delete/revert this file when the game is closed, and thus every ds title on the system will be stuck in widescreen until it is manually deleted.

### Additional Information

To get widescreen working I followed the steps on the GBATemp page, current as of 7/30/2020
To get twilightmenu I installed it with the updater, then manually installed the latest .cia files in FBI, before taking the steps to get widescreen.

**Comment by RocketRobz** [comment]
Delete the TWiLight Menu++ titles in FBI, then install the latest CIAs.

**Comment by Drazini** [comment]
I deleted the 2 Twilightmenu Titles, then got and installed the 2 newest cias from the releases. 
The problem persists

**Comment by RocketRobz** [comment]
Apparently, you aren't using the latest CIAs, or else the problem would've been solved.

**Comment by Drazini** [comment]
I downloaded them minutes ago and installed the 2 in the from the 16.0.0 release's TWiLightMenu.7z\3DS - CFW users\

**Comment by RocketRobz** [comment]
Does your SD card have an EmuNAND?

**Comment by Drazini** [comment]
no

**Comment by RocketRobz** [comment]
So after deleting `TwlBg.cxi`, did you make a new one using TWPatch?

**Comment by Drazini** [comment]
It may be worth noting when the issue was a problem, I had the overall twilightmenu settings aspect ratio set to 4:3, and the game specific settings set to 16:10
I am trying to see right now if just having 16:10 in settings and no game specific settings will give me the same issue

yes, I made a new one with TWPatch after deleting the old one.

**Comment by Drazini** [comment]
I'm troubleshooting another thing right now trying to get the result of what I mentioned above, when I try to open a game with the overall twilightmenu settings set to 16:10, then open a game without a aspect ratio set in its game specific settings, i get "could not backup twlbg.cfg" and the game boots in 4:3

**Comment by Drazini** [comment]
manually deleted twlbg.cfg and twlbg_backup.cfg, currently remaking twlbg.cfg in twlpatch to see if that fixes the problem

**Comment by Drazini** [comment]
that fixed the "failed to backup custom twlbg.cxi" problem, and the game now boots in 16:10. and this quite is interesting: 
16:10 DID NOT PERSIST
the game booted in 16:10, but once i closed the game and opened twligthtmenu there was no problem.
now im going to mess with the game specific settings and see if i am able to have 4:3 and 16:10 in the game settings without causing the issue, when the master twilightmenu setting is 16:10

**Comment by Drazini** [comment]
After messing with settings, i concluded that this bug is only present when the master twilightmenu setting is at 4:3, and a game specific setting is set to 16:10
when the master twilightmenu setting is 16:10
a game with its game specific setting set to 4:3 will launch in 4:3 as intended, 
a game with its game specific setting to "default will launch in 16:10 as intended, without causing the "16:10 persisting" issue
and a game with its game specific setting at 16:10 caused twilightmenu to hang on the white screen after clicking the game (I believe when trying to make a backup of twlbg.cxi although I'm not sure)

conclusion: the master twilight setting at 4:3, as the game specific setting at 16:10 is what causes the issue, other configurations do not cause the problem. (although the 16:10 game specific configuration while master settings are also 16:10 might cause a different issue(?))

**Comment by bfoos** [comment]
Confirmed. 

**System Information**

**New 3DS with Luma3DS - System Firmware Version:** 11.13.0-45U | Luma Version: 10.2
**TWiLight Menu++ Version:** v16.1.0 (Release)
**TwilightMenu Theme:** DSi Dark

If "Screen Aspect Ratio" in "Games and Apps settings" isn't set to 16:10 (Wide), after launching any game in widescreen, widescreen will persist in the menu and all subsequent NDS titles will be launched in 16:10, regardless of per game aspect ratio settings. Deleting the TwilightMenu++ titles and reinstalling the .cia's doesn't remedy it. Deleting TwlBg.cxi restores 4:3, as does disabling "Enable loading external FIRMs and modules in Luma Config.

**Comment by ccfman2004** [comment]
It seems that TWiLightMenu++ isn't deleting TwlBG.cxi or restoring the backup one.

**Comment by RocketRobz** [comment]
Starting with 277230e4, widescreen will be handled differently.
