### ISSUE TITLE
GPU Scaling (health hazard!)

### ISSUE THREAD

**Issue by Aqee1** [DS-Homebrew/TWiLightMenu#1148]
I'm widescreen patching my 2ds and the instructions tell me to enable gpu scaling but next to gpu scaling on my 2ds it says (health hazard!) what does this mean? Will it harm my 2DS or something? Sorry this is a question instead of an issue.

**Comment by RocketRobz** [comment]
Health hazard means your eyes may hurt, but this seems to only apply to certain users.
