### ISSUE TITLE
Freeze in Pokemon Soul Silver

### ISSUE THREAD

**Issue by AlejqueGB** [DS-Homebrew/TWiLightMenu#1152]
Hello, I am having a failure with my pokemon soul silver rom and that is that in the middle of the game there is some frozen loading screen and I have to close it and lose all my progress, I would appreciate if you could give me any solution, thanks

**Comment by RocketRobz** [comment]
1. This is an nds-bootstrap issue.
2. There is currently no fix for this. You should save often.

**Comment by AlejqueGB** [comment]
Is it possible that in future versions this will be solved ???

**Comment by RocketRobz** [comment]
Yes, it's possible.

**Comment by AlejqueGB** [comment]
Thank you
