### ISSUE TITLE
Sound glitching. 

### ISSUE THREAD

**Issue by flowergard1** [DS-Homebrew/TWiLightMenu#1154]
"Crackling" sound during RocketRobz intro. This happens at random. 
Sometimes it sounds as it should, other times not. Once, after the sound glitched, the menu graphics also got corrupt. 

Ds games work without issues after booting, despite glitches.

My setup:

New 3ds xl

System firmware 11.13.0-45

Boot9strap 1.3

Luma3ds 10.2

64gb memory card

TWiLight Menu++  v16.1.0 

"Save FAT table cache" is disabled, and always has been.

**Comment by Jonatan6** [comment]
This seems to happen on my DSi with the newest version as well.

**Comment by RocketRobz** [comment]
Seems to be fixed in later versions.
