### ISSUE TITLE
Gameboy Color and R4 themes missing accents

### ISSUE THREAD

**Issue by UltraSyko** [DS-Homebrew/TWiLightMenu#1155]
**New 3DS XL with Luma3DS** (Latest firmware)
**TWiLight Menu++ Version: 16.1.0** Nightly 201434d -->
**TWiLight Menu++ Theme:** Gameboy Color

### Expected behaviour

See **Pokémon** on my rom list

### Actual behaviour

Displayed as **Pok mon**
[](https://cdn.discordapp.com/attachments/262131974498418689/740965876555317319/20200806_121329.jpg)
### Steps to reproduce

1.Select Gameboy Color Theme
2.Have a rom named with an accent

**Comment by Epicpkmn11** [comment]
The applies to the R4 theme as well btw, the text rendering for them needs to be rewritten... I'll probably do that at some point soon

**Comment by NightScript370** [comment]
Didnt the font rendering system of these themes switch to the way the DS Classic Menu renders its text? In that case, shouldnt it be fixed already?

**Comment by Epicpkmn11** [comment]
Not yes, I've been meaning to but the R4 theme is a bit trickier than the DS classic menu so haven't gotten around to it yet
