### ISSUE TITLE
Failed to backup TwlBG

### ISSUE THREAD

**Issue by ccfman2004** [DS-Homebrew/TWiLightMenu#1158]
**Your console configuration:** New 2DS XL Luma3DS 11.3.0-45U 
**TWiLight Menu++ Version:** 16.1.0
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

No error message

### Actual behaviour

When I load a DS game with widescreen on I get a message on the bottom screen saying "Failed to backup TwlBG"

Game is Pokemon Diamond

### Steps to reproduce

1.Setup widescreen
2.Launch DS game

**Comment by NightYoshi370** [comment]
Could you take a screenshot of it?

**Comment by ccfman2004** [comment]
No as I only see it for a split second before nds-bootloader takes over.

**Comment by RocketRobz** [comment]
When did you set up widesceen?

**Comment by ccfman2004** [comment]
Yesterday.

**Comment by RocketRobz** [comment]
If you never installed a previous TWiLight Menu++ version, then disable widescreen, and wait for RTCom-activated widescreen.

**Comment by ccfman2004** [comment]
Widescreen works fine with TwlMenu 16.1.0.  Also on my SD card was a file named TwlBG.bak

**Comment by RocketRobz** [comment]
Starting with 277230e4, widescreen will be handled differently.
