### ISSUE TITLE
TWiLightMenu sometimes loads slowly

### ISSUE THREAD

**Issue by ccfman2004** [DS-Homebrew/TWiLightMenu#1161]
**Your console configuration:** New 2DS XL 11.13.0-45U Luma 10.2
**TWiLight Menu++ Version:** 16.10
**TWiLight Menu++ Theme:** Not sure

### Expected behaviour

TWiLightMenu to load within 20 seconds

### Actual behaviour

It could take up to 5 minutes to load.  Sometimes it loads in 10-15 seconds but other times it takes a lot more.

**Comment by NightYoshi370** [comment]
What's your SD card size? How is it formatted?

**Comment by ccfman2004** [comment]
Class 10 128GB 32Kb cluster Sandisk

**Comment by NightYoshi370** [comment]
What did you use to format it?

**Comment by ccfman2004** [comment]
SDFormatter Mac.  Sometimes it loads quick other times not its weird.

**Comment by ccfman2004** [comment]
I moved everything off the microSD card, reformatted it and copied everything back.  Seems to be faster now.
