### ISSUE TITLE
creating new save issue.

### ISSUE THREAD

**Issue by Sansnyan** [DS-Homebrew/TWiLightMenu#1163]
So i was recently using twilight menu and was gonna play pokemon platinum on it. what happened was that it randomly created a new save but instead of it being a normal .sav it was a .sav9 file. and it kept on creating that sav9 file every time i got rid of it. any help would be appreciated 

i’ve also been running B9S with Luma3DS instead on my new 2ds xl

**Comment by RocketRobz** [comment]
Switch the save number to 0 in the per-game settings.

**Comment by NightYoshi370** [comment]
Hit Y and change the save slot from save slot 9 to save slot 0.
Also, for support, please use the Discord server linked in the readme
