### ISSUE TITLE
[Request] Twilight Menu autoboot on EDGE

### ISSUE THREAD

**Issue by AyraHikari** [DS-Homebrew/TWiLightMenu#1164]
I am using EDGE Flashcart in my NDS Phat
Then trying Twilight Menu by downloading latest TWiLightMenu-Flashcard in release
Extracted:
- _nds
- BOOT.NDS

Then run BOOT.NDS in EDGE firmware, it run works well
At first it say flashcart not supported when running a game, then i am enable "Use nds-bootstrap" and works fine
Also GBARunner2 is work when change DLDI access to ARM7 (nds phat)

My question is, can it do auto run TM without run BOOT.NDS manual?
I don't really know how to check autoboot support for this flashcart, but when this flashcart inserted in NDS slot, it will run EGDE OS instead of NDS menu
EDGE Firmware: https://www.linfoxdomain.com/nintendo/ds/dl.php/EDGE_OS_v2.3.rar

**Comment by hansoljin** [comment]
The main problem with the EDGE and iEDGE is that the boot file is encrypted. No one has broken this encryption, so unless that gets sorted out, we won't be able to put any custom payloads to directly boot. 

Now, if the kernel supported automatically loading the last-ran ROM, one can actually utilize this to boot into TWiLight Menu++ directly, complete with SCFG access. However, this is, from what I can remember, not possible to do so, at least not on the EDGE kernel. 

This means that until someone cracks the encryption key for the EDGE, it's not happening.
