### ISSUE TITLE
Holding Exit Combo quits TWiLightMenu

### ISSUE THREAD

**Issue by ccfman2004** [DS-Homebrew/TWiLightMenu#1167]
**Your console configuration:** N2DS 11.13.0-45U Luma 10.2 
**TWiLight Menu++ Version:** commit nightly 4200c8eb05100276eb22def8d86eb7a8e36de49a
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

Holding L+R+Down+B should quit the DS game and return me to the TWiLightMenu game selection screen

### Actual behavior

TWiLightMenu fully quits to the 2DS Home Menu

### Steps to reproduce

1. Start DS Game
2. Hold L+R+down+B to exit DS Game
3.

This issue doesn't exist in 16.1.0

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue that happens randomly, so it doesn't matter which TWiLight Menu++ version you're using.

**Comment by ccfman2004** [comment]
Then why did I never have this issue until I installed the latest nightly?  It kept happening until I went back to 16.1.0.  Now it functions as intended.

**Comment by RocketRobz** [comment]
It is unknown why this happens.
Did you use the release version of nds-bootstrap on both TWLMenu++ builds?

**Comment by ccfman2004** [comment]
I have been using the latest nightly

**Comment by RocketRobz** [comment]
Try the release version of nds-bootstrap instead.

**Comment by ccfman2004** [comment]
No change. 16.1.0 does the reset correctly and the TWiLightMenu commit 4200c8eb05100276eb22def8d86eb7a8e36de49a completely quits TWiLightMenu.

**Comment by RocketRobz** [comment]
Did the game you launch run in widescreen?

**Comment by ccfman2004** [comment]
I tried both

**Comment by RocketRobz** [comment]
I'm still stumped. There should be nothing in the TWLMenu++ code that causes this.
Can anyone else test this, and see if you get the same issue?

**Comment by ccfman2004** [comment]
I will attempt to test every commit to see if I can find a commit where this issue starts.

**Comment by ccfman2004** [comment]
I have tested this on both my N2DS XL and N3DS XL and the commit that this issue starts in is 867e10692d315f297adcfd363437f546c502efb9

I get consistent results every time.

**Comment by RocketRobz** [comment]
Thanks for testing!
Now fixed.

**Comment by ccfman2004** [comment]
Works great. Thanks
