### ISSUE TITLE
Cheats Do Not Deselect

### ISSUE THREAD

**Issue by ibschmitty** [DS-Homebrew/TWiLightMenu#1168]
**Console Configuration** 2DS XL on 11.13.0-45U running Luma3DS 10.2 
**TWiLight Menu++** 16.1.0
**TWiLight Menu++** Tested in DSi, 3DS, R4, Sega, Homebrew Launcher :** 

**Expected behaviour**
Cheats selected with A should be unselected with A.

**Actual behaviour**
Have gone through multiple pokemon games
When selecting cheats, often the ones in a list that cannot be active at the same time because they perform the same function (movement speed x2, x4), pressing A does not deselect them. And if the selected cheats are saved it is impossible to deactivate them unless I remove the cheat file. In my situation I was stuck with x2 or x4 movement speed after activating

For Pokemon Heartgold here is a pretty much a complete list of cheat categories where this occurs
-Wild pokemon modifier codes
-Wilde pokemon level modifier codes
-Wild pokemon nature modifier codes
-Wild pokemon iv modifier codes
-View and camera codes
-Game time codes
-Movement speed multiplier codes
-Trainer gender modifier codes
-Pokegear color them codes
-Pokemon marking codes
-Ability marking codes
-Experience multiplier codes
-Ev multiplier codes
-Calling name modifier codes
-Weather codes
-Play as _____codes ", multiple different ones
-Wi fi arena background modifier
-Backlight codes

Checked other games and they also had the same issue. Found similar bug posted for castlevania, solution was to redownload cheat file. Attempted and it did not fix

**Steps to reproduce**
1. Get heartgold, or any pokemon game
2. Go to cheats like experience multiplier codes, with list of only cheats that can only be active one at a time
3. Press A to select then try to deselect

**Comment by ccfman2004** [comment]
I have had similar issues
