### ISSUE TITLE
White screen after DS loading screen.

### ISSUE THREAD

**Issue by JVGstopstop** [DS-Homebrew/TWiLightMenu#1173]
So recently I got the DSi menu in TWiLightMenu and I just wanted to look around and see some of the new functions. Then I saw an orange cartridge at the top of the game select screen and wanted to see what it would do only to get a white screen. I turned of my console opened it and went back to TWiLightMenu and the DS startup/health and safety screen loaded as normal but when I pressed start the screen turned white.

**Your console configuration:** New 2DS XL Luma3DS

**TWiLight Menu++ Version:** v16.1.0
**TWiLight Menu++ Theme:** DSi

### Expected behaviour 

It should load into the game select were I can pick my ROM to play

### Actual behaviour

Turns the screen white straight after pressing start on the DS startup/health and safety screen 

### Steps to reproduce

1.Load TWLightMenu threw 3DS home screen 
2. DS startup/health and safety screen shows asking me to touch the screen/any button
3.White screen

**Comment by Rix565** [comment]
@JVGstopstop Hey ! 
Delete the configuration file of Twilight Menu ++.

**Comment by JVGstopstop** [comment]
> @JVGstopstop Hey !
> Delete the configuration file of Twilight Menu ++.

Thanks for the reply! I'll try that out and see what happens.

**Comment by NightYoshi370** [comment]
Seems to be a support issue, rather than an actual bug. Please use the discord server for this
