### ISSUE TITLE
Add French translations of the manual and Unlaunch settings

### ISSUE THREAD

**Issue by Dhalian** [DS-Homebrew/TWiLightMenu#1177]
I suppose this requires a bit of work, but given the practicality of the manual, it would be more convenient if it were available in other languages (I suppose this may have been planned, but it will avoid some of the inconvenience of asking for unnecessary help when everything is written in the manual).

The manuel has been translated on Crowdin

**Comment by Epicpkmn11** [comment]
As long as they're done on Crowdin they should be in the next release, translations just aren't merged until shortly before the release to give time to translate and such

**Comment by urmum-69** [comment]
unlaunch also can't be (easily) translated

**Comment by Epicpkmn11** [comment]
I think they were referring to the Unlaunch page in settings as that isn't translated in any languages in the last release iirc

**Comment by urmum-69** [comment]
oh, I'm stupid
I get it now

**Comment by Dhalian** [comment]
All right , thanks for your answer
