### ISSUE TITLE
Games don't launch in Widescreen anymore

### ISSUE THREAD

**Issue by ccfman2004** [DS-Homebrew/TWiLightMenu#1178]
**Your console configuration:** N2DS 11.13.0-45U Luma3DS 10.2
**TWiLight Menu++ Version:** d6d43c241dc1502c3051c997032d5631e192143c
**TWiLight Menu++ Theme:** 3DS Suicune

### Expected behaviour

DS Game should be in widescreen

### Actual behaviour

Game is in normal 4:3

### Steps to reproduce

1. Follow updated Widescreen instructions in Wiki
2. Set option to launch game in widescreen
3. Launch DS game.

**Comment by RocketRobz** [comment]
Just re-run TWPatch and enable widescreen.

**Comment by ccfman2004** [comment]
That was the first thing I did.
