### ISSUE TITLE
Top screen is squished in menu

### ISSUE THREAD

**Issue by ccfman2004** [DS-Homebrew/TWiLightMenu#1179]
**Your console configuration:** N2DS 11.13.0-45U Luma3DS 10.2 
**TWiLight Menu++ Version:** d6d43c241dc1502c3051c997032d5631e192143c
**TWiLight Menu++ Theme:** 3DS Suicune

### Expected behaviour

Top screen should be the size of the DS screen

### Actual behavior

![IMG_7154](https://user-images.githubusercontent.com/79392/92330836-1179f580-f040-11ea-82b1-8a69bdc4bfc2.jpeg)

**Comment by RocketRobz** [comment]
Just re-run TWPatch and enable widescreen.

**Comment by ccfman2004** [comment]
That was the first thing I did.

**Comment by RocketRobz** [comment]
By enabling widescreen, you did so in TWPatch, right?
After doing that, leave `TwlBg.cxi` where it's currently at.

**Comment by ccfman2004** [comment]
I followed the updated instructions on the wiki.

**Comment by RocketRobz** [comment]
It has not been updated for the latest commits.

**Comment by ccfman2004** [comment]
Should there be Widescreen.cxi in the TwlBG folder.

**Comment by RocketRobz** [comment]
No. You just need the widescreen `TwlBg.cxi` in `sd:/luma/sysmodules/`.

**Comment by ccfman2004** [comment]
Nope, didn't fix it.

**Comment by RocketRobz** [comment]
Make sure external FIRMs and modules are enabled.

**Comment by ccfman2004** [comment]
Already did that when I first setup widescreen week ago.  I had no issues with widescreen until I updated TwiLightMenu today with last commit.

**Comment by RocketRobz** [comment]
To make sure, are you doing this in order?
* Launch TWPatch
* Go into patch list
* Enable GPU scale test
* Exit from patch list
* Hold the button combo for widescreen
* Leave `TwlBg.cxi` at `sd:/luma/sysmodules/`, and don't move into `sd:/_nds/TWiLightMenu/TwlBg/`

**Comment by ccfman2004** [comment]
Still squished.

**Comment by RocketRobz** [comment]
Is Luma being run from CTRNAND or the SD card?

**Comment by ccfman2004** [comment]
I have 10.2 installed in both.

**Comment by RocketRobz** [comment]
That doesn't answer my question.

**Comment by ccfman2004** [comment]
How do I tell?

**Comment by RocketRobz** [comment]
Check Luma config and look at the bottom of the bottom screen.

**Comment by ccfman2004** [comment]
SD

**Comment by RocketRobz** [comment]
`TwlBg.cxi` does appear in `sd:/luma/sysmodues/`, right?
If so, then it seems Luma is just failing to read it for some reason.
Try reformatting the SD card to FAT32 with 32kb cluster size.
If that doesn't fix the issue, then open an issue at the Luma repo.

**Comment by ccfman2004** [comment]
The issue didn't start until commit 6d61dc9ca97c8fee73a19b41fa3dfe0f25d36081

**Comment by RocketRobz** [comment]
This does not affect how Luma reads the CXI file though.
The Luma bug just wasn't made apparent until that commit.

**Comment by ccfman2004** [comment]
I think you be confusing this issue with the other issue I am having.  The issue here is that the top screen is being squished now.  This has nothing to do with games not launching in widescreen which is the other issue I am now having.

**Comment by RocketRobz** [comment]
Both issues are linked to the Luma bug.

**Comment by ccfman2004** [comment]
This is weird, I ran TWPatch again and now it seems to be working.

**Comment by RocketRobz** [comment]
That would mean that TWPatch is being buggy with the screen refresh and button code then. :P
How long did you hold the button combo before it started working properly?

**Comment by ccfman2004** [comment]
Until the screen started to display that it was doing something. Not even 1 second like every other time I did it.

**Comment by ccfman2004** [comment]
Also the text in the top screen is horrible now.

**Comment by RocketRobz** [comment]
Unfortunately, that can't be done without properly reworking the TWLMenu++ themes for widescreen.

**Comment by ccfman2004** [comment]
Even the text on the box art is pixelated now.

**Comment by ccfman2004** [comment]
Also TwiLightMenu ignores the 4:3 settings now.

**Comment by RocketRobz** [comment]
Unfortunately, there's no way around this issue, aside from turning off external FIRMs and modules.

**Comment by ccfman2004** [comment]
Will that ever change?

**Comment by RocketRobz** [comment]
Yes, the upcoming RTCom code will allow switching between 4:3 and 16:9 without separate TwlBg CXI files and changing Luma settings.

**Comment by ccfman2004** [comment]
That's good to hear.

I'm not sure why but I have an N3DS and N2DS and widescreen on the N3DS looks fine but on the N2DS everything looks pixelated including DS games.  I have the exact same setup on both.
