### ISSUE TITLE
Theme Settings not saving

### ISSUE THREAD

**Issue by fefss** [DS-Homebrew/TWiLightMenu#1183]
**Your console configuration:**  DS Lite with www.r4isdhc.com flashcard + YSMenu
**TWiLight Menu++ Version:**  Release v16.2.2
**TWiLight Menu++ Theme:**  

### Expected behaviour

After changing the theme, when I restart the console, the theme should be the one I chose before.

### Actual behaviour

When restarting, the theme goes back to DSi theme.

### Steps to reproduce

1. Load TWiLightMenu through Autoboot
2. Go into settings and change the theme.
3. Exit the settings and restart the console.

**Comment by RocketRobz** [comment]
Cannot reproduce.
