### ISSUE TITLE
Constant widescreen now

### ISSUE THREAD

**Issue by ryotoko** [DS-Homebrew/TWiLightMenu#1184]
**Your console configuration:** New 3DS 11.13 with Luma3DS 10.2
**TWiLight Menu++ Version:** v16.2.2
**TWiLight Menu++ Theme:** 3DS

### Expected behaviour

I was expecting to be able to specify 4:3 or 16:10 display via the Misc settings, or per-game settings. I went through the new guide step by step, including installing the new CIA files of Twi Menu and TWPatch. Before doing this, I deleted the old TwlBg.cxi and bak in luma/sysmodules 

### Actual behaviour
Twimenu is now all widescreen, all the time. It doesn't matter what the per-game setting is or the misc settings option is.

**Comment by RocketRobz** [comment]
That's normal. You need to either turn off external FIRMs and modules, or delete `TwlBg.cxi` at `sd:/luma/sysmodules/`, if you want to run in 4:3 again.

**Comment by ryotoko** [comment]
I guess you gave up making it more convenient? Thanks for trying at least

**Comment by RocketRobz** [comment]
In the future, widescreen will be activated via RTCom.
That way, it can be activated without the need to rename or copy the CXI file.

**Comment by danylopez123** [comment]
I guess that for now, i'll keep the 4:3 normal ratio until this is fixed.
It's even affected if you play a DSiWare game or any NDS game outside TWiLight Menu++
The problem it's still present in v23.1.1

**Comment by RocketRobz** [comment]
> I guess that for now, i'll keep the 4:3 normal ratio until this is fixed. It's even affected if you play a DSiWare game or any NDS game outside TWiLight Menu++ The problem it's still present in v23.1.1

Due to the TWPatch developer leaving the scene, RTCom will not be implemented.
You can fix your issue by deleting `TwlBg.cxi` at `sd:/luma/sysmodules/`, and re-following this guide [here](https://wiki.ds-homebrew.com/twilightmenu/playing-in-widescreen).

**Comment by danylopez123** [comment]
> 
> Due to the TWPatch developer leaving the scene, RTCom will not be implemented. You can fix your issue by deleting `TwlBg.cxi` at `sd:/luma/sysmodules/`, and re-following this guide [here](https://wiki.ds-homebrew.com/twilightmenu/playing-in-widescreen).

I did followed the Guide, Widescreen.cxi gets renamed back to TwlBg.cxi and gets moved back to the luma/sysmodules folder.
At least i don't have to keep putting my microSD back to my PC just to re-do the same thing, i have 3DShell in my New 3DS XL so i can just re-move it back to the apropiated folder and rename it again.

**Comment by RocketRobz** [comment]
> I did followed the Guide, Widescreen.cxi gets renamed back to TwlBg.cxi and gets moved back to the luma/sysmodules folder. At least i don't have to keep putting my microSD back to my PC just to re-do the same thing, i have 3DShell in my New 3DS XL so i can just re-move it back to the apropiated folder and rename it again.

Try deleting the TWiLight Menu++ titles in the FBI title list, and try re-installing using Universal-Updater.
If the issue persists, idk why. It should've at least shown if it failed to rename `TwlBg.cxi` back to `Widescreen.cxi`, after it rebooted to widescreen.
