### ISSUE TITLE
YSMenu cannot be used after a game is launched by it through TWLMenu++

### ISSUE THREAD

**Issue by tomrow** [DS-Homebrew/TWiLightMenu#1186]
I attempted to launch YSMenu to use AR cheat codes as the DS version of TWLMenu++ doesn't seem to support it, but instead it just launches the last booted commercial ROM. If direct boot is turned off for YSMenu.NDS and it is launched, the system will get stuck in a loop. 

TwlMenu++ Version 16.1.0

**Comment by Epicpkmn11** [comment]
Try holding <kbd>B</kbd> as YSMenu loads, TWiLight sets YSMenu's autoboot title to the game to load when using it instead of B4DS but holding <kbd>B</kbd> should cancel the auto load

**Comment by NightYoshi370** [comment]
This is not something on TWiLight Menu++'s end. Ideally, it would be nice if YSMenu supported arguments so that we wouldn't need to change the last ran rom, but this is the only way we could do it for now
