### ISSUE TITLE
I don't get the roms in the twilight menu

### ISSUE THREAD

**Issue by AlejqueGB** [DS-Homebrew/TWiLightMenu#1187]
Hello, I have a problem and it is that the roms that are in the sd do not appear, I have been changing configurations on the recommendation of a friend and I do not know what I have been able to change 🤦‍♂️

**Comment by Epicpkmn11** [comment]
Are you in the right folder where your roms are? Also make sure they aren't zipped or anything like that, they need to just be the plain roms (ex. DS games should be `.nds`)

Also it'd be better to join the [Discord server](https://discord.gg/yD3spjv) for support

**Comment by AlejqueGB** [comment]
yes I was but I have already solved it, my sd had been corrupted ... sorry for the annoying
