### ISSUE TITLE
Cheat menus

### ISSUE THREAD

**Issue by Gamerknox** [DS-Homebrew/TWiLightMenu#1189]
**Your console configuration: New 2DSXL running Luma3DS**  
**TWiLight Menu++ Version:**  16.2.2
**TWiLight Menu++ Theme:**  DSi

### Expected behaviour

 I should be able to deselect a cheat

### Actual behaviour

 I am unable to deselect 

### Steps to reproduce

1. On a game press Y then X
2. Enter a cheat category 
3. Select a cheat then deselect

**Comment by RocketRobz** [comment]
Already fixed in later commits.

**Comment by Gamerknox** [comment]
How do I fix the issue with the commit that is already released?

**Comment by RocketRobz** [comment]
You can either update to the latest TWLMenu++ nightly, or wait for the next version to release.
