### ISSUE TITLE
Original R4 (non-SDHC) unable to autoboot to TWLMenu++

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/TWiLightMenu#1191]
**TWiLight Menu++ Version:** v16.0.0 and later

### Expected behaviour

Boots TWiLight Menu++ successfully

### Actual behaviour

Stuck on `Loading...` screen

### Steps to reproduce

1. Follow the autoboot steps for OG R4.
2. Launch flashcard or turn on DS console.
3. Profit.

**Comment by NightYoshi370** [comment]
Actually, 16.0.0 was the one to make this break. So it's that version and everything past that
This was tested by Samuel and ariebe on our Discord server

**Comment by RocketRobz** [comment]
As tested once again by Samuel, the issue isn't fixed.
