### ISSUE TITLE
the cheats doesn't work

### ISSUE THREAD

**Issue by ilpollopazzo** [DS-Homebrew/TWiLightMenu#1200]
Hi, I have an old nitendo 3ds, I have twilight menù updated at the last version, but I can't use cheats. I was playng pokemon platinum and I wated to capure aceus,s o I tried to cheat the blue flute but the man how have to deliver me it doesn't appares, what I have to do? I've fpllowd every steps but The cheat doesn't work. Is ita a bug or something eals??????

**Comment by SleepyLark** [comment]
We can't guarantee that every cheat will work.

**Comment by ilpollopazzo** [comment]
so it simpli doesn't work?

**Comment by RocketRobz** [comment]
It can be fixed. We just don't know how to, yet.
