### ISSUE TITLE
Crashes regardless if I use the cfw fix

### ISSUE THREAD

**Issue by chowder908** [DS-Homebrew/TWiLightMenu#1206]
I keep getting crashes when I don't use the cfw fix I get a crash asking me to reset the 3ds and with the cfw fix I get a crash telling me to use my CTRNAND

**Comment by RocketRobz** [comment]
This isn't a TWiLight Menu++ issue.
Please visit [here](https://discord.gg/C29hYvh) for Luma assistance.
