### ISSUE TITLE
Widescreen mode active while settings say otherwise

### ISSUE THREAD

**Issue by HaxTheCharizard** [DS-Homebrew/TWiLightMenu#1207]
### Console Config:
2DS with Godmode9 and Luma3DS
launcher v16.4.0
bootstrap v0.35.1
Typically use DSi theme, but occurs with all themes

### Explanation of expected and actual behavior:
I downloaded the latest update today (version 16.4.0), and saw that the top screen was now widescreen, despite my settings saying it was in 4:3. Games occasionally are partially squished graphically, and have the bottom 1/8th of the screen doubled on top of itself.

Changing the settings to widscreen mode causes all games launched to be in widescreen like normal.

I used FBI to completely delete the app, then removed all residual files in order to have a fresh installation... however, this visual glitch happened again.

I am unsure what exactly is causing the problem, as I see nothing wrong with the settings or installation files.

The launcher occasionally glitches the color pallet of the ds game slot icon after changing the setting, apart from this, the launcher shows no sign of other issues apart from the main visual distortion.

Included are several pictures of the issue

![20201012_224833](https://user-images.githubusercontent.com/68970651/95810573-43394880-0cdf-11eb-8ebc-b862aefecf86.jpg)
![20201012_224821](https://user-images.githubusercontent.com/68970651/95810575-446a7580-0cdf-11eb-9e33-024610cf6667.jpg)
![20201012_224906](https://user-images.githubusercontent.com/68970651/95810577-459ba280-0cdf-11eb-8fda-50f37ef6ed9c.jpg)

### Steps to reproduce

1. downloaded the launcher update through the updater Homebrew application
2. updated the updater
3. updated the launcher again, due to uncertainty that I installed the newest version
4. upon opening the launcher, the issue occurred
5. attempted to completely uninstall/reinstall the app, and had the same issue
6. I am unsure of what exactly triggered the repeated bottom 1/8th of the screen, the reinstallation made it stop occurring for now, but I believe it is related due to it showing up at the same time as the main issue. (if/when it happens again, I will post an update to this post with what was done when it triggered)

**Comment by RocketRobz** [comment]
The line duplication is a TWL_FIRM issue.
Also, turn on 16:10 in TWLMenu++ Settings to fix the stretched top screen.
If you want to disable widescreen, keep 4:3 set, and delete `TwlBg.cxi` at `sd:/luma/sysmodules/`.

**Comment by HaxTheCharizard** [comment]
Thank you, that seemed to fix the problem!

I will keep searching to make sure there aren't any other bugs with the launcher on my device, since I have had some weirdness in the past... but for now, that was all I needed. Thanks!
