### ISSUE TITLE
Include boxart package with latest Twilight Menu

### ISSUE THREAD

**Issue by ObscureExtractor** [DS-Homebrew/TWiLightMenu#1209]
**Is your feature request related to a problem? Please describe.**
This isn't related to any problem just simple quality of life improvement.

**Describe the solution you'd like**

**Describe alternatives you've considered**
You could go look up the images for the boxart and resize them or go to a website and download a package of almost all games.

**Additional context**

**Comment by urmum-69** [comment]
I see zero reason to do this.
https://www.gametdb.com/DS/Downloads
You can find all the boxarts here, I hardly see why this needs to be included with the downloads, especially when it isn't an "essential" function.

**Comment by NightYoshi370** [comment]
We really do not need to bloat up the package when they are:

a) Simply cosmetics
b) Easy enough to get

- 3DS: TWiLight Menu++ Updater
- PC: https://github.com/KirovAir/TwilightBoxart/releases
