### ISSUE TITLE
Save files are not expanded if manually truncated outside of TWiLightMenu.

### ISSUE THREAD

**Issue by chyyran** [DS-Homebrew/TWiLightMenu#1210]
**Your console configuration:** Nintendo DSi
**TWiLight Menu++ Version:** Tested on d487782 but this should affect 16.5.0 and all previous versions as well.
**TWiLight Menu++ Theme:** All nds-bootstrap launching themes that create/expand save files (including quickmenu).

### Expected behaviour

After manually truncating a save file created by TWiLightMenu, the existing save file is expanded by TWiLightMenu if not the proper size for the ROM.

### Actual behaviour

Save file is not changed before booting into nds-bootstrap. **nds-bootstrap will then read *and write* past the end of the truncated file, without expanding the file.** This could possibly cause data corruption. The portions of the save file that nds-bootstrap writes that are beyond the size of the file noted in the FAT table are inaccessible to conforming FAT implementations (like Windows Explorer), but nds-bootstrap will happily read and write into the cluster, past the size of the file.

Save size is only expanded if `saveSizeFixNeeded` is true. However, this does not account for the user, for some reason, having a save file smaller than what is expected.

### Steps to reproduce

1. Create a save as usual with TWiLightMenu
2. Manually truncate the save file (in testing, I chopped off everything except the first byte, and wrote `1` in it)
3. Observe that TWiLightMenu will not create a new save file, or expand the existing file. 
4. Observe that nds-bootstrap will write into the truncated file (game may say "save data corrupted" on first boot, but will work after save data is written) across multiple reboots.
    * In my testing, the `1` was replaced with `M` as the beginning part of the Mario Kart DS save header. However, no other save data was accessible, and the file size read 1KB on Windows Explorer
    * Save data is persisted despite it being inaccessible to a conforming FAT implementation.

### Suggested Fix

A fix like this is needed but I'm not sure what the purpose of `saveSizeFixNeeded` is and why we check for that.

```patch
+ if ((orgsavesize == 0 && savesize > 0) || (orgsavesize < savesize && saveSizeFixNeeded)) {
- if ((orgsavesize == 0 && savesize > 0) || (orgsavesize < savesize)) {
```

Alternatively, fix the FAT implementation that nds-bootstrap uses to properly expand the save file, or have nds-bootstrap refuse to read/write into a save file of incorrect size.

**Comment by RocketRobz** [comment]
Seems to have been fixed some versions ago.
