### ISSUE TITLE
Acekard 2(i) reports "System File is Missing" with autoboot

### ISSUE THREAD

**Issue by sskylar** [DS-Homebrew/TWiLightMenu#1217]
**Your console configuration:** New 3DS with Luma3DS + Acekard 2(i) with AKAIO 1.9.0
**TWiLight Menu++ Version:** 16.5.0
**TWiLight Menu++ Theme:** (default)

### Expected behaviour

When launching the flashcart (via 3DS homescreen), I should see TWiLightMenu++ instead of AKAIO.

### Actual behaviour

The flashcart screen goes from "Loading..." to "System File is Missing". 

### Steps to reproduce

1. Copy `__aio` and `akmenu4.nds` from AKAIO 1.9.0 to SD card.
2. Copy `_nds`, `BOOT.NDS`, and `roms` from TWL release following steps in [the wiki](https://github.com/DS-Homebrew/TWiLightMenu/wiki/installing-%28flashcard%29).
3. Copy contents of `Flashcart Loader/Acekard 2(i)` from TWL release.
4. Copy contents of `Autoboot/Acekard 2i & Acekard 2.1` from TWL release (overwriting `akmenu4.nds`).

Final contents of SD card:
```
📁 __aio
📁 _afwd
📁 _nds
📁 roms
📄 Afwd.dat
📄 akmenu4.nds
📄 BOOT.NDS
```

5. Insert SD card into Acekard 2(i) and launch by tapping icon from 3DS homescreen.
6. Screen hangs on "System File is Missing".

Note: Restoring the original `akmenu4.nds` (from AKAIO 1.9.0 release) allows the flashcart to load again, and I'm able to manually launch TWL sucessfully once in AKAIO. So this appears to only affect autoboot.

**Comment by hoby1k** [comment]
I'm having the same issue as described above. Once I restored the original akmenu4.nds from AKAIO 1.9.0 I enabled autorun in the AKAIO menu. Now my system boots into AKAIO for a moment then automatically launches Twilight Menu ++. Not sure if this is the best solution, but it works.

**Comment by Epicpkmn11** [comment]
[nds-hd-menu](https://github.com/devkitPro/nds-hb-menu)'s BootStrap file works, so here's a modified version of that that boots TWiLight: [akmenu4.nds.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/5732221/akmenu4.nds.zip)

I might try see if I can get the actual TWiLight one working, but if we can't we could just use this

**Comment by Epicpkmn11** [comment]
Alright, did a bit of testing and figured out a fix. Changing booter_fc's arm9 `LDFLAGS` to
```diff
- LDFLAGS	=	-specs=../../../universal/arm9/ds_arm9_twlm.specs -g $(ARCH) -Wl,-Map,$(notdir $*.map)
+ LDFLAGS	=	-specs=ds_arm9.specs -g $(ARCH) -Wl,-Map,$(TARGET).map
```
and adding this at line 122
```diff
$(OUTPUT).elf	:	$(OFILES)
+ 	@$(LD) -Wl,--defsym,__secure_area__=0 -Wl,--section-start,.crt0=0x02000450,--nmagic $(LDFLAGS) $(OFILES) $(LIBPATHS) $(LIBS) -o $@
```
fixes it, I have absolutely no clue what those are actually doing though so I'm going to leave this up to @RocketRobz
