### ISSUE TITLE
Cannot Access Twilight Menu ++ Settings v16.5.0

### ISSUE THREAD

**Issue by Darkroe** [DS-Homebrew/TWiLightMenu#1218]
**Your console configuration:**  
**TWiLight Menu++ Version:** 
**TWiLight Menu++ Theme:** 

Console: 2DSXL Firmware: 11.13.0-45U
Twilight Menu++ Version: 16.5.0
Twilight Menu++ Theme: Default (No theme set)

### Expected behaviour

When opening Twilight Menu++ from the 2DSXL Menu, I am greeted with a white screen,
which proceeds to a "Nintendo DSi" top screen and a "Touch the Touch Screen to continue" bottom screen.
After touching the screen, the Twilight Menu ++ animatic intro plays.
After the intro, the DSi screen pops up with settings being accessible on the bottom screen.
Through the bottom right of the bottom screen, I can access the "roms" folder on the SD card.

### Actual behaviour

Everything above except instead of going to a DSi screen after the Twilight Menu ++ intro,
it immediately goes to reading the SD card, and I cannot back out to access the DSi screen
to access Twilight Menu ++ settings. 

### Steps to reproduce

1. I downloaded the Twilight Menu ++ v 16.4.0 as per the instructions on the GitHub. After installation I updated using the Universal Updater, as per the instructions on the GitHub. When Twilight Menu ++ v 16.5.0 was released, I used the Universal Updater again.
2. After installing and updating Twilight Menu ++, I turned off my 2DSXL and I placed all my .nds files into the roms folder.
3. I launched Twilight Menu ++. I was able to launch and run all my .nds games. I just can't access Twilight Menu ++ settings.

**Comment by SleepyLark** [comment]
I'm assuming you're updating from an older version, they changed it so that screen is accessed by pressing the SELECT on the screen that shows your SD card folders. From there you can access the settings and change it so it will boot on start up.

**Comment by Darkroe** [comment]
Ah, my mistake. Assuming there is some manual for that I missed while browsing the GitHub. Thanks for the response! I know a few other people who were having the same issue and I'll pass it on!
