### ISSUE TITLE
White screen at startup || Fixed

### ISSUE THREAD

**Issue by HAMBRUGNATCHERS** [DS-Homebrew/TWiLightMenu#1228]
This was previously a problem but was unable to be resolved and has since been closed and tagged with stale. I have since found a solution which can be found below. If it does not work for you, please comment below letting me know.

**Your console configuration:** DSi XL with Unlaunch v2.0
**TWiLight Menu++ Version:** 16.3.0
**TWiLight Menu++ Theme:** 3DS

### Expected behavior

TWiLight Menu ++ should boot within 10 - 15 seconds.

### Actual behavior

Screen is stuck on white screen indefinitely.

### Steps to reproduce

1. Boot up TWiLight Menu ++
2. Repeat step one until you get a white screen for more the 15 seconds

### Step for solution

1. Close the DS, but do not turn it off.
2. Reopen the DS and it should resume booting up.

**Comment by unresolvedsymbol** [comment]
You're using a very old version. I've never experienced this on my DSi booting through unlaunch.
