### ISSUE TITLE
Pokemon Platinum running too fast.

### ISSUE THREAD

**Issue by kruemmelbande** [DS-Homebrew/TWiLightMenu#1229]
Pokemon platinum runs way too fast at times. Its only this game i think. The sound doesent seem to be effected. It looks like the speed flactuates too. If i run in a straight line between to loading zones, i notice my character noticibly speeding up or slowing down. The intro sequence also is very unsynchronised with the music, wich cuts out too Early. I tried multiple settings, and none seem to resolve the issue, so i hope this gets fixed in a future update.

Im using a 3ds, with luma 3ds.
My Twilight version is the newest version at this time.

**Comment by RocketRobz** [comment]
You can fix this right now.
Just delete the .ips file(s) containing the game's TID, at `sd:/_nds/TWiLightMenu/apfix/`.
