### ISSUE TITLE
No screen aspect ratio option in games and apps settings.

### ISSUE THREAD

**Issue by 5kulld** [DS-Homebrew/TWiLightMenu#1235]
I tried deleting settings.ini and selecting console but when i did that twlmenu just booted up normally as usual

**Comment by 5kulld** [comment]
Im using an old 3ds xl with latest luma.

**Comment by RocketRobz** [comment]
It got moved to `Misc settings`. If you don't see it there either, then just re-follow the widescreen steps.

**Comment by 5kulld** [comment]
i dont see it there either and i refollowed the patching steps multiple times

**Comment by 5kulld** [comment]
im going to try install the latest nightly

**Comment by RocketRobz** [comment]
By following the patching steps, you should have `TwlBg.cxi` at `sd:/luma/sysmodules/`. If it's not there, then that's why you aren't seeing the option.

**Comment by 5kulld** [comment]
yeah i have it there then i moved it to sd:/nds/twilightmenu/twlbg and renamed it to widescreen, as a tutorial suggested

**Comment by RocketRobz** [comment]
As the *outdated* tutorial suggested.

The up-to-date one is [here](https://github.com/DS-Homebrew/TWiLightMenu/wiki/playing-in-widescreen).

**Comment by 5kulld** [comment]
thanks so much, guess i was following the wrong one bro
