### ISSUE TITLE
Exit and softreset combos aren't working properly

### ISSUE THREAD

**Issue by Mima-09** [DS-Homebrew/TWiLightMenu#1236]
**Your console configuration:**  Old 3DS 11/13 0-45U Luma v10.2
**TWiLight Menu++ Version:**  Release v0.35.s2
**TWiLight Menu++ Theme:**  DSi

### Expected behaviour

 Exit combo (R+L+Down+B) returns to the ROM selection menu. Softreset combo (R+L+Start+Select) restarts the game without having to exit to menu and open it again.

### Actual behaviour

 Either combo always goes back to the 3DS home screen; going there by Softreset makes Twilight Menu instantly start the game on startup (just once, nothing permanent). 

### Steps to reproduce

1. Enter exit or softreset combos.
2. Back to the 3DS home screen menu, rather than ROM selection or, well, game's startup.

I can't really say which version I was using before, since I just updated TWL this morning (and hadn't done so before since I; installed it a few weeks ago). Regardless, this wasn't an issue before the update, for either combo worked as intended before then.

**Comment by RocketRobz** [comment]
The combos work fine for me on N3DS.

I heard this issue is specific to O3DS, so it probably won't be fixed anytime soon, as nothing related to soft-resetting was changed.

**Comment by Mima-09** [comment]
Ah, I see. That's mildly unfortunate, but I guess I'm going to live with that for now!

Thanks for the quick response, and have nice day!

**Comment by emmahaskins15** [comment]
I had the same issue on O3DS and was able to resolve the issue by enabling game patching in Luma. (Hold select while turning the console on, check enable game patching, start to save).
