### ISSUE TITLE
TM doesn't recognize Genesis games (Megadrive) - DSi

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/TWiLightMenu#1238]
I tried loading .bin and .md games in my SD card, but Twilight Menu doesn't recognize it. 
The Genesis games folder (and also outside of it) appears totally empty...

![image](https://user-images.githubusercontent.com/70182567/99596497-23c7c680-29d5-11eb-8f13-b436af0cb1b3.png)

![image](https://user-images.githubusercontent.com/70182567/99596983-047d6900-29d6-11eb-8c60-1ac73f3ffa28.png)
![image](https://user-images.githubusercontent.com/70182567/99596996-0b0be080-29d6-11eb-84cb-e2174a369f40.png)

what am I doing wrong? Thanks!

**Comment by Epicpkmn11** [comment]
They have to be `.gen`, `.md` could also be markdown and `.bin` is just super generic so TWiLight only supports Genesis / Mega Drive games with `.gen`

**Comment by urmum-69** [comment]
Considering there is a decent amount of confusion over this, I think it would be a good idea to add mention of the systems/extensions on the manual, or wiki somewhere

**Comment by NightYoshi370** [comment]
I'll add it to the wiki soon:tm:
Since OP was already answered, I'll close this issue

**Comment by SofyUchiha** [comment]
> Tienen que ser, también podría ser markdown y es simplemente super genérico por lo que TWiLight sólo es compatible con Genesis / Mega Drive juegos con `.gen``.md``.bin``.gen`
> 
> Editar: Simplemente cambie el nombre de los archivos y funcionarán, todos son en realidad el mismo formato


I'll try It!

**Comment by SofyUchiha** [comment]
> They have to be `.gen`, `.md` could also be markdown and `.bin` is just super generic so TWiLight only supports Genesis / Mega Drive games with `.gen`
> 
> Edit: Simply rename the files and they'll work, they're all actually the same format

It's works! Thanks so much!
