### ISSUE TITLE
Scrolling text for long words and names in the cheat menu screen.

### ISSUE THREAD

**Issue by Yola-cola** [DS-Homebrew/TWiLightMenu#1239]
**Is your feature request related to a problem? Please describe.**
I find quite irritating that when a name of a cheat is too long to fit in the cheat menu screen. Those kinds of cheats always have corrupted text at the end and you can't even see what the full name is. It's very irritating: especially for cheats that don't have an info page or have a input combination(s) in its name.

**Describe the solution you'd like**
I was thinking, if a cheat name is too long, the text should scroll to the left when the cheat is highlighted by the cursor. This way we can see the input commands in the full name of the cheat.

**Describe alternatives you've considered**
the only other alternative I can think of is to have button command that allows you to see the full title of a cheat. But it seems very pointless unless you have something else that also goes with that command. (like viewing actual code for the cheat)

**Additional context**
![20201119_104358](https://user-images.githubusercontent.com/53379032/99688883-4ea52f80-2a54-11eb-9ca8-c6e5ccfdf021.jpg)

**Comment by urmum-69** [comment]
I suppose another alternative could be having the text wrap, but I don't like that either
What you're suggesting is reasonable

**Comment by SofyUchiha** [comment]
The same goes for the Twilight settings menu (Lenguage: Spanish) 😞

**Comment by Yola-cola** [comment]
Is everyone doing ok?
