### ISSUE TITLE
Organizing ROMs in a certain order

### ISSUE THREAD

**Issue by blueingsh** [DS-Homebrew/TWiLightMenu#1248]
**Is your feature request related to a problem? Please describe.**

I want to organize my games, not just putting them in order of played/alphabetical, but I want to be like how in the 3DS menu you could put the different apps/games in certain orders, and zoom in the menu to have less apps/games or zoom out the menu to have more app/games in view.

**Describe the solution you'd like**

The ability to drag and drop your ROMs and put them in a certain order, and also to zoom in and have less ROMs to show or to zoom out to have more ROMs show.

**Describe alternatives you've considered**

For putting it in a order yes, but you can’t put them in a order that can be like NDS > SNES > NES > GBA.

**Additional context**

I do not have any additonal context to add.

**Comment by SofyUchiha** [comment]
That can already be done. In the settings menu you change from alphabetical order to custom. There are also other options for ordering the ROMs.

**Comment by NightYoshi370** [comment]
After changing the setting to custom, use the up arrow on the DPAD to order it.
