### ISSUE TITLE
Widescreen behaving strangely

### ISSUE THREAD

**Issue by OmriPi** [DS-Homebrew/TWiLightMenu#1249]
Hi!
I have TM++ installed through universal updater on a new 3DS XL console, with the widescreen patch applied, but I'm getting strange behavior on TM++.
When on the 3DS theme, in the main TM++ menu (where you see the games), if the aspect ratio in the misc settings is set to 4:3, the upper screen is filled and stretched.
If the aspect ratio is set to 16:10, the upper screen is square with black bars on the sides.
Is this the intended behavior? I would think 4:3 should be square and 16:10 should be widescreen, and not the other way around...
Additionally, all games launch in widescreen on the top screen regardless of whether I set the aspect ratio to 4:3 or 16:10, so it seems the aspect ratio setting only affects the menu of TM++ and it does so opposite to what I would've thought it would do.
Is this how it is supposed to be? Is there something wrong with my installation? Or with my understanding of how it is supposed to behave?

Thanks!

**Comment by RocketRobz** [comment]
That's expected behavior. Originally, the menu would stay 4:3, with some games launching in 16:10.
Since that didn't work properly for some users, the menu now has black bars to accommodate TWL_FIRM running in 16:10, and games that aren't supported in widescreen, are now stretched without any fixes.

**Comment by OmriPi** [comment]
@RocketRobz Thank you so much for the quick response!
So the aspect ratio setting does not, in fact, do anything aside from setting black bars on the menu? It does not affect the games themselves if I understood correctly.
Keep up the amazing work you're doing with TM, it is one incredible piece of software!
Thanks!

**Comment by RocketRobz** [comment]
Yes.
Also, you're welcome!
