### ISSUE TITLE
doubt about SNEmulDS

### ISSUE THREAD

**Issue by JosephVnzla** [DS-Homebrew/TWiLightMenu#1251]
How does SNEmulDS run through TwilightMenu ++? , I don't get the games in my snes folder I have version 17.1.1.

**Comment by RocketRobz** [comment]
You need to install Unlaunch for the games to show.

**Comment by JosephVnzla** [comment]
@RocketRobz oh I see, well thank you very much, I thought that without unlauch it could work.
