### ISSUE TITLE
[EZFlash 3in1] Blank screen after rebooting into GBA mode

### ISSUE THREAD

**Issue by andrebrait** [DS-Homebrew/TWiLightMenu#1255]
**Console Configuration:** Nintendo DS Lite + EZFlash 3in1
**TWiLight Menu++ Version:** 17.1.1
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

The game should start after rebooting into GBA mode

### Actual behaviour

A blank screen with the GBA frame around it

### Steps to reproduce

1. Set GBA mode to Native
2. Try loading a small game (like The Legend of Zelda - A Link to The Past + Four Swords, or Final Fantasy VI)
3. See it reboot and go into a blank screen

**Comment by RocketRobz** [comment]
Already fixed in later commits.

**Comment by andrebrait** [comment]
@RocketRobz It wasn't fixed in 17.2.0 for me.

First, when it happens, now Twilight Menu will freeze when loading. I have to remove the EZFlash 3in1 from the slot or else it won't start. I suppose it's now trying to do something with the 3in1 when starting up (backing up SRAM to a `.sav` file, I suppose?) and it just freezes on a blank screen when starting up. I had to remove the reference to the GBA ROM in the an `.ini` file (which was in the `SECONDARY_ROM` key, I think).

I tested LoZ:ALTTP and it just went to blank screen after loading it. Is the file name being somewhat long an issue? I already have a `.sav` file in place with my saved game there.

**Comment by RocketRobz** [comment]
I don't think file name length would be an issue.

**Comment by RocketRobz** [comment]
Just tested LoZ:ALTTP, and boots fine for me.
If the GBA BIOS screen didn't show, shorten the file name.

**Comment by andrebrait** [comment]
The GBA screen showed just fine. It just went blank after that, though. I already had another ROM on the NOR and its save on SRAM. Anyway, I'll try another ROM and see if that works.

**Comment by andrebrait** [comment]
Since I was using a patched ROM, I have tried again with a clean dump (according to No-Intro) but the result is still the same. Uploading my SAV file (ROM not included in the ZIP, obviously) so you can try with it as well, if that's somehow important.

ROM  Hash (SHA-1): `a272055abbbf6c26b0cd54c87395d01699589161`
[save_file.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/5675763/Legend.of.Zelda.The.-.A.Link.to.the.Past.Four.Swords.USA.zip)

**Comment by RocketRobz** [comment]
The game has reconized your save.

**Comment by andrebrait** [comment]
@RocketRobz So the solution for PSRAM ended up being not using it at all? :smile: 
Even GBAExploader doesn't work 100% of the time with it, so I can't blame you for that, if that is indeed the case :sweat_smile: I was going to suggest adding that as an option and to make it the default, but I guess maintaining the PSRAM mechanism doesn't make sense if it's going to be buggy, right?

**Comment by RocketRobz** [comment]
Yup.
