### ISSUE TITLE
[EZFlash 3in1] NOR does not get overwritten, previous game gets booted instead

### ISSUE THREAD

**Issue by andrebrait** [DS-Homebrew/TWiLightMenu#1256]
**Console Configuration:** Nintendo DS Lite + EZFlash 3in1
**TWiLight Menu++ Version:** 17.1.1
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

The new game should start after rebooting into GBA mode

### Actual behaviour

The old game gets booted into, instead

### Steps to reproduce

1. Set GBA mode to Native
2. Use GBA Exploader to load another game into NOR memory
3. Try loading a big game (like Mother 3)
4. See it reboot into the old game

### Notes

The time it takes to write the new game to NOR is suspiciously short. Is it erasing the NOR before writing it? GBA Exploader does that. Perhaps this should be attempted here too, in case it's not being done.

**Comment by andrebrait** [comment]
This was indeed fixed (loading the game to NOR and booting into GBA mode worked flawlessly), but now Mother 3 can't save. I guess I need to SRAM patch it? Trying with GBAExploader to see if that makes any difference (but GBAExploader might be automatically SRAM patching the ROM).

Also, TwilightMenu is locking up again when starting after playing Mother 3, unless I remove the 3in1 from the slot or make `SECONDARY_ROM_PATH` empty on `settings.ini`. I guess it could be trying to read the SRAM on start up ainda freezing for some reason?

I can create a new issue here as those are separate things. Will do that when I have tested it with GBAExploader.

**Comment by RocketRobz** [comment]
The lock-up has been fixed in later commits.

**Comment by RocketRobz** [comment]
Also, ROMs are automatically SRAM-patched, but apparently, that doesn't work if the game is loaded into NOR.

**Comment by andrebrait** [comment]
Indeed, I can save just fine when using GBAExploader. Probably SRAM patching is indeed broken when flashing to NOR.

**Comment by andrebrait** [comment]
@RocketRobz so, there's still no automatic SRAM patching when flashing to NOR, is that correct? I see you added a warning.

**Comment by RocketRobz** [comment]
Yes. It would be hard to fix the patching code for NOR.
