### ISSUE TITLE
The game binaries are missing

### ISSUE THREAD

**Issue by AlejqueGB** [DS-Homebrew/TWiLightMenu#1262]
Hello, I am having an error when starting Pokemon black / white / white2 / black2 and it says "The game binaries are missing" This has started to appear since I updated to the latest version of twilight, can you help me?

**Comment by SleepyLark** [comment]
You must have a bad dump, it's missing the DSi binaries.  You can try running it in "DS mode", but it's probably better to redump the game instead to prevent any other issues.

**Comment by AlejqueGB** [comment]
how do I do that?

**Comment by RocketRobz** [comment]
Just change the `Run in` setting back to `DS mode` instead of either `DSi mode` or `DSi mode (Forced).`
