### ISSUE TITLE
Native GBA support stopped working using M3

### ISSUE THREAD

**Issue by Y4niv** [DS-Homebrew/TWiLightMenu#1263]
**Console Configuration:** Nintendo DS Phat (I also have a Lite to test this) + Acekard 2i + M3 Perfect Mini SD
**TWiLight Menu++ Version:** v17.2.1
**TWiLight Menu++ Theme:** 3DS

### Expected behaviour
After selecting a ROM it should start playing (I have successfuly tested several ROMs with my M3 in versions v17.1.0 and v17.1.1)

### Actual behaviour
After selecting a ROM (even those that I've already played on the previouse versions) the game will not start playing and instead the M3's menu will show up (like it is trying to run the flashcart instead of the game I just chose (with Twilight Menu++'s Gameboy Advance border)

### Steps to reproduce
1. Use v17.2.1 on Acekard 2i in slot 1 with M3 inserted to slot 2
2. Choose a GBA game like Gunstar Super Heroes (which is one of the games that worked on previous versions)
3. The game will not start and instead the flashcart's menu will show up (with Twilight Menu++'s Gameboy Advance border)

### Note
After returning to v17.1.1 the games are working again

**Comment by RocketRobz** [comment]
After launching TWiLight Menu++, before the ROM list shows, hold B to start the last-launched GBA ROM.

**Comment by RocketRobz** [comment]
After trying the above, please install [this](https://github.com/TWLBot/Builds/blob/9820b8191cc45d682287983f536f321f3c0c33f9/TWiLightMenu-Flashcard.7z) nightly build, and see if that fixes the issue.

**Comment by Y4niv** [comment]
> 
> 
> After trying the above, please install [this](https://github.com/TWLBot/Builds/blob/9820b8191cc45d682287983f536f321f3c0c33f9/TWiLightMenu-Flashcard.7z) nightly build, and see if that fixes the issue.

I did not manage to load the last rom on v17.2.1, I've installed the nightly build and it has the same problem where every GBA rom I try to run ending up loading the M3's flashcart menu instead, so it seems that something that was changed in version v17.2.0 broke the native GBA support for M3, version 17.1.1 is the last one that's still working

**Comment by Y4niv** [comment]
Your fix worked! Thanks @RocketRobz! 🥇  :)
