### ISSUE TITLE
Bundled GBARunner2 messes up the display after a reset of the ROM

### ISSUE THREAD

**Issue by nn9dev** [DS-Homebrew/TWiLightMenu#1268]
### This issue isn't on the end of Gericom's GBARunner, as it does not happen on the latest release on his github page, but DOES happen on the bundled version in TWiLight Menu.

**Console Configuration:** New Nintendo 2DS with Luma
**TWiLight Menu++ Version:** v17.2.1
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

The ROM resets as normal. no display issues.

### Actual behaviour

Every "reset", a little bit of the bottom of the GBA's "display" gets copied up, slowly blocking the entire screen with each reset.

### Steps to reproduce

1. Open a GBA ROM
2. Tap bottom screen to pull up the GBARunner2 menu
3. Choose "reset". initially there will just be a few black bars at the bottom, with a bit of the framebuffer in it, but upon resetting more times, they duplicate themselves.

**Comment by zakame** [comment]
This seems a well-known issue in https://github.com/Gericom/GBARunner2/issues/156 (which can be worked around.)

**Comment by systemallica** [comment]
Should the proposed workaround maybe be included with twilight menu so the experience is improved?

**Comment by Kaisaan** [comment]
Since the workaround is using older builds of GBARunner2, this would decrease compatibility with these games. You can manually replace builds if it is too much of an issue.

**Comment by qamichelemassa5859** [comment]
@zenseii will be replyed your message? Gericom/GBARunner2/issues/278
