### ISSUE TITLE
Chinese manual

### ISSUE THREAD

**Issue by FIve201** [DS-Homebrew/TWiLightMenu#1272]
What? The chinese manual is so bad.
It appeared three times and It’s been like this a few versions ago. 
Please fix it.

**Comment by Epicpkmn11** [comment]
Do you mean the translations are bad? If you'd like to suggest better ones then you can at https://crowdin.com/project/TwilightMenu

Or is there some sort of other problem with it?

**Comment by FIve201** [comment]
> Do you mean the translations are bad? If you'd like to suggest better ones then you can at https://crowdin.com/project/TwilightMenu
> 
> Or is there some sort of other problem with it?

Please open the Chinese manual and turn to the cheat page of nds-bootstrap, you should see the problem

**Comment by Epicpkmn11** [comment]
Oh, I see the problem, since the manual was moved to a separate repository I completely forgot to update it for this release, my bad 😅 

Just update that so it should be updated for the next release, sorry for forgetting about it this time...
