### ISSUE TITLE
The new update makes the DSi theme unstable

### ISSUE THREAD

**Issue by Kobun42** [DS-Homebrew/TWiLightMenu#1275]
**Console Configuration:** New Nintendo 3DS XL with Luma3DS
**TWiLight Menu++ Version:** 2020 Christmas release 
**TWiLight Menu++ Theme:** DSi

### Steps to reproduce

1. Open Twilight menu on DSi theme
2. Do something like scroll to the edge of the menu or open the SELECT menu
3. It will softlock

I am unsure as to what is causing this, and I cannot switch to other themes to test if they work. This has essentially softlocked me out of using the software.

EDIT: I exited my games folder and found that it doesn't seem to happen. Is it maybe because I have too many games?

**Comment by Kobun42** [comment]
Welp, turns out it may have been because I had too many games in one folder. I'll work on organizing them. You might want to fix this or at least add some kind of limit.

I'll close this.

**Comment by Localhorst86** [comment]
could you tell me which game is causing it for you? I am having the same issue but I do not know which title it is.

**Comment by Epicpkmn11** [comment]
Try turning off "Photo & box art color de-band" in settings, that was causing freezing for me

**Comment by Localhorst86** [comment]
> 
> 
> Try turning off "Photo & box art color de-band" in settings, that was causing freezing for me and some other people

That seems to have fixed it, allthough I had to disable it via the settings.ini file because the DSi would always freeze when trying to bring up the select menu.

**Comment by Kobun42** [comment]
> 
> 
> Try turning off "Photo & box art color de-band" in settings, that was causing freezing for me and some other people

Yes, this does indeed solve the problem. Thanks.

**Comment by Epicpkmn11** [comment]
> > Try turning off "Photo & box art color de-band" in settings, that was causing freezing for me and some other people
> 
> That seems to have fixed it, allthough I had to disable it via the settings.ini file because the DSi would always freeze when trying to bring up the select menu.

FYI for the future, you can open settings by holding <kbd>SELECT</kbd> while TWiLight is loading

**Comment by Localhorst86** [comment]
> 
> 
> Try turning off "Photo & box art color de-band" in settings, that was causing freezing for me and some other people

Looking at the changelog, I can see that this is, apparently, a new setting and the changelog also mentions disabling it when encountering issues in the DSi theme (sorry for not properly reading the changelog beforehand).

But out of curiousity: The changelog reads to me as if this feature was always enabled in previous releases - but I haven't had issues like this with older versions of TWiLight. Am I correct in interpreting that changelog entry as such and if so, why did it not cause instability before? (genuine question, not a "gotcha!")

**Comment by Epicpkmn11** [comment]
I'm not actually sure tbh... I think it was added in v17.1.0, but it it is kinda off that it only started causing so much more freezing now, Robz is taking a break for a while though so can't ask him right now...

Looking at 145e10aea63acb2d3742daf0a0d8f245f325c0db where it was added, it looks like if it's enabled is being checked within some large for loops, so it's doing that whole check for every single pixel which might be slowing it down enough to cause more crashing

**Comment by urmum-69** [comment]
well if it's proven to cause instability, then I think it should be reverted and have a new release for the time being

**Comment by imora7024** [comment]
I Noticed that too after updating
I saw some horizontal bars flashing while on the dsi menu
yeah i think thats the issue

**Comment by imora7024** [comment]
Yep disabling it the crashing issues i had

**Comment by Epicpkmn11** [comment]
I've pinned this since people have made a couple more issues about it. To have it in one comment at the end here, the solution is either to disable `Box art & photo de-band` in settings (you can access settings by holding <kbd>SELECT</kbd> while loading TWiLight) or replacing `sd:/_nds/TWiLightMenu/dsimenu.srldr` with [this dsimenu.srldr](https://github.com/DS-Homebrew/TWiLightMenu/files/5753118/dsimenu.srldr.zip) from #1278 seems to fix it for me.
