### ISSUE TITLE
DSi Theme SELECT Menu reappears upon pressing SELECT in the Menu and doing so twice causes menu to hang

### ISSUE THREAD

**Issue by kyoforkshomebrews** [DS-Homebrew/TWiLightMenu#1276]
**Console Configuration:**   New Nintendo 3DS XL with Luma3DS
**TWiLight Menu++ Version:**  v18.0.0 (Release)
**TWiLight Menu++ Theme:**  Nintendo DSi 

### Expected behaviour
Menu closes after pressing SELECT in it.

### Actual behaviour
Menu reappears, pressing SELECT again causes it to hang and stop responding to inputs.
Also, after doing this it might even hang up upon opening the SELECT menu for the first time.

### Steps to reproduce

1. Set Theme to Nintendo DSi
2. Set DSi/Saturn: SELECT to SELECT Menu
3. Press SELECT in the main menu screen
4. After the SELECT menu turns up, press SELECT again (Sometimes it already hangs at this point)
5. Optionally, press SELECT again to make the menu hang

**Comment by Localhorst86** [comment]
I assume this is the same issue as this:

https://github.com/DS-Homebrew/TWiLightMenu/issues/1275

Specifically, the solution is here:
https://github.com/DS-Homebrew/TWiLightMenu/issues/1275#issuecomment-751517848
