### ISSUE TITLE
Bug on selecting games.

### ISSUE THREAD

**Issue by MusafiPits** [DS-Homebrew/TWiLightMenu#1280]
I use a Nintendo DSi with Unlaunch.
**TWiLight Menu++ Version 18.0.0.
**TWiLight Menu++ Theme: Sorry. I can't say what is the Theme, I change nothing.
I use a 32 gb microsd card on an sd adapter. (In case is need to know).

When selecting the games, often the menu stop and i have to turn off and on, because the reset don't work on this problem. When this happen the game's name is change for the one on his side. This problem don't happen in an especific game. Sometime this happen even starting the game, with the screen staying white, but is less often.

Sorry if my english is bad. Thank you.

**Comment by NightYoshi370** [comment]
It's most likely the Nintendo DSi theme.
Please hold SELECT on boot and disable the color debanding option.

**Comment by MusafiPits** [comment]
Thank you.
