### ISSUE TITLE
Freeze on New 3DS XL

### ISSUE THREAD

**Issue by gek169** [DS-Homebrew/TWiLightMenu#1281]
**Console Configuration:**  New 3DS XL with Luma3DS and your provided nds bootstrap
**TWiLight Menu++ Version:** v18.0, christmas update 
**TWiLight Menu++ Theme:** The default? It's dark? I've never used this program before, I didn't know it had themes?

### Expected behaviour
Program doesn't freeze while browsing the menus

Have more than 10 seconds to browse the menus before it crashes

### Actual behaviour

Menu crashes while browsing folders.
### Steps to reproduce

1. Open Twilight Menu
2. Move selection around, click on folders
3. The sound will begin to loop and the cursor will stop responding. Frozen, but can still use home button on 3DS to go back to the 3DS home menu.

**Comment by Epicpkmn11** [comment]
The "Box art & photo de-band" option is causing this in the latest version, either hold <kbd>SELECT</kbd> while loading and turn it off in settings, or you can try replacing `sd:/_nds/TWiLightMenu/dsimenu.srldr` with this one from #1278 which seems to fix the problem for me: [dsimenu.srldr.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/5753118/dsimenu.srldr.zip)

**Comment by gek169** [comment]
That fix worked @Epicpkmn11
