### ISSUE TITLE
No Nintendo logo on startup

### ISSUE THREAD

**Issue by Michal2k7** [DS-Homebrew/TWiLightMenu#1290]
**Console Configuration: DSi with Unlaunch**  
**TWiLight Menu++ Version: 18.1.0** 
**TWiLight Menu++ Theme: Nintendo 3DS** 

### Expected behaviour

On DSi splash screen I should see Nintendo logo in color that I choosed in Misc. settings tab in TWiLightMenu settings.
### Actual behaviour

On DSi splash screen, Nintendo logo is gone. DSi logo is still there.
### Steps to reproduce

1. Set Nintendo Logo Color in Misc. settings
2. Set DSi Splash Screen in Misc. settings to With H&S or Without H&S
3. Reboot DSi

**Comment by RocketRobz** [comment]
Insert a cartridge in the game slot for it to show. (I thought everybody knew this. :P )
