### ISSUE TITLE
Unwanted SELECT Menu when changing brightness

### ISSUE THREAD

**Issue by Michal2k7** [DS-Homebrew/TWiLightMenu#1291]
**Console Configuration: Nintendo DSi with hiyaCFW + Unlaunch**  
**TWiLight Menu++ Version: release version 18.1.0** 
**TWiLight Menu++ Theme: Nintendo DSi dark** 

### Expected behaviour
When pressing select + volume buttons I should change brightness.

### Actual behaviour
When pressing select + vol up/down on home screen brightness changes than select menu pops up.

### Steps to reproduce

1. On home screen press and hold select and use volume buttons to change brightness
2. When releasing select the menu will appear

It is super annoying and I hope it will be fixed.
Thanks

**Comment by RocketRobz** [comment]
Unfortunately, this cannot be fixed without making the SELECT button do nothing at all.
You can press Y to open the per-game settings before attempting to change the brightness.
