### ISSUE TITLE
Guru Meditation Error Screen

### ISSUE THREAD

**Issue by Yola-cola** [DS-Homebrew/TWiLightMenu#1297]
**Console Configuration:** Luma3DS 
**TWiLight Menu++ Version:** 18.2.0 
**TWiLight Menu++ Theme:** DSI Theme

### Expected behavior

It's supposed to go to the DSI Theme menu
### Actual behaviour
It shows a guru meditation error

### Steps to reproduce

1. Update to 18.2.0
2. Launch Twilight Menu++
![20210108_221413](https://user-images.githubusercontent.com/53379032/104081940-2342f380-5200-11eb-8e37-e226110edb69.jpg)

**Comment by moo182** [comment]
I am also experiencing the same issue on the o3ds.
n3ds doesn't seem to be affected

**Comment by RocketRobz** [comment]
Can you see if this is fixed in the latest TWLMenu++ nightly?

**Comment by moo182** [comment]
loaded up 9425d16b now it boots fine :) thank you

**Comment by RocketRobz** [comment]
Was most likely a memory issue then. Thanks for testing!

**Comment by RocketRobz** [comment]
Seems it's not solved for some users who tested the latest nightly.

**Comment by DarkMetaK** [comment]
Yeah I'm having the same problem and can't fix it

**Comment by RocketRobz** [comment]
Fixed in v18.2.1
