### ISSUE TITLE
Crackling/Popping audio unlike real carts

### ISSUE THREAD

**Issue by gek169** [DS-Homebrew/TWiLightMenu#1303]
**Console Configuration:**  
New Nintendo 3DS XL
Luma3DS 
Boot9strap
**TWiLight Menu++ Version:** 
18.2.1
**TWiLight Menu++ Theme:** Homebrew Launcher

### Expected behaviour
Sound in games does not crackle and pop, plays like original carts

### Actual behaviour
Games run from Twilight menu have crackling and popping sound, unlike cartridges.

No, my speakers are not going bad, I tested my copy of Kirby SSU (Exact same as the rom!) and it has no crackling audio, but when run on Twilight menu, there is crackling audio, both at the 32 khz setting and higher quality setting.

### Steps to reproduce

1. Load any Nintendo DS Rom
2. Listen to the audio
3. There is crackling audio

**Comment by RocketRobz** [comment]
That's an nds-bootstrap issue.
Just change the sound setting to Stereo in the game (if supported).
