### ISSUE TITLE
Top menu screen gets squished in widescreen mode

### ISSUE THREAD

**Issue by jojojo8359** [DS-Homebrew/TWiLightMenu#1304]
**Console Configuration:** New Nintendo 3DS XL with Luma3DS v10.2.1 (128GB SD Card) - 3DS Firmware: 11.14.-046U  
**TWiLight Menu++ Version:** v18.2.1 stable, nds-boostrap version Release v0.35.s5 
**TWiLight Menu++ Theme:** Nintendo DSi, Dark skin 

### Expected behaviour

Regardless of the value of "Screen Aspect Ratio" in the Misc. settings tab (either "16:10 (Wide)" or "4:3 (Original)"), the top menu screen should stay a consistent width (or at least it did before I updated to 18.2.1 from 15.2.0).

### Actual behaviour

When the "Screen Aspect Ratio" setting is set to "4:3 (Original)", the top menu screen appears normal.

![File_000](https://user-images.githubusercontent.com/31038772/104141743-37b0f880-5386-11eb-91a2-dde382e528c5.jpeg)
Game selection menu displaying top screen correctly in 4:3 mode.

However, when the "Screen Aspect Ratio" is "16:10 (Wide)", the top menu screen is squished length-wise, but only in the game selection and DS Classic menus. All other TWiLightMenu++ Menus (including settings and manual) appear fine on the top screen.

![File_001](https://user-images.githubusercontent.com/31038772/104141753-4d262280-5386-11eb-9372-c0b54550a30b.jpeg)
Game selection menu not displaying top screen correctly in 16:10 mode.

![File_002](https://user-images.githubusercontent.com/31038772/104141755-4f887c80-5386-11eb-9154-3504c2d5c749.jpeg)
DS Classic Menu also not displaying top screen correctly in 16:10 mode.

### Steps to reproduce

1. Start TWiLight Menu++ (v18.2.1).
2. Go to the TWiLight Menu++ Settings (either through DS Classic Menu or SELECT Menu).2.
3. Navigate to Misc. settings, and set "Screen Aspect Ratio" to "16:10 (Wide)".
4. Back out of settings, and menus like DS Classic Menu and the game selection menu will squish the top screen.
5. To verify this is only the case with 16:10 mode, go back to settings, and change "Screen Aspect Ratio" to "4:3 (Original)". Back out again to see the changes to top menu screens.

**Comment by RocketRobz** [comment]
Did you run TWPatch to enable widescreen?
TWiLight Menu++ has no way of checking if the `TwlBg.cxi` file contains the widescreen patch or now.

**Comment by jojojo8359** [comment]
Using TWPatch seemed to fix this issue. I guess things must have gotten overwritten when I went to upgrade TWiLight Menu++, but now it appears to be back to normal. Thanks for your help!
