### ISSUE TITLE
Can't access DSi Menu(the original one) via select menu

### ISSUE THREAD

**Issue by Misaka15539** [DS-Homebrew/TWiLightMenu#1306]
twilight menu v18.2.1
unlaunch v2.0
The model is JP version of DSi.

Every time I launch the DSi menu it just goes to unlaunch and executes the "loading error" option. I can however go to the DSi menu by selecting "Launcher" in unlaunch. This action worked in v15, but it doesn't work in the newest version.

**Comment by Epicpkmn11** [comment]
I'm not sure why this would break after working in the past, but make sure that "SysNAND Launcher" and "SysNAND Region" are set correctly in the "Misc. Settings" page of TWiLight Settings.

**Comment by Misaka15539** [comment]
It works after I set the SysNAND region to JPN. I assume it has to do with the mismatched language (ENG for system but JPN model) But I didn't have to set this before.
