### ISSUE TITLE
Ukrainian Translate DSiMenu++

### ISSUE THREAD

**Issue by IRONKAGE** [DS-Homebrew/TWiLightMenu#131]
DSiMenu++ Translated
[Ukrainian]
SAVING_SETTINGS = Збереження налаштувань...
SETTINGS_SAVED = Налаштування збережено!

LR_SWITCH = L/R/Y/X Перемикання сторінок
GUI_SETTINGS = Налаштування ГІК
GAMESAPPS_SETTINGS = Налаштування Ігор та Застосунків

; GUI settings
THEME = Тема
LASTPLAYEDROM = Запускається останній ROM при запуску
DSIMENUPPLOGO = DSiMenu++ логотип при запуску
DIRECTORIES = Каталоги/папки
BOXART = Коробкові/Ігрові обкладинки
ANIMATEDSIICONS = Анімувати DSi значки
STARTBUTTONLAUNCH = Запускати кнопкою START
SYSTEMSETTINGS = Системні Налаштування
REPLACEDSIMENU = Замінити Меню DSi
RESTOREDSIMENU = Відновити Меню DSi

SHOW = Показати
HIDE = Приховати

DESCRIPTION_THEME_1 = Тема для використання у DSiMenu++.
DESCRIPTION_THEME_2 = Натисніть A для підтеми.

DESCRIPTION_LASTPLAYEDROM_1 = Якщо увімкнуто,
DESCRIPTION_LASTPLAYEDROM_2 = утримуй B при запуску,
DESCRIPTION_LASTPLAYEDROM_3 = перейде до меню вибору ROMів.
DESCRIPTION_LASTPLAYEDROM_4 = Натисніть Y для запуску останнього ROMу.

DESCRIPTION_DSIMENUPPLOGO_1 = Логотип DSiMenu++ буде
DESCRIPTION_DSIMENUPPLOGO_2 = показано, коли ви запустите
DESCRIPTION_DSIMENUPPLOGO_3 = DSiMenu++.

DESCRIPTION_DIRECTORIES_1 = Якшо ви у папці, де є більшість
DESCRIPTION_DIRECTORIES_2 = ваших ігор, то це буде надійно для
DESCRIPTION_DIRECTORIES_3 = приховання каталогів/папок.

DESCRIPTION_BOXART_1 = Для відображення у верхньому екрані
DESCRIPTION_BOXART_2 = обкладинок DSi/3DS.

DESCRIPTION_ANIMATEDSIICONS_1 = Анімувати збільшення іконок DSi, як у
DESCRIPTION_ANIMATEDSIICONS_2 = Меню DSi/3DS. Вимкнення анімаії
DESCRIPTION_ANIMATEDSIICONS_3 = виправить появу білих значків.

DESCRIPTION_STARTBUTTONLAUNCH_1 = Кнопка START буде використовуватись
DESCRIPTION_STARTBUTTONLAUNCH_2 = для запуску ігр замість A, проте A
DESCRIPTION_STARTBUTTONLAUNCH_3 = буде викликати ігрове налаштування.

DESCRIPTION_SYSTEMSETTINGS_1 = Натисніть A для зміни налаштувань
DESCRIPTION_SYSTEMSETTINGS_2 = пов'язані з системою DSi.

DESCRIPTION_REPLACEDSIMENU_1 = Запускати DSiMenu++ при запуску,
DESCRIPTION_REPLACEDSIMENU_2 = замість звичайного Меню DSi?

DESCRIPTION_RESTOREDSIMENU_1 = Знову показувати Меню DSi при запуску?

; Games/Apps settings
LANGUAGE = Мова
CPUSPEED = Швидкість ЦП ARM9
DEBUG = Відлагоджувати
ROMREADLED = Діод інформує про ROM
ASYNCPREFETCH = Асинхронна предвибірка
SNDFREQ = Частота Звуку/Мікрофону
SLOT1LAUNCHMETHOD = Слот-1 метод запуску
LOADINGSCREEN = Екран завантаження
BOOTSTRAP = Завантажувач
USEGBARUNNER2 = Використовувати GBARunner2

SYSTEM = Системна
ON = Вкл.
OFF = Викл.
YES = Так
NO = Ні
NONE = Жоден
POWER = Живлення
CAMERA = Камера
REBOOT = Перезапуск
DIRECT = Безпосередній
REGULAR = Звичайний
RELEASE = Стабільний
NIGHTLY = Нічний

DESCRIPTION_LANGUAGE_1 = Налаштувавши даний параметр,
DESCRIPTION_LANGUAGE_2 = ви уникните обмеження
DESCRIPTION_LANGUAGE_3 = вибору мови.

DESCRIPTION_CPUSPEED_1 = Встановивши TWL - ви позбудетесь
DESCRIPTION_CPUSPEED_2 = підторможувань в деяких іграх.

DESCRIPTION_DEBUG_1 = Буде відображений деякий текст
DESCRIPTION_DEBUG_2 = перед запуском гри.

DESCRIPTION_ROMREADLED_1 = Діод слугує індикатором читання ROMу.

DESCRIPTION_ASYNCPREFETCH_1 = Можна зробити плавне відтворення
DESCRIPTION_ASYNCPREFETCH_2 = відео/музики.
DESCRIPTION_ASYNCPREFETCH_3 = Може обірвати деякі ігри.

DESCRIPTION_SNDFREQ_1 = 32.73 кГц: Оригінальна якість
DESCRIPTION_SNDFREQ_2 = 47.61 кГц: Висока якість

DESCRIPTION_SLOT1LAUNCHMETHOD_1 = Змініть це, якщо деякі картриджі
DESCRIPTION_SLOT1LAUNCHMETHOD_2 = не запускаються у Slot-1. Увага!
DESCRIPTION_SLOT1LAUNCHMETHOD_3 = Метод перезапуску - не використовує
DESCRIPTION_SLOT1LAUNCHMETHOD_4 = вибір мови або швидкості ЦП.

DESCRIPTION_LOADINGSCREEN_1 = Показує екран завантаження перед ROMом,
DESCRIPTION_LOADINGSCREEN_2 = що запускається у nds-bootstrap.

DESCRIPTION_BOOTSTRAP_1 = Вибір стабільного чи нічного
DESCRIPTION_BOOTSTRAP_2 = завантажувача.

DESCRIPTION_FLASHCARD_1 = Виберіть карту, яку використовуватимете
DESCRIPTION_FLASHCARD_2 = для запуску ROMів.

DESCRIPTION_GBARUNNER2_1 = Використовуйте або GBARunner2
DESCRIPTION_GBARUNNER2_2 = або рідний режим GBA - для гри в GBA ігри.

; Flashcard(s) settings
FLASHCARD_SELECT = Виберіть карту(и)
LEFTRIGHT_FLASHCARD = Вліво/Вправо: Вибір карт(и)
AB_SETRETURN = A/B: Встановити і повернутись

; Sub-theme select
SUBTHEMESEL_DSI = Вибір підтеми: Меню DSi
SUBTHEMESEL_3DS = Вибір підтеми: ДОМАШНЄ Меню 3DS
SUBTHEMESEL_R4 = Вибір підтеми: R4
AB_SETSUBTHEME = A/B: Встановити підтему
DSI_DARKMENU = SD/Темне Меню
DSI_NORMALMENU = Звичайне Меню
R4_THEME01 = 01: Сніговий пагорб
R4_THEME02 = 02: Засніжена земля
R4_THEME03 = 03: Зелений лист
R4_THEME04 = 04: Рожеві троянди
R4_THEME05 = 05: Парк
R4_THEME06 = 06: Вишневий цвіт
R4_THEME07 = 07: Пляж
R4_THEME08 = 08: Літнє небо
R4_THEME09 = 09: Річка
R4_THEME10 = 10: Осінні дерева
R4_THEME11 = 11: Різдв'яна ялинка
R4_THEME12 = 12: Червоний символ
R4_THEME13 = 13: Синій місяць

**Comment by IRONKAGE** [comment]
DSiMenu++ Translated
[Ukrainian]
SAVING_SETTINGS = Збереження налаштувань...
SETTINGS_SAVED = Налаштування збережено!

LR_SWITCH = L/R/Y/X Перемикання сторінок
GUI_SETTINGS = Налаштування ГІК
GAMESAPPS_SETTINGS = Налаштування Ігор та Застосунків

; GUI settings
THEME = Тема
LASTPLAYEDROM = Запускається останній ROM при запуску
DSIMENUPPLOGO = DSiMenu++ логотип при запуску
DIRECTORIES = Каталоги/папки
BOXART = Коробкові/Ігрові обкладинки
ANIMATEDSIICONS = Анімувати DSi значки
STARTBUTTONLAUNCH = Запускати кнопкою START
SYSTEMSETTINGS = Системні Налаштування
REPLACEDSIMENU = Замінити Меню DSi
RESTOREDSIMENU = Відновити Меню DSi

SHOW = Показати
HIDE = Приховати

DESCRIPTION_THEME_1 = Тема для використання у DSiMenu++.
DESCRIPTION_THEME_2 = Натисніть A для підтеми.

DESCRIPTION_LASTPLAYEDROM_1 = Якщо увімкнуто,
DESCRIPTION_LASTPLAYEDROM_2 = утримуй B при запуску,
DESCRIPTION_LASTPLAYEDROM_3 = перейде до меню вибору ROMів.
DESCRIPTION_LASTPLAYEDROM_4 = Натисніть Y для запуску останнього ROMу.

DESCRIPTION_DSIMENUPPLOGO_1 = Логотип DSiMenu++ буде
DESCRIPTION_DSIMENUPPLOGO_2 = показано, коли ви запустите
DESCRIPTION_DSIMENUPPLOGO_3 = DSiMenu++.

DESCRIPTION_DIRECTORIES_1 = Якшо ви у папці, де є більшість
DESCRIPTION_DIRECTORIES_2 = ваших ігор, то це буде надійно для
DESCRIPTION_DIRECTORIES_3 = приховання каталогів/папок.

DESCRIPTION_BOXART_1 = Для відображення у верхньому екрані
DESCRIPTION_BOXART_2 = обкладинок DSi/3DS.

DESCRIPTION_ANIMATEDSIICONS_1 = Анімувати збільшення іконок DSi, як у
DESCRIPTION_ANIMATEDSIICONS_2 = Меню DSi/3DS. Вимкнення анімаії
DESCRIPTION_ANIMATEDSIICONS_3 = виправить появу білих значків.

DESCRIPTION_STARTBUTTONLAUNCH_1 = Кнопка START буде використовуватись
DESCRIPTION_STARTBUTTONLAUNCH_2 = для запуску ігр замість A, проте A
DESCRIPTION_STARTBUTTONLAUNCH_3 = буде викликати ігрове налаштування.

DESCRIPTION_SYSTEMSETTINGS_1 = Натисніть A для зміни налаштувань
DESCRIPTION_SYSTEMSETTINGS_2 = пов'язані з системою DSi.

DESCRIPTION_REPLACEDSIMENU_1 = Запускати DSiMenu++ при запуску,
DESCRIPTION_REPLACEDSIMENU_2 = замість звичайного Меню DSi?

DESCRIPTION_RESTOREDSIMENU_1 = Знову показувати Меню DSi при запуску?

; Games/Apps settings
LANGUAGE = Мова
CPUSPEED = Швидкість ЦП ARM9
DEBUG = Відлагоджувати
ROMREADLED = Діод інформує про ROM
ASYNCPREFETCH = Асинхронна предвибірка
SNDFREQ = Частота Звуку/Мікрофону
SLOT1LAUNCHMETHOD = Слот-1 метод запуску
LOADINGSCREEN = Екран завантаження
BOOTSTRAP = Завантажувач
USEGBARUNNER2 = Використовувати GBARunner2

SYSTEM = Системна
ON = Вкл.
OFF = Викл.
YES = Так
NO = Ні
NONE = Жоден
POWER = Живлення
CAMERA = Камера
REBOOT = Перезапуск
DIRECT = Безпосередній
REGULAR = Звичайний
RELEASE = Стабільний
NIGHTLY = Нічний

DESCRIPTION_LANGUAGE_1 = Налаштувавши даний параметр,
DESCRIPTION_LANGUAGE_2 = ви уникните обмеження
DESCRIPTION_LANGUAGE_3 = вибору мови.

DESCRIPTION_CPUSPEED_1 = Встановивши TWL - ви позбудетесь
DESCRIPTION_CPUSPEED_2 = підторможувань в деяких іграх.

DESCRIPTION_DEBUG_1 = Буде відображений деякий текст
DESCRIPTION_DEBUG_2 = перед запуском гри.

DESCRIPTION_ROMREADLED_1 = Діод слугує індикатором читання ROMу.

DESCRIPTION_ASYNCPREFETCH_1 = Можна зробити плавне відтворення
DESCRIPTION_ASYNCPREFETCH_2 = відео/музики.
DESCRIPTION_ASYNCPREFETCH_3 = Може обірвати деякі ігри.

DESCRIPTION_SNDFREQ_1 = 32.73 кГц: Оригінальна якість
DESCRIPTION_SNDFREQ_2 = 47.61 кГц: Висока якість

DESCRIPTION_SLOT1LAUNCHMETHOD_1 = Змініть це, якщо деякі картриджі
DESCRIPTION_SLOT1LAUNCHMETHOD_2 = не запускаються у Slot-1. Увага!
DESCRIPTION_SLOT1LAUNCHMETHOD_3 = Метод перезапуску - не використовує
DESCRIPTION_SLOT1LAUNCHMETHOD_4 = вибір мови або швидкості ЦП.

DESCRIPTION_LOADINGSCREEN_1 = Показує екран завантаження перед ROMом,
DESCRIPTION_LOADINGSCREEN_2 = що запускається у nds-bootstrap.

DESCRIPTION_BOOTSTRAP_1 = Вибір стабільного чи нічного
DESCRIPTION_BOOTSTRAP_2 = завантажувача.

DESCRIPTION_FLASHCARD_1 = Виберіть карту, яку використовуватимете
DESCRIPTION_FLASHCARD_2 = для запуску ROMів.

DESCRIPTION_GBARUNNER2_1 = Використовуйте або GBARunner2
DESCRIPTION_GBARUNNER2_2 = або рідний режим GBA - для гри в GBA ігри.

; Flashcard(s) settings
FLASHCARD_SELECT = Виберіть карту(и)
LEFTRIGHT_FLASHCARD = Вліво/Вправо: Вибір карт(и)
AB_SETRETURN = A/B: Встановити і повернутись

; Sub-theme select
SUBTHEMESEL_DSI = Вибір підтеми: Меню DSi
SUBTHEMESEL_3DS = Вибір підтеми: ДОМАШНЄ Меню 3DS
SUBTHEMESEL_R4 = Вибір підтеми: R4
AB_SETSUBTHEME = A/B: Встановити підтему
DSI_DARKMENU = SD/Темне Меню
DSI_NORMALMENU = Звичайне Меню
R4_THEME01 = 01: Сніговий пагорб
R4_THEME02 = 02: Засніжена земля
R4_THEME03 = 03: Зелений лист
R4_THEME04 = 04: Рожеві троянди
R4_THEME05 = 05: Парк
R4_THEME06 = 06: Вишневий цвіт
R4_THEME07 = 07: Пляж
R4_THEME08 = 08: Літнє небо
R4_THEME09 = 09: Річка
R4_THEME10 = 10: Осінні дерева
R4_THEME11 = 11: Різдв'яна ялинка
R4_THEME12 = 12: Червоний символ
R4_THEME13 = 13: Синій місяць

**Comment by IRONKAGE** [comment]
Settings = Налаштування
START = ЗАПУСК
Back = Назад
L Previous = L Попередній
Next R = Наступний R

**Comment by Robz8** [comment]
@NightYoshi370 No, but it's still possible for the app itself to support it, except there's no Ukrainian font to use.

**Comment by IRONKAGE** [comment]
@Robz8 What font format support?

**Comment by IRONKAGE** [comment]
@NightYoshi370 All Game consoles not supported Ukrainian language, but it's possible =)

**Comment by RonnChyran** [comment]
@IRONKAGE  Check the work done in #148 and #140.Some form of font page switching will also need to be implemented, since the Cyrillic UTF16 code point range does not fit in the small amount of VRAM that the DSi has.

I believe the DSi system menu font does have Cyrillic glyphs, to dump those from a copy of 
TWLFontTable.dat, see [twlfonttools](https://github.com/RonnChyran/twlfonttools).

**Comment by NightYoshi370** [comment]
@IRONKAGE can you send a pull request with these changes?

**Comment by IRONKAGE** [comment]
@NightYoshi370 Where to send request?

**Comment by NightYoshi370** [comment]
Welp, this is late, but @RocketRobz & @Epicpkmn11, these are most likely outdated, right?
Also, @IRONKAGE, if it's up to date, I'll add it for you

**Comment by IRONKAGE** [comment]
It's actually, but now I not good understand programming, but I now
Ukrainian and English (and another's)
I will translate for Ukrainian people's =)

Чт, 14 лют. 2019, 22:19 NightYoshi370 користувач notifications@github.com
пише:

**Comment by Epicpkmn11** [comment]
Ukrainian is now finally able to be supported in the DSi-based themes and Settings, so if you're still interested in translating I can add Ukrainian to https://crowdin.com/project/TWiLightMenu (which is where we now have set up for making translating more convenient)

**Comment by IRONKAGE** [comment]
@Epicpkmn11 Good new

**Comment by NightYoshi370** [comment]
Seems like Ukrainian is now part of the crowdin project. Please use that instead, since we'd like to keep all translations in one spot.
Closing
