### ISSUE TITLE
Twilight Menu can't install

### ISSUE THREAD

**Issue by Tsathogga** [DS-Homebrew/TWiLightMenu#1313]
**Console Configuration:**Nintendo Old3ds --> 
**TWiLight Menu++ Version:** Can't install
**TWiLight Menu++ Theme:** 

I have a problem installing the Twilight Menu cia. It just doesn't install. I already tested with another SD and does not install. I already tested with Twilight Updater and does not install. The unlocking was done on the 14th.
![1610831998087](https://user-images.githubusercontent.com/77553069/104823241-af789a80-5840-11eb-9cae-46f01246dce1.jpg)

**Comment by RocketRobz** [comment]
How are you running FBI?

**Comment by Tsathogga** [comment]
> How are you running FBI?

With Homebrew :V

**Comment by Tsathogga** [comment]
> How are you running FBI?

I did the unlocking all right. But only the TM cia that does not install. The others, games, are installing normal.

**Comment by RocketRobz** [comment]
What about other DSiWare CIAs?

**Comment by Tsathogga** [comment]
> What about other DSiWare CIAs?

![1610836059837](https://user-images.githubusercontent.com/77553069/104824507-19e20880-584a-11eb-9a40-f6a662d4ff7d.jpg)
I don't have any dsiware.

**Comment by RocketRobz** [comment]
I know you're obviously using homebrew, but what application are you using to boot FBI?

**Comment by Tsathogga** [comment]
![1610837805227](https://user-images.githubusercontent.com/77553069/104824916-2d8f6e00-584e-11eb-8470-6601bf828536.jpg)

I do not know. I just followed a tutorial. I don't understand these things. I thought the FBI used the program itself to open.

**Comment by RocketRobz** [comment]
I'm out of ideas then.
