### ISSUE TITLE
Alphabetical arrangement does not sort properly

### ISSUE THREAD

**Issue by elijah0067** [DS-Homebrew/TWiLightMenu#1314]
**Console Configuration:** Twilight Menu installed in a flashcard (R4i+ RTS Gold) tested on: DS, DSi 1.4.5 (Hiya CFW), and 3DS 
**TWiLight Menu++ Version:** v18.2.1
**TWiLight Menu++ Theme:** Original R4 (My bug report covers every theme.)

### Expected behaviour

Roms and folders must be listed alphabetically:
ROM Alphabetical Arrangement:
[...]
1 vs 100 (USA).nds
007 - Blood Stone (USA).nds
11 Card Games (EUR).nds
101 in 1 Sports Megamix (USA).nds
1001 Touch Games (USA).nds
1500 DS Spirits - Mahjong (Japan).nds
iCarly (USA).nds
I'm a Celebrity - Get me out of here! (USA).nds

FOLDER Alphabetical Arrangement:
[...]                <- Return to previous directory (Not a folder) 
[#]
[A]
[B]

### Actual behaviour

Roms and folders are not listed alphabetically:
ROM Arrangement:
007 - Blood Stone (USA).nds      
1 vs 100 (USA).nds
1001 Touch Games (USA).nds
101 in 1 Sports Megamix (USA).nds      
11 Card Games (EUR).nds
1500 DS Spirits - Mahjong (Japan).nds
I'm a Celebrity - Get me out of here! (USA).nds 
iCarly (USA).nds

FOLDER Arrangement:
[#]
[...]                <- Return to previous directory (Not a folder)          
[A]
[B]

### Steps to reproduce

1. Copy a bunch of roms with a filename starting with a number. Roms starting with a letter is fine but not those with filenames (roms) starting with a number
2. Copy a bunch of roms that has a special character after first letter. (ex: "I'm")
3. Create folders starting with special character ("#" as an example)

**Comment by gek169** [comment]
technically speaking, this isn't a bug, this *is* alphabetical sorting.

It's treating numerical characters as if they were letters. Think about it.

if you want your roms to be sorted correctly, pad all numbers with preceding zeroes so that all numbers have the same number of digits.

**Comment by NightYoshi370** [comment]
This is normal for alphanumeric sorters out there. The names of your folder are the issue.
Please rename them.

Closing...
