### ISSUE TITLE
Freezes as soon as the DSi theme loads up

### ISSUE THREAD

**Issue by RhanCandia** [DS-Homebrew/TWiLightMenu#1318]
**Console Configuration:** New Nintendo 3DS with Luma3DS
**TWiLight Menu++ Version:** 18.3
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

A freshly installed 18.3 TWMenu++. On launch, be able to navigate through the TWMenu.

### Actual behaviour

On launch, after both the DSi intro and TWMenu++ intro, the Nintendo DSi theme (default) loads up and then the first folder icon bounces and immediately freeze. Unable to navigate or access the settings.

### Steps to reproduce

1. Launch TWMenu++.
2. Wait for the intro/splash to finish.
3. Watch the DSi theme get loaded and then after the first folder bounces it freezes.

### Workaround

1. Launch TWMenu++.
2. While the TWMenu splash is playing, keep pressing SELECT.
3. Settings will show up and change theme to New 3DS.

**Comment by RocketRobz** [comment]
If this bug is consistent, try reformatting the SD card to FAT32 with 32kb cluster size, or just simply reformat with 32kb cluster size, if it's already FAT32.
If that doesn't fix it, open TWLMenu++ Settings by holding SELECT during the TWLMenu++ intro, then turn off `Photo/box art color deband`.

**Comment by RhanCandia** [comment]
> If this bug is consistent, try reformatting the SD card to FAT32 with 32kb cluster size, or just simply reformat with 32kb cluster size, if it's already FAT32.
> If that doesn't fix it, open TWLMenu++ Settings by holding SELECT during the TWLMenu++ intro, then turn off `Photo/box art color deband`.

I've added a workaround just now. I think the problem is the DSi theme. I'm afraid reformatting the sd card is not an option right now. Thanks for the response.

**Comment by RocketRobz** [comment]
Was the workaround just disabling said option?

**Comment by RhanCandia** [comment]
> Was the workaround just disabling the color deband option?

I'll give that a try next and report back.

**Comment by RhanCandia** [comment]
> Was the workaround just disabling the color deband option?

Okay. I disabled the option you've mentioned and it fixed the problem.

**Comment by RocketRobz** [comment]
Great! Nice to know that it fixed it for you.
