### ISSUE TITLE
The nintendo logo didn't show

### ISSUE THREAD

**Issue by zeroultima6** [DS-Homebrew/TWiLightMenu#1322]
**Console Configuration:**  
**TWiLight Menu++ Version:** 18.3
**TWiLight Menu++ Theme:** 

### Expected behaviour

The splash screen shows the nintendo logo on startup

### Actual behaviour

It didn't show up on startup, options are on for it

### Steps to reproduce

1.
2.
3.

**Comment by Epicpkmn11** [comment]
Do you have a cartridge in? It only shows if there's a cartridge in, just like the official splash

**Comment by zeroultima6** [comment]
Ok it makes sense, didn't notice it at that time.
