### ISSUE TITLE
TWiLight Menu does not boot on EmuNAND Japanese New 2DS

### ISSUE THREAD

**Issue by INFINITE-PIKA** [DS-Homebrew/TWiLightMenu#1324]
System details: New Nintendo 2DS, EmuNAND v11.14.0-46J Luma+Boot9Strap CFW
TWiLightMenu version: v18.3.0
Theme: Nintendo 3DS Suicune (left over from my SD card used by my SysNAND as well as EmuNAND)

### Expected behaviour

Menu boots like normal, DS games are able to be played

### Actual behaviour

After clicking on icon, title crashes and says:

```
An error occurred (ErrDisp)
Error type: generic

Process ID: 19
Process name: am
Process title ID: 0x0004013000001502

Address: 0x001093aa
Error code: 0xc8804478

Press any button to reboot
```

### Steps to reproduce

1. Use Japanese New 2DS (I used EmuNAND on a USA version)
2. Boot TWiLightMenu
3. There should be no Nintendo screen, with a process error (in English) with hex code

**Comment by RocketRobz** [comment]
Is TWiLight Menu++ installed on both SysNAND and EmuNAND?

**Comment by INFINITE-PIKA** [comment]
> Is TWiLight Menu++ installed on both SysNAND and EmuNAND?

Yes, it is

**Comment by RocketRobz** [comment]
Try following [this](https://3ds.hacks.guide/move-emunand) guide to move EmuNAND to SysNAND then.

**Comment by INFINITE-PIKA** [comment]
I can use it on my SysNAND no problem though, so do you think this could be an issue with my EmuNAND, or just Japanese systems trying to boot TWL menu in general? I'd rather not move my Emu to Sys (if I can help it, that is, but if you want me to I can tomorrow).

**Comment by RocketRobz** [comment]
I have no idea.

**Comment by INFINITE-PIKA** [comment]
Alright, I assume that this isn't a high priority for you, so I'll go ahead and close it?

**Comment by RocketRobz** [comment]
Yes. This isn't something I can fix.

**Comment by INFINITE-PIKA** [comment]
Alright, thank you for your time then!

**Comment by INFINITE-PIKA** [comment]
You were right about moving it to SysNAND, I did because I just wanted my DS in Japanese to help my studying, and it worked.
