### ISSUE TITLE
White screen after I boot a game

### ISSUE THREAD

**Issue by Fruit234** [DS-Homebrew/TWiLightMenu#1327]
When I try to play a game, it stays on a white screen and then after a while the bottom screen goes black.

**Console Configuration:**  New 3DS XL, Luma 3DS 10.2.1 and FW 11.14.0-46U
**TWiLight Menu++ Version:** 18.33
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

 The game should play.

### Actual behaviour

 It stays on a white screen for around 10 minutes and then the top screen is white and the bottom screen is black.

### Steps to reproduce

1. launch TWilight menu
2. Select the game
3. Profit

**Comment by RocketRobz** [comment]
Which games?

**Comment by Fruit234** [comment]
I've tried Pokemon platinum, New Super Mario bros, and Black 2

**Comment by RocketRobz** [comment]
Try reformatting the SD card to FAT32 with 32kb cluster size (even if already using FAT32).

**Comment by Fruit234** [comment]
(Sorry for the late reply)

Nope. It's still a white screen

**Comment by RocketRobz** [comment]
Either your SD card is dying, or idk what else is wrong.
