### ISSUE TITLE
Possibility to add input redirection and maybe even streaming support? 

### ISSUE THREAD

**Issue by linusrg1** [DS-Homebrew/TWiLightMenu#1332]
**Is your feature request related to a problem? Please describe.**
It would be cool if I could use a controller with ds games on my 3ds. 
**Describe the solution you'd like**
The ability to use a controller with ds games, and maybe even stream them. 
**Describe alternatives you've considered**
Emulation, but that has its own issues.

**Comment by INFINITE-PIKA** [comment]
There's huge limitations with ds stuff as opposed to 3ds, and the LUMA team doesn't want to/can't do ROSALINA in twl stuff, at least I've heard. Also, isn't TWiLight menu emulation, too? Sorta? I dunno. I'd recommend emulation, although this is a super good idea(s)!

**Comment by RocketRobz** [comment]
TWiLight Menu++ and nds-bootstrap run in native DS mode, so there's no emulation involved.
Thus, input redirection and streaming support probably aren't possible.

**Comment by zs2212221** [comment]
@RocketRobz This is a feature that I'd like to possible develop... what would it take to implement at least input redirection? Would this functionality need to be added to nds-bootstrap?

Ideally if input redirection could be done in DS mode, GBA games would work too using GBARunner2.

**Comment by RocketRobz** [comment]
Yes, it would need to be implemented to nds-bootstrap.
