### ISSUE TITLE
Small delay in the appearance of the loading bar

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/TWiLightMenu#1337]
**Console Configuration:** Nintendo DSi XL with Unlaunch
**TWiLight Menu++ Version:** 18.04
**TWiLight Menu++ Theme:** Nintendo DSi (light skin)
### Expected behaviour
After turning on the console and loading TM ++, enter any folder and the loading bar will appear (its appearance time will depend on the number of files / ROMs) 

### Actual behaviour
After turning on the console and loading TM ++, you enter a folder and there is a delay in the appearance of the loading bar (white screen).
This only happens the first time after turning on the console and entering a folder, whatever it is. Then it works properly.
I know it is a minor detail. But I wanted to report it since in previous versions it didn't happen.

Illustrative video attached: 

https://user-images.githubusercontent.com/70182567/106496549-c273a780-649b-11eb-9763-a38f1065ef72.mp4

**Comment by RocketRobz** [comment]
Unfortunately, there's no way to have a loading bar shown when getting the file list, as there's no info on how many files are in the directory.
