### ISSUE TITLE
Crash when starting TwilightMenu

### ISSUE THREAD

**Issue by moujib85** [DS-Homebrew/TWiLightMenu#1343]
Hello,

On my nintendo 2ds installed twilightmenu latest version with latest luma but I'm getting an error when starting 
Did the cfw twice , changed the sdcard twice 16gb and 8 gb always having the issue.
The console has no hardware issues.

![IMG_20210206_222652](https://user-images.githubusercontent.com/3957560/107139697-88802680-691d-11eb-859b-70990aae1f7b.jpg)

**Comment by Epicpkmn11** [comment]
Try following this: https://3ds.hacks.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

**Comment by moujib85** [comment]
Thank you Epicpkmn11 it worked !
