### ISSUE TITLE
Crashed Homebrew and Luma3ds

### ISSUE THREAD

**Issue by BrazilReich** [DS-Homebrew/TWiLightMenu#1349]
O3ds with Luma3ds v10.2.1
**v.35.s5** 
**White Theme Dsi:** 

### Expected behaviour

Open DS Download Play

### Actual behaviour

Crashed all LUMA3DS, Godmode9 and Homebrew
### Steps to reproduce

1. Open TWL Settings
2.Place DSi light theme
3.Open Download Play

**Comment by BrazilReich** [comment]
version 0.35.s5**

**Comment by RocketRobz** [comment]
I don't understand...
Let's move this to the Discord server: https://discord.gg/yD3spjv
