### ISSUE TITLE
Como coloco trucos al twilightmenu?

### ISSUE THREAD

**Issue by nigthmare77** [DS-Homebrew/TWiLightMenu#1358]

**Comment by urmum-69** [comment]
For next time, you should ask for support on the [discord server](https://discord.gg/yD3spjv), in English.
The answer to your question can be found here:
https://wiki.ds-homebrew.com/twilightmenu/faq#how-do-i-use-cheats
And in Spanish:
https://wiki.ds-homebrew.com/es-ES/twilightmenu/faq#p-c%C3%B3mo-puedo-usar-trucos

**Comment by caydenpri44** [comment]
Donwload the usercheat.dat 
or download Action Replay
or download Nitrohax3DS (if you have 3DS)
