### ISSUE TITLE
Twilight menu launch problem

### ISSUE THREAD

**Issue by DimmaOSB** [DS-Homebrew/TWiLightMenu#1359]
**Console Configuration: Old Nintendo 3DS XL with Luma3DS**  Ver. 11.5.0-38E
**TWiLight Menu++ Version: After-Valentines 2021 with nds-bootstrap v0.36.0 (100th release!)** 
**TWiLight Menu++ Theme:**  N/A

### Expected behaviour

Twilight menu should launch up on DS menu

### Actual behaviour

So I've just found out about Twilight today and decided to install it in order to play a couple old DS games on my 3DS. I have carefully followed the instructions on how to completely install Twilight from https://www.cfwaifu.com/twilight-menu-3ds/. However after following all their instructions I finally got to the end where I could finally open the app after applying the latest updates from the updater app but it wouldn't let me. The screen either goes pitch black or loads up a screen that says something along the lines of error occurred and then gives me options to shut down the system or to save crash load I think. Im not sure if I've done anything wrong whilst installing it because I've deleted and installed twilight twice now and it still does the same thing.

### Steps to reproduce

1. Should I follow steps from another website
2. Did I do something wrong whilst installing
3.

**Comment by Epicpkmn11** [comment]
The cfwaifu guide is rather outdated, https://wiki.ds-homebrew.com/twilightmenu/installing-3ds is the official guide so it's better to use that.

But I don't think that's your current problem, it sounds like you need to follow this: https://3ds.hacks.guide/troubleshooting#dsi--ds-functionality-is-broken-after-completing-the-guide

**Comment by DimmaOSB** [comment]
Oh ok then thank you for the fast reply. I will definitely try those methods right now.

**Comment by DimmaOSB** [comment]
Ok so I followed the instructions from the link you provided but now when I've turned on the 3DS it just takes me to same black screen saying an exception occurred and wont even let me access the 3DS completely.

It says:
An exception occurred
Processor: Arm11 (core 1)
Exception type: undefined instruction
Current process: pm (Bunch of zeros)
And then below it says Press A to save the crash dump, press any other button to shutdown

Im not sure where I go from here tbh

**Comment by Epicpkmn11** [comment]
Hmm, maybe make sure you're on the latest version of Luma3DS, the latest system update broke previous versions and since the TWLFix instructions have you update it might've broken that: https://github.com/LumaTeam/Luma3DS/releases

**Comment by DimmaOSB** [comment]
Ok then thanks

**Comment by DimmaOSB** [comment]
Ok yeah everything is working now thank you so much for the help!
