### ISSUE TITLE
Twilight menu stuck on loading folder at launch

### ISSUE THREAD

**Issue by tohumaster69420** [DS-Homebrew/TWiLightMenu#1365]
**Console Configuration:** 
New Nintendo 2DS with Luma3DS
**TWiLight Menu++ Version:** 
I have no idea how to figure this out because I can’t access twilight menu settings
**TWiLight Menu++ Theme:**
 SEGA Saturn

### Expected behaviour 

twilight menu loads up into the main menu like normal

### Actual behaviour

Twilight menu tries to load back into a folder with a crapload of gameboy roms that causes it to stay on the loading screen

### Steps to reproduce

1. Try to go into a folder with loads of items inside
2. Folder wont load
3.close twilight menu
4. Reopen twilight menu
5. Twilight menu tries to load folder with loads of items that causes it to softlock

**Comment by RocketRobz** [comment]
Please split the ROMs into separate folders.
