### ISSUE TITLE
Error Disp 

### ISSUE THREAD

**Issue by shalinrox123** [DS-Homebrew/TWiLightMenu#1372]
**Console Configuration:**  OLD Nintendo 3DS with Luma3DS). Please include firmwares where possible. 
**TWiLight Menu++ Version:** 1.1 for 3ds 
**TWiLight Menu++ Theme:** i didnt know there were skins, i just downloaded the cia files 

### Actual behaviour
 I get a errordisp message : https://ibb.co/jbXVgtC 

### Steps to reproduce

1. Download twilightmenu files
2. Download and run TWLFix-3DS.3dsx (i was following a tutorial and they said to run this if i had a black screen before launching the nds games. prior to running this everything worked fine)
3.  open twilight menu and then you get the error

**Comment by shalinrox123** [comment]
I tried formatting the sd card and reinstalling twilight menue over and over again and i still get the error

**Comment by RocketRobz** [comment]
1.1 doesn't look right.
Is that the launcher version, or the TWLMenu++ version?
If the first, make sure you got the latest version.

**Comment by shalinrox123** [comment]
i cant find the twilight menu in my data management to be able to delete it to reinstall so i downloaded and installed the 2021 after valentines day release and im still getting the same issue

**Comment by RocketRobz** [comment]
Please join this Discord server for assistance: https://discord.gg/yD3spjv
