### ISSUE TITLE
Top screen gets squished in the menu and games are not playing in widescreen.

### ISSUE THREAD

**Issue by ThibeauDS** [DS-Homebrew/TWiLightMenu#1377]
**Console Configuration:** old Nintendo 3DS (11.14.0-46E) with luma (10.2.1-c058e3f) 
**TWiLight Menu++ Version:** after-valentines (2021) release (nds-bootstrap Ver. Release v0.36.0)
**TWiLight Menu++ Theme:** Nintendo DSi, Dark skin

### Expected behaviour

After I followed the tutorial from your website (with some differend is key combinations) it gives a new option to enable widescreen (16:10) instead of the standard (4:3). After enabling it it should enable widescreen.

### Actual behaviour

In the menu the top screen gets squished and only in the menu. If I open the settings of TWLmenu or a game, the screen ratio is 4:3 even when 16:10 (wide) is enabled.
Even when I open TWLMenu++ I see it's starting from squished to 4:3 in the boot process.

### Steps to reproduce

1. Open TWPatch
2. Hold Y and and press B
3. Press A on GPU scaling (blurry, no filters)
4. Press B to go back
5. Hold START to begin patching
6. After the loading and when promted hold SELECT
7. Hold SELECT while booting to enable external FIRMs and modules
8. Launching TWLight Menu ++ RocketRobz
9. Press SELECT go to TWLMenu++ Settings
10. Press L and set Screen Aspect Ratio 16:10 (wide)

**Comment by hansoljin** [comment]
Between step 2 and step 3, you forgot to enable "Widescreen patch (384x240 16:10)".

**Comment by ThibeauDS** [comment]
Ok, let me try that real quick.

**Comment by ThibeauDS** [comment]
Alright, thank you for helping and responding so quickly.
