### ISSUE TITLE
Integration with Pokémon Dream Radar

### ISSUE THREAD

**Issue by CapNinja** [DS-Homebrew/TWiLightMenu#138]
That's it. A way to integrate Dsimenu ++ and pokémon dream radar to send legit pokémon.

**Comment by shutterbug2000** [comment]
Not *easily* possible. I'll keep this open as I have some ideas, but it's not gonna be for a while.

**Comment by legoj15** [comment]
I was always thinking that it would be unreal if there was a way to send Pokémon from lets say Soul Silver (or any other DS Pokémon game) to the Pokémon bank like you would from an actual cart but using a nds-bootstrap save. Sounds outlandish, I know, but this reminded me of that thought.

**Comment by pikachuk** [comment]
You could send a pokemon to the pokebank, but it would require to dump your saves from your ds and 3ds pokemon game  and use PKHEX to transfer the pokemon from your DS game to your 3ds game, it would still be a legit pokemon, then you can send your pokemon to the pokebank from your 3ds pokemon game

**Comment by FlameKat53** [comment]
hmm, this is a thing that would be implemented into TWiLight Menu++ and not nds-bootstrap or even Dream Radar itself?

**Comment by NightYoshi370** [comment]
This feels outside the scope of TWiLight Menu. I'm gonna close this
