### ISSUE TITLE
Touchscreen doesn't work

### ISSUE THREAD

**Issue by CristianOrtega97** [DS-Homebrew/TWiLightMenu#1386]
**Console Configuration: This is on a DSi XL JAP (I just changed the TM to English)->

### Steps to reproduce

1. Run Twilight Menu (works normal)
2. Run Game (backup -> can't use touchscreen but game have sound and  still running)
3.  Run Cartridge (

https://user-images.githubusercontent.com/14861982/111446504-18aa4c00-86d2-11eb-8a78-b55f5def845a.mp4

can't use touchscreen but game have sound and  still running)

**Comment by CristianOrtega97** [comment]
Bug fixed itself. I just opened the regular DSi screen used the touchscreen on photo app and then it worked on every game.

Closing ticket

**Comment by VersedXth** [comment]
I'm having the same problem on my Japanese DSi. but using the photoapp doenst work for me. This problem only exists with games on the SD-Card. with normal Cartriges everthing works fine
