### ISSUE TITLE
Hotel Dusk: Room 215 Korean version error

### ISSUE THREAD

**Issue by sadnas** [DS-Homebrew/TWiLightMenu#1387]
Console configuration: New nintendo 3ds with luma

Twilightmenu version : v19.0.0

Expected behavior : works normally

Actual behavior : error

Steps to reproduce

1. Use the cheat code to solve this problem.
2. I turn on the game.
3. Error

https://user-images.githubusercontent.com/80848393/111516226-03e3bc00-8797-11eb-9e6e-94da0b7b140e.mp4

**Comment by RocketRobz** [comment]
What happens if the cheat code is disabled?

**Comment by sadnas** [comment]
> What happens if the cheat code is disabled?



> What happens if the cheat code is disabled?

It doesn't work when the Cheat is disabled. The same error occurs.

**Comment by hansoljin** [comment]
> It doesn't work when the Cheat code is disabled. The same error occurs.

Can you send your usrcheat.dat? I want to check this myself. (I can read it)

**Comment by appff** [comment]
is this solved right now? I encountered this problem  on twilight version 21.1.1

**Comment by lifehackerhansol** [comment]
Is it Korean specifically? The issue is kind of dead as the OP didn't respond to my last message.

**Comment by hy1o** [comment]
@lifehackerhansol 
I am not the OP, but here's the cheat information
https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=rhsfks1785&logNo=20062400306

**Comment by lifehackerhansol** [comment]
> @lifehackerhansol
> I am not the OP, but here's the cheat information
> https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=rhsfks1785&logNo=20062400306

That's not a `usrcheat.dat`. TWiLight does not use plaintext AR codes. Which is why I was asking for it, specifically the one OP is using.

**Comment by hy1o** [comment]
Thanks for your interest in this issue.
Actually, this issue is irrelevant to cheats. Whether using the cheat or not, the behavior is the same: black on top screen, white on bottom then freeze. Many people are experiencing this issue, and I can reproduce as well. I downloaded many usercheat.dat that claim to fix this issue but they were using the same code I posted. I tried it as well but it didn't work as OP posted.
And yes, this only occurs in Korean version of Hotel Dusk as far as I know.

**Comment by lifehackerhansol** [comment]
Then a proper issue with details on that bug should be created, as that was not information that was relevant to, or mentioned in, this issue at all until you pointed it out. Maybe Robz did, but anyone else that is seeing this issue would read it very differently.

**Comment by hy1o** [comment]
Sure thing. I'll open a new one. 
Thanks

**Comment by lifehackerhansol** [comment]
Superseded by https://github.com/DS-Homebrew/nds-bootstrap/issues/1236.
