### ISSUE TITLE
Crayon Shin-chan Shokkugan! Densetsu wo Yobu Omake Daiketsusen!! Korean version error

### ISSUE THREAD

**Issue by sadnas** [DS-Homebrew/TWiLightMenu#1389]
Console configuration: New nintendo 3ds with luma

Twilightmenu version : v19.0.0

Expected behavior : works normally

Actual behavior : It works normally, but the game does not work with a black screen.

Steps to reproduce
1. I turn on the game.
2. Title screen works fine
3. Stops with a black screen when entering the stage.

The Japanese version does not have this problem, but only the Korean version does.
The upgrade of the twilightmenu version resolves most of the problems, but is one of the things that has not been resolved.

**Comment by RocketRobz** [comment]
Try updating the nds-bootstrap nightly, and setting it for that game.
