### ISSUE TITLE
Black and green stripes in the Manual (again?)

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/TWiLightMenu#1395]
**Console Configuration**--> Nintendo DSi XL with Unlanch 2.0
**TWiLight Menu++ version** --> 19.0.0
**TWiLight Menu++ Theme:** --> DSi Light 

When you open the TM Manual and browse through it for a while, these stripes appear on the bottom screen.  
This happens randomly when browsing the manual and selecting an item.
I attach a photo:

![20210323_024055](https://user-images.githubusercontent.com/70182567/112103309-543c8e80-8b88-11eb-8a35-b00533de1fbe.jpg)

**Comment by Epicpkmn11** [comment]
Hmm, what language is this happening on? It seems fine for me in English and Japanese...

**Comment by SofyUchiha** [comment]
> Hmm, what language is this happening on? It seems fine for me in English and Japanese...
Spanish

**Comment by NightScript370** [comment]
Can this be reproduced in the latest version
