### ISSUE TITLE
Homebrew NDS Games are not loading

### ISSUE THREAD

**Issue by RedstoneGuyLol** [DS-Homebrew/TWiLightMenu#1396]
**Console Configuration:**  
**TWiLight Menu++ Version: St. Patrick's Day (2021) release** 
**TWiLight Menu++ Theme: Nintendo 3DS** 

### Expected behaviour

Boots up the game normally

### Actual behaviour

Shows a black screen and nothing else

### Steps to reproduce

1. Download a Homebrew NDS (I was using "Mario Paint Composer")
2. Drag the file to roms/nds
3. Boot the NDS file in TWiLightMenu

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, which is a known one.
Not all homebrew games are compatible, so you'll need to create a RAM disk for it.
https://wiki.ds-homebrew.com/twilightmenu/creating-ram-disks

**Comment by RedstoneGuyLol** [comment]
Thank you.
