### ISSUE TITLE
Can’t open custom games

### ISSUE THREAD

**Issue by Gamerztour** [DS-Homebrew/TWiLightMenu#1398]
I downloaded a game with the .dsi file at the end and it had its own icon and everything... but when I try to open it on my ds, it just goes to a black screen... its not a rom hack btw... help!

**Comment by Kaisaan** [comment]
Which game?

**Comment by Gamerztour** [comment]
> Which game?

It was an undertale port that someone made

**Comment by NightScript370** [comment]
Feels like more of a support-base issue rather than an actual bug in twilight. Join our Discord Server to learn how to fix

Closing
