### ISSUE TITLE
Add an option to install an older version of nds-bootstrap

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/TWiLightMenu#1399]
I want an "Old" option that can boot with any older version in case something goes wrong with the new bootstrap.

**Comment by Mewthree3** [comment]
Wouldn't you just replace the bootstrap files?

**Comment by KururinX** [comment]
Now I treat older versions as nightly.

**Comment by Peter0x44** [comment]
That's one way to approach it - either way, having two versions of nds-bootstrap simultaneously is clearly possible

If this is really necessary, how do you suggest it should be implemented? just having a third nds-bootstrap-old.nds or such?
I personally don't think there's any need for such a thing.

**Comment by KururinX** [comment]
"Release version" brings comfortable operation with many software and
"Nightly build" allows you to try out the latest features and fixes.
However, some software may work comfortably only on certain older builds.
Because of its slight comfort, I think there may be a third choice. (example : nds-bootstrap-old.nds)

**Comment by lifehackerhansol** [comment]
I am not particularly in favour of this. It's a _very_ specific thing to ask, and I even think some nds-bootstrap configs were added/removed within the releases, and probably more to come. There are only a handful of people that play on a downgraded version of nds-bootstrap, not to mention that the recent releases have fixed quite a handful of compatibility issues and even blacklists that outright disable a certain function if it is known not to work. 

Just seems realy unnecessary to me is all.

**Comment by NightScript370** [comment]
Been a month without a response on how to effectively edit the configuration for older versions

Seems like the best thing to do would be to keep twilight on the older version as well.

Closing
