### ISSUE TITLE
Guru Meditation error on startup

### ISSUE THREAD

**Issue by Mewthree3** [DS-Homebrew/TWiLightMenu#1402]
**Console Configuration:** New Nintendo 2DS XL, 11.14.0-46J. Luma3DS v.10.2.1-9189e3d7
**TWiLight Menu++ Version:** Latest, 19.1.1
**TWiLight Menu++ Theme:** 3DS, Suicune theme w/ HBL music, RocketRobz startup disabled, DSi Startup may or may not be disabled.

### Expected behaviour

TWiLight Menu should start up normally, to the game selection menu.

### Actual behaviour

Red screen on top that says Guru Meditation Error! data abort! (attached is the [error message](https://ibb.co/wKgnQcM))

### Steps to reproduce

1. Boot TWiLight Menu on N2DS XL
2. There should be a red screen.
 
### Additional info
I attached my error message, right here. [https://ibb.co/wKgnQcM](url)

**Comment by RocketRobz** [comment]
Try changing the theme.
If that doesn't solve it, one of your ROMs could be causing this issue.

**Comment by Mewthree3** [comment]
Thanks for the help. It seems to be a ROM issue. I added some new ones today, (weirdly enough I could boot to menu just fine with them before) so I suppose I'll just have to see which one is causing the problem.

**Comment by Mewthree3** [comment]
Seems like my Metroid Prime rom was causing the issue. I got it again, and everything works fine. So, I'm closing this. Thanks again for the help, keep on doing what you're doing!!
