### ISSUE TITLE
ds sudden sleep mode

### ISSUE THREAD

**Issue by nkwem** [DS-Homebrew/TWiLightMenu#1403]
The ds goes into sleep mode at any moment and doesn't come up till I close and open it back up and as you can guess it disrupts whatever the person is playing even resulting in death. thanks for reading the complaint.

**Comment by RocketRobz** [comment]
This is not an issue with TWLMenu++ or nds-bootstrap.

It could be one of these causes:
1. The sleep mode detection is bugged on your console.
2. Some magnetic objects around you could be making the console trigger sleep mode.

**Comment by nkwem** [comment]
Thanks
