### ISSUE TITLE
3DS WiFi Setup Music

### ISSUE THREAD

**Issue by N3Tgames-dev** [DS-Homebrew/TWiLightMenu#1406]
I'd like you to add the 3ds WIFI setup theme 

Best regards

**Comment by urmum-69** [comment]
You should try doing this yourself
see https://wiki.ds-homebrew.com/twilightmenu/custom-dsi-3ds-sfx and https://wiki.ds-homebrew.com/twilightmenu/custom-dsi-3ds-skins for reference.

**Comment by N3Tgames-dev** [comment]
I tried but I wasn't very good at it, my dsi didn't recognize the music

**Comment by NightScript370** [comment]
If you need help, please ask on our Discord Server
Closing, as this isn't an issue
