### ISSUE TITLE
A simple file manager

### ISSUE THREAD

**Issue by malvarenga123** [DS-Homebrew/TWiLightMenu#1408]
**Is your feature request related to a problem? Please describe.**
Currently, TWiLightMenu is the only app that can access both the (micro)SD card in the 3DS/2DS and the microSD card in a flashcard. Copying files between the two is only possible through a PC and physically removing the card.

**Describe the solution you'd like**
A simple file manager with just basic functions with access to both drives simultaneously.
It could have a similar interface to Godmode9

**Describe alternatives you've considered**
Godmode9, but it was [dismissed by the devs](https://github.com/d0k3/GodMode9/issues/171) because of how troublesome it would be to port DLDI to GM9.

**Comment by NightYoshi370** [comment]
Does GodMode9*i* suit your purposes?

**Comment by malvarenga123** [comment]
I tried running GodMode9i, but I could only access my flashcard's microSD.
If it could access both cards, then yes, it would.

**Comment by malvarenga123** [comment]
I was able to get GM9i to access my Flashcart's microSD by updating its firmware, reformatting the card with 32K cluster size and launching GM9i through TWM.
