### ISSUE TITLE
Glitched top screen and sound after waking from sleep mode

### ISSUE THREAD

**Issue by SillyAnim** [DS-Homebrew/TWiLightMenu#1409]
![5D69086D-A6B5-418D-9BC0-7330F316B81E](https://user-images.githubusercontent.com/82294497/114287890-877d8980-9a73-11eb-98ba-4e5934f077c2.png)

**Console Configuration: DSi with hiyaCWF**  
**TWiLight Menu++ Version: release 19.1.1.** 
**TWiLight Menu++ Theme:Nintendo DSi** 

I found very scary bug after long charging my console in sleep mode. I opened my console and it’s just making very loud and scary sound with graphical bugs on the top screen(look to the photo), rebooting the console helps to fix this. I open this issue form to know: anyone see this on their console because this very scary to me.

P.S. I don’t know english well

**Comment by RocketRobz** [comment]
This bug is rare for me. I have no idea why that would happen.

**Comment by heydootdoot** [comment]
this also happened to me actually when i'm trying to translate TWiLightMenu UI texts and i'm just letting my DSi open and then close it for a long time because i'm observing the text so that my translation would look nice, sometimes when i open it again after so long it'll glitch out like the image you just sent.
so i think this is a bug with how TWiLightMenu handles sleep mode for a long period of time that sometimes the screen glitch out when you open it again.

**Comment by RocketRobz** [comment]
I don't recall this issue occurring on later versions, and hasn't happened on my side recently, so it's safe to assume this is fixed.

**Comment by pizzamakesgames** [comment]
This is happening to me regularly on a DSi XL with the newest release of TwilightMenu.

**Comment by RocketRobz** [comment]
Commit 2bf242b8159dbcdd7201251d9a0b4871c26b628b disables sleep mode until a fix is found.

**Comment by pizzamakesgames** [comment]
I made a video of one of the times it happened, if that helps at all.

https://drive.google.com/file/d/1_m1zha5c9GlObcvIk0JRTNy40Ryip0Zv/view?usp=sharing

Personally, I've now just switched to a theme where this does not happen though.

**Comment by kyoforkshomebrews** [comment]
Not sure whether this is a separate issue but I've gotten a screeching sound in TWLMenu++ Settings twice now and I believe it just happens if the system is in standby for a few minutes. It's completely hung up when this happens so it won't react to key presses.

**Comment by RocketRobz** [comment]
Since this or a similar bug has occurred in other libnds homebrew, commit 89533eb4 has implemented a custom sleep mode function to workaround the bug.
Closing, since this is a libnds issue.
