### ISSUE TITLE
White screen after starting a custom rom

### ISSUE THREAD

**Issue by G9-Dev** [DS-Homebrew/TWiLightMenu#1412]
**Console Configuration:**  
Old 3DS XL with Luma3DS
**TWiLight Menu++ Version:** 
19.1.1 (idk for version but its the latest)
**TWiLight Menu++ Theme:** 
Nintendo DSi ; Blue
### Expected behaviour

Start a custom rom like DScraft or PortalDS
### Actual behaviour
The saving screen appears, then... white screen for ever.

### Steps to reproduce

1.Start TWL++
2.Select a custom rom and start it
3.watch a beautiful white screen.

### Additionnal info
I tried NDS forwarder ( in universal updater) but they also make a white screen...
I have another 3DS (with a broken screen), I installed TWL++ on it, and it worked !
I downloaded TWL++ from Universal-Updater.

**Comment by RocketRobz** [comment]
Make sure you're using the Nitro versions, and that the homebrew's folder is in the same location as the .nds file.

**Comment by G9-Dev** [comment]
> Make sure you're using the Nitro versions, and that the homebrew's folder is in the same location as the .nds file.

Thank you for your quick reply. Where I can get Nitro versions ?
Also, I forgot to notice, I have another 3DS (with a broken screen), I installed TWL++ on it, and it worked !

**Comment by G9-Dev** [comment]
I also found that you can't access the bootstrap menu or flipping screens when playing custom rom.
I tried to start a normal DS game, it worked but it said me that my SD card wasn't formatted to 32kb cluster size, but I have formatted it !
Also before the nds_bootstrap loading screen I see a console at bottom with "dumping ram data" on it.
Please help me :3

**Comment by G9-Dev** [comment]
Are you still here ? I really need help :( I found that nds-bootstrap doesn't launch when launching custom roms ??

**Comment by RocketRobz** [comment]
I don't know if you've solved your issue already, but I'll close this due to cleanup.

**Comment by G9-Dev** [comment]
Sadly I didn't. But as I can see there is no solution 😂

**Comment by RocketRobz** [comment]
You can download the Nitro version of DScraft from here then: https://dscraft.github.io/
