### ISSUE TITLE
GBA saves dissapear

### ISSUE THREAD

**Issue by gingertomato** [DS-Homebrew/TWiLightMenu#1423]
Currently using v20.0.1, but I started noticing the issue on v19.1.1

GBA saves backed up from cartridges and emulators seem to load fine, but if I then save in game, power off and back on, the save file initialises and all progress is lost.

I'm mainly trying to use native mode, via an R4i SDHC Gold Pro with a Supercard / Supercard Lite on a DS Lite, but I've also tried using GBArunner2 (also on the DS Lite) briefly and it seemed to have the same issue.

Sometimes the save stays but most of the time it seems to initialise. I don't know if sometimes I'm power-cycling without ejecting the R4 and sometimes I'm not... would that make any difference? How and when does the save get send to the R4 sd card?

If anyone else has had an issue similar to this, help would be really appreciated! Thanks.

**Comment by gingertomato** [comment]
I've done a bit more testing and it seems to only lose save data if the R4 is ejected after playing the GBA game. Even if I play a GBA game, power-cycle, then eject, it still will lose the save. 

However, if I play another game between finishing the GBA game and ejecting (i.e. GBA game > DS game > eject), it retains the save.

Is this because it only writes the GBA save to the SD when starting another game?

**Comment by Squall-Leonhart** [comment]
its definitely a gbarunner2 bug.

**Comment by Epicpkmn11** [comment]
> its definitely a gbarunner2 bug.

If I'm not missing something it doesn't look like this is in any way related to GBARunner2... OP is using native mode with a Slot-2 flashcard

**Comment by RocketRobz** [comment]
> Is this because it only writes the GBA save to the SD when starting another game?
Yes, this is true.

When you're done playing a GBA game, restart TWLMenu++ to bring the save to your SD card.
