### ISSUE TITLE
Manual "SD card was removed"

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#1436]
**Console Configuration:** DSi with Unlaunch booting TWiLight Menu++ via held button
**TWiLight Menu++ Version:** 20.0.1-30cb40c
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

The system would not tell me that the SD card was removed, because it hasn't.

### Actual behaviour

The system tells me that the SD card was removed.

### Steps to reproduce

1. Start TWiLight Menu++
2. Open Manual
3. Go to the TWiLight Menu++ DSi Theme page
4. Go to the previous page (TWiLight Menu++ Settings page)
5. Go to the next page (TWiLight Menu++ DSi Theme page)
6. At this point, the system consistently tells me that the SD card has been removed.

**Comment by RocketRobz** [comment]
See if 6b2a7122 fixes this bug.

**Comment by spellboundtriangle** [comment]
That seems to have fixed it, thank you!
