### ISSUE TITLE
Very strange graphical bugs, possible memory corruption?

### ISSUE THREAD

**Issue by tomrow** [DS-Homebrew/TWiLightMenu#1442]
**Console Configuration:**  
**TWiLight Menu++ Version:** 
**TWiLight Menu++ Theme:** 
DSi, HiyaCFW, TWLMENU v20.0.1

### Expected behaviour
Game names should render properly

### Actual behaviour
Many DS games with banners have their names corrupted into glitch text consisting of many CJK ideographs and missing characters. NDSBootstrap was able to boot these successfully, and other programs such as Unlaunch and GodMode9i were able to read the files and display the titles with no issues. The SD card has been checked with CHKDSK with no issues.

### Steps to reproduce

View a variety of NDS ROMs in the DSi Theme

**Comment by tomrow** [comment]
On closer inspection, DSi enhanced games and DSiWare games don't seem to have this issue. DS games and homebrew with banners seem to have problems though.

**Comment by RocketRobz** [comment]
Where are you booting TWLMenu++, exactly?
If it's through DSiWarehax entrypoints such as Memory Pit, then I'd imagine that'd be normal.
If it's through the system menu, then idk why that would happen.

**Comment by tomrow** [comment]
I'm booting through the DSi system menu.

**Comment by tomrow** [comment]
I've checked and it doesn't seem to occur on 3DS. I also tried copying new ROMs over to the SD card and reinstalling TWLMENU which didn't solve the issue.

**Comment by jeffyjeffy1023** [comment]
Well, it occurs on my N3DSXL. SD is 64GB. Nearly full, though.

**Comment by NightYoshi370** [comment]
Do you have a picture of this occuring?

**Comment by alemercu** [comment]
If it may help I made some tests and I have the same issue if I change "Game Title Language" option in Twilight Menu from "System" to any other language, no matter what and even if I set the same language of my system. It happen in DSi, 3DS, Sega Saturn and Homebrew Launcher themes.

Tested with Twilight Menu 20.2.0
