### ISSUE TITLE
New super mario bros ds

### ISSUE THREAD

**Issue by eltonb** [DS-Homebrew/TWiLightMenu#1443]
When i start the super mario it stock at white screen

**Comment by RocketRobz** [comment]
Already fixed in later commits.

**Comment by eltonb** [comment]
Sorry i don't get it, so you say this problem has been solved? And where
can i find the guidement?

**Comment by RocketRobz** [comment]
The fix will be in the next version of TWiLight Menu++.

**Comment by eltonb** [comment]
So many thanks
