### ISSUE TITLE
White Screen with some games

### ISSUE THREAD

**Issue by Ekaintxu12** [DS-Homebrew/TWiLightMenu#1445]
Your console: New 3DS XL (EUR Ver. 11.14.0-46E) Launch Method: Booted from SD card via TwilightMenu++ 20.0.1. Version used: Latest. Game tested/used/applicable: Mega Man ZX (EUR) - Mega Man ZX Advent (EUR) - Mega Man Zero Collection (EUR)
Expected Behavior: Game boots, functions correctly Actual Behavior: Game locks up with two white screens upon attempting to boot (except for Zero Collection, which locks up with a black upper screen and a white lower screen).

Steps to reproduce
1.Attempt to boot the games with TwilightMenu++ 20.0.1.
2.Games don't boot (double white screen locked after nds bootsrap loading screen)
Notes: Tried another rom´s region too but still the same

**Comment by RocketRobz** [comment]
Already fixed in later commits.

**Comment by Ekaintxu12** [comment]
Where I can find the solution? Could you give me the link to that commit?

**Comment by RocketRobz** [comment]
You can either use Universal Updater to update TWLMenu++ to the latest nightly, or wait for the next stable version to be released.

**Comment by Ekaintxu12** [comment]
Okay thanks dude. You're the best :)

**Comment by Ekaintxu12** [comment]
YEAH MAN YOU ARE THE BEST. I was going crazy with this problem but installing the nightly version solved it and now they run perfectly. Thanks a lot really I appreciate it too much ;-)
