### ISSUE TITLE
Various issues in Twilight Menu ++ Flashcart release

### ISSUE THREAD

**Issue by alemercu** [DS-Homebrew/TWiLightMenu#1453]
Premise: I use Twilight Menu ++ 20.1.0 flashcart release in a NDS lite with Original R4 Revolution.

**Is your feature request related to a problem? Please describe.**
There are 2 big issues:
1. Backlight issue: the brightness using kernel to launch .nds can't be changed. It stays always to 2 even if I change the backlight.ini file.
2. My GBA games in root directory of flashcart's sd every time i play them the .gba file automatically move to "sd:\saves" folder (generated automatically by twilight menu). Very strange :(
(using kernel to boot games nds and sav must be in the same folder, so i choose root for all my roms)

**Describe the solution you'd like**
1. The backlight.ini file is in the wrong folder. It must be in "sd:\__rpg" instad of "sd:\ _wfwd", doing so changes applied to file are correcly applied.
2. I don't know why but save format in "sd:\ _wfwd\globalsettings.ini" (precisely "saveext" parameter) is set to .nds.sav, so I changed my .sav to .nds.sav to use them, but to solve the gba issue i have to simply change it to a normal .sav format in globalsettings.ini and set back file extensions to .sav. It fixed the issue and the "saves" folder isn't automatically generated anymore.

**Describe alternatives you've considered**
Nope haha, now all works great so I don't tried other ways to do this.

**Additional context**
All the isseus are caused by problems in files from "TWiLightMenu-Flashcard.7z\Flashcart Loader\Original R4 & M3 Simply" folder.

**Comment by RocketRobz** [comment]
The .sav file must be in `saves` for .nds ROMs. TWLMenu++ moves it out of `saves` for the flashcard kernel to read it.

**Comment by RocketRobz** [comment]
I have no idea why .gba files get moved to `saves` though.

**Comment by alemercu** [comment]
Ok i made other tests and my solution doesn't work hahaha. Backlight isssue is fixed, but my gba files continue to go in saves folder. I think I fixed this only because the saves folder isn't still created by twilight menu. Once it's there my games move to it. :(
Is possible that twl menu see .gba files as .sav files? Because it is the same thing that happen with my saves, as you mentioned before.
It happens with my last loaded gba rom, exactly like .sav nds files.

**Comment by hurda** [comment]
That's not fixing the first issue, does it?

**Comment by alemercu** [comment]
> That's not fixing the first issue, does it?

The first issue can be fixed by manually moving "backlight.ini" file from "sd:\_wfwd" to "__rpg" (I have the original R4). Changing the backlight value in the file in this path will apply the changes.
