### ISSUE TITLE
Use of touchscreen on manual crashes

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#1458]
**Console Configuration:** Nintendo DSi with hiyaCFW + Unlaunch
**TWiLight Menu++ Version:** 9f420620
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

The touchscreen would allow me to scroll on the manual.

### Actual behaviour

The system tells me that the SD card was removed.

### Steps to reproduce

1. Open the manual
2. Touch the touchscreen

**Comment by Dimensional** [comment]
Same problem: n3DS, latest official TWiLight Menu++ Release.

Touching the bottom screen when looking at the manuals causes it to error out with a message about the SD being removed. Pressing the home button allows me to close out the menu and get back to the 3DS Home Menu.

**Comment by alemercu** [comment]
I can confirm what said before. Same issue on my DSi with Twilight Menu 20.1.0 + HiyaCfW + Unlaunch. 
However I have a DS with Official R4 Revolution + Twilight Menu and the manual work perfectly without touch issues (the only issue is in 3ds theme in which the little icon to open the manual does't work).

**Comment by RocketRobz** [comment]
> the only issue is in 3ds theme in which the little icon to open the manual does't work

The icon works for me on my side.

**Comment by alemercu** [comment]
> > the only issue is in 3ds theme in which the little icon to open the manual does't work
> 
> The icon works for me on my side.

Sorry maybe I written a bit bad

DS(i) > icon in 3ds theme work but touch issue in all themes
DS > icon in 3ds theme not working but NO touch issue in all themes

If icon problem is only mine no prob, I never use it haha

**Comment by alemercu** [comment]
A little update: Touch issue only happen if "SD removal detection" is enabled in settings, thats why in my DS all works, because there isn't this option. So if I disable this option in DSi all works geat.

**Comment by RocketRobz** [comment]
`SD removal detection` is now disabled for Manual.

**Comment by alemercu** [comment]
> `SD removal detection` is now disabled for Manual.

Well, I updated to v20.2.1 and issue is still present. It will be fixed in the next update?

**Comment by lifehackerhansol** [comment]
Yes, it was fixed in a nightly after the last release.

You can test the nightly here: https://github.com/TWLBot/Builds/releases

**Comment by alemercu** [comment]
> Yes, it was fixed in a nightly after the last release.
> 
> You can test the nightly here: https://github.com/TWLBot/Builds/releases

Ok thanks for the answer!
