### ISSUE TITLE
Atari Lynx Emulator

### ISSUE THREAD

**Issue by Yola-cola** [DS-Homebrew/TWiLightMenu#1460]
I think I would be nice if Twilight Menu can play Lynx ROMs. I'm pretty sure it can run it fine.

**Comment by Epicpkmn11** [comment]
Does an Atari Lynx emulator exist for the DS? I don't see any...

**Comment by SimPiko** [comment]
apparently there was an attempt to port Handy https://dmunsie.wordpress.com/2007/04/25/handy-on-the-ds/
but seems like there isn't any downloads available

**Comment by takenusername5** [comment]
I found one for the Nintendo 3DS, but not the DS

https://gbatemp.net/threads/release-handy-3ds-atari-lynx-emulator.394329/

**Comment by NightYoshi370** [comment]
TWiLight Menu++ is not an emulator, but simply a menu that launches emulators. The lack of an emulator for a console is not a something that we can control, but rather something that needs to be taken up outside our little community.
Closing...

PS: If you have a Nintendo DS-based Atari Lynx emulator, please link it and I'd be glad to reopen
