### ISSUE TITLE
Custom icons for emulated games

### ISSUE THREAD

**Issue by alemercu** [DS-Homebrew/TWiLightMenu#1464]
It would be nice to be able to add custom icons for emulated games (such as gb/gbc/gba/nes/snes ecc.) instead of the default emulator icon, maybe by creating an icon folder and place here png with same name of the file (similar to what happen with boxart).

**Comment by blamedeath4x** [comment]
right click properties/customize/add new icon

**Comment by NightScript370** [comment]
@blamedeath4x That custom icon wouldn't display on TWiLight; it's Windows exclusive

**Comment by Epicpkmn11** [comment]
Added in #1800
