### ISSUE TITLE
Name Updates not translating into TWL

### ISSUE THREAD

**Issue by seraphsunny** [DS-Homebrew/TWiLightMenu#1465]
**Console Configuration:** DSi Lite running TWL through MemPit- no Unlaunch.
**TWiLight Menu++ Version:** v. 19.1.1 (presumed) || nds-bootstrap Ver. Release v0.38.0
**TWiLight Menu++ Theme:** NDSi Dark Theme

### Expected Behaviour:

Alterations to Name and Colour in the DSi settings should reflect through TWL.

### Actual Behaviour:

Name and Colour stay at the oldest version

### Steps to reproduce

1. Install TWL and MemPit onto SD card
2. Run TWL setup
3. Attempt details change through DSi Menu
--
I know a bit about why this is happening from a thread closed ~2 years ago, something to do with which NAND its supposed to pull from, but both of us are at a loss. I can't figure out which files need to be altered to change it. I figure if I were to run it through setup on another SD card and copy the files over, it would work that way, but it's something I wanted to share nonetheless before I did that. And, reasonably, it isn't a major bug, it just bugs us a little

**Name censored on image for our peace of mind. It isn't anything rude. ...Apologies for the camera photo.
![names](https://user-images.githubusercontent.com/83987952/117733321-fce59280-b1b6-11eb-9d59-5fc3769f6a08.png)

**Comment by Epicpkmn11** [comment]
Do you have hiyaCFW? If so you need to change it from the hiyaCFW SDNAND System Settings. If your DSi is autobooting into TWiLight Menu++ try holding <kbd>SELECT</kbd> while turning it on and if that opens the hiyaCFW configuration, disable `Autoboot Title`.

**Comment by RocketRobz** [comment]
You don't need hiyaCFW installed to fix this.
Try deleting `16KBcache.bin`, so that TWLMenu++ regenerates it with the up-to-date information.

**Comment by seraphsunny** [comment]
Hm. Wound up not seeing that and installing the unlauncher fixed it. However that's much smarter and a lot less tedious. thank you, sir.
