### ISSUE TITLE
Game titles appear garbled

### ISSUE THREAD

**Issue by jeffyjeffy1023** [DS-Homebrew/TWiLightMenu#1470]
(I don't know how to get a log, so I've attached a photo. Sorry.)
**Console Configuration:**  New Nintendo 3DS XL (RED, US) on System Update 11.14 , Luma3DS 10.2. SD size is 64 GB.
**TWiLight Menu++ Version:** 3DS v20.1.0, stable.
**TWiLight Menu++ Theme:** DSi

ADDITIONAL NOTE:
In the settings menu, the only options for fonts are Chinese, (simplified) Default, and Korean. All text but the game names appears in english.

### Expected behaviour

Every game name should appear normally.

### Actual behaviour

Most game names appear as a long mix of random chinese characters and ?s. (The only exception I've found is YOU DON"T KNOW JACK, published by THQ)

### Steps to reproduce

1. Power system on
2. Open TWiLightMenu++
3. Navigate to your DS ROMs

Photo link because github won't let me upload for some reason:
https://cubeupload.com/im/jeffyThePicMan/IMG20210515145923.jpg

**Comment by tomrow** [comment]
#1442

**Comment by NightYoshi370** [comment]
Let's keep things to one issue please. I have moved the image above over there.
Closing...
