### ISSUE TITLE
NDS ROMs were deleted, no other files deleted

### ISSUE THREAD

**Issue by Zerutonii** [DS-Homebrew/TWiLightMenu#1472]
**Console Configuration:** 
Nintendo DSi with hiyaCFW + Unlaunch
**TWiLight Menu++ Version:** 
v11.1.0
**TWiLight Menu++ Theme:** 
Acekard

### Expected behaviour
No ROMs should be deleted

### Actual behaviour
All NDS ROMs deleted, other files such as the nds-bootstrap .bin files of the games I had have remained however the actual ROMs in the ROMs folder are gone 

### Steps to reproduce
not sure exactly what happened but this is my best guess as this is the most unusual thing that happened
1. launch physical DS game from Unlaunch
2. have DSi run out of power whilst closed and in this state
3. recharge DSi and ROMs are gone

OTHER POSSIBLE CAUSES and steps to reproduce:
1. try loading incompatible game in twilight menu ++
2. turn off DSi when loading bar is stuck on half way loaded

**Comment by lifehackerhansol** [comment]
Hello,

You are running _way too low_ a version of TWiLight Menu++. The latest version is 20.2.0. Please update TWiLight Menu++.

The akMenu theme was actually _removed_ during this time as this bug as well as many others were present. Please follow the progress on akMenu [here](https://github.com/DS-Homebrew/TWiLightMenu/pull/1109).

This issue should be closed.
