### ISSUE TITLE
My twilight menu doesn't apply the changes in the settings

### ISSUE THREAD

**Issue by renansaiki** [DS-Homebrew/TWiLightMenu#1481]
My Nintendo DS is the XL, and i have a issue when i'm starting the DS, every time the twilight menu starts at akmenu, even if i change the settings to start at another menu, it keeps starting at akmenu, sorry if my english is bad, i'm brazilian, the twilight menu version is v20.2.1 and the nds-bootstrap is v0.40
![c89b64c3-2039-46cc-bbf1-30eef3e826bb](https://user-images.githubusercontent.com/84743794/119415700-81143b80-bcc8-11eb-8853-637b700dadfa.jpg)

**Comment by RocketRobz** [comment]
Unlaunch is set to start TWLMenu++'s `akmenu.srldr` file on boot.
You need to change it so that Unlaunch starts `boot.nds` file from the SD root.

**Comment by renansaiki** [comment]
thanks bro
