### ISSUE TITLE
Exit combo not working 

### ISSUE THREAD

**Issue by shiggityputz** [DS-Homebrew/TWiLightMenu#1482]
I am running the latest version of TM++, on a new 3ds xl. Holding L/R, B & down for even 20+ seconds will not exit to the menu. 

It keeps loading the last game I tried, Castlevania portrait of ruin, and I've even tried holding B down when starting TM++ to disable the auto run, and it won't let me get to the menu.

**Comment by lifehackerhansol** [comment]
The button combo has changed to L+Down+SELECT since v19.0.0. This brings up an in-game menu with a few options regarding resetting.

**Comment by shiggityputz** [comment]
Ah. There we go. Thanks. I even did searches and everything came up with the old combo. I hadn't used my 3DS in a long time lol.

**Comment by RocketRobz** [comment]
Also, if TWLMenu++ keeps loading the last-launched game, then you're not on the latest version.
Starting with v20.2.1, holding B is now the only way to start the last-launched game.

**Comment by shiggityputz** [comment]
Weird. I just updated it using the universal updater, which I also just installed tonight.

**Comment by RocketRobz** [comment]
Hold A+B+X+Y on boot to clear the settings, then open TWLMenu++ Settings to verify the version you're using.

**Comment by Dimensional** [comment]
> 
> 
> Also, if TWLMenu++ keeps loading the last-launched game, then you're not on the latest version.
> Starting with v20.2.1, holding B is now the only way to start the last-launched game.

I'm on the latest version, and I've run into some weird issue when testing the wifi settings for one of my games in DS mode, if I don't use the button combo to close out of the game into Twilight Menu, but instead press the home or power button to close out, opening Twilight Menu from my 3DS home will auto-boot the last game, regardless if attempting to update or clear settings. I have to let the game boot, then use the button combo to load the In-game menu, to then close out of the game and get back into the Twilight Menu. From there, things work as normal again.

**Comment by RocketRobz** [comment]
> I'm on the latest version, and I've run into some weird issue when testing the wifi settings for one of my games in DS mode, if I don't use the button combo to close out of the game into Twilight Menu, but instead press the home or power button to close out, opening Twilight Menu from my 3DS home will auto-boot the last game, regardless if attempting to update or clear settings. I have to let the game boot, then use the button combo to load the In-game menu, to then close out of the game and get back into the Twilight Menu. From there, things work as normal again.

That's weird. I can't reproduce this on my side.

**Comment by Dimensional** [comment]
> 
> 
> > I'm on the latest version, and I've run into some weird issue when testing the wifi settings for one of my games in DS mode, if I don't use the button combo to close out of the game into Twilight Menu, but instead press the home or power button to close out, opening Twilight Menu from my 3DS home will auto-boot the last game, regardless if attempting to update or clear settings. I have to let the game boot, then use the button combo to load the In-game menu, to then close out of the game and get back into the Twilight Menu. From there, things work as normal again.
> 
> That's weird. I can't reproduce this on my side.

I can't reproduce it either, and I tested the nightly as well. Either way, guess things appear to be working properly. :)
