### ISSUE TITLE
Cheat Codes Not Showing

### ISSUE THREAD

**Issue by CoolUsernam3** [DS-Homebrew/TWiLightMenu#1486]
**Console Configuration:** Nintendo 2DS XL With the Latest Firmware
**TWiLight Menu++ Version:** I'm using the normal release, not sure what version but I know that I am on a recent one
**TWiLight Menu++ Theme:** Nintendo 3DS

### Expected behaviour

The cheats for the rom should show up.

### Actual behaviour

The cheats aren't showing up, and a message saying "No cheats found" shows up, when there's a usrcheat.dat file in SD>_nds>TwilightMenu>extras

### Steps to reproduce

1. Download Universal Updater
2. Download the usrcheat.dat File
3. Open up TWiLightMenu and go to Pokemon Black 2
4. Open the Cheats menu, and the cheats won't appear

Cheats used to appear, but now they don't.

**Comment by Epicpkmn11** [comment]
Do you have a clean ROM? The default cheat database won't find the game for randomizers, most ROM hacks, or some bad dumps.

**Comment by CoolUsernam3** [comment]
Oh, I have a edited ROM with fixed trade evolutions, I guess that's the reason. Is there anyway to make the cheat menu work for it?

**Comment by Epicpkmn11** [comment]
You'll need to edit the cheat database to change the header checksum to that of your ROM. You can use [r4cce](https://hp.vector.co.jp/authors/VA013928/soft_en.html) to edit it:
1. Open the `usrcheat.dat` file with r4cce (it can take a while to load as DSJ's database is *huge*)
2. Search for the game (bottom left)
3. Copy and paste the game if you don't want to break compatibility with the clean ROM
4. Click the [...] button and select your ROM
5. Save the file

**Comment by CoolUsernam3** [comment]
Thanks a lot, really appreciate it.
