### ISSUE TITLE
Add ability to select the icons beside the selected icon by tapping on them, in the dsi theme. 

### ISSUE THREAD

**Issue by linusrg1** [DS-Homebrew/TWiLightMenu#1494]
**Is your feature request related to a problem? Please describe.**
In the dsi theme, unlike the og dsi menu, you cant tap on an icon on either side of the selected icon, to select that icon. You have to scroll over to it. 
**Describe the solution you'd like**
The ability to be able to select the icons neighbouring the selected icons to select that new icon. 
**Describe alternatives you've considered**
None. But I guess I could just use forwarders on the dsi firmware if I want.

**Comment by Scripter17** [comment]
This is also applicable to the homebrew launcher and 3ds themes

It might be worth adding this to the SEGA Saturn theme with yellow ovals on each side depending on what exactly they're supposed to be
