### ISSUE TITLE
Not all Games in directory are listed

### ISSUE THREAD

**Issue by KH1501** [DS-Homebrew/TWiLightMenu#1496]
Console Configuration: New 2ds xl with luma 3ds cfw version 11.14.0-46E  
TWiLight Menu++ Version: 20.3.0. 
TWiLight Menu++ Theme: homebrew launcher 

### Expected behaviour

should list all nds games that are in a directory
### Actual behaviour

only lists 38 games and cuts off the rest. other missing games appear when games are deleted
### Steps to reproduce

1. open game selection menu
2. observe

**Comment by RocketRobz** [comment]
If you've looked at the top screen, you'll know how to see more of the games in the directory.
