### ISSUE TITLE
The settings are not reflected

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/TWiLightMenu#1500]
Even if "Run in" is specified on the ROM selection setting screen in the menu, it is not reflected (saved).
　[ Postscript ] I forgot to mention what's happening on the DSi and DSiLL.  Changes that do not include "Run in" seem to remember without problems

TWiLightMenu : e9f8ce0a etc.
Beta for the last few days (I can't write more about it right now, but I've confirmed it in some after v20.3.0)

- - - - - - - - - -
39fbdc5a...Good
bc302dce...NG
0fbe9e5b...NG
3b1bbc0e...NG
e9f8ce0a...NG
b44df880...NG
fb87f7b8...NG
- - - - - - - - - -
8679b28d...NG
8c538ed5...NG
f26974f7...NG
- - - - - - - - - - - 
c0967b64...NG
5b779e5b...NG
a5afff8f...NG
- - - - - - - - - -

**Comment by KururinX** [comment]
Use Console : DSi (Works the same on the DSi LL)

https://user-images.githubusercontent.com/81461991/121128074-bf336280-c865-11eb-9018-734a4df90d53.mp4

The DSi mode and DS mode specifications can be reflected from the TWL overall settings, but not from the ROM selection.
It is inconvenient in the current situation to use "DSi mode" and "DS mode + cheat" depending on the situation.

**Comment by RocketRobz** [comment]
Fixed.
For future reference, please only reference the commit that caused this bug, not the commits that came after it.

**Comment by KururinX** [comment]
thanks a lot.
