### ISSUE TITLE
ColecoDS (ColEm by Marat Fayzullin) has been played that the colecovision games on DSi

### ISSUE THREAD

**Issue by qamichele59** [DS-Homebrew/TWiLightMenu#1503]
**Console Configuration:** Nintendo DSi
**TWiLight Menu++ Version:** v0.40.0
**TWiLight Menu++ Theme:** SEGA Saturn

### Expected behaviour

Playable

### Actual behaviour

Playable

### Steps to reproduce

1. Plays ColecoVision Rom Games
2. Runs .col or .bin rom file?
3. Fully functional working

**Comment by lifehackerhansol** [comment]
... could you please fill out the issue templates?

**Comment by shadowspike74** [comment]
2.1 works fine on TWlightmenu++

RAM disk: 1
Direct boot: no
Run in: DS mode
ARM9 CPU Speed: 133mhz (TWL)
VRAM Boost: Default
Bootstrap Default

**Comment by lifehackerhansol** [comment]
Speaking of which... this issue itself is vague. Is something _not_ working? 

Closing, as issue seems to be resolved as mentioned by above comment, if any.
