### ISSUE TITLE
Uh oh text glitched

### ISSUE THREAD

**Issue by Gecko4526** [DS-Homebrew/TWiLightMenu#1508]
**Console Configuration:**
New Nintendo 2DS XL With Luma Installed
**TWiLight Menu++ Version:**
Version 20.4.1 With nds-bootstrap Ver. Release v0.42.0
**TWiLight Menu++ Theme:** <!-- Nintendo DSi

### Expected behaviour

Game Names Should Display Correctly

### Actual behaviour

Weird Question Marks And Some Chinese Text

### Steps to reproduce

1. Update Twilight Menu With An Old Version Of Twilight Menu Updater (Didn't Know It Was Discontinued)
2. After That, Update Twilight Menu Updater.
3.Twilight Menu Updater Will Say It's Discontinued.
4. Update Twilight Menu Again Through Universal Updater.
5. Run Twilight Menu And The Name Of Games Will Now Glitch.

**Note:**
Here's what my settings look like

![IMG_20210616_094323.jpg](https://user-images.githubusercontent.com/80373776/122145543-06ce7580-ce88-11eb-9c51-3770043c125e.jpg)

![IMG_20210616_094329.jpg](https://user-images.githubusercontent.com/80373776/122145567-0f26b080-ce88-11eb-8da2-117e34a54d4b.jpg)

![IMG_20210616_094333.jpg](https://user-images.githubusercontent.com/80373776/122145575-12ba3780-ce88-11eb-8479-f6c80fd2ac9a.jpg)

![IMG_20210616_094336.jpg](https://user-images.githubusercontent.com/80373776/122145646-37161400-ce88-11eb-94a9-e6383e10a843.jpg)

![IMG_20210616_094344.jpg](https://user-images.githubusercontent.com/80373776/122145657-3c735e80-ce88-11eb-8a56-48e8cdbee5af.jpg)

Also This What It Looks Like
And For Some Reason Folders Are Ok

![IMG_20210616_083358.jpg](https://user-images.githubusercontent.com/80373776/122145810-85c3ae00-ce88-11eb-8d92-a52f2d720de1.jpg)

![IMG_20210616_083446.jpg](https://user-images.githubusercontent.com/80373776/122145722-5b71f080-ce88-11eb-87f6-8ad5ca02f9de.jpg)

**Comment by RocketRobz** [comment]
I have no idea why this happens.
Try resetting the settings by holding A+B+X+Y after launching TWLMenu++.
If that doesn't fix it, then reinstall TWLMenu++ by following [this](https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds) and [this](https://wiki.ds-homebrew.com/twilightmenu/installing-3ds) guides.

Closing, as this cannot be reproduced.
