### ISSUE TITLE
Failure to start the program happens 7/10 times.

### ISSUE THREAD

**Issue by Fau57** [DS-Homebrew/TWiLightMenu#1510]
Okay hi guys first off I'd like to say that I am grateful for this program. I guess I'm just wondering if I'm doing something wrong because legitimately I have to start and close the app multiple times before it actually gets to the menu to pick my games. Don't get me wrong I'll continue to be a slave to that process, at least until I can buy a r4 cart. I am a super basic programmer so I can't say I know what is going wrong but for a program to fail to start so often something definitely is off. I'm willing to provide any needed details if it actually helps this program perform over all. Thanks. 

**Console Configuration:**  
**TWiLight Menu++ Version:** 
**TWiLight Menu++ Theme:** 

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Whenever such a lock-up occurs, close the console's lid and open it again.
This is due to libnds' FIFO handler being a bit buggy.

**Comment by Fau57** [comment]
Oh fair that's an easy fix but can I ask is there a way to go over said
code and make it less buggy? As I said novice programmer so I'm just kinda
assuming.

**Comment by RocketRobz** [comment]
> Oh fair that's an easy fix but can I ask is there a way to go over said code and make it less buggy? As I said novice programmer so I'm just kinda assuming.

https://github.com/devkitPro/libnds/blob/master/source/common/fifosystem.c
