### ISSUE TITLE
Certain games crash when saving 

### ISSUE THREAD

**Issue by RealPortalastical64** [DS-Homebrew/TWiLightMenu#1524]
I’m using the latest release of TWLmenu++ on an Old 3DS XL with the latest version of Luma3DS.

Up until this morning everything worked perfectly fine. However, when I tried saving my progress in New Super Mario Bros this morning, the game completely crashed. I tried again: another crash. When I tested this on SM64DS, the same thing happened. But when I tried Spirit Tracks, saving worked perfectly fine.

I had been experimenting with DS mode for a day or two at this point (primarily trying to get the OG DS firmware to run with ntrldr), but I hadn’t messed with TWLmenu at all.

I can’t test this with other games since my SD card is nearly full, meaning I can’t fit anything else on there. It may be worth mentioning that all other DS homebrew, as well as the entirety of 3DS mode, is unaffected.

**Comment by RocketRobz** [comment]
This particular issue only occurs on nds-bootstrap v0.43.0.
Please update nds-bootstrap, as it got fixed in v0.43.1.
