### ISSUE TITLE
Crash when starting Twilight Menu++ 3ds

### ISSUE THREAD

**Issue by gmxw** [DS-Homebrew/TWiLightMenu#1527]
I used Twilight Menu and everything worked fine until I updated everything.

I am using a 3DS XL, CFW 11.14.0-46E, luma3ds 10.2.1

I updated my luma3ds and Twilight Menu++. Twilight Menu++ now crashes the console when starting the app.
I tried updating firmware on emuNand.
I tried using TWLFix-CFW.3dsx then updating the firmware again.
I tried uninstalling completely Twilight Menu++ then reinstalling it.

Nothing of what I tried fixed the problem.
I tried putting a nds game cartridge and it works but Twilight Menu++ doesn't work.

**Comment by lifehackerhansol** [comment]
First off: Where are the issue templates?


Also, use of emuNANDs are discouraged. Please go back to sys.

**Comment by gmxw** [comment]
Sorry didn't knew there was an issue template


### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [x]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Direct boot to DSiMenu++ via Unlaunch
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW


### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Start the app

### Actual behaviour

Console Crash

### Steps to reproduce

1.
2.
3.


I tried on sysNAND and it doesn't work

**Comment by gmxw** [comment]
Sorry didn't knew there was a template.

Console : 3DS XL, CFW 11.14.0-46E, luma3ds 10.2.1
TwilightMenu++ Version : 21.0.2

I tried on sysNAND and I have the exact same result.

**Comment by lifehackerhansol** [comment]
Please update your system, and then update TWiLight Menu++. See if there is any improvement.

Also, a picture of the crash is appreciated.

**Comment by lifehackerhansol** [comment]
Closing, as there has not been a similar report.

Please join the Discord server in the README if this is still an issue on the latest system version and latest TWiLight Menu++ version.
