### ISSUE TITLE
none of the games and folders are titled

### ISSUE THREAD

**Issue by IvakaDivaka** [DS-Homebrew/TWiLightMenu#1528]
ok so when i open up twighlight menu i can see my games and stuff but there are no titles for them. neither for the folders themselves. if anyone has a solution please help

**Comment by lifehackerhansol** [comment]
Is this still an issue? I don't think this is an issue with TWiLight in general as I have not seen any reports outside of this.

**Comment by lifehackerhansol** [comment]
Not reproducible, closing.
