### ISSUE TITLE
Ability to launch apps from Hiya CFW SD Nand

### ISSUE THREAD

**Issue by DraconicNEO** [DS-Homebrew/TWiLightMenu#1529]
**Is your feature request related to a problem? Please describe.**
If you are using an SD card larger than 2 gigabytes with HiyaCFW it isn't possible to access any apps on the HiyaCFW Nand like system settings or camera. This is very annoying if you want to use one of these apps and can also be problematic if you need to access the System settings (i.e. to change Wifi configurations). 

**Describe the solution you'd like**

**Describe alternatives you've considered**
Using a smaller SD card to make HiyaCFW functional.
(This isn't desired, and not exactly feasible if you have a lot of games and/or DSiware)

**Additional context**
My idea is to have an extra menu that displays all the apps Installed to the HiyaCFW Nand, allowing you to be able to launch and access nand apps without the need for the DSi menu (which doesn't work on larger SD cards).

**Comment by spellboundtriangle** [comment]
The latest version of hiyaCFW will automatically generate dummy files to account for the 2GB "limit" (see [here](https://wiki.ds-homebrew.com/ds-index/dsi-twl-firm) at "Nintendo DSi system menu" for an explanation)

**Comment by Kaisaan** [comment]
To add on to what @spellboundtriangle said, updating hiyaCFW to the latest version will fix the issue. The latest version can be found [here](https://github.com/RocketRobz/hiyaCFW/releases/latest). Update instructions are also listed in the changelog for each release. 
Closing.
