### ISSUE TITLE
p heart gold black screen ap patchet

### ISSUE THREAD

**Issue by Ryper-maximoft** [DS-Homebrew/TWiLightMenu#1530]
the game "p heartgold" already ap patched doesnt work in this new version black screen afther logo and load data screen, it works fine in the previus version already test delete cache files

**Comment by Squall-Leonhart** [comment]
use a clean dump without the ap patch.

**Comment by Ryper-maximoft** [comment]
already tested a version whitout patch and same problem :c

**Comment by SNBeast** [comment]
What exactly are you trying to run? The original Pokemon HeartGold or a romhack?

**Comment by Ryper-maximoft** [comment]
the original one, as i said already use it before in a previus version and it worked fine, idont know why it doesnt in this new version,also tried a clean install and nothing

**Comment by SNBeast** [comment]
Cannot replicate on 3DS or DSi.
Also not the correct repository for the issue. Please report this on the nds-bootstrap repo.
And when you report this on the nds-bootstrap repo, fill in the information in the template, as that prevents having to spend time in an exchange asking for it.

**Comment by Ryper-maximoft** [comment]
> Cannot replicate on 3DS or DSi.
> Also not the correct repository for the issue. Please report this on the nds-bootstrap repo.
> And when you report this on the nds-bootstrap repo, fill in the information in the template, as that prevents having to spend time in an exchange asking for it.

allright or i just wait for a fix later,doesnt seem im gonna recive a reply for it
