### ISSUE TITLE
[IR Passthrough] Pokéwalker not connecting with Pokémon SoulSilver on version v21.0.1/v21.0.2 of TWiLightMenu++

### ISSUE THREAD

**Issue by LXLegend** [DS-Homebrew/TWiLightMenu#1531]
**Console Configuration:** Nintendo o3DS with Luma3DS 
(Reproducible on Nintendo n3DS with Luma3DS)
**TWiLight Menu++ Version:** v21.0.2
**TWiLight Menu++ Theme:** Nintendo DSi

**Other Info:**
- using a USA version of the Pokémon SoulSilver ROM
- Have tried both a USA version of the SoulSilver and a USA version of the White Cartridge
DS Classic Menu on startup: No
DSi/Saturn: SELECT: SELECT Menu
SD access in Slot-1: Off

Can provide other settings upon request (either specific setting or the .ini file)

This issue is _not present_ on v12.2.1 (I just plucked an earlier version to see if it was an issue with the current version)

### Expected behaviour
Pokéwalker should connect to SoulSilver and display a message other than "No Trainer Found."

### Actual behaviour
"No Trainer Found." message on Pokéwalker indicating there was no connection to SoulSilver.

### Steps to reproduce
Prerequisite: A save for SoulSilver with access to the PC in order to unlock Pokéwalker functionality.
1. Launch TWiLight Menu++ and configure the settings listed under _Other info_
2. restart the 3DS
3. Launch TWiLight Menu++, navigate to the ROM and launch it.
4. Go to the "Connect to Pokéwalker" setting in the main menu.
5. If the Pokéwalker is already synced to the save, Pokémon should be transferred properly. If the Pokéwalker is not synced, there should still be an attempt to connect- To ensure functionality input L + down + X to sync the Pokéwalker.
6. The Pokéwalker will time out if a connection is not made, and the Pokéwalker will display the message "No Trainer Found."

**Comment by Dimensional** [comment]
The IR Passthrough feature was disabled a long time ago.

**Comment by LXLegend** [comment]
> The IR Passthrough feature was disabled a long time ago.

Thank you for the speedy reply- I was not aware of this. I will close this issue. Apologies for unnecessary issue being raised.
