### ISSUE TITLE
Twilight menu closes when a soft reset should occur.

### ISSUE THREAD

**Issue by KeeveeKoomoo** [DS-Homebrew/TWiLightMenu#1534]
**Console configuration:**
Old 3DS running on Luma3DS

**TWiLight Menu++ Version:**
Occurs in both Release v0.35.1 and Nightly ver. 06b24917

**TWiLight Menu++ Theme:**
DSi

**Expected behaviour:**
1) Game resets due to a prompt in game e.g. exiting a menu.
2) Game resets due to a button combination e.g. L+R+Start+Select in Pokèmon.
3) Game closes to TWiLight menu via button combination e.g. L+Down+B or whatever it may have been changed to.

**Actual behaviour:**
TWiLight menu will exit to the 3ds home menu. Upon relaunching the last rom will automatically be started. To get back to the TWiLight menu I have to close the game by pressing Home and returning to the home menu and relaunching TWiLight. Powering off also works.

**Steps to reproduce:**
Receive a mystery gift in any DS Pokèmon game and press any button in the mystery gift section that would usually restart the game.
OR 
Press the soft reset button combination
OR
Press the button combination required to return to the TWiLight menu.

**Comment by Dimensional** [comment]
Nds-bootstrap's latest release is v0.43.2. What about the version of Twilight Menu? Latest version there is v21.0.2.

**Comment by spellboundtriangle** [comment]
This is a bug with O3DS systems, unrelated to nds-bootstrap (as far as I know, I don't have a 3DS)

**Comment by KeeveeKoomoo** [comment]
I used to be able to soft reset. I can't remember when this issue started but it has been occuring a while even after updating with universal updater.

**Comment by ErdbeerbaerLP** [comment]
I am also experiencing this issue for months. It WAS fixed at some point, but that bug came back. 
Also tried "Quit Game" from NDS Bootstrap and I get relaunched to 3ds menu

**Comment by KeeveeKoomoo** [comment]
> Nds-bootstrap's latest release is v0.43.2. What about the version of Twilight Menu? Latest version there is v21.0.2.

Tried again using TWiLight Menu release 21.3.0- 179f4a6 and nds-bootstraps versions 0.43.2 and c96d45af. I am really not sure of the cause.

**Comment by KeeveeKoomoo** [comment]
Also tried to reset the game using the function labelled as such in the nds-bootstrap menu and recieved the same outcome as if I had used the ingame function.

**Comment by KeeveeKoomoo** [comment]
Heck if it helps I generated a log file. Maybe   someone can make sense of what it is saying lol 

[NDSBTSRP.LOG](https://github.com/DS-Homebrew/TWiLightMenu/files/6941115/NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
The log is irrelevant in cases like this.
I suggest downgrading TWLMenu++, and see which previous version worked with soft-resetting.

**Comment by NightScript370** [comment]
Is this a TWiLight error or nds-bootstrap problem?

**Comment by NightScript370** [comment]
Soft reset behavior has changed in recent releases
That + the fact that this is an nds-bootstrap issue, ill assume its fixed and close this. If its still an issue, please open it on the nds-bootstrap repo
