### ISSUE TITLE
Pictochat disabled with NDS Lite

### ISSUE THREAD

**Issue by juherr** [DS-Homebrew/TWiLightMenu#1535]
From [the documentation](https://wiki.ds-homebrew.com/twilightmenu/download-play-pictochat):

> If you’re using a DSi console, you should already be able to launch those apps.

I'm using a DS Lite console and it's not clear enough if the feature is supposed to work out-of-the-box in my case too. 

**Console Configuration:** a Nintendo DS Lite with R4 and ez-flash-3in1 
**TWiLight Menu++ Version:** v21.0.2
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

Be able to run Pictochat/DS Download Play like it is the case from the original boot.

### Actual behaviour

The buttons are gray/disabled.

### Steps to reproduce

1. Turn on the console with TWiLightMenu autoboot
2. Open the menu
3. Check the Pictochat button

**Comment by carcaschoi** [comment]
Dsi =/= Dslite

**Comment by juherr** [comment]
> Dsi =/= Dslite

Sure! That's the reason for the issue: what about Dslite which is not yet documented.

**Comment by RocketRobz** [comment]
A flashcard step has been added. (If the page doesn't show it, please wait some time.)
A DSi is still required to get the `pictochat.nds` file, unfortunately.

**Comment by juherr** [comment]
For the record, the files from https://archive.org/details/dsi-pictochat-dlplay are working well, except when we try to return to the "DSi menu"
