### ISSUE TITLE
Always installing as DSiWare in my o3DS.

### ISSUE THREAD

**Issue by pacarevolution** [DS-Homebrew/TWiLightMenu#1551]
Hello! I tried fresh installing the app in my Old 3DS in every way possible, but I can't manage to use it in 3DS mode.
It always installs as a DSi Ware and I never get the message asking at the first start if I want to boot it on 3DS or DSi mode.
Installed manually and through universal patcher, same results.

The app works perfectly, but giving this situation I can't play games in widescreen mode, because the app always launches in DSi mode.

Console configuration: Nintendo 3DS (old) with Luma3DS
TwiLight Menu++ Version: Release (21.1.1)

**Comment by RocketRobz** [comment]
Seems that you either didn't follow [these](https://wiki.ds-homebrew.com/twilightmenu/playing-in-widescreen) instructions, or haven't tried a widescreen-compatible game yet.

**Comment by pacarevolution** [comment]
I followed all the steps!
The problem is that the app doesn't install as a 3DS game, so the option for enabling widescreen doesn't even appear in the menu.

**Comment by RocketRobz** [comment]
That's not the problem. TWLMenu++ being installed as DSiWare is intentional, as it's made as such.
The problem is that `Widescreen.cxi` isn't detected in `sd:/_nds/TWiLightMenu/TwlBg/`.

**Comment by pacarevolution** [comment]
Ahhhh ok! I'll do those steps again more carefully!
By the way, thanks for the quick answer all this awesome work!
