### ISSUE TITLE
ratio aspect update?

### ISSUE THREAD

**Issue by shadowspike74** [DS-Homebrew/TWiLightMenu#1564]
would you ever plan on improving the ratio aspect hack on the 3ds version of TWiLightmenu++ like for 16:10 to be widescreen for games that have the codes to support widescreen and 4:3 non stretched out with black border for those that don't is that workable or not that's what I'd like to know?

**Comment by RocketRobz** [comment]
Update TWiLight Menu++ and then re-follow the widescreen steps to get that result.

**Comment by shadowspike74** [comment]
I looked up the guide made a few mess ups but now it works fine thanks for the tip
