### ISSUE TITLE
Splash screen audio doesn't play

### ISSUE THREAD

**Issue by Yola-cola** [DS-Homebrew/TWiLightMenu#1566]
**Console Configuration:** New Nintendo 3DS with Luma3DS 
**TWiLight Menu++ Version:** v21.3.0 release 
**TWiLight Menu++ Theme:** DSi Theme, Black and Purple

### Expected behaviour

The splash screen should play normally

### Actual behaviour

The video plays but the audio is mute

### Steps to reproduce

1.Open Twilight Menu
2.Listen

**Comment by RocketRobz** [comment]
During testing, this has never happened for me on both DSi and 3DS, even after a few soft-resets.
Are you sure the volume slider isn't completely low?

**Comment by Yola-cola** [comment]
I have some proof

**Comment by Yola-cola** [comment]
https://youtu.be/w6X5CtCrzw8

**Comment by RocketRobz** [comment]
I assume this is consistent then.
Since you're the only one with this issue, I'll close this, until someone else chimes in with this same issue.

**Comment by RocketRobz** [comment]
Actually, could you try holding A+B+X+Y immediately after launching TWLMenu++ and after the white screens appear, to reset the settings?
Maybe an unknown setting is causing this.
