### ISSUE TITLE
Won't load if a GBA game is inserted

### ISSUE THREAD

**Issue by emmandyar** [DS-Homebrew/TWiLightMenu#1567]
Console Configuration: NDS Lite with r4 flashcart and ezflash 3in1+ slot-2 expansion
TWiLight Menu++ Version: Stable TwilightMenu++ v.21.3.0
TWiLight Menu++ Theme: DSi, white

**Expected behaviour**
Twilight menu boots

**Actual behaviour**

Both screens remains white and the menu never loads

**Steps to reproduce**

Plug 3in1+ on the slot-2, power on the console.

Recently got a pair of ezflash 3in1 plus slot-2 expansion carts, both work fine with regular flashcart firmware and YS menu, but  twilight menu ++ gets both screens white and never actually loads. I've formatted the sd card, I've deleted everything and started fresh, same thing. If the 3in1 is connected, twilight won't boot

**Comment by emmandyar** [comment]
Ok, it also won't load whenever my only gba game (chinese repro, btw) is inserted in the slot-2. Weird.

Tried fresh installs in different sd cards, even different r4 cards (an original one, and 2015 sdhc clone)

**Comment by RocketRobz** [comment]
Seems to be a user-specific issue, as I haven't heard of anyone else with this issue.
