### ISSUE TITLE
3ds enters sleep mode/ freezes on black screen upon launching any forwarder or twilight menu 

### ISSUE THREAD

**Issue by KeeveeKoomoo** [DS-Homebrew/TWiLightMenu#1573]
**Console Configuration:**  O3DS
**TWiLight Menu++ Version:**  I can't tell because I can't check but I think 21.3.0
**TWiLight Menu++ Theme:**  I can't remember exactly but I think the default

### Expected behaviour

Twilight menu should open or a forwarder should run the selected rom.
### Actual behaviour

The 3ds will make a shutter noise and go to a black screen. If you wait long enough, the 3ds will show the nds-bootstrap screen (or white screen if I just open twilight menu) and make another shutter noise before going to the "In sleep mode, the system can" screen.
### Steps to reproduce

1.open twilight menu or any nds-bootstrap forwarder
2.wait
I did not make any changes to my settings when this occured. I was playing pokemon white when I went off of it to check something in checkpoint and when I re-opened the twilight menu, the previously mentioned events occurred. I tried to open the forwarder for pokemon white but got the same outcome. It may be of notice that the pokemon white forwarder didn't work anyway but I did try my platinum forwarder and it also gave the same outcome. I can open normal 3ds games. I have tried twlfix-cfw but it didn't work.

**Comment by KeeveeKoomoo** [comment]
If it isn't a problem with twilight, can you suggest a fix?

**Comment by RocketRobz** [comment]
Delete the following:
1. `settings.ini` in `sd:/_nds/TWiLightMenu/`
2. `nds-bootstrap.ini` in `sd:/_nds/`

If deleting both doesn't fix your issue, then you're out of luck.

**Comment by Epicpkmn11** [comment]
If what Robz said doesn't fix it maybe try [reformatting your SD card and checking for errors](https://dsi.cfw.guide/sd-card-setup) it sounds like it could maybe be SD card corruption.

**Comment by KeeveeKoomoo** [comment]
Thanks, will do. Its good to see u are always so quick to help when u can.

**Comment by KeeveeKoomoo** [comment]
> If what Robz said doesn't fix it maybe try [reformatting your SD card and checking for errors](https://dsi.cfw.guide/sd-card-setup) it sounds like it could maybe be SD card corruption.

Could that happen from backing up a save in checkpoint?

**Comment by Epicpkmn11** [comment]
> Could that happen from backing up a save in checkpoint?

It shouldn't, but if your SD card is dying then it could.

**Comment by KeeveeKoomoo** [comment]
> If what Robz said doesn't fix it maybe try [reformatting your SD card and checking for errors](https://dsi.cfw.guide/sd-card-setup) it sounds like it could maybe be SD card corruption.

Also would that not affect every game including non nds titles

**Comment by Epicpkmn11** [comment]
> Also would that not affect every game including non nds titles

It could maybe be that only a part of nds-bootstrap got corrupted or something like that, corruption doesn't necessarily have to affect the whole card at once I don't think.

**Comment by KeeveeKoomoo** [comment]
Well I may have an issue... I deleted the ini files but I still get the same outcome but I don't have to wait as long for the sleep mode screen to come up. Deleting the files definitely did something, just not enough.

**Comment by KeeveeKoomoo** [comment]
> If what Robz said doesn't fix it maybe try [reformatting your SD card and checking for errors](https://dsi.cfw.guide/sd-card-setup) it sounds like it could maybe be SD card corruption.

And at this current time I can't check my sd card with a pc :(

**Comment by Epicpkmn11** [comment]
Maybe just try reinstalling TWiLight Menu++ from Universal-Updater or so, that may fix it. Though if you have anything important on there probably good to back it up soon if there's a chance your SD card might be dying.

**Comment by KeeveeKoomoo** [comment]
I have reinstalled the twilight menu. Sad thing is, that rn, I can't access
my sd card any other way other than my 3ds.

**Comment by KeeveeKoomoo** [comment]
Also, unrelated to twilight, but do you know why it makes the shutter sound?

**Comment by KeeveeKoomoo** [comment]
Do you think a log file would help here? I can use andftp to try and access it

**Comment by KeeveeKoomoo** [comment]
Oh no it isn't a twilight problem. I thought "if anything ds related is broken, what about the internet settings". They too are broken. I have no idea what is wrong. If it was something normal, the twlfix should have fixed it

**Comment by Epicpkmn11** [comment]
You system updated after doing twlfix, right? That's required to actually fix it

**Comment by KeeveeKoomoo** [comment]
Yep and because I am so lost for ideas I am tried twlfix again. It didn't
work, not that I expected it to. It was sort of just a ditch effort

**Comment by Epicpkmn11** [comment]
Maybe try asking in the [Nintendo Homebrew](https://discord.gg/MWxPgEp) Discord server, they probably know more about 3DS problems then we do.

**Comment by KeeveeKoomoo** [comment]
i am kinda worried now cuz if everything nds related is broken, I am gonna
be stripped of a lot of functionality

**Comment by KeeveeKoomoo** [comment]
ok some good news. it's not sd related. the same thing occurs when booting
without the sd card; it must be luma or smthn that is on the 3ds itself

**Comment by KeeveeKoomoo** [comment]
Atm I have no access to discord but I will definitely join once I can

**Comment by KeeveeKoomoo** [comment]
I've tried updating luma because at this point idk what else could work but it didn't work. I really have no idea anymore. It is my 3ds and not my sd card cuz you don't need an sd card to access ds internet settings. I will check back here if I find a fix so then at least someone will be able to help others if they encounter this problem

**Comment by KeeveeKoomoo** [comment]
Well bad news is I can't ask reddit for help cuz they banned me from 3dshacks because my copy of white is pirated. I wasnt trying to get a pirated game to work like they said, I was trying to fix the ds part of my 3ds. They banned me for sayi g the word pirated I swear lmao

**Comment by KeeveeKoomoo** [comment]
it started working again on its own and I have no idea why but I can't
complain lol. thanks for all your help!
