### ISSUE TITLE
sometimes when starting HG SS this error occurs

### ISSUE THREAD

**Issue by RuneinA** [DS-Homebrew/TWiLightMenu#1574]
sometimes when starting HG SS this error occurs
![IMG_20210807_134705](https://user-images.githubusercontent.com/60844000/128599207-3f179614-1278-421a-a198-1adb36dcc218.jpg)
![IMG_20210807_134651](https://user-images.githubusercontent.com/60844000/128599208-e3160481-e7c4-42d8-80a9-e68e07740139.jpg)
![IMG_20210807_134627](https://user-images.githubusercontent.com/60844000/128599209-f2ed1357-c2ab-47f6-8a80-c85721d67f01.jpg)

**Comment by RocketRobz** [comment]
This a TWL_FIRM bug that happens randomly, not a TWLMenu++ or nds-bootstrap bug.
When that happens, just close the console's lid and open it back up.
