### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by christopher3242** [DS-Homebrew/TWiLightMenu#1590]
Nds rom Not working black screen 
1. Hulk 
2. Best of Arcade Games 

that's all I'm going two pictures.

thanks you.

**Comment by christopher3242** [comment]
![16291366078065885847752413244958](https://user-images.githubusercontent.com/52284167/129608205-275e9090-8e2d-4ab0-a816-8a444368b715.jpg)

Uploading 20210816_195810.mp4…

**Comment by christopher3242** [comment]
![16291366078065885847752413244958](https://user-images.githubusercontent.com/52284167/129608205-275e9090-8e2d-4ab0-a816-8a444368b715.jpg)

Uploading 20210816_195810.mp4…

**Comment by Squall-Leonhart** [comment]
use the template that you deleted entirely.

**Comment by christopher3242** [comment]
That's working

**Comment by lifehackerhansol** [comment]
Please re-open the issue using the issue templates, which seem to be nonexistent here.
