### ISSUE TITLE
Top screen flickering with color issues on 3ds XL when lauching TWILightMenu.

### ISSUE THREAD

**Issue by jojo57420** [DS-Homebrew/TWiLightMenu#1591]
Console Configuration: Old 3ds Xl with luma3DS. (console version is 1.14.0).

TWiLight Menu++ Version : Occur in version 21.4.0 didn't try on Nightly version.

TWiLight Menu++ Theme: Dsi

Expected behaviour:

Should have started normally witouth the top screen flickering and the color issues.

Actual behaviour:

When i launched TWILightMenu the top screen

https://user-images.githubusercontent.com/82333195/129718996-b2ae0d5f-86a1-460b-99ef-9b9eeced5d0f.mp4

 was flickering and there was color issues (even in games).

Steps to reproduce:

1.Start the 3ds Xl
2.Find the Apllication TWILightMenu
3.Launch the app and watch the top screen

**Comment by Epicpkmn11** [comment]
Does this happen with other DS-mode software or just TWiLight and things loaded through it. (ex. DS Download Play or a cartridge)

**Comment by jojo57420** [comment]
Hello,thanks for the respond !it also happen in a cartridge but not in apps like DS Download (In catridge the problem is color issues with brightness issues,I try it on MH4U cartridge)but the problem is that everything was working perfectly fine before the installation of TWILight but now the problem is on cartridge too ! also my 3ds is pretty old(like 5 years) and she is a bit broken but it's working and there was not problem (luma 3ds was installed btw).

**Comment by Epicpkmn11** [comment]
It even happens on 3DS cartridges? There's no way TWiLight Menu++ could possibly cause that... If it's even happening in 3DS mode it sounds like it's a hardware problem with your 3DS.

Maybe try asking on the [Nintendo Homebrew](https://discord.gg/MWxPgEp) Discord server.

**Comment by jojo57420** [comment]
Yep i think the problem is with my 3ds not TWILight Menu i will try to repair mine and see if the problem will be fixed.

Thanks for the respond !
