### ISSUE TITLE
TWL (133 MHz) doesn't work anymore

### ISSUE THREAD

**Issue by lathian** [DS-Homebrew/TWiLightMenu#1600]
**Console Configuration:** New 2DS XL with 11.14.0-46E firmware and Luma3DS 10.2.1
**TWiLight Menu++ Version:** 21.4.0 (bootstrap v0.46.1)
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

Select 133 MHz (TWL) in settings for better DS game performance respectively to prevent slowdowns (like in Final Fantasy XII: Revenant Wings or Dragon Quest IX)

### Actual behaviour

It has no influence on the game performance whether TWL or NTR was selected.

### Steps to reproduce

1. Open Twilight Menu Settings
2. Switch to game settings and select 133 MHz (TWL) for ARM9 CPU-Clock
3. Go back to game selection and start a game (with all settings on "Standard")

**Comment by RocketRobz** [comment]
Please note that certain games are blacklisted from using TWL clock speed, so you'll need to turn it on manually in the per-game settings (though the games you mentioned aren't blacklisted, so I don't see why they wouldn't work with it).

Also, please check in TWLMenu++ Settings if it's still set to TWL. If it shows NTR once you open the settings, please switch it to TWL, and then press B to save the settings.
