### ISSUE TITLE
Stuck in white screen and not able to get into the menu ( I am using a 256gb card)

### ISSUE THREAD

**Issue by sugarnyannyan** [DS-Homebrew/TWiLightMenu#1606]
**Console Configuration:**  New Nintendo 3DS with Luma3DS
**TWiLight Menu++ Version:** 21.4.0
**TWiLight Menu++ Theme:** 

### Expected behaviour

I expect I can get into twilight menu ++ normally
### Actual behaviour

I was stuck at the white screen for 30+ minutes and nothing happen. 
I tried to format my sd card to 32kb format, which I ended up able to use twilight menu ++. 
But it made my 3ds unable to load the theme correctly so I decided to format it to 64kb.
Now the theme loads correctly but I cannot enter twilight menu again.
Is there any way to use twight light menu with a large sd card without sacrificing the capability of using them normally?

### Steps to reproduce

1.Download twilight menu ++ from universal DB
2. Launch it
3.

**Comment by RocketRobz** [comment]
Use GUIFormat to reformat to FAT32 with 32kb cluster size.
If the theme doesn't load, try re-installing it or re-loading it.

Please note that the white screen crash happens on occasion, so when that happens, press HOME, and then press B.

**Comment by sugarnyannyan** [comment]
Thank you for your quick reply. I may not phrase my problem with themes correctly. Every time I exit twilight menu or restart my device, my themes disappear. This problem only happens when the card is formatted into 32kb cluster size. So I was wondering if there is any other way to use twightlight menu without formatting it to 32kb cluster size. But based on your reply, I guess that is a "No"?
