### ISSUE TITLE
Donor rom error

### ISSUE THREAD

**Issue by Fehgoku** [DS-Homebrew/TWiLightMenu#1607]
When i open a some games It appears a error saying "this game requires a donor rom to run. please set an existing  early sdk3 game as a donor rom" how i do I solve this?

**Comment by Fehgoku** [comment]
Im in the flashcard Twilight version , is there a difference about going in that per-game settings and doing what you Said?

**Comment by Epicpkmn11** [comment]
There shouldn't be

**Comment by Fehgoku** [comment]
I did It , ty
