### ISSUE TITLE
Home menu not working

### ISSUE THREAD

**Issue by randomsomeone69** [DS-Homebrew/TWiLightMenu#1611]
**Console Configuration:** European New Nintendo 2DS XL, Luma3DS v10.2.1-58540cb2, 32 GB microSD card
**TWiLight Menu++ Version:** 25.1.0
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

After the TwiLight Menu ++ animation, we should select a rom in the menu, and then play the game we selected.

### Actual behaviour

After the TwiLight Menu ++ animation, it's like a bootlooping. A litte loading will appear for 0,5 second, then the screen flashes to the white, and the TwiLight Menu ++ animation appear, then, it's a loop.

### Steps to reproduce

1. Format the 32 GB microSD card as 32 Ko clusters. Then ut more than 5 roms in the nds folder and 6 other roms in an another folder. Then turn on the 3DS. And install the 25.1.0 cia file.
2. Launch  the loader, get to SD:\roms\nds folder, then launch CTGP Nitro (or any other game) or get out of the folder
3. Exit CTGP Nitro or go to the another folder with the 6 other roms.

**Comment by NightScript370** [comment]
How did you format the card?

**Comment by randomsomeone69** [comment]
I formatted the SD card in FAT32 with 32 Ko clusters.

**Comment by lifehackerhansol** [comment]
I can't reproduce this. I'd suggest reinstalling TWiLight Menu++ (delete the `_nds` folder, then reinstall from Universal Updater.)

**Comment by randomsomeone69** [comment]
I retried this, but I think it was patched.

And I've tried deleted the _nds folder then reinstall. It was keeping rebooting.

For me, case closed
