### ISSUE TITLE
DSiware and DSi Enhanced Games booting to white screen.

### ISSUE THREAD

**Issue by DraconicNEO** [DS-Homebrew/TWiLightMenu#1612]
**Console Configuration:** 3DS Booting Twilight Menu from Home screen
**TWiLight Menu++ Version:** [v21.5.0](https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v21.5.0)
**TWiLight Menu++ Theme:** 3DS

### Expected behaviour

Booting DSiware or DSi Enhanced software with the .nds extension normally Boots it in DSi mode.

### Actual behaviour

Any DSiware or DSi Enhanced games with .nds extension show a white screen and never boot or Boot with freezing.
This can be fixed by renaming the files to .dsi but that shouldn't have to happen.

### Steps to reproduce

Launch DSiware or DSi Enhanced Games in .nds format in Twilight Menu. (This only happens on 3DS, never had this issue on DSi)

**Comment by RocketRobz** [comment]
Delete the `patchOffsetCache` folder in `sd:/_nds/nds-bootstrap/`.

**Comment by DraconicNEO** [comment]
> 
> 
> Delete the `patchOffsetCache` folder in `sd:/_nds/nds-bootstrap/`.

That fixed it.
