### ISSUE TITLE
R4/GBC Themes: Wrong filename for DSiWare savefiles (.pub/.prv) is used

### ISSUE THREAD

**Issue by SimPiko** [DS-Homebrew/TWiLightMenu#1615]
**Console Configuration:** DSi XL 1.4.5E (Unlaunch 2.0 installed)  
**TWiLight Menu++ Version:** v21.5.1 
**TWiLight Menu++ Theme:** 'Original R4' (also affects 'Gameboy Color') 

### Expected behaviour

TWLMenu++ should use/create .pub/.prv files with same filename as the DSiWare's .dsi/.nds file uses

### Actual behaviour

TWLMenu++ uses/creates savefiles with only first character of DSiWare's file name with no file extension at all. 
(Example: Instead of 'Pyoro.pub', it uses 'P'

### Steps to reproduce

This was tested on clean installation of TWiLight Menu++ 21.5.1
1. Enter TWLMenu++ Settings and change 'Theme' to either 'R4 Original' or 'GameBoy Color'
2. Exit settings, and launch any DSiWare through TWLMenu++
3. It should now create new save file that uses only first letter/number/character of the DSiWare's filename with no extenstion

### Additional Notes

Mentioned in https://github.com/DS-Homebrew/nds-bootstrap/issues/1272#issuecomment-918475933
Seems that to trigger the bug, the settings.ini has to have all the settings that gets created when exiting Settings menu, as to why, I have no clue.
Also, it only appear in R4 Theme and in GBC theme, probably due to same(or similar) codebase.

**Comment by Squall-Leonhart** [comment]
See https://github.com/DS-Homebrew/nds-bootstrap/issues/1272
