### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by marbug64** [DS-Homebrew/TWiLightMenu#1627]
the screen went black after I uninstalled TWiLightMenu my console and dsi

**Comment by lifehackerhansol** [comment]
This isn't a result of TWiLight Menu++ uninstalled as that would either boot normally or show the Unlaunch file menu. (In fact, this sounds very likely that you may have uninstalled Unlaunch?)

Please join the Discord server linked in the main page of this repository for further assistance.
