### ISSUE TITLE
The game doesn't appear in the DS Select Screen

### ISSUE THREAD

**Issue by GuttoBarros09** [DS-Homebrew/TWiLightMenu#1641]
*Your console:* Old 3DS.
*Launch Method:* Is it launched via SD. SCFG is Unlocked.
*Version used:* I used the released version. v21.5.1 39577d2
*Game tested/used/applicable:* The game that i test is Yu-Gi-Oh! World Championship Tournament 2008. The same not appear in the screen select game DS.

*Expected Behavior:* Appear the DS Game, name and icon.
*Actual Behavior:* Nothing appear in the screen. Only another games.

### Other notes

**Comment by RocketRobz** [comment]
The top selection should show your last launched flashcard game, and the bottom should show your last launched SD game.

**Comment by GuttoBarros09** [comment]
Sorry RocketRobz, I made a mistake reporting something that wasn't wrong. In the list of my ROMS nds folder, I didn't know that in the game selection screen, that if I pressed L or R I would go to an extension of it, and the Yu-Gi-Oh! was there at the end.

Taking this opportunity to thank you for this amazing project that is TWL++. We see.
