### ISSUE TITLE
Use a more compact font for R4 theme

### ISSUE THREAD

**Issue by lifehackerhansol** [DS-Homebrew/TWiLightMenu#1642]
**Is your feature request related to a problem? Please describe.**
Functionally, nothing wrong with it. The default font (which I assume is what it is as the codebase is basically nds-hb-menu) looks pretty bad imo, and it also doesn't reflect the font of the real R4 menu. 

**Describe the solution you'd like**
A more compact font is already used for the bottom display of the R4 menu. I think it could be adapted to be used on the top display.

**Describe alternatives you've considered**
Make a new font? lol
I don't exactly have an alternative in mind, perhaps I'll add it when I think of one.

**Comment by Epicpkmn11** [comment]
It's not possible to do a more compact font without changing the rendering as it's currently just using the default console which is on the tile engine. However I've been meaning to rewrite that anyways to use NFTR and use the same font as the DS Classic Menu so I'll try get around to it soon™.

**Comment by NightScript370** [comment]
> However I've been meaning to rewrite that anyways to use NFTR and use the same font as the DS Classic Menu so I'll try get around to it soon™.

Has there been any updates on it?
