### ISSUE TITLE
3DS Theme Dark Mode

### ISSUE THREAD

**Issue by zurgeg** [DS-Homebrew/TWiLightMenu#1648]
**Is your feature request related to a problem? Please describe.**
Not really, just a request

**Describe the solution you'd like**
A dark mode for the 3DS theme

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by spellboundtriangle** [comment]
There's one here, along with other skins: https://skins.ds-homebrew.com/nintendo-3ds/default-dark

**Comment by zurgeg** [comment]
I just took a look through the themes, the latest ver of Twilight has one, oops
