### ISSUE TITLE
Menus that display cover art freeze navigation while loading cover art

### ISSUE THREAD

**Issue by zurgeg** [DS-Homebrew/TWiLightMenu#1650]
**Console Configuration:** NDSi with HiyaCFW + Unlaunch
**TWiLight Menu++ Version:** v22.0.0
**TWiLight Menu++ Theme:** Really anything that shows cover art

### Expected behaviour

Navigation can continue while cover art is loading

### Actual behaviour

Navigation freezes while cover art is loading

### Steps to reproduce

1. Grab cover art via [TwilightBoxart](https://github.com/KirovAir/TwilightBoxart), and pick "Large"
2. Change your theme to one that displays cover art
3. Scroll to the game
4. Try and navigate.

Once it finishes loading, navigation will work again, so it's not that big of a deal, but it's still annoying

**Comment by RocketRobz** [comment]
Since threaded operations cannot be implemented in libnds, this is not possible.

**Comment by zurgeg** [comment]
Oh okay! Would it be possible to preload coverart if the system has enough RAM? Ie:
Say the toplevel SD card (or whatever) has 6 folders, each with 2 games in it. Would it be possible to preload the as much coverart as possible during the loading sequence?

**Comment by RocketRobz** [comment]
They're already pre-loaded. Make sure the box art option is set to `Cached` in TWLMenu++ Settings.
If it's already set, then the freezing is due to the .png file being decompressed. There is not enough room in RAM to store them decompressed.
