### ISSUE TITLE
"Gliches" lines on Menu?

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/TWiLightMenu#1659]
**Console Configuration:** old 3DS XL, with Luma and GM9 
**TWiLight Menu++ Version:** v22.1.0
**TWiLight Menu++ Theme:** Nintendo DSi dark and light

When scrolling through the menu, black and / or white lines appear. It is repetitive.
Attached a couple of videos for better understanding. 

https://user-images.githubusercontent.com/70182567/136632757-8670d1b8-dddb-435a-8a7b-dcaf6a174881.mp4

https://user-images.githubusercontent.com/70182567/136632808-40047ccb-b498-4bf1-a565-ebdf112910d9.mp4

**Comment by RocketRobz** [comment]
As of currently, the only fix is to turn off photo/box art color de-banding in TWLMenu++ Settings.

**Comment by SofyUchiha** [comment]
This issue reappeared in version v27.24.1 (Hotfix), and it's much more noticeable.
Just to clarify:
Photo/box art color de-banding is off
It occurs on both the Nintendo DSi and the 3DS (especially on the icons at the top of 3DS themes)
I've tried different themes, and they all have the same issue.
