### ISSUE TITLE
Remove nds-bootstrap settings from settings.srldr and keep it to per-game settings

### ISSUE THREAD

**Issue by lifehackerhansol** [DS-Homebrew/TWiLightMenu#1675]
**Is your feature request related to a problem? Please describe.**
TWiLight Menu++ settings is quite annoying to sift through, and the multitude of options can be daunting for the end user to figure out.

**Describe the solution you'd like**
@Epicpkmn11 gave this big brain idea that I actually like more than mine:
- What if we removed the global options for Run in, CPU speed, VRAM mode, and SWI halt hook (am I missing any) and made those per-game settings only since 99% of the time the default is right, then when something is blacklisted it just doesn't show that in that game's per-game settings
- @lifehackerhansol: perhaps we should remove nds-bootstrap settings as a whole and just stick to per-game settings? Adding on to above point

**Describe alternatives you've considered**
By @lifehackerhansol:
- A good way to get around this would be:
  - Nightly will be as usual, with all settings present. Anyone with issues in release can install the nightly build and test there.
  - Release should not contain any nds-bootstrap options. It should default to max settings, and have a blacklist for what is known to not work. I believe that nds-bootstrap has matured to a point where most things not working is mainly the game unwilling to cooperate with some options. An example of this is Hotel Dusk: Room 215 that refuses to use _any_ DSi hardware whatsoever, and setting it all to NTR mode solves any issues with it.

By @Epicpkmn11:
- As for the idea on the whole, I'd say an "Advanced Settings" or so toggle option would probably be better than limiting to nightly and release, could maybe have it show a warning that these settings are can cause issues before enabling.

**Comment by Epicpkmn11** [comment]
> It should default to max settings, and have a blacklist for what is known to not work.

I'd say defaulting to normal (DS mode, 67 MHz, DS mode VRAM, 32 kHz sound, etc for NTR games) like it does now is better. The benefits of the DSi features on NTR games are basically non-existent for the most part as the games were designed for the original DS anyways, 48 kHz audio I think is the only one that doesn't tend to cause issues and can have noticeable benefits.

As for the idea on the whole, I'd say an "Advanced Settings" or so toggle option would probably be better than limiting to nightly and release, could maybe have it show a warning that these settings are can cause issues before enabling.

Maybe have some of the settings that don't tend to cause issues stick around but the troublesome ones require enabling advanced settings. And when you turn advanced settings off maybe have it force all of its things to defaults.

**Comment by lifehackerhansol** [comment]
Issue has been slightly rewritten to reflect discussion from the Discord server.
