### ISSUE TITLE
slot1launch: r4isdhc.com, r4i-sdhc.com carts crash

### ISSUE THREAD

**Issue by tinoposts** [DS-Homebrew/TWiLightMenu#1676]
**Console Configuration: DSi XL with R4iSDHC Flashcart**  
**TWiLight Menu++ Version: v23.0.1** 
**TWiLight Menu++ Theme: Nintendo DSi** 

### Expected behaviour
The flashcart should boot to YSmenu.

### Actual behaviour
The flashcart will only boot with Launch Method Reboot. Unlaunch and Direct will boot to a white screen.

Launch Method Reboot is prone to random crashes when entering Sleep Mode and during gameplay. 

On occasion, Twilight Menu will boot back to the DSi System Menu for no reason.

### Steps to reproduce

1. Open Twilight Menu
2. Press Select and Launch Slot 1 with Reboot Launch Method (Must use a Flashcart from r4isdhc.com with a YSmenu kernel.)
3. Game will eventually crash or freeze.

**Comment by tinoposts** [comment]
After messing with a few settings and searching the issues, my flashcard might not be supported or the way I set up the flashcard won't work. 

It gives a four color code pattern of "red yellow yellow green" but no one in the issues seemed to have the same code I got.

**Comment by MegaMarkLM** [comment]
I actually had the same issue, with an R4iSDHC.com flashcart as well. I reset the settings to see if that fixed the issue but after doing that it just showed a white screen instead. I then manually reinstalled the previous version v23.0.0, and it started reading the flashcart just fine again. After that, I went into Universal Updater, downloaded v23.0.1 from it again, and once again it didn't load the flashcart. I no longer get the color code pattern, though, just the white screen. It's definitely something with this update.

**Comment by tinoposts** [comment]
Hey thanks for the tip. I'm on a DSi though, but I assume I just download v23 onto a fresh SD card? I'm sure I won't be missing much if I were to use an older update.

I'll try and see if that works 7 or so hours from the time that this was commented.

**Comment by lifehackerhansol** [comment]
I can't even reproduce this, trying "Reboot" with my r4isdhc.com cart causes it to load Unlaunch menu instead.

**Comment by lifehackerhansol** [comment]
I can, however, confirm that using Unlaunch to boot results in a white screen. But it doesn't launch when actually launching from Unlaunch's menu either, so this seems to be an issue on the Unlaunch side, so nothing we can do about that.

Launching "Direct" seems to lead to the same issue that @MegaMarkLM has mentioned. I'll try going back by each commit in slot1launch.

**Comment by lifehackerhansol** [comment]
It seems commit ad91b37883e4a998519e1cf9effedbd01050c2b7 caused it to freeze.

**Comment by lifehackerhansol** [comment]
Over on Discord, another flashcart is reported broken by that commit. It is a closely related model of this flashcart: https://media.discordapp.net/attachments/489307733074640926/912378105702805534/20211122_172442.jpg?width=508&height=678

**Comment by lifehackerhansol** [comment]
Also, I am unable to reproduce Settings being unable to go back to TWiLight. Nor the random boot to System Menu.

**Comment by tinoposts** [comment]
I found that using the nds-bootstrap was a more efficient and reliable solution.

**Comment by lifehackerhansol** [comment]
This issue should stay open as this is a bug that still affects other people.

**Comment by lifehackerhansol** [comment]
I think I am reproducing the Settings exit crash, and I've filed a separate report here: https://github.com/DS-Homebrew/TWiLightMenu/issues/1691

**Comment by lifehackerhansol** [comment]
Actually, this looks like it's fixed completely.
