### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by mtbox9x** [DS-Homebrew/TWiLightMenu#1682]
**Console Configuration:**   old 3ds
**TWiLight Menu++ Version:**  23.0.1
**TWiLight Menu++ Theme:** 

### Expected behaviour

I used twilight menu months ago, it worked well. Recently, I updated twilight menu via universal updater to continue the game i played before. However, after dsi boot screen and “touch screen to continue”, just white screen. I mean i can not open twilight menu or directly access to gba game i played before. Thank you.

### Steps to reproduce

1.
2.
3.

**Comment by NightScript370** [comment]
Try holding ABXY and seeing if reseting your settings fixes it.
By the way, please join our Discord Server for further communication. If the above doesn't fix it, I highly bet it's an SD card issue.

**Comment by NightScript370** [comment]
Closing, due to lack of response.
