### ISSUE TITLE
Clarify support for "x in 1" or fake Ace3DS+ cartridges

### ISSUE THREAD

**Issue by AlphaNERD-** [DS-Homebrew/TWiLightMenu#1689]
**Is your feature request related to a problem? Please describe.**
I have bought 2 cartridges: One named "520 in 1" and a Pokemon Diamond cartridge. I bought the first one because i expected to get an original Ace3DS+ for relatively cheap. I didn't expect the latter one to be the same cartridge 😆 . Anyway i didn't manage to get TWiLightMenu++ to boot automatically on the cartridge because i thought that this was in fact an Ace3DS+. Through some detective work i realized that the "520 in 1" cartridge was in fact an R4iLS type cartridge you already support.

**Describe the solution you'd like**
Basically i wish that you mention in your Autoboot folder and maybe in a next update that you support the x in 1 and other fake Ace3DS+ cartridges. That's all.

**Describe alternatives you've considered**
Not mention it i guess. I mean these cartridges are double frauds. Not only they deliver ROMs they never had the right to deliver but they also pretend to be a cartridge they're not. So if you do not wish to support this i can absolutely get behind that.

**Additional context**
I've added 2 screenshots to show what the interfaces looks like. The cartridge presents itself as Deep Labyrinth. I'm not sure about the other cartridges but this may be a sign on how to recognize them.
![Main Menu](https://user-images.githubusercontent.com/9458093/142726539-94f2debc-79d1-4475-b81d-be4818809513.PNG)
![Shitty Main Menu](https://user-images.githubusercontent.com/9458093/142726546-0375b65b-e3de-499f-959e-c9a11e7d5f7b.PNG)
![Very Shitty Main Menu](https://user-images.githubusercontent.com/9458093/142726552-90a2454b-368f-42f7-bc3b-f18b83fd2a64.PNG)
.

**Comment by lifehackerhansol** [comment]
There are too many variants of these clones to list them all, I think. (I'm the one who added support.) Like there are funny game clones, XX in 1 carts, carts that straight up don't have a label on them, et al.

They tend to be Ace3DS+s, I didn't know they came in R4iLS versions, though. 

Basically what I'm trying to point out here is that there are enough variants of this dumb thing to make it slightly infeasible, not to mention that now they're releasing it in both types of clones, so what, I have to put XX in 1 in the folder name of _both carts?_

Let me know what you think.

**Comment by AlphaNERD-** [comment]
How many versions of these are out there? Because if there are too many variations of fake Ace3DS+ out there, i think we can shorten it by adding "Fake Ace3DS+" to the R4iLS directory and writing some examples in the next update message on Github.

**Comment by lifehackerhansol** [comment]
For example, the fake Pokemon cart you ended up with. Pokemon is not the only game that is cloned using an Ace3DS+ cart. There are also the unlabeled Ace3DS+ carts as well as all the XX in 1 carts. 

The idea I had was merging Ace3DS+ and the R4iLS folder and then adding all the other funny versions of them, but really not sure how that can be worded professionally. I want to be careful not to make people think that their cart is an Ace3DS+ when it is in fact not, as loading the wrong autoboot has a good chance of permanently bricking your cart. That was the initial reason to my decision to not include any of the other clones in its folder name.

**Comment by lifehackerhansol** [comment]
Actually, I may as well merge them for now, so at least for the current line of clones, at least it boots, with the downside being that you may have an extra 180kb file that isn't needed. Then if one figures out that it's an Ace3DS+ clone it'll work even if it technically is under another name.

**Comment by lifehackerhansol** [comment]
So I am opposed to the idea of clarifying support for all of the clones for the reasons above. However, since these are known widely enough in the community as an Ace3DS+ clone, merging the two would mean if people copy from the Ace3DS+ folder, one of the two files present there will be the correct one. I think that is the best compromise at this time.

**Comment by AlphaNERD-** [comment]
Yeah, that's a sensible solution 👍
