### ISSUE TITLE
Multiple button presses do not register well in the main menu

### ISSUE THREAD

**Issue by fyredragon69** [DS-Homebrew/TWiLightMenu#1694]
**Console Configuration:** Nintendo 3DS XL with Luma3DS v10.2.1
**TWiLight Menu++ Version:** v23.0.1
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

Multiple button presses should be registered on the main menu, similar to the stock DSi menu.

### Actual behaviour
The main menu lags behind, and even more button presses are required.

### Steps to reproduce

1. Install TWiLightMenu normally
2. Try to press either the left or right part of the d-pad multiple times to get to your requested game faster
3. Does not process multiple inputs very well and does so very slowly.

**Comment by androidian5980** [comment]
If this issue is already being worked on, then this issue can be closed.

**Comment by RocketRobz** [comment]
It's slow, because box art gets loaded and rendered. Try turning off box art.

**Comment by androidian5980** [comment]
It's a bit better, but the lag is still present.

**Comment by NightScript370** [comment]
Please test the latest nightly.

**Comment by fyredragon69** [comment]
After installing the latest nightly (commit 6d8eb93) and disabling box art, the responsiveness of button presses are much better than before.

**Comment by NightScript370** [comment]
Great! Thank you for coming back after so long to test this. I'll go ahead and close this because I don't think anything the nightly did have an impact on this, but rather, it was attached to a release that was already published.
