### ISSUE TITLE
about not translate strings

### ISSUE THREAD

**Issue by realkkk** [DS-Homebrew/TWiLightMenu#1701]
are these would be added to i18n for  translate on crowdin?
sorry for my poor english.
![20211128135558](https://user-images.githubusercontent.com/12512619/143732074-2b38bab1-3171-4cf1-9378-b1ababfeadae.jpeg)

**Comment by Samplasion** [comment]
Those are hardcoded for the theme you're using. You can find them in `sd:/_nds/TWiLightMenu/dsimenu/themes/<your theme>/ui/` if you want to manually edit them, but I don't think you could add those to Crowdin.

**Comment by realkkk** [comment]
OK, Thanks for your help!
