### ISSUE TITLE
prefetchPatch makes bad assumption: not all GBA start at 0x80000C0

### ISSUE THREAD

**Issue by khmann** [DS-Homebrew/TWiLightMenu#1706]
**Console Configuration:** NDS/DS Lite w/ GBA Slot2 card
**TWiLight Menu++ Version:** Thanksgiving 2021

### Expected behaviour
GBA games run on Slot2 as native

### Actual behaviour
While working on a personal GBA project, I noticed the function "prefetchPatch" (gbapatcher/arm9/source/main.cpp) sets the ARM7 PC=0x80000C0 when done, but several hundred of the nointro .GBAs don't actually start there.  Perhaps 0x8000000 is more correct?  (Traditionally this would have been the patch entrypoint, but here we are running from RAM)

The 2,3,4 in 1 ROMs are common offenders, also here are some randoms:
./Asterix & Obelix XXL.gba: 8000000: ea013ffe b 0x8050000
./Cars.gba: 8000000: ea000031 b 0x80000cc
./Final Fantasy IV Advance.gba: 8000000: ea00041e b 0x8001080
./Final Fantasy V Advance.gba: 8000000: ea000407 b 0x8001024
./Incredibles, The.gba: 8000000: ea000031 b 0x80000cc
./Mario Golf - Advance Tour.gba: 8000000: ea00010e b 0x8000440
./Mario Tennis - Power Tour.gba: 8000000: ea00011a b 0x8000470
./Pokemon - Ruby Version.gba: 8000000: ea000032 b 0x80000d0
./Pokemon - Sapphire Version.gba: 8000000: ea000032 b 0x80000d0

### Bonus
It would be cool to have WAIT_CNT configurable, as for example SuperCards require 4/2 timing but my M3 card (which cost 5X as much) will pass memtest all day at 2/1!  Perhaps this function should become part of the card detection & init...

**Comment by RocketRobz** [comment]
The 0x80000C0 part actually changes depending on the ROM, so the ROMs you mentioned should work fine.
*Asterix & Obelix XXL* booted, last time I tested.

**Comment by khmann** [comment]
oh, gptc_patchWait... duh <facepalm>, I see that now.  Sorry
