### ISSUE TITLE
Colors 1.1 displays error with RAM Disk option, then causes guru meditation error

### ISSUE THREAD

**Issue by BrunoDSL** [DS-Homebrew/TWiLightMenu#1709]
**Console Configuration:**  Nintendo DSi with Ulaunch 2.0
**TWiLight Menu++ Version:**  23.1.1
**TWiLight Menu++ Theme:**  DSi Theme

### Expected behaviour

App should run

### Actual behaviour

The app complains about the FAT file structure and DLDI Patch. If set to launch from a RAM Disk, the same error shows up and doing anything results in a guru meditation error.
![IMG_20211203_232349](https://user-images.githubusercontent.com/9355061/144693784-c8eb2707-8ff0-4647-8c6a-9cb30ed91344.jpg)

### Steps to reproduce

1. Put Colors! 1.1 in your SD Card
2. Set it to use a RAM Disk
3. Run it

**Comment by Epicpkmn11** [comment]
Colors! should work fine even without a RAM disk, make sure you have the latest version (https://db.universal-team.net/ds/colors, use the `colors_1_10bbeta2.zip` one)

**Comment by BrunoDSL** [comment]
I tried with the latest version and...There doesn't seem to be any option to turn off RAM Disks once you set one. Same error happens.

**Comment by BrunoDSL** [comment]
Same error happens. Also, it seems you can't turn RAM Disk creation off once it's on.
![IMG_20211203_234339](https://user-images.githubusercontent.com/9355061/144694153-05370c71-71a5-499b-92de-1e949311dd6e.jpg)

**Comment by RocketRobz** [comment]
> Same error happens. Also, it seems you can't turn RAM Disk creation off once it's on. ![IMG_20211203_234339](https://user-images.githubusercontent.com/9355061/144694153-05370c71-71a5-499b-92de-1e949311dd6e.jpg)

So you can't set `RAM disk` to `None`?

**Comment by BrunoDSL** [comment]
hyu

> > Same error happens. Also, it seems you can't turn RAM Disk creation off once it's on. ![IMG_20211203_234339](https://user-images.githubusercontent.com/9355061/144694153-05370c71-71a5-499b-92de-1e949311dd6e.jpg)
> 
> So you can't set `RAM disk` to `None`?

Yes. Pressing `Left`, `Right` or `A` doesn't change it from `0`. It also seems the error is not related to the Colors! version, as the beta one recommended has the exact same error.

**Comment by spellboundtriangle** [comment]
> Yes. Pressing `Left`, `Right` or `A` doesn't change it from `0`. It also seems the error is not related to the Colors! version, as the beta one recommended has the exact same error.

Turn Direct Boot off, you can't change the RAM Disk setting if Direct Boot is turned on. Also, [RAM disks have to be created manually](https://wiki.ds-homebrew.com/twilightmenu/creating-ram-disks), TWLM++ doesn't do it for you.

It runs fine for me with Direct Boot off & no RAM disk.

**Comment by BrunoDSL** [comment]
> Turn Direct Boot off, you can't change the RAM Disk setting if Direct Boot is turned on. Also, [RAM disks have to be created manually](https://wiki.ds-homebrew.com/twilightmenu/creating-ram-disks), TWLM++ doesn't do it for you.
> 
> It runs fine for me with Direct Boot off & no RAM disk.

I tested those and I also had to set it to run in DS Mode, otherwise it just stays at a white screen and nothing happens.

Although, the whole setting for RAM Disks is a bit counter intuitive. You should be able to set RAM Disks without Direct Boot turned on, as you can have it on with RAM Disk set to `none`.

**Comment by spellboundtriangle** [comment]
> Although, the whole setting for RAM Disks is a bit counter intuitive. You should be able to set RAM Disks without Direct Boot turned on, as you can have it on with RAM Disk set to `none`.
I think you might mean `off` rather than `on`? But this should be addressed in #1748
