### ISSUE TITLE
Atari VCS emulator - unable to browse directory/see rom files

### ISSUE THREAD

**Issue by jonesandy911** [DS-Homebrew/TWiLightMenu#1712]
**Console Configuration:**  
**TWiLight Menu++ Version:** 
twilight menu v23.1.1 / bootstrap v0.51.1
**TWiLight Menu++ Theme:** 

### Expected behaviour

In the previous versions of twilight menu I was able to browse files/directories and Atari VCS roms were visible. I could also navigate to any other directory (none were hidden?)
### Actual behaviour
Unfortunately, now I am unable to 'see' certain folders, an example would be the, '_nds', folder. Also, none of the Atari VCS files are visible even though I am in the correct rom directory.

So I am unable to load the Atari VCS emulator manually, as it resides within the ,'_nds', folder which is no longer visible. As well as not being able to see the rom files within twilight menu itself. As a side note I have also made sure that all files are visible within the settings, as well as resetting twilight menus options to default by holding the four buttons.
### Steps to reproduce

1. Fire up twilight menu
2. Try to browse to VCS rom directory
3. Notice none of the rom files are visible

**Comment by RocketRobz** [comment]
What are the ROM file extensions?

**Comment by jonesandy911** [comment]
*.bin
The roms and folder are intact from other versions.
I have not altered any of the directories, or filenames.

**Comment by RocketRobz** [comment]
`.bin` has never been supported by TWLMenu++.
You need to rename them to what's shown [here](https://wiki.ds-homebrew.com/ds-index/emulators).

**Comment by jonesandy911** [comment]
Thank you Rob.
Sorry for bothering you. I'm very appreciative of your hard work on this outstanding piece of homebrew!
