### ISSUE TITLE
Add ColecoDS emulator to Twilight Menu++

### ISSUE THREAD

**Issue by Harry7228** [DS-Homebrew/TWiLightMenu#1717]
**Is your feature request related to a problem? Please describe.**
I want to be able to open .col files (ColecoDS game files) with Twilight Menu++

**Describe the solution you'd like**
Add support for wavemotion-dave's ColecoDS game emulator to Twilight Menu++

**Additional context**
https://github.com/wavemotion-dave/ColecoDS

**Comment by lifehackerhansol** [comment]
I think this should be added after implementing https://github.com/DS-Homebrew/TWiLightMenu/issues/1690

**Comment by lifehackerhansol** [comment]
Integrated in 146b9f9c0438fe4ad8a4dbdd4f03865a105c2899.
