### ISSUE TITLE
Pokemon soul silver doesn't boot correctly if launched from twilightmenu

### ISSUE THREAD

**Issue by edo9300** [DS-Homebrew/TWiLightMenu#1734]
**Console Configuration:**  
**TWiLight Menu++ Version:** v23.2.0 
**TWiLight Menu++ Theme:** quick menu and dsi

Pokemon Soul Silver italian version (IPGI) is being used.

### Expected behaviour
Game launches and plays fine

### Actual behaviour
The game boots and plays the title screen, then after pressing a it shows a "communication error" and replays the title screen when pressing a. This doesn't happen if the game is launched instead directly using the hiya title to launch the last run game, or if the game is reset via the in game menu (resetting via the in game menu also makes it work if it was booted from twilight). Normal reset with the l+r+start+select combo also doesn't fix the behaviour.
Also even tho it says communication error, it seems to be unrelated to the wireless connectivity being on or off or it needing an IR cart (I tested with a pokemon white cart inserted).

![screenshot01](https://user-images.githubusercontent.com/18705342/147367357-5eb02fe7-7572-4b54-bdec-50880f9a4872.png)

### Steps to reproduce

1. Launch the game from twilight using the quick menu or the dsi menu
2. Get past the title screen

**Comment by RocketRobz** [comment]
This error does not occur on my side. Make sure WiFi is turned on in TWLMenu++ Settings, and then press B to exit TWLMenu++ Settings to save the setting, and then reboot the console.

**Comment by edo9300** [comment]
https://youtu.be/P3M273Kb3Kw
I recorded a video of the issue, as you can see, if I reset with the in game menu it works (I didn't record all the other scenarios but they behave as i described), also I already tried with the wifi on from twilight itself, even tho it shouldn't really make any difference as with the other boot methods the game works fine with it off in any case.

**Comment by RocketRobz** [comment]
I still can't reproduce this. How is TWLMenu++ being started? Directly by Unlaunch, or hiyaCFW?
Also, can you check if the same issue happens with Pokemon Diamond, Pearl, and/or Platinum?

**Comment by edo9300** [comment]
I'm booting directly from unlaunch 2.0, also just tested with platinum, same error and even more interesting, it gives the same error if i directly boot my platinum cart from twilight itself.

**Comment by Squall-Leonhart** [comment]
just you mate.

**Comment by Retashe** [comment]
me too, did I get any solution?

**Comment by RocketRobz** [comment]
> me too, did I get any solution?

Your solution: https://github.com/DS-Homebrew/nds-bootstrap/issues/1669#issuecomment-1886160725
