### ISSUE TITLE
Cheat support for flashcard

### ISSUE THREAD

**Issue by Minionguyjpro** [DS-Homebrew/TWiLightMenu#1737]
**Is your feature request related to a problem? Please describe.**
Yes, when i try to open the cheats menu on flashcard, it doesn't work. I tried to first press Y, then i got some information about the ROM, And then i pressed X, but it didn't do anything. This works on normal version for like 3DS.
**Describe the solution you'd like**
Being able to use cheats. It works on other firmware like R4 and TTMenu.

**Describe alternatives you've considered**
Using an program to patch the ROM and add the cheats.

**Additional context**
Cheats do work on other firmware like R4 and TTMenu.

**Comment by RocketRobz** [comment]
To use cheats, you need to turn on nds-bootstrap. There is no (known) way to use cheats on flashcard firmwares with ROMs being passed as arguments (which is what TWLMenu++ does to run games with that method).

**Comment by Minionguyjpro** [comment]
Real? Can't the cheats being booted from the official firmware? Like the R4 Menu or TTMenu?

**Comment by Minionguyjpro** [comment]
I should think you could enable it and then it enables them via the real firmware. (I'm not sure, i am not the best to know this.)

**Comment by Minionguyjpro** [comment]
I'll try NDS Bootstrap

**Comment by Minionguyjpro** [comment]
I just know this software like 1 month.

**Comment by Minionguyjpro** [comment]
I thought booting NDS Bootstrap would take long, but i see that is not true.

**Comment by Minionguyjpro** [comment]
Can i get back to the TWLMenu from a game booted from NDS Bootstrap?

**Comment by RocketRobz** [comment]
I suggest joining our Discord server, if you have more questions: https://discord.gg/yD3spjv

**Comment by Minionguyjpro** [comment]
I was already in, but okay.

Op wo 29 dec. 2021 22:59 schreef RocketRobz ***@***.***>:
