### ISSUE TITLE
Enabling widescreen mode causes console to reboot back into the home menu

### ISSUE THREAD

**Issue by 9cxndy** [DS-Homebrew/TWiLightMenu#1739]
**Console Configuration:** Luma3DS
**TWiLight Menu++ Version:** 23.4.0
**TWiLight Menu++ Theme:** Nintendo DSi

### Steps to reproduce

1. Follow widescreen mode guide
2. Enable widescreen mode for Mario Kart DS (EUR)
3. Start game

### Expected behaviour

Wide screen mode works

### Actual behaviour

3DS reboots back to the home menu (Starting the game without widescreen works perfectly).

### More details

After the console reboots back to the home menu, I checked and can see `TwlBg.cxi` is moved into `luma/sysmodules/`, and hasn't been moved back.

I don't really know much about the internals of Twilight Menu, but IIUC it tries to reboot after moving `Widescreen.cxi` to `TwlBg.cxi`, so maybe that step failed somehow?

**Comment by RocketRobz** [comment]
If you're on an O3DS/O2DS, then rebooting while in DS(i) mode doesn't work.
If you're on an N3DS/N2DS, I don't see why this would happen.

**Comment by 9cxndy** [comment]
I am on N3DS. I don't see why either, any advises how to debug this?

I tried quitting into Twilight Menu via `L+R+Down+B` and `nds-bootstrap menu > exit game`. Both works. So rebooting works in some instances, at least?

**Comment by 9cxndy** [comment]
Hmm, actually. `L+R+Down+B` isn't reliable, it does cause reboot to home menu _some_ of the times, maybe 50% success rate.

**Comment by Minionguyjpro** [comment]
I have no problems booting Mario Kart DS Europe ROM on my N2DS XL. It just boots on both normal kernel and bootstrap.

**Comment by 9cxndy** [comment]
There must be something weird about my setup then, I think? How do I figure out what went wrong?

**Comment by RocketRobz** [comment]
All I can say is to make sure both Luma and TWLMenu++ are up to date.
There is no way to debug this, unfortunately.
