### ISSUE TITLE
Can't boot DS games on DS Lite, black screen on Zelda Phantom Hourglass on New 3DS, when using nds-bootstrap

### ISSUE THREAD

**Issue by andrebrait** [DS-Homebrew/TWiLightMenu#1740]
**Console Configuration:**
Nintendo DS Lite
R4i-SDHC RTS from www.r4i-sdhc.com
Autoboot files from the `r4isdhc.com cards` folder.

On the New 3DS, I'm using the same flashcart.
The New 3DS is running Luma3DS 10.2.1
**TWiLight Menu++ Version:** 23.4.0, with DS Lite being broken as far back as 17.2.1
**TWiLight Menu++ Theme:** Nintendo DSi and Nintendo 3DS

Using a 128GB card formatted with 32KB cluster size.

### Expected behaviour

The games should boot on the DS Lite.
Zelda Phantom Hourglass should run flawlessly on the New 3DS.

### Actual behaviour

Games won't boot on DS Lite.
I get the "Saving..." screen, then the nds-bootstrap screen and then both screens go blank (full white).
Tools such as GBAExpLoader load just fine, but games won't.
I think it also ended up corrupting my save file for Phantom Hourglass once (it became a 0KB file with no modification date).

On the 3DS, I can go into the temple (see [the attached save file](https://github.com/DS-Homebrew/TWiLightMenu/files/7801304/Legend.of.Zelda.The.-.Phantom.Hourglass.USA.En.Fr.Es.zip)) but it just goes black as soon as I get to the second floor.

Everything works file if I disable nds-bootstrap and boot using the card's firmware using RetroGameFan's YSMenu.

### Steps to reproduce

DS Lite
1. Try to boot a DS game using nds-bootstrap (both Release and Nightly result in the same)
2. See a blank screen after the nds-bootstrap screen

New 3DS
1. Run Zelda Phantom Hourglass using my save file, with nds-bootstrap enabled
2. Run forward (up) and enter the dungeon
3. Keep going up and go to the second floor
4. You should see a black screen and nothing else

**Comment by RocketRobz** [comment]
DS Lite: I've tried Phantom Hourglass on OG DS with nds-bootstrap, and booted fine on my side, last time I tried, though game compatibility varies by flashcard.
As for the save file becoming 0KB, sounds like your SD card is dying. I suggest trying a different SD card to ensure it's not an nds-bootstrap issue.

New 3DS: Try adjusting some settings in the per-game settings menu (opened by pressing Y in the TWLMenu++ ROM listing).

**Comment by andrebrait** [comment]
@RocketRobz the SD card is fine. That only happened when using nds-bootstrap and even when that wouldn't happen, the save file would be overwritten (on 23.4.0). On older builds it wouldn't be overwritten, but I could not boot anyway.

It wasn't just Phantom Hourglass that couldn't boot on the DS Lite. I can't boot any DS games at all. Have to call back to the card's firmware.

I checked the hash of the ROM and it looks good. Maybe the thing on the 3DS also has to do with the card?

**Comment by RocketRobz** [comment]
> @RocketRobz the SD card is fine. That only happened when using nds-bootstrap and even when that wouldn't happen, the save file would be overwritten (on 23.4.0). On older builds it wouldn't be overwritten, but I could not boot anyway.

This bug does not happen on my side.
What happens is that nds-bootstrap backs up and writes back a specific byte in the .sav file, so that the modified date gets updated, but in your case, for some reason, the file becomes 0 bytes.

What is the size of your flashcard's SD card?

> I checked the hash of the ROM and it looks good. Maybe the thing on the 3DS also has to do with the card?

Possibly. I suggest trying a 32GB (or lower) SD card for both the flashcard and 3DS.
