### ISSUE TITLE
Visually disable RAM Disk option if Direct Boot is turned on

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#1748]
**Is your feature request related to a problem? Please describe.**
When Direct Boot is turned on, the RAM Disk setting is unable to be changed, but it looks like it's enabled.

**Describe the solution you'd like**
Visually indicate to the user that the RAM Disk setting is not used, in some way. Some options would be:
- "Lighten" the text
- Show "Disabled" or "N/A" in place of the slot number
- Hide the setting completely

**Describe alternatives you've considered**
As part of #1680, it could inform the user that the RAM disk won't be applied if using Direct Boot & RAM Disk is set.

**Additional context**
N/A

**Comment by NightScript370** [comment]
I prefer changing the color. Easiest way to still see the configuration you used to have before you swapped Direct Boot options.

**Comment by NightScript370** [comment]
It's probably best to restructure this issue to now account for the new update.
The original request has now been vanquished.

**Comment by spellboundtriangle** [comment]
The other issue (#1680) kinda takes care of the rest of this, so I guess this can just be closed entirely.
