### ISSUE TITLE
Sadly, No Games Work On 2DSXL.

### ISSUE THREAD

**Issue by HelgenX** [DS-Homebrew/TWiLightMenu#1752]
Hi, I've tried quite a few DS games on this (all of the Castlevania's, Final Fantasy 3, something else.) None of them load. FF3 went to the intro, then just crashed, the rest just a white screen after the TL loading screen. I've been using a Gateway to load the DS games, but I would rather use your software. Any help would be greatly appreciated.

**Comment by Minionguyjpro** [comment]
At me works fine on N2DSXL so i think it is a problem at you.

**Comment by HelgenX** [comment]
Actually, it did work! It was my fault, I was missing one file, something booter.cia. Everything is working now on my 2DSXL (the one with the baby bluish color.) Thanks!
