### ISSUE TITLE
Feature Request: Infrared support for Game Boy Color on 3DS TWiLightMenu++

### ISSUE THREAD

**Issue by MarkEire** [DS-Homebrew/TWiLightMenu#1763]
**Is your feature request related to a problem? Please describe.**
It would be amazing to have a means to use the niche IR feature of the GBC. I've struggled to find a means to do this via any sort of emulation, and given the 3DS IR capabilities perhaps this would be a way to allow these IR game features to be preserved.

**Describe the solution you'd like**
Support for IR features running GBC games. Whether via 3DS console IR, or via an IR capable DS cartridge (eg. Pokémon Heart Gold).

**Describe alternatives you've considered**
Attempting to use Mystery Gift function between two copies of Pokémon Crystal, I have not successfully found a means. I believe the GBEplus emulator should have the capability, but I've not had any successful attempts yet personally. Considering any other hardware (eg. WiiU), I don't believe any support the means to communicate via IR in a GBC game.

**Additional context**
Being able to experience the IR feature in physical hardware would be a fantastic way to preserve this GBC feature. Whilst software emulators may have a means to do some features one day (such as Pokémon Mystery Gift), some games such as "Chee Chai Alien" work via holding against different light sources, blocking the IR with your finger and so on. Without some sort of IR capable hardware running GBC games, these experiences are currently impossible outside of original hardware.

After asking in the Discord, I believe this may be a possible feature request (though I lack the knowledge to appreciate how difficult I'm sure this may be). Some limitations accessing the 3DS console hardware IR were noted, but whether 3DS or an IR capable DS, any means at all would be fantastic.

Thanks very much for all the work on TWiLightMenu++, it is a fantastic tool to use.

**Comment by RocketRobz** [comment]
1. DS(i) mode cannot access the console's IR port, so IR support would have to be implemented in an emulator for 3DS mode (ex. mGBA).
2. TWiLight Menu++ doesn't run GB(C) games. GameYob does.
