### ISSUE TITLE
Slot-1 microSD access broken

### ISSUE THREAD

**Issue by lifehackerhansol** [DS-Homebrew/TWiLightMenu#1773]
**Console Configuration:** DSi XL 1.4.5, Unlaunch 2.0, R4 Ultra
**TWiLight Menu++ Version:** 53c90e77
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

R4 Ultra SD is accessed when pressing SELECT+UP/DOWN

### Actual behaviour

It does nothing

### Steps to reproduce

1. Enable Slot-1 microSD access
2. Try to switch drives

**Comment by lifehackerhansol** [comment]
Appears to be specific to the DSi? Another tester had it working with a 3DS but they have _other_ unrelated issues.

**Comment by RocketRobz** [comment]
I remember it working before d2830cea, so maybe somewhere in that commit broke it.

**Comment by lifehackerhansol** [comment]
This didn't work for me on release either, again on a DSi. The 3DS tester was on release as well and they didn't test the nightly.

**Comment by lifehackerhansol** [comment]
This is reproducible on the AK2i (the one other cart that supports this function) and thus this feature is broken as a whole.
