### ISSUE TITLE
R4 Ultra DSi mode not working with Slot-1 microSD access

### ISSUE THREAD

**Issue by lifehackerhansol** [DS-Homebrew/TWiLightMenu#1774]
**Console Configuration:** DSi XL 1.4.5, Unlaunch, R4 Ultra
**TWiLight Menu++ Version:** https://github.com/DS-Homebrew/TWiLightMenu/commit/dfd46b1010e2665322c813afc7c1552edef9a5c1
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behaviour

DSi Enhanced games (only Black 2 tested at this time) work from the R4 Ultra's microSD.

### Actual behaviour

Freezes on a white screen. (Unsure if this is a nds-bootstrap fault or a TWiLight fault, to be quite honest.)

### Steps to reproduce

1. Get an R4 Ultra
1. Launch TWiLight Menu++ with Slot-1 microSD access
1. Get some DSi ROM and launch it

#### Notes
The nds-bootstrap in-game menu is still active, so the game doesn't appear to be crashing.

**Comment by lifehackerhansol** [comment]
This was also reported in the release version.

**Comment by RibShark** [comment]
This doesn't appear to be a flashcart specific issue, the same behaviour occurs on a R4i Gold 3DS Plus when running from the flashcart with nds-bootstrap (tested with Pokémon Black/Black 2); non-DSi Enhanced games work fine when booted in this manner).

**Comment by lifehackerhansol** [comment]
> This doesn't appear to be a flashcart specific issue, the same behaviour occurs on a R4i Gold 3DS Plus when running from the flashcart with nds-bootstrap (tested with Pokémon Black/Black 2); non-DSi Enhanced games work fine when booted in this manner).

The R4i Gold 3DS Plus doesn't support Slot-1 microSD access. Are you booting the flashcart via TWiLight with SCFG access turned on?

I actually haven't tested with SCFG access on, but I do know that Slot-1 microSD access launching is different from it, so I'd hesitate to say it's the same bug.

**Comment by RibShark** [comment]
> Are you booting the flashcart via TWiLight with SCFG access turned on?
Yes. I wasn't aware the launching was that different, but it certainly seems to cause the same effects regardless (white screen with working nds-bootstrap menu).

**Comment by RocketRobz** [comment]
Slot-1 microSD access has been fixed in v24.0.0.

**Comment by lifehackerhansol** [comment]
Has it? Black 2 still white screens in DSi mode when ran from R4 Ultra.

**Comment by lifehackerhansol** [comment]
Seems the game did crash, but didn't crash enough for the IGM to be active. Usually the power button is instant, but it was not instant here. (Tested on a DSi.)

This is almost certainly an nds-bootstrap issue.
