### ISSUE TITLE
TWL_FIRM stays in widescreen after opening game

### ISSUE THREAD

**Issue by guusbuk** [DS-Homebrew/TWiLightMenu#1776]
I'm using a N3DSXL using firmware 11.15.0-47E and Luma v10.2.1 (nanquitas) and the latest TWLmenu++ and ndsbootstrap on Universal Updater (v23.4.0 and v0.53.2 respectively) with the dsi theme.

### Expected behaviour

I ran TWpatch, enabled widescreen and moved TwlBg.cxi from sd:/luma/sysmodules/ to sd:/_nds/TWiLightMenu/TwlBg/ while renaming it to Widescreen.cxi and enabled widescreen in the per-game-settings. The game should be in widescreen, while other TWL_FIRM (such as ds download play and TWLMenu) should stay in the original resolution.

### Actual behaviour
When i now launch a game it shows a white screen and goes back to the 3ds home menu. Now every app that uses TWL_FIRM stays in widescreen including ds download play, ds internet settings, twilightmenu and every game launched from it.
I noticed that the Widescreen.cxi file gets moved (copied and deleted in the original place) to luma/sysmodules/ and named to TwlBg.cxi. When i do Move TwlBg.cxi from sd:/luma/sysmodules/ to sd:/_nds/TWiLightMenu/TwlBg/ (create TwlBg folder, if it doesn’t exist), and rename the file to Widescreen.cxi again it is fine, untill i try to open a game in widescreen and it repeats.

### Steps to reproduce

1. Follow https://wiki.ds-homebrew.com/twilightmenu/playing-in-widescreen
2. reinstall TWilightMenu as stated on the bottom of the page
3. enable external FIRMs and modules in Luma's configuration
4. enable widescreen in per-game-settings
5. Open a widescreen compatible game (which you enabled widescreen for)

**Comment by guusbuk** [comment]
I enable loading external firms. Using gm9 i copy Twlbg.cxi to clipboard and past it twlmenu/twlbg and select move paths. and using R+X rename it to Widescreen.cxi. I reboot my system. Open twlmenu (is in normal resolution) select mario kart ds. Press y and set screen aspect ratio to 16:10. Open it. Gets to now saving screen, doesn't load nds bootstrap and softresets to 3ds home menu. Now every ds title (incl. twlmenu and games) are in widescreen. Widescreen.cxi isn't in twilightmenu/twlbg and twlbg.cxi is back in luma/sysmodules.
I haven't included any capitals in my message but i check if they were correct on my 3ds.

**Comment by RocketRobz** [comment]
Make sure you're using the non-modified Luma version, and that it's in the SD root, and named `boot.firm`.

**Comment by guusbuk** [comment]
> Make sure you're using the non-modified Luma version, and that it's in the SD root, and named `boot.firm`.

What do you mean with non-modified? Do you mean the original luma3ds instead of nanquitas fork?

**Comment by guusbuk** [comment]
Using the original Luma from uu solved the problem. Do you happen to know what the difference is?

**Comment by RocketRobz** [comment]
The fork probably doesn't preserve the TWL autoboot check.

**Comment by DullPointer** [comment]
> The fork probably doesn't preserve the TWL autoboot check.

Where in original Luma is the TWL autoboot check persevered? It would be cool to see if that could be fixed in the fork. Sorry if this is considered off topic.
