### ISSUE TITLE
Cheats enabled in the DSTwo In-Game Menu do not save after enabling them when running NDS games from TWiLightMenu on DSTwo Kernel

### ISSUE THREAD

**Issue by winsupermario1234** [DS-Homebrew/TWiLightMenu#1790]
Console Configuration: Nintendo DS Lite with Supercard DSTwo Flashcard
TWiLight Menu++ Version: New Year's Release
TWiLight Menu++ Theme: Nintendo 3DS

Expected behaviour:

After enabling cheat codes in the DSTwo In-Game Menu opened by pressing L+R+Start, the cheats should be promptly enabled in the game that is running.

Actual behaviour:

Nothing happens after enabling the cheats and going back to the cheats menu shows that they were disabled again. Any cheats that were enabled were not saved.

Steps to reproduce:

1. Run an NDS game in TWiLightMenu on a DSTwo using the DSTwo kernel instead of nds-bootstrap.
2. Open the In-Game Menu with L+R+Start key combo and browse to Cheats menu.
3. Enable whichever cheats you please and then exit the cheats menu with B.
4. Browse back to the cheats menu to see that all the cheats didn't work and were all disabled again.

**Comment by winsupermario1234** [comment]
Additional information: I am running TWiLightMenu to autoboot upon running the flashcard and I am using DeadSkullzJr's usrcheat.dat in the _dstwo folder.

**Comment by lifehackerhansol** [comment]
This is reproduceable in the actual EOS kernel. I was not able to get a single cheat to properly enable from the in-game menu of the DSTWO and DSTWO Plus (or at all, actually.) Testing Black 2 and NFSU2, this is the case.

Thus, this is outside the scope of TWiLight Menu++.

**Comment by winsupermario1234** [comment]
> This is reproduceable in the actual EOS kernel. I was not able to get a single cheat to properly enable from the in-game menu of the DSTWO and DSTWO Plus (or at all, actually.) Testing Black 2 and NFSU2, this is the case.
> 
> Thus, this is outside the scope of TWiLight Menu++.

Really? I found that I was able to enable cheats again once I stopped autobooting TWiLightMenu++ and just used the EOS kernel. Furthermore, I was able to enable and use cheats in both the games you mentioned. Using DeadSkullzJr's database works flawlessly in this regard.

**Comment by lifehackerhansol** [comment]
Is your ROM set to "Patch" or "Clean" mode? I couldn't use Clean on Black 2 so I just tested both using patch, which isn't supposed to break cheats but who knows.

**Comment by winsupermario1234** [comment]
Is that a setting in EOS or TWiLightMenu? I don't believe I'm using any patches at all in my ROMs.

**Comment by lifehackerhansol** [comment]
It is an EOS setting. Press X on your game before launching.

**Comment by winsupermario1234** [comment]
Ah. It looks like when loading from the EOS kernel menu they were booting using Patch all along and I wasn't even aware. Could they not be booting this way when loading from TWiLightMenu using the EOS kernel (as opposed to nds-bootstrap)?

**Comment by lifehackerhansol** [comment]
For maximum compatibility, patch should be left on.

**Comment by winsupermario1234** [comment]
Is there something that must be set to boot it in "Patch" when loading from TWiLightMenu while using the EOS kernel/other flashcard kernel?

**Comment by lifehackerhansol** [comment]
I believe it's set to patch by default.

**Comment by winsupermario1234** [comment]
Weird, I wonder why it wouldn't work then.
That's okay, I found that file browsing in the EOS kernel menu is faster anyway and I can always boot TWiLightMenu manually.
I've got two DSTwos and a bunch of SD cards so I can always do a bit of experimenting and find out what's happening.
Doesn't seem like it's a bug with TWiLightMenu so I'll be happy to leave it at that.

**Comment by rods-03** [comment]
I know this thread is old but I would like to ask a question.

I also have a DSTWO and I can't load any roms through nds-bootstrap in TWiLightMenu. A red screen always appears with the message "Error: Data abort!".

Do you know any solution besides the EOS kernel?

**Comment by RocketRobz** [comment]
> I know this thread is old but I would like to ask a question.
> 
> I also have a DSTWO and I can't load any roms through nds-bootstrap in TWiLightMenu. A red screen always appears with the message "Error: Data abort!".
> 
> Do you know any solution besides the EOS kernel?

You'll have to wait for a fix (if it ever comes).
