### ISSUE TITLE
Load a specific directory, regardless of previously used one where the game was launched

### ISSUE THREAD

**Issue by Minionguyjpro** [DS-Homebrew/TWiLightMenu#1794]
**Is your feature request related to a problem? Please describe.**
No.
**Describe the solution you'd like**
Add an option in the settings to select which directory to start in. Add the options to start in the root (The home directory of the flashcard or console), or in the directory where the menu was previously loaded (I mean like you play an game in a directory called ``NDS Games`` and then exit and open the menu again, it will open the menu up in the ``NDS Games`` directory)

**Comment by Epicpkmn11** [comment]
Is the main request here the ability to force it to start in root? I'm not sure exactly what's being asked since it kinda sounds like you're asking for it to be able to start in the last directory, which is already the current behaviour...

An ini option to force a directory to start in would be pretty easy, not sure how best to incorporate it into the GUI though.

**Comment by Minionguyjpro** [comment]
> Is the main request here the ability to force it to start in root? I'm not sure exactly what's being asked since it kinda sounds like you're asking for it to be able to start in the last directory, which is already the current behaviour...
> 
> An ini option to force a directory to start in would be pretty easy, not sure how best to incorporate it into the GUI though.

To choose a directory.

**Comment by Minionguyjpro** [comment]
> Is the main request here the ability to force it to start in root? I'm not sure exactly what's being asked since it kinda sounds like you're asking for it to be able to start in the last directory, which is already the current behaviour...
> 
> An ini option to force a directory to start in would be pretty easy, not sure how best to incorporate it into the GUI though.

Couldn't you make it that allows you to select a folder that exists, change the value to that and done?
