### ISSUE TITLE
Touch input is broken when booting a Slot-1 game

### ISSUE THREAD

**Issue by AlphaNERD-** [DS-Homebrew/TWiLightMenu#1795]
**Console Configuration:** European Nintendo DSi XL with Unlaunch
**TWiLight Menu++ Version:** 23.4.0 (d638c32)
**TWiLight Menu++ Theme:** Nintendo DSi (White)

### Expected behaviour

When i boot up a Slot-1 game through the Select menu, touch input still works properly and i can start games.

### Actual behaviour

The touch input doesn't work properly if at all. Depending on the game it works until the game asks me to tap the bottom screen to start. This can prevent me from actually playing the games.

I noticed this first with Viva Pinata. I tested this with Sims 3, Settlers and Art Academy (randomly picked out of my library) and every game had this problem. When i boot the games from the DSi firmware, touch works fine.

I tested touch input with a few randomly picked games from my SD card (Henry Hatsworth, 42 All-Time Classics, Emergency DS and Sims 3) and touch works properly in these games.

### Steps to reproduce

1. Boot the Nintendo DSi XL
2. Press Select to open the menu
3. Boot the Slot-1 cartridge (Please note: I disabled the DS-style menu. I don't like the look of it on my DSi XL.)

**Comment by RocketRobz** [comment]
In TWLMenu++ Settings, you need to switch `Slot-1 touch mode` to `DS mode`, as that's set by default.
