### ISSUE TITLE
r4ultra flashcard loader white screen on slot1

### ISSUE THREAD

**Issue by CaiMiao** [DS-Homebrew/TWiLightMenu#1806]
**Console Configuration:**  DSLite / 3DS slot1 w/ R4SDHC flashcard (www.r4ultra.com, non DSi, old r4 clone), R4Ultra Autoboot + Loader installed, nds-bootstrap turned off
**TWiLight Menu++ Version:**  [this](https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v24.0.0)
**TWiLight Menu++ Theme:**  DSi

### Expected behaviour

profit ~~never see it behave as intended~~

### Actual behaviour

not launching rom. shows white screen when launching rom, hitting A and B button return to theme menu

### Steps to reproduce

1. launch slot1
2. launch rom
3. tada

**Comment by lifehackerhansol** [comment]
Took out my DS Lite, took out my R4 Ultra, extracted TWiLight, extracted R4 Ultra autoboot and flashcart loader, launched Sonic & SEGA All-Stars Racing.

Game launched with no issues whatsoever, and my Rumble Pak still works with it, and it showed the AKAIO loading logo as always. 

Not sure what's going on with your flashcart, but there is absolutely nothing wrong going on in my end. I did test on a freshly formatted SD card with only the above files on it.

**Comment by CaiMiao** [comment]
formatted and it works, wonder if random bad clusters or something.
