### ISSUE TITLE
White screen freeze when leaving setting menu

### ISSUE THREAD

**Issue by CaiMiao** [DS-Homebrew/TWiLightMenu#1809]
**Console Configuration:** new 3ds xl + 3ds setup
**TWiLight Menu++ Version:** [this](https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v24.0.0)
**TWiLight Menu++ Theme:** dsi

### Expected behaviour
save setting and go back main menu

### Actual behaviour
white screen freeze when leaving setting menu, after updating to the latest version.  
and seems settings are saved.

tested with fresh install and sd format. but [previous release](https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v23.4.0) exits without problem.

### Steps to reproduce

1. install twilightmenu
2. hold select to enter setting menu
3. press b to exit
4. tada

**Comment by spellboundtriangle** [comment]
This is a known issue and will be fixed in the next release.
