### ISSUE TITLE
Add Completed Dutch Language To TWLMenu

### ISSUE THREAD

**Issue by Minionguyjpro** [DS-Homebrew/TWiLightMenu#1810]
I completed the Dutch language for TWLMenu on Crowdin. Can it now be implemented?

**Comment by RocketRobz** [comment]
If you added it via CrowdIn, it should be part of this PR: https://github.com/DS-Homebrew/TWiLightMenu/pull/1742

**Comment by Epicpkmn11** [comment]
Just updated #1742 so yep, it'll be updated when that's merged.
