### ISSUE TITLE
The volume buttons on my dsi have no effect on the twilight menu ++

### ISSUE THREAD

**Issue by Dievato** [DS-Homebrew/TWiLightMenu#1814]
I am new to this and possibly I have made the wrong issue, but I would like significant help, the fact is that I was happy with twilight menu ++ for a long time, that is until today, when I realized that the volume has remained at the highest point and despite lowering the volume with the buttons on the dsi there is no change (both in the menu and in the games), these buttons are not damaged, since they work correctly with the up and down function the brightness of the screens, really the last thing I did was add pc engine games taking advantage of the emulator, so I don't know if I've moved any important files, and this happens even using the original dsi launcher, so I hope not my dsi has crashed.

the version of the twilight menu is v13.0.0, in a dsi 1.45 japanese model

**Comment by RocketRobz** [comment]
Please update TWiLight Menu++ to the latest version.

**Comment by Dievato** [comment]
> Please update TWiLight Menu++ to the latest version.

I have updated it to 24.0.0, but the problem persists

**Comment by RocketRobz** [comment]
Try starting Launcher from the Unlaunch menu, then launch a title from there.
If the issue persists, then your hardware is bugged.

**Comment by Dievato** [comment]
> Intente iniciar Launcher desde el menú Unlaunch, luego inicie un título desde allí. Si el problema persiste fuera de TWLMenu++, entonces su hardware tiene errores.

And if so, is there any fix besides a repair?

**Comment by Dievato** [comment]
> Try starting Launcher from the Unlaunch menu, then launch a title from there. If the issue persists outside of TWLMenu++, then your hardware is bugged.

And if so, is there any fix besides a repair?

**Comment by RocketRobz** [comment]
> > Try starting Launcher from the Unlaunch menu, then launch a title from there. If the issue persists outside of TWLMenu++, then your hardware is bugged.
> 
> And if so, is there any fix besides a repair?

Nope. A hardmod/repair (or buying another console) is the only way.

**Comment by RocketRobz** [comment]
> Nope. A hardmod/repair (or buying another console) is the only way.

Before ruling that out, try opening DSi Sound, and adjust the volume from there.

**Comment by RocketRobz** [comment]
Closing due to no response.
