### ISSUE TITLE
3DS theme on DSi has glitchy bar on the top screen

### ISSUE THREAD

**Issue by Raiyan-AP** [DS-Homebrew/TWiLightMenu#1820]
**Console Configuration: DSi 1.4.5A with memory pit**  
**TWiLight Menu++ Version: 24.1.0** 
**TWiLight Menu++ Theme: 3DS** 

### Expected behaviour
Top screen, flash cart and manual icon with no glitch

### Actual behaviour
The middle of the top screen will have a glitchy bar every few seconds that lasts for a frame maybe. The manual and flashcart icons will also have smaller glitchy bars on them.
![3ds theme glitch](https://user-images.githubusercontent.com/89087265/155206505-7d6f00c0-7ed5-4cbc-9737-88e09942cab5.jpg)

### Steps to reproduce

1. Open twilight menu with the 3ds theme
2. Wait for the glitch to occur

I tried reformattting the sd card, reinstalling twilight menu, and changing the framerate from 60 to 50 but it still happens. I first installed twilight menu from version 24.0.0 but the glitch persists with 24.1.0

**Comment by RocketRobz** [comment]
There is no way to fix this bug, possibly due to leftover code from the DSi Camera app.
Please install Unlaunch, and use it to run TWLMenu++.

**Comment by Raiyan-AP** [comment]
> There is no (known) way to fix this bug, possibly due to leftover code from the DSi Camera app. Please install Unlaunch, and use it to run TWLMenu++.

That's unfortunate but I found a potential fix for at least the top screen. If you remove the 3dsRotatingCubes.rvid file then the top screen won't glitch out anymore but the bottom screen flashcart and manual icons will still have a glitch.
