### ISSUE TITLE
Ultimate mortal Kombat multiplayer TWLmenu

### ISSUE THREAD

**Issue by luizsaling** [DS-Homebrew/TWiLightMenu#1821]
**Console Configuration:**  
**TWiLight Menu++ Version:** 
**TWiLight Menu++ Theme:** 

### Steps to reproduce

1.
2.
3.

Hello friends, how are you?  thanks for the app it's awesome, but i found a problem in ultimate mortal kombat(nds game)  when i try to start the multiplayer mode it doesn't work.  I'm using 3ds, 2dsa.  can anyone help me?
V18.3.0
Nds bootstrap v0.35.s5

**Comment by RocketRobz** [comment]
Please update TWiLight Menu++ and nds-bootstrap, as various improvements and bug fixes have been made since then.

**Comment by luizsaling** [comment]
thanks man but not work too

**Comment by RocketRobz** [comment]
1. What happens, exactly?
2. Did you try all 3 options in the Local Wireless menu?
3. How did you update TWiLight Menu++ and nds-bootstrap?

**Comment by RocketRobz** [comment]
Just tried Download Play, and worked fine for me.
Make sure you've updated using Universal-Updater, and not the discontinued TWiLight Menu++ Updater.

**Comment by luizsaling** [comment]
1 - I choose multiplayer mode, when it comes to character selection there is a "communication error" and it crashes.
2-  only 2 because I have 2 roms downloaded. I don't know how to play download play through twl
3 - I downloaded the current version here from the forum, replaces the files in the root of the sd and installed the two cias, changed the twl options to wifi on

**Comment by RocketRobz** [comment]
Please check if wireless works in other games. If it doesn't work, then your console's WiFi card is either broken not properly seated.

**Comment by luizsaling** [comment]
yes, i did the test with mario kart and it worked

**Comment by RocketRobz** [comment]
> yes, i did the test with mario kart and it worked...
>
> only mortal kombat that doesn't work

I have no clue as to what's wrong then.

> 2- only 2 because I have 2 roms downloaded. I don't know how to play download play through twl

To use download play/single-card play, just select the option in the game, and on the other console, open the DLP app.

**Comment by luizsaling** [comment]
OK!  the dlp won't work here, I won't play anyway.. I imagine the rom must need some patch but I have no idea where to find it or how to do that...
Thank you very much for your attention!
