### ISSUE TITLE
Custom icons for folders

### ISSUE THREAD

**Issue by cwacha** [DS-Homebrew/TWiLightMenu#1837]
I like the custom icons feature for apps and roms as implemented in #1800. It would be great to get the same functionality for folders including the "back folder" icon that lets you go up.

The roms folder by default has lots of sub folders for each rom type and its quite annoying to find the one called "nds" for example. All you get is the text that shows when you select the icon. Custom icons would help distinguish the different folders. And the feature is already there it just does only work on files.

Let me know if you need more details or explanations.

Cheers
Clemens

**Comment by cwacha** [comment]
Thanks, I confirm it works. But not as described in the original issue.
It works when a 32x32 PNG file is placed inside the ./icons folder and named as <folder>.png

Not sure though if  "<..>" folder icon can also be changed.

**Comment by DieGo367** [comment]
Yeah the back folder works. Just have to name the icon `...png`, an incredibly cursed filename.
