### ISSUE TITLE
Add one more level of speed in the scrollbar

### ISSUE THREAD

**Issue by RS55** [DS-Homebrew/TWiLightMenu#185]
With the menu full of games and that pressing L or R does not return you to the last previous position, I think it would be fair to add a level of speed. Something like what happens in the 3DS menu.

**Comment by NightYoshi370** [comment]
Wouldn't that be inconsistent for the DSi theme?
If this goes get implemented, it should be for the 3DS theme only.

Although, now you have inspired me for my own idea

**Comment by NightYoshi370** [comment]
@RS55 can you test using the latest TWLMenu++ and see if your suggestion has been implemented in #420?

**Comment by NightYoshi370** [comment]
This wasn't explicitly implemented but the benefits of what you want are there.
If you want a more accurate scrolling, open up a new issue
