### ISSUE TITLE
TWLMenu++ start YSMenu instead of game

### ISSUE THREAD

**Issue by niansa** [DS-Homebrew/TWiLightMenu#186]
### Your console

- [x]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release _6.0.0_
- [ ]  I've compiled myself
- [ ]  Old release

### Flashcard

Tell us which Flashcard you are using:

![R4iSDHC Gold Pro 2018 RTC](http://www.r4isdhc.com/wp-content/themes/nds9/images/g/31.jpg)

### Expected behaviour

The game should start

### Actual behaviour
YSMenu starts (with the directory which contains the game which i should be started)

### Steps to reproduce

1. Start the Flashcard
2. Go to Games
3. Select BOOT_fc.nds and start it
4. Start the game from DSiMenuPlusPlus

**Comment by Robz8** [comment]
Is your ysmenu folder named `TTMenu` or `YSMenu`?

**Comment by niansa** [comment]
It's named TTMenu. Because I have TWLoader installed on it (the side on the Flashcard to be able to boot flashcard games directly from TWLoader).

**Comment by NightYoshi370** [comment]
@niansa does this happen on the latest version?

**Comment by niansa** [comment]
Nope, it got even WORSE. Not it says that nds-bootstrap is missing, even if it isn't.

**Comment by FlameKat53** [comment]
hello, i would like to add my 2¢ my card (R4i-SDHC 3DS RTS) can not auto-boot TWiLight Menu++ either, (supposedly, it is a DSTT DLDI(boyakkey ver.) as of a custom build that shows the card name that Robz provided to me) if I use *any* of the auto-boot files (I tried them all) it will say “Menu?” With a MicroSD Card with this type face 😥

**Comment by niansa** [comment]
Yep, same problem. It does not want to load any R4.dat files except the official one... Probably it is signed.

**Comment by FlameKat53** [comment]
well, I guess YSMenu is too, I wonder how we could get boot_fc.nds to be signed

**Comment by niansa** [comment]
I checked it and redownloaded it, but there is still the same Problem.

**Comment by niansa** [comment]
I am pretty sure that the problem is the faulty DLDI of that model...

**Comment by niansa** [comment]
Hmm, Even GBARunner2 doesn't work. At the ROM selections it says at the top of the screen: "     N   IO Library" and if I start any GBA Gameit stucks at "COPYN   IO Library"

**Comment by FlameAlt53** [comment]
so, (alt account btw) i used a file which is called "fincs' bootstrap" which let me autoboot twilight menu++ and will be included in v7.4.0 and up, as far as i know, the "fincs' bootstrap" only works on cards that use R4.dat to boot

**Comment by FlameKat53** [comment]
https://cdn.discordapp.com/attachments/286686210225864725/542787520228753456/Test_for_twilight_autoboot.zip

**Comment by niansa** [comment]
Does it work on latest autoboot files now? Can't find my R4 rn but if yes I'll search and try

**Comment by niansa** [comment]
yes it does! :D

**Comment by reagan-afk** [comment]
I need help I do what it sead on r4 twighlite menu I don't like nds bootstrap cause it don't want to play bowser inside story so I set boot strap to no and delete ed the gba diners and nds boot strap and it just resets twighlite menu
I have the gold she has it too

**Comment by poopman97** [comment]
The ysmenu.ini file is probably write protected
