### ISSUE TITLE
Loading DSi enhanced game turns off my DSi

### ISSUE THREAD

**Issue by cgamer891** [DS-Homebrew/TWiLightMenu#1861]
I recently found out about this and installed it and so the first game I got on this was Pokémon Black 2 but when I try to launch it, my DSi turns off

**Comment by RocketRobz** [comment]
If you have cheats installed, try deleting the `usrcheat.dat` file.

**Comment by cgamer891** [comment]
I don’t have anything else installed

**Comment by RocketRobz** [comment]
Try turning off `Update recently played list` in TWLMenu++ Settings (opened by pressing SELECT and then touching the DS icon).

**Comment by cgamer891** [comment]
Doesn’t change anything, also I actually don’t think it turns off, it turns off the screen completely but the power button is fading the brightness of the blue instead of staying solid

**Comment by RocketRobz** [comment]
Your ROM might be either corrupted or have it's DSi code corrupt then. Try switching `Run in` to `DS mode` in the per-game settings menu (opened by pressing Y in TWLMenu++), or redump your ROM to run in DSi mode.

**Comment by cgamer891** [comment]
It won’t let me run in DSi mode so that’s what I’ve tried

**Comment by cgamer891** [comment]
But I will try redumping the files

**Comment by RocketRobz** [comment]
Since there has been no update, I'll assume this is fixed.
