### ISSUE TITLE
hola dios :3

### ISSUE THREAD

**Issue by Owan-ctrl** [DS-Homebrew/TWiLightMenu#1863]
is it possible that in the twl of the DSI, in the splash, you can put the zelda logo?
it would look great

as transparent, in the screenshot above, only if you can :3

**Comment by RocketRobz** [comment]
Where's the screenshot?

**Comment by Epicpkmn11** [comment]
The boot splashes are just GIF files and TWiLight allows custom ones, so should be able to do that yourself. See [the wiki page](https://wiki.ds-homebrew.com/twilightmenu/custom-boot-splashes) for details.

The bundled GIFs are here: https://github.com/DS-Homebrew/TWiLightMenu/tree/master/title/nitrofiles/video/splash

Though currently the sound effect is only supported on the bundled GIFs, not custom ones... I can look into adding some way to do sounds with custom ones just haven't gotten around to it... Also if you edit them you'll need to somehow set the user input flag on the last frame as that's what TWiLight uses to wait for input. It's an official part of the GIF spec but rarely used so most editors clear it. You can use [this Python script](https://gist.github.com/Epicpkmn11/90d1c3008e61beaf9f928fd57221cd49) to do so, just do `python3 gif-input-flag.py dsi.gif 111` or such.

**Comment by Owan-ctrl** [comment]
I really have no idea how to do it, I'm just a hobbyist, I have no programming knowledge. I just wanted to know if it's possible, or if you can make a selda version of the twl version. You would not have to change anything if not, put logos on it. I really like what you do, you gave life to my consoles :3

**Comment by Owan-ctrl** [comment]
osea que descargo los archivos, agrego el gif en la dirección que me acabas de pasar y vuelvo a pasar todos los archivos a la memoria de la dsi cierto?

**Comment by Epicpkmn11** [comment]
(DeepL translated as my Spanish isn't great)
> so I download the files, add the gif in the address you just gave me and then transfer all the files back to the dsi memory, right?

You need to put them at `sd:/_nds/TWiLightMenu/extras/splashtop.gif` (top screen) or `sd:/_nds/TWiLightMenu/extras/splashbottom.gif` (bottom screen), as the wiki page says, then set `DSi Splash Screen` to `Custom` in settings. fyi that wiki page is also [in Spanish](https://wiki.ds-homebrew.com/es-ES/twilightmenu/custom-boot-splashes).

**Comment by Owan-ctrl** [comment]
gracias por la atención, no pensé que fuera tan eficaz :3
antes, disculpen las molestias :3
