### ISSUE TITLE
Other systems games not showing up.

### ISSUE THREAD

**Issue by astigb** [DS-Homebrew/TWiLightMenu#1864]
New 2ds xl
Luma3ds latest
Latest twl 
v24.2.1: MAR10 Day (2022) (hotfix)

When in menu selecting games from gb, gba, nes or snes not all the games are showing up. Only about 100. Then stops at about H,J. They all used to show up. But after updating via Universal, all other systems don't show all games. 

All games from nds however do show up.

Recreate

Copy a few hundred games into gba folder and scroll through using any theme.

**Comment by spellboundtriangle** [comment]
This is likely due to a change in the Valentine's Day release:
`- To cut down on wait times, the maximum limit of found files/folders (even those not displayed) is now 320.`

**Comment by astigb** [comment]
Ahhh. Ok. Yes that would be it. I still prefer to use twl menu rather than other emulators for the layout and boxart so I will downgrade. Feel free to close or remove this issue as this is purposeful and not a bug.

Thank you for the response.

**Comment by spellboundtriangle** [comment]
Glad to have helped, why not just sort them into folders though?

**Comment by astigb** [comment]
Ahhh ok. I misread the change log you quoted. Yes I will sort them in letter folders then. Thanks again.
