### ISSUE TITLE
Some games didn't show up in the frontend

### ISSUE THREAD

**Issue by zeroultima6** [DS-Homebrew/TWiLightMenu#1868]
**Console Configuration:**  New 3DS XL - Luma 10.3
**TWiLight Menu++ Version:**  24.3.0
**TWiLight Menu++ Theme:**  Any

### Expected behaviour

 The roms/icons appear as they should on the frontend {NDS side or similar)

### Actual behaviour

 Some of the games didn't show up even they are in the roms folder, (ex. in my case, crafting mama didn't show in the frontend, I have over 200 games in the nds folder for reference)

### Steps to reproduce

1.
2.
3.

**Comment by zeroultima6** [comment]
![20220327_200305](https://user-images.githubusercontent.com/49905163/160308013-87a99a00-0338-4202-883c-ec1598a78447.jpg)
![20220327_200743](https://user-images.githubusercontent.com/49905163/160308027-753c7a32-5814-45b4-b272-6196136a16e4.jpg)

**Comment by Epicpkmn11** [comment]
Since a few versions ago there's a hard limit of 320 games per folder, if you need that many games split them up into multiple folders. (ex. A-M, N-Z)
