### ISSUE TITLE
Not working on 2DS, 32GB SD

### ISSUE THREAD

**Issue by lucasmr** [DS-Homebrew/TWiLightMenu#1880]
**Console Configuration: jailbroken 2DS and 32GB SD card**  
**TWiLight Menu++ Version: v24.3.1** 
**TWiLight Menu++ Theme: default** 

### Expected behaviour
TWiLight Menu++ should open

### Actual behaviour
TWiLight Menu++ fails to open with the following message:
"The TWiLight Menu++ files are missing. In order to start TWiLight Menu++, please add the missing files. If they already exist, and the above message still appears, then the SD Card is formatted in a way that TWiLight Menu++ cannot start. Please reformat your SD Card, or try another SD Card. Press B to return to menu."

### Steps to reproduce

1. On Linux, format the SD card with guide https://dsi.cfw.guide/sd-card-setup.html?tab=linux#section-i-formatting-your-sd-card-with-sd-formatter
2. Test the card with F3, all good
3. Install using guide https://wiki.ds-homebrew.com/twilightmenu/installing-3ds?tab=manual (installing via Universal-Updater gives the same result)
4. Try to run

**Comment by RocketRobz** [comment]
Are you able to use Windows instead of Linux?
If so, try using Windows instead.

**Comment by lucasmr** [comment]
Booting up a Windows XP VM and doing a default FAT32 format gave the same results.

However, using SD Card Formatter inside the VM did the trick.

Perhaps there must be a disclaimer in the install page? https://wiki.ds-homebrew.com/twilightmenu/installing-3ds

**Comment by lifehackerhansol** [comment]
I really don't want to tell people to make a VM just to format one card.
That being said, I am going to conclude that this was more or less an isolated issue, as this isn't something I've heard of happening before. mkdosfs has worked fine for pretty much everyone I've come across...

FWIW the FAQ/Troubleshooting page does tell you to format. Which, again, this is the first time I have seen a Linux user report this.

**Comment by lucasmr** [comment]
No problem, just a heads-up if someone else encounters the same issue. There is something very sensitive about the formatting and SD Card Formatter was the only way to solve it.
