### ISSUE TITLE
Volume icon not in the correct position.

### ISSUE THREAD

**Issue by Michal2k7** [DS-Homebrew/TWiLightMenu#1887]
**Console Configuration:**  DSi with Unlaunch and hiyaCFW
**TWiLight Menu++ Version:**  v24.4.0 release (latest as of 4/11/2022)
**TWiLight Menu++ Theme:**  Dark Nintendo DSi

### Expected behaviour
The volume icon should be in the upper left hand corner

### Actual behaviour
The volume icon is in the upper left hand corner, but lowered by about 16px

### Steps to reproduce

1. Update TWiLightMenu to 24.4.0 release 
2. Boot up the console
3. You should notice that the volume icon is off-centered 

![IMG_5174](https://user-images.githubusercontent.com/76980454/162786550-012faf16-90b7-4e77-b8cb-ad026b792834.jpg)

**Comment by RocketRobz** [comment]
You need to update the skin file by either downloading from https://skins.ds-homebrew.com/ or deleting it in `sd:/_nds/TWiLightMenu/dsimenu/themes/`
