### ISSUE TITLE
Option to disable Y and Select menu

### ISSUE THREAD

**Issue by nandolawson** [DS-Homebrew/TWiLightMenu#1890]
It would be great to disable both to prevent children from messing with any settings. I kind of imagine something like RetroArchs kiosk mode.
My suggestion would be to create an empty file on SD. As long as this file exists, there would be no way to get into any settings or into the DSi menu.
Everything else (nds-bootstrap menu or unlaunch menu) are relatively hard to enter by accident. This simple feature would make the DSi perfect for everyone. ^^

**Comment by spellboundtriangle** [comment]
> My suggestion would be to create an empty file on SD. As long as this file exists, there would be no way to get into any settings or into the DSi menu.

 It would be better to have it be a hidden setting, imo

**Comment by nandolawson** [comment]
True, as long as it is hidden enough.

**Comment by nandolawson** [comment]
A very good idea imo would be to just add an option to disable the Y and Select menus. Enabling them would be as easy as holding select while booting up TWLM++ to get directly to the settings menu and disable the protection.

**Comment by kcinnaJlol** [comment]
What is also possible is the equivalent to 'kiosk mode' found on other software, locking the settings until unlocked with a password.

**Comment by nandolawson** [comment]
Right, but that would be more effort to code. But that would ofc be the best option.
