### ISSUE TITLE
TWLM++ reboots when viewing per-game settings of some icon-less ROMs

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#1893]
**Console Configuration:** DSi with Unlaunch
**TWiLight Menu++ Version:** 610f31f8
**TWiLight Menu++ Theme:** DSi theme, any skin apparently

### Expected behaviour

The per-game settings would open on DS ROMs.

### Actual behaviour

Attempting to open the per-game menu on some icon-less homebrew ROMs will cause TWLM++ to reboot. However, it does not occur if you navigate folders during the session.

### Steps to reproduce

1. Find a homebrew ROM such as pikmin-nds.nds, without having navigated folders during the session
2. Press Y

### Other notes
Here's a video of this occuring: https://cdn.discordapp.com/attachments/489307733074640926/964513302015250462/VID_20220415_080750.mp4

**Comment by NightScript370** [comment]
Could you post a file that can trigger this?

**Comment by Dartz150** [comment]
Same here, use this to test, its NeoDS: https://www.mediafire.com/file/291en1exk51dvth/NeoDS.nds/file

**Comment by spellboundtriangle** [comment]
Fixed in 69b8a42
