### ISSUE TITLE
Application crashes with DSi Theme if certain skins are selected

### ISSUE THREAD

**Issue by Allinxter** [DS-Homebrew/TWiLightMenu#1902]
**Console Configuration:** Nintendo DSi using Unlaunch
**TWiLight Menu++ Version:** 24.6.0
**TWiLight Menu++ Theme:** DSi Theme + Several skins

### Expected behaviour
Application boots normally with any selected skins.

### Actual behaviour
The application crashes on boot if the Theme setting is set to Nintendo DSi and certain skins are selected.

### Steps to reproduce

1. Open TWiLight Menu++ Settings
2. Set Theme to Nintendo DSi and select any of the following skins: [any of the default skins, including the iQue one](https://skins.ds-homebrew.com/nintendo-dsi/category/default), [any of the Switch Basic skins](https://skins.ds-homebrew.com/nintendo-dsi/category/switch)
3. Exit TWiLight Menu++ Settings so the configuration is saved
4. Crash

**Additional Notes:** This issue started happening after updating to [24.3.0](https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v24.3.0). At first I thought it was a bad installation and/or SD card corruption. Four updates later I decided to test all the skins after users reported having the same issue on the Discord server, and seeing as the problem persists and only happens with select skins 100% of the time, I think we can cross out a bad installation.

**Comment by RocketRobz** [comment]
I think this commit caused the issue: bfa60dea

**Comment by Allinxter** [comment]
Issue keeps happening in nightly [e77e1b28](https://github.com/TWLBot/Builds/releases/tag/v20220424-020916).

Additionally, the 3DS theme presents the same issue with the following skins:
[Default Light](https://skins.ds-homebrew.com/nintendo-3ds/default-light)
[Default Dark](https://skins.ds-homebrew.com/nintendo-3ds/default-dark)
[Pokémon BW2 - Kyurem](https://skins.ds-homebrew.com/nintendo-3ds/pokmon-bw2---kyurem)
[Pokémon HGSS - Tower Duo](https://skins.ds-homebrew.com/nintendo-3ds/pokmon-hgss---tower-duo)

All the other skins for the 3DS theme work properly.

**Comment by Allinxter** [comment]
As proven by testing on the Discord server, having the `DSi/3DS Theme Music` set to `Off` makes the skins work correctly

**Comment by Allinxter** [comment]
> I think this commit caused the issue: [bfa60de](https://github.com/DS-Homebrew/TWiLightMenu/commit/bfa60deaa35e066fd8322447c5b67aa1bed90e05)

I don't know if we already crossed this out since it seems to be a problem with the music, but for the record, it happens on the nightly right before that commit was merged.
I'm currently rolling back to previous versions to see where the problem begins to appear.

**Comment by Allinxter** [comment]
I was rolling back and the problem seems to affect earlier versions too. Weird thing is, these earlier versions had no issues before this bug started presenting on newer versions, so it's like whatever it's happening, it's retroactively breaking older versions.
Deleting the cache file makes the bgm mute when `DSi/3DS Theme Music` is set to `Theme`, but also fixes the issue.
Additionally, making a clean install makes the issue dissapear altogether.

**Comment by spellboundtriangle** [comment]
Does this still occur? Might not be reproducing it correctly but, I tried the iQue skin with the theme music set to `Theme`, and it seems to work fine. Using a pretty old installation too.

**Comment by Allinxter** [comment]
I have the suspicion that this is caused by a combination of using old files and repeatedly switching bethween skins with different custom bgm, since apparently what causes the issue to appear is something wrong with the cache files and having it set to use custom skin bgm.

I have done no testing for this since a clean installation fixed the issue, so I can't be sure if this is something that can happen still, or if whatever that made it happen was fixed already.

**Comment by lifehackerhansol** [comment]
Closing as we have not heard any reports of this since.

Should anyone continue to encounter this issue, please feel free to reopen or leave a comment.
