### ISSUE TITLE
Hack ROM de gba

### ISSUE THREAD

**Issue by Jekevk** [DS-Homebrew/TWiLightMenu#1906]
Hola buenas, los hack rom de gba como Pokémon no los corre en la nintedo DSi se queda la pantalla en blanco, existe alguna solución para esto ? Los juegos normal de GBA los juega bien

**Comment by Dartz150** [comment]
@Jekevk DEpende mucho de la hackrom que estés intentando jugar. Usualmente, estas usan algo conocido como "hicode", lo cual significa que usan código ejecutable o scripts ubicados más allá o igual a limite de los 32MB que es el tamaño máximo en las roms de GBA. Desafortunadamente, muchos de estos romhacks no son soportados por GBARunner2 debido a limitaciones técnicas con el "hicode".

Existen otros casos donde el hackrom en cuestión está diseñado exclusivamente para usarse en emuladores, así que recomendamos probarlo usando hardware oficial para descartar que este sea el caso. En dado caso, esto debes ontificarlo al creador del hackrom en cuestión para que haga las correcciones necesarias.

**Comment by Jekevk** [comment]
el hack rom en cuestion es omega red y ocupa 32.768 kb, y hay otro que soporte los hack rom que no se GBARunner2?

**Comment by Dartz150** [comment]
> el Hackrom en cuestión es omega red y ocupa 32.768 kb, y hay otro que soporte los Hackrom que no se GBARunner2?

Antes de responder a esto, olvide preguntar en qué consola estás tratando de cargar la ROM, y en caso de serlo, que otros medios tienes disponibles para cargarlos? Esto último para poder recomendarte una alternativa en caso de que no se pueda arreglar la ROMHack en GBARunner2
