### ISSUE TITLE
SNES games are not automatically booted

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#1908]
**Console Configuration:** DSi w/ Unlaunch
**TWiLight Menu++ Version:** 45cd4529
**TWiLight Menu++ Theme:** DSi, WIP MKDS skin

### Expected behaviour

SNES games would launch from TWLM++using SNEmulDS 0.6c.

### Actual behaviour

SNEmulDS 0.6c is loaded, but the game is not started, and instead the SNEmulDS filemenu appears.

### Steps to reproduce

1. Start a SNES ROM

**Comment by NightScript370** [comment]
We would appreciate it if you were to try this again, due to the latest TWiLight Menu++ release adding both the old and new SNEmulDS side by side.

**Comment by spellboundtriangle** [comment]
It seems to be working fine now, with both versions.
