### ISSUE TITLE
Turn box art off by default

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#1909]
**Is your feature request related to a problem? Please describe.**
TWLM++ does not come with box art, it has to be manually downloaded by the user. Without any found box art, all titles will display a large `?` square.

**Describe the solution you'd like**
Turn box art off by default.

**Describe alternatives you've considered**
Add some sort of auto-detection, only showing the missing box art icon if there are instances of existing box art.

**Additional context**
None

**Comment by NightScript370** [comment]
I would rather a check be implemented at initial setup which would detect if there is a boxart folder and if image files exist there. If so, then toggle the option.
