### ISSUE TITLE
V24.5+V24.6 earthday crash

### ISSUE THREAD

**Issue by lxg1202** [DS-Homebrew/TWiLightMenu#1913]
NDSILL :V24.5+V24.6 earthday when start ,white screen in a long loading.

**Comment by Allinxter** [comment]
Try holding SELECT while booting TWiLight Menu++ and from there change the option `DSi/3DS Theme Music` to any option other than `Theme`, and then press B

**Comment by lxg1202** [comment]
> Try holding SELECT while booting TWiLight Menu++ and from there change the option `DSi/3DS Theme Music` to any option other than `Theme`, and then press B

thanks

**Comment by lxg1202** [comment]
> On my DSi, when I boot it up it gives me a white screen and nothing happens, I press the power button to reset and it takes me to the TWiLightMenu. Thought I'd share my method but this is a weird bug.

press button is right,thanks.
