### ISSUE TITLE
[DSI] white screen upon booting dsi

### ISSUE THREAD

**Issue by CommicKick69ing** [DS-Homebrew/TWiLightMenu#1914]
**Console Configuration:** Nintendo DSi with hiyaCFW + Unlaunch. I cant boot the DSI so I can tell what the firmware is
**TWiLight Menu++ Version:** v24.6.0
**TWiLight Menu++ Theme:** I don't know because I cannot launch it. 

### Expected behaviour

Boot into TWiLightMenu++menu.

### Actual behaviour

Booting the the DSI results in a static white screen

### Steps to reproduce

1. Download TWiLightMenu-3DS.7z from v24.6.0, and copy the contents of the zip file to the root of the SD card
2. Press the power button
3. Stare at a White screen

### What I have tried so far
Reformat SD card (64GB) to FAT32 and 32KB allocated unit size.
Delete the _nds folder and Twilight Menu++ titles and install via Twilight Menu++ Updater.

EDIT: For some reason I got TwightMenu to only work by launching it through unlaunch menu

**Comment by Allinxter** [comment]
Try holding SELECT while booting the console and from there change the option `DSi/3DS Theme Music` to any option other than `Theme`, and then press B

**Comment by CommicKick69ing** [comment]
> Try holding SELECT while booting the console and from there change the option `DSi/3DS Theme Music` to any option other than `Theme`, and then press B

When booting my DSI and holding the select button I only get the HiyaCFW v1.3.2 config menu. Since I boot into a white screen means I cant boot into TwlightMenu++ which also means I can change any music settings.

**Comment by Allinxter** [comment]
Then hold SELECT while opening TWiLight from HiyaCFW instead of when booting the console.
If you have it set up to boot TWiLight automatically, disable autobooting the last ran title from hiyaCFW settings.

**Comment by CommicKick69ing** [comment]
> Then hold SELECT while opening TWiLight from HiyaCFW instead of when booting the console. If you have it set up to boot TWiLight automatically, disable autobooting the last ran title from hiyaCFW settings.

Just tried your suggestion and no matter how long I hold the select button Upon booting up TwilightMenu++ from the dsi menu it is still a white screen

**Comment by Allinxter** [comment]
I see, in that case try accessing TWiLight Menu++ Settings directly from Unlaunch.
Hold A+B while turning on the console, find the applet that's labeled `Settings` (Not `System Settings`, just `Settings`) and boot it.

**Comment by CommicKick69ing** [comment]
> I see, in that case try accessing TWiLight Menu++ Settings directly from Unlaunch. Hold A+B while turning on the console, find the applet that's labeled `Settings` (Not `System Settings`, just `Settings`) and boot it.

For me **Settings** just boots me into DSI system settings **System Settings** doesn't exist on my unlaunch menu

**Comment by CommicKick69ing** [comment]
EDIT: For some reason I got TwightMenu to only work by launching it through unlaunch menu. I then restarted the console and now the menu works.
