### ISSUE TITLE
FlashCard: bottom screen flashing/weird graphics (unusable) v24.5.0 + v24.6.0 (works on v24.4.0)

### ISSUE THREAD

**Issue by McFly75** [DS-Homebrew/TWiLightMenu#1915]
When trying to install v24.5.0 or v24.6.0 on my Flash Cards for use on my DS Lite,
the bottom screen is flashing and showing bad graphics, so it is unusable.
(Tried both overwrite old files and fresh install)

But with v24.4.0 there is no problems and it works fine.
So I´m using this version for now.
But would like to be able to use the newer versions (because of fixes and features)

Tried several flash cards on both DS Lite & DSi and same problem.

**Comment by lifehackerhansol** [comment]
This seems to work fine on my DSTT on v24.6.0. It also worked on about 10 other carts as I was testing something unrelated but was still using TWiLight on the flashcart.

Does formatting SD help here?

**Comment by McFly75** [comment]
OK, I tried this:
Formatted a 8GB card with 32k cluster size using guiformat.exe
Then copied TwiLightMenu-Flashcard v24.6.0 + TTMenu.dat from Autoloader
And put in my DSTT card in my DS Lite.
I boots fine a first when setting language and Intro Videos, but when Main menu appear the button screen shows huge graphical distortion and I hear a load unpleasant sound (very distorted music)

**Comment by McFly75** [comment]
I tried to upload a picture and a short video.

https://user-images.githubusercontent.com/102325072/166121897-800736d5-d577-4d64-8c85-dc62a4a8c475.mp4

![20220430_223530](https://user-images.githubusercontent.com/102325072/166121901-2da5bdba-95aa-4906-a02c-fcf4060e73cb.jpg)

**Comment by McFly75** [comment]
I now copied the files from v24.4.0 (overwriting the v24.6.0 files)
And it works perfect. No graphical distortions or anything.
So I don´t think there is anything wrong with my flash card/SD Card or DS Lite, because everything is working fine with v24.4.0.

**Comment by McFly75** [comment]
Found out that the file that is causing the problem is:
_nds/TWiLightMenu/dsimenu.srldr
By replacing this file with the one from v24.4.0, everything seems fine in v24.6.0

**Comment by lifehackerhansol** [comment]
I still have no idea what is going on here because all my flashcarts are fine. Even the DSi theme works.

**Comment by McFly75** [comment]
Weird problem is guess.
I have tried 6 different flash cards (with different SD cards) and 2 different DS Lite and DSi,
and I get the same graphical problems when using v24.6.0 (or 24.5.0) on all of them.

**Comment by McFly75** [comment]
Don´t know what is going on.
Tried v24.6.0 today on several flash cards and now everything works fine.
I think the only thing I did different, was to unpack the archive before transferring the files.
(Instead of unpacking on fly/in memory)

So I think this issue is closed.

**Comment by McFly75** [comment]
Just to make sure that I am not crazy, I tried to copy the files from v24.6.0 (without unpacking first)
And got the same problem.

If anybody is willing to try to reproduce the problem, here are the steps:
Just must have Total Commander v10.00 for windows (ShareWare or full)
In one colum click on TWiLightMenu-Flashcard.7z
In second colum have your flash card sd
And just drag and drop the TwiLightMenu files (unpack on the fly/background)
Then just start TwiLightMenu.

**Comment by RocketRobz** [comment]
Are you using the autoboot files?

**Comment by McFly75** [comment]
On my DSTT & Gateway Blue I do.
Not on my Supercard DSOne SDHC or DSTwo (Because I like to use RTS)

But I have Tried with Autoboot files and without = same problem.

Maybe there is a problem with Total Commander & the 7 zip plugin?
But have never have had any problems before.

**Comment by RocketRobz** [comment]
You're the only who has reported this issue, so possibly.
Is the issue fixed by only using the standalone 7-zip application?

**Comment by McFly75** [comment]
OK, thanks for the feedback.

If I unpack the files first, there is no problem.
(So I just have to remember to unpack the files first then transfer them, when a new update comes out)

Thanks for the Great work...
I really appreciate it.

**Comment by RocketRobz** [comment]
Closing, since this is not a TWLMenu++ issue.
