### ISSUE TITLE
Cheat names don't scroll in R4 theme

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#1919]
**Console Configuration:** DSi
**TWiLight Menu++ Version:** 24.6.0 probably
**TWiLight Menu++ Theme:** R4 Original or GameBoy Color

### Expected behaviour

Cheat names would autoscroll when the name is too long, like in the DSi-based themes

### Actual behaviour

Long cheat names do not scroll.
![IMG_20220502_190153842](https://user-images.githubusercontent.com/79382000/166344914-896507f1-7b23-486c-a16e-36b4fac8580b.jpg)

### Steps to reproduce

1. Set theme to R4 Original or GameBoy Color
2. Go to a game and find a cheat with a longer name

### Notes

I know this is probably moreso just unimplemented than a bug, but I figure it's better classified as such.

**Comment by NightScript370** [comment]
Might be halting on #1642.
