### ISSUE TITLE
Autoboot (Gateway Blue) Freeze at start with "Auto-start Slot-1" On.

### ISSUE THREAD

**Issue by rocknard** [DS-Homebrew/TWiLightMenu#1920]
**Console Configuration:** 

Nintendo Old3ds system ver. 11.3.0-36E + Luma3DS v10.2, Gateway Flashcart (blue)

**TWiLight Menu++ Version:** v24.6.0
**TWiLight Menu++ Theme:** [Nintendo DSi] + Default

### Expected behaviour

After installed Autoboot Gateway Blue and activated "Auto-start Slot-1", you will reopen TWiLightMenu and would go to Flashcard directly.

**Note:** some games (only tested on two translated games), freeze at menu or when you start to play (not in menu). If i use "TWL Slot-1 Launcher v3.cia" (gbatemp) to launch the flashcart with the TwiLightmenu (with kernel gateway blue from TWiLight and nds bootstrap), the games works fine.

### Actual behaviour

After the setting up and open TWiLightMenu, you get a black screen with four dots "red, yellow, yellow and green"

### Steps to reproduce

1. Install TWiLightMenu 3DS on SD + TWiLightMenu Flashcart on Slot-1.
2. Copy "Autoboot\Gateway Blue\ _DSMENU.dat" on root slot-1 sd card and active the option "Auto-start Slot-1" on "Misc settings". Press Select to "Menu HOME 3DS" to exit.
3. Open TWiLightMenu and...

P.s.: sorry if this problem is not related or reported here (i don't know where exactly and asked on discord, but not response). Since i'm posting on windows xp, if you need a video o pics, i will need a little to do it.

**Comment by RocketRobz** [comment]
Does the flashcard work normally when you launch it in the DS Classic Menu?

**Comment by rocknard** [comment]
Interesting...:

With Kernel flashcard activated:

1º Changed to "DS Classic Menu on startup" > "Yes". Exit.
2º Open TWiLightMenu, select "slot1", search the rom to load it (Flascart kernel selected): Freeze white screen.
3º Again open TWiLightMenu, select "slot1", select "Last played games" (appear the icon from the previous freezed game) and working fine! If i don't play the rom from "Last played game", the game won't even run.

With NDS-bootstrap activated:

The rom will get a red screen after the menu shows using the same procedure (1, 2 and 3)

With Autoboot enabled after changed "DS Classic Menu on startup":

- The same problem: black screen at start with 4 dots (red, yellow, yellow, gree).

**Comment by RocketRobz** [comment]
With `Auto-start Slot-1` enabled, try turning on `Slot-1 microSD access` in the Misc settings page.
Also, you don't need to enable the `DS Classic Menu on startup` setting to access it. Instead, in the ROM menu, press SELECT to open the DS Classic Menu, if the SELECT menu isn't enabled.

**Comment by rocknard** [comment]
SCFG access in Slot-1 >> Off   
SD access in Slot-1 >> Off
Slot-1 microSD access >> On
Auto-start Slot-1 >> Yes

TWiLightMenu at start works fine.

-Loaded the rom properly (with Flascard kernel)
-Loaded the rom properly (with nds-bootstrap)

* With this option, i can't revert the "Auto-start Slot-1" because "SD access in Slot-1" is Off. So i'm stuck on Slot-1 without possibility of use the SD in the future for other purposes because the settings doesn't show them when you enter directly on Slot-1 (even if "SD access in Slot-1" is On, one time you start on Slot-1, you lost the possiblity to change that setting, it get lost ).
__________________________________________________________________
SCFG access in Slot-1 >> Off   
SD access in Slot-1 >> On
Slot-1 microSD access >> Off
Auto-start Slot-1 >> Yes

Black screen on TWiLightMenu at start (4 dots = red, yellow, yellow, green)
______________________________________________________________________________________
SCFG access in Slot-1 >> On
SD access in Slot-1 >> On
Slot-1 microSD access >> Off
Auto-start Slot-1 >> Yes

Black screen on TWiLightMenu at start (4 dots = red, yellow, yellow, green)
_________________________________________________________________________
SCFG access in Slot-1 >> On
SD access in Slot-1 >> On
Slot-1 microSD access >> On
Auto-start Slot-1 >> Yes

TWiLightMenu at start works fine

-Don't loaded the rom. White screen (with Flascard kernel)
-Loaded the rom but freeze with red screen at menu (with nds-bootstrap)

* I can move between SD and slot-1 (SELECT+UP/DOWN). More info Down.
_____________________________________________________________________________________________________
SCFG access in Slot-1 >> Off
SD access in Slot-1 >> On
Slot-1 microSD access >> On
Auto-start Slot-1 >> Yes

TWiLightMenu at start works fine

-Loaded the rom properly (with Flascard kernel)
-Loaded the rom properly (with nds-bootstrap)

* I can't move between SD and slot-1 (SELECT+UP/DOWN)... Access is granted both of them (?).

___________________________________________________________________________________________________________________
                                                                       ***ABOUT SETTINGS LOSTED**

Regarding of the losted ability to change some "settings" ("SCFG access in Slot-1 , SD access in Slot-1, Slot-1 microSD access, Auto-start Slot-1"):

It seems TWiLight doesn't show some settings (related to SD access Slot-1 and others not mentioned) after you enter to the Slot-1 flashcard ("SELECT + UP/DOWN" or press only SELECT and then select Slot-1). You only regain the possibility of change AUTOBOOT -or others related to SD- after you restart the APP and starts on "SD", not on Slot-1. With "AUTOBOOT" option you will never can see or change the options, because you will start on Slot-1 Flashcard directly (it forces me to use a backup of "settings.ini", set "AUTORUNSLOT1 = 0" or delete it.).

**Comment by RocketRobz** [comment]
So the verdict is: Your flashcard boots if `Slot-1 microSD access` is turned on.
It is also recommended to keep both `SCFG access in Slot-1` and `Auto-start Slot-1` enabled. If you don't see some settings, restart TWLMenu++ with Slot-1 empty.

**Comment by RocketRobz** [comment]
Should be fixed by f8897a6d
