### ISSUE TITLE
changing unlanuch settings in Twilight ++ does nothing

### ISSUE THREAD

**Issue by LivingFox** [DS-Homebrew/TWiLightMenu#1927]
**Console Configuration:** DSi (USA)
**TWiLight Menu++ Version:** 24.7.0 5/5
**TWiLight Menu++ Theme:** DSi  (USA)

### Actual behaviour

settings changed, ini file updated, no changes reflected in system.
example: if background set to "black.gif" or "desert.gif" it still shows default. switching patches to "off" still  leaves them "on"

### Steps to reproduce

1. Select --> Settings
2. R/L to Unlaunch Settings
3. Changing Patches &/or Background has no effect

**Comment by lifehackerhansol** [comment]
Did you reinstall Unlaunch after saving those settings?

**Comment by LivingFox** [comment]
> Did you reinstall Unlaunch after saving those settings?

yes, i tested reinstalling unlaunch using Unlaunch Dsi Installer , but no setting changes are applied

**Comment by spellboundtriangle** [comment]
Had you launched the Unlaunch installer from TWLM++?

**Comment by LivingFox** [comment]
> Had you launched the Unlaunch installer from TWLM++?

this must be the step i missed, i was reinstalling from unlaunch but doing so from TWLM++ did the trick. thanks
