### ISSUE TITLE
DSi/3DS Theme Music `Theme` setting causes crash if no custom music is found

### ISSUE THREAD

**Issue by lxg1202** [DS-Homebrew/TWiLightMenu#1930]
by hold SELECT during the splash screen or  change the DSi/3DS Theme Music setting to something other than Theme.  V24.7 also booting screen is  white.so instead of V24.4,all is normal.

**Comment by NightScript370** [comment]
Does this happen in the latest release?

**Comment by tacosplease** [comment]
> Does this happen in the latest release?

Yes, I’m having the same bug with the current release.

**Comment by lxg1202** [comment]
> Does this happen in the latest release?

no, release after V25  ,everything is OK!

**Comment by lxg1202** [comment]
> > Does this happen in the latest release?
> 
> Yes, I’m having the same bug with the current release.

now ,V25+ is OK!
