### ISSUE TITLE
DS Classic Menu bug- screen duplication

### ISSUE THREAD

**Issue by p0pcake** [DS-Homebrew/TWiLightMenu#1935]
**Is your feature request related to a problem? Please describe.**

The very bottom part of DS Classic Menu duplicates. Noticed the problem on the Flashcard edition. The problem seems to appear only on the XL models (for example, DS Lite shows the menu correctly, 2DS XL doesn't.) It can be temporarily removed by closing and re-opening the console's lid. It appears again after reopening the menu. 

The problem was already described here:
https://github.com/DS-Homebrew/TWiLightMenu/issues/991

**Describe the solution you'd like**

No duplication would be lovely to see. 

**Additional context**
Attaching a screenshot showing the issue. 
![IMG_4738](https://user-images.githubusercontent.com/62682518/170231887-7d482f22-d120-4773-bb2e-17fa2bb332ac.jpeg)

**Comment by Epicpkmn11** [comment]
This is a bug in TWL_FIRM itself and not something we can fix in TWiLight, it can even happen when playing retail DS carts on an unmodded 3DS, just need to close and reopen the lid when it happens.

I think the GPU scaling patch from [TWPatch](https://db.universal-team.net/3ds/twpatch) does fix this, though I think it's blurrier than even the default filter so it may not be what you want for scaling.
