### ISSUE TITLE
Add subfolders for boxart

### ISSUE THREAD

**Issue by kourm** [DS-Homebrew/TWiLightMenu#194]
A box art collection (for example the one by XrayXout) results in a lot (1801) of files in one single single directory. This results in ftp clients taking ages (more than 1 m) to display the boxart folder. For me, it seems like the sdmc_gettime function (and the backing sdmc service) needs longer the more previous entries are inside a single directory (maybe iterating through all previous entries?). 
To remedy this, I propose splitting the path for the TID in a folder for the first two characters and a file for the rest (boxart/AC/4E.bmp), like git does it. In my case, this would lead to 197 directories, which is much more manageable. 
If you're interested, I could try implementing it.

**Comment by NightYoshi370** [comment]
I mean, @baregl, I don't exactly see the point of making boxart subfolders other than folder render lag.
Wouldn't putting them in sub folders actually make it even less managable?

Although, if you want to try to implement it, I don't see any reason why you won't want to
