### ISSUE TITLE
Not enter sleep mode bug 

### ISSUE THREAD

**Issue by Dogreened** [DS-Homebrew/TWiLightMenu#1941]
**Console Configuration:**  
**TWiLight Menu++ Version:24.8.0
**TWiLight Menu++ Theme:** 

### Expected behaviour

Close the lid then

### Actual behaviour

 not entering sleep mode as well

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Fixed in the next version.
