### ISSUE TITLE
Launching an nds rom reboots twilightmenu

### ISSUE THREAD

**Issue by ryuuyu** [DS-Homebrew/TWiLightMenu#1949]
Hey, all of a sudden whenever I launch any nds game in twilightmenu both screens turn black and then I get sent back to the twiligtmenu rom selection screen.
I'm using a New 3DS with luma v11.0, sys 11.15.0-47e, twilightmenu v24.9.1

**Comment by RocketRobz** [comment]
Try turning off `Update recently played list` in TWLMenu++ Settings.
If the issue persists, then delete `sd:/_nds/TWiLightMenu/extras/cheat.dat`.

**Comment by ryuuyu** [comment]
Turning off update recently played list didn't fix it, and deleting usrcheat.dat also didn't work

**Comment by RocketRobz** [comment]
Try re-installing then.
https://wiki.ds-homebrew.com/twilightmenu/uninstalling-3ds
https://wiki.ds-homebrew.com/twilightmenu/installing-3ds

**Comment by ryuuyu** [comment]
Reinstalling fixed it, thank you so much!
