### ISSUE TITLE
New Nintendo 2DS XL (Luma3DS v11.0) White Screen on launch 

### ISSUE THREAD

**Issue by mahirahman** [DS-Homebrew/TWiLightMenu#1953]
**Console Configuration:** New Nintendo 2DS XL with Luma3DS v11.0
**TWiLight Menu++ Version:** TWiLight Menu++ v24.10.1
**TWiLight Menu++ Theme:**

### Expected behaviour

Launch TWiLight Menu++

### Actual behaviour

It opens to both screens being stuck on white.
I have tried reinstalling manually and via universal updater.
Putting device to sleep and then waking it back up.
And clicking the START button after 60 seconds.
Reformatted SD card, reinstalled gm9 and Luma. Then download TwilightMenu from universal-db. Still white screen.
I've also tried TWLFix-CFW.3dsx

None of these seem to fix the issue.

### Steps to reproduce

1. https://wiki.ds-homebrew.com/twilightmenu/updating-3ds.html?tab=manual (Followed both methods exactly)
2. Downloaded onto a 64GB SD card
3. Open TwilightMenu ++ App
4. Stuck on white screen

**Comment by mahirahman** [comment]
I installed nds-bootstrap with YANBF and the same issue prevails.
So I'm assuming this is a problem with nds-bootstrap

**Comment by RocketRobz** [comment]
It's actually a problem with libfat, which both TWLMenu++ and nds-bootstrap use.
Theoretically, switching to libslim or smth else should fix the issue, but that would take a while.

Try reformatting the SD card using this guide: https://dsi.cfw.guide/sd-card-setup.html
If the issue persists, then try another SD card (preferably 32GB or below).

**Comment by Vaporeon** [comment]
I had the same issue, but in my case it loaded to the menu 1/8 times
I found turning off saving history and switching to the r4 theme dodged the issue and made it 100% reliable.

**Comment by mahirahman** [comment]
Thanks, I'll try both methods and see if they work this week.

**Comment by NightScript370** [comment]
This doesn't seem like a bug (aka reproducable by everyone) but more like a support problem.
Let's take this to the Discord Server

Closing

**Comment by mahirahman** [comment]
> It's actually a problem with libfat, which both TWLMenu++ and nds-bootstrap use. Theoretically, switching to libslim or smth else should fix the issue, but that would take a while.
> 
> Try reformatting the SD card using this guide: https://dsi.cfw.guide/sd-card-setup.html If the issue persists, then try another SD card (preferably 32GB or below).

Not working. I'll try with another SD card. Is it possible this may be an issue with the 3DS system itself?
