### ISSUE TITLE
please increase OVERLAY function

### ISSUE THREAD

**Issue by mhc19881010** [DS-Homebrew/TWiLightMenu#1955]
most NDS games looks blurry, 
( I tried TWPatch, but not satisfied )
I can make it better by using my own OVERLAY, 
( maybe just for me...) 
so I hope this TITLE. 
Thank you!

**Comment by RocketRobz** [comment]
This is something that's out of our scope to implement, so please request this feature in the [TWPatch thread](https://gbatemp.net/threads/twpatcher-ds-i-mode-screen-filters-and-patches.542694/).

**Comment by mhc19881010** [comment]
OK, thank you!
