### ISSUE TITLE
Seriously, make an auto updater

### ISSUE THREAD

**Issue by spudpiggy** [DS-Homebrew/TWiLightMenu#1988]
**Is your feature request related to a problem? Please describe.**
I feel that TwiLightMenu updates _way_ too often. I'm almost always on an old version because it's near impossible to remember that I need to check so often.

**Describe the solution you'd like**
This problem could be solved by adding an automatic update function to the app. Before the app is launched, it will check if it needs to update and then attempt to update if it needs to. This can be configured to only check once every x days too if you so desire. If no WiFi connection(s) are usable, the check should be skipped.

**Describe alternatives you've considered**
On 3DS we could go back to the launcher, but that sounds naff. Just the version check every time you boot TwiLightMenu would be extremely helpful, if the unzipping process is too slow on the weak CPU you could try this route.

**Additional context**

**Comment by NightScript370** [comment]
Seriously, read the other issues that requested this where we already said we wouldnt be doing this due to the bloat and the technical aspects

Use Universal Updater for DSi instead, whenever that comes out.
