### ISSUE TITLE
More GBA Launch Options

### ISSUE THREAD

**Issue by Knightsurfer** [DS-Homebrew/TWiLightMenu#1990]
For the DS version it would be nice to have a "launch slot 2" option to boot gba games without an emulator, 

also what would be nice to be able to read the file system of omega carts come to think of it, the firmware is open source so it's something to consider.

As for the 3DS version (though mind you I dunno if you have gotten ontop of this already, been a while since I used the 3ds version due to my battery being on the verge of exploding, so I need to wait for another battery to come in.)

but anyway, having the option to load into gba.firm would be nice, also the option to use mgba, as mgba from what I can tell has full compatibility with games such as WarioWare Twisted,

Also if it is possible it would be nice to have some gameshark options implemented though I imagine that's more up to the emulator programmers, as as far as I'm aware there is no gba cheats for 3ds.

**Comment by NightScript370** [comment]
> For the DS version it would be nice to have a "launch slot 2" option to boot gba games without an emulator,

Hey there, this is already possible (at least, in the DS Classic Menu)

> As for the 3DS version, having the option to load into gba.firm would be nice, also the option to use mgba, as mgba from what I can tell has full compatibility with games such as WarioWare Twisted,

This would go against the scope of TWiLight; an all-in-one environment for all of your TWL_FIRM needs

> Also if it is possible it would be nice to have some gameshark options implemented though I imagine that's more up to the emulator programmers, as as far as I'm aware there is no gba cheats for 3ds.

Not a TWiLight area, as you acknowledged

---

Best you make a new issue with your request for the omega or change up OP heavily.

**Comment by Knightsurfer** [comment]
may I ask you something? Do you have any idea about the capacity of the R4 - Revolution for DS? I got it from a friend years ago and I heard it had a hard limit of like 2GB,  is that true? and if so do you know if there are any flash cards that expand that capacity? just referring to the normal DS and DSLite here.

**Comment by NightScript370** [comment]
The R4 has a 2GB limit, but virtually every other card that came after it has support for higher capacity cards. If thats your concern, though, I recommend joining the discord server because its offtopic from the issue

**Comment by NightScript370** [comment]
https://github.com/DS-Homebrew/TWiLightMenu/issues/1716

This covers the only valid suggestion here. This issue is moot.
Closing...
