### ISSUE TITLE
automatically toogle power card-slot on and off

### ISSUE THREAD

**Issue by desolutionX** [DS-Homebrew/TWiLightMenu#1993]
**Is your feature request related to a problem? Please describe.**
If the power is toogled off from the flashcard by Rosalina menu. Then you use TWLmenu++ installed on 3DS with activated flashcard slot-1 access. If you start TWLmenu++, it will toogle power on from the flashcard automatically. But if you close TWLmenu++ and return to the 3DS menu the card is still powered on.

**Describe the solution you'd like**
If TWLmenu++ will be closed and returned to 3DS menu, the flashcard should be automatically toggeled power off.

**Describe alternatives you've considered**
An Alternativ would be a homebrew app to toogles the power on or off.

**Additional context**
In Rosalina menu is under System configuration the option to toogle power from the card-slot on and off.

**Comment by NightScript370** [comment]
This is not an aspect that's up to us to deal with, as even if we were to disable the card on our end, Luma will turn it back on when it gets launched, due to https://github.com/LumaTeam/Luma3DS/issues/1762 not being implemented.

We recommend showing support for that issue by adding a 👍 to its reaction menu to get your problem solved.

**Comment by desolutionX** [comment]
This is an idea of an enhancement.
At the moment its not implemented in luma by boot. But iam looking foward and it lies for sure in their interrest and their having an eye on. Because it will not be their interrest implementing a function where the user have to disable/ activate the flashcard each time manually again.

And i dont think you will sit on a missing function, because none told. Till now you did a good job with TWLmenu. With regards.
