### ISSUE TITLE
Allow larger date/time icon sizes

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#1995]
**Is your feature request related to a problem? Please describe.**
The font I want to use for date/time in my TWLM++ skin is larger than the default 8x8 characters.

**Describe the solution you'd like**
The ability to have larger characters. I'm not sure how this would be implemented exactly, maybe accepting something like `date_time_font_12x12.png` and such as an override may work well.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Epicpkmn11** [comment]
The easiest way is probably to just rewrite the top screen to use NFTR, I'll see about doing that in a little bit, might not be too bad really.
