### ISSUE TITLE
Launching Slot-2 from other themes

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#2003]
**Is your feature request related to a problem? Please describe.**
At the moment, Slot-2 can only be launched from the DS Classic Menu (which is not accessible from the 3DS/R4 themes), as far as I know anyways.

**Describe the solution you'd like**
Put a Slot-2 launcher in place of the Slot-1 launcher. The space is already empty on a Phat/Lite since it's being taken by the Slot-1 flashcard, so nothing needs to be moved around.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by RocketRobz** [comment]
Slot-2 has not been launchable from the 3DS theme due to a long-standing bug, which will be fixed in the next version.
No idea about the R4 theme though.
