### ISSUE TITLE
Custom ".png" icon for the "Back" folder (button).

### ISSUE THREAD

**Issue by Calvorejas** [DS-Homebrew/TWiLightMenu#2023]
Hi.

**Context:** I made some custom icons to improve the navigation system as my collection of ROMs is very large... Around 8000 ROMs total... I divided each collection with folders that go from A to Z (including # for ROMs whose names begin with numbers).

**Problem:** Everything looks great except for the "Back" Folder (which really works as a button to go to the previous folder). All Folders have each custom icon except for the Back folder. I'll attach a picture of how it looks (Instead of "Back", It says "Atrás" as my Twilight Menu is in Spanish) and the icon that I would like to use (.png).

**Possible solution:** It would be great if I could use that icon to personalize that button or folder the same I used the other icons.
You paste it in _"(SD Card letter):\_nds\TWiLightMenu\icons"_ and it appears on your DS's screen.

**Doubt:** It can probably be done already and I just don't know how to do it... If that's the case, I would love to know which name I should use in order for Twilight Menu to recognize the icon and/or where to locate the file (in case it should be in a different folder instead of the "icons" folder.

In any case, all help will be helpful.

Thank you!

Pictures and the icon pack I made:
![How it looks](https://user-images.githubusercontent.com/74108190/187183044-8ace33fb-8cdf-48a3-829c-c16c37a25e49.jpg)
![The Back icon I want to use](https://user-images.githubusercontent.com/74108190/187183168-e0cfb31d-1bca-42a4-b969-826f0b41185b.png)
[My custom icon pack.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/9443853/My.custom.icon.pack.zip)

**Comment by spellboundtriangle** [comment]
You can use `...png` for the back button.

**Comment by Calvorejas** [comment]
> You can use `...png` for the back button.

Hi!

That works flawlessly. Thank you very much for your help! Now the menus look perfect.
