### ISSUE TITLE
Add text strings (to translate)

### ISSUE THREAD

**Issue by Hassan2402** [DS-Homebrew/TWiLightMenu#2027]
**Is your feature request related to a problem? Please describe.**
There're certain text strings that aren't translated in TM++ and are also not available in the crowdin project (or at least I haven't found them). Images in **Additional context**

**Describe the solution you'd like**
Add these text strings for your translation (I can help with the Spanish language)

**Describe alternatives you've considered**
N/C

**Additional context**
![image](https://user-images.githubusercontent.com/77475401/188300016-9d953183-a502-4119-ae13-1368d3d8c791.png)

![image](https://user-images.githubusercontent.com/77475401/188300027-aa1a27fa-4c79-43d5-be75-7810c7d4aac5.png)

![image](https://user-images.githubusercontent.com/77475401/188300075-9e5c48ae-05c3-495c-8272-55e966697062.png)

**Comment by lifehackerhansol** [comment]
nds-bootstrap loading screen is a different Crowdin project. (also, that exact string is not translatable. I don't think it's even text...)

The others just needed to be synced to Crowdin by @Epicpkmn11. The one in the image is a relatively new string so it likely just was left out by accident.

**Comment by Epicpkmn11** [comment]
Pushed to Crowdin, sorry about the delay
