### ISSUE TITLE
Add Unlaunch as a homebrew launcher option

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#2028]
**Is your feature request related to a problem? Please describe.**
Some homebrew applications (mainly DSGM/PAlib games and such) do not work with nds-bootstrap or direct boot, or do boot but are bugged when launched using one or both of these options (like World of Sand DS, [nds-bootstrap/#1372](https://github.com/DS-Homebrew/nds-bootstrap/issues/1372)) but do work when launched from Unlaunch.

**Describe the solution you'd like**
Add a per-game option to launch a specific homebrew with Unlaunch, like the option that DSiWare has for this.

**Describe alternatives you've considered**
Perhaps whatever magic Unlaunch is performing to launch these could be applied to Direct Boot launching or nds-bootstrap, but given that Unlaunch is not open source, that probably won't happen.

**Additional context**
N/A

**Comment by TrueNTG** [comment]
This needs.to be a Future feature

**Comment by TrueNTG** [comment]
This definitely needs to be part of the next big update
