### ISSUE TITLE
Clock is Messed Up

### ISSUE THREAD

**Issue by godreborn** [DS-Homebrew/TWiLightMenu#2034]
I noticed that the clock in the upper right hand corner of the top screen looks like gibberish now.  when you back out to the menu where you can go into settings, it looks fine on the lower screen.  I don't recall this issue from the previous version or maybe it was present and I just didn't notice?

**Comment by spellboundtriangle** [comment]
Try making sure the skin is set to `Default` or re-downloading it from [the skins site](https://skins.ds-homebrew.com)

Skins stopped being bundled + the default one is no longer loaded externally, so it might not have been updated.

**Comment by godreborn** [comment]
thank you.  that worked.
