### ISSUE TITLE
latest update messing up the app

### ISSUE THREAD

**Issue by shadowspike74** [DS-Homebrew/TWiLightMenu#2038]
when I updated the app this month though universal updater the application has been behaving weirdly. such as broken date display and no widescreen option in sight.

I'm running
sys 11.15.0-47E since last year but have yet to update my 2ds xl

**Comment by spellboundtriangle** [comment]
Dunno about widescreen, but the date display should be fixed by setting the skin to `Default`, or re-downloading it from [the skins site](https://skins.ds-homebrew.com/).

**Comment by shadowspike74** [comment]
that fixed it since I was using the default 3ds theme. but the ratio aspect option is still not anywhere on my screen.

I've checked pre game configurations and main settings and there is no sign of it.

**Comment by RocketRobz** [comment]
You need to update Luma as well, via Universal-Updater.
