### ISSUE TITLE
after running nes game, and spamming power button after 1 secound, it crashes, and can't turn off console and up screen is white and down is black. (Sometimes screen flashes black lines on upper screen)

### ISSUE THREAD

**Issue by o4lvvi** [DS-Homebrew/TWiLightMenu#2041]
Skin Used: 3ds 

### Steps to reproduce

1.have on sd 1 nes game. 
2.run it
3.when screen is black spam power button (i did it like 4 times)

**Comment by RocketRobz** [comment]
If pressing POWER does not properly exit the emulator to TWLMenu++, then this is an issue with nesDS, not TWLMenu++.
Also, you need to hold POWER, if pressing POWER doesn't power off the console.
