### ISSUE TITLE
White screen with the colors red green yellow and something else

### ISSUE THREAD

**Issue by maxwell1532** [DS-Homebrew/TWiLightMenu#2042]
So after i posted the black screen slot 1 problem i fixed it but now its a different screen i tried tinkering with the settings, nothing worked so how am i going to fix it and i know im not the only one with this problem ive seen people having the same problem to. So if you see this RocketRobz, message me anytime.

**Comment by RocketRobz** [comment]
Please join our Discord server like I told you in the previous issue.

**Comment by maxwell1532** [comment]
yes its maximus1236#9603
