### ISSUE TITLE
About key operation

### ISSUE THREAD

**Issue by KururinX** [DS-Homebrew/TWiLightMenu#2043]
In TWL after v20220911-213518 (a5af1ca), some button actions are not accepted immediately after boot.
 A, Start...ROM does not start
Y...Startup option screen? is not displayed 
X...Does not display a confirmation screen for deletion or display/hide
Select... select menu and classic menu can be started, but the ROM cannot be started 

cursor? If I move the , all the buttons work normally...
I mainly checked with the DSi theme, but it seems that the same thing happens with other themes, so it doesn't seem to be a theme-specific problem.

**Comment by RocketRobz** [comment]
Do you know which commit is causing this issue?
It makes no sense for commit 09e3edaa3 to be the cause.

**Comment by NightScript370** [comment]
Can confirm my commit was made by opening VSCode, replace all "if(" by "if (" and then push. Nothing within the codebase should have changed.

**Comment by NightScript370** [comment]
![image](https://user-images.githubusercontent.com/18664762/191302712-a0bed75f-d840-456b-a67e-9f15f172a790.png)
Yep, GitHub shows the exact same thing.
