### ISSUE TITLE
Setting for root ROM Directory.

### ISSUE THREAD

**Issue by zaide-chris** [DS-Homebrew/TWiLightMenu#205]
Rather then a hide all folders setting could we get a set Root Directory setting?
So amusing the SD cad has a layout of

* sd:\
    * 3ds\
        * ...
    * gm9\
        * ...
    * luma\
        * ...
    * Nintendo 3DS\
        * ...
    * roms\
        * Mario\
            * < Mario Roms >
        * Other\
            * < Other Roms >
        * Pokemon\
            * < Pokemon Roms >
        * Zelda\
            * < Zelda Roms >
    * System Volume Information\
        * ...

So if the root is set to sd:\roms\ you could see the "Mario", "Other", "Pokemon", and "Zelda" folders, but no "Back".  Only while in one of these folders under root does the back choice show up.

**Comment by NightYoshi370** [comment]
I don't really see the use of this to be honest.

**Comment by quentinguyot2** [comment]
This could be very useful! hope it will be added
