### ISSUE TITLE
Move "Game Loader" setting to Games and Apps settings

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#2053]
**Is your feature request related to a problem? Please describe.**
At the moment, the "Use nds-bootstrap" setting (for switching between using nds-bootstrap and a flashcard kernel for booting retail DS games) is under the nds-bootstrap settings page. This doesn't make much sense in my opinion, as one of the set options makes nds-bootstrap not used at all, and has nothing to do with the settings of nds-bootstrap itself.

**Describe the solution you'd like**
Move this setting to the Games and Apps settings, where other options between different emulators and loading methods are listed, including DSiWare booter (Unlaunch and nds-bootstrap)

**Describe alternatives you've considered**
If there is some good reason for this setting to stay in the nds-bootstrap settings, I would figure the DSiWare booter setting should be moved to nds-bootstrap settings instead.

**Additional context**
Changing the name of this setting would also be appropriate, but I'm not sure what a good name would be.

**Comment by NightScript370** [comment]
Maybe the name instead could reflect the fact that it would launch either a kernel of nds-bootstrap.
Perhaps..."DS Retail Title Loader" -> "nds-bootstrap" & "Kernel ([name of kernel for that specific loader, but not that we'll start splitting up this option into 20.])". I think this is the best combo of both Evie's and SNBeast's suggestion.
