### ISSUE TITLE
Crash Golden Sun Dark Dawn

### ISSUE THREAD

**Issue by DavidSomber** [DS-Homebrew/TWiLightMenu#2054]
Nose si pueda arreglar el TwilightMenú para poder jugar este gran juego que se llama Golden Sun Dark Dawn llevo mucho tiempo queriendolo jugar:(

**Comment by NightScript370** [comment]
This already has an issue in the nds-bootstrap repository. Also, our support tickets have an English-only policy. Sorry
Closing...
