### ISSUE TITLE
HackRoom'

### ISSUE THREAD

**Issue by TUMTUMTARAM** [DS-Homebrew/TWiLightMenu#2067]
When i tried to open a hackroom the screem freeze on a white page.

**Comment by RocketRobz** [comment]
Depends on which ROM hack it is.

**Comment by NightScript370** [comment]
Unfortunately, with the little information you provided (even after a request to respond), we are unable to assist. Please join our Discord Server for a live-chat room where we could help you load your ROM hack.
Closed...
