### ISSUE TITLE
Allow using the user profile color on more skin elements

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#2083]
**Is your feature request related to a problem? Please describe.**
At the moment, only some skin elements from the DSi theme can make use of the set system color.

**Describe the solution you'd like**
Allow any (or as many as feasible) skin elements to use the user profile color. This would allow for more personalization and distinct theming with the same skin.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Juicyousiguy** [comment]
Not only that, I also think that this shouldn't be limited to the DSi theme. Let it be usable for 3DS themes and such!

**Comment by NightScript370** [comment]
Fixed by #2137
