### ISSUE TITLE
Make top screen photo displaying a setting

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#2084]
**Is your feature request related to a problem? Please describe.**
At the moment, photo rendering in skins is an option set by the skin creator. If they want to have a version with a photo and one without it, they have to upload another version of the same skin.

**Describe the solution you'd like**
Create an option to turn the photo on or off in TWLM++ settings.

Going forward, this would mean skin creators could supply two copies of the top screen background, one for photo displaying and one without. This wouldn't cause issues with existing skins, as it would simply disable or ignore the setting if it can't find one of the backgrounds, or if something in the theme.ini indicates as such.

I'm not completely sure what would be the cleanest way to approach implementing this would be, though.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by DieGo367** [comment]
It would make sense to have something like `top` and `top_photo`, where the latter falls back to the first when missing. The only tricky decision is what to do about `renderPhoto` in theme.ini. Either ignore it, which is a breaking change for older skins, or leave it as is, and older skins will have to be updated if they want to allow photos.

**Comment by spellboundtriangle** [comment]
Completed in #2340
