### ISSUE TITLE
Allow customization of palette when using the user profile color in custom skins

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#2089]
**Is your feature request related to a problem? Please describe.**
It can be difficult to create custom skins while using the user profile color option, as it forces a hardcoded palette and ignores that of the image.

**Describe the solution you'd like**
Allow using the palette included in the image.

I'm not completely sure how this would work, as flexibility with different color choices and amount of user color shades are important, instead of having to always have the 8(?) shades reserved for the user color. It could perhaps be that all colors to the left of #FF00FF in the colormap would be considered user color shades (with #FF00FF being hardcoded as *the* transparency color with this setting being a downside, I guess), if possible.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by NightScript370** [comment]
#2137 should have made this possible. What do you think of the implementation there?

**Comment by spellboundtriangle** [comment]
> #2137 should have made this possible. What do you think of the implementation there?

If I'm understanding correctly, the specified part of #2137 essentially allows you to create your own user color color palette that's derived from the console settings.

What this issue was created for, was the fact that if you try to have the user color palette enabled, your _entire_ palette in the image is thrown out and overridden by TWiLight Menu++'s hardcoded one, including parts of the texture that _aren't_ supposed to be colorized per the user palette. 
For example:

Here, I have this setup. It's mostly the same as the original white version, but with the white changed to lime green.
![image](https://user-images.githubusercontent.com/79382000/211002684-756a023d-923d-444d-b183-bccee615f84e.png)
When viewed in TWLM++, the lime green has been replaced by white.
![image](https://user-images.githubusercontent.com/79382000/211001427-971c10d0-529b-43c8-9c15-f5e0ca1a7121.png)
Funnily enough, I had made this issue for my "Darker Default" skin, but I hadn't thought to just use the last color in the palette, which is black for whatever reason.

#2137 closer resembles #2133, albeit with color sets chosen by the skin creator rather than an end-user chosen color.

**Comment by DieGo367** [comment]
For this specific example, you would have to set that lime green color in all 16 palettes of a `dialog.bin` palette file, which would then keep it lime green in all user colors. (As a side note I should probably create some example palette files based on the hardcoded defaults just so that there is a base to make simple edits from)

My PR is not exactly the solution you proposed initially, but it's a lot more flexible in terms of controlling which colors can change and which shouldn't.

**Comment by spellboundtriangle** [comment]
Ah, so the .bin contains the entire palette each time? That makes sense (I hadn't checked the math and assumed it only stored the user color palettes themselves)
