### ISSUE TITLE
Disable automatic AP patching

### ISSUE THREAD

**Issue by MochiBluse** [DS-Homebrew/TWiLightMenu#2092]
**Is your feature request related to a problem? Please describe.**
Indeed. I don't know if the issue is really AP patching, but some games (more specifically, a Pokémon HG hackrom) stay on a white screen when launching them. Correct me if I'm wrong, but I believe this has something to do with the patch being automatically applied by TM++ on top of the hackrom due to it not being detected correctly.

**Describe the solution you'd like**
A way of choosing whether you'd like to apply an AP patch for each game, or at the very least, a way to disable this feature. I currently don't know if it already exists, but if it does, I haven't been able to find it.

**Comment by Epicpkmn11** [comment]
You can simply delete `sd:/_nds/TWiLightMenu/extras/apfix.pck` to remove to AP patches, thus disabling them.

**Comment by MochiBluse** [comment]
I guess this did remove the AP patch, but I'm still unable to launch the game. I'll try to look further into it on my own. I still believe that a feature for this to be turned off individually would be useful.

Thank you!

**Comment by Kaisaan** [comment]
Launching a ROM hack from TWiLight Menu++ shouldn't apply any AP patches in this case (it checks for the gameID along with the header CRC, which would be different for ROM hacks). As Evie mentioned, deleting (or renaming) the apfix.pck disables automatic AP patching. I'll close this issue as I suggest that you create an issue over in [nds-bootstrap's page](https://github.com/DS-Homebrew/nds-bootstrap/issues/new/choose) for the games that don't work.
