### ISSUE TITLE
Add support for .msx rom files to TWiLightMenu

### ISSUE THREAD

**Issue by Harry7228** [DS-Homebrew/TWiLightMenu#2096]
**Is your feature request related to a problem? Please describe.**
I want to be able to open .msx rom files from TWiLightMenu. They are supported by the included ColecoDS emulator.

**Describe the solution you'd like**
When I choose a .msx rom file, then start the ColecoDS emulator.

**Comment by RocketRobz** [comment]
Implemented by 83259a3f7
