### ISSUE TITLE
SNEmulDS don't work

### ISSUE THREAD

**Issue by Spyro24** [DS-Homebrew/TWiLightMenu#2101]
The emulator SNEmulDS does not display graphics correctly and does not display the image as it is on the original console and the game experience suffers because the controls do not react correctly and some games do not want to load like Super Mario World 2: Yoshis Island

I use an original DSI + a NONAME SD card

**Comment by RocketRobz** [comment]
Even though TWLMenu++ bundles SNEmulDS, it is not an issue within TWLMenu++ itself.
Unfortunately, it is expected for SNEmulDS to experience such issues, as well as some games not supported due to them using unemulated chips.
