### ISSUE TITLE
The 'no' option on nds bootstrap boot loops the game all the time

### ISSUE THREAD

**Issue by EpicDoodleboy2** [DS-Homebrew/TWiLightMenu#2102]
DS Lite NO EXPANSION PAK -- non modified
Flashcard (R4 2021)
TWL ver. 0.66.0
Theme. White DSI menu

When going into the game settings menu and then switching to ''no' on nds bootstrap and boot up a game it'll boot up but when I restart It autoboots the game that I was playing before

I was expecting when I switch off the system It goes back into Twilight Menu but instead it autoboots the game and to get out of this state
1.Plug in my SD Card to my computer
2. go to YSMenu.ini (Yes, I put YSmenu as my Firmware for my R4)
3. Set the 'Autoboot' location to BOOT.NDS
4. Launch the System then I'm back into TWL menu

---I didn't know if it should go into NDS bootstrap or TWilightmenu but it's TWL making the option not NDS bootstrap---
Video Footage with compression

https://user-images.githubusercontent.com/111697934/201964253-4110695f-70cc-4252-bc70-5839cf2a3774.mp4

**Comment by NightScript370** [comment]
You'll need to setup TWiLight Menu++ autoboot, considering that the use nds-bootstrap option is only a compliment to that feature.

**Comment by EpicDoodleboy2** [comment]
Alr thanks I done it and it works
