### ISSUE TITLE
B4DS Guru meditation error on latest firmware

### ISSUE THREAD

**Issue by EpicDoodleboy2** [DS-Homebrew/TWiLightMenu#2109]
When updating TWL menu to the latest version then inserting it into my ds lite it showed a guru meditation error
![20221125_163753](https://user-images.githubusercontent.com/111697934/204027278-5d56b276-573b-4cef-b4af-d013b1a89340.jpg)

**Comment by NightScript370** [comment]
Which flashcard on your DS Lite? Is it autobooting into TWiLight? If not, which kernel are you using?
Also, we fixed this and released the patch a second after the initial version was made. So chances are you got the older link.

**Comment by EpicDoodleboy2** [comment]
> Which flashcard on your DS Lite? Is it autobooting into TWiLight? If not, which kernel are you using? Also, we fixed this and released the patch a second after the initial version was made. So chances are you got the older link.

I'm using r4 sdhc clone cart and im using the latest version ive reinstalled it, it showed guru, did a older version it worked so it's the latest version and yes im autobooting TWL

**Comment by NightScript370** [comment]
Please rename "settings.srldr" found in sd:/_nds/TWiLightMenu to "title.srldr" (overwriting the currently existing "title.srldr"), and tell me the version number on the bottom right side of the top screen.

**Comment by EpicDoodleboy2** [comment]
> Please rename "settings.srldr" found in sd:/_nds/TWiLightMenu to "main.srldr" (overwriting the currently existing "main.srldr"), and tell me the version number on the bottom right side of the top screen.

Um on the new firmware or the old

**Comment by RocketRobz** [comment]
I think the reason why this error occurred is because you didn't update the autoboot files.
Try updating again, but this time, update both the autoboot files and `boot.nds`.

**Comment by EpicDoodleboy2** [comment]
> I think the reason why this error occurred is because you didn't update the autoboot files. Try updating again, but this time, also update both the autoboot files and `boot.nds`.

Thx RocketRobz that worked! I was using the TWL Wiki, and it didn't say to update the autoboot files and I think it should be changed This issue has been closed.

**Comment by RocketRobz** [comment]
> Thx RocketRobz that worked! I was using the TWL Wiki, and it didn't say to update the autoboot files and I think it should be changed This issue has been closed.

Please check again then, because it has already changed.
