### ISSUE TITLE
Add setting to toggle Slot-2 memory expansion in settings.ini

### ISSUE THREAD

**Issue by PrgmrAtHrt** [DS-Homebrew/TWiLightMenu#2115]
**Is your feature request related to a problem? Please describe.**
Having a setting in settings.ini to toggle the use of Slot-2 as a memory expansion would be nice, because currently this causes the original EZ-Flash Omega to not be detected by homebrew that allows the user to boot Slot-2 in GBA mode. Moonshell has a setting like this that allows the Omega to be booted properly when memory expansion is disabled (This is a moot point if Moonshell is loaded through TM++).

**Describe the solution you'd like**
Add a user setting in settings.ini that allows to the user to choose whether the cart in Slot-2 is used as a memory expansion or not.

**Comment by RocketRobz** [comment]
Commit 879b37f677914076c01aaf4d4c02f0a6c70415e6 disables using the EZ-Flash as Slot-2 memory expansion by default, and can only be enabled by setting `EZ_FLASH_RAM` to `1` in `settings.ini`.

**Comment by PrgmrAtHrt** [comment]
Didn't even notice the commit. I'll give it a shot.
