### ISSUE TITLE
Date and time characters have some artifacts

### ISSUE THREAD

**Issue by FirebusMx** [DS-Homebrew/TWiLightMenu#2126]
**TWiLight Menu++ Version: 25.7.0
**TWiLight Menu++ Theme:**  Dark theme

### Expected behavior
In the menu, the date and time should be visible in clear and crisp pixels

### Actual behavior

The date and time are displayed with artifacts and misaligned pixels rendering them non-legible 

### Steps to reproduce

1. install v25.7.0
2.Select DSi or 3DS style menu
3. Dark Theme

### Notes

Japanese console (if it matters), same result using manual update and Lazy Dsi Downloader script. Spanish and English languages tested, same result in both of them.

**Comment by NightScript370** [comment]
Could you send a picture of what you're referring to?

**Comment by RocketRobz** [comment]
If this was updated from a prior version, you need to either update or delete the dark theme in `sd:/_nds/TWiLightMenu/dsimenu/themes/`.

**Comment by FirebusMx** [comment]
@RocketRobz Thanks for a very fast response, Yes I am updating from a prior version, and I am trying to follow your directions but when I look into the files of v25.7.0 in the themes folder, I only see a "default" folder, but no dark or light theme available to copy and paste in the SD card. If I delete the dark theme in the sd card, from where can I obtain the new one to replace it in the sd card? thanks in advance

**Comment by FirebusMx** [comment]
@NightScript370 I just added a picture of the glitched characters

**Comment by FirebusMx** [comment]
@RocketRobz Ignore my previous message, I was not aware that a website with the themes available for download existed, followed your directions and deleted the dark theme, downloaded it again from that website, put it in the sd card and that's it, it worked perfectly, thanks!!
