### ISSUE TITLE
Pokemon BW2 3DS Twilight Fowarder Issue

### ISSUE THREAD

**Issue by LittleHooligan74** [DS-Homebrew/TWiLightMenu#2128]
when I launch pokemon BW2 specifically from (via) forwarder, it gives me a red screen when I try to boot up my save file, however both versions worked as normal when I boot them up on the twilight menu++
![20221225_071148 428](https://user-images.githubusercontent.com/93485120/209582560-b410e7f6-56f3-4232-8182-310c285204fc.jpg)
![HNI_0028](https://user-images.githubusercontent.com/93485120/209582574-bfbd0684-7bce-4a58-9037-7d3402ed7449.JPG)
![HNI_0029](https://user-images.githubusercontent.com/93485120/209582576-1559c602-63f9-4c93-890e-cdaaa2d8ba72.JPG)

**Comment by RocketRobz** [comment]
Let's move this to the Discord server (linked in the readme), as this issue isn't specific to TWiLight Menu++.
