### ISSUE TITLE
Add option to disable alpha blending to top screen fonts in theme.ini

### ISSUE THREAD

**Issue by B1BU** [DS-Homebrew/TWiLightMenu#2136]
**Is your feature request related to a problem? Please describe.**
The color palette for the date and time font in my custom theme can't be set to the values I want because color 2 always gets darker than it's supposed to.

**Describe the solution you'd like**
An option inside theme.ini that disables alpha blending for top screen fonts.

**Describe alternatives you've considered**
I'm not sure how all of that works so I don't know what other options there could be.

**Comment by NightScript370** [comment]
Added in the latest release. Thank you Evie
Closing...
