### ISSUE TITLE
List of games more "clean"

### ISSUE THREAD

**Issue by gMagnus87** [DS-Homebrew/TWiLightMenu#2142]
![imagen](https://user-images.githubusercontent.com/28157324/213829941-d39ea6c7-ff7e-4e56-8d2b-69cd658355f6.png)
Currently the game screen shows a huge list of items so you can scroll to an empty space.

It would be great to be able to customize this screen a bit more by adding an option to show only the occupied slots, focusing the view on them.
![imagen](https://user-images.githubusercontent.com/28157324/213830566-74e6d333-8bcb-4bc1-8a6e-c5883dd2f152.png)

**Comment by reddleak** [comment]
This should be marked as closed since the pull request acknowledging this has been merged.
