### ISSUE TITLE
Widescreen patch not working

### ISSUE THREAD

**Issue by kkellogg378** [DS-Homebrew/TWiLightMenu#2146]
O3DS v11.16, Luma v11.0, TWLM v25.7, NDSBS v0.68

Did every combination of downloading TWPatcher and TWiLightMenu++ (from CIAs and Universal Updater) as well as leaving the generated TwlBg.cxi file in the luma/sysmodules folder and copying it to /_nds/TwilightMenu/TwlBg and renaming it Widescreen.cxi. Nothing works. Scoured the internet for an answer and I wasn't able to find any working solutions. I enabled loading of other firms in Luma. I know that when I boot into the Luma menu it says "Booted from CTRNAND via B9S" but I'm not sure whether that makes a difference.

**Comment by RocketRobz** [comment]
> Booted from CTRNAND via B9S

This is why it's not working. Luma needs to be booted from the SD card.

**Comment by kkellogg378** [comment]
I'm not sure how to do that. Can't find a how-to anywhere

**Comment by RocketRobz** [comment]
You can use Universal-Updater to install Luma to the SD card.

**Comment by kkellogg378** [comment]
Figured it out, it wasn't booting off the SD card because I had to choose 32kb cluster size when i reformatted my SD card. Thanks for the quick replies!

**Comment by RocketRobz** [comment]
> Figured it out, it wasn't booting off the SD card because I had to choose 32kb cluster size when i reformatted my SD card. Thanks for the quick replies!

Huh, that's weird. My SD card has 32kb cluster size and Luma is booted off the SD card for me.
Was `boot.firm` on the SD root when Luma was booted off CTRNAND?

**Comment by kkellogg378** [comment]
I had picked 16kb when I initially formatted it. I reformatted with 32kb and now it works great
