### ISSUE TITLE
Cheats/RTS does not work with native flashcart driver (r4ids.cn R4i+ Gold 3DS RTS)

### ISSUE THREAD

**Issue by dankcuddlybear** [DS-Homebrew/TWiLightMenu#2147]
I am on a DS Lite with an R4i+ Gold 3DS RTS flashcart (r4ids.cn). Twilightmenu++ version is v25.8.0 with DSi theme.
I cannot use cheats at all with the native flashcart driver, only NDS-bootstrap. Also, I cannot open the RTS menu while in-game (save/load RAM, exit game, return to game). RTS stands for Real Time Save (basically the same as save states).

STEPS TO REPRODUCE:
- Press Y on any game (in this case Super Mario 64 DS). Set Use NDS bootstrap to yes. Press B and Y again. Cheats menu is now visible.
- Enter cheats menu and enable backlight code/test map 2 code.
- Launch game with NDS bootstrap.
- Cheats are working. I can change brightness with L+R+select+up/down and load test map 2 while holding select while loading a file. I can access the NDS-bootstrap menu with a button combination.
- Reboot DS. Press Y on game. Set Use NDS bootstrap to no. Press B and Y again. Cheats menu is now gone. Pressing X on the ROM info screen does nothing and I cannot select any cheats.
- Launch game with native flashcart driver.
- Cheats are not enabled. L+R+select+up/down does nothing, holding select while loading a file does not load the test map 2 and you start in Peach's garden). I cannot open the RTS menu with the default combination of L+R+B+A+down, or any of the other combinations available in my flashcart's stock kernel. This means I cannot save/load RAM or exit the game.

**Comment by RocketRobz** [comment]
Unfortunately, none of the flashcard kernels used by TWLMenu++ don't have an RTS menu.
As for cheats, the flashcard kernel's autoboot feature doesn't allow cheats to be used, so that in particular isn't a TWiLight Menu++ issue.
It's possible to implement RTS/save-states within nds-bootstrap though.

**Comment by dankcuddlybear** [comment]
It is 100% possible to get it working (at least on my card). When you launch a DS game, in the case of R4i+ Gold 3DS RTS, Twilightmenu sets lastLoaded to that game's path in fat0:/_wfwd/lastsave.ini, then loads fat0:/Wfwd.dat. Because autorunWithLastRom is set to 1 in fat0:/_wfwd/globalsettings.ini, the flashcart kernel immediately loads that game without showing the menu. By changing autorunWithLastRom to 0, I can enable cheats and RTS menu. Now the RTS menu works just fine in-game. However, for some reason when cheats are globally enabled, the kernel gets stuck on a loading screen for a few seconds before both screens turn off (DS is still on).

I managed to get cheats AND RTS working in the end. I downloaded the latest source code for Twilightmenu, changed ALL the file paths in the source code from "fat0:/_wfwd" to "fat0:/__rpg" and from "fat0:/Wfwd.dat" to "fat0:/rpg.dat". I then compiled Twilightmenu and copied it to my flashcart's SD card. I then downloaded the STOCK kernel and firmware from r4ids.cn. I renamed the stock kernel from _DS_MENU.dat to rpg.dat. Then I had to manually patch the Twilightmenu _DS_MENU.dat with my DLDI driver but now cheats and RTS are working. The only problem is that if I want to change what cheats are active for a game, I have to manually edit fat0:/__rpg/globalsettings.ini and change autorunWithLastRom to 0 so I can load the stock menu.

But this shows that it is 100% possible to enable cheats outside nds-bootstrap (at least on flashcarts that originally support cheats). The problem is that the firmware and kernel included with Twilightmenu are NOT stock and that's probably why it's not working properly.

**Comment by lifehackerhansol** [comment]
@dankcuddlybear They _are_ stock though. Just hex edited to a different path. This is only done because some people keep the regular kernel and it overlaps, so we just renamed everything to `_wfwd`. literally just ran `sed -i "s/__rpg/_wfwd/g __DS_MENU.DAT`

In fact, the question we need to ask is why _doesn't it work?_

**Comment by lifehackerhansol** [comment]
The problem is very likely that `globalsettings.ini` inside `_wfwd` likely has an RTS setting that is maybe turned off (or outright missing).

I don't have an RTS compatible flashcart though, so if you could find this INI setting, I can add it.

**Comment by lifehackerhansol** [comment]
Wait actually, I do have one. Got an R4iDSN.

The INI setting required is `rts = 1`. And it is indeed missing in the two kernels that support Wood RTS (r4ids.cn 1.64 and R4iDSN).

**Comment by lifehackerhansol** [comment]
Cheats is a wont-fix, just to clarify. Wood's built in loading mechanism does not allow cheats to work. It does allow RTS, I guess.
