### ISSUE TITLE
Red Screen appears when run it on the flashcard.

### ISSUE THREAD

**Issue by bulzipke** [DS-Homebrew/TWiLightMenu#2149]
**Your console:**
2DS and new 3DS XL both appears

**Launch Method:**
flashcart (r4ids.cn gold, acekard2i, ace3ds plus, cyclodsi, dstt)

**Version used:**
v0.69.0

**Game tested/used/applicable:** Ghost Trick
This is a Korean fan translation game.

**Save file:**

**Expected Behavior:**
Run fan translation game in flashcard bootstrap.

**Actual Behavior:**
Red Screen appears when run it on the flashcard. But install twilight menu to 3ds as cia it will be ok.

### Steps to reproduce
1. Use [this](https://wiki.ds-homebrew.com/twilightmenu/installing-flashcard) and install it on the flashcard.
2. run by bootstrap with fan translation game.
3. red screen

### Will you be available for future issues and/or replies?
Yes

**Comment by NightScript370** [comment]
Do you have a picture of the red screen?

**Comment by bulzipke** [comment]
![image](https://user-images.githubusercontent.com/15259720/220183115-09e0125d-6cc5-42d7-a5e3-5533761e5ee2.png)

**Comment by RocketRobz** [comment]
Does this issue still occur?

**Comment by bulzipke** [comment]
> Does this issue still occur?

I just checked and it doesn't happen anymore.
Thanks!
