### ISSUE TITLE
Separate screen filters for top & bottom screens (like in Luma 12.0)

### ISSUE THREAD

**Issue by InsanePrimate** [DS-Homebrew/TWiLightMenu#2155]
**Is your feature request related to a problem? Please describe.**
A huge amount of DSi, 3DS & NEW 3DS have differently calibrated (or simply NOT calibrated screens). I have several and none of them have matching screens which annoys me to no end. Since Luma 12.0 this can somewhat be compensated on the 3ds while in 3DS mode. But as soon as I start TWiLightMenu and go in DS mode, the difference in screen color (white point) becomes very noticeable again (since Luma can't access DS mode and therefore can't apply the screen filters)

**Describe the solution you'd like**
I would LOVE to see a "solution" (more like a band-aid but A LOT better than nothing) in TWiLightMenu similar to the screen filter solution in Luma 12.0. If at all possible, I believe many DSi and 3DS users would love this feature, since this is a very common problem and I do not believe, that I am the only one who is annoyed by the fact, that Nintendo quite obviously stopped caring about basic quality decades ago!

**Comment by RocketRobz** [comment]
TWPatch has a redshift feature which can be used to change screen colors. idk if it separate settings can be used for each screen though.
