### ISSUE TITLE
GBA games not saving when running in Native Mode on Supercard SD

### ISSUE THREAD

**Issue by Infection321** [DS-Homebrew/TWiLightMenu#2168]
I am running v25.8.1 on a DS lite. I have a Supercard SD and when running GBA Roms in native mode it won't save games. The games are SRAM patched. I did notice that it creates a save file, but I don't know if it's just the file that gets made on ROM boot.

**Comment by RocketRobz** [comment]
Please use clean ROMs instead of SRAM-patched ROMs.
TWiLight Menu++ itself automatically SRAM-patches the ROMs on the fly, so manually SRAM-patched ROMs may cause interference.

**Comment by Infection321** [comment]
To exit a game, is that with a shortcut combination or simply refering to resetting the console? I have been simply resetting the DS and entering the twilight menu. Thanks for the SRAM correction, Mario world tells me that my save data is corrupted so there is definitely progress.

**Comment by RocketRobz** [comment]
> To exit a game, is that with a shortcut combination or simply refering to resetting the console?

It's simply resetting the console.

**Comment by Infection321** [comment]
I have done more tests and it does save, but only if I reset very quickly. Waiting even one second corrupts the save file.

**Comment by RocketRobz** [comment]
Closing, as this sounds like an issue with the Supercard SRAM chip.
