### ISSUE TITLE
Add Recently Played menu, accessible via button shortcut

### ISSUE THREAD

**Issue by Soundtoxin** [DS-Homebrew/TWiLightMenu#2176]
**Is your feature request related to a problem? Please describe.**

If you have a lot of games it can be annoying to get to the same few you've played lately in your list.

**Describe the solution you'd like**

I like the feature of the EZ-Flash Omega GBA flashcart where you can press start and see a list of recently launched games in order. Something like this for TWiLightMenu would be awesome.
**Describe alternatives you've considered**

**Additional context**

**Comment by clach04** [comment]
@Soundtoxin looks similar to https://github.com/DS-Homebrew/TWiLightMenu/issues/1873

**Comment by Soundtoxin** [comment]
Yep, you're right. I'll close this as a dupe then.
