### ISSUE TITLE
Top screen goes blank when dsi theme music is set to off

### ISSUE THREAD

**Issue by Alpdrucken** [DS-Homebrew/TWiLightMenu#2180]
TWLM Version: 25.9.0
Installed on an DSi with an SD
Theme: DSi

Bug: Since the latest release, when I turn off the DSi theme music in TWLM settings and return to the DSi UI, the top screen goes blank. Games and other apps work fine, it only happens within the game selection menu.

**Comment by Harry7228** [comment]
I have the same problem: On a 3ds with the DSi theme TWiLightMenu v25.9.1a

**Comment by Alpdrucken** [comment]
still happens in v25.9.1a
