### ISSUE TITLE
White Screen on startup if Custom Anemone3DS Theme is installed

### ISSUE THREAD

**Issue by Someguy1519** [DS-Homebrew/TWiLightMenu#2181]
**Base Console:** 

New 3DS XL Firmware version
11.16.0-49U
Luma3DS 12.0.1
boot9strap 1.4

**TWiLight Menu++ Version:** 25.9.0

**TWiLight Menu++ Theme:** DSi

### Expected behavior

Normal Boot

### Actual behavior

White Screen if Custom Anemone 3DS theme is installed.

### Steps to reproduce

1. Have Custom Anemone3DS Theme installed
2. Startup TwilightMenu
3. 

Issue only seems to happen if I have a custom Anemone3DS theme installed. TwilightMenu boots up fine if I have stock Black theme installed.

**Comment by RocketRobz** [comment]
Anemone3DS does not affect how TWiLight Menu++ boots.
When a white screen occurs, just reboot TWiLight Menu++.

**Comment by Someguy1519** [comment]
Well, for some reason TwilightMenu just refuses to boot when I have a custom theme installed. I go back to one of the stock 3DS themes and it boots up. I've tried everything to get it to boot while I have my custom theme installed and it still white screens.

**Comment by RocketRobz** [comment]
Try reformatting the SD card here then: https://dsi.cfw.guide/sd-card-setup.html

**Comment by Someguy1519** [comment]
Recent update fixed this issue for me.
