### ISSUE TITLE
Zip file support for DS games

### ISSUE THREAD

**Issue by Agusum** [DS-Homebrew/TWiLightMenu#2192]
**Is your feature request related to a problem? Please describe.**
Emulators support running roms directly from zip files but TWiLightMenu can't, so I need to keep 2 different rom sets for both platforms.

**Describe the solution you'd like**
Ability to play zipped DS games in TWiLightMenu. I'm not sure if this is technically feasible though.

**Comment by Agusum** [comment]
Do you know approximately how much time would it be for large games? If it's not too big, it could be up to the user whether or not they're willing to endure the additional wait time and the usage of the SD write cycles faster.

**Comment by lifehackerhansol** [comment]
In my opinion, NACK.

There is no reason to _ever_ have any ROM in a zip file. This entire program is already bordering on the legal line, and considering the _only_ reason you ever have a zipped ROM in the first place is by pirated means, supporting it would indicate full embracement of piracy at that point. Not to mention, one shouldn't even have them zipped to begin with, the correct thing to do if you are running low on space is to trim the ROM, not compress it. Hell, dumping tools such as GodMode9 already let you trim the ROM right in the dumping process, and NDSTokyoTrim exists, you have many options here.

**Comment by Agusum** [comment]
@lifehackerhansol It's more for the convenience of having a combined rom set for both platforms than for the space saving, with additional benefit of faster transfer speeds over wifi.

**Comment by Masamune3210** [comment]
> In my opinion, NACK.
> 
> There is no reason to _ever_ have any ROM in a zip file. This entire program is already bordering on the legal line, and considering the _only_ reason you ever have a zipped ROM in the first place is by pirated means, supporting it would indicate full embracement of piracy at that point. Not to mention, one shouldn't even have them zipped to begin with, the correct thing to do if you are running low on space is to trim the ROM, not compress it. Hell, dumping tools such as GodMode9 already let you trim the ROM right in the dumping process, and NDSTokyoTrim exists, you have many options here.

.....you....you know people can make their own zip archives, right? the only reason to have a zip file isn't just because you got it from uncle fred's random rom server

**Comment by lifehackerhansol** [comment]
Did you not read my last point?

**Comment by Masamune3210** [comment]
Trimming a rom is a destructive process, zipping a rom is not

**Comment by lifehackerhansol** [comment]
...have a backup?
Use NDSTokyoTrim, set the output folder to your SD card, let it trim from your original file straight to your SD? Or trim it to a temporary location and copy to your networked whatever? If the goal is to move it via Wi-Fi, why would you zip the files one by one, instead of zipping the entire collection and moving it, then extracting it at the destination? Or even better, why zip? Why not just throw all of your files into a `.tar.gz` and add the files to said tar every time you gain a file? This would certainly alleviate the congestion of moving files from one place to another.

I'm genuinely failing to grasp the concept of an individual zip file, not even for compression does this make sense.

**Comment by Kaisaan** [comment]
![apandah-zank](https://user-images.githubusercontent.com/34224128/231036895-12a71307-cb35-4eca-9357-76e21d8f2130.gif)

**Comment by Agusum** [comment]
> > It's more for the convenience of having a combined rom set for both platforms
> 
> What platforms? I don't get it

Computer & 3DS

> > with additional benefit of faster transfer speeds over wifi.
> 
> the time to decompress is probably going to be even longer than the actual transfer... I don't think this makes sense to implement on multiple levels

This is what I was trying to get to. How long will it take to decompress the game to play it? Is this what emulators do in the background too to allow playing from zip files?

**Comment by Allinxter** [comment]
Emulators also support running .nds files as they are without zipping them, which TWiLight can do. I don't really see the point of this, considering if what you want is for the files to be compatible with "both platforms," just unzip them.
If you want to move your files to a different drive, you can zip them all in a file (not individually), move them, and then unpack them on the new destination.

**Comment by Kaisaan** [comment]
As it stands for now, zip file support will not be added. If you want to continue this discussion I suggest doing so in our [DS⁽ⁱ⁾ Mode Hacking! Discord Server](https://discord.gg/yD3spjv).
