### ISSUE TITLE
system wide blue light filter 

### ISSUE THREAD

**Issue by avichou** [DS-Homebrew/TWiLightMenu#2193]
i saw someone mention it 4 years ago and at that time it wasnt doable

have times changed, and do you believe it could be possible to integrate a system wide yellow filter in order to limit blue waves emission, like phones do ? 

something that would not only work within the menu, but also during gameplay

**Comment by RocketRobz** [comment]
It is unfortunately not possible, because of how the video hardware works.

**Comment by avichou** [comment]
> It is unfortunately not possible, because of how the video hardware works.

Thanks, closing it
