### ISSUE TITLE
Add DSP blacklist for GBARunner2

### ISSUE THREAD

**Issue by spellboundtriangle** [DS-Homebrew/TWiLightMenu#2194]
**Is your feature request related to a problem? Please describe.**
Some GBA games are known to have issues with the DSP branch of GBARunner2 (see the [compatibility list](https://wiki.gbatemp.net/wiki/GBARunner2/DSi_3DS_Compatibility_List)). TWiLight Menu++ defaults to the DSP build if not using Memory Pit, so this may cause an issue with launching some games that could be easily solved, given that TWLM++ is distributed with with DSP and non-DSP builds.

**Describe the solution you'd like**
Create a blacklist that will force the specified games to launch with the non-DSP build.
This is assuming that the results are consistent with what's in the compatibility list, as those are mostly tested on official builds.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by RocketRobz** [comment]
Will not be needed, as GBARunner3 will soon be bundled.
