### ISSUE TITLE
Camera led does not turn off

### ISSUE THREAD

**Issue by srtanooki** [DS-Homebrew/TWiLightMenu#2197]
I have been using twilight menu for a long time, ([v25.9.1a])  on a dsi, and since I updated to the latest version, I activated the option to read rom and select camera led. The problem here is that it gets very hot, and ends up causing other errors. 

When I tried to deactivate it, I realized that it was still on, even entering the normal dsi launcher it is still on, it wouldn't be a problem if it wasn't that the place where the led is is heated like an oven.

Sorry for my bad writing and language, my English is bad, I hope it can be resolved

**Comment by RocketRobz** [comment]
When re-entering TWLMenu++, are the LED options still shown as off? If they're still shown as `Camera`, make sure you turn them off, as well as pressing B to save the TWLMenu++ Settings.
If the issue persists, hold A+B+X+Y to reset the settings when starting TWLMenu++.

**Comment by srtanooki** [comment]
> 

Yes, even if it says that it is disabled in the settings, it is still on even entering unlaunch or something else

I also tried resetting the twilight menu configuration and reinstalling it and nothing

**Comment by RocketRobz** [comment]
Then this is not a TWiLight Menu++ issue. The issue on the hardware's side.

Please join our Discord server to continue this discussion further: https://discord.gg/yD3spjv
