### ISSUE TITLE
NTFS Support for Flashcards (Possible???)

### ISSUE THREAD

**Issue by Minionguyjpro** [DS-Homebrew/TWiLightMenu#2200]
**Is your feature request related to a problem? Please describe.**

Not exactly, if there was support for NTFS cards might be a bit faster.

**Describe the solution you'd like**

Support for flashcards formatted with NTFS.

**Describe alternatives you've considered**

N/A

**Additional context**

I guess this will depend on the card whether it is possible, or might just **not** be possible.

**Comment by NightScript370** [comment]
Since this is dependent on the firmware to load the nds file in the first place, the only reasonable flashcard that you could expect this for is the DSPico project by Gericom.

@Gericom which SD card driver do you plan on using? Does it support NTFS? If not, feel free to close this issue with a comment.

**Comment by lifehackerhansol** [comment]
NTFS might actually be a detriment due to a lack of RAM.

**Comment by Minionguyjpro** [comment]
How about file systems like exFAT then?

**Comment by NightScript370** [comment]
The rule I outlined above of currently being limited in the firmware is with any file system, including the Linux ones, or whatever the big corporations determine to be next. The only one that's in actual development is the DSPico Firmware.

Thereby, it is outside our control up until they allow it.

**Comment by lifehackerhansol** [comment]
Not just the firmware you have to think about. libfat is a problem here too, which doesn't support exFAT at all. And nds-bootstrap's custom FAT driver certainly won't handle it.

Closing, as we have no feasible way to make this work.
