### ISSUE TITLE
Start failed. Error -2 Won't let me boot nds files.

### ISSUE THREAD

**Issue by ps1freak26** [DS-Homebrew/TWiLightMenu#2202]
System Used: 2ds with custom firmware no flashcart

Twilight Menu Version: Release and Nightly

Expected Behavior: Let the game run without errors.

Actual Behavior: It shows a black screen with Start failed. Error -2 

Steps to Reproduce: 
1. Install the widescreen patch
2. Reinstall twilight
3. Update luma

Notes: It worked before I uninstalled twilight. I regretted using the widescreen patch because it made the upscaling blurry. Did what the guides said then now I can't play ds games digitally.

**Comment by RocketRobz** [comment]
Sounds like your nds-bootstrap installation is corrupted.
Try manually installing nds-bootstrap here: https://github.com/DS-Homebrew/nds-bootstrap/releases

**Comment by ps1freak26** [comment]
Reinstalling it with the universal updater version of the release version of nds bootstrap causes the error for some reason. I'll try the github version when I have access to a sd card slot on a computer.

**Comment by ps1freak26** [comment]
I'm still getting the error

**Comment by RocketRobz** [comment]
I've found the error actually means that the .nds file is missing, and it has been found that TWiLight Menu++ is incorrectly setting the .nds file path, which is causing the error.

**Comment by colebob9** [comment]
Having this issue on a Japanese New 3DS LL with US firmware. Didn't do anything with the widescreen patches, only installed TWiLight Menu++ from Universal Updater. Tried deleting the "_nds" folder, reinstalling both TWiLight Menu++ and nds-bootstrap, using TWLFix, updating the system, no change.

One workaround I found is that using an NDS forwarder icon boots games fine.
