### ISSUE TITLE
Trying to connect MIDIControlDS

### ISSUE THREAD

**Issue by Jonas195** [DS-Homebrew/TWiLightMenu#2204]
hey robz, I've been trying to connect a homebrew application called MIDICONTROLDS for a long time but it seems to have problems connecting to an internet server from the DSi, what do you recommend?

NOTE: I DO NOT SPEAK ENGLISH

**Comment by Jonas195** [comment]
1) - https://forum.ableton.com/viewtopic.php?t=158697 < - - - - - - - - - - - - forum on the subject in question

2) - https://www.youtube.com/watch?v=QlW6OP2cWOA&list=PLB3B186008C216A82 < - - - - - - - - - Videos

3) - https://www.gamebrew.org/wiki/DS_MIDI_Keyboard < - - - - - - - - - - Homebrew MIDI keyboard

4) - https://gbatemp.net/download/midi-control-ds.25286/ < - - - - - - - - - MIDICONTROLDS Overview

5) -  http://midicontrolds.blogspot.com/ < - - - - - - - - - - - MIDI CONTROL BLOGSPOT

**Comment by Jonas195** [comment]
https://www.youtube.com/watch?v=AYDF313Ae7A < - - - - - - - - DEMO VIDEO 

NOTE: VIDEOS AND FORUMS ARE SHORT

**Comment by RocketRobz** [comment]
Your access point may not be a WEP or Open type. Newer types such as WPA will not work.
See this page for more details: https://wiki.ds-homebrew.com/ds-index/wifi
