### ISSUE TITLE
Dark and white themes

### ISSUE THREAD

**Issue by Leonardo5681** [DS-Homebrew/TWiLightMenu#2225]
Hey, I have a rather annoying problem, practically some time ago, when I went into the themes and pressed the A key on the DS It told me if I wanted the dark or light theme (in some themes that supported it) but for a few versions it doesn't happen anymore, and since with the 25.9.6 update you set the light theme by default, I would like to get the menu back to put the dark theme, fix the problem please
![IMG_1509](https://github.com/DS-Homebrew/TWiLightMenu/assets/92219720/fc4af5d9-8d83-4a99-aa98-e5daff05825f)

**Comment by spellboundtriangle** [comment]
You have to download it from https://skins.ds-homebrew.com

**Comment by spellboundtriangle** [comment]
It's not a bug, TWiLight Menu++ hasn't included multiple skins for individual themes in quite some time. Why you don't *still* have those skins I couldn't tell you, but all TWiLight Menu++ comes with for the DSi theme now is the default light skin. The dark skin is not present inside of the app at all, nor is it intended to be selectable by default. Unless you download it, of course

**Comment by RocketRobz** [comment]
Reverting to the white skin was a decisive choice, not a bug.

TWLMenu++'s first versions contained the white skin by default, with the dark skin being optional.
Later on, it was made to only contain one skin of the DSi theme to save space, which is the dark theme.

The decision to go back to the original white skin is stated by the v25.9.6 release page:

> This was done because of some users apparently having bad first impressions with TWLMenu++ on DSi, and in addition, would end up making forwarders for the original DSi Menu (along with optionally installing hiyaCFW, a DSi CFW which is not needed nowadays).

**Comment by Leonardo5681** [comment]
oh, ok
