### ISSUE TITLE
3ds power off when exit game to menu of twilight menu

### ISSUE THREAD

**Issue by Pig0983** [DS-Homebrew/TWiLightMenu#2234]
Sometimes when i hold L + down+ select to exit ds game to menu of twilight menu, my 3ds power off so i must turn it on again and go back to twilight menu, i use twilight menu version 25.10.0 latest version, when i play gba game all of game i play are crash i can't play, please solve it, I'm from vietnam with love to twilight menu on old 3ds, thanks, my english is not good.

**Comment by Pig0983** [comment]
pls fix when i exit game hold l down select not power my system in the next version @RocketRobz

**Comment by RocketRobz** [comment]
This is not a TWiLight Menu++ issue.
Sounds more like an issue with Luma.
