### ISSUE TITLE
Add TempGBA emulator support from Supercard DSTWO

### ISSUE THREAD

**Issue by rods-03** [DS-Homebrew/TWiLightMenu#2235]
Hello! My name is Rodrigo, I'm from Brazil.
First I want to thank you for the excellent work done with TWiLightMenu.

How likely are we to have TempGBA emulator support (https://github.com/belek666/TempGBA) as an alternative to GBARunner2 on Supercard DSTWO?

TempGBA is native to DSTWO, makes use of the RAM built into the flashcard and its compatibility list is infinitely longer than that of GBARunner2. (https://wiki.gbatemp.net/wiki/TempGBA_Compatibility)

Grateful!

**Comment by RocketRobz** [comment]
If TempGBA supports autobooting a ROM, then it may be likely.

**Comment by rods-03** [comment]
If there's a way to open TempGBA from the TWiLightMenu, that would be great. 🤩

**Comment by RocketRobz** [comment]
> If there's a way to open TempGBA from the TWiLightMenu, that would be great. 🤩

That you can already do. Just launch it's .plg file like you would with any .nds or other ROM file.

**Comment by rods-03** [comment]
> > Se houver uma maneira de abrir o TempGBA a partir do TWiLightMenu, isso seria ótimo.🤩
> 
> Isso você já pode fazer. Basta iniciar o arquivo .plg como faria com qualquer arquivo .nds ou outro arquivo ROM.

Very good! I tested it and it worked. I didn't think of that before, sorry.

Anyway, I stand by my suggestion for possible native support by TWiLightMenu.

**Comment by rods-03** [comment]
Taking advantage of your kindness, I still use the TWiLight Menu on my DSTWO flashcard, but for some reason I can't use nds-bootstrap as a game loader.  When opening any DS ROM, a red screen appears with the message "Error: Data abort!".
I use a 4GB FAT32 SD card - 32kb allocation.

Because of that I started using the Kernel as a game loader and it has worked well.  But when opening any DS rom, the game is not opened directly.  Instead the DSTWO Kernel menu appears so I can choose the rom again.  This somewhat detracts from the experience of using the TWiLight Menu.

Is there any solution for these cases?

**Comment by RocketRobz** [comment]
Try (re-)adding the flashcard loader files from `TWiLightMenu-Flashcard.7z`.

**Comment by rods-03** [comment]
> Try (re-)adding the flashcard loader files from `TWiLightMenu-Flashcard.7z`.

I've done it a few times, including formatting the SD card in different ways and also testing other cards, but it didn't work.  :/

**Comment by RocketRobz** [comment]
> > Try (re-)adding the flashcard loader files from `TWiLightMenu-Flashcard.7z`.
> 
> I've done it a few times, including formatting the SD card in different ways and also testing other cards, but it didn't work. :/

Have you tried deleting the `_dstwo` folder before re-adding the flashcard loader files?
If you did, then idk why the issue is occurring.

**Comment by rods-03** [comment]
> > > Try (re-)adding the flashcard loader files from `TWiLightMenu-Flashcard.7z`.
> > 
> > 
> > I've done it a few times, including formatting the SD card in different ways and also testing other cards, but it didn't work. :/
> 
> Have you tried deleting the `_dstwo` folder before re-adding the flashcard loader files? If you did, then idk why the issue is occurring.

I did this whole process more than once and got no results. However, after some testing, I found that nds-bootstrap fails to open roms in DSTWO when TWiLightMenu autoboot is enabled.

When opening TWiLightMenu from DSTWO's EOS kernel, the roms run normally with nds-bootstrap.

Is there any way to make it work normally with 'autoboot', or just through a future fix?
