### ISSUE TITLE
DSI Dark Theme date and time unreadable

### ISSUE THREAD

**Issue by clach04** [DS-Homebrew/TWiLightMenu#2240]
**Base Console:** DSi (not sure if this is relevent

**TWiLight Menu++ Version:** 

https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v25.11.0

**TWiLight Menu++ Theme:** 

DSI Dark. I.e. not the default, not white/light.

### Expected behavior

Readable date and time ;-)

### Actual behavior

Unreadable date and time

### Steps to reproduce

1. Open Twilight settings
2. scroll down 1, to theme
3. select DSI
4.  Press A to bring up theme options
5. Choose Dark

### Notes

Been like this for a few versions, only just got around to reporting.

Workaround, don't use Dark ;-). Default works fine.

See:
![DSi_dark_time_date_battery_0](https://github.com/DS-Homebrew/TWiLightMenu/assets/424032/849f12b6-f0a6-4566-8557-92017b56dae4)

**Comment by spellboundtriangle** [comment]
Download the latest version of the skin from [the skins site](https://skins.ds-homebrew.com)

**Comment by clach04** [comment]
Thanks @spellboundtriangle ,  that dark version looks better :-)

![Imagepipe_2](https://github.com/DS-Homebrew/TWiLightMenu/assets/424032/a2482189-0bb6-4055-8205-9beb92decef7)

I grabbed https://github.com/DS-Homebrew/twlmenu-extras/blob/master/_nds/TWiLightMenu/dsimenu/themes/dark.7z from https://github.com/DS-Homebrew/twlmenu-extras/commit/586693770a91cbd44aacbabc32a99e6b547d9ae3

**Comment by clach04** [comment]
@Epicpkmn11 Does this mean it's appropriate to update https://github.com/DS-Homebrew/TWiLightMenu/tree/master/romsel_dsimenutheme/resources/dsimenu_theme_examples/dsi/dark with the contents of the archive https://github.com/DS-Homebrew/twlmenu-extras/blob/master/_nds/TWiLightMenu/dsimenu/themes/dark.7z ?

I can open a PR if that's useful.

**Comment by Epicpkmn11** [comment]
Oh, yeah those have probably gotten a bit behind

**Comment by clach04** [comment]
Not had chance to get back to this for a while :-(

    cd romsel_dsimenutheme/resources/dsimenu_theme_examples/dsi/
    rm -rf dark
    7z x /..../twlmenu-extras/blob/master/_nds/TWiLightMenu/dsimenu/themes/dark.7z
    git checkout -- dark/Makefile

status:

    .....\TWiLightMenu\romsel_dsimenutheme\resources\dsimenu_theme_examples\dsi>git status
    On branch master
    Your branch is up to date with 'origin/master'.

    Changes not staged for commit:
      (use "git add/rm <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

            deleted:    dark/background_grit/bottom.bmp
            deleted:    dark/background_grit/bottom.grit
            deleted:    dark/background_grit/bottom_bubble.bmp
            deleted:    dark/background_grit/bottom_bubble.grit
            deleted:    dark/background_grit/bottom_bubble_macro.bmp
            deleted:    dark/background_grit/bottom_bubble_macro.grit
            deleted:    dark/background_grit/bottom_moving.bmp
            deleted:    dark/background_grit/bottom_moving.grit
            deleted:    dark/background_grit/top.bmp
            deleted:    dark/background_grit/top.grit
            modified:   dark/battery/battery0.png
            modified:   dark/battery/battery1.png
            deleted:    dark/battery/battery1purple.png
            modified:   dark/battery/battery2.png
            deleted:    dark/battery/battery2purple.png
            modified:   dark/battery/battery3.png
            deleted:    dark/battery/battery3purple.png
            modified:   dark/battery/battery4.png
            deleted:    dark/battery/battery4purple.png
            modified:   dark/battery/batterycharge.png
            modified:   dark/battery/batterychargeblink.png
            modified:   dark/battery/batteryfull.png
            modified:   dark/battery/batteryfullDS.png
            modified:   dark/battery/batterylow.png
            deleted:    dark/grit/bips.bmp
            deleted:    dark/grit/bips.grit
            deleted:    dark/grit/box.grit
            deleted:    dark/grit/box.png
            deleted:    dark/grit/brace.grit
            deleted:    dark/grit/brace.png
            deleted:    dark/grit/bubble.grit
            deleted:    dark/grit/bubble.png
            deleted:    dark/grit/button_arrow.grit
            deleted:    dark/grit/button_arrow.png
            deleted:    dark/grit/cornerbutton.grit
            deleted:    dark/grit/cornerbutton.png
            deleted:    dark/grit/dialogbox.grit
            deleted:    dark/grit/dialogbox.png
            deleted:    dark/grit/folder.grit
            deleted:    dark/grit/folder.png
            deleted:    dark/grit/icon_a26.grit
            deleted:    dark/grit/icon_a26.png
            deleted:    dark/grit/icon_col.grit
            deleted:    dark/grit/icon_col.png
            deleted:    dark/grit/icon_gb.grit
            deleted:    dark/grit/icon_gb.png
            deleted:    dark/grit/icon_gba.grit
            deleted:    dark/grit/icon_gba.png
            deleted:    dark/grit/icon_gbamode.grit
            deleted:    dark/grit/icon_gbamode.png
            deleted:    dark/grit/icon_gg.grit
            deleted:    dark/grit/icon_gg.png
            deleted:    dark/grit/icon_img.grit
            deleted:    dark/grit/icon_img.png
            deleted:    dark/grit/icon_int.grit
            deleted:    dark/grit/icon_int.png
            deleted:    dark/grit/icon_m5.grit
            deleted:    dark/grit/icon_m5.png
            deleted:    dark/grit/icon_manual.grit
            deleted:    dark/grit/icon_manual.png
            deleted:    dark/grit/icon_md.grit
            deleted:    dark/grit/icon_md.png
            deleted:    dark/grit/icon_nes.grit
            deleted:    dark/grit/icon_nes.png
            deleted:    dark/grit/icon_ngp.grit
            deleted:    dark/grit/icon_ngp.png
            deleted:    dark/grit/icon_pce.grit
            deleted:    dark/grit/icon_pce.png
            deleted:    dark/grit/icon_plg.grit
            deleted:    dark/grit/icon_plg.png
            deleted:    dark/grit/icon_settings.grit
            deleted:    dark/grit/icon_settings.png
            deleted:    dark/grit/icon_sg.grit
            deleted:    dark/grit/icon_sg.png
            deleted:    dark/grit/icon_sms.grit
            deleted:    dark/grit/icon_sms.png
            deleted:    dark/grit/icon_snes.grit
            deleted:    dark/grit/icon_snes.png
            deleted:    dark/grit/icon_unk.grit
            deleted:    dark/grit/icon_unk.png
            deleted:    dark/grit/icon_vid.grit
            deleted:    dark/grit/icon_vid.png
            deleted:    dark/grit/icon_ws.grit
            deleted:    dark/grit/icon_ws.png
            deleted:    dark/grit/launch_dot.grit
            deleted:    dark/grit/launch_dot.png
            deleted:    dark/grit/moving_arrow.grit
            deleted:    dark/grit/moving_arrow.png
            deleted:    dark/grit/nintendo_dsi_menu.grit
            deleted:    dark/grit/nintendo_dsi_menu.png
            deleted:    dark/grit/progress.grit
            deleted:    dark/grit/progress.png
            deleted:    dark/grit/scroll_window.bmp
            deleted:    dark/grit/scroll_window.grit
            deleted:    dark/grit/small_cart.grit
            deleted:    dark/grit/small_cart.png
            deleted:    dark/grit/start_border.grit
            deleted:    dark/grit/start_border.png
            deleted:    dark/grit/start_text.grit
            deleted:    dark/grit/start_text.png
            deleted:    dark/grit/wirelessicons.grit
            deleted:    dark/grit/wirelessicons.png
            modified:   dark/quickmenu/bottombg.png
            modified:   dark/quickmenu/phat_topbg.png
            modified:   dark/quickmenu/topbg.png
            modified:   dark/theme.ini
            modified:   dark/ui/Lshoulder.png
            modified:   dark/ui/Lshoulder_greyed.png
            modified:   dark/ui/Rshoulder.png
            modified:   dark/ui/Rshoulder_greyed.png
            modified:   dark/volume/volume0.png
            modified:   dark/volume/volume1.png
            modified:   dark/volume/volume2.png
            modified:   dark/volume/volume3.png

**Comment by clach04** [comment]
@Epicpkmn11 I posted PR https://github.com/DS-Homebrew/TWiLightMenu/pull/2250 - it's 100% **untested**.

I took the dark.7z and applied it manually to my SD card which works for me (see earlier) comment.

Potentially could sync automatically via a script that automates the steps in comment https://github.com/DS-Homebrew/TWiLightMenu/issues/2240#issuecomment-1627807830

**Comment by RocketRobz** [comment]
The dark skin files are already up to date in the main TWLMenu++ repo.
Your issue (which is now fixed) was that the dark skin was probably missing some files.
