### ISSUE TITLE
Force white backdrop on game icons for custom themes 

### ISSUE THREAD

**Issue by Yola-cola** [DS-Homebrew/TWiLightMenu#2241]
**Is your feature request related to a problem? Please describe.**
I find it a little jarring that custom skin makes some ds icons look terrible. Since the ds only have a white backdrop most game icons made their white transparent to save time. So that's why it looks werid with some skins

**Describe the solution you'd like**
My solution is to add an option in setting to force a white background on game icons to make it look more pleasant.

**Describe alternatives you've considered**
If that doesn't work maybe you can do a guide on how to edit a skin

**Additional context**
![890e2bbe-1d7b-4802-9b0a-d64755d18aec](https://github.com/DS-Homebrew/TWiLightMenu/assets/53379032/42f0d91b-c6b5-40fd-95ae-a1a0cdcf23bb)

**Comment by Epicpkmn11** [comment]
imo this should be up to the skin, if you want a white background then simply make that area have a white background in the skin. Maybe it could be a toggleable setting, but not forced.

The DS doesn't actually do solid white, it does a gradient, so forcing a solid white background on white skins would look worse.

**Comment by Yola-cola** [comment]
> imo this should be up to the skin, if you want a white background then simply make that area have a white background in the skin. Maybe it could be a toggleable setting, but not forced.
> 
> The DS doesn't actually do solid white, it does a gradient, so forcing a solid white background on white skins would look worse.

I'm wasn't saying

**Comment by Yola-cola** [comment]
> imo this should be up to the skin, if you want a white background then simply make that area have a white background in the skin. Maybe it could be a toggleable setting, but not forced.
> 
> The DS doesn't actually do solid white, it does a gradient, so forcing a solid white background on white skins would look worse.

I'm not saying to force a white backdrop. I just want a little toggle option in setting.

**Comment by Yola-cola** [comment]
> imo this should be up to the skin, if you want a white background then simply make that area have a white background in the skin. Maybe it could be a toggleable setting, but not forced.
> 
> The DS doesn't actually do solid white, it does a gradient, so forcing a solid white background on white skins would look worse.

Also I mean the box containing a game Icon not a the whole thing
