### ISSUE TITLE
Allow placing menu items away from front of menu

### ISSUE THREAD

**Issue by DatHypnoboi** [DS-Homebrew/TWiLightMenu#2254]
**Is your feature request related to a problem? Please describe.**
I would like to be able to have items be out of the way enough to not have to think about them during normal use, but not have to enter the settings to show hidden items if I need to use them

**Describe the solution you'd like**
In the stock DSi menu, you can place items anywhere you want so that every item isn't clustered at the start of the screen. It would be nice if this functionality could be replicated for the TWiLightMenu

**Describe alternatives you've considered**
Currently I just hide all my mostly unused items and show hidden items when I need to use them, rehiding them when I'm done. This technically works, but it's super tedious

**Additional context**
I have no idea if it's even remotely feasible to basically just copy-paste in the stock menu's reorganization functionality, but if it is possible, that would probably make this super easy. Sorry if that sounds really stupid to anyone who actually knows what they're doing with this

**Comment by spellboundtriangle** [comment]
> Currently I just hide all my mostly unused items and show hidden items when I need to use them, rehiding them when I'm done. This technically works, but it's super tedious

Using folders sounds like a simpler solution to that
Otherwise, I think #500 describes wym?

**Comment by DatHypnoboi** [comment]
> Otherwise, I think #500 describes wym?

Ah, that is what I was hoping for, I didn't see this one when I was searching for duplicates, thanks
