### ISSUE TITLE
Luma 13 broke external firm

### ISSUE THREAD

**Issue by Witop1** [DS-Homebrew/TWiLightMenu#2259]
New 3ds XL with cfw. All updated. Luma 13 with external firm on breaks Twilight menu and goes black

**Comment by Witop1** [comment]
They told me

Remove twibg.cxi from sd:/luma/sysmodules and you'll be fine

**Comment by TheUnknownCod3r** [comment]
Fixed in Luma 13.0.1, can be closed.
