### ISSUE TITLE
Wood / Ace Wood Theme

### ISSUE THREAD

**Issue by Weaky322** [DS-Homebrew/TWiLightMenu#2266]
My suggestion isn't related to a problem, just a suggestion. 

If it all possible, I think it would be cool to have a TWiLight Menu++ theme that resembles the Wood theme. Essentially, a file list on the bottom screen with the game icons, and a clock and/or calendar on the top screen. 

We have the R4 Original theme, however I think it'd be neat to include more flashcard themes. (Also I really like the Wood theme.)

**Comment by Wryyyong** [comment]
https://wiki.ds-homebrew.com/twilightmenu/faq?faq=where-is-the-acekardwood-ui-theme
> The Acekard (also called Wood UI) theme was removed due to its buggy behavior and causing SD card corruption. Please wait for a fix. Progress for the return of this theme can be found in [this PR](pull/1109).
