### ISSUE TITLE
add zip files compatibility

### ISSUE THREAD

**Issue by ExGuestCJ** [DS-Homebrew/TWiLightMenu#2270]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by ExGuestCJ** [comment]
why the hell the text didnt appear?

**Comment by Epicpkmn11** [comment]
Discussed before, too complicated to be worthwhile. If you need to save space I recommend you trim your roms.

**Comment by ExGuestCJ** [comment]
thanks for letting me know that it exists
