### ISSUE TITLE
White Screen On New 2DS XL

### ISSUE THREAD

**Issue by mzy1996** [DS-Homebrew/TWiLightMenu#2274]
### Discussed in https://github.com/DS-Homebrew/TWiLightMenu/discussions/2273

<div type='discussions-op-text'>

<sup>Originally posted by **mzy1996** August 17, 2023</sup>
I have an new 2DS XL with SanDisk 512GB MicroSD Card and Installed Fastboot3ds instead of B9S 1.4, but when I bootup TWiLightMenu it shows white screen even I close the WIFI in Home Menu Settings，What should I do to get into the menu and Play my favorite DS games?</div>

**Comment by NightScript370** [comment]
Hey, please use our Discord server for support like this, found in the Readme of the repo
