### ISSUE TITLE
3ds and n3dsxl modes

### ISSUE THREAD

**Issue by Trickygamers** [DS-Homebrew/TWiLightMenu#2286]
I saw a nds forwarder YANBF that lets me boot a nds game in 3ds mode and wondering if it is possible to add it it would allow for greater overclocking of the games like for the old 3ds would be able to be overclocked at 268MHz and n3dsxl would be clocked at 804MHz

**Comment by lifehackerhansol** [comment]
This isn't possible. YANBF still runs the game in DSi mode; the only 3DS part of it is the icon itself.

The DSi mode on 3DS family consoles also does not use the ARM11 CPU, it uses the ARM9 which remains clocked at 133mhz (same as a DSi). So such a thing isn't possible either.

**Comment by Trickygamers** [comment]
thanks I didn't know now I am curious if it would be somehow possible to get both the ARM9 and ARM11 CPU both running side by side both in 3ds mode and ds mode. I bet in a alternate reality it is doable.

**Comment by lifehackerhansol** [comment]
Sometimes hardware that is only accessible to the ARM11 can be passed through to the ARM9, though there hasn't really been work on that lately. Otherwise, you can't run actual code on the ARM11 while in DSi mode... well nothing relevant to nds-bootstrap anyway.
