### ISSUE TITLE
Randomized Pokemon Black 2 version freezes

### ISSUE THREAD

**Issue by Franky113311** [DS-Homebrew/TWiLightMenu#2292]
Dont know why but my Randomized Pokemon Black 2 version freezes when i want to see the summary of a pokemon. I tried on R4gold flashcard where it works fine and on desmume. only TM++ is not working and i have all latest updates installed and tried also another randomizer.

**Comment by RocketRobz** [comment]
- This is an nds-bootstrap issue, not a TWiLight Menu++ issue.
- To fix the freezes, you need to AP-patch the clean ROM using DS-Scene ROM Tool before randomizing it.

**Comment by Franky113311** [comment]
ok thanks for the help. but everytime after i use the randomizer the rom will gets from 500 mb to 300 mb. i think the randomizer dont like mygerman rom. Only not working on nds bootstraper and on my r4 (on my r4 i dont get exp now). 
Im really confused where to ask about this problem.

**Comment by Franky113311** [comment]
and i tried it now with this tool

**Comment by RocketRobz** [comment]
The size being smaller is not an issue, as unused padding is only removed.

**Comment by Franky113311** [comment]
but its weird that the german randomized rom is only not working on TWLM++ (NDS Bootstrapper) and on R4. on every other emulator i tested it on it worked fine. No freeze and I gained exp. 
I also tested the Rom on the 3dswith TWLM++ before i played randomized and it worked and same rom seems to break on R4 and NDSBootstrapper after randomizing
