### ISSUE TITLE
Pls update the emulators to an up to date ones pls

### ISSUE THREAD

**Issue by Rnzei** [DS-Homebrew/TWiLightMenu#2312]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RocketRobz** [comment]
Which emulators, specifically? Each TWLMenu++ release bundles up to date emulators.

**Comment by RocketRobz** [comment]
Closing, due to lack of response.
If you have any further questions, please join our Discord server.
