### ISSUE TITLE
Add custom splash screen

### ISSUE THREAD

**Issue by HSL0175** [DS-Homebrew/TWiLightMenu#2322]
I would like to keep this virtual boy splash screen I'm not a fan of the og DSi splash screen is there a way to make this splash screen permanent?
![IMG_20231109_092433162_HDR.jpg](https://github.com/DS-Homebrew/TWiLightMenu/assets/150366957/815ce00f-cd20-44d9-b748-151de9424b26)

**Comment by NightScript370** [comment]
Use the custom splash option with this as the GIF of choice: https://github.com/DS-Homebrew/TWiLightMenu/blob/master/title/nitrofiles/video/splash/virtualPain.gif
