### ISSUE TITLE
3D Boxart, and icons

### ISSUE THREAD

**Issue by andyrock922** [DS-Homebrew/TWiLightMenu#2333]
**Describe the solution you'd like**
have an option to make boxart 3d, 3d icons and make your own 3d model for the icon 

**Additional context**
![IMG_0516](https://github.com/DS-Homebrew/TWiLightMenu/assets/108361918/24c55c80-4025-45c9-a203-7467f6acb5bb)
![IMG_0515](https://github.com/DS-Homebrew/TWiLightMenu/assets/108361918/d3d39204-fe38-4a0f-8037-f941430ee612)

**Comment by andyrock922** [comment]
![IMG_0517](https://github.com/DS-Homebrew/TWiLightMenu/assets/108361918/48f542df-a8d1-4e9f-8283-839a606aa043)
Twilight menu boxart

**Comment by NightScript370** [comment]
Not enough resources.
