### ISSUE TITLE
IRDO-D75C.ips corrupted (white 2 apfix)

### ISSUE THREAD

**Issue by clbr** [DS-Homebrew/TWiLightMenu#2337]
The white 2 apfix patch seems to be corrupted. When I try to apply it with two separate tools, they both report that the IPS patch is corrupted. Other patches from this repo have applied fine, so seems specific to this patch.

**Comment by RocketRobz** [comment]
The patch is not meant to be applied with a patcher. It is only intended to be applied by nds-bootstrap.
If you want to use a patcher though, remove the `A9` byte from the end of the file using a hex editor, then decompress the arm9 binary in the ROM, and then apply the patch.
