### ISSUE TITLE
Big problem on pkmn black and white 2

### ISSUE THREAD

**Issue by Ametystrs** [DS-Homebrew/TWiLightMenu#2339]
When running pokemon black or white on a DSi the game is turning on 5 fps and the loading screens are like 10 seconds long each...

**Comment by RocketRobz** [comment]
You need to turn off C-Gear to fix the issue.

**Comment by HypnoLop** [comment]
> You need to turn off C-Gear to fix the issue.

Hey just wanted to add, I've also been experiencing the framerate drops (in Black 2 on a DSi XL running latest TWLmenu), and while turning off the C-gear does help, it does not completely solve the issue. Also, any wireless functions cause the issue, not just the C-gear. Running the game in DS mode does seem to help a lot, but no matter how I run the game or whether I have wireless functions enabled, I seem to get slight frame drops here and there at the very least. It's also something that only seems to happen on my DSi, and not my 3DS with TWLmenu? I'm not entirely sure, but I think the performance issues have been causing desyncs in wireless play with my friend who has a cart, so it's been pretty frustrating.

**Comment by RocketRobz** [comment]
> > You need to turn off C-Gear to fix the issue.
> 
> Hey just wanted to add, I've also been experiencing the framerate drops (in Black 2 on a DSi XL running latest TWLmenu), and while turning off the C-gear does help, it does not completely solve the issue. Also, any wireless functions cause the issue, not just the C-gear. Running the game in DS mode does seem to help a lot, but no matter how I run the game or whether I have wireless functions enabled, I seem to get slight frame drops here and there at the very least. It's also something that only seems to happen on my DSi, and not my 3DS with TWLmenu? I'm not entirely sure, but I think the performance issues have been causing desyncs in wireless play with my friend who has a cart, so it's been pretty frustrating.

DS mode allocates the DSi-specific memory as an LRU cache, which helps performance.
On 3DS, the extra debug RAM is allocated as an LRU cache (in addition to the existing cache in DS mode), which helps performance in DSi mode.
