### ISSUE TITLE
Can't launch Mario Kart DS Kiosk Demo USA Version

### ISSUE THREAD

**Issue by Alexis20000** [DS-Homebrew/TWiLightMenu#2357]
If you trying to Launch mario kart ds kiosk demo Usa Version = you are on a black screen

Settings:
Language: Default
Save Number: 0*
Run in: DSi mode
ARM9 CPU Speed: 133mhz (TWL)
VRAM Mode: DSi mode
Card Read DMA: Off
Asynch Card Read: Off
Bootstrap: Release

NDS-BootStrap is the default bootstrap
Console: DSi XL
My default language is french

**Comment by RocketRobz** [comment]
Please re-open the issue at the nds-bootstrap repo.
https://github.com/DS-Homebrew/nds-bootstrap/issues
