### ISSUE TITLE
exit gbarunner ?

### ISSUE THREAD

**Issue by rofl0r** [DS-Homebrew/TWiLightMenu#2361]
i can't seem to find a way to quit gbarunner, once it's launched. it'd be great to get back to the menu other than rebooting the device, which takes a lot of time to reload everything.

**Describe the solution you'd like**
add option "exit gbarunner" to gbarunner menu, which returns to twilightmenu or whatever app it's been launched from.

**Describe alternatives you've considered**
i considered opening this bug/feature report on gbarunner2 repo, but then it seems mostly unmaintained, and the README mentions gbarunner3 and some beta feature, and generally as gbarunner seems to be an integral part of twilight menu, it appeared that this is the most likely place to get help (in case there's a secret button combo) or a bugfix.

**Comment by Dartz150** [comment]
This feature request belongs to GBARunner3 repo, and is a planned feature yeah, it may come eventually. If you're using a DSi, note that this method compared to rebooting the console won't make a significant difference, since TwilightMenu++ takes some seconds to boot regardless how you launch it.

**Comment by rofl0r** [comment]
> since TwilightMenu++ takes some seconds to boot

indeed, this is pretty annoying tbh. it takes 8 seconds to start twilightmenu, whereas unlaunch appears immediately, and even supercard dsone eos boots up in one second. i suspect the main bottleneck is loading the theme and fancy skins from external files. it might also be worth looking into the dldi loader on EOS, maybe they patched some obvious flaw to make it faster.
anyone ever did some profiling on twl to find out what makes it so slow ?
