### ISSUE TITLE
Request Use MGBA imstead of GameYob

### ISSUE THREAD

**Issue by ScottNash042** [DS-Homebrew/TWiLightMenu#2363]
GameYob is not getting any updates over the years and there is so many bugs in games 
while MGBA is getting update frequently

**Comment by RocketRobz** [comment]
Not possible, as mGBA runs in 3DS mode and not DS(i) mode, which is what TWiLight Menu++ runs in.

**Comment by ScottNash042** [comment]
what about Gnuboy ???
https://github.com/rofl0r/gnuboy

**Comment by RocketRobz** [comment]
> what about Gnuboy ??? https://github.com/rofl0r/gnuboy

Does it work on 3DS and/or DS(i)? If not, then no.

**Comment by ScottNash042** [comment]
it should run on both by the looks of it

**Comment by ScottNash042** [comment]
@RocketRobz 
gnuboy should run on both

**Comment by SNBeast** [comment]
> @RocketRobz gnuboy should run on both

It does not have a build target for the DS. If you can port it and demonstrate that it is indeed better than GameYob on DS, then this consideration can be practical.

**Comment by NightScript370** [comment]
>  there is so many bugs in games
Please make issues in our [github repo](https://github.com/ds-homebrew/gameyob)

**Comment by ScottNash042** [comment]
@NightScript370 
you can log any issues on that site ????
