### ISSUE TITLE
Support for EZ-Flash Parallel

### ISSUE THREAD

**Issue by jamieshaw** [DS-Homebrew/TWiLightMenu#2371]
**Is your feature request related to a problem? Please describe.**
Nope. New feature/enchancement.

**Describe the solution you'd like**
Support for booting from the new EZ-Flash Parallel flashcard, which I believe is a R4iLS clone.

**Describe alternatives you've considered**
Nothing at present, have bought to replace existing no-name R4 clone.

**Additional context**
Requires EZ-Flash Parallel hardware for development/debugging, but is now available on AliExpress with English kernel available on ezflash.cn

**Comment by lifehackerhansol** [comment]
It already supports it... is what I would have said, but I had to remove it soon after because nds-bootstrap on EZ-Flash is corrupting saves.

So I suppose this can be open until said corruption is fixed somehow.

**Comment by jamieshaw** [comment]
> It already supports it... is what I would have said, but I had to remove it soon after because nds-bootstrap on EZ-Flash is corrupting saves.
> 
> 
> 
> So I suppose this can be open until said corruption is fixed somehow.

I assumed as much but didn't have the stones to attempt renaming the R4iLs files to see what happens in fear or borking the card 😅

Would rather wait until someone gives me the thumbs up with, as you mention, tweaks for appropriate support.

**Comment by lifehackerhansol** [comment]
The R4iLS is completely different from the EZ-Flash, it wouldn't have worked anyway.

**Comment by li-fstz** [comment]
> It already supports it... is what I would have said, but I had to remove it soon after because nds-bootstrap on EZ-Flash is corrupting saves.
> 
> So I suppose this can be open until said corruption is fixed somehow.

I only use BOOT.nds on EZ-Flash Parallel, it's work, is that may cause the saves issus?

**Comment by lifehackerhansol** [comment]
EZ-Flash's stock driver has issues that break homebrew compatibility in some cases (it doesn't handle memory-unaligned writes), and this is known to break nds-bootstrap (like games don't even boot. Several people reported the same thing.)

So I wrote my own driver that fixes that issue, but now it's corrupting saves. Trying to figure out *what* exactly is causing said corruption is proving to be quite annoying, though.

**Comment by DroidlyMobile** [comment]
You have to manually boot TWilight Menu with the EZ Flash cards right now there's a guide on YouTube by mobile gaming that shows this and I haven't had issues with mine just sucks no autoboot yet.

**Comment by Dipstick8462** [comment]
any updates? im new to all of this srry

**Comment by RocketRobz** [comment]
> any updates? im new to all of this srry

No updates, sadly. Likely difficult to write a DLDI driver that properly works around the corruption issues.

**Comment by RocketRobz** [comment]
Fixed by this commit: https://github.com/DS-Homebrew/DLDI/commit/a0ce9960becddedb0a559380df4796b1b5cc1825
