### ISSUE TITLE
Gb/C massive crashing

### ISSUE THREAD

**Issue by Elmagob99** [DS-Homebrew/TWiLightMenu#2382]
Hello, since upgrading the TM to the latest version 26.8, i got A LOT of issues emulating my gb games and gbc as well, i thought the rooms were bad so i tried to change them and got the same results.I tried to downgrade to 26.7 and i had some crashes still, i went to the 26.6 and had zero issues, the thing is that the 26.6 has a pretty outdated boostrap version , so i downloaded the lastest (1.4) and replaced them on the 26.6 version which has the 1.2.2, i wanted to report this because idk if its a bug or what

![156692381-e40e07dc-43ba-4cec-b11f-ab40f9bf946a](https://github.com/DS-Homebrew/TWiLightMenu/assets/104046438/4ffd478a-b80e-4d3e-8c9f-9b1c58408e3a)

**Comment by RocketRobz** [comment]
I can still run those games on my side. Is Unlaunch installed?

**Comment by Elmagob99** [comment]
> I can still run those games on my side. Is Unlaunch installed?

i have to install unlaunch everytime i update the TM?

**Comment by RocketRobz** [comment]
> i have to install unlaunch everytime i update the TM?

No, you don't. You only install that once.

**Comment by Elmagob99** [comment]
> > i have to install unlaunch everytime i update the TM?
> 
> No, you don't. You only install that once.

im pretty sure its instaled,i saw the icon on the homescreen and out of curiosity i instelled it(i got my dsi second hand alredy hacked with TM)

**Comment by RocketRobz** [comment]
> im pretty sure its instaled,i saw the icon on the homescreen and out of curiosity i instelled it(i got my dsi second hand alredy hacked with TM)

So when you turn on the DSi, TWiLight Menu++ starts up?

**Comment by Elmagob99** [comment]
> > im pretty sure its instaled,i saw the icon on the homescreen and out of curiosity i instelled it(i got my dsi second hand alredy hacked with TM)
> 
> So when you turn on the DSi, TWiLight Menu++ starts up?

yes, when i got it it was on version 26.5, when i updated to 26.6 i had no issues emulating any of the consoles that TM offers(i tried them all) but with the last build cant play gb or gbc

**Comment by RocketRobz** [comment]
> yes, when i got it it was on version 26.5, when i updated to 26.6 i had no issues emulating any of the consoles that TM offers(i tried them all) but with the last build cant play gb or gbc

The only reason I can think of as to why the crash occurs is because of commit 89de04975, but again, I can still play those games.
Try re-installing TWiLight Menu++, as it's possible you have a corrupt installation:
1. https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
2. https://wiki.ds-homebrew.com/twilightmenu/installing-dsi

**Comment by Elmagob99** [comment]
> > yes, when i got it it was on version 26.5, when i updated to 26.6 i had no issues emulating any of the consoles that TM offers(i tried them all) but with the last build cant play gb or gbc
> 
> The only reason I can think of as to why the crash occurs is because of commit [89de049](https://github.com/DS-Homebrew/TWiLightMenu/commit/89de049753ace6f4cd9c5fab75a98f37e843a8e9), but again, I can still play those games. Try re-installing TWiLight Menu++, as it's possible you have a corrupt installation:
> 
>     1. https://wiki.ds-homebrew.com/twilightmenu/uninstalling-ds
> 
>     2. https://wiki.ds-homebrew.com/twilightmenu/installing-dsi

i can try reinstalling without formatting the sd? i have like 30gb of roms  lol

**Comment by RocketRobz** [comment]
> i can try reinstalling without formatting the sd? i have like 30gb of roms lol

Yes, you can. Just follow those guides in order.

**Comment by Elmagob99** [comment]
> > i can try reinstalling without formatting the sd? i have like 30gb of roms lol
> 
> Yes, you can. Just follow those guides in order.

for now i will say its fixed somehow lol, i will test a few more games but i can at least boot them and play, thanks for the MASSIVE work, thanks to you my second hand dsi its a whole retro emulation system with a 10hs battery life
