### ISSUE TITLE
The rotating cubes appear behind ALL  boxarts (again - 3DS theme)

### ISSUE THREAD

**Issue by SofyUchiha** [DS-Homebrew/TWiLightMenu#2387]
**TWiLight Menu++ Version:** v26.9.0: April Fools Release
**TWiLight Menu++ Theme:**  Nintendo 3DS (White) in  DSi XL and 3DS XL (both consoles)

### Expected behavior
Rotating cubes should disappear when the box art of any ROM appears.

### Actual behavior
The rotating cubes appear on the back of all covers, without exception.
PS: Photo & box art color de-band is off
I reported a similar problem some time ago, in #1367

### Steps to reproduce
1. Navigate through the list of games from left to right

### Notes
Attached is a (current) photo for clarity. Thanks!
**
![WhatsApp Image 2024-04-03 at 11 25 13 PM](https://github.com/DS-Homebrew/TWiLightMenu/assets/70182567/dc356e06-ec3b-45b0-b6e7-3b6b83501555)
**

**Comment by SofyUchiha** [comment]
Problem persists in the latest version: v27.1.2 (hotfix) 😞

**Comment by RocketRobz** [comment]
> Problem persists in the latest version: v27.1.2 (hotfix) 😞

Did you update straight from v26.9.0, or did you try any other versions between that and the latest?

**Comment by SofyUchiha** [comment]
> Did you update straight from v26.9.0, or did you try any other versions between that and the latest?

I upgraded directly from v26.9.0. I was a few days without my console due to health problems, so I didn't have a chance to test the versions in between.

**Comment by SofyUchiha** [comment]
Problem persists in the latest version: v27.3.2 (hotfix #2)....
Are there any settings I should apply to fix it? I'm already starting to suspect that I'm doing something wrong....
Sorry for the inconvenience, but I am reporting it again

**Comment by RocketRobz** [comment]
> Problem persists in the latest version: v27.3.2 (hotfix #2).... Are there any settings I should apply to fix it? I'm already starting to suspect that I'm doing something wrong.... Sorry for the inconvenience, but I am reporting it again

**Comment by RocketRobz** [comment]
> Problem persists in the latest version: v27.3.2 (hotfix #2).... Are there any settings I should apply to fix it? I'm already starting to suspect that I'm doing something wrong.... Sorry for the inconvenience, but I am reporting it again

Try turning off folders/directories.

**Comment by RocketRobz** [comment]
v27.3.3 should fix this bug once and for all. If the bug persists, then I'm out of ideas.

**Comment by SofyUchiha** [comment]
Unfortunately, the problem has not been resolved in either the DSi version or the 3DS version.
P.S.: I turned off the folders/directories to see if it fixed the problem on both consoles. It didn't work either :(

**Comment by RocketRobz** [comment]
So my prior fixes have not worked because it seems the box art clearing code got changed to no longer account for the rotating cubes for whatever reason.
I've added new code to properly clear the rotating cubes, and this time, I can confirm on my side that the fix works!
