### ISSUE TITLE
Add an option to load/store .savs from within same folder as ROM

### ISSUE THREAD

**Issue by milkcanworld** [DS-Homebrew/TWiLightMenu#2415]
**Is your feature request related to a problem? Please describe.**
If there were an option to load and stores save files within the same folder as the ROM, rather than in a saves subfolder, it would be easy to seamlessly move saves between DSes with and without TWiLightMenu. For example, many flashcart kernels just store the save with the ROM. So, I could put the AceKard kernel on my DSi microSD card, and if I wanted to use my Lite instead, I could just take my TWL DSi microSD card, plop it in to the AceKard, and be on my way.

**Describe the solution you'd like**
I'd like an option to be added to elect to load/store saves with the ROM rather than in a saves subfolder.

**Describe alternatives you've considered**
The current alternative is the status quo, which is where saves are just put in a subfolder in the folder the ROM is in and there is no toggle to change this to more "traditional" behavior.

**Additional context**
N/A

**Comment by edo9300** [comment]
This option has been added in 27.2.0
