### ISSUE TITLE
Add cursor support to top icons

### ISSUE THREAD

**Issue by RS55** [DS-Homebrew/TWiLightMenu#242]
I like how it looks now with the small 3DS style icons in both themes (DSi / 3DS), but even though I do not have the touch screen damaged, if you do not plan to do anything with the buttons up and down serious well received add support as it happens in 3DS with the browser, configuration, miiverse ... And not depend on the touch screen.

Edit: It would be nice to also add shortcuts to NES and GB / GBC directories next to these icons, making this the effect of changing pages but with the NES and GB / GBC games

**Comment by NightYoshi370** [comment]
Alright, so I'd like to give a little 2019 update for the DSi theme:

After a conversation on the TWL Mode Hacking Discord Server, we've made a conclusion to move the 4 buttons (Home Menu, Settings, Slot 1 card & GBARunner2) to a menu that can be activated by pressing SELECT. As such, there will no longer be buttons on the top and the window will be wider, making it more accurate to the DSi theme.
The up and down buttons are now used for reorganizing the icons, so they now have a purpose.

For the Official Nintendo 3DS Home Menu, however, the reorganizing of the app icons is done through touch only, and the up and down buttons are used to access the top menus. Therefore, I think this would now apply only for the 3DS theme.

> It would be nice to also add shortcuts to NES and GB / GBC directories next to these icons, making this the effect of changing pages but with the NES and GB / GBC games

Well, in the Discord server, I posted a suggestion of a filter view between all kind of different of different application titles so if that ever gets implemented, you can use that and dump all your roms into the same folder

**Comment by NightYoshi370** [comment]
Hey @Epicpkmn11, can you move apps by touching in TWiLightMenu++?

**Comment by Epicpkmn11** [comment]
Not currently, it would be a bit tricky, but probably not too hard to add

**Comment by NightYoshi370** [comment]
Well, once that's done, we could probably make the UP and DOWN buttons access the top icons, correct?

**Comment by Epicpkmn11** [comment]
the top icons have been removed in the DSi theme, but in the 3DS theme maybe we could do that

**Comment by NightYoshi370** [comment]
Right, that's what I meant. The UP and down would still be used for repositioning in the DSi theme

**Comment by NightYoshi370** [comment]
Let's use issue #749 since this should be included in the grander 3DS theme rework
