### ISSUE TITLE
Toggle Top/Bottom Screen Backlight Independently Request

### ISSUE THREAD

**Issue by radicalten** [DS-Homebrew/TWiLightMenu#2423]
Version: v27.3.3 (Final hotfix, hopefully)
Console: Original 3DS

Hello, is it possible to add the option to turn off the bottom screen or top screen backlight only (e.g. The top screen backlight is ON while the bottom screen backlight is OFF and vice versa)? This option would be perfect for playing DS games where the secondary screen is not used often and for emulators (such as GameYob) where only one screen is used for gameplay.  

**Describe the solution you'd like**
Preferably the option to toggle the top or bottom screen backlight could be included in the settings menu, or implemented through any other method that the author sees fit (such as inputting a button combination, or activating the option through a submenu before or after launching the game).  

**Describe alternatives you've considered**
Any information with how to achieve this would be appreciated. (For example, if independently disabling backlights is already possible in the current version, a short explanation of how to do that would be very helpful). 

**Additional context**
Thank you for creating and maintaining this project!

**Comment by RocketRobz** [comment]
Have you tried the Macro Mode setting?

**Comment by radicalten** [comment]
Yes sir, when utilizing the Macro Mode Setting, unfortunately the top screen backlight is still active. 

Is this not the expected behavior? (In other words, Macro Mode should disable the backlight.)

Additional Context: I am using the permanent brightness recalibration setting from CustomLuma3DS, which may or may not be interfering with the expected behavior of the Macro Mode option.

Thanks you for your response.

**Comment by RocketRobz** [comment]
> Yes sir, when utilizing the Macro Mode Setting, unfortunately the top screen backlight is still active.
> 
> Is this not the expected behavior? (In other words, Macro Mode should disable the backlight.)
> 
> Additional Context: I am using the permanent brightness recalibration setting from CustomLuma3DS, which may or may not be interfering with the expected behavior of the Macro Mode option.
> 
> Thank you for your response.

Backlight control does not work (for either of the screens) on 3DS/2DS consoles. It just turns the screen(s) black.

**Comment by radicalten** [comment]
Thank you, I will close this issue.
