### ISSUE TITLE
Boot from a DS game back to TwiLightMenu

### ISSUE THREAD

**Issue by Skyblu119** [DS-Homebrew/TWiLightMenu#2431]
Right now, switching games can be tedious. You have to exit out of the game, which puts you back in the 3ds menu. Then you have to re-open TwiLightMenu and pick another game. This is why I think that having the ability to go back to TwiLightMenu from a game would be amazing.

**Comment by NightScript370** [comment]
It's already implemented: go to the in-game menu and click the last option

**Comment by Skyblu119** [comment]
The “Quit Game” option just puts me back in the 3ds menu.

**Comment by XoTT29** [comment]
You can exit to the menu by pressing the L+D-pad Down+Select button. At the
very bottom there will be a button "exit to menu"

чт, 20 июн. 2024 г., 16:39 Skyblu119 ***@***.***>:

**Comment by Skyblu119** [comment]
![image](https://github.com/DS-Homebrew/TWiLightMenu/assets/173373613/7e717573-47e5-4e82-b106-0bc36c4b3a64)

**Comment by Skyblu119** [comment]
I don’t see it in that menu.
