### ISSUE TITLE
HiyaCFW autoboot not working on v27.5.1

### ISSUE THREAD

**Issue by FirebusMx** [DS-Homebrew/TWiLightMenu#2436]
Updated from v22 to 27.5.1, did not work, booting DSi menu instead; went back to v22 and it worked again.

**Comment by RocketRobz** [comment]
When it showed the DSi Menu, did it show TWiLight Menu++?

**Comment by FirebusMx** [comment]
> When it showed the DSi Menu, did it show TWiLight Menu++ as a launchable title?

Yes

**Comment by FirebusMx** [comment]
Tried reformatting the SD card, tried using another SD card, the only thing that worked was switching back to v22.

**Comment by RocketRobz** [comment]
After updating, delete the `autoboot.bin` (or w/e it's called) in `sd:/hiya/`, and re-set the `Default Launcher` setting to TWLMenu++ in TWLMenu++ Settings.

**Comment by FirebusMx** [comment]
It worked, thanks!

**Comment by FirebusMx** [comment]
> After updating, delete the `autoboot.bin` (or w/e it's called) in `sd:/hiya/`, and re-set the `Default Launcher` setting to TWLMenu++ in TWLMenu++ Settings.


It worked, thanks!
