### ISSUE TITLE
Help, when I apply a downloaded theme, it doesn't work and looks buggy

### ISSUE THREAD

**Issue by linfan18REAL** [DS-Homebrew/TWiLightMenu#2442]

**Comment by linfan18REAL** [comment]
![IMG_2024-07-14-16-12-14-070.jpg](https://github.com/user-attachments/assets/02aa6ea8-324c-47f4-bfdc-4e1519b526aa)

**Comment by NightScript370** [comment]
Which theme? What version of TWiLight?

**Comment by linfan18REAL** [comment]
The theme is cinnamoroll and the version is 0.38.0

**Comment by NightScript370** [comment]
Please update
