### ISSUE TITLE
Makefile included in the guide does not properly run and compile SFX into sfx.bin.

### ISSUE THREAD

**Issue by theshmunguss1** [DS-Homebrew/TWiLightMenu#2445]
### Expected behavior

The Windows command line should run the `make` command, and compile all correct sound effect WAVs into `sfx.bin`.
### Actual behavior

CMD gives an error message, and everything is unchanged.
### Steps to reproduce

1. Collect your sound effect WAVs, for mine, I used the Wii SFX. Make sure that `Makefile` is in the same directory.
2. Set the command prompt's CD to the directory holding the SFX and `Makefile`.
3. Run the command `make`, as seen at [https://wiki.ds-homebrew.com/twilightmenu/custom-dsi-3ds-sfx#sound-effect-bank](https://wiki.ds-homebrew.com/twilightmenu/custom-dsi-3ds-sfx#sound-effect-bank).

### Notes
 All my files are under 512 kb.

![image](https://github.com/user-attachments/assets/40916a94-bb76-4ab7-8698-4b023d683c79)

**Comment by Vickerinox** [comment]
you need to install ``make`` in order to use the ``make`` command
