### ISSUE TITLE
3ds whitescreen(Even in Nds Forwarder)

### ISSUE THREAD

**Issue by Oto-the-bastard** [DS-Homebrew/TWiLightMenu#2447]
Ok so,i think this is a problem of my console or idk because my 3ds new xl when i installed twilight menu dont work and i just get a white screen and i wait for hours,so i reinstall all and still dont working,i do all right and same,so i try nds forwarder,dont work too!so idk what happen with my console,is a used one with last versiok of luma

**Comment by RocketRobz** [comment]
Which brand is the SD card you're using?

**Comment by Oto-the-bastard** [comment]
ADATA 128 GB

**Comment by RocketRobz** [comment]
As said in the Discord server, please try a different SD card of a well-known brand, such as Kingston, Samsung, SanDisk, or Sony.
This is out of our scope to fix.

**Comment by Oto-the-bastard** [comment]
So that why that happen?even with ndsforwarder

**Comment by RocketRobz** [comment]
libfat (the SD library used by a majority of DS(i) homebrew, as well as TWLMenu++ and the forwarders) has trouble handling your SD card.

**Comment by Oto-the-bastard** [comment]
Ok ty,i gonna try buy a kingston
