### ISSUE TITLE
Twilight Menu++ doesn't let me change my theme

### ISSUE THREAD

**Issue by KenKaneki18** [DS-Homebrew/TWiLightMenu#2458]
**R4 Gold Pro from 2019** 
**New 3DS XL:** 

**TWiLight Menu++:** 
**TWiLight Menu++ Any added theme:** 

### Expected behavior

I should be able to change my theme

### Actual behavior

Can't change my theme and only Default theme shows up

### Steps to reproduce

1.
2.
3.

### Notes

I'm using Twilight Menu++ to run my R4 card. I just decided to change my theme and downloaded some from skins.ds-homebrew.com but they don't show up in the settings when I want to change my theme. I'm using the "normal" Twilight Menu++ version

Edit: For some reason not everything I wrote shows up. I wrote under expected behavior that Twilight Menu++ should let me change my theme and under actual behavior that Twilight Menu++ doesn't let me change it

**Comment by RocketRobz** [comment]
> Edit: For some reason not everything I wrote shows up. I wrote under expected behavior that Twilight Menu++ should let me change my theme and under actual behavior that Twilight Menu++ doesn't let me change it

That's because what's written is surrounded by `<!--` and `-->`. I've removed those.
Also, are you following this to use the downloaded skins?: https://wiki.ds-homebrew.com/twilightmenu/faq?faq=how-do-i-install-custom-themes-for-twilight-menu

**Comment by KenKaneki18** [comment]
> > Edit: For some reason not everything I wrote shows up. I wrote under expected behavior that Twilight Menu++ should let me change my theme and under actual behavior that Twilight Menu++ doesn't let me change it
> 
> That's because what's written is surrounded by `<!--` and `-->`. I've removed those. Also, are you following this to use the downloaded skins?: https://wiki.ds-homebrew.com/twilightmenu/faq?faq=how-do-i-install-custom-themes-for-twilight-menu

Yes I am and I followed the instructions

**Comment by RocketRobz** [comment]
> Yes I am and I followed the instructions

So in TWLMenu++ Settings, did you press the A button after pressing Left/Right to switch to the theme the skin is made for?
If so, you should see the skin you downloaded.

> Also do they have to be in the default folder or just in the themes folder as loose files?

Just in the `themes` folder, as the FAQ page says.

**Comment by KenKaneki18** [comment]
> > Yes I am and I followed the instructions
> 
> So in TWLMenu++ Settings, did you press the A button after pressing Left/Right to switch to the theme the skin is made for? If so, you should see the skin you downloaded.
> 
> > Also do they have to be in the default folder or just in the themes folder as loose files?
> 
> Just in the `themes` folder, as the FAQ page says.

I did that but it won't let me change it

**Comment by RocketRobz** [comment]
Resolved in the Discord server.

**Comment by KenKaneki18** [comment]
> Resolved in the Discord server.

Thanks again for helping me solve this issue
