### ISSUE TITLE
Flipnote on DS Lite, is it possible rn?

### ISSUE THREAD

**Issue by MaymonAdir** [DS-Homebrew/TWiLightMenu#2466]
It says: "For use with Nintendo DSi systems only. Cannot be used with Nintendo DS/DS Lite Systems."

What should I do?

**Comment by RocketRobz** [comment]
No, it is not possible.

**Comment by MaymonAdir** [comment]
Hold up for a moment, Animanatee is the 2nd option, You can close this issue properly
