### ISSUE TITLE
No sound with Slot-1 card

### ISSUE THREAD

**Issue by InsanePrimate** [DS-Homebrew/TWiLightMenu#2471]
System: New 3ds (non-XL) Dual IPS Screen (PAL Region)
Firmware: Sys 11.16.0-49E Luma3DS v13.1.2
TWiLightMenu v27.8.0
NDS-Bootstrap v2.0.0
System SD: SanDisk 256 gb Ultra Plus formatted to Fat32, cluster size 64kb
Flashcard: RTS R4i Plus (www.r4ids.cn)
Flashcard SD: SanDisk 64 gb Ultra Plus formatted to Fat32, cluster size 64kb

After installing the newest version (I did a completely fresh install, because I thought at first that I messed something up when updating) When using TWiLightMenu with the settings below there is NO SOUND whatsoever (not in game selection, not in menu and not in game). This is a first for me. I was using these settings since they became available and never had this problem before. There is sound when using either the Flashcard OR the TWiLightMenu on the 3DS System, but not when using the Settings shown below.

**TWiLightMenu (3DS) settings**

_GUI settings_
Language: System (German) 
Theme: Nintendo DSi (dark)
DS Classic Menu on startup: No
DSi/Saturn: SELECT: SELECT Menu*
DSi/3DS Theme Music: Theme
Settings Music: Theme
Font: Press A
Use skin font: Yes
DS Classic Menu font: Default
Show empty boxes: Hide*
Sort Method: Alphabetical
TWLMenu++ Splash Screen: Hide*
Splash Jingle Length: Short
Rocked Robz Logo: Hide*
DSi Splash Screen: Without H&S
DSi Splash Auto-skip: Off
Nintendo Logo Color: Gray*
Directories/Folders: Show
Show hidden files: Hide
Top screen photo: Show
Box art/Game covers: Non-cached
Photo & box art color de-band: Off
Refer to the SD as: microSD Card*
Clock system: 24 hours*
Animated DSi icons: Yes
Custom icons: On
Animation on highlight: Zoom
Logging: Off

_nds-bootstrap settings_
Game Language:  System (German) 
Game Title Language:  System (German) 
Game Region:  System (German) 
Use ROM Region: Yes
Save Location: "saves" folder
ESRB Rating Screen: Off
Menu hotkey: press A
Sound/Mic Frequency: 47.61 kHz*
Photo Location: SD Card
Force sleep mode patch: Off
Load Bootloader: Direct*
Bootstrap: Release
Debug: Off
Logging Off

_GBARunner2 settings_
DS main memory i-cache: on
WRAM i-cache: on
BIOS intro: On
Display Screen: Top
Border frame: On
Center and mask: On
Simulate GBA colors: No

_Games and Apps settings_
ColecoVision emulator: ColecoDS
Sega MD/Gen emulator: Hybrid
Sega SG/SC emulator: ColecoDS
Amstrad CPC emulator: AmEDS
Run FluBBa emus. in: DSi mode
Slot-1 Launch Method: Direct

_Misc. settings_
Color Mode: Press A
SCFG access in Slot-1: On*
SD access in Slot-1: On*
Slot-1: Touch Mode: DSi mode*
Slot-1 microSD access: On*
Auto-start Slot-1: Yes*
Prevent ROM hiding and deletion: Yes*
Update Recently Played list: No* (could use some shortening in German to not have the fonts overlap when choosing "nein")
WiFi: Off*
Macro Mode: Off
Limited Mode: Off
SysNAND Region
Set Luma Autoboot: Press A

**TWiLightMenu (Flash Card) settings**

_GUI settings_
Language: System (German) 
Theme: Nintendo DSi (dark)
DS Classic Menu on startup: No
DSi/Saturn: SELECT: SELECT Menu*
DSi/3DS Theme Music: Theme
Settings Music: Theme
Font: Press A
Use skin font: Yes
DS Classic Menu font: Default
Show empty boxes: Hide*
Sort Method: Alphabetical
TWLMenu++ Splash Screen: Hide*
Splash Jingle Length: Short
Rocked Robz Logo: Hide*
DSi Splash Screen:  Hide*
DSi Splash Auto-skip: Off
Nintendo Logo Color: Gray*
Directories/Folders: Show
Show hidden files: Hide
Top screen photo: Show
Box art/Game covers: Show
Clock system: 24 hours*
Animated DSi icons: Yes
Custom icons: On
Animation on highlight: Zoom
Logging: Off

_nds-bootstrap settings_
Game Language:  System (German) 
Game Title Language:  System (German) 
Game Region:  Europe
Use ROM Region: Yes
Save Location: "saves" folder
ESRB Rating Screen: Off
Menu hotkey: press A
Sound/Mic Frequency: 47.61 kHz*
Bootstrap: Release
Debug: Off
Logging Off

_GBARunner2 settings_
DLDI access: ARM9
DS main memory i-cache: on
WRAM i-cache: on
BIOS intro: On
Display Screen: Top
Border frame: On
Center and mask: On
Simulate GBA colors: No

_Games and Apps settings_
Game Loader: Kernel (R4i Gold Wood Kernel v1.64)
ColecoVision emulator: ColecoDS
Sega MD/Gen emulator: Hybrid
Sega SG/SC emulator: ColecoDS
Amstrad CPC emulator: AmEDS

_Misc. settings_
Color Mode: Press A
Prevent ROM hiding and deletion: Yes*
Update Recently Played list: No* (could use some shortening in German to not have the fonts overlap when choosing "nein")
Macro Mode: Off

**Comment by RocketRobz** [comment]
You need to switch the `Slot-1: Touch Mode` setting back to `DS mode`, unless you plan on using TWLMenu++ to access both SD and flashcard contents.

**Comment by InsanePrimate** [comment]
Did as you said... still no sound! Thanks anyway, gonna have to roll back it seems.

**Comment by InsanePrimate** [comment]
I did a complete new install.. as i said. I thought i messed it up so i wiped an did a clean install.

**Comment by RocketRobz** [comment]
I tried on DSi, and sound still worked with DS touch mode, but not with DSi touch mode.
On 3DS though, both of the modes did not have sound playing. Hopefully it'll be fixed in the next version.

**Comment by InsanePrimate** [comment]
Thanks for all the hard work!

**Comment by RocketRobz** [comment]
Fixed by 824c74344 for TWLMenu++, and [09ea7d38](https://github.com/DS-Homebrew/nds-bootstrap/commit/09ea7d386add8732d8897988508acdd527430614) for nds-bootstrap

**Comment by InsanePrimate** [comment]
Cool. thank you!
