### ISSUE TITLE
Twilight top splash screen bug

### ISSUE THREAD

**Issue by xyzoxyz** [DS-Homebrew/TWiLightMenu#2472]
**Base Console:** Dsi  v1.4u

**TWiLight Menu++ Version:** v27.7.1
**TWiLight Menu++ Theme:** Nintendo DSi

### Expected behavior

Should display classic top splash screen

### Actual behavior

Displays bugged top splash screen

### Steps to reproduce
 Unsure

### Notes

I powered on the console holding volume down button and when it booted it displayed the bugged splash screen, I tried on another console and it did not get this bug, uninstalled and reinstalled twilight menu and its still there
![IMG_0189](https://github.com/user-attachments/assets/13cf7702-8a01-4e65-8100-46daf11a01bb)

**Comment by RocketRobz** [comment]
This is not a bug. Also, if the other console doesn't show this, then the date isn't set correctly on it.

**Comment by xyzoxyz** [comment]
Much love thank you❤️
