### ISSUE TITLE
Twilight menu doesn't work at all.

### ISSUE THREAD

**Issue by SlvinoALT** [DS-Homebrew/TWiLightMenu#2477]
Im using
O3DS Sys 11.17.0-50E
I'm using the latest twilight menu release V27.10.0
I'm on the latest luma version V13.2.1.

https://github.com/user-attachments/assets/0e27397b-9a03-40c9-b6e7-d757a362bf0e
A video showing what happens ^

My issue is that whenever I try and load up twilight menu, it decides to black screen with this at the bottom:
An error occurred (ErrDisp)
Error type: generic
Proccess ID: 19
Proccess name: am
Process title ID: 0004013000001502

Address: 0x001093aa
Error code: 0xc8804478

Press any button to reboot.

I've tried everything I could find about it, I saw someone had the problem with the error thing but that issue was in 2021, I honestly dont know what the do. 
I've tried reinstalling different releases of twilight menu and all of them show the exact error thing.
I've reinstalled the current twilight menu version about 5 times and still the same thing.
I really REALLY need help on this cause I do not know what I'm doing wrong.

Edit: (If you do reply, I will reply on my actual account since I've found it.)

**Comment by RocketRobz** [comment]
Please follow the DS/DSi functionality steps in this page here: https://3ds.hacks.guide/troubleshooting#software-issues-on-consoles-with-custom-firmware

**Comment by Slvino** [comment]
UPDATE: I had forgotten to turn off pretendo 😅

**Comment by Slvino** [comment]
It works now! Thank you so much, I don't get how I missed that part when I first tried it.
