### ISSUE TITLE
DSi menu music doesn't play when i select ''Launcher'' in the Nocash Unlaunch.dsi v2.0

### ISSUE THREAD

**Issue by D-Tapia11** [DS-Homebrew/TWiLightMenu#2482]
So everytime i boot up my DSi and i want to do something in the actual DSi menu i hold the A button to open Unlaunch and i click on ''Launcher'' but ever since i updated the TWiLightMenu++ from v27.6.0 to v27.7.0 it doesn't play the DSi menu music anymore for some reason.

**Comment by RocketRobz** [comment]
Make sure the `Launcher Patches` setting is set to `Default` in the Unlaunch page of TWLMenu++ Settings.
After that, launch the Unlaunch installer using TWLMenu++, then select `Install Now`.

**Comment by D-Tapia11** [comment]
Yeah i did all that, it worked thanks man!
