### ISSUE TITLE
Nds ap-patch

### ISSUE THREAD

**Issue by BigBoss320** [DS-Homebrew/TWiLightMenu#286]
Hello. How can I ap-patch a game? I can't find any patch on the internet.

**Comment by BigBoss320** [comment]
OK. I will see when I have my computer! Thanks again.

**Comment by dubbz82** [comment]
If you have any further issues with this, please open an issue on nds-bootstrap.  This should be used ONLY for issues with the menu itself.  Bootstrap is where problems with roms should be reported.
