### ISSUE TITLE
Long publisher names are drawn outside of the "current game" panel 

### ISSUE THREAD

**Issue by gingerbeardman** [DS-Homebrew/TWiLightMenu#310]
![GitHawk Upload by gingerbeardman](https://i.imgur.com/P47cing.jpg)

**Comment by RocketRobz** [comment]
A slimmer font would have to be used to fix that issue.
There doesn't seem to be a ripped font image of the original though.

**Comment by NightYoshi370** [comment]
https://www.dafont.com/img/charmap/n/i/nintendo_ds_bios0.png
I found this

**Comment by NightYoshi370** [comment]
@RocketRobz now that we found a ripped image font of the slimmer font, can we implement it? Or is it more complex than that?

**Comment by NightYoshi370** [comment]
I'd like to also add that this issue also affects the R4 theme as well as the DSi theme. I think showing the extention for nes/gameboy games should be turned off for starters

**Comment by chyyran** [comment]
Even the smallest DSi Font is too thick for this.. maybe if we can get the DS BIOS font somehow...

**Comment by gingerbeardman** [comment]
What format does the font need to be in?

https://fontstruct.com/fontstructions/show/1084085/nds_true_bios

**Comment by gingerbeardman** [comment]
I've taken the liberty of converting the above font to BDF format.

[NDS-true-bios-16.bdf.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/3116130/NDS-true-bios-16.bdf.zip)

You can generate PNG/BMP/etc from the TTF or BDF

**Comment by gingerbeardman** [comment]
here is a PNG 
![pc](https://user-images.githubusercontent.com/49612/61878044-28b35d80-aee8-11e9-8d9c-b1d90f3c3abc.png)

**Comment by gingerbeardman** [comment]
Any further thoughts?

**Comment by Nomelas** [comment]
what about scrolling text instead.

**Comment by NightYoshi370** [comment]
Why scroll when we could be accurate?
@gingerbeardman I told people in the Discord server about the issue. Hopefully someone takes your work and adds it in

**Comment by NightYoshi370** [comment]
[1:20 PM] Evie11 (TWL-EVIE-USA): Ah, I'll try switching it to that when I get home in a couple hours. bdf seems to be a really simple plain text format so we can also get the kernings from that font really easily

Good news

**Comment by gingerbeardman** [comment]
Boom! Thanks
