### ISSUE TITLE
Add per-game debugging option? 

### ISSUE THREAD

**Issue by MrMcTiller** [DS-Homebrew/TWiLightMenu#393]
Is there a possibility to add a per-game setting to turn on and off debugging?

**Comment by RocketRobz** [comment]
Why?

**Comment by MrMcTiller** [comment]
> 
> 
> Why?

I was just thinking that maybe you might want to debug one game, but not another.

**Comment by FlameAlt53** [comment]
Would this be difficult if not, why not add it so we can close the issue?

**Comment by FlameKat53** [comment]
this issue has been around for a while with no fix commit, but is it really nessecary?

**Comment by chyyran** [comment]
closing due to stale issue
