### ISSUE TITLE
3DS Sleep Mode interaction bug

### ISSUE THREAD

**Issue by ChampionLeake** [DS-Homebrew/TWiLightMenu#426]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[Version 7.4.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

After exiting sleep-mode, the interface shouldn't move or navigate to areas the user didn't perform. 

### Actual behaviour

After exiting sleep-mode, you'll possibly be hovering over something else in the main menu

### Steps to reproduce

1. Put the 3DS in sleep mode for about 2-3 seconds
2. Open it and sometimes you'll navigate to somewhere else

### Additional Details
This seems to occur on the following themes:
* DSi
* 3DS
* R4

**Comment by FlameKat53** [comment]
not just a random place, but left or up in the DSi/3DS theme (idk in the R4 theme) this happens for me as well

**Comment by NightYoshi370** [comment]
Thank you for giving us the details we need. Although, are you positive that this does not occur in the akmenu theme?

**Comment by FlameKat53** [comment]
Oh, also this only happens on my 3DS consoles (3DS small, 3DS XL, n3DS small)

**Comment by ChampionLeake** [comment]
@NightYoshi370 I tested the akmenu on sleep mode for about 10 seconds and I didn't get anything wrong with it. Is there a specific theme for akmenu?

**Comment by NightYoshi370** [comment]
Nah, most of the themes are the same. Although, you said you tested 3 minutes for DSi/3DS and R4? Can you try 3 minutes for akmenu as well?

I want to see if it's an issue of inconsistency, as there are many inconsistencies between the akmenu theme and the DSi/3DS & R4 themes

**Comment by ChampionLeake** [comment]
akmenu seems to be fine. I set my sleep mode for about 5 minutes ans checked constantly. 

DSi/3DS and R4 seem to be the only ones I get the bug to occur 100% of the time.

**Comment by NightYoshi370** [comment]
This doesn't occur for me on the latest version on an Old3DS. I'll be closing this but if someone else can replicate it, please let me know
