### ISSUE TITLE
DSi games cannot be launched from slot-1

### ISSUE THREAD

**Issue by TheCoder3156** [DS-Homebrew/TWiLightMenu#435]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  New 3DS/2DS (XL)
- [ ]  Old 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch v1.7 and HyiaCFW v.1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v7.4.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

TWiLightMenu should launch the game cart.

### Actual behaviour

A white screen

### Steps to reproduce

1. Open TWiLightMenu from the original homemenu
2. Launch a slot-1 game (only some fail)

**Comment by NightYoshi370** [comment]
Can you give an example of games that do not work?

**Comment by TheCoder3156** [comment]
Not working:
Pokémon Black 2
Pokémon Black
Pokémon White
Phineas and Ferb Ride Again
LEGO Battles Ninjago

Working:
LEGO Battles
LEGO Star Wars The Complete Saga
Mario Party DS
Pokémon Platinum
New Super Mario Bros

These are all the games I own and can test. All of the non working are TWL cartridges with the exception of LEGO Battles Ninjago. I think it might be a TWL thing with the Ninjago being it's own issue.

**Comment by RS55** [comment]
I can confirm that, the TWL cartridges do not start with Twilightmenu and for adding something, neither from unlaunch 1.8 but it is already separate.
