### ISSUE TITLE
Changing configuration settings crashes TWiLightMenu

### ISSUE THREAD

**Issue by margaro95** [DS-Homebrew/TWiLightMenu#438]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v7.4.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

TWiLightMenu should launch with the specified settings.ini file

### Actual behaviour

The booting of TWiLightMenu shows a loading animation that crashes at the end and can´t load TWiLight.

### Steps to reproduce

1. Just copy and paste this settings.ini content in the file located at your sd:\\_nds\TWiLightMenu.
Probably it was not just this config file, but also the one located at sd:\\_nds\ thats called nds-bootstrap.ini

    [nds-bootstrap.ini.txt](https://github.com/RocketRobz/TWiLightMenu/files/2889260/nds-bootstrap.ini.txt)

    [settings.ini.txt](https://github.com/RocketRobz/TWiLightMenu/files/2889167/settings.ini.txt)

2. I manually changed this config files in my Old 2Ds by clicking in the button thats located at the bottom of the home page of TWiLight (below the GBArunner).

I cannot change back these settings because I can't access the config files via the 2DS. Could anyone please copy and paste the original config files so that I can go back to when it worked?

**Comment by margaro95** [comment]
Ok. This is maybe not the solution for the bug, but I found a way to fix it. Just delete both of your ini files and the TWiLight will reboot as out of the box.

The variables that I changed to make the bug happen where:
- settings.ini
    > autorungame = 1 (the one functioning is set to 0)
    > showlogo = 0 (functioning is set to 1)
    > theme = 1 (functioning is set to 0)
    > show_12oclock = 0 (functioning is set to 1)
    > Boost_vram = 1 (functioning is set to 0)
- nds-bootstrap.ini
    No changes

**Comment by NightYoshi370** [comment]
@RocketRobz shouldn't it check for these types of things?

**Comment by RocketRobz** [comment]
@margaro95 Did you launch a ROM before turning on `autorungame`?

**Comment by margaro95** [comment]
Yes, I did. I launched Tales of phantasia and then tried to change some of the settings just to try. I closed Twilight and on reopening, error.

**Comment by NightYoshi370** [comment]
Does this happen on the latest nightly?

**Comment by margaro95** [comment]
I'll check as soon as I can

**Comment by NightYoshi370** [comment]
According to Flame on the Discord Server, this no longer crashes
