### ISSUE TITLE
NeoGeo emulation using NeoDS and RAM disks

### ISSUE THREAD

**Issue by NightYoshi370** [DS-Homebrew/TWiLightMenu#457]
Hey, I think it'd be cool if we can add support for displaying NeoGeo games in TWiLightMenu++. It will require a RAM Disk but I don't see why it shouldn't be possible.

**Comment by artsyca** [comment]
I've been using NeoDS off my flashcart it works remarkably well 
How does it need a RAM Disk if I may ask?

**Comment by RocketRobz** [comment]
nds-bootstrap doesn't patch NeoDS properly, I believe.

**Comment by NightYoshi370** [comment]
We'll use #902 instead, since it includes builds and stuff
