### ISSUE TITLE
Add Chinese Font for iQue games to properly show their titles

### ISSUE THREAD

**Issue by FlameKat53** [DS-Homebrew/TWiLightMenu#509]
Add Chinese Font to TWiLight Menu++ for iQue DS games to properly show their names. (Extension of Title)

Currently, iQue DS games show their names with a single Japanese character, or have no name at all.

Here are all the pictures

![image](https://cdn.discordapp.com/attachments/283770736215195648/557715951814967316/image0.jpg)

![2](https://cdn.discordapp.com/attachments/283770736215195648/557716056265719813/image0.jpg)

![3](https://cdn.discordapp.com/attachments/283770736215195648/557716164671700993/image0.jpg)

![4](https://cdn.discordapp.com/attachments/283770736215195648/557716276236255272/image0.jpg)

![5](https://cdn.discordapp.com/attachments/283770736215195648/557716445845389312/image0.jpg)

![6](https://cdn.discordapp.com/attachments/283770736215195648/557716505392054289/image0.jpg)

**Comment by chyyran** [comment]
I need a list of all the titles in Chinese, could you grab them from DSLazy for me?

**Comment by chyyran** [comment]
List of all potentially used codepoints
```
'一' 0x4e00 '一' 0x4e00
'中' 0x4e2d '中' 0x4e2d
'任' 0x4efb '任' 0x4efb
'兄' 0x5144 '兄' 0x5144
'力' 0x529b '力' 0x529b
'天' 0x5929 '天' 0x5929
'弟' 0x5f1f '弟' 0x5f1f
'感' 0x611f '感' 0x611f
'摸' 0x6478 '摸' 0x6478
'欧' 0x6b27 '歐' 0x6b50 *
'步' 0x6b65 '步' 0x6b65
'漫' 0x6f2b '漫' 0x6f2b
'狗' 0x72d7 '狗' 0x72d7
'瓦' 0x74e6 '瓦' 0x74e6
'直' 0x76f4 '直' 0x76f4
'神' 0x795e '神' 0x795e
'笔' 0x7b14 '筆' 0x7b46 *
'级' 0x7ea7 '級' 0x7d1a *
'耀' 0x8000 '耀' 0x8000
'制' 0x5236 '製' 0x88fd *
'西' 0x897f '西' 0x897f
'超' 0x8d85 '超' 0x8d85
'造' 0x9020 '造' 0x9020
'游' 0x6e38 '遊' 0x904a *
'云' 0x4e91 '雲' 0x96f2 *
'马' 0x9a6c '馬' 0x99ac *
```

**Comment by chyyran** [comment]
The large font is `TBF1_banner_lm`, not `TBF1_l`, extracted from the launcher SRL and not TWLFontTable.

**Comment by chyyran** [comment]
TBF1_banner_lm contains the following CJK glyphs

```xml
<CharInfo Char="上" Code="19978" Hex="4e0a" Index="397" Width="14" />
  <CharInfo Char="下" Code="19979" Hex="4e0b" Index="398" Width="14" />
  <CharInfo Char="了" Code="20102" Hex="4e86" Index="399" Width="14" />
  <CharInfo Char="今" Code="20170" Hex="4eca" Index="400" Width="14" />
  <CharInfo Char="他" Code="20182" Hex="4ed6" Index="401" Width="14" />
  <CharInfo Char="付" Code="20184" Hex="4ed8" Index="402" Width="14" />
  <CharInfo Char="以" Code="20197" Hex="4ee5" Index="403" Width="14" />
  <CharInfo Char="位" Code="20301" Hex="4f4d" Index="404" Width="14" />
  <CharInfo Char="体" Code="20307" Hex="4f53" Index="405" Width="14" />
  <CharInfo Char="何" Code="20309" Hex="4f55" Index="406" Width="14" />
  <CharInfo Char="使" Code="20351" Hex="4f7f" Index="407" Width="14" />
  <CharInfo Char="保" Code="20445" Hex="4fdd" Index="408" Width="14" />
  <CharInfo Char="信" Code="20449" Hex="4fe1" Index="409" Width="14" />
  <CharInfo Char="健" Code="20581" Hex="5065" Index="410" Width="14" />
  <CharInfo Char="入" Code="20837" Hex="5165" Index="411" Width="14" />
  <CharInfo Char="全" Code="20840" Hex="5168" Index="412" Width="14" />
  <CharInfo Char="内" Code="20869" Hex="5185" Index="413" Width="14" />
  <CharInfo Char="分" Code="20998" Hex="5206" Index="414" Width="14" />
  <CharInfo Char="切" Code="20999" Hex="5207" Index="415" Width="14" />
  <CharInfo Char="初" Code="21021" Hex="521d" Index="416" Width="14" />
  <CharInfo Char="刻" Code="21051" Hex="523b" Index="417" Width="14" />
  <CharInfo Char="前" Code="21069" Hex="524d" Index="418" Width="14" />
  <CharInfo Char="力" Code="21147" Hex="529b" Index="419" Width="14" />
  <CharInfo Char="加" Code="21152" Hex="52a0" Index="420" Width="14" />
  <CharInfo Char="動" Code="21205" Hex="52d5" Index="421" Width="14" />
  <CharInfo Char="去" Code="21435" Hex="53bb" Index="422" Width="14" />
  <CharInfo Char="参" Code="21442" Hex="53c2" Index="423" Width="14" />
  <CharInfo Char="取" Code="21462" Hex="53d6" Index="424" Width="14" />
  <CharInfo Char="合" Code="21512" Hex="5408" Index="425" Width="14" />
  <CharInfo Char="名" Code="21517" Hex="540d" Index="426" Width="14" />
  <CharInfo Char="員" Code="21729" Hex="54e1" Index="427" Width="14" />
  <CharInfo Char="在" Code="22312" Hex="5728" Index="428" Width="14" />
  <CharInfo Char="報" Code="22577" Hex="5831" Index="429" Width="14" />
  <CharInfo Char="外" Code="22806" Hex="5916" Index="430" Width="14" />
  <CharInfo Char="大" Code="22823" Hex="5927" Index="431" Width="14" />
  <CharInfo Char="好" Code="22909" Hex="597d" Index="432" Width="14" />
  <CharInfo Char="始" Code="22987" Hex="59cb" Index="433" Width="14" />
  <CharInfo Char="存" Code="23384" Hex="5b58" Index="434" Width="14" />
  <CharInfo Char="安" Code="23433" Hex="5b89" Index="435" Width="14" />
  <CharInfo Char="完" Code="23436" Hex="5b8c" Index="436" Width="14" />
  <CharInfo Char="定" Code="23450" Hex="5b9a" Index="437" Width="14" />
  <CharInfo Char="室" Code="23460" Hex="5ba4" Index="438" Width="14" />
  <CharInfo Char="容" Code="23481" Hex="5bb9" Index="439" Width="14" />
  <CharInfo Char="差" Code="24046" Hex="5dee" Index="440" Width="14" />
  <CharInfo Char="年" Code="24180" Hex="5e74" Index="441" Width="14" />
  <CharInfo Char="度" Code="24230" Hex="5ea6" Index="442" Width="14" />
  <CharInfo Char="康" Code="24247" Hex="5eb7" Index="443" Width="14" />
  <CharInfo Char="後" Code="24460" Hex="5f8c" Index="444" Width="14" />
  <CharInfo Char="必" Code="24517" Hex="5fc5" Index="445" Width="14" />
  <CharInfo Char="応" Code="24540" Hex="5fdc" Index="446" Width="14" />
  <CharInfo Char="情" Code="24773" Hex="60c5" Index="447" Width="14" />
  <CharInfo Char="態" Code="24907" Hex="614b" Index="448" Width="14" />
  <CharInfo Char="扱" Code="25201" Hex="6271" Index="449" Width="14" />
  <CharInfo Char="択" Code="25246" Hex="629e" Index="450" Width="14" />
  <CharInfo Char="押" Code="25276" Hex="62bc" Index="451" Width="14" />
  <CharInfo Char="振" Code="25391" Hex="632f" Index="452" Width="14" />
  <CharInfo Char="探" Code="25506" Hex="63a2" Index="453" Width="14" />
  <CharInfo Char="整" Code="25972" Hex="6574" Index="454" Width="14" />
  <CharInfo Char="方" Code="26041" Hex="65b9" Index="455" Width="14" />
  <CharInfo Char="日" Code="26085" Hex="65e5" Index="456" Width="14" />
  <CharInfo Char="明" Code="26126" Hex="660e" Index="457" Width="14" />
  <CharInfo Char="時" Code="26178" Hex="6642" Index="458" Width="14" />
  <CharInfo Char="書" Code="26360" Hex="66f8" Index="459" Width="14" />
  <CharInfo Char="月" Code="26376" Hex="6708" Index="460" Width="14" />
  <CharInfo Char="本" Code="26412" Hex="672c" Index="461" Width="14" />
  <CharInfo Char="機" Code="27231" Hex="6a5f" Index="462" Width="14" />
  <CharInfo Char="正" Code="27491" Hex="6b63" Index="463" Width="14" />
  <CharInfo Char="残" Code="27531" Hex="6b8b" Index="464" Width="14" />
  <CharInfo Char="決" Code="27770" Hex="6c7a" Index="465" Width="14" />
  <CharInfo Char="法" Code="27861" Hex="6cd5" Index="466" Width="14" />
  <CharInfo Char="消" Code="28040" Hex="6d88" Index="467" Width="14" />
  <CharInfo Char="源" Code="28304" Hex="6e90" Index="468" Width="14" />
  <CharInfo Char="状" Code="29366" Hex="72b6" Index="469" Width="14" />
  <CharInfo Char="現" Code="29694" Hex="73fe" Index="470" Width="14" />
  <CharInfo Char="生" Code="29983" Hex="751f" Index="471" Width="14" />
  <CharInfo Char="用" Code="29992" Hex="7528" Index="472" Width="14" />
  <CharInfo Char="画" Code="30011" Hex="753b" Index="473" Width="14" />
  <CharInfo Char="発" Code="30330" Hex="767a" Index="474" Width="14" />
  <CharInfo Char="登" Code="30331" Hex="767b" Index="475" Width="14" />
  <CharInfo Char="確" Code="30906" Hex="78ba" Index="476" Width="14" />
  <CharInfo Char="示" Code="31034" Hex="793a" Index="477" Width="14" />
  <CharInfo Char="移" Code="31227" Hex="79fb" Index="478" Width="14" />
  <CharInfo Char="終" Code="32066" Hex="7d42" Index="479" Width="14" />
  <CharInfo Char="経" Code="32076" Hex="7d4c" Index="480" Width="14" />
  <CharInfo Char="続" Code="32154" Hex="7d9a" Index="481" Width="14" />
  <CharInfo Char="置" Code="32622" Hex="7f6e" Index="482" Width="14" />
  <CharInfo Char="能" Code="33021" Hex="80fd" Index="483" Width="14" />
  <CharInfo Char="自" Code="33258" Hex="81ea" Index="484" Width="14" />
  <CharInfo Char="色" Code="33394" Hex="8272" Index="485" Width="14" />
  <CharInfo Char="行" Code="34892" Hex="884c" Index="486" Width="14" />
  <CharInfo Char="表" Code="34920" Hex="8868" Index="487" Width="14" />
  <CharInfo Char="補" Code="35036" Hex="88dc" Index="488" Width="14" />
  <CharInfo Char="要" Code="35201" Hex="8981" Index="489" Width="14" />
  <CharInfo Char="見" Code="35211" Hex="898b" Index="490" Width="14" />
  <CharInfo Char="解" Code="35299" Hex="89e3" Index="491" Width="14" />
  <CharInfo Char="言" Code="35328" Hex="8a00" Index="492" Width="14" />
  <CharInfo Char="設" Code="35373" Hex="8a2d" Index="493" Width="14" />
  <CharInfo Char="認" Code="35469" Hex="8a8d" Index="494" Width="14" />
  <CharInfo Char="誕" Code="35477" Hex="8a95" Index="495" Width="14" />
  <CharInfo Char="語" Code="35486" Hex="8a9e" Index="496" Width="14" />
  <CharInfo Char="説" Code="35500" Hex="8aac" Index="497" Width="14" />
  <CharInfo Char="読" Code="35501" Hex="8aad" Index="498" Width="14" />
  <CharInfo Char="調" Code="35519" Hex="8abf" Index="499" Width="14" />
  <CharInfo Char="起" Code="36215" Hex="8d77" Index="500" Width="14" />
  <CharInfo Char="退" Code="36864" Hex="9000" Index="501" Width="14" />
  <CharInfo Char="通" Code="36890" Hex="901a" Index="502" Width="14" />
  <CharInfo Char="遊" Code="36938" Hex="904a" Index="503" Width="14" />
  <CharInfo Char="過" Code="36942" Hex="904e" Index="504" Width="14" />
  <CharInfo Char="選" Code="36984" Hex="9078" Index="505" Width="14" />
  <CharInfo Char="録" Code="37682" Hex="9332" Index="506" Width="14" />
  <CharInfo Char="開" Code="38283" Hex="958b" Index="507" Width="14" />
  <CharInfo Char="間" Code="38291" Hex="9593" Index="508" Width="14" />
  <CharInfo Char="除" Code="38500" Hex="9664" Index="509" Width="14" />
  <CharInfo Char="電" Code="38651" Hex="96fb" Index="510" Width="14" />
  <CharInfo Char="面" Code="38754" Hex="9762" Index="511" Width="14" />
  <CharInfo Char="鳴" Code="40180" Hex="9cf4" Index="512" Width="14" />
```

Most of what is required is not available. We need a dump of the iQue TWLFontTable and Launcher SRL (preferably a full NAND dump) to continue.

**Comment by chyyran** [comment]
As a workaround, could we whitelist these games and just write English titles for them for the time being?

**Comment by FlameKat53** [comment]
I wouldn’t mind that :P

**Comment by FlameAlt53** [comment]
oh, adding onto what I said last week, I'd want either the Chinese titles or the English ones with it saying 'Nintendo/iQue" as the author though.

**Comment by R-YaTian** [comment]
I succeed in getting the iQue TWLFontTable file,but I do not know which file is Launcher SRL.

**Comment by R-YaTian** [comment]
> TBF1_banner_lm contains the following CJK glyphs
>   <CharInfo Char="上" Code="19978" Hex="4e0a" Index="397" Width="14" />
>   <CharInfo Char="下" Code="19979" Hex="4e0b" Index="398" Width="14" />
>   <CharInfo Char="了" Code="20102" Hex="4e86" Index="399" Width="14" />
>   <CharInfo Char="今" Code="20170" Hex="4eca" Index="400" Width="14" />
>   <CharInfo Char="他" Code="20182" Hex="4ed6" Index="401" Width="14" />
>   <CharInfo Char="付" Code="20184" Hex="4ed8" Index="402" Width="14" />
>   <CharInfo Char="以" Code="20197" Hex="4ee5" Index="403" Width="14" />
>   <CharInfo Char="位" Code="20301" Hex="4f4d" Index="404" Width="14" />
>   <CharInfo Char="体" Code="20307" Hex="4f53" Index="405" Width="14" />
>   <CharInfo Char="何" Code="20309" Hex="4f55" Index="406" Width="14" />
>   <CharInfo Char="使" Code="20351" Hex="4f7f" Index="407" Width="14" />
>   <CharInfo Char="保" Code="20445" Hex="4fdd" Index="408" Width="14" />
>   <CharInfo Char="信" Code="20449" Hex="4fe1" Index="409" Width="14" />
>   <CharInfo Char="健" Code="20581" Hex="5065" Index="410" Width="14" />
>   <CharInfo Char="入" Code="20837" Hex="5165" Index="411" Width="14" />
>   <CharInfo Char="全" Code="20840" Hex="5168" Index="412" Width="14" />
>   <CharInfo Char="内" Code="20869" Hex="5185" Index="413" Width="14" />
>   <CharInfo Char="分" Code="20998" Hex="5206" Index="414" Width="14" />
>   <CharInfo Char="切" Code="20999" Hex="5207" Index="415" Width="14" />
>   <CharInfo Char="初" Code="21021" Hex="521d" Index="416" Width="14" />
>   <CharInfo Char="刻" Code="21051" Hex="523b" Index="417" Width="14" />
>   <CharInfo Char="前" Code="21069" Hex="524d" Index="418" Width="14" />
>   <CharInfo Char="力" Code="21147" Hex="529b" Index="419" Width="14" />
>   <CharInfo Char="加" Code="21152" Hex="52a0" Index="420" Width="14" />
>   <CharInfo Char="動" Code="21205" Hex="52d5" Index="421" Width="14" />
>   <CharInfo Char="去" Code="21435" Hex="53bb" Index="422" Width="14" />
>   <CharInfo Char="参" Code="21442" Hex="53c2" Index="423" Width="14" />
>   <CharInfo Char="取" Code="21462" Hex="53d6" Index="424" Width="14" />
>   <CharInfo Char="合" Code="21512" Hex="5408" Index="425" Width="14" />
>   <CharInfo Char="名" Code="21517" Hex="540d" Index="426" Width="14" />
>   <CharInfo Char="員" Code="21729" Hex="54e1" Index="427" Width="14" />
>   <CharInfo Char="在" Code="22312" Hex="5728" Index="428" Width="14" />
>   <CharInfo Char="報" Code="22577" Hex="5831" Index="429" Width="14" />
>   <CharInfo Char="外" Code="22806" Hex="5916" Index="430" Width="14" />
>   <CharInfo Char="大" Code="22823" Hex="5927" Index="431" Width="14" />
>   <CharInfo Char="好" Code="22909" Hex="597d" Index="432" Width="14" />
>   <CharInfo Char="始" Code="22987" Hex="59cb" Index="433" Width="14" />
>   <CharInfo Char="存" Code="23384" Hex="5b58" Index="434" Width="14" />
>   <CharInfo Char="安" Code="23433" Hex="5b89" Index="435" Width="14" />
>   <CharInfo Char="完" Code="23436" Hex="5b8c" Index="436" Width="14" />
>   <CharInfo Char="定" Code="23450" Hex="5b9a" Index="437" Width="14" />
>   <CharInfo Char="室" Code="23460" Hex="5ba4" Index="438" Width="14" />
>   <CharInfo Char="容" Code="23481" Hex="5bb9" Index="439" Width="14" />
>   <CharInfo Char="差" Code="24046" Hex="5dee" Index="440" Width="14" />
>   <CharInfo Char="年" Code="24180" Hex="5e74" Index="441" Width="14" />
>   <CharInfo Char="度" Code="24230" Hex="5ea6" Index="442" Width="14" />
>   <CharInfo Char="康" Code="24247" Hex="5eb7" Index="443" Width="14" />
>   <CharInfo Char="後" Code="24460" Hex="5f8c" Index="444" Width="14" />
>   <CharInfo Char="必" Code="24517" Hex="5fc5" Index="445" Width="14" />
>   <CharInfo Char="応" Code="24540" Hex="5fdc" Index="446" Width="14" />
>   <CharInfo Char="情" Code="24773" Hex="60c5" Index="447" Width="14" />
>   <CharInfo Char="態" Code="24907" Hex="614b" Index="448" Width="14" />
>   <CharInfo Char="扱" Code="25201" Hex="6271" Index="449" Width="14" />
>   <CharInfo Char="択" Code="25246" Hex="629e" Index="450" Width="14" />
>   <CharInfo Char="押" Code="25276" Hex="62bc" Index="451" Width="14" />
>   <CharInfo Char="振" Code="25391" Hex="632f" Index="452" Width="14" />
>   <CharInfo Char="探" Code="25506" Hex="63a2" Index="453" Width="14" />
>   <CharInfo Char="整" Code="25972" Hex="6574" Index="454" Width="14" />
>   <CharInfo Char="方" Code="26041" Hex="65b9" Index="455" Width="14" />
>   <CharInfo Char="日" Code="26085" Hex="65e5" Index="456" Width="14" />
>   <CharInfo Char="明" Code="26126" Hex="660e" Index="457" Width="14" />
>   <CharInfo Char="時" Code="26178" Hex="6642" Index="458" Width="14" />
>   <CharInfo Char="書" Code="26360" Hex="66f8" Index="459" Width="14" />
>   <CharInfo Char="月" Code="26376" Hex="6708" Index="460" Width="14" />
>   <CharInfo Char="本" Code="26412" Hex="672c" Index="461" Width="14" />
>   <CharInfo Char="機" Code="27231" Hex="6a5f" Index="462" Width="14" />
>   <CharInfo Char="正" Code="27491" Hex="6b63" Index="463" Width="14" />
>   <CharInfo Char="残" Code="27531" Hex="6b8b" Index="464" Width="14" />
>   <CharInfo Char="決" Code="27770" Hex="6c7a" Index="465" Width="14" />
>   <CharInfo Char="法" Code="27861" Hex="6cd5" Index="466" Width="14" />
>   <CharInfo Char="消" Code="28040" Hex="6d88" Index="467" Width="14" />
>   <CharInfo Char="源" Code="28304" Hex="6e90" Index="468" Width="14" />
>   <CharInfo Char="状" Code="29366" Hex="72b6" Index="469" Width="14" />
>   <CharInfo Char="現" Code="29694" Hex="73fe" Index="470" Width="14" />
>   <CharInfo Char="生" Code="29983" Hex="751f" Index="471" Width="14" />
>   <CharInfo Char="用" Code="29992" Hex="7528" Index="472" Width="14" />
>   <CharInfo Char="画" Code="30011" Hex="753b" Index="473" Width="14" />
>   <CharInfo Char="発" Code="30330" Hex="767a" Index="474" Width="14" />
>   <CharInfo Char="登" Code="30331" Hex="767b" Index="475" Width="14" />
>   <CharInfo Char="確" Code="30906" Hex="78ba" Index="476" Width="14" />
>   <CharInfo Char="示" Code="31034" Hex="793a" Index="477" Width="14" />
>   <CharInfo Char="移" Code="31227" Hex="79fb" Index="478" Width="14" />
>   <CharInfo Char="終" Code="32066" Hex="7d42" Index="479" Width="14" />
>   <CharInfo Char="経" Code="32076" Hex="7d4c" Index="480" Width="14" />
>   <CharInfo Char="続" Code="32154" Hex="7d9a" Index="481" Width="14" />
>   <CharInfo Char="置" Code="32622" Hex="7f6e" Index="482" Width="14" />
>   <CharInfo Char="能" Code="33021" Hex="80fd" Index="483" Width="14" />
>   <CharInfo Char="自" Code="33258" Hex="81ea" Index="484" Width="14" />
>   <CharInfo Char="色" Code="33394" Hex="8272" Index="485" Width="14" />
>   <CharInfo Char="行" Code="34892" Hex="884c" Index="486" Width="14" />
>   <CharInfo Char="表" Code="34920" Hex="8868" Index="487" Width="14" />
>   <CharInfo Char="補" Code="35036" Hex="88dc" Index="488" Width="14" />
>   <CharInfo Char="要" Code="35201" Hex="8981" Index="489" Width="14" />
>   <CharInfo Char="見" Code="35211" Hex="898b" Index="490" Width="14" />
>   <CharInfo Char="解" Code="35299" Hex="89e3" Index="491" Width="14" />
>   <CharInfo Char="言" Code="35328" Hex="8a00" Index="492" Width="14" />
>   <CharInfo Char="設" Code="35373" Hex="8a2d" Index="493" Width="14" />
>   <CharInfo Char="認" Code="35469" Hex="8a8d" Index="494" Width="14" />
>   <CharInfo Char="誕" Code="35477" Hex="8a95" Index="495" Width="14" />
>   <CharInfo Char="語" Code="35486" Hex="8a9e" Index="496" Width="14" />
>   <CharInfo Char="説" Code="35500" Hex="8aac" Index="497" Width="14" />
>   <CharInfo Char="読" Code="35501" Hex="8aad" Index="498" Width="14" />
>   <CharInfo Char="調" Code="35519" Hex="8abf" Index="499" Width="14" />
>   <CharInfo Char="起" Code="36215" Hex="8d77" Index="500" Width="14" />
>   <CharInfo Char="退" Code="36864" Hex="9000" Index="501" Width="14" />
>   <CharInfo Char="通" Code="36890" Hex="901a" Index="502" Width="14" />
>   <CharInfo Char="遊" Code="36938" Hex="904a" Index="503" Width="14" />
>   <CharInfo Char="過" Code="36942" Hex="904e" Index="504" Width="14" />
>   <CharInfo Char="選" Code="36984" Hex="9078" Index="505" Width="14" />
>   <CharInfo Char="録" Code="37682" Hex="9332" Index="506" Width="14" />
>   <CharInfo Char="開" Code="38283" Hex="958b" Index="507" Width="14" />
>   <CharInfo Char="間" Code="38291" Hex="9593" Index="508" Width="14" />
>   <CharInfo Char="除" Code="38500" Hex="9664" Index="509" Width="14" />
>   <CharInfo Char="電" Code="38651" Hex="96fb" Index="510" Width="14" />
>   <CharInfo Char="面" Code="38754" Hex="9762" Index="511" Width="14" />
>   <CharInfo Char="鳴" Code="40180" Hex="9cf4" Index="512" Width="14" />
> Most of what is required is not available. We need a dump of the iQue TWLFontTable and Launcher SRL (preferably a full NAND dump) to continue.

I succeed in getting the iQue TWLFontTable file,but I do not know which file is Launcher SRL.

**Comment by chyyran** [comment]
@R-YaTian dm me on discord chyyran#9284

**Comment by FlameAlt53** [comment]
Come to think of it, this would probably make some iQue DSiWare have proper titles too and they could all be added to a whitelist as well as there isn't very many of them (they all fit on one twilight menu++ page for the dsi/3ds theme)

**Comment by MasterGamingYT** [comment]
Wait, which full nand dump? 3ds or dsi

**Comment by NightYoshi370** [comment]
Hasn't this been implemented already?

**Comment by RocketRobz** [comment]
It isn't.

**Comment by chyyran** [comment]
@Epicpkmn11 with the new font rendering should this still be open?

**Comment by Epicpkmn11** [comment]
Oh, I need all the iQue game titles as they apper on the menu so I can add their characters to the fonts, then it can be closed though

**Comment by chyyran** [comment]
I think this should be all the characters needed to display iQue game titles

```
'一' 0x4e00 '一' 0x4e00
'中' 0x4e2d '中' 0x4e2d
'任' 0x4efb '任' 0x4efb
'兄' 0x5144 '兄' 0x5144
'力' 0x529b '力' 0x529b
'天' 0x5929 '天' 0x5929
'弟' 0x5f1f '弟' 0x5f1f
'感' 0x611f '感' 0x611f
'摸' 0x6478 '摸' 0x6478
'欧' 0x6b27 '歐' 0x6b50 *
'步' 0x6b65 '步' 0x6b65
'漫' 0x6f2b '漫' 0x6f2b
'狗' 0x72d7 '狗' 0x72d7
'瓦' 0x74e6 '瓦' 0x74e6
'直' 0x76f4 '直' 0x76f4
'神' 0x795e '神' 0x795e
'笔' 0x7b14 '筆' 0x7b46 *
'级' 0x7ea7 '級' 0x7d1a *
'耀' 0x8000 '耀' 0x8000
'制' 0x5236 '製' 0x88fd *
'西' 0x897f '西' 0x897f
'超' 0x8d85 '超' 0x8d85
'造' 0x9020 '造' 0x9020
'游' 0x6e38 '遊' 0x904a *
'云' 0x4e91 '雲' 0x96f2 *
'马' 0x9a6c '馬' 0x99ac *
```

**Comment by Epicpkmn11** [comment]
Ah, didn't realize you'd sent that here 😅 
Just the simplified forms should be needed, right?

**Comment by chyyran** [comment]
Yeah, I think so
