### ISSUE TITLE
Twilight menu sometimes crashes when I move the icons (3ds theme)

### ISSUE THREAD

**Issue by MasterGamingYT** [DS-Homebrew/TWiLightMenu#529]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
-  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

-  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

-  Release _[7.4.1]_
-  Nightly _[b78208b]_

### Expected behaviour

I should move the icons as much as I please

### Actual behaviour

It randomly crashes when I move icons

### Steps to reproduce

1. Set theme to 3ds (and music to dsi shop)
2. Keep moving the icons around
3. Crash

**Comment by RocketRobz** [comment]
You put in the versions for nds-bootstrap, not TWiLight Menu++.

**Comment by MasterGamingYT** [comment]
Wait what

**Comment by MasterGamingYT** [comment]
Fixed

**Comment by Ty-Dye** [comment]
why reopen?

**Comment by FlameKat53** [comment]
He likely did it without thinking

**Comment by MasterGamingYT** [comment]
I closed it by accident

**Comment by MasterGamingYT** [comment]
Also the crash I'm talking about is Guru Meditation error

**Comment by MasterGamingYT** [comment]
Has this issue been resolved? I'll close it if it is

**Comment by FlameKat53** [comment]
Mind trying, @MasterGamingYT ?

**Comment by MasterGamingYT** [comment]
Can't seem to reproduce it, so I guess it's bye bye to this issue then
