### ISSUE TITLE
Freezes on white screen

### ISSUE THREAD

**Issue by crensyhanilas** [DS-Homebrew/TWiLightMenu#543]
Please Help. Reply me Please.

**Comment by RocketRobz** [comment]
On what game?

**Comment by crensyhanilas** [comment]
No game. When i press the arrow button

**Comment by NightYoshi370** [comment]
delete your _nds folder and redownload everything

**Comment by crensyhanilas** [comment]
This release is bad (8.0.0). Don't Use

**Comment by Stack3r** [comment]
You have no idea what you are even talking about
