### ISSUE TITLE
Weird dithering with certain colour combos on the menu. (DSi theme)

### ISSUE THREAD

**Issue by MochaChocha667** [DS-Homebrew/TWiLightMenu#555]
It's easy to see if you set the colour to purple and the theme to, say, green.

### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Can you explain what happens and/or show screenshots?

**Comment by MochaChocha667** [comment]
![screenshot](https://cdn.discordapp.com/attachments/568130936538005541/568132175891922944/image0.jpg)

**Comment by MochaChocha667** [comment]
The light purple in the settings makes it the same "purple" you see above.

**Comment by chyyran** [comment]
![latest](https://cdn.discordapp.com/attachments/568130936538005541/568140144125673506/MVIMG_20190417_142140.jpg)

Issue does not occur in the latest TWLBot build

**Comment by Stack3r** [comment]
Closing this due to the issue being fixed in latest builds
