### ISSUE TITLE
O3DS XL boot to White Screen.

### ISSUE THREAD

**Issue by ExoGamer** [DS-Homebrew/TWiLightMenu#556]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[8.0.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Boot to TWiLightMenu

### Actual behaviour

It gets stuck at a white screen at boot

### Steps to reproduce

1. Download the latest TwiLight Menu from github
2. Extract _nds from 3DS - CFW users and DSI&3DS - SD card users to the root of SD card
3.Extract BOOT.NDS to the root of the SD card
4. Extract the .CIA files from 3DS - CFW users to root of SD card
5. Install both .CIA files via FBI
6.Then boot TWiLight Menu++

**Comment by Epicpkmn11** [comment]
Can you try installing TWiLight Menu++ (and nds-bootstrap) using the TWiLight Menu++ Updater?
https://github.com/RocketRobz/TWiLightMenu-Updater/releases
![twlup](https://user-images.githubusercontent.com/41608708/56935453-c4365d00-6ab6-11e9-9f35-28e684da5904.png)

**Comment by ExoGamer** [comment]
> Can you try installing TWiLight Menu++ (and nds-bootstrap) using the TWiLight Menu++ Updater?
> https://github.com/RocketRobz/TWiLightMenu-Updater/releases
> ![twlup](https://user-images.githubusercontent.com/41608708/56935453-c4365d00-6ab6-11e9-9f35-28e684da5904.png)

Sorry for the late reply :) . So I tried your idea and it still didn't work. I tried deleting the files too and it still did it. I dont know if this might help but I'm on the latest luma cfw, and I have a 64 GB SD card, also my TWL_FIRM is not corrupted because I'm able to play dsi ware games from the eshop or ds games from cartridge and I have it installed on my sysnand and emunand

**Comment by piratesephiroth** [comment]
try to format the SD with 32KB clusters

**Comment by ExoGamer** [comment]
> try to format the SD with 32KB clusters.
> Or even better, format it first with [SD Formatter](https://www.sdcard.org/downloads/formatter/eula_windows/SDCardFormatterv5_WinEN.zip) to have the partition aligned properly, then use [guiformat](http://www.ridgecrop.demon.co.uk/guiformat.exe) to format it again to FAT32 with 32768 as allocation uint size.
> 
> EDIT: ah you use emunand, then you can't use SD Formatter, heh

K I'll try that :)

**Comment by ExoGamer** [comment]
It looks like it's working now :) thank you piratesephiroth
