### ISSUE TITLE
white screen when launch game in twilightmenu

### ISSUE THREAD

**Issue by Bezerker7234** [DS-Homebrew/TWiLightMenu#557]
Long story short try tried playing pokemon black 2 on my 3ds and it didn't work as soon as i open the rom it shows  white screen it worked when I used my rom from the cartridge but it had anti-pirating stuff on there so I don't know if it the rom(the one I got off the web) the patch or the twilightmenu

**Comment by RocketRobz** [comment]
You must run the game in DS mode.

**Comment by Bezerker7234** [comment]
didn't work oh and cant see it under resent rom

**Comment by takeshineale128** [comment]
> didn't work oh and cant see it under resent rom

press the Y button on Pokemon Black version 2 icon, Run in option set to DS Mode and ARM 9 CPU Speed option set to 133mhz (TWL)

**Comment by Bezerker7234** [comment]
oohh didn't know you had to press y im gonna try that now

**Comment by takeshineale128** [comment]
work for me

**Comment by Bezerker7234** [comment]
no doesn't seem to work do you think its the rom. im using the one i found online

**Comment by Bezerker7234** [comment]
hi um i tried patching the rom i got from the cartrige but it said that it didn't have a CRC32 of the file
