### ISSUE TITLE
Super Fantasy Zone (Mega Drive) & Zero Wing (Mega Drive) need to be Tested on jEnesisDS.

### ISSUE THREAD

**Issue by ghost** [DS-Homebrew/TWiLightMenu#558]
& Added to the jEnesisDS Compatibility List (Note they are not on the jEnesisDS Compatibility List at all).
https://wiki.gbatemp.net/wiki/JenesisDS_compatibility_list

Especially need to Test the NTSC Versions.

**Comment by NightYoshi370** [comment]
This is not related to TWiLightMenu++.
