### ISSUE TITLE
white screen when opening game on twilightmune++

### ISSUE THREAD

**Issue by Bezerker7234** [DS-Homebrew/TWiLightMenu#559]
so i tried opening the game in ds mode and it made no diffrence plz help

**Comment by Bezerker7234** [comment]
so the acctual problem was the rom i got a new one from rom depot i 100% recomend getting your roms from there if problem persists check other people with post similar to your problem goodluck

**Comment by RocketRobz** [comment]
Remember that you can comment on closed issues as well.

**Comment by RocketRobz** [comment]
Also, please don't say the names of ROM sites.
