### ISSUE TITLE
use touch screen to change game list order

### ISSUE THREAD

**Issue by flutterbrony** [DS-Homebrew/TWiLightMenu#560]
On the original DSi Menu, we can use the touch screen, and drag an icon to the top, then to the sides to be able to change it's position in the menu.
Will it be done in the future?

**Comment by Stack3r** [comment]
This can probably be done in the future, right move what we have is what we get

**Comment by NightYoshi370** [comment]
Going to merge it with #773, since there's no need to create multiple issues for the same project
