### ISSUE TITLE
TWLBot (non-docker) builds not working correctly on DSTWO

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/TWiLightMenu#561]
### Your console

Tell us which console do you have:

- [x]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

DSi splash and/or TWLMenu++ splash plays, and then ROM menu is shown.

### Actual behaviour

DSi splash and/or TWLMenu++ splash will play, and then white screen (if `settings.ini` exists).

### Steps to reproduce

1. Download TWLBot build [here](https://github.com/TWLBot/Builds/raw/4b444dde7a1e8f90b444a36f60be57ac5e25ae02/TWiLightMenu.7z).
2. Extract `_nds` folder to SD root, overwriting the existing one (if exists).
3. Start up the DSTWO flashcard.

**Comment by FlameKat53** [comment]
The docker and normal builds didn’t work?

**Comment by RocketRobz** [comment]
Only tried the normal one.

**Comment by FlameKat53** [comment]
Try this one: https://github.com/TWLBot/Builds/blob/master/TWiLightMenu_docker.7z

**Comment by RocketRobz** [comment]
That works.

**Comment by FlameKat53** [comment]
Nice!
Chyyran said it was a problem with dkA 51 and 52 in the past though, that’s why we have the docker builds

**Comment by Stack3r** [comment]
Is this still an on going problem?

**Comment by FlameKat53** [comment]
Yes, I can confirm this also happens with R4i-SDHC cards

**Comment by FlameKat53** [comment]
In a few hours i'll check if this is still an issue on my R4i-SDHC, along with some testing of B4DS.

**Comment by FlameKat53** [comment]
it's working on my flashcard!
@RocketRobz you should try on your DSTWO to see if this can be closed

**Comment by NightYoshi370** [comment]
According to a conversation that Robz had on discord, DSTWO's can now boot TWiLight Menu++. Unless this is now inaccurate, I'll close the issue
