### ISSUE TITLE
Guru Mediation Error, Data Abort on launch

### ISSUE THREAD

**Issue by Gyurn** [DS-Homebrew/TWiLightMenu#562]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:
DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release _[pre easter build?]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Normally Opening TWiLight menu opens up to my DS roms

### Actual behaviour

Guru mediation error data abort, happens right after the video splash you just added, I cannot enter Twilight menu

### Steps to reproduce

1.open twilight menu

Unsure if these are related, but they were the last steps I took before breaking the software I guess.  I tried to delete a DS game from within the menu, got the error then too, I also used the updater to update boxart, after those two steps I could not open twilight menu anymore.

**Comment by RocketRobz** [comment]
Try deleting `settings.ini` at `sd:/_nds/TWiLightMenu`.
I don't have this issue.

**Comment by Gyurn** [comment]
Success 🙌 many thanks!
