### ISSUE TITLE
Compatibility issue with an R4iSDHC card

### ISSUE THREAD

**Issue by megaman9521** [DS-Homebrew/TWiLightMenu#563]
I installed this firmware, and I got error 1 when I tried to start a retail game (However, homebrew started up just fine). When I reinstalled nds-bootstrap, I got error 0, saying my card may be unsupported. My card is the R4 SDHC Dual Core (used with a Phat DS).

**Comment by arraystock** [comment]
Please try [this](https://github.com/DS-Homebrew/TWiLightMenu/files/3129407/twlmenu_r4.zip) build, overwrite your `_nds` folder. If it still gives error 0, can you send the card name it tells you?

**Comment by megaman9521** [comment]
I now got an error about nds-bootstrap. It says it can only be used on the SD card. It doesn't give error 1 or 0 anymore.

**Comment by RocketRobz** [comment]
Switch Bootstrap to nightly in TWLMenu++ settings.

**Comment by arraystock** [comment]
^ B4DS needs to be used on flashcarts.

**Comment by megaman9521** [comment]
It worked, but the system froze when it tried to load a game.

**Comment by RocketRobz** [comment]
Not all games work.

**Comment by megaman9521** [comment]
Alright. Thanks for the help. I'll try out TWiLight and see what I can do.

**Comment by megaman9521** [comment]
Ok, I tried some games, like Mario Kart, MegaMan Battle Network 5, and Brain Age, and almost any game i tried to start up crashed the system.

**Comment by arraystock** [comment]
I can confirm that both Sonic Classic Collection and Super Mario 64 DS run according to the [b4ds compatibility list](https://docs.google.com/spreadsheets/d/1LRTkXOUXraTMjg1eedz_f7b5jiuyMv2x6e_jY_nyHSc/edit#gid=860616020), so your crashes are b4ds related.

**Comment by FlameKat53** [comment]
Sadly `Sonic Classic Collection`, doesn't work anymore...
And SM64DS doesn't work 100%, but you can try `WarioWare Touched!`, `Bomberman`, `Feel the Magic`/`Project Rub`, and `Spider-Man 2`

**Comment by NightYoshi370** [comment]
Not really a twilight issue at this point
