### ISSUE TITLE
CycloDS white screen on N2DSXL

### ISSUE THREAD

**Issue by subworx** [DS-Homebrew/TWiLightMenu#564]
### Your console
- [x]  Old 3DS XL
- [x]  New 2DS XL

### CFW and configuration
3DS/2DS:

- [x]  Luma3DS 9.1-89cc6ed
All settings as per 3ds.guide manual plus Game Patching enabled for cheats.
On N2DS I played around with clock/cache settings in Rosalina menu.

### TWiLight Menu++ version

- [x]  Release _[7.4.1]_ (O3DSXL)

- [x]  Release _[8.0.1]_ (N2DSXL)

### Expected behaviour

CycloDS card on latest firmware boots properly.

### Actual behaviour

O3DS: works perfectly. Haven't touched this setup since.
N2DS: white screen.
With an older release of TWL Menu and nds-bootstrap (cannot remember which exactly) it worked reliably after a few tries on the N2DS. After updating TWL Menu and nds-bootstrap (Release and Nightly) to the latest versions, it stopped working.

L+R+Down+B does not work in this state.
I can press the Home button and kill the app, though, so it is not the whole console crashing.

### Steps to reproduce

1. TWLMenu config is identical for both consoles:
Quick/Main Menu: Show
Theme: R4

Run in: DSi Mode
ARM9 CPU speed: 133 MHz (TWL)
VRAM boost: On
(Force sleep mode patch: off/on makes no difference, N2DS only)
SCFG access in Slot 1: Off
Slot-1 launch method: Direct
Sound/Mic frequency: 32.73 kHz
Loading screen: Regular
Loading screen theme: Light
Loading screen location: Top
Bootstrap on O3DS: Nightly 279a9cc
Bootstrap on N3DS: Release 0.18.0 / Nightly 8efbcdd

Language: System
Color mode: Regular
Slot-1 microSD access: On

2. Return to main menu and tap "Start Game Card" 

Debugging and Logging didn't return any output or logfiles so I am at a loss on how to help.

If there is a way to provide a log or similar, please let me know.
Also please let me know if I should post this to nds-bootstrap instead.

Thank you so much.

**Comment by subworx** [comment]
Just found out that the main menu stopped working as well.
Used Updater 3.1.1 to update to TWL Menu 8.0.1.
When pressing the yellow arrow in the quick menu to open the main menu, I get a white screen (Acekard, R4 themes) or a black screen stating "The SD card with TWiLight Menu++ was removed" (DSi, 3DS themes).
Before, at least the R4 theme worked properly and I could launch games or Slot-1 from there.

**Comment by subworx** [comment]
F*** me.
After playing around with all 4 loaders with and without flashcart and with an NDS game cart, it works.
First, when removing the flashcart, all 4 themes work perfectly fine. After inserting the flashcart, they'd all crash again.
Started them without the cart, then put in the cart, didn't work out.
All went fine with the game cart, all themes loaded and the game booted.
But after one of these tries, the flashcart worked again as well.
I have absolutely no idea why.

Except for the skin, during my testing, I did not change any other options anywhere.

**Comment by subworx** [comment]
And broken again.
Sent the device to sleep while playing a game. 
Woke up to black screen. No button reaction except for Home. 
Now even after a device reboot, the flashcart won't boot again.

**Comment by NightYoshi370** [comment]
@subworx please try the latest nightly of TWiLightMenu++, both the docker builds and the normal TWLBot builds.

**Comment by subworx** [comment]
Hey, tried nightly ade013a2, non-docker first. 
After playing around a bit (entering and leaving the R4 menu with and without flashcart and trying to boot it a few times), it currently works again, question is for how long :/

**Comment by NightYoshi370** [comment]
Since it works now, I doubt it'll randomly break. Lets close this and when you have an issue, just leave a comment and I'll open it again
