### ISSUE TITLE
White Screen When Load NDS Game on Japan DSi

### ISSUE THREAD

**Issue by yuu002** [DS-Homebrew/TWiLightMenu#565]
##############################################################
##############################################################
Please report this issue here: https://github.com/ahezard/nds-bootstrap/issues/new
##############################################################

I've already installing Twilight Menu ++ 
i tried to play Gbc and it's work fine, but the problem are when i opened DS game.

it keeps Freeze with white screen ( I've pressing A or Start Button when choose the game, But Nothing happens)

I used 32gb sd card with unlauch installed on my DSI XL (JP region). 
and I've tried to reformat my SD Card or etc but Nothing Happens.

**Comment by RocketRobz** [comment]
Go into Unlaunch options, and set the `No Buttons` option to `HIYACFW.`
