### ISSUE TITLE
Harvest Moon Ds white screen

### ISSUE THREAD

**Issue by tyronn28** [DS-Homebrew/TWiLightMenu#567]
ive been having issues with my harvest moon ds game, i cant seem to get it to load up. everytime i try to open it, it just loads a bit then freezes at a white screen. any help pls?

btw im a bit new here

**Comment by Epicpkmn11** [comment]
If you're on DSi, are you launching `HIYACFW` or `TWLMENUPP`? You need to use `HIYACFW` for DS games to work.

Also, isues with games should be reported on https://github.com/ahezard/nds-bootstrap/issues, not on the TWiLight Menu++ repo

**Comment by tyronn28** [comment]
im using twlmenu. anyway thanks a lot for the heads up and the help.
