### ISSUE TITLE
Soft-reset issues (most recent updates with v0.18.0 bootstrap)

### ISSUE THREAD

**Issue by Dyathias** [DS-Homebrew/TWiLightMenu#568]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.8+1.3.2]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.0.1+nds-bootstrap 0.18.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen:
Reboots game on soft-reset press on flashcart game AND direct rom game in _nds folder.
### Actual behaviour

Tell us what happens instead:
Stuck white screen indefinitely.
### Steps to reproduce

1. Wi-Fi config reset.
2. or, soft-reset button press.
3. or, flash-cart soft reset.

**Comment by Dyathias** [comment]
hmm seems like the soft-reset button press works, but sometimes it just gets stuck. Seems like the only big issue is when the game(s) reset after exiting the Wi-Fi configuration.

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, not a TWLMenu++ issue.
