### ISSUE TITLE
Inconsistencies with the cheat menu

### ISSUE THREAD

**Issue by zeroultima6** [DS-Homebrew/TWiLightMenu#569]
A minor issue but there are a few games like nanashi no geemu doesn't show the cheats with the ENG patch applied but without the patch on it does show the cheats.

**Comment by piratesephiroth** [comment]
it's a problem with the cheats them

**Comment by Epicpkmn11** [comment]
I think this is probably intended behavior. The rom's header's crc is probably changed by the translation patch, which will make the cheats not be valid for that rom. You'll need to make a `usrcheat.dat` file that has cheats for the english patched rom's header's crc

Unless the header's crc is actually the same, then this issue should probably be closed

**Comment by NightYoshi370** [comment]
This is not an issue with twilight.
