### ISSUE TITLE
wifi ON/OFF option

### ISSUE THREAD

**Issue by evilCiD** [DS-Homebrew/TWiLightMenu#570]
**Is your feature request related to a problem? Please describe.**
when i made the nand-backup i had my wifi disabled and now i can't turn it back on again. this should be warned about in the dsi cfw guide btw. 

**Describe the solution you'd like**
a wifi ON/OFF option in the twilight menu++ settings

**Describe alternatives you've considered**
any other way to enable/disable wifi

**Comment by flutterbrony** [comment]
That's weird, the wifi shouldn't be turned off when installing cfw to a dsi.
Anyway, your wifi problem is not related to TWiLightMenu++, and the feature to enable/disable wifi is already present on cfw dsi, if I remember well, you should press the A button to disable it, else, it should stay enabled.
Are you sure you didn't disabled it in your System Settings ?

**Comment by edo9300** [comment]
Launch the system settings from twilight, and change it from there. If you get the "an error has occurred" then remove the read only property from all the files in the shared1 folder in your SD card

**Comment by evilCiD** [comment]
ok i guess this is related to my 16gb sd card then, i can enter system settings after a few attempts (most of the time the dsi reboots when i try to enter system settings) but after changing settings and clicking on "return to dsi menu" the dsi reboots to the hiya screen and maybe doesn't save. i ll just play alone :P this can be closed :) thanks for the support

**Comment by flutterbrony** [comment]
Try booting your dsi by pressing the A button, you should go in the original firmware (otherwise, press A + B while booting, you should enter in Unlaunch, then, you can ask to boot the original launcher by choosing it, and pressing A (the path unlaunch will indicate should indicate Nand:path/to/the/launcher
Try setting wifi back on from there.
Good luck with that !
