### ISSUE TITLE
Can't change username

### ISSUE THREAD

**Issue by galvaniccoffee** [DS-Homebrew/TWiLightMenu#571]
### Your console
Tell us which console do you have: DSi

### CFW and configuration
DSi: Unlaunch V1.8 + HiyaCFW (V1.3.2, probably) 

### TWiLight Menu++ version
Release 7.4.1

### Expected behaviour

Changing the username in the system settings should change the username displayed in TWiLight Menu++ (e. g. on the top screen in DSi/3DS mode).

### Actual behaviour

Changing the username in the system settings has no effect on the username displayed in TWiLight Menu++. There seems to be no way to update it.

### Steps to reproduce

1. Install Unlaunch/HiyaCFW/TWiLight Menu++.
2. Attempt to change username via system settings.

**Comment by Epicpkmn11** [comment]
Did you change your username on sysNAND or SDNAND? I think TWiLight reads username and such from sysNAND

**Comment by BaJIeHTuHbI4** [comment]
Same problem here. 
Change name after installing TWiLightMenu. 
In system menu - new correct name, in TWiLightMenu - old name.
Remove SD card from DSi - show correct new name.

**Comment by FlameKat53** [comment]
Yeah, you have to change it in sysNAND, not SDNAND.

**Comment by gretel** [comment]
had to re-dump `nand` and -build `sdnand` from scratch be actually able to have the username changed.

**Comment by dazzaXx** [comment]
I've ran into this using 9.0.1 Release, booting System Settings from the TWLMenu Settings in the Misc. Page sometimes either runs system settings that isnt the right one, sometimes it does load the correct system settings and sometimes it just errors out with the "An Error Occurred" screen.

**Comment by PanderTech** [comment]
I can confirm this is still an issue. I have booted into emunand (w/ sd card) and sysnand (sd removed)...both of the names are correct (I checked the launchers on both internal and sd)...however, if I hit system settings from TM++ options, it then loads me into settings that show an entirely different user...which theoretically shouldn't even be possible! :/
Maybe update to read from emunand?
