### ISSUE TITLE
can't get main.srldr to work when compilling it myself

### ISSUE THREAD

**Issue by flutterbrony** [DS-Homebrew/TWiLightMenu#572]
Hello, I wanted to compile the latest commit of TWiLight Menu ++ by myself and then copy it to sd:/_nds/TWiLightMenu/main/srldr as it is done by the compile.bat file, and as I always done when compiling the latest commit  month ago, but this time, my dsi is just stuck on a white screen at boot. I put back the original main.srldr, and it worked, so I downloaded the release.zip, and compiled there the title.nds, copied it to my sd, and again, stuck at a white screen.
I still can compile the settings.slrdr on the latest commit and get it working, and if I just put title.nds at sd:/title.nds, then boot it from TWiLightMenu, it work, and I'm going back to TWiLightMenu.
I also noticed that if I specify a number of core when trying to build title.nds, it fails to compile with a load_bin.h not found.
I'm using the latest devkitpro and libnds, any ideas on why I'm getting stuck on title.nds ?

**Comment by arraystock** [comment]
Are you using the `libmm7.a` included in TWiLightMenu source? I was having the same issue until I copied it over my installed version at `/opt/devkitpro/libnds/lib` (if I remember correctly).

**Comment by flutterbrony** [comment]
I already have it, but I copied it anyway, and also found why it wasn't booting. It was just a stupid mistake I made :/
It's now working, thanks ! ^^
