### ISSUE TITLE
(REQUEST) R4i flashcarts support for twilight menu as skin

### ISSUE THREAD

**Issue by MasterGamingYT** [DS-Homebrew/TWiLightMenu#576]
Is it possible to add support for the R4i flashcarts (i.e R4i Gold 3DS, R4i SDHC Gold Pro, R4i SDHC Dual Core, etc) so that we can get twilight menu as a skin for these flashcarts while still maintaining the flashcart compatability?

**Comment by NightYoshi370** [comment]
Can you send me the firmware? If it has autoboot settings, than we can use it.
Although, it'd most likely not have it and in that case, we'd be forced to use nds-bootstrap.

**Comment by F-l-a** [comment]
Hi, here it is
https://drive.google.com/open?id=1su3mzUjKOBhOTOumbLPnCVzS2Ex47nKl

**Comment by MasterGamingYT** [comment]
@NightYoshi370 I'm using YSmenu

**Comment by MasterGamingYT** [comment]
I'm gonna leave this open until compatability gets added (Not being impatient)

**Comment by NightYoshi370** [comment]
I checked, and there doesn't seem to be autobooting support on the card. Therefore, I don't think it's possible to have TWiLightMenu++ flashcard launcher, unless @RocketRobz says otherwise.

**Comment by FlameKat53** [comment]
By the way, you can autoboot into twilight menu++ on these flashcards, if you want to use YSMenu or something like that you could just boot into YSMenu first then choose twilight menu or you could use my app, ButtonBoot, to have TWiLight Menu++ as boot.nds and YSMenu as one of the hotkeys or the other way around.

**Comment by F-l-a** [comment]
Yes, it works. But I can't boot games or homebrews as long as TwilightMenu++ bootloaders (Release and Nightly) don't work on these flashcards (I think they aren't supported, as said by the error code shown on the screen). Also the bootloader of the flashcard' firmware don't work with TWLMenu++..

**Comment by froggestspirit** [comment]
I think this is the same flashcart I spoke with Robz on breifly. I believe it was that booting into TwilightMenu breaks the DLDI with the Flashcart (You can test this by booting YSMENU from TwilightMenu, then from YSMENU, roms won't load). I wanted to try doing a memory dump of YSMenu's RAM before running TM and after to compare, but I don't think there's an easy way to do that in an emulator.

**Comment by Eru-Ponaho** [comment]
So I have both TWLoader and the latest TWiLight Menu to run this flashcart, TWLoader seems to work with this flashcart. TWiLight Menu can autoboot a game from this flashcart but it can't show the roms on the flashcart. It will autoboot the last game that was running which I use from TWLoader.
