### ISSUE TITLE
Touchscreen doesn't work when booting directly from Unlaunch (i.e. not using HiyaCFW)

### ISSUE THREAD

**Issue by PoroCYon** [DS-Homebrew/TWiLightMenu#577]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _0.8_
- [ ]  Unlaunch+HiyaCFW _N/A_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _8.1.1_
- [ ]  Nightly _N/A_

### Expected behaviour

When TWiLightMenu has loaded, touchscreen input should do *something* (eg. start a ROM, scroll between files, open settings, etc.)

### Actual behaviour

The touchscreen is completely unresponsive. (All other *physical* buttons, dpad etc. do work.)

### Steps to reproduce

1. Boot directly from Unlaunch
2. Try touching the touchscreen
3. ???

**Comment by Epicpkmn11** [comment]
Can you try updating your Unlaunch? 0.8 is very old, so that could be why touch isn't working. It works fine for me on Unlaunch 1.9

To update:
1. Download the 1.9 installer from https://problemkaputt.de/unlaunch.htm
2. Rename `sd:/bootcode.dsi` to `sd:/hiya.dsi`
3. Copy `UNLAUNCH.DSI` to your sd and rename it `bootcode.dsi`
4. Boot and choose `Install Now`
5. Go to `OPTIONS` → `NO BUTTON` and set it to `TWiLight Menu++` (`sdmc:/BOOT.NDS`)

**Comment by PoroCYon** [comment]
I know how to update. I would've done that a long time ago if I weren't getting the "Mismatch in FAT copies"-error. I do have a NAND backup, but I don't have the equipment to flash it back. (My soldering iron and wire are waay to blunt, but I do know how to do the actual flashing, I've done that with different devices before.)

**Comment by Epicpkmn11** [comment]
Ah, if you're sure the nand backup is good, you can flash it using fwTool 1.6, but since that's not a hard mod, if something goes wrong it will be bricked.

**Comment by NightYoshi370** [comment]
Are you sure its a twilight issue? Try using the system menu or another homebrew with touch and see if it works

**Comment by PoroCYon** [comment]
Yes, those do work.

And yeah, I *could* use fwTool, but I'm not going to when I don't have a backup solution at hand.

**Comment by FlameAlt53** [comment]
the touch screen works for me when booting from unlaunch...

**Comment by FlameAlt53** [comment]
also, if its important to you, I have Unlaunch 1.9 and am launching it by the (tons of 0's).app file.
