### ISSUE TITLE
Assassin's Creed - Altair Chronicles & Discovery ERROR.

### ISSUE THREAD

**Issue by lenix9090** [DS-Homebrew/TWiLightMenu#578]
I was testing 2 Assassin's Creed from DS and they do not work.

Assassin's Creed: Atlair Chronicles. When the game started, the screen above turned red with a few dots.

Assassin's Creed 2: Discovery. While loading it gives error.

(Extra inf.)
DSi, SD, No CFW, TWNLF (Flipnote Lenny).

-Translated with Google Translator

**Comment by SuperSaiyajinVoltZ** [comment]
This is a NDS-Bootstrap Issue and not a TWiLightMenu++ Issue.

**Comment by RocketRobz** [comment]
Also, both games work on latest nds-bootstrap version.

**Comment by lenix9090** [comment]
> Also, both games work on latest nds-bootstrap version.

And ... how do I update it? (I'm not CFW)
to tell you the truth, I do not know much about the subject ... :P

**Comment by lenix9090** [comment]
(Rookie Alert!)

**Comment by arraystock** [comment]
Download the .zip or .7z file from [here](https://github.com/ahezard/nds-bootstrap/releases), and put its contents in the `_nds` folder on your SD.

**Comment by RocketRobz** [comment]
[[Update TWiLight Menu++]](https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-update-TWiLight-Menu) as well, while you're at it.
Scroll down to `DSiWarehax Update instructions`.

**Comment by lenix9090** [comment]
> Download the .zip or .7z file from [here](https://github.com/ahezard/nds-bootstrap/releases), and put its contents in the `_nds` folder on your SD.

I did it, but now I do not see the loading screen, Megaman ZX does not start me (it was the only game I tried) and it keeps giving error. D:

**Comment by lenix9090** [comment]
> [Update TWiLight Menu++](https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-update-TWiLight-Menu) as well, while you're at it.
> Scroll down to `DSiWarehax Update instructions`.

Ok.

**Comment by RocketRobz** [comment]
So why can't you install Unlaunch again?
If it's the FAT mismatch error, then in System Settings, copy your DSiWare to the SD card, delete them from System Memory, then copy the DSiWare from SD, back to System Memory.

**Comment by lenix9090** [comment]
The 1 if it works well, but the 2 does not... @RocketRobz
