### ISSUE TITLE
Pokemon Pearl & Heart Gold not booting

### ISSUE THREAD

**Issue by hannahlorrainee** [DS-Homebrew/TWiLightMenu#579]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.1.1]
- [ ]  Nightly _[insert here commit hash]_
nds-bootstrap: 0.19.2
### Expected behaviour

Games should boot

### Actual behaviour

Pokemon Pearl goes to white screen, Pokemon HG goes to black screen with some sound.

### Steps to reproduce

1. Boot TWL++
2. Select Game
3. Try to boot

I have both games set to boot in DS Mode (by clicking y and selecting in that menu). Please help--I posted this in bootstrap and they said it wasn't a bootstrap issue. ROMS are not corrupted.

**Comment by SuperSaiyajinVoltZ** [comment]
This is not an TWLMenu Issue.

**Comment by hannahlorrainee** [comment]
> This is not an TWLMenu Issue.

Okay well then where should I post this to get help?

**Comment by hannahlorrainee** [comment]
Honestly, I'm exhausted looking for answers on this. So if you can't tell me where to properly post so I can get some answers, please don't comment. You have no idea how frustrated I am.

**Comment by SuperSaiyajinVoltZ** [comment]
Ask in the Discord Server for help. https://discord.gg/yqSut8c

**Comment by hannahlorrainee** [comment]
> Ask in the Discord Server for help. https://discord.gg/yqSut8c

It's not loading into the discord server

**Comment by hannahlorrainee** [comment]
Can't connect. Super helpful.

**Comment by SuperSaiyajinVoltZ** [comment]
2 Discord Accounts called `Hannahle` and `Hannahlew` are in the Discord Server. I assume both accounts are from you.

**Comment by hannahlorrainee** [comment]
> 2 Discord Accounts called `Hannahle` and `Hannahlew` are in the Discord Server. I assume both accounts are from you.

yes but I can't see anything it just keeps "connecting" and won't let me in. Didn't mean to make two. It's just not working.

**Comment by SuperSaiyajinVoltZ** [comment]
Discord Probably has Issues at the Moment. Just wait, until Discord works properly again.

**Comment by NightYoshi370** [comment]
@SuperSaiyajinVoltZ please don't link people to the discord server to report issues, they get lost quite quickly from the influx of messages.

@hannahlorrainee You will need to report the issue in the nds-bootstrap repository on @ahezard's github

**Comment by MasterGamingYT** [comment]
Hold L while booting them (It will probably work)

**Comment by RocketRobz** [comment]
They work fine without holding L though.

**Comment by MasterGamingYT** [comment]
Ah ok
