### ISSUE TITLE
Any Pokemon Games White screen

### ISSUE THREAD

**Issue by lexusui1** [DS-Homebrew/TWiLightMenu#580]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[latest]_
- [ ]  Nightly _[]_

### Expected behaviour
Any Pokemon
Game should boot

### Actual behaviour

Whithe screen

### Steps to reproduce

1.Open TWL
2.Select Game
3.Try to open it

**Comment by lexusui1** [comment]
Any Game no boot white screen

**Comment by ItsDeidara** [comment]
How long did you wait? At least on my N2DS I had to wait a good 30 seconds or so before the game would load past the white screen

**Comment by RocketRobz** [comment]
@lexusui1 Ah, you're using DSiWarehax (assuming it's Flipnote Lenny).
You should switch to Unlaunch+HiyaCFW.
