### ISSUE TITLE
Guru Meditation Error when creating save file

### ISSUE THREAD

**Issue by LeddaZ** [DS-Homebrew/TWiLightMenu#581]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW Unlaunch 1.9 + HiyaCFW 1.3.2

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release 8.1.1
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

When starting a game for the first time a .sav file is created.

### Actual behaviour

A Guru Meditation Error appears when creating the save file. After rebooting the console I can boot the game, but the .sav file is 0 bytes because of the error and the game doesn't save. Tested with release & nightly bootstrap on SM64DS and Pokémon HeartGold, the SD card isn't read only.

### Steps to reproduce

1. Delete the .sav file for a game if it exists
2. Try to boot the game
3. The error appears

**Comment by LeddaZ** [comment]
A temporary solution is to run "fsutil file createnew "game.sav" 524228" to create an empty 512KB save file

**Comment by chyyran** [comment]
fixed by #687
