### ISSUE TITLE
can't run games through boot.nds. Manually launching the 00000000.app works fine.

### ISSUE THREAD

**Issue by alivebacon** [DS-Homebrew/TWiLightMenu#582]
### Your console

Tell us which console do you have:

- []  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [X ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_
Unlaunch 1.8
3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_ I think it's the latest.
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour
Games load if you use boot.nds
Tell us what should happen

### Actual behaviour
Games won't run
Tell us what happens instead

### Steps to reproduce

1. Without hiyacfw, launch the boot.nds.
2. Go to a DS or DSi rom. (not sure about emus)
3. Run it.
I can't run hiyacfw as it blackscreens.

**Comment by RocketRobz** [comment]
I can run games with only Unlaunch just fine.
What nds-bootstrap version are you on? (Check TWLMenu++ Settings)

**Comment by MasterGamingYT** [comment]
How did you add the bug tag yourself?

**Comment by RocketRobz** [comment]
It's part of the issue template.

**Comment by MasterGamingYT** [comment]
oh

**Comment by alivebacon** [comment]
IDK because i probs updated.

**Comment by RocketRobz** [comment]
Issue is fixed in later nds-bootstrap versions.
