### ISSUE TITLE
Touchscreen does not work when running nds roms

### ISSUE THREAD

**Issue by didakf** [DS-Homebrew/TWiLightMenu#583]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[V8.1.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Roms should be properly running when I open a rom through twilightmenu

### Actual behaviour

Touchscreen works fine when selecting roms through twilightmenu but after opening a rom, touchscreen does not work. All other buttons work fine though. I installed the latest version of TwiLightMenu and nds-bootstrap. 

### Steps to reproduce

1. Open TwiLightMenu from 3DS home menu
2. Open NDS roms through TwiLightMenu
3.

**Comment by RocketRobz** [comment]
Did you install the latest CIAs as well?
If you did, are you using EmuNAND?

**Comment by m00nyONE** [comment]
i had the same problem on my DSi with unlaunch after i started TWM++ for the first time .. after 2 reboots it worked fine and never happend again.

**Comment by didakf** [comment]
Revisiting this problem after few months and updating TwiLight Menu to the latest version(8.4.0), it still doesn't work. I've rebooted my 3DS countless times. And no, I am not using EmuNAND.

**Comment by RocketRobz** [comment]
Well, it's likely the next version will fix your issue, as nds-bootstrap's next version now does the touch mode switch to NTR, and TWLMenu++ will start with TWL touch mode again.
