### ISSUE TITLE
"ROM read LED" don't work correctly

### ISSUE THREAD

**Issue by BaJIeHTuHbI4** [DS-Homebrew/TWiLightMenu#584]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Ulaunch 1.8 + HiyaCFW 1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.1.1]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

When you set "ROM read LED" to "WiFi", WiFi LED must blinking when reading ROM.
When you set "ROM read LED" to "Power", Power LED must blinking when reading ROM.

### Actual behaviour

When you set "ROM read LED" to "WiFi", Power LED is blinking when reading ROM.
When you set "ROM read LED" to "Power", WiFi LED is blinking when reading ROM.

### Steps to reproduce

1. Set "ROM read LED" to "Power" or "WiFi"
2. Load ROM
3. Blinking another, not selected LED

**Comment by RocketRobz** [comment]
This is normal, actually.
When WiFi LED is set, when a game does a normal read, WiFI LED blinks, and when a game does a DMA read, the Power LED blinks,
When Power LED is set, when a game does a normal read, Power LED blinks, and when a game does a DMA read, the WiFi LED blinks,
