### ISSUE TITLE
Cheats don't work properly.

### ISSUE THREAD

**Issue by GhostBelmont** [DS-Homebrew/TWiLightMenu#585]
Hi, i'm having a issue when i use a cheat code in TWLMenu. The first time that i activate the cheat, works normaly in the game, but when i quit and start the game again the code doesn't work. I have to restart the game multiples times until the cheat works again. Are there some configuration to be done on TWLMenu? I've downloaded the usrcheat.dat from DeadSkullzJr's Cheat Databases and the version is v2.2.0 and put in the extra directory of TWLMenu folder. Thanks!

**Comment by RocketRobz** [comment]
There's a bug in nds-bootstrap which only activates cheats sometimes.

**Comment by GhostBelmont** [comment]
Thanks for answer me! Just for me to know, will this be fixed on a future nds-bootstrap release?
