### ISSUE TITLE
Booting game without cheats removes usrcheat.dat and crashes the game

### ISSUE THREAD

**Issue by rootyElf** [DS-Homebrew/TWiLightMenu#590]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _[1.8]_
- [x]  Unlaunch+HiyaCFW _[1.8+can't remember exactly - happens without HiyaCFW as well,though ]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[not a TWLMenu++ version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

When a game is started from sd without any cheat enables, it should just run the game.

### Actual behaviour

When a game is started while a usrcheat.dat is present and without any cheats enabled, the usrcheat.dat gets removed. Also the game crashes and future attempts to boot any game also result in a crash until a game gets started from the "System Menu" launcher (not from the files menu). After a successful boot through the System Menu, other games can be booted again. (I am not 100% confident that this is always going to happen, but those are my observations)

### Steps to reproduce

1. put a usrcheat.dat into the extras folder
2. boot any game without cheats enabled (I have tested Mario Kart DS, PMD Time, Pokémon Black 2)
3. watch a white screen and find the usrcheat.dat being removed

**Comment by RocketRobz** [comment]
What theme are you using?

**Comment by RocketRobz** [comment]
Also, what you posted is the nds-bootstrap version, not the TWLMenu++ version.

**Comment by rootyElf** [comment]
Acekard Theme. Sorry, TWLMenu++ version is 8.2.2.

**Comment by RocketRobz** [comment]
Fixed in v8.2.3.

**Comment by rootyElf** [comment]
I see, thanks.
