### ISSUE TITLE
Cannot delete all of _nds, "gamesettings" folder denies deletion

### ISSUE THREAD

**Issue by MrGamerNaut** [DS-Homebrew/TWiLightMenu#592]
### Your console

Tell us which console do you have:

- [X ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

_nds can properly delete

### Actual behaviour

Operation denied
Sd card considered corrupted on some computers after attempted deletion

### Steps to reproduce

1.Uninstall all Twilight Menu++ titles via FBI to be safe
2.Delete _nds on a computer
3."Operation denied"/Error window
4.All _nds files are gone, except sdmc:/_nds/TwiLightMenu/gamesettings

**Comment by Epicpkmn11** [comment]
Did you ever use GBARunner2 without making the save files before running the games?
That can cause corruption, but other than that I can't really think of anything TWiLight could've done that would cause that...

**Comment by MrGamerNaut** [comment]
Possibly, I must have opened a gba rom that already had a save from a separate emulator (mgba)

**Comment by MrGamerNaut** [comment]
Ok solved, after running cmd in admin mode and inputting: "chkdsk (drive): /f" where "(drive)" is replaced with the microsd card drive letter (in my case, "E:"), it recovered all my files. When it outputted: "bad link in lost chain at cluster xxxxxxx" (which were the gamesettings files) multiple times, it asked if I wanted to store these files in a new folder with a Y/N prompt. I inputted "n", and the card was fully recovered, and the gamesettings files were deleted.
