### ISSUE TITLE
Any Hope to get the R4 Gold RTS/Plus to get the auto booting to work.

### ISSUE THREAD

**Issue by ghost** [DS-Homebrew/TWiLightMenu#593]
If any of you have a r4 gold rts/plus then try to debug it.

**Comment by Kodtiz3D** [comment]
Seems to have already being discussed in issue #576, although I would like this to be a feature it seems unlikely due to the card seemingly not natively supporting autoboot.

**Comment by NightYoshi370** [comment]
This is a clone of #576. Please use that instead.
