### ISSUE TITLE
Modify The S8DS Source 0.1 Source into a TwilLightMenu++ Optimized Sega Master System Emulator.

### ISSUE THREAD

**Issue by ghost** [DS-Homebrew/TWiLightMenu#594]
BTW The 0.1 Source is the only Sega Master System Emulator for DS Source Code in existence.
[S8DS01Src.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/3192354/S8DS01Src.zip)

**Comment by RocketRobz** [comment]
No thanks. Latest S8DS is working fine in DSi mode.
