### ISSUE TITLE
White screen after enabling cheats

### ISSUE THREAD

**Issue by zener88** [DS-Homebrew/TWiLightMenu#595]
When I enable some cheats on Pokemon Diamond/Pearl, spanish versión, it goes into an infinite white screen. Even if I disable the cheats, it still happens, no matter what theme I'm using. Also, after that, every time I try to access Pk Diamond cheats menu, the application crashes and send me to the 3ds main manu. I'm using a cfw, not a R4 card.

**Comment by MasterGamingYT** [comment]
Try holding L on boot

**Comment by MasterGamingYT** [comment]
Also make sure you're using the latest version
