### ISSUE TITLE
Nitrohax White screen issue when loading game with cheats(on all newest versions).

### ISSUE THREAD

**Issue by AngelCrft** [DS-Homebrew/TWiLightMenu#596]
Console: Dsi(latest firmware)
Unlaunch: Version 1.8(latest)
Cfw: Hiyah

Issue: I've tested nitrohax 0.94 and 0.99 with the hiyah cfw and they sucessfully load cheats but when i press start(to attempt to play the game i have on my ds slot) It shows in 1 frame weird black and glitched rectangles downwards in the top display screen right before it freezes on a white screen.

Ive followed all steps correctly and even retried the method by scratch and it still doesnt work

**Comment by RocketRobz** [comment]
This obviously isn't a TWiLight Menu++ issue.
Also, not all games work with NitroHax.
Try using cheats for ROMs on the SD card.
