### ISSUE TITLE
Pokemon Black White 1 & 2 whitescreen

### ISSUE THREAD

**Issue by haruyukihyo** [DS-Homebrew/TWiLightMenu#598]
In the last version of TWiLMenu(8.2.3), the Pokemon Black/White 1 & 2 don't run the game at start, only have a white screen, i used three roms one w/AP, other clean(no AP) and EUR rom w/AP and don't work, the cheat of AP bypass don't work

**Comment by takeshineale128** [comment]
put the menu in ds mode will fix the issue

**Comment by haruyukihyo** [comment]
What a silly boy i'm...
Thanks Black/White 1 & 2 works again

**Comment by NightYoshi370** [comment]
Not a twilightmenu++ issue.
