### ISSUE TITLE
Allow disabling bootup animations for application

### ISSUE THREAD

**Issue by rensenware** [DS-Homebrew/TWiLightMenu#599]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to get to my games as quick as possible, and I think a way to disable boot animations with a settings options would make the application feel cleaner.

**Describe the solution you'd like**
Allow boot animations such as the 'tap screen to continue' and other animations to be disabled in settings.

**Comment by SuperSaiyajinVoltZ** [comment]
You already can disable it in the Settings.

**Comment by vulpes-vulpeos** [comment]
Settings have several pages. Use L/R buttons.
