### ISSUE TITLE
Make Settings dependant on theme

### ISSUE THREAD

**Issue by FlameKat53** [DS-Homebrew/TWiLightMenu#602]
Here's an image of the DSi Settings Screen's bottom screen, the top screen wouldn't need to be changed too much, but I have an idea how we could change it if we needed to.
![image](https://user-images.githubusercontent.com/38171335/58269786-188ece80-7d3d-11e9-8077-ef3ae0dcec04.png)

Perhaps we could also have settings themes such as the 3DS settings screen if the 3DS theme was the theme being used. These themed settings screens would be nothing but a different look, all the settings would be on all the settings themes.

(that would look like this but in 256x192)
![image](https://user-images.githubusercontent.com/38171335/58269875-4d9b2100-7d3d-11e9-977c-422665ecf1a8.png)

This is an R4i settings screen, not the original R4.
![image](https://user-images.githubusercontent.com/38171335/58270052-c26e5b00-7d3d-11e9-8592-4d94bce0514a.png)

Lastly, the Acekard settings screen could look like this.
![image](https://user-images.githubusercontent.com/38171335/58270083-d31ed100-7d3d-11e9-9b43-2cf837ef854f.png)

**Comment by FlameKat53** [comment]
Oh, note that the 3DS Transfer Tool app for DSi has some graphics you might be able to use for the 3DS Settings thingy

**Comment by FlameAlt53** [comment]
continuing on the previous comment, CARDBOARD (3DS Transfer Tool) also has a prompt bubble which, well, looks much better than the current one :p

**Comment by NightYoshi370** [comment]
This seems to be partially implemented for the new Saturn theme

**Comment by FlameKat53** [comment]
Since this is partally implimented in the staurn theme, I will close this as I don't really like this idea anymore :p

**Comment by FlameKat53** [comment]
''input is required'' (sorry for double post)
