### ISSUE TITLE
Add a scroll bar (visual only) in the 3DS theme

### ISSUE THREAD

**Issue by FlameKat53** [DS-Homebrew/TWiLightMenu#603]
Here's what I am talking about, it's under the top row icons (Such as Miiverse and the Friends List) (in this gif it's under the Home Menu Settings icon)
![image](https://66.media.tumblr.com/6ecbf20db66eb68d62a4970871dca78e/tumblr_ndacpubD8x1qzp9weo1_640.gif)

Please notice the bar fades away when not scrolling, this is a minor thing but something important for authenticity.

**Comment by FlameKat53** [comment]
(lines)
<https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_dsimenutheme/arm9/source/graphics/graphics.cpp#L615> to <https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_dsimenutheme/arm9/source/graphics/graphics.cpp#L635>

You could copy & paste this code then modify it for the scroll bar in the 3ds theme.

**Comment by FlameAlt53** [comment]
so the above commit I tried to as such and it white screened...
(alt account because the school has keyloggers)

**Comment by FlameKat53** [comment]
Oh, i might've used a flashcard for that or something and that's why it whitescreened.
But probably because I didn't do it correctly in the slightest

**Comment by NightYoshi370** [comment]
Lets merge this with #749 since it feels more complete there
