### ISSUE TITLE
Only my 16GB card functions

### ISSUE THREAD

**Issue by alivebacon** [DS-Homebrew/TWiLightMenu#604]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _[please specify version]_  Unlaunch 1.8
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_   8.2.3
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Tell us what should happen
It works as normal on my 4GB card.

### Actual behaviour

Tell us what happens instead
I whitescreen completely at boot unless I use my 16GB card.

### Steps to reproduce

1. Get the current version of TWLMenu++ onto a 4GB card
2. Boot it on DSi
BTW, how do u switch sd at boot?

**Comment by RocketRobz** [comment]
You can skip booting HiyaCFW, and go straight into TWLMenu++.
