### ISSUE TITLE
Ram Viewer error?

### ISSUE THREAD

**Issue by TacosOfficial** [DS-Homebrew/TWiLightMenu#605]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[Latest]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

When i open an game, after 2 minutes it crash and i see an "RAM VIEWER" text in green and an ram editor.... all of this with blue and green colors

**Comment by TacosOfficial** [comment]
i think this is an twilight menu++ error because the game start and i don't see any error in the boot screen

**Comment by edo9300** [comment]
What game are you trying to launch? This looks more like a crash of the game, and probably it's not related to twilightmenu but rather to https://github.com/ahezard/nds-bootstrap

**Comment by TacosOfficial** [comment]
No... The game is NSMB... when i open it doesn't crash... when i connect with another console with versus mode doesn't crash, but when i select the map to play it show the "RAM VIEWER"

**Comment by arraystock** [comment]
This is related to nds-bootstrap.
