### ISSUE TITLE
Guru Meditation Error when loading Pokemon White 2.

### ISSUE THREAD

**Issue by Dragonfirepie** [DS-Homebrew/TWiLightMenu#607]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ X]  Release _v8.2.3_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

When i load Pokemon White 2, it should boot into the game, provided other issues are not present.

### Actual behaviour

Loading results in a "Guru Meditation Error! Data Abort!"

### Steps to reproduce

1.Open TWilight Menu++
2.tap the Arrow in the Corner
3.attempt to boot Pokemon White 2.

**Comment by RocketRobz** [comment]
The Acekard theme has bugs. Try switching to another theme.

**Comment by Dragonfirepie** [comment]
Don't close my post with just that, I'm not using the Acekard theme.

**Comment by RocketRobz** [comment]
What are you using then?

**Comment by Dragonfirepie** [comment]
I was using the DSi theme, then i tried the 3DS theme, i didn't try Acekard because i had heard it was buggy anyway.

**Comment by Dragonfirepie** [comment]
I can actually try to run it with the R4 menu, but it says that ndsbootstrap is missing.

**Comment by Dragonfirepie** [comment]
Got it to work! I just needed to boot it through the R4 menu.
