### ISSUE TITLE
CheatData.bin not showing after enabling cheats and white screens on most of the games with cheats (I.e AP patch code)

### ISSUE THREAD

**Issue by zeroultima6** [DS-Homebrew/TWiLightMenu#608]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [*]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [*]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [*]  Release _8.2.3_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [x]  3DS HOME Menu
- [x]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen

Games should work with cheats enabled

### Actual behaviour

Tell us what happens instead

White screens on most of them with cheats enabled

### Steps to reproduce

1.
2.
3.

**Comment by chronoss09** [comment]
Where to find CheatData.bin file fr test ?

**Comment by zeroultima6** [comment]
In the nds-bootstrap folder but its not there for me

**Comment by NightYoshi370** [comment]
That isn't a twilight issue
