### ISSUE TITLE
Guru meditation error when loading several pokemon roms

### ISSUE THREAD

**Issue by SilverGuardian** [DS-Homebrew/TWiLightMenu#611]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.2.3]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [x]  3DS HOME Menu
- [x]  R4
- [x]  Acekard/akMenu

### Expected behaviour

Tell us what should happen

The game should load and create a save file

Tell us what happens instead
I get a guru meditation error
### Steps to reproduce

1. Enter Twilight menu
2. Load game

I cycled through all the themes, re-installed twilight menu and the latest version of nds bootstrap. The roms appear on the rom selection menu, I load the games and get the error

![IMG-6237](https://user-images.githubusercontent.com/51215670/58669259-93418600-8309-11e9-84ec-04420371a37a.JPG)

**Comment by RocketRobz** [comment]
Can be fixed by turning off `Update recently played list`.
