### ISSUE TITLE
Pokemon Black/White 2 white screen (ds mode does not help)

### ISSUE THREAD

**Issue by GamerVI** [DS-Homebrew/TWiLightMenu#612]
Your console
Tell us which console do you have:

  DS Phat/Lite
  DSi (XL)
  Old 3DS/2DS (XL)
  [x] New 3DS/2DS (XL)
CFW and configuration
Tell us which CFW do you have:

DSi:

  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
  (No CFW) Unlaunch only [please specify version]
  Unlaunch+HiyaCFW [please specify versions of both]
3DS/2DS:

  [x] Luma3DS
  Rei-Six
  Other CFW [specify]
  Older CFW
TWiLight Menu++ version
Tell us which versions you are using:

  [x] Release [8.2.3]
  Nightly [insert here commit hash]
TWiLight Menu++ theme
Tell us which theme you are using:

  DSi Menu
  [x] 3DS HOME Menu
  R4
  Acekard/akMenu

When I try to start Pokemon White 2, the launcher stuck in a white screen

i've seen in an other issue tab that says put ds mode on should help but for me its not working

**Comment by RocketRobz** [comment]
Do you have cheats turned on?

**Comment by NightYoshi370** [comment]
Not a TWiLight issue
