### ISSUE TITLE
ZXDS Emulator

### ISSUE THREAD

**Issue by Nigey777** [DS-Homebrew/TWiLightMenu#613]
When i launch this emulator it just sits on waiting to load.
Would be great to have this running in TWiLightMenu on DSi and 3DS

**Comment by NightYoshi370** [comment]
Press Y, and tell us if Direct Boot is turned on or off

**Comment by RocketRobz** [comment]
If it is already turned off, then you'll need a RAM disk created for the emulator to work.

**Comment by Nigey777** [comment]
How do I create a RAM disk???

**Comment by trlkly** [comment]
Directions are available in [the GBATemp post](https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/).
