### ISSUE TITLE
Add support for CIA'd PictoChat on 3DS

### ISSUE THREAD

**Issue by tomrow** [DS-Homebrew/TWiLightMenu#619]
I have a New Nintendo 3DS running LumaCFW, and I have installed PictoChat onto it using a CIA file. In TWiLightMenu++'s quick menu the PictoChat button is disabled on 3DS systems (for likely obvious reasons). It would be nice if there was a way to configure the menu to run that PictoChat title (or a SRL dump of it) when the button is pressed.

**Comment by RocketRobz** [comment]
Trim the first 0x3900 bytes off the CIA, then save it as `pictochat.nds` at `sd:/_nds`/

**Comment by tomrow** [comment]
Did I do this right? The first 16 bytes are now `506963746F4368617400000041335353`.

**Comment by tomrow** [comment]
I tried it and it booted into PictoChat (my hex editing was OK i think), but I encountered a strange error message that I've never seen before. It's in the standard DS error box style with the orange border and grey background.

`Communication error.`
`The Nintendo DS will now shut down.`

**Comment by Javier107** [comment]
That happens when Pictochat is launched using nds-bootstrap OR the title id of the game is wrong. Most likely you got the wrong TID bc iirc TWLMenu++ don't allows you to launch Pictochat using nds-bootstrap anymore but instead launches it normally

**Comment by Javier107** [comment]
For fix it open the .nds of pictochat using a hex editor and place the following values from the offset 0xC to 0xF : 48 4E 45 41

**Comment by tomrow** [comment]
It works! Thank you very much! Is there a way to run nds files as if they were DSiWare without fiddling with the files in a Hex editor? Is there some sort of configuration file I can change because when I try to run backups of e.g. Petit Computer or Flipnote Studio, they freeze at a white screen when selected.

**Comment by Javier107** [comment]
Im glad it worked. About the DSiWares i didn't understood very well what you wanna do. You wanna run DSiWares from TWLMenu++ or run nds files from the home menu?

**Comment by tomrow** [comment]
I'd like to run DSiWare form TWLMenu

**Comment by Javier107** [comment]
Not possible unless they are homebrew dsiware.

**Comment by tomrow** [comment]
I see. Thank you for your help anyway!

**Comment by Javier107** [comment]
Np :+1:
