### ISSUE TITLE
Muted intro.

### ISSUE THREAD

**Issue by Javier107** [DS-Homebrew/TWiLightMenu#620]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS 9.1
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v8.2.3]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

The intro should always have sound when the console is not muted

### Actual behaviour

If i launch TWLMenu++ with the sound muted and when the intro starts I quickly set the sound to max the audio of the intro won't reproduce like it always does (and is not because my 3DS still muted, I made sure of that, and even after the intro i can hear the DSi Shop music)

### Steps to reproduce

1. Launch TWiLight Menu++ with the sound muted
2. When the splash screen of "health and safety" vanishes quickly set sound to max and you'll notice no sound plays.

**Comment by RocketRobz** [comment]
Doesn't seem to happen for me.
