### ISSUE TITLE
Return to menu (L+R+down+B) always crashes the O3DS

### ISSUE THREAD

**Issue by Stooovie** [DS-Homebrew/TWiLightMenu#621]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:
3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using: 

- [X]  Release _[please specify version]_8.3.0
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [X]  Acekard/akMenu

### Expected behaviour

L+R+down+B quits game, reloads TWLmenu

### Actual behaviour

L+R+down+B quits game, crashes the unit
https://i.imgur.com/x8Lnf2s.jpg

### Steps to reproduce

hold L+R+down+B while in-game

**Comment by SuperSaiyajinVoltZ** [comment]
You don't have `Enable Game Patching` In the Luma Settings on. Put it on and it is fixed.

**Comment by montoulieu** [comment]
@SuperSaiyajinVoltZ 's suggestion worked for me on a new 3DS Xl.

Thank you!

**Comment by ErdbeerbaerLP** [comment]
For me it always reboots into home menu, patching and such is all enabled! (o3ds)

**Comment by luis0088** [comment]
> You don't have `Enable Game Patching` In the Luma Settings on. Put it on and it is fixed.

I have N3DS XL, Luma v10.1, TWiLight Menu++ v11.1.0 and this doesn't work for me.

**Comment by NightYoshi370** [comment]
It works for me and many more people in the comments section.
I have a O3DS and it works

Closing
