### ISSUE TITLE
***The ability to swap screen when playing GBARunner2***

### ISSUE THREAD

**Issue by PrimaryShooter** [DS-Homebrew/TWiLightMenu#622]
I believe a great feature to add to GBARunner2 would be the ability to swap screens. For example, instead of using the top LCD screen, I would like to use the bottom. I say this because my LCD on my Dsi is broken. I wish there was an option to switch screen screens to touch screen.

Since with the recent update, we now have a UI for GBARunner2. The solution is to implement an option for switching screens. Hopefully it isn't much of a hassle to implement.

**Comment by RocketRobz** [comment]
It is planned.
Also, GBARunner2 has it's own repo, so please post an issue there, next time.
