### ISSUE TITLE
crackling sound after closing the console

### ISSUE THREAD

**Issue by graziel666** [DS-Homebrew/TWiLightMenu#624]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ X ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ X ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ X ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

sleep mode working correctly

### Actual behaviour

the sound gets bugged and crack, also my batery drains extremely fast when that happens

### Steps to reproduce

1. start a game
2. close the console
3. and tadaaa bye bye batery

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, not a TWLMenu++ issue.
Certain flashcards in Slot-1 make sleep mode not work in nds-bootstrap.
Exit the game, and either take out the flashcard, or turn on force sleep patch in TWLMenu++ settings.
