### ISSUE TITLE
problems with the headphones

### ISSUE THREAD

**Issue by xdragonicx** [DS-Homebrew/TWiLightMenu#626]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
There's the issue: DSiWarehax.
Please install Unlaunch and boot TWLMenu++ with it, to fix the headphones issue.

**Comment by xdragonicx** [comment]
In the last updates the problems of the headphones were solved, now I can enjoy the sound better. Greetings from South America Chile. TWiLightMenu v8.5.1. Thank you
