### ISSUE TITLE
Cheats in general

### ISSUE THREAD

**Issue by BerserkJoker66** [DS-Homebrew/TWiLightMenu#628]
I'm frustrated trying to get cheats to work on TwilightMenu because they won't load and its very difficult for them to be used. Its also very confusing on how to get them on there in the first place. I would like to see an improvement on how cheats are loaded so that they are easily accessible and preferably being able to access them during gameplay. Another thing I would like to see added in the future is fast forward because most games are a bit slow paced I would like that to be implemented maybe. Though TwilightMenu has seen a lot of improvement lately so I'm glad its at least being worked on.

**Comment by arraystock** [comment]
Unfortunately, it’s impossible to enable/disable cheats on the fly, as well as to fast forward games AFAIK.

TwilightMenu configures nds-bootstrap, which patches your rom with saving patches (and cheats passed to it) to allow the game to read/write it’s save data from a file on the SD (simplified explanation).

**Comment by edo9300** [comment]
Fast forward would be pratically impossible to do, as games aren't being emulated, also to fast forward a game, the CPU should be ale to go faster, same for other stuff, but when you're running on the same hardware, there's no way to make the CPU go faster than its maximum speed. @arratstock _that's pretty simplified_ actually the bootstrap redirects all the reads/writed done to the slot-1 (the game cart) to the SD card

**Comment by NightYoshi370** [comment]
They are easily accessable.
Every theme can access them very easily.

Also, fast forward is a thing that is handled by nds-bootstrap, not twilight.
Closed issue
