### ISSUE TITLE
KH 358/2 Days Freezes after picking a difficulty

### ISSUE THREAD

**Issue by Angelixia** [DS-Homebrew/TWiLightMenu#629]
I have been looking for a fix for days but I can't seem to find one since the threads are old and most of the links that were useful were already removed so I had to ask here.
I have my rom downloaded and when I tried to boot it in TwilightMenu++ (fully updated luma, fbi and godmode, New 3DS XL) it freezes on a black screen and nothing happens. If I try to hex or use DS-Scene it gives me the "guru meditation error data abort" screen. Anyway to fix this?

**Comment by RocketRobz** [comment]
Are you using the Acekard theme?

**Comment by Angelixia** [comment]
How do I check the theme I am using? Sorry kind of a novice 3DS user

**Comment by Angelixia** [comment]
Found it. No I'm not using Acekard

**Comment by NightYoshi370** [comment]
It seems as if it's a bad ROM dump. Please try dumping it again.
Also, for game related issues, please use the nds-bootstrap repository

**Comment by Angelixia** [comment]
Just wanted to update. The issue can be fixed by inserting any cart on the cart slot. I'm using a flash cart and it's already working. Also, thanks for redirecting me to the nds repo!
