### ISSUE TITLE
Not exiting on L + R + DOWN + B press

### ISSUE THREAD

**Issue by theoneandonlyjustin** [DS-Homebrew/TWiLightMenu#630]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.4.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Exit back to TWiLight Menu on L + R + DOWN + B

### Actual behaviour

Nothing

### Steps to reproduce

1. Open ROM (tested with SMB, SMB3, SMW)
2. Press/Press and hold L + R + DOWN + B
3. Nothing; game continues running

**Comment by RocketRobz** [comment]
You hold it, not press it.

**Comment by theoneandonlyjustin** [comment]
How long do you need to hold it down? I've tried up to 30 seconds already.

**Comment by RocketRobz** [comment]
Oh, I overlooked the ROMs you're trying.
The button combo only works on DS games.

**Comment by theoneandonlyjustin** [comment]
Is there any way to exit from NES/SNES without soft resetting?

**Comment by RocketRobz** [comment]
No, there isn't.
