### ISSUE TITLE
Animal Crossing not saving 

### ISSUE THREAD

**Issue by cryopotato** [DS-Homebrew/TWiLightMenu#631]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ bleh ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ latest as of now ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ i think this one? not quite sure. ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ dis ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen:
when i "save and quit to menu" in animal crossing wild world, it should save

### Actual behaviour

Tell us what happens instead:
when i play animal crossing wild world, it dont save. in this particular game, you have to "go to bed" and save. you can only save and quit to menu, there is no option to save an continue. i heard from some googling that this might be related? not sure. literally as soon as i get to the menu of the game, theres not even an option to continue. it just.... didnt save. theres a .sav file in the save folder but its extremely small compared to the others. im pretty sure it contains little to no data at all.

### Steps to reproduce

1. start the game from scratch
2. create character and complete tom nook's tutorial-ish thing until the game allows you to save
3. go to the bed in the house to save
4. select "save and quit" the only option
5. it takes you to the games main menu
6. find out theres no option to continue, just an option to start a new game
7. ok
8. cry

**Comment by RocketRobz** [comment]
What's the file size of your .sav file?

**Comment by cryopotato** [comment]
i think it was 5kb or something like that... i remember the other .sav files having like 3 digits and the animal crossing one just had 1.

**Comment by RocketRobz** [comment]
That may very well be why it's not saving.
Delete the .sav file, and have TWiLight Menu++ create it again.
By default, it creates a 512KB save file.

**Comment by cryopotato** [comment]
got it. ill give you an update soon

**Comment by cryopotato** [comment]
ohdamnitworked
i havent checked if its able to save yet but the .sav is the same file size as everything else now :)
thamks robo !!!
