### ISSUE TITLE
Use 3ds ir module in games that use IR

### ISSUE THREAD

**Issue by fennectech** [DS-Homebrew/TWiLightMenu#632]
**Is your feature request related to a problem? Please describe.**
Using games that have an internal IR emitter without a cart is impossible making use of things like pokewalker useless without a cart or with a knockoff cart.

**Describe the solution you'd like**
we could use the 3ds's internal IR transceiver 

**Describe alternatives you've considered**
using their transmitters in other carts is possible  but a non-optimal solution as it requires buying other carts that may be just as rare if not rarer than the game you want to play.

**Additional context**
not really.

**Comment by RocketRobz** [comment]
That requires reverse-engineering TWL_FIRM, so it might not happen.
