### ISSUE TITLE
All slot-1 cards/software freezing on white screen

### ISSUE THREAD

**Issue by theoneandonlyjustin** [DS-Homebrew/TWiLightMenu#633]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi XL
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[unlaunch: can't check hiya: v3.3]_

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.4.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tested with: DSTTi, Cars 2, Scribblenauts, hiya, unlaunch installer, GBArunner2 (boots into gameboy logo then freezes)

Can boot: NES/SNES roms

*Can boot all slot-1 cards via DSi menu*

### Actual behaviour

Freeze on white screen

### Steps to reproduce

1. Boot into TWLmenu fine
2. Try to play NES/SNES roms (it works fine)
3. Try to boot into slot-1 or GBArunner2 (white screen freeze)

**Comment by RocketRobz** [comment]
The Slot-1 cards and GBA ROMs you tried, are not compatible. Slot-1 cards that have `TWL` on the sticker, will not work. 
Most NTR Slot-1 cards and GBA ROMs do work, so that doesn't mean all of them don't work.

**Comment by theoneandonlyjustin** [comment]
What about homebrew software? I can't boot into hiya or unlaunch from TWLmenu.

**Comment by RocketRobz** [comment]
They're not supposed to be launched from TWLMenu++.
