### ISSUE TITLE
multiplayer problem

### ISSUE THREAD

**Issue by inkknightzx** [DS-Homebrew/TWiLightMenu#634]
im having trouble playing multiplayer agian on the twilight menu. when i start a local game with my brother the wifi bars are not showing and he can't connect. why is that?

**Comment by SuperSaiyajinVoltZ** [comment]
It's a NDS-Bootstrap Issue and it does not work, because Clone Boot isn't implemented yet.

**Comment by inkknightzx** [comment]
so i got to wait for there to be another update before i can play multiplayer again locally?

**Comment by SuperSaiyajinVoltZ** [comment]
You may Need to wait a while.

**Comment by inkknightzx** [comment]
okay thanks.
