### ISSUE TITLE
Settings don't load on R4 Flashcart

### ISSUE THREAD

**Issue by froggestspirit** [DS-Homebrew/TWiLightMenu#635]
After updating to version 8.4.0, using an R4 Gold Pro (YSMENU firmware), settings for TwilightMenu do not load.

-The settings all save and load on the settings menu to what they were set to, however most of them don't apply.

For example, the default theme is dark DSi, folders showing. I set this to DSi white, hidden folders and left the menu. TM reboot, still with the dark theme and folders. Going back into settings show that it is set to white with folders hidden (I also tried a hard reboot with the same results).

The odd part is that the settings for the splash screens and the DS pre-menu save, as I disabled these and TM does skip them as intended. (I also successfully re-enabled them).

**Comment by arraystock** [comment]
Hm, it’s like your settings aren’t being loaded by the theme(s), but they’re being loaded by everything else.

**Comment by froggestspirit** [comment]
I didn't want to say theme specifically since the folder option might not
be classified as theme. This was working on an older version, though I dont
know which update it broke in.

**Comment by RocketRobz** [comment]
v8.4.0 hasn't been tested on flashcards 'til now.
The settings aren't being loaded by the DSi/3DS theme.
This bug will be fixed in the next version.
