### ISSUE TITLE
Can't change to 3ds and dsi(other color) themes with r4iGold card

### ISSUE THREAD

**Issue by megabitsenmzq** [DS-Homebrew/TWiLightMenu#636]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.4.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Change to 3ds and dsi(other color) themes with r4iGold card. It should change.

### Actual behaviour

The settings has been changed, but menu theme is stuck in DSi black. Change to ak/r4 theme works properly.

### Steps to reproduce

1.Install
2.Change menu theme to 3DS in the settings.
3.Back to main menu.

**Comment by RocketRobz** [comment]
Will be fixed in the next version.
