### ISSUE TITLE
nds rom bug

### ISSUE THREAD

**Issue by fuckyouyu** [DS-Homebrew/TWiLightMenu#637]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[3.1.0]_
- [x]  Nightly _[#.1.0]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen
i go to the rom and boot it and it sould start it up 
### Actual behaviour

Tell us what happens instead
i boot the rom and it redirects me to the power off menu 
### Steps to reproduce

1.
2.
3.

**Comment by SuperSaiyajinVoltZ** [comment]
Issues with ROMs are for NDS-Bootstrap. TWiLightMenu is just the frontend.

**Comment by fuckyouyu** [comment]
ok but can you still help me with this

**Comment by RocketRobz** [comment]
The release number you said is the updater version, not the actual app's version.
