### ISSUE TITLE
(L+R+DOWN+B) Returns to 3ds menu

### ISSUE THREAD

**Issue by RogueDXZ** [DS-Homebrew/TWiLightMenu#640]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _v8.4.0_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [x]  Acekard/akMenu

### Expected behaviour

(L+R+DOWN+B) Returns to TWiLight Menu

### Actual behaviour

(L+R+DOWN+B) Close TWiLight Menu and it returns to 3DS menu

### Steps to reproduce

1. Open TWiLight Menu
2. Open any NDS game
3. Do (L+R+DOWN+B)
(I have the Game Patching Enabled)

**Comment by RocketRobz** [comment]
It won't always work.
It takes some tries for it to work.
