### ISSUE TITLE
o3DS: Touch screen stopped working after update 8.5.0. (Only TWLMenu, not NDS-bootstrap)

### ISSUE THREAD

**Issue by YYoshi241** [DS-Homebrew/TWiLightMenu#643]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:
3DS/2DS:

- [X]  Luma3DS (9.1, 9.1-f4852cd5)
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[8.5.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [X]  3DS HOME Menu
- [X]  R4
- [X]  Acekard/akMenu
- [X] Quick Menu
### Expected behaviour

Touching the touch screen does stuff.

### Actual behaviour

Nothing happens. 

### Steps to reproduce

1.Launch TWLMenu++ (boot.nds, launcher or directly)
2.Try to use the touch screen

NOTE: This doesn't affect nds bootstrap. And I am running this from SD. Tried this on BOTH of my o3DS's and the same result. This DID NOT
happen in the last release (8.4.0). 
Also I haven't tried a flashcard since I don't own one.

**Comment by RocketRobz** [comment]
You have to install the latest CIAs for touch to work again.

**Comment by YYoshi241** [comment]
Thanks
