### ISSUE TITLE
System Settings option in TwilightMenu++ Settings

### ISSUE THREAD

**Issue by Boured** [DS-Homebrew/TWiLightMenu#645]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[1.8 & 1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.5.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Upon hitting A on the System Settings option located in the Misc. Settings of TwiLightMenu++'s settings, the screen should go dark, then white for a few moments and then load the System Settings application on the DSi. It should also take into account that you're using a SDNAND, using the settings on the SDNAND as such.

### Actual behaviour

Upon hitting A on the System Settings option loacated in the Misc. Settings of TwiLightMenu++'s settings, the screen goes dark, then white before quickly showing the top screen a solid green color, and the bottom screen a solid blue color for a few moments. Then three things should happen, either TwilightMenu++ reboots to the quick/DSi Theme menu, or the System Settings option is launched, however it is on SysNAND instead of SDNAND (Found due to my SysNAND's profile name being "SysNAND"). Finally, it will just hang on a white screen.

### Steps to reproduce

1. Launch TwiLightMenu++
2. Head to Settings
3. Head to Misc. Settings
4. Select System Settings at the bottom of the options.
5. The reported issue should happen.

**Comment by dazzaXx** [comment]
Also getting this issue on v9.0.1 Release

**Comment by NightYoshi370** [comment]
I think this is intentional
