### ISSUE TITLE
Attempting to enable cheats for games that have a long cheat list reboots twilight menu

### ISSUE THREAD

**Issue by MasterGamingYT** [DS-Homebrew/TWiLightMenu#646]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
*  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

*  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
*  Latest Nightly

### TWiLight Menu++ theme

Tell us which theme you are using:

*  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

It should load the cheats list

### Actual behaviour

It reboots Twilight menu when it even tries to load it

### Steps to reproduce

1. Pick a game that has a really long cheat list (Such as Animal Crossing: Wild World, and Pokemon Black 2)
2. Open the cheats list
3. It reboots without warning

**Comment by RocketRobz** [comment]
Try the latest release instead.

**Comment by NightYoshi370** [comment]
Can you try this on the latest TWiLightMenu++ nightly?

**Comment by MasterGamingYT** [comment]
no longer reproduceable
