### ISSUE TITLE
Can't change theme

### ISSUE THREAD

**Issue by Keeganab** [DS-Homebrew/TWiLightMenu#649]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [+ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [+ ]  Unlaunch+HiyaCFW _[3.4]_ 

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [+ ]  Release _[*v8.5.0*]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [+ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen

### Actual behaviour

I change theme to 3DS Home Menu and disable screen with last played game, settings, download play etc.  I can not enter the settings anymore to change again theme. In the DSI theme, I click the select button, but this does not work on 3DS theme. 

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
So does touching the wrench button on the touch screen not work?

**Comment by Keeganab** [comment]
Yes, the touch does not work. Normally works in a standard menu.

**Comment by RocketRobz** [comment]
Follow the DSi CFW update guide here: https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-update-TWiLight-Menu
It seems you don't have the TWLMenu++ .app files from the latest version.

**Comment by Keeganab** [comment]
I have latest v8.5.0.

**Comment by RocketRobz** [comment]
I know, but you probably don't have the .app files from the latest versions.

**Comment by Keeganab** [comment]
Ok, I will try to update

**Comment by chyyran** [comment]
@Keeganb please confirm this bug still occurs on the latest version

**Comment by NightYoshi370** [comment]
Apparently, this doesn't occur on the latest. Even if it did, this seems like more of a support thing rather than an issue. Closing
