### ISSUE TITLE
Issue getting games to boot

### ISSUE THREAD

**Issue by Hi-C-Enthusiast** [DS-Homebrew/TWiLightMenu#652]
Tell us which console do you have:

  DS Phat/Lite
  DSi (XL)
  [*] Old 3DS/2DS (XL)
  New 3DS/2DS (XL)
CFW and configuration
Tell us which CFW do you have:

DSi:

  HiyaCFW
Not using CFW / Unlaunch only
  Not using CFW / DSiWarehax
3DS/2DS:

  [*] Luma3DS
  Rei-Six
  Other CFW [specify]
  Older CFW
TWiLight Menu++ Launcher version (ignore, if you're using DS/DSi)
This launches TWiLight Menu++ on 3DS/2DS.

Tell us which versions you are using:

 [*]  Release [please specify version] v3.1.2
  Nightly [insert here commit hash]
TWiLight Menu++ version
Tell us which versions you are using:

  Release [please specify version]
  Nightly [insert here commit hash]
Expected behaviour
The Game(Pokemon white, White 2 & Platinum specifically are the ones I tried but i assume my issue would be universal across all games on my 3ds) should boot completely and run fine
Actual behaviour
When the game attempts to boot and fails, resulting in error 1, nds bootstrap not found i believe was the exact wording, despite the fact that i have the .ini file in the _nds directory on my sd card

Steps to reproduce

1. install the latest updater & menu
2.Open the TWiLight Menu, and once it boots to the default DS home screen, tap the small arrow
3.Scroll to the nds files, attempt to boot one of the three games listed

Additional note: I'm very new to attempting to do things like this and its very likely i might be missing something simple in a way to fix it that i simply cannot find.

**Comment by RocketRobz** [comment]
Download [nds-bootstrap](https://github.com/ahezard/nds-bootstrap/releases).

**Comment by RocketRobz** [comment]
btw, games should be run in DS mode.

**Comment by Hi-C-Enthusiast** [comment]
Alrighty thank you it worked, it was already in DS Mode, just needed those extra files!
