### ISSUE TITLE
Cheats fail to work

### ISSUE THREAD

**Issue by bloggingninja** [DS-Homebrew/TWiLightMenu#653]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[8.5.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

You should select cheats for a game and have them work.

### Actual behaviour

Activating Cheats for a game either causes the game to not load or the game loads and the cheats do not work. 

Cheats cause game to not load:
Pokemon Black
Pokemon Black 2

Game loads but cheats fail to work
Monster Rancher DS

### Steps to reproduce

1.start TWiLight Menu++
2.Go to game
3.Press Y
4.Press X (enter cheat menu)
5.Select any cheat
6.Press X (save cheats)
7.Start Game
8a. for Pokemon Games see white screen and game never loads
8b. for Monster Rancher DS any cheats requiring button presses do nothing when buttons are pressed.

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, not a TWLMenu++ issue.
