### ISSUE TITLE
what game formats TWilight Menu does support??

### ISSUE THREAD

**Issue by PedroxTheBest99** [DS-Homebrew/TWiLightMenu#654]
hello, i'm Pedrox and i have a question: What games formats TW Menu support? beacuse i want to play UNO™ and i only got a .app and a .cia, nothing about .NDS, does TW Menu supports .cia or .app?, thanks ^^

-Pedrox

**Comment by Epicpkmn11** [comment]
You can rename the `.app` to a `.nds` and it will work in TWiLight

**Comment by RocketRobz** [comment]
Just rename `.app` to `.nds`.
