### ISSUE TITLE
(Question) Can't seem to compile by myself?

### ISSUE THREAD

**Issue by ismailhasannnnnn** [DS-Homebrew/TWiLightMenu#655]
I'm trying to compile TwiLightMenu by myself, as I've made a change to the source code to fit my liking, but whenever i use the compile.bat, or compile_docker.ps1 (I've installed Docker, by the way) it goes through fully, but I don't seem to be getting any output. I know compile is different from build, so is there something I'm missing here?

**Comment by chyyran** [comment]
it should give you `romsel_[something].nds`. Rename this to an `*.srldr` file.

**Comment by ismailhasannnnnn** [comment]
Should it be in the root of the folder? Because if it should, it's not there.

**Comment by arraystock** [comment]
I believe files are output in the ‘7zfile’ directory, in their proper locations as they would be in a release .7z file. Can’t remember for sure, I’m not at my computer.

**Comment by ismailhasannnnnn** [comment]
In the '7zfile' directory, I've only got two folders. '_nds' and 'roms'. Under the '_nds' directory, it seems to just be the themes, and nothing else.

**Comment by ismailhasannnnnn** [comment]
well i got it to compile, but it seems like it only compiles for the DSi version, and not the 3DS version, which is what i need

**Comment by arraystock** [comment]
Both the 3DS and DSi run the same version, they are just launched through different methods.

**Comment by ismailhasannnnnn** [comment]
Oh, okay. so how do i put my own compiled build on my 3ds? since so cia
files were generated. just a bunch of sldrs files and the boot.nds

**Comment by Epicpkmn11** [comment]
Unless you modified any of the `booter` folder code you don't need the cia. If you did you should be able to make a cia out of `boot.nds`

**Comment by NightYoshi370** [comment]
In order to create a CIA, you would need Python 2.7 installed.
The application as far as I'm aware does not work on Python 3.X
