### ISSUE TITLE
Cannot seem to be able to launch some apps (even system ones) via Twilightmenu++

### ISSUE THREAD

**Issue by lorecast162** [DS-Homebrew/TWiLightMenu#657]
I updated my DSI XL 1.4.5E to Twilightmenu++ from 6.3.0 to 8.5.1 and learned to need to use appgen.exe instead of launcharggen.exe
Premise: everything worked fine before I updated
So, I updated TWLMenu++, then Unlaunch from 1.2 to 1.9 and made .nds launchers for my dsiware and system channels.
Pictochat, DS download, Pop Island Paperfield and a dsiware I downloaded from the internet that I had before but cancelled and didnt reinstall before dsi shop was closed all throw a guru meditation error.
System Settings, DSi Shop, DSi Browser, DSi Camera, DSi Sound, Flipnote Studio, Dictionary 6in1, Mario v DK, Brain Training, Zelda Four Swords, Nintendo DSi + Internet and myDiary all work, some had to rebuild save data and stuff but then worked fine after that.
Petit Computer goes to a white screen and freezes.
If I disable autoboot in HiyaCFW and use the stock dsi menu there are no issues whatsoever.
What could be wrong here?

**Comment by lorecast162** [comment]
so, uhh, can anyone help me here?

**Comment by RocketRobz** [comment]
Are you using the Acekard theme?
It's not stable, if so.

**Comment by lorecast162** [comment]
Yes I'm actually using that one, are R4 and DSi ok?

Il giorno mer 3 lug 2019 alle ore 19:14 RocketRobz <notifications@github.com>
ha scritto:

**Comment by RocketRobz** [comment]
Yes.

**Comment by lorecast162** [comment]
Alright, using the DSi theme I don't get any guru meditation errors anymore but Pop Island now shows me a "An error has occurred" screen with the NDS_BOOTSTRAP logo, is compatibility maybe an issue?
Also, Petit Computer still white-screens and now Zenonia does too. They work just fine from the stock DSi Launcher tho. I'm guessing another kind of compatibility issue here?

**Comment by RocketRobz** [comment]
What are the TIDs for Pop Island, Petit Computer, and Zenonia?
Press Y on the games in TWLMenu++ to check.

**Comment by lorecast162** [comment]
Pop Island: KPFP
Petit Computer: KNAP
Zenonia: KZAV

**Comment by RocketRobz** [comment]
For those games, are any settings shown in the menu with the TID?

**Comment by lorecast162** [comment]
Only in Pop Island's

**Comment by lorecast162** [comment]
btw if it can help, I have logging on

**Comment by RocketRobz** [comment]
No thanks. That's all I need.
I found the issue. In Pop Island's ROM header, it states that it's DSi-enhanced, and TWLMenu++ only checks the DSiWare if it's DSi-exclusive.
I will fix that bug for the next version.

**Comment by lorecast162** [comment]
How about the other two tho?

**Comment by RocketRobz** [comment]
Post in the Unlaunch thread about those two games.

**Comment by lorecast162** [comment]
Ok thanks, I suppose I should close this?

**Comment by RocketRobz** [comment]
Yes.

**Comment by lorecast162** [comment]
Alright, have a good day.

**Comment by lorecast162** [comment]
Hold up, can you point me to the Unlaunch thread?

**Comment by RocketRobz** [comment]
Here: https://forums.nesdev.com/viewtopic.php?f=23&t=17581
