### ISSUE TITLE
Theres no sound in pokemon black 

### ISSUE THREAD

**Issue by snes666** [DS-Homebrew/TWiLightMenu#659]
i downloaded the latest version v8.51 and it won't play any music

**Comment by RocketRobz** [comment]
Sound plays for me.
What console are you using?

**Comment by snes666** [comment]
dsi xl
and it doesnt work for any of the other ds games im using

**Comment by monkeyman4412** [comment]
I'll give it a shot. I have a ds, dsi, and n2ds models. What region of black? And who (if you didn't dump it yourself) who dumped it? Don't provide a link just the name of the dumper

**Comment by takeshineale128** [comment]
> dsi xl and it doesnt work for any of the other ds games im using
> […](#)

My dsi works perfect with Pokemon Black with the latest v8.5.1 menu and the latest ads-bootsrap and the sounds works on mine as I just tested it.

**Comment by snes666** [comment]
i beleive it was romsmania

**Comment by FlameKat53** [comment]
yeah, please refrain from sending names of piracy websites, also I believe this is the wrong repository, as it happens in game this would be an nds-bootstrap issue

**Comment by Renegtd** [comment]
I had the same problem but i fixed it replacing the title folder from the lastest 8.5.1 with the title folder from 8.3.0

**Comment by NightYoshi370** [comment]
I don't think this relates to TWiLightMenu++.
Closing
