### ISSUE TITLE
Guru Meditation Error on all my homebrew

### ISSUE THREAD

**Issue by HandMaskTar** [DS-Homebrew/TWiLightMenu#660]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [/]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [/]  Unlaunch 1.8+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [/]  Release 8.51_[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [/]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen
homebrew should launch from TWiLight Menu
### Actual behaviour

Tell us what happens instead
Guru Meditation error. I was able to launch ASDS once after updating.
### Steps to reproduce

1. be unlucky
2. launch any sort of homebrew

**Comment by RocketRobz** [comment]
Put `ASDS` folder into the same folder as the .nds file.

**Comment by RocketRobz** [comment]
I have an idea on how to fix this. I will add an option to disable modifying the most played list.
