### ISSUE TITLE
[Feature Request] Blue light filter

### ISSUE THREAD

**Issue by 5kyl4rk** [DS-Homebrew/TWiLightMenu#661]
I really liked the blue light filter that Luma3DS added in v10.0 and thought that it would be cool if TWiLight Menu could add one also considering that there's already a black & white filter.  Just curious if it's even possible, thanks.

**Comment by RocketRobz** [comment]
I tried implementing it before, but it wasn't working right.
The sprite layer looked fine, but the BG layers had weird colors.
