### ISSUE TITLE
Auto AP patch on boot (If there is patches on the sd card)

### ISSUE THREAD

**Issue by MasterGamingYT** [DS-Homebrew/TWiLightMenu#662]
I would like a feature to have a patches folder in _nds so that the next time TWiLight Menu++ boots, it will detect the patches and will promt the player if he/she wants to apply the patches, if the player clicks yes, then it will apply the patches to their respective games, after that, the patches will be deleted from the SD Card and TWiLight Menu++ will boot. If clicked no, then it will boot normally!

**Comment by GlaZedBelmont** [comment]
why not patch the game before?

there's many many patches available and also...

how would twlmenu reverts the game to the normal state?

**Comment by MasterGamingYT** [comment]
It wouldn't revert the game to the original state, the player would have an option of yes or no (It's permanent for that game, unless you delete the rom)

**Comment by GlaZedBelmont** [comment]
then in that case, it's easier to use DS-scene, youd still need to get the patch files. would make extra work, considering the database is 800+ games...

**Comment by DMSalesman** [comment]
@GlaZedBelmont On-the-fly patching could be an interesting idea, but I doubt it's doable.

**Comment by dubbz82** [comment]
This is something that has been brought up before and I think may even still be in the to do list.  It COULD actually be temporary (at least in theory) for the games that are loaded into ram if they were copied first, patched, then loaded up by bootstrap.  Main benefit there of being able to keep clean untouched roms

**Comment by GlaZedBelmont** [comment]
hmmmmmm, thats just call redump your carts and youll get your untouched roms

**Comment by NightYoshi370** [comment]
Somewhat implemented in latest nds-bootstrap/twilightmenu++ release but not permanent (keeps the ROM clean). Closed
