### ISSUE TITLE
Nintendo DS lite with a DSTT card

### ISSUE THREAD

**Issue by kib78** [DS-Homebrew/TWiLightMenu#663]
### Your console

Tell us which console do you have:

- [X]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using: v8.5.1

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

Hi, I have a Nintendo DS lite with a DSTT card… 
I tried the TTMenu.dat in TWiLightMenu\Flashcard users\Autoboot\DSTT
But when I try to run roms with bootstrap off I just get the following message:
Start failed. Error 0 
Flashcard may be unsupported.
Flashcard name:
TTCARD IO Library
----------------------------------------------------------
But when I test the same rom with the following Kernel it works perfectly:
Non-official Kernel Download
DSTTi DSTT YSMenu V7.06       (Dec-24-2018)
http://old.r4wood.com/pages/TTi-DSTT-Kernel.html
----------------------------------------------------------
And when I try to run snes roms it only go to white screen
----------------------------------------------------------
I can not get nds-bootstrap v0.21.2 to work… I only get the following error:
This edition of nds-bootstrap can only be used on the SD card (optinally, alongside a flashcard).

**Comment by RocketRobz** [comment]
To run the SNES ROMs, try running the emulator itself. (Copy `SNEmulDS.nds` from `sd:/_nds/TWiLightMenu/emulators`)
Also, you can't use TWLMenu++ to run retail games from your flashcard.
