### ISSUE TITLE
Box Art- Guru Meditation Error

### ISSUE THREAD

**Issue by koyabears** [DS-Homebrew/TWiLightMenu#664]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen

Hi, I have this error the moment I've transferred box arts downloaded from GameTDB. Can you please help me?
![66417352_2258146237848835_7536909130435395584_n](https://user-images.githubusercontent.com/52752437/60981333-b4fe4600-a368-11e9-88d5-6b481a839167.jpg)

**Comment by ZAP223** [comment]
I had the same problem.
You need covers that are 128x115 png.
From gameTBD download the S Covers pack.

**Comment by NightYoshi370** [comment]
Can you upload the boxart here?

**Comment by ZAP223** [comment]
> Can you upload the boxart here?

https://www.gametdb.com/DS/Downloads#cover_packs
