### ISSUE TITLE
Does not load games and Does not load multiplayer

### ISSUE THREAD

**Issue by TheHeroLol23** [DS-Homebrew/TWiLightMenu#665]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [X]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[v0.21.2]_
- [ ]  Nightly _[aa79599]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu (Dark)
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

It should run the .nds file and it should load the multiplayer screen for games

### Actual behaviour

Lately the games don't load and when I want to play multiplayer the game crashes.

### Steps to reproduce: 1st problem

1. Launch TwilightMenu++ from Sudokuhax
2. Launch a game.

### Steps to reproduce: 2nd problem

1. Launch TwilightMenu++ from SudokuHax
2. Launch a game
3. Enter in a multiplayer menu

**Comment by RocketRobz** [comment]
You should install and use Unlaunch to boot TWLMenu++, for multiplayer to work.
