### ISSUE TITLE
Hold Button On gamestart to make new cache

### ISSUE THREAD

**Issue by RinMaru** [DS-Homebrew/TWiLightMenu#666]
sometimes games after making a cache and updating TWiLightMenu will boot to white screen unless you delete the cache files for that game so why not have a button the has twlmenu make a new one if this issue occurs so we dont have to go to FBI and manually delete them

**Comment by RocketRobz** [comment]
Sorry. I don't have that issue.

**Comment by RinMaru** [comment]
ive had it a few time like GTA CTW will white screen after so many updates to TwiLightmeu and ndsbootstrap and the only way to boot it again was deleting its cache entries

**Comment by RocketRobz** [comment]
nds-bootstrap is supposed to update them, if they're out of date though.
Make sure you're not using the nds-bootstrap nightly from the latest TWLMenu++.

**Comment by RinMaru** [comment]
im always using the nightly. is it only every other stable that updates them?

**Comment by RocketRobz** [comment]
The nightly should update them as well.
It's just the included nightly doesn't work correctly.

**Comment by kevincrans** [comment]
Thank you, this answers my question as well, I'm gonna try it at home!
