### ISSUE TITLE
Unable to load twilight menu using Emunand. "An error has occured. Press and hold power button" etc.

### ISSUE THREAD

**Issue by kyosuke888** [DS-Homebrew/TWiLightMenu#667]
Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x]  New 3DS/2DS (XL)

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release v8.5.1
- [ ]  Nightly _[insert here commit hash]_

### Steps to reproduce

1. Followed the instructions carefully
Installing (3DS, Manual method) using FBI
   Downloaded the latest version here: https://github.com/DS-Homebrew/TWiLightMenu/releases
Extracted the "_nds" folder from both the 7z root and the "DSi&3DS - SD card users" folder, to the SD Card root. Merged folders.
    Extract the "boot.nds" file from the "DSi&3DS - SD card users" folder, to the SD Card root.
    Extract the "cia" folder from the "3DS - CFW users" folder, to the SD Card root.
    Put .gb/.gbc/.gen/.gg/.nes/.nds/.sms/.smc/.sfc ROMs anywhere on your SD card.
    Install all 2 CIAs in the "cia" folder in "3DS - CFW users".
    NOTE: If you're using EmuNAND, then install them to SysNAND as well.
    Launch TWiLight Menu++!

2. Launched the twilight menu
3. Black screen "An error has occured. Press and hold power button" etc. prompts.

Question:
"If you're using EmuNAND, then install them to SysNAND as well." How to do this? How can I install them to SysNAND? I am using EmuNAND.

-TIA

**Comment by RocketRobz** [comment]
You should move your EmuNAND to SysNAND.
https://3ds.hacks.guide/move-emunand

**Comment by kyosuke888** [comment]
is it safe? or there are is a chance i might brick the system? i used emunand since it is safe

**Comment by RocketRobz** [comment]
If you don't mess up following the guide, then it's safe.
If your system ever bricks, restore a NAND backup.

**Comment by kyosuke888** [comment]
ok thank you very much! ^_^v

**Comment by kyosuke888** [comment]
another question, will I lose all the data in my sd card by doing these steps?

**Comment by RocketRobz** [comment]
Only if you don't back them up.

**Comment by kyosuke888** [comment]
do I need to move EmuNAND to SysNAND before or after installing twilight menu ++?

**Comment by RocketRobz** [comment]
You move it after installing, which is what you did.

**Comment by kyosuke888** [comment]
Success!! I am now able to play DS games. Thank you very much! More power to you and your team!! v^_^v

**Comment by RocketRobz** [comment]
You're welcome!

**Comment by ntchris** [comment]
Make TwilightMenu works with EmuNand

Hi, I encountered this problem too.  I have two 3DS, one can run twilight menu ++  and the other has instant black screen Error.
After compared both 3DS I found the one with error is running on EmuNand.
There is an easy work around for those don't want to move to sys nand.
Please try below steps 

0. Install TwilightMenu++ in Emu Nand, run it, it instantly has a Black Screen Error message. Turn 3DS OFF.
1. Hold L key to Power ON the 3DS, so to boot using Sys Nand, enter system setting to confirm it is SYSNand: SYS version###....
2. In Sys Nand, install TwilightMenu++,  then run it, it should run without problem, try to exe a rom to further confirm.
3. Power off 3DS , and power on as usual using EmuNand,  run TwilightMenu, it can magically runs now.
This works for but YMMV

Anyway, Thanks for making Twilight Menu++!!
