### ISSUE TITLE
Game icon moved up when exiting sleep mode

### ISSUE THREAD

**Issue by androidian5980** [DS-Homebrew/TWiLightMenu#668]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[Ver. 8.5.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Normal operation in application

### Actual behaviour

When leaving sleep mode, game moves up out of slot on screen without input from user.

### Steps to reproduce

1. Launch TWiLightmenu++
2. Put system to sleep
3. Exit sleep mode

**Comment by RocketRobz** [comment]
I don't understand your issue...
What exactly happens?

**Comment by androidian5980** [comment]
> I don't understand your issue...
> What exactly happens?

It's hard to explain.. When you are using a stock DSi menu, you can press up on the d-pad and move icons. This happens when I close my system and open it up when I am in the menu

**Comment by RocketRobz** [comment]
Oh, that issue.
When you said "slot", I thought you we're referring to Slot-1 of the console.
I have no idea how to fix this bug. :(

**Comment by androidian5980** [comment]
> Oh, that issue.
> When you said "slot", I thought you we're referring to Slot-1 of the console.
> I have no idea how to fix this bug. :(

Sorry if there were many issues, probably best to close it then.
