### ISSUE TITLE
Add support for wii connection

### ISSUE THREAD

**Issue by Mattlau04** [DS-Homebrew/TWiLightMenu#669]
**Is your feature request related to a problem? Please describe.**
I was playing pokemon battle revolution and wanted to transfer pokemons from my pokemon diamond save to the game, but when i triyed to connect the games, pkmn diamond froze on a white screen

**Describe the solution you'd like**
Support interaction with the wii
I know it work on a 3ds with a real cardrige so it must probably be possible to make it work (i hope)

**Describe alternatives you've considered**
Hacking in the pokemons using PKHeX but you need to trade at least once to access storages so i can't select my pokémons

**Comment by dubbz82** [comment]
This should be closed and re-opened under the bootstrap github, as this isn't a problem specifically with the menu itself.  Additionally I know the developers are aware that this isn't yet working, however I'm not sure where this lays in terms of priority, as there are still some features missing that are preventing some games from booting which are probably higher priority than this.  It's still a good idea to have an opened issue for it (if there isn't one already on that github...) however it may be a while before it's addressed.

**Comment by RocketRobz** [comment]
There's already an issue open in the nds-bootstrap repo.

**Comment by Mattlau04** [comment]
oh ok, sorry >-<
