### ISSUE TITLE
Add support for selecting per-game Twlbg.cxi 

### ISSUE THREAD

**Issue by jetlego** [DS-Homebrew/TWiLightMenu#671]
Since sono on gbatemp released his Twlbg patcher, would it be possible to add the option to select a Twlbg filter from cxi's in /_nds/TWiLightMenu/TwlBg/ for each game? 

I have noticed that, in my opinion, some text-heavy games look better with the crisp filter, while 3d games benefit more from linear interpolation. However, with the way the current patcher works, you cannot switch between different filters without generating Twlbg.cxi from scratch again, or by manually renaming a pre-generated version to Twlbg.cxi using a file manager.  

I did notice that preliminary support for "Widescreen.cxi" was added in main.cpp, but I wanted to confirm whether or not arbitrary filter switching would be added.

EDIT: This may end up being more suited for nds-bootstrap, but could this also be made to work with cia forwarders?

**Comment by RocketRobz** [comment]
Closing, since rtcom is now a thing.
