### ISSUE TITLE
Saving hangs game (Mugen no Frontier EXCEED)

### ISSUE THREAD

**Issue by weirdingway** [DS-Homebrew/TWiLightMenu#672]
Using 8.5.1 TWLM++ and nds-bootstrap v0.21.2.

In Mugen no Frontier EXCEED whenever I hit save at a save point the game responds with the audio cue for selecting the option but then hangs. The default save file exists at sdroot\romfolder\saves (512KB) but clearly isn't being written to or loading (restarting the game there is no continue option, only new game) so it must not see the save file.

It is a .sav and it has the same name as the ROM.

**Comment by RocketRobz** [comment]
Please re-open this issue in the nds-bootstrap repo.
