### ISSUE TITLE
Guru Meditation Error!: Hack Roms

### ISSUE THREAD

**Issue by Proyecto-N** [DS-Homebrew/TWiLightMenu#673]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
-  Old 3DS
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS:

-  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

-   Release _[8.5.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
-  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Playing the game normally.

### Actual behaviour

They are two HACK ROM's of Mario Kart (Ex: Mario Kart Zero), when opening the game, this error appears in the upper screen, "Guru Meditation Error!" if they explain me if it is program error, theme, bug, game, etc, since in DSi Menu ++ this did not happen to me...

**Comment by RocketRobz** [comment]
In the next version, there will be an option to disable updating the recently played list, which is the cause of the error.

**Comment by Proyecto-N** [comment]
Thank you very much RocketRobz!

PD: I adore your work and it is difficult to contact you xD thank you very much for everything!
