### ISSUE TITLE
Touchscreen not working after update

### ISSUE THREAD

**Issue by AdeptusCustodes** [DS-Homebrew/TWiLightMenu#674]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

.

### Actual behaviour

After update touchscreen doesnt work in nds games, but working in twl menu.

### Steps to reproduce

1.Launch a game
2.Try use touchscreen

**Comment by RocketRobz** [comment]
nds-bootstrap has to be updated as well.
If you're using TWLMenu++ Updater, use that to update it.
If not, download the latest nds-bootstrap release [here](https://github.com/ahezard/nds-bootstrap/releases).
