### ISSUE TITLE
were not using download play but the multiplayer still wont work

### ISSUE THREAD

**Issue by inkknightzx** [DS-Homebrew/TWiLightMenu#676]
i dont under stand what single card play means but me and my brother have the same games and are trying to play wireless but still wont work. how do we get the game to do wireless play?

**Comment by RocketRobz** [comment]
What game is it?

**Comment by RocketRobz** [comment]
Also, you could've commented on the closed issue. :P

**Comment by inkknightzx** [comment]
well we are trying to play a bunch of games mulitplayer but right now we used to play multiplayer on crystal chronicles echoes of time. now when we try to do wireless play that its not finding anything and the wireless bars are not showing up. also i didn't know i could answer in a close issue. my bad.

**Comment by RocketRobz** [comment]
Are you running the game in DS mode or DSi mode (Forced)?

**Comment by inkknightzx** [comment]
i dont know really

**Comment by inkknightzx** [comment]
when i get on twilight menu it says nintendo dsi does that means something?

**Comment by RocketRobz** [comment]
No.
DS mode is set by default.

Can you see if multiplayer works in other games?

**Comment by inkknightzx** [comment]
ive tried and nothing. the connection bar isn't rising does that means something?

**Comment by RocketRobz** [comment]
Usually, it means the other console isn't found.

**Comment by inkknightzx** [comment]
really? so since it showing that there isn't no bars it means im not finding my brothers consol?

**Comment by RocketRobz** [comment]
Right.
Your doing this, right?
1. One console hosts.
2. Other console joins.

**Comment by inkknightzx** [comment]
its suddenly started working!!! im sorry for bothering you it just now started working after my brother updated.

**Comment by RocketRobz** [comment]
No problem.
If you need more assistance, please join these Discord servers.
TWL Mode Hacking Discord: https://discord.gg/yqSut8c
NDS(i)Brew Scene Discord: https://discord.gg/XRXjzY5

**Comment by inkknightzx** [comment]
thanks for the help dude.
