### ISSUE TITLE
Guru Meditation Error - Games randomly stop working

### ISSUE THREAD

**Issue by Intensitygate** [DS-Homebrew/TWiLightMenu#680]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ x ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ x ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen

Game should just launch without showing errors.
 
### Actual behaviour

Tell us what happens instead

Game stays on the "Now Saving..." screen before launching, and originally showed a Guru Meditation error with an "undefined" issues, but now the screen doesn't show up at all and is a black screen.

### Steps to reproduce

1. Install game (unsure if its exactly PKMN Mystery Dungeon: Exp of Skys)
2. Attempt to launch game after deleting an old game you didnt want
3. Get confused because nothing should of affected it

**Comment by RocketRobz** [comment]
There's a bug with the code that updates the recently played list.
That can be disabled in the next version.

**Comment by Intensitygate** [comment]
There's a new error, however, after changing how it launches, I got a new GM error.
![OXHzBQ0](https://user-images.githubusercontent.com/53235331/61742059-e1966280-ad57-11e9-8e6a-d20039536f74.jpg)
