### ISSUE TITLE
Update to past error, new GM error

### ISSUE THREAD

**Issue by Intensitygate** [DS-Homebrew/TWiLightMenu#681]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Expected black error screen

### Actual behaviour

Guru Meditation error

### Steps to reproduce

1. Change lauching format (Default to DSi)
2. Error occurs

Picture of screen below.

![61742059-e1966280-ad57-11e9-8e6a-d20039536f74](https://user-images.githubusercontent.com/53235331/61849385-16510980-ae7f-11e9-884e-053363cbf74b.jpg)

**Comment by Intensitygate** [comment]
https://user-images.githubusercontent.com/53235331/61742059-e1966280-ad57-11e9-8e6a-d20039536f74.jpg

**Comment by Intensitygate** [comment]
help? :(

**Comment by NightYoshi370** [comment]
Can you upload your settings.ini file?

**Comment by Intensitygate** [comment]
Yes, I assume you are talking about the one in the _nds > TWiLightMenu directory. Here it is:

[settings.txt](https://github.com/DS-Homebrew/TWiLightMenu/files/3440921/settings.txt)

**Comment by Intensitygate** [comment]
Did that help any?

**Comment by NightYoshi370** [comment]
Have you tried doing a fresh install?

**Comment by Intensitygate** [comment]
I'm not very sure how to uninstall to actually get to that part, because there's nothing out there that's clear about what you have to do.

**Comment by NightYoshi370** [comment]
Delete the _nds folder, download the latest nightly and follow the install procedure
