### ISSUE TITLE
AKMenu Guru Meditation when touching a a game

### ISSUE THREAD

**Issue by daemonspudguy** [DS-Homebrew/TWiLightMenu#683]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [x]  Other CFW [specify]
- [ ]  Older CFW
Luma3DS with PabloMK7's plugin loader
### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.5.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [x]  Acekard/akMenu

### Expected behaviour

Tell us what should happen
Touching the screen should launch a game or open the folder
### Actual behaviour

Tell us what happens instead
Touching the screen creates a guru meditation error
### Steps to reproduce

1.Use akmenu theme
2.Choose a sub-theme
3. touch a game on the game list

**Comment by RocketRobz** [comment]
The Acekard theme isn't stable.
Please use a different theme.
