### ISSUE TITLE
Namco Museum DS bugs out

### ISSUE THREAD

**Issue by AshuraChan** [DS-Homebrew/TWiLightMenu#684]
Namco Museum DS glitches out in TWiLightMenu++, as in the icon is a bunch of random pixels, the name doesn't appear, and it does not boot NMDS

**Comment by RocketRobz** [comment]
Sounds like your ROM got corrupted somehow.
Try replacing your ROM.

**Comment by NightYoshi370** [comment]
It works just fine on my end. I don't think it's a TWiLight issue

**Comment by AshuraChan** [comment]
Well it's been fixed (as in I installed a rom and patched my legal dump) about a week since this was posted

**Comment by NightYoshi370** [comment]
Glad to hear.
If you have any other issues, please open up a brand new issue.

For now though, I'll be closing this
