### ISSUE TITLE
Option to turn off dropping/bouncing animation on DSi theme

### ISSUE THREAD

**Issue by gingerbeardman** [DS-Homebrew/TWiLightMenu#686]
**Is your feature request related to a problem? Please describe.**
Currently with the _Default DSi Theme_ when you go into a folder a bunch of icons drop from the top of the screen and bounce into place. This process takes a second or so, during which time you cannot interact with the menu. This is annoying.

**Describe the solution you'd like**
An option to turn off the folder drop animation would be appreciated.

**Describe alternatives you've considered**
Other themes (3DS, R4, AceKard)) do not suffer from this animation delay.
(But I do not want to use those other themes)

**Comment by RocketRobz** [comment]
Why is it annoying, if it only takes a second?

**Comment by gingerbeardman** [comment]
Two reasons: 

1. Because during that time I cannot interact with the menu.
2. And it happens every time I go into a folder

Here's a sample user journey:

- open TW menu
- (wait 1 second)
- go into rom folder
- (wait 1 second)
- go into nds folder
- (wait 1 second)
- realise what I am looking for is in dsiware folder
- go up a folder
- (wait 1 second)
- go into dsiware folder
- (wait 1 second)
- launch game

Hopefully you can see that all those 1 second waits soon add up and become annoying.

If I could interact with the menu, or press a button to cancel the animations then that would be good enough. 

Compare that to the same journey with another theme.

- open TW menu
- go into rom folder
- go into nds folder
- realise what I am looking for is in dsiware folder
- go up a folder
- go into dsiware folder
- launch game

Much speedier because there are no forced 1-second waits.

**Comment by Midou36O** [comment]
I'm suggesting to keep the bouncing animation, but only after TWLMenu++ boots, this means when we go to a folder the bouncing animation won't be triggered, only when we launch TWLMenu++

**Comment by gingerbeardman** [comment]
That's a good compromise @Midou36O

**Comment by RocketRobz** [comment]
The drop-in animation now only occurs on theme start, in v10.2.0.
