### ISSUE TITLE
Certain R4 subthemes are broken

### ISSUE THREAD

**Issue by daemonspudguy** [DS-Homebrew/TWiLightMenu#688]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.5.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [x]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

DSI and 3ds subthemes work 
### Actual behaviour
The DSI ones are black, and the 3ds one flickes red

### Steps to reproduce

1. Choose R4 theme
2. Choose the specified subthemes
3. Go to the menu

**Comment by RocketRobz** [comment]
I never had an issue with the included R4 subthemes.
