### ISSUE TITLE
HeartGold shows black screen after ap patch 

### ISSUE THREAD

**Issue by xRoyalPainx** [DS-Homebrew/TWiLightMenu#690]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release _[v0.21.2]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

The game load perfectly with a sav file I found of a perfect HeartGold copy                             
### Actual behaviour

The games loads with a black screen but audio plays 

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
The issue happens in a game itself, so it's an nds-bootstrap issue.
Your .sav file might be corrupted. Can you see if it works in an emulator for PC?

**Comment by xRoyalPainx** [comment]
I put the ap patch rom into desmume and it still showed the black screen until I loaded the sav file

**Comment by RocketRobz** [comment]
Where did you get the .sav file?

**Comment by xRoyalPainx** [comment]
From here 
https://filetrip.net/nds-downloads/game-saves/download-pokemon-hgss-perfect-save-1-31-f10256.html

**Comment by RocketRobz** [comment]
Hmm, with both the clean and AP-patched ROM, save works fine for me in DeSmuME.

**Comment by RocketRobz** [comment]
Now I tested it with the AP-patched ROM in nds-bootstrap.
Black screens. :(

Closing, because this is an nds-bootstrap issue.
