### ISSUE TITLE
Option to disable intro

### ISSUE THREAD

**Issue by ergoithz** [DS-Homebrew/TWiLightMenu#691]
**Is your feature request related to a problem? Please describe.**
With the addition of the intro and the return of the DSi splash screen, we all now have to get pass two intros to get were we came to. It's too much a waste of time (and the TWiLightMenu one is not especially beautiful or polished, but at least it's skipable).

**Describe the solution you'd like**
An option to completely disable it.

**Describe alternatives you've considered**
Downgrade, but I like the higher compatibility of recent versions of nds-bootstrap.

**Comment by Midou36O** [comment]
This feature is already out, just go to TWLMenu++ Settings and press L to move to "Misc. Settings" there should be 3 settings at the end to turn on or off the splash screen, the health and safety message, and the TWLMenu++ splash screen, disable them all and you're good to go!

**Comment by ergoithz** [comment]
@Midou36O thank you so much!
