### ISSUE TITLE
TwilightMenu Restarts After Trying to Load A Game

### ISSUE THREAD

**Issue by TooMuchStrafes** [DS-Homebrew/TWiLightMenu#693]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Can you try the latest nightly build?

**Comment by TooMuchStrafes** [comment]
how do you do that? I just installed Twilight Menu Yesterday

**Comment by RocketRobz** [comment]
Use the TWiLight Menu++ Updater.

**Comment by TooMuchStrafes** [comment]
okay give me a minute

**Comment by TooMuchStrafes** [comment]
which updater should i install .cia or .3dsx

**Comment by RocketRobz** [comment]
CIA

**Comment by TooMuchStrafes** [comment]
after ive installed what should i do?

**Comment by RocketRobz** [comment]
Launch the Updater, and touch `Nightly` for `TWLMenu++`.

**Comment by TooMuchStrafes** [comment]
i dont have apps to launch the updater

**Comment by NightYoshi370** [comment]
Are you checking the homebrew launcher? Or the system's home menu?

**Comment by TooMuchStrafes** [comment]
wait are you suppost to move the updater somewhere because right now its on my desktop

**Comment by TooMuchStrafes** [comment]
Also when I try to boot up the homebrew launcher on my 3ds is says "An exception occurred"

**Comment by RocketRobz** [comment]
You put the updater CIA on your 3DS SD card, then use FBI to install it.

**Comment by TooMuchStrafes** [comment]
ohhhhhh so on the root of the sd card?

**Comment by TooMuchStrafes** [comment]
I installed it to my 3ds now what?

**Comment by RocketRobz** [comment]
Exit FBI, and launch the updater. If it doesn't appear, reboot the 3DS.

**Comment by TooMuchStrafes** [comment]
okay I tapped nightly for twlmenu++, now it says "choose a commit for commit notes" what should i do?

**Comment by RocketRobz** [comment]
Pick the latest.

**Comment by TooMuchStrafes** [comment]
its updating

**Comment by TooMuchStrafes** [comment]
What after?

**Comment by NightYoshi370** [comment]
Now check if the issue is fixed

**Comment by TooMuchStrafes** [comment]
okay ill check

**Comment by RocketRobz** [comment]
@TooMuchStrafes Is it fixed?

**Comment by TooMuchStrafes** [comment]
sorry, no it did not fix it

**Comment by TooMuchStrafes** [comment]
also want to say that sometimes the games loaded like heargold and platinum but now they dont

**Comment by TooMuchStrafes** [comment]
is it because i ap patched heartgold

**Comment by RocketRobz** [comment]
AP patched ROMs work fine though.

**Comment by RocketRobz** [comment]
Try turning off `Update recently played list` in TWLMenu++ Settings.

**Comment by TooMuchStrafes** [comment]
done should i check if it fixed

**Comment by RocketRobz** [comment]
Yes. If it's still not fixed, idk what to do. :(

**Comment by TooMuchStrafes** [comment]
what a legend...

**Comment by TooMuchStrafes** [comment]
it fixed it, i give you 5 stars

**Comment by TooMuchStrafes** [comment]
you were pacient with me and exellent responce time :]

**Comment by TooMuchStrafes** [comment]
you were pacient with me and exellent responce time :]

**Comment by NightYoshi370** [comment]
Enjoy TWiLightMenu++!

**Comment by RocketRobz** [comment]
lol, thanks!
Nice to know that fixed it. Hopefully it'll help others with this issue.

**Comment by TooMuchStrafes** [comment]
have been playing heartgold and platimum for about 2 hours and it works great
