### ISSUE TITLE
The latest release won't boot.

### ISSUE THREAD

**Issue by niwtr** [DS-Homebrew/TWiLightMenu#695]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[8.5.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [x]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

The software should boot normally.

### Actual behaviour

The software boots to black screen of Japanese texts, telling me that some errors have occurred and I have to cut off the power and reboot the 3DS.

### Steps to reproduce

Just followed the official routines of installation. I tried install manually AND via the updater and both failed.

BTW my sys version is 11.8 and my CFW is B9S.

**Comment by RocketRobz** [comment]
Install the CIAs to SysNAND as well.

**Comment by niwtr** [comment]
Update: this is the screenshot: 
[screenshot](https://ibb.co/gyHJ0ss)

**Comment by niwtr** [comment]
> Please install the CIAs to SysNAND as well.

Please let me know how can I do that?

**Comment by RocketRobz** [comment]
Actually, please don't.
Follow this guide instead: https://3ds.hacks.guide/move-emunand

**Comment by niwtr** [comment]
> Actually, please don't.
> Follow this guide instead: https://3ds.hacks.guide/move-emunand

Ok forgive me some time to try it out. Thanks first!

**Comment by niwtr** [comment]
> Actually, please don't.
> Follow this guide instead: https://3ds.hacks.guide/move-emunand

May I ask you a question? Do I need to finish all the steps of this guid totally, including the final "Section VIII - Format SD card" step? This is a pretty hard work to do.

**Comment by RocketRobz** [comment]
Yes.

**Comment by niwtr** [comment]
Well I managed to have TWLight Menu++ running, without going through the "Format SD card" step. Do you think it's a big problem doing so?
