### ISSUE TITLE
A custom theme maker

### ISSUE THREAD

**Issue by CaptainLui** [DS-Homebrew/TWiLightMenu#698]
I think that's ( for me ) , custom themes , and an editor for make custom themes would be cool ...

**Comment by chyyran** [comment]
Custom themes can be made with conventional image editing programs. Instructions here: https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_dsimenutheme/resources/dsimenu_theme_examples/theming.md

**Comment by NightYoshi370** [comment]
Not necesarily something that TWiLightMenu++ handles. I'm not sure though, so I'll keep this open

**Comment by FlameKat53** [comment]
i think we could close this issue and use #783 instead

**Comment by chyyran** [comment]
#783 seems to be better specified as an issue

**Comment by NightYoshi370** [comment]
Half of this is invalid as there are custom themes
The other half is better defined by #783

Closing...
