### ISSUE TITLE
Games crash when running them through direct access on Slot-1 (Acekard 2i)

### ISSUE THREAD

**Issue by rootyElf** [DS-Homebrew/TWiLightMenu#699]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _[1.8]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[9.0.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [X]  R4
- [X]  Acekard/akMenu

### Expected behaviour

When entering the Slot-1 SD (Acekard) through direct access (TWiLightMenu was run from internal SD) and running a game on there, it plays. (that's what should happen right - unfortunately, I didn't find specific documentation on this feature, though)

### Actual behaviour
Browsing the Slot-1 card (Acekard 2i showing up as Horzes) works fine. However, Games (retail and homebrew) crash when launched from Slot-1. Tried different themes and running the games from the quick menu as well. I also tried different games like Pokémon Platinum, Mario Kart and New Super Mario Bros, but from what I can tell, it does not make a difference which games I try. The situation is the same on on both my O3DS running Luma3DS and my DSi running Unlaunch (no HiyaCFW). Most of the time I get a white screen. I tried different settings (clock frequencies, DS/DSi modes, SCFG access, enabling/disabling nds-bootstrap) and I tried putting the AK2i forwarder stuff on the Slot-1 SD as well. Yet, I have never been able to successfully boot a game through Slot-1 direct access. 

### Steps to reproduce

1. Run TWiLight Menu++ on 3DS or DSi while having an Acekard 2i mimicking Horzes insert into Slot-1
2. Go to settings and enable Slot-1 SD access
3. Browse the Slot-1 SD cards and try to run an nds file.

**Comment by RocketRobz** [comment]
Are you on the latest nds-bootstrap version (v0.22.0)?
Pokemon Platinum and Mario Kart DS work fine for me (using an R4 Ultra).

**Comment by rootyElf** [comment]
Yes, I'm on that version. It also works fine when booting games from internal SD. There is also nothing wrong with my AK as far as I can tell, it boots games just fine when booted normally with AKAIO. It's HW-81, if that's relevant. Does the AK2i-SD maybe have to be formatted with a specific cluster size?

**Comment by RocketRobz** [comment]
No.
Is the flashcard set to use nds-bootstrap?

**Comment by rootyElf** [comment]
I tried it with and without nds-bootstrap. No luck in either case.

**Comment by rootyElf** [comment]
Here's my [ak2i_flash.bin](https://www.dropbox.com/s/5eb1xgbu2iz90v6/ak2i_flash.bin?dl=1) dumped using Decrypt9. Maybe someone can test it and/or post one that's known working.

Also here is my [setting.ini](https://pastebin.com/Zfbp76B0).

**Comment by RocketRobz** [comment]
Try SDK5 games, and see if they work.

**Comment by rootyElf** [comment]
So I tried KH-Re:Coded, Super Scribblenauts and Pokémon Black (1 and 2) - all EU/DE. Same result unfortunately.

**Comment by RocketRobz** [comment]
Try switching the flashcard save path to the SD card.
Before doing that, make sure the folder path on the flashcard (ex. `roms/nds`) is also on the SD card.

**Comment by rootyElf** [comment]
Still crashes. Save files seem to be created fine on either SD card.

**Comment by RocketRobz** [comment]
Did the `nds-bootstrap` logo screen ever show, when launching a game?

**Comment by rootyElf** [comment]
No

**Comment by RocketRobz** [comment]
Closing, since this is an nds-bootstrap issue.
