### ISSUE TITLE
System Settings Boot Issue - TWLMenu Misc Settings

### ISSUE THREAD

**Issue by dazzaXx** [DS-Homebrew/TWiLightMenu#700]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW [V1.9 + V1.3.2]

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release v9.0.1
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Go to System Settings, save options changed and displays on the Main Menu.

### Actual behaviour

Upon booting System Settings via Misc Settings in TWLMenu Settings, system settings either boots the incorrect version where no matter what option is changed, for instance the user name, it doesn't show up on the Main Menu as if it were never changed. It boots the correct System Settings, boots to "An Error Occurred" Screen or just returns back to the TWiLight Main Menu Screen.

### Steps to reproduce

1. Go to the TWLMenu Settings Misc. Page
2. Scroll down to System Settings and Boot.
3. Result varies between the 4.

**Comment by NightYoshi370** [comment]
This cannot be reproduced by Kaissan
