### ISSUE TITLE
 error activating external firms and modules

### ISSUE THREAD

**Issue by manuel9106** [DS-Homebrew/TWiLightMenu#701]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour
open normally

Tell us what should happen

### Actual behaviour

error when activating external companies and modules, when trying to open any application freezes me, the top is not visible, such as time, etc. any solution? 
or am I missing something?
 Thank you

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Is there anything already in `sd:/luma/sysmodules`?

**Comment by manuel9106** [comment]
> Is there anything already in `sd:/luma/sysmodules`?


I have nothing, do I need to download anything else? Thank you

**Comment by RocketRobz** [comment]
Try reinstalling TWLMenu++.

**Comment by manuel9106** [comment]
> Try reinstalling TWLMenu++.


the problem is that when trying to open the twlmenu it freezes, but if not active that option of luma works for me normally.
I should have something in sd:/luma/sysmodules?

**Comment by RocketRobz** [comment]
No.
Activating that option of Luma does not affect the functionality of TWLMenu++.
Please check your SD card for errors.

**Comment by manuel9106** [comment]
very well thanks, I just say that it is not just the twmenu but all the applications that freeze, so I ask if I am missing something on that route that you mentioned before
