### ISSUE TITLE
3ds theme touch input

### ISSUE THREAD

**Issue by Valkristh** [DS-Homebrew/TWiLightMenu#702]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW _[Latest versions]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[Latest]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [X]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen
Access a game or to settings touching the icons
### Actual behaviour
The touch isn't responding and can't launch a game other than pressing start 
(i was trying to change to other theme with select but i can't access to settings neither )
Tell us what happens instead

### Steps to reproduce

1.open twilightmenu++ (touching the icon from hiyacfw so isn't a failure of the console)
2.touch any icon
3.nothing happenes

**Comment by RocketRobz** [comment]
In the 3DS theme, touch the wrench icon to go to settings.

**Comment by Valkristh** [comment]
*Latest hiya and unlaunch versions, can't edit

**Comment by Valkristh** [comment]
No icon is working, its described in steps to reproduce

**Comment by RocketRobz** [comment]
Touch works fine for me.

**Comment by RocketRobz** [comment]
Touching the game icon doesn't work though.

**Comment by Valkristh** [comment]
Hmm strange, any other way for change the theme? Maybe downgrade to 9.0.1?

**Comment by RocketRobz** [comment]
So touch worked in that version?

**Comment by Valkristh** [comment]
Sorry for the multipost, I've launched from unlaunch, and the touch input works...
