### ISSUE TITLE
Opening manual causes TWiLight Menu++ to reset

### ISSUE THREAD

**Issue by cnzqy1** [DS-Homebrew/TWiLightMenu#703]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _9.0.2_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Manual should open.

### Actual behaviour

White screen, and then TWiLight Menu++ resets.

### Steps to reproduce

1. Tap on the yellow arrow on the home screen.
2. Press SELECT to open the menu.
3. Choose "Open Manual".

**Comment by RocketRobz** [comment]
Fixed. Please re-update to v9.0.2.
