### ISSUE TITLE
Widescreen

### ISSUE THREAD

**Issue by ClickPond** [DS-Homebrew/TWiLightMenu#704]
- [x]  New 2DS (XL)

- [x]  Luma3DS

- [x]  Release 9.0.2

- [ ]  DSi Menu

I'm not sure if this is the right place to put this but I'm not sure how to get widescreen working, is there any tutorial on this or any specific way i can get this to function?

**Comment by zeroultima6** [comment]
The widescreen patcher is not out yet.
