### ISSUE TITLE
No audio in roms launched from R4i+

### ISSUE THREAD

**Issue by jonthysell** [DS-Homebrew/TWiLightMenu#706]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _1.8+1.3.2_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _9.0.2]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [x]  Acekard/akMenu

### Expected behaviour

Game loads as usual and audio works.

### Actual behaviour

Game loads but no audio.

### Steps to reproduce

1. Launch TwilightMenu++ from HiyaCFW.
2. Select "Slot-1 Card".
3. The R4i+ boots into its menu.
4. Select a NDS rom.

I was using TwilightMenu 8.0 to launch the Slot-1 flashcard so any ROM I picked would use the faster clock speed and it worked fine. I was using Sonic Classic Collection which shows a marked framerate improvement.

Upgrading to 9.0.2 and it no longer works.

**Comment by RocketRobz** [comment]
Either wait for the next version to be out, or set the Sound/Mic frequency to 48khz.

**Comment by NightYoshi370** [comment]
Why not use the Docker builds?
