### ISSUE TITLE
Disable deleting of games

### ISSUE THREAD

**Issue by fennectech** [DS-Homebrew/TWiLightMenu#707]
**Is your feature request related to a problem? Please describe.**
I have accidently deleted games multiple times
**Describe the solution you'd like**
An option in the settings to disable the delete game dialog 

**Additional context**
I am using the DSI menu theme.

**Comment by RocketRobz** [comment]
How do you accidentally delete a game multiple times? That never happened for me.

**Comment by fennectech** [comment]
I dont know why but i instinctively press “X” to open the menu. And have pressed A before realizing i opened the delete menu more than once.

**Comment by piratesephiroth** [comment]
perhaps you could display a big red warning image in that delete game dialog

**Comment by DMSalesman** [comment]
I often tend to press X rather than Y, but accidentally deleting a game never occurred to me.

A big red warning image seems a bit overboard, in my opinion. Maybe a randomized keycombo to unlock the deletion dialog à la GodMode9?

**Comment by arraystock** [comment]
There could even be a delay in the delete dialog, you can't confirm the deletion until after X amount of time, this could prevent that sort of thing happening in the future by making the user read the prompt when nothing happens immediately.

**Comment by piratesephiroth** [comment]
There is a delay already. The problem is that it's a very bland message, easy to ignore.

**Comment by DMSalesman** [comment]
Apart from taking up a lot of screen estate, I believe that a warning will only be looked at for so many times. How long before muscle memory kicks in?

**Comment by AlbertoDiazC** [comment]
+1 here.
If you have some kids around, you'll realize this is a must.

**Comment by NightYoshi370** [comment]
Maybe check if the NAND has parental controls setup and if it does, try to initiate the PIN ask

**Comment by tomudo** [comment]
Dirty fix. Maybe change file attribute to Read-only.

**Comment by AlbertoDiazC** [comment]
A new setting for defining the root folder could help to control damage. Some kind of sandbox.

**Comment by FlameKat53** [comment]
> Maybe check if the NAND has parental controls setup and if it does, try to initiate the PIN ask

I don't think anyone knows how to read the parental controls pin yet, i could look at it in a hex editor; 

i assume the pin is in the TWLCFG0.dat and TWLCFG1.dat files, but that wouldn't work on 3ds

**Comment by Darknior** [comment]
Yep good idea, to prevent children to delete games alone on the DS ... :(

**Comment by NightYoshi370** [comment]
The problem is that any smart child would be able to change the settings to allow it again.
Overall, I think we should RE how Parental Controls works and see if we could incorperate that pin into TWiLight Menu++

**Comment by Darknior** [comment]
> The problem is that any smart child would be able to change the settings to allow it again.
> Overall, I think we should RE how Parental Controls works and see if we could incorperate that pin into TWiLight Menu++

Yes a PIN code to enter Twilight Menu will be the best idea like we have on Wii
But for real a little children will not go change the option in the menu, and they don't speak english :p 
By accident maybe ... ;)

**Comment by RocketRobz** [comment]
Implemented in 67704081
