### ISSUE TITLE
Acekard theme doesn't load themes, if using a flashcard

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/TWiLightMenu#708]
### Your console

Tell us which console do you have:

- [X]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[v9.0.2]_
- [X]  Nightly _[541adb20]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [X]  Acekard/akMenu

### Expected behaviour

Themes load from the flashcard.

### Actual behaviour

Fallback theme `zelda` is loaded instead.

### Steps to reproduce

1. Go into TWLMenu++ Settings.
2. Set Acekard subtheme.
3. Exit TWLMenu++ settings, and touch yellow arrow, if in the quick menu.

Thanks to CÄSTLES for pointing out this bug.

**Comment by NightYoshi370** [comment]
Apparently, this is fixed. Can anyone try again?

**Comment by chyyran** [comment]
Fixed as of #757
