### ISSUE TITLE
Twilight Menu ++ wont load my sav file

### ISSUE THREAD

**Issue by The-Sexy-Waffle-Maid** [DS-Homebrew/TWiLightMenu#710]
Hey, I'm having some issues with Twilight menu. I have a sav file of Pokemon mystery dungeon explorers of sky on my PC and I'd like to upload my saved data to the Twilight menu, but i cannot for the life of me figure out how to do this. I've put the sav file into the same location as the rom, I've renamed both the file and the rom, and I've tried placing the files in different locations (though I didn't expect much to happen with that). I'm using the latest version of the application. When I check my SD card after pulling up my game (asking me to create a new game as my saved data will not load) I can see that another sav file has been created. I don't know if this is much help, but I can see that all the other sav files from my other games (including the newly created sav file from mystery dungeon) all have a size of 512 KB, while my original sav file has a size of 2,049 KB. Im not too sure what any of this means, as im still really new to all this, and that might be fairly obvious. If there is at all any confusion to understanding my problem, I will not hesitate to explain further and provide screenshots. I would really like to find a solution to this problem. I don't know if this is fixable or not, but either way, I would really appreciate your answers. Thank you!

**Comment by edo9300** [comment]
You have to put the save in the "saves" folder inside the rom's folder

**Comment by The-Sexy-Waffle-Maid** [comment]
> You have to put the save in the "saves" folder inside the rom's folder

I don't have a rom's folder. Should I just create one and see if a new saves folder will appear after inserting the SD card back into my 3ds?

**Comment by RocketRobz** [comment]
The `saves` folder should already be in the folder where your ROMs are at.

**Comment by The-Sexy-Waffle-Maid** [comment]
> The `saves` folder should already be in the folder where your ROMs are at.

It is, but the sav file is not loading correctly

**Comment by RocketRobz** [comment]
Did you put the correct .sav file in the `saves` folder?

**Comment by The-Sexy-Waffle-Maid** [comment]
> Did you put the correct .sav file in the `saves` folder?

Yes, I believe so (highlighted sav is the one that won't upload)
![image](https://user-images.githubusercontent.com/53931356/62816418-21e63680-baf5-11e9-85f7-050a7ff3a657.png)

**Comment by RocketRobz** [comment]
The .sav file is probably either corrupt, or not in a compatible format.

**Comment by The-Sexy-Waffle-Maid** [comment]
> The .sav file is probably either corrupt, or not in a compatible format.

Well, it was converted from my phone emulator as a different file. Do you have any suggestions for what I should do?

**Comment by The-Sexy-Waffle-Maid** [comment]
> The .sav file is probably either corrupt, or not in a compatible format.

Do you think maybe the size of the sav file has anything to do with the issue? Or is that unrelated?

**Comment by RocketRobz** [comment]
It's unrelated.
