### ISSUE TITLE
The "Precise volume control" setting doesn't apply to gbarunner2

### ISSUE THREAD

**Issue by zacchi4k** [DS-Homebrew/TWiLightMenu#712]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW latest releases

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release latest
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

With Precise volume control off, there are 7 different volume levels. When turning it on, that number should increase

### Actual behaviour

GBA games ran via Gbarunner2 still only have 7 volume levels

### Steps to reproduce

1. Count the volume levels when running a GBA game from gbarunner2
2. Turn on Precise volume control
3. Count the levels again

**Comment by RocketRobz** [comment]
That's an nds-bootstrap issue, not a TWLMenu++.
If you're running homebrew, then it's normal for it to not work.
