### ISSUE TITLE
Abnormailty?

### ISSUE THREAD

**Issue by james1222312334** [DS-Homebrew/TWiLightMenu#713]
I was Just booting up a Game and I saw that the Touch Screen was not Responding, and The Mic was Crazy! Not even the A Button would Register Input on SM64DS! This is going to get weird because I wish there was an Update that can fix that...

**Comment by RocketRobz** [comment]
Install the latest TWLMenu++ CIAs.

**Comment by james1222312334** [comment]
O Rly?

**Comment by james1222312334** [comment]
Now I must Find da wae...

**Comment by james1222312334** [comment]
I installed the Lastest CIAs Didn't work for me...

**Comment by RocketRobz** [comment]
Does touch work in the ROM menu?
If so, then you need a file which should fix that, but idk which one.

**Comment by james1222312334** [comment]
Only works on the Wrench which is good...

**Comment by james1222312334** [comment]
and i changed to DSi and it failed...

**Comment by RocketRobz** [comment]
Is there a `boot.nds` file on the SD root?

**Comment by james1222312334** [comment]
Yeah...

**Comment by james1222312334** [comment]
what do i need to do?

**Comment by RocketRobz** [comment]
Install the latest nds-bootstrap [here](https://github.com/ahezard/nds-bootstrap/releases/tag/v0.23.0).

**Comment by james1222312334** [comment]
and nothing's Working and I still can't tap things

**Comment by james1222312334** [comment]
and oh hey! I least I can finally tap stuff in MySims Party!

**Comment by RocketRobz** [comment]
Install [v9.1.2](https://github.com/DS-Homebrew/TWiLightMenu/releases/tag/v9.1.2) of TWLMenu++ as well.

**Comment by james1222312334** [comment]
But i've already installed that...

**Comment by RocketRobz** [comment]
> and oh hey! I least I can finally tap stuff in MySims Party!
Nice!
Makes no sense that it doesn't work in other games though.

> But i've already installed that...
I figured you're still on an older version, because it might be booting an outdated nighty nds-bootstrap, instead of the stable/release.

**Comment by james1222312334** [comment]
No Mic thing with Puyo Pop Fever! And it's working well!
