### ISSUE TITLE
TWiLightMenu doesn't go back to 4:3 after playing a game in 16:10 mode

### ISSUE THREAD

**Issue by zacchi4k** [DS-Homebrew/TWiLightMenu#715]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [X]  Luma3DS 10.0.1
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release 9.0.3
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

After playing a game in widescreen mode and returning to Twlightmenu by holding L+R+Down+B, the application should revert back to 4:3 mode

### Actual behaviour

Twlightmenu doesn't revert to 4:3 mode and instead appears stretched to 16:10 mode. This persist even after relaunching the application, even if you switch back to 4:3 in the settings. This also causes game to render in 4:3 stretched to 16:10 even after reverting to 4:3 in the settings

### Steps to reproduce

1. Enable widescreen mode
2. Play a game that support widescreen mode
3. Hold L+R+Down+B

**Comment by vulpes-vulpeos** [comment]
Did you installed cias from 9.0.3 update archive?

**Comment by zacchi4k** [comment]
I reinstalled the cias just to be sure, and it didn't solve the issue

**Comment by vulpes-vulpeos** [comment]
try to delete _nds folder and copy fresh files from 9.0.3 update archive (don't forget to backup your widescreen.cxi). For me it solved the problem.

**Comment by zacchi4k** [comment]
Why was this closed?

**Comment by RocketRobz** [comment]
There's no issues for me.

**Comment by RocketRobz** [comment]
Did you do what @vulpes-vulpeos suggetsed?

**Comment by Midou36O** [comment]
i also have this bug, but on a O3ds
