### ISSUE TITLE
Screen gets scrambled when trying to use Widescreen on original resolution

### ISSUE THREAD

**Issue by SleepyLark** [DS-Homebrew/TWiLightMenu#717]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:
3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[9.0.3]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Issue
It's not anything major and I know that the "Widescreen" is not meant to be used on the original resolution, but I thought I should notify others in case they accidentally do it.   

When attempting to use Widescreen on the original resolution (holding START or SELECT while booting TWiLight Menu), it cause the screen to get "scrambled" and only shows three cutoff sections on both screens.  The game still runs and touch input is still registered, but it's impossible to play a game like that. 

![IMGP0046](https://user-images.githubusercontent.com/37351525/62983515-d2518480-bdec-11e9-817c-d3c1560f2bec.JPG)
   

### Steps to reproduce

1. boot TWiLight Menu while holding either START or SELECT
2. turn on "Widescreen" and boot a game (I tested this on SM64 DS).
3. game tries to boot using the Widescreen patch but can't because it's not possible

### Possible solutions
1. Have some way to detect if the screen size is at the "original resolution" or the 3DS's screen ratio and prevent the patch from booting
2. Put some kind of a warning to notify users that the patch won't work unless you use the 3DS display.

**Comment by RocketRobz** [comment]
I'd say this is a patcher issue, and not a TWiLight issue, but since the patcher's repo is private, I'll let this issue stay open here.

**Comment by NightYoshi370** [comment]
Since the patcher repo is now public, I feel like this could be moved over there now
