### ISSUE TITLE
[Request] Add ability to turn on/off "Widescreen Patch" on the "per-game settings"

### ISSUE THREAD

**Issue by SleepyLark** [DS-Homebrew/TWiLightMenu#718]
It would be nice to be able to select which games you want to use with widescreen, similar to how you have the option to switch between the CPU clock speed by pressing 'Y'.

I was thinking that it would first check to see if that games ID is even compatible with the patch and have that option appear on the quick menu (if possible), or just have it be a global option.

it will work like the other options with the choice of either "Default", "On", or "Off".

**Comment by RocketRobz** [comment]
Why do you want it per-game though?

**Comment by SleepyLark** [comment]
sometimes I like seeing it in the 4:3 ratio and I'm just too lazy to open up the settings I guess¯\_(ツ)_/¯
unless someone else can think of a better reason you can just close this.
