### ISSUE TITLE
[This is an nds-bootstrap issue]

### ISSUE THREAD

**Issue by Proyecto-N** [DS-Homebrew/TWiLightMenu#719]
How do I put an image in that "question mark" in the title of a DS game in the Twilight' Menu?

**Comment by DMSalesman** [comment]
How would this be an nds-bootstrap issue?

**Comment by arraystock** [comment]
From the post on [GBATemp](https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/):

> **Box art/game cover display**
Make sure box art/game cover is set to be shown in TWiLight Menu++ settings.
Download a png box art pack from [here](https://www.gametdb.com/DS/Downloads#cover_packs).
Extract the .png files to "sd:/_nds/TWiLightMenu/boxart".
Your DS game's box art/game cover will now be shown!
**To add your own box art:**
Place them in "sd:/_nds/TWiLightMenu/boxart".
Can either have the game's TID (ex. ASME.png), or the filename (ex. SM64DS.nds.png).
Must be in .png format, with the size of 128x115.
Individual box art can also be downloaded from GameTDB.

Also for just custom images and not box art, instructions are on the [FAQ](https://github.com/DS-Homebrew/TWiLightMenu/wiki/FAQs#q-how-do-i-show-a-custom-picture-on-the-top-screen-of-the-dsi-theme).

**Comment by Proyecto-N** [comment]
Thank you so much!

**Comment by arraystock** [comment]
No problem!
