### ISSUE TITLE
Inconsistency between Widescreen compatibility list and nds-bootstrap compatibility list (game doesn't work with widescreen patch as claimed)

### ISSUE THREAD

**Issue by sks316** [DS-Homebrew/TWiLightMenu#722]
The TWLMenu++ widescreen compatibility list shows Mario Kart DS (USA) as working, but the nds-bootstrap compatibility list says the game needs to be repacked with dslazy to avoid crashes. This repacking process would therefore make the game incompatible with the widescreen patch (at least, it has in my experience), so listing the USA version as working with widescreen patches is misleading.

**Comment by RocketRobz** [comment]
The repacking thing is outdated info.

**Comment by sks316** [comment]
Oh.
You may want to update the nds-bootstrap compatibility list then...

**Comment by RocketRobz** [comment]
Just did. :P
