### ISSUE TITLE
Twilight stays on the Now Loading... screen

### ISSUE THREAD

**Issue by DrPickens** [DS-Homebrew/TWiLightMenu#723]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v9.0.4]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [x]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

It should load into the menu

### Actual behaviour

It sticks on the loading screen

### Steps to reproduce

1.Play a game
2.Go to 3DS home screen
3.Doesn't load

**Comment by RocketRobz** [comment]
Does the `:` in the clock blink?
If not, press HOME, then press B after 2 seconds.

**Comment by DrPickens** [comment]
Yeah, the : blinks. But that is just about all the animation. The loading Circle Spins too.

**Comment by RocketRobz** [comment]
Try having less ROMs in the folder.
