### ISSUE TITLE
Twilight menu duplicate cheat code error

### ISSUE THREAD

**Issue by coltenxxx** [DS-Homebrew/TWiLightMenu#724]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X ]  Release _[9.0.4]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [X ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen
- Be able to apply cheats like normal.

### Actual behaviour

Tell us what happens instead
- On any theme **except the Acekard themes**, when selecting a cheat such as Experience multiplier in pokemon mystery dungeon explorers of sky, upon toggling a value for the experience multiplier cheat, the code below it is automatically toggling the same value (noticed it only when there are codes right after eachothe with similar values/choices to toggle). So if I toggle x8 for the experience multiplier and the code below it was money reward multiplier x4, for whatever reason me choosing x8 for the code above it is overriding my original value for the code below.

### Steps to reproduce

1. Select codes such as Experience multiplier, or Pokemon starter modifier, and toggle a value
2. Upon saving, the values for the codes below will be a duplicate of the value you just chose.
3.

**Comment by eku** [comment]
This is also a problem in M&L Bowser Inside Story.

**Comment by SleepyLark** [comment]
Still a problem on v14.1.0

**Comment by NightYoshi370** [comment]
Is this a bug on v15.2.0?

**Comment by eku** [comment]
This is still faulty in 308c747a - tested with M&L Bowser Inside Story.

**Comment by SamusAranX** [comment]
This is still a problem in v16.0.0.
I encountered the bug with Castlevania: Dawn of Sorrow.
