### ISSUE TITLE
Codes in up screen

### ISSUE THREAD

**Issue by limabatista** [DS-Homebrew/TWiLightMenu#726]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [x]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
Is it a Guru Meditation Error?

**Comment by limabatista** [comment]
when I open twilight menu a series of codes appears on the top screen
![IMG_1149](https://user-images.githubusercontent.com/54183976/63182867-e7672700-c029-11e9-81f7-6d0438e3b992.JPG)
![IMG_1149](https://user-images.githubusercontent.com/54183976/63182922-154c6b80-c02a-11e9-9e20-fa152c721e85.JPG)

**Comment by RocketRobz** [comment]
If you have not followed my guide for playing in widescreen, please do that.
Re-download the patcher, while doing that.

**Comment by limabatista** [comment]
is working full screen but the codes do not disappear

Ok i gonna try that

**Comment by RocketRobz** [comment]
When you're done, please delete `TwlBg.cxi` at `sd:/luma/sysmodules/` to remove the numbers on the right side.

**Comment by limabatista** [comment]
thanks it worked, I followed a tutorial from brazil and he did not explain this thanks for the help
