### ISSUE TITLE
Guru Meditation Error When TWiLight Menu++ Loads

### ISSUE THREAD

**Issue by stampylongr** [DS-Homebrew/TWiLightMenu#728]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch (v1.9)+HiyaCFW (v1.3.2) _[please specify versions of both]_ 

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen
> TWiLightMenu should load.
### Actual behaviour
> I get an error,
Tell us what happens instead
I get this error on the top screen:
![IMG_20190816_235041](https://user-images.githubusercontent.com/42777835/63206362-d4cc0c80-c080-11e9-936b-9eb6a2436fe4.jpg)

**Comment by RocketRobz** [comment]
Try [this](https://github.com/TWLBot/Builds/commit/16509b3a390743717187e38cb4b76c76be4b9347) nightly build of TWLMenu++.

**Comment by stampylongr** [comment]
Works! Should I close this?

**Comment by RocketRobz** [comment]
Yes.
