### ISSUE TITLE
akMenu cheat selection is unstable

### ISSUE THREAD

**Issue by ClammyMantis488** [DS-Homebrew/TWiLightMenu#730]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [X]  Acekard/akMenu

### Expected behaviour
When left is pressed at the top of the cheats menu nothing should happen.
### Actual behaviour
A guru meditation error.

### Steps to reproduce

1.  Use the Acekard theme
2. Press Y then X to open the cheats menu
3. Press left on the dpad

**Comment by NightYoshi370** [comment]
Fixed as of latest nightly
