### ISSUE TITLE
Certain Themes == Guru Meditation Error

### ISSUE THREAD

**Issue by BrunoDSL** [DS-Homebrew/TWiLightMenu#731]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) Unlaunch only _[1.9]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[9.0.4]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [x]  Acekard/akMenu

### Expected behaviour

Theme should work properly

### Actual behaviour

As the title states, certain themes from the Acekard list (Adv.Evol, gbatemp.v1, zelda, Ds Menu, HatsuneMiku, switch calendar and switch minimal  ) generate Guru Meditation errors. The only way to get out of those is to turn the DSi off and back on as the error hard locks the DSi.

### Steps to reproduce

1. Turn the DSi on and either have it start with the theme or select the theme in the settings.
2. Press 'B' to get out of the folder you're currently in
3. Go to a folder that's not empty, then press 'A' to open it

**Comment by Kodtiz3D** [comment]
This issue is already known internally, the Acekard theme in particular is buggy and it is not known why.

**Comment by chyyran** [comment]
@BrunoDSL Please confirm bugs are still present in the latest version

**Comment by BrunoDSL** [comment]
All problem themes work normally in the latest version.
