### ISSUE TITLE
Adding a feature to disable/enable "ALL" cheats code at once

### ISSUE THREAD

**Issue by ChampionLeake** [DS-Homebrew/TWiLightMenu#736]
**Is your feature request related to a problem? Please describe.**
Others and myself tend to spend too much time scrolling through our cheat list to enable or disable codes. Leaving users to sometimes want to delete their cheat.dat file and make a new one for specific tasks.

**Describe the solution you'd like**
A clear and time-saving way to solve this is to have a option that provides the user to disable/enable ALL cheats from the list.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by FlameKat53** [comment]
I could look into this later, but no guarantee. I'd need to see what changes in the usrcheat.dat once you enable a cheat and make sure that doesn't pop up in any of the actual codes

**Comment by RocketRobz** [comment]
Closed via #979

**Comment by eku** [comment]
@RocketRobz  #979 only deactivates all cheats with L, but does not activate all. Please reopen this issue.

**Comment by Epicpkmn11** [comment]
Disabling was added in #979 as Robz said above, and enabling just doesn't seem practical to me, so should this still be open?

Enabling all:
1. Would likely result in too many active cheats
2. Would me messy with single option folders, should it enable the first one? the last one? none?
3. You really just probably don't want all the codes on except for in very special circumstances

**Comment by NightYoshi370** [comment]
Besides, not only is there a cheat limit but some directly conflict with others.
Closing, due to all the issues mentioned
