### ISSUE TITLE
Accident

### ISSUE THREAD

**Issue by Proyecto-N** [DS-Homebrew/TWiLightMenu#738]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- []  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- []  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- []  Release _[9.1.2 at present]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- []  DSi Menu
- []  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

I accidentally installed TWiLight 9.0.4 by the Updater and did not read that it would generate errors. Now I think I have them... How do I solve it?
I tried to delete the program and reinstall it manually, but I think it's the same...

I also ask if they will soon have the "Pokémon Mundo Misterioso: Equipo de Rescate Azul" (Pokemon Mystery Dungeon: Blue Rescue Team" in spanish of Spain, I am from South America, Venezuela) soon on Widescreen :D

**Comment by RocketRobz** [comment]
What are the errors?
Also, the game will less likely have a widescreen patch, as it's using the 2D engine.

**Comment by Proyecto-N** [comment]
It seems that the music to the title "2 anniversary" is delayed with the music, I also think I had an error when entering the "DS screen", among other graphic errors, I expected you to tell me to recognize them it.
