### ISSUE TITLE
Hex on the right side of 3ds when using widescreen

### ISSUE THREAD

**Issue by Ultraman360** [DS-Homebrew/TWiLightMenu#742]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release _[Twl 9.1.2]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Tell us what should happen
A Ds game in widescreen

Tell us what happens instead
Hex on the right side of the top screen 
![IMG_20190825_183313](https://user-images.githubusercontent.com/54516029/63658332-13d81d00-c767-11e9-9932-2d9f5f64f222.jpg)

### Steps to reproduce

1.Follow the steps to do the widescreen ds games
2.Run a game
3.See what happen

**Comment by NightYoshi370** [comment]
Is this within twilightmenu itself that you get the hex numbers, or within the application?

**Comment by Ultraman360** [comment]
Is not twilight and is not the app

**Comment by Ultraman360** [comment]
is when i turn on the widescreen mode

**Comment by RocketRobz** [comment]
When did you download the patcher?
If it was just recently, did you make and run the .bat file?

**Comment by Ultraman360** [comment]
No i didn't ran it

**Comment by Ultraman360** [comment]
and i dowloaded it yesterday

**Comment by RocketRobz** [comment]
> No i didn't ran it

That's why you're seeing hex numbers.
Please run the .bat file.

**Comment by Ultraman360** [comment]
ok thanks Rocket Robs
