### ISSUE TITLE
Have a random chance to play a different sound on startup

### ISSUE THREAD

**Issue by sks316** [DS-Homebrew/TWiLightMenu#747]
I've noticed a bug in TWLMenu that randomly causes the sound that usually plays on startup to be muted. While this is a _bug_, it gave me an idea. Perhaps you could have a random chance of playing a different sound on startup, for example [Totaka's Song](https://www.youtube.com/watch?v=aR9xAtD4CYA). This could be treated as an easter egg in TWLMenu++, and could be toggleable in the settings with an "Enable easter eggs" switch. It's a stupid suggestion, but a suggestion nonetheless.

**Comment by spellboundtriangle** [comment]
TWLM++ already has easter egg/holiday intros for specific dates, wouldn't this kinda clash with that?
