### ISSUE TITLE
Pokémon Black very slow

### ISSUE THREAD

**Issue by dedenneisgood** [DS-Homebrew/TWiLightMenu#750]
First time ever doing this. Sorry if i’m doing anything wrong. 

The game is Pokemon Black. It takes around 15 minutes to boot, and when it does it runs very slow during battles, transitioning through menus, or pretty much anything that isn’t just walking around. Again, sorry if I did this in the wrong place.

**Comment by takeshineale128** [comment]
There a problem may be do with your Sd card because mine have no issues

**Comment by dedenneisgood** [comment]
I don’t think that’s the case. I have a 64gb SD card formatted in FAT32. What other problems would there be?

**Comment by RocketRobz** [comment]
You might have an outdated TWLMenu++ and/or nds-bootstrap version.

**Comment by dedenneisgood** [comment]
I just downloaded the most recent version last night. After re-ap patching it the issues are still present.

**Comment by RocketRobz** [comment]
You don't need to manually AP-patch it now.

**Comment by RocketRobz** [comment]
Check your SD card for errors, just to be sure.

**Comment by dedenneisgood** [comment]
What errors should I be looking for?

**Comment by RocketRobz** [comment]
How do you check your SD card for errors?

**Comment by dedenneisgood** [comment]
Not sure, not too experienced with this whole thing.

**Comment by dedenneisgood** [comment]
Just finished checking, and there seems to be no errors.
Anything else you can think of?

**Comment by RocketRobz** [comment]
The SD card might be slow for nds-bootstrap to handle.
Try another one.

**Comment by dedenneisgood** [comment]
I’m not sure it’s the SD card that is the problem. On a New 3ds XL that recently broke it worked fine, and it’s the same brand and size of sd card. Could it be the fact that I’m running this on the first 3ds?

**Comment by dedenneisgood** [comment]
Should probably mention that it’s only Black that’s running like this. SoulSilver and Platinum run fine.

**Comment by RocketRobz** [comment]
That makes the situation even stranger.
Try another SDK5 ROM that isn't Pokemon, and see if it also loads slow.

**Comment by dedenneisgood** [comment]
Not exactly sure what a SDK5 ROM is. Kind of new to this whole thing.

**Comment by dedenneisgood** [comment]
I thought maybe it was the rom that was the problem, so I got a fresh install. Still got the same results. I even tried a ROM hack of Black, and that didn’t work either.

**Comment by RS55** [comment]
did you format your SD correctly? 32kb cluster?

**Comment by NightYoshi370** [comment]
Hey, uh, sorry to ruin the show but this doesn't belong here. Please move it over to ahezard/nds_bootstrap
