### ISSUE TITLE
Kirby Mass Attack AP message

### ISSUE THREAD

**Issue by Csgm** [DS-Homebrew/TWiLightMenu#752]
when i open kirby mass attack it tells me it needs an ap patch this isnt an imediate issue but if you could get it to work properly it would be appreciated i really admire what you do for the community because I have had lots of nostalgia and have had some memories brought  back from using your service thank you 

If you are trying to resolve this thank you and also thank you for making the twilight menu because i have had the most fun time being on it and playing my old games that i sadly no longer have Thanks Rocket

**Comment by RocketRobz** [comment]
As of currently, the ROM needs to be manually AP-patched.
