### ISSUE TITLE
Wireless connection not switching on but off

### ISSUE THREAD

**Issue by ErdbeerbaerLP** [DS-Homebrew/TWiLightMenu#759]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[9.3.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [X]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

You should be able to toggle wifi on and off

### Actual behaviour

It will only turn it off but hitting the switch again does nothing

### Steps to reproduce

1. Start TwilightMenu
2. Disable wifi
3. Try to enable it again

**Comment by RocketRobz** [comment]
This is normal.
WiFi can't be re-enabled in TWL_FIRM, as a whole.
