### ISSUE TITLE
Oregon Trail - dsiware not work

### ISSUE THREAD

**Issue by tomudo** [DS-Homebrew/TWiLightMenu#760]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW  -Unlaunch 2.0 / HiyaCFW 1.3.2

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release 23.0
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Oregon Trail - work

### Actual behaviour
Game do not start. It white then black screen and freeze after that.
### Steps to reproduce

1. Run Oregon Trail - dsiware
2. Screen go white and black
3. Game freeze - cannot soft reset(need hard reset by hold power button).

**Comment by RocketRobz** [comment]
Is any setting shown, when pressing Y in the ROM menu?

**Comment by tomudo** [comment]
=============

[icon picture] The Oregon Trail
                     Gameloft

Oregon Trail.nds
SDK  ver: 5 (TWLSD)   SDK TID: KORE
==================

No, configuration menu.

**Comment by RocketRobz** [comment]
So this is an Unlaunch issue then.

**Comment by RocketRobz** [comment]
Please report it to the Unlaunch thread at nesdev.
