### ISSUE TITLE
AP patching not work when using 'most recent' sorting option

### ISSUE THREAD

**Issue by hubert-skowronek** [DS-Homebrew/TWiLightMenu#761]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release 9.3.0
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour
Radiant Historia US, ML Bowser Inside Story US, Ghost Trick (EUR), LoZ ST (EUR) should work and be AP patched

### Actual behaviour

Radiant Historia - not AP patched, can't read or write save file
ML BiS - hangs on the white screen just after booting the game
Ghost Trick - not AP patched, can't see dialogues
LoZ Spirit Tracks - hangs on the black screen just after booting

I use nds-bootstrap release version 0.24.0. My roms are clean and trimmed.

**Comment by RocketRobz** [comment]
I have no issues with BiS and Spirit Tracks.

**Comment by RocketRobz** [comment]
What did you use to trim the ROM. Those should work fine.

**Comment by hubert-skowronek** [comment]
@RocketRobz  I have used http://eden.fm/ndstoykotrim/ - do you use something else?

**Comment by RocketRobz** [comment]
I just use a hex editor to trim off the padding. :P

**Comment by hubert-skowronek** [comment]
I still have the issue even with clean, untrimmed rom... the steps I did:
1. removed _nds directory and boot.nds from the SD card
2. downloaded twilightmenu 9.3.0, unpacked and put needed files to SD card
3. just run the rom

Should I do anything else/verify something?

**Comment by RocketRobz** [comment]
Are the .ips files in `sd:/_nds/TWiLightMenu/apfix/`?

**Comment by hubert-skowronek** [comment]
@RocketRobz Yes, they are - CLJE-CE77 for M&L BiS, sha1 of my rom: c3eb5ea6f90069294f4baa9148764102eff059ea

**Comment by RocketRobz** [comment]
Is that same .ips filename shown in `nds-bootstrap.ini`?

**Comment by hubert-skowronek** [comment]
> AP_FIX_PATH =

so it seems that in my case nds-bootstrap.ini is not updated with AP fix path - why is that?

**Comment by RocketRobz** [comment]
The header CRC in the ROM might be different.

**Comment by hubert-skowronek** [comment]
But for all of these mentioned 4 roms?

**Comment by RocketRobz** [comment]
My only guess is that the ROMs have already been modified from the clean ones in some way.

**Comment by hubert-skowronek** [comment]
May I ask you for checksum of your clean roms? Or at least ML BiS

**Comment by RocketRobz** [comment]
Same one as yours: `C3EB5EA6F90069294F4BAA9148764102EFF059EA`

**Comment by hubert-skowronek** [comment]
Then how crc may be different if it is the same file?

**Comment by RocketRobz** [comment]
Open the ROM in a hex editor, and check it at 0x15E.

**Comment by hubert-skowronek** [comment]
It is 77 CE

**Comment by RocketRobz** [comment]
Ok good. Those bytes should already be reversed for the `.ips`.

This makes no sense. It seems that TWiLight Menu++ just isn't picking up the file.
Try using the updater to update to v9.3.0.

**Comment by hubert-skowronek** [comment]
I have already done this, I think I found the issue, I observed strange state of nds-bootstrap.ini after turning off Radiant Historia, it pointed to valid rom and save, but to AP fix of previous game (ML BiS)... I had turned on 'most recent' sorting option in the settings, I reverted it to factory default (alphabetical) and AP patch worked. So there is a bug here in the end

**Comment by NightYoshi370** [comment]
Sorting code was improved since the time this issue was made. Since there was no comment on whether this has been fixed or not, I'll close this
