### ISSUE TITLE
Per-game widescreen settings

### ISSUE THREAD

**Issue by LeddaZ** [DS-Homebrew/TWiLightMenu#763]
I use the widescreen patch a lot, but with some games (Pokémon for example) I prefer widescreen disabled. Would it be possible to implement per-game widescreen settings so you can choose to use it or not for each game?

**Comment by SleepyLark** [comment]
Already been asked (#718).

**Comment by NightYoshi370** [comment]
This is kind of in already: Just remove/rename the file and it won't become widescreen anymore.
Since it was already asked and closed, I'll be closing this duplicate as well
