### ISSUE TITLE
Screen black when close the screen 

### ISSUE THREAD

**Issue by EtianAM** [DS-Homebrew/TWiLightMenu#764]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS [10.0.1]
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[9.3.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Close the screen and the game continue

### Actual behaviour

Close the screen but the console continue in dark screen but the game still runing

### Steps to reproduce

1. Start TWiLight Menu++
2. Star a game (In my case, I probe Mario 64 and Rhythmin Paradise)
3. Close the screen (In some case and in short times, the game continue)
4. Open the scrren

**Comment by RocketRobz** [comment]
Please use NTR clock speed for those games.

**Comment by EtianAM** [comment]
Thanks
