### ISSUE TITLE
no game starts ...

### ISSUE THREAD

**Issue by lenix9090** [DS-Homebrew/TWiLightMenu#765]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [X ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X ]  Release _[v9.3.0]_
- [ ]  Nightly _[insert here commit hash]_

**Comment by lenix9090** [comment]
and updated to the most recent version, but I brought the nds-bootstrap, I downloaded it (recent too) and I don't run any games, it makes the .sav file, I get the nds-bootstrap logo and then it goes blank screens (in "Tetris DS" remain black) ...

**Comment by lenix9090** [comment]
P.S: I had to use an old version.

(Google translator)

**Comment by RocketRobz** [comment]
Are you using Flipnote Lenny or Memory Pit?
If the first, please use Memory Pit.

**Comment by FlameKat53** [comment]
also, I recommend at the least installing Unlaunch

**Comment by RocketRobz** [comment]
He can't install Unlaunch.
afaik, he gets the mismatch error.

**Comment by FlameKat53** [comment]
oh, I see
