### ISSUE TITLE
White screen when booting Pokemon Black

### ISSUE THREAD

**Issue by Booksisgreat** [DS-Homebrew/TWiLightMenu#766]
I'm using the most recent version TwilightMenu++ (9.3.0) and I'm using a New 3DS XL. I followed the instructions for installing TwilightMenu++ and I booted it through Sudoku. I successfuly boot into the DSI menu but upon selecting Pokemon Black, I get a white screen. I stayed at this screen for 10 minutes but to no avail.

**Comment by RocketRobz** [comment]
Are you running the game in DS mode?

**Comment by Booksisgreat** [comment]
I'm sory, I'm not quite sure what you mean by that. I'm not very well versed with modding stuff but my 3DS is homebrewed and I can boot into the DSI interface through Sudoku.

**Comment by RocketRobz** [comment]
Check the `Run in` option in TWLMenu++ settings.

**Comment by Booksisgreat** [comment]
Ah yes it does say DS mode. Should I change that?

**Comment by RocketRobz** [comment]
No, it should be DS mode.
Do other ROMs work?

**Comment by Booksisgreat** [comment]
I haven't tested any others. What's a good one to test with?

**Comment by RocketRobz** [comment]
Super Mario 64 DS.

**Comment by Booksisgreat** [comment]
Downloading it, will report back in a bit

**Comment by Booksisgreat** [comment]
Super Mario 64 DS gets to the NDS Bootstrap loading screen, then the Nintendo logo and then a black screen that I've been at for like 3 minutes.

**Comment by RocketRobz** [comment]
So SD reads stop working, once the game has loaded.

Please install the TWiLight Menu++ CIA, and launch it to fix this bug.

**Comment by Booksisgreat** [comment]
Sorry, I don't understand what you mean. Do you mean the CIA files included in the zip file?

**Comment by RocketRobz** [comment]
Yes.

**Comment by Booksisgreat** [comment]
Sorry I'm so dense but how do I launch this CIA?

**Comment by RocketRobz** [comment]
You install it using FBI.

**Comment by Booksisgreat** [comment]
I instaled the gamebooter CIA and the Twilight Menu CIA through FBI and the games still won't start.

**Comment by RocketRobz** [comment]
You launch TWiLight Menu++ from 3DS HOME Menu now, not Sudoku.

**Comment by Booksisgreat** [comment]
Oh my God it works!!! Thank you so much for walking me through this process and holding my hand, I really do appreciate it. I couldn't have done it without the help, I can't thank you enough.

**Comment by RocketRobz** [comment]
You're welcome!
