### ISSUE TITLE
Custom sram file size

### ISSUE THREAD

**Issue by tomudo** [DS-Homebrew/TWiLightMenu#767]
**Is your feature request related to a problem? Please describe.**
Default save filesize is 512KB and hardcode to specific game. It would be nice to have configuration of save file size.

**Describe the solution you'd like**
Custom sram file size.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by FlameKat53** [comment]
proposed alternative: make savefile on a computer at a custom size?

**Comment by SleepyLark** [comment]
Is there a specific reason why this is needed?

**Comment by RocketRobz** [comment]
Save size per-game is already a thing.
