### ISSUE TITLE
I selected the wrong model how do i change it?

### ISSUE THREAD

**Issue by Storm-Surfer7** [DS-Homebrew/TWiLightMenu#768]
I accidentally selected the ds option when it prompted me to select my model. how do i change what model i am using? i would like it if i do not need to delete TWiLight Menu++ but if that's all there is i would just like to know.

**Comment by RocketRobz** [comment]
Delete `settings.ini` at `sd:/_nds/TWiLightMenu/`.

**Comment by Storm-Surfer7** [comment]
thank you
