### ISSUE TITLE
Mario & Luigi Bowser's Inside Story Saving Issue

### ISSUE THREAD

**Issue by pichuzapper** [DS-Homebrew/TWiLightMenu#770]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [. ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ .]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ .]  Release _[v0.24.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ .]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour
I expected that the game will keep going and not make any file unplayable

### Actual behaviour
Saving the file in any way white screens, once I boot the game up and continued on my file, the game crashes.  Resetting the file and not saving is the only way to play

### Steps to reproduce

1. Start a new game
2. Before the Bowser tutorial boss, save your game
3. Beat the boss and the games crashes when Peach flings Bowser to the bottom screen
4. This can happen anywhere. For example, when a game is saved when Bowser is in Cavi Cave, rebooting the file crashes the game

**Comment by RocketRobz** [comment]
Loading your save only crashes sometimes.
Also, I do not have the issue where saving causes a white screen. If you're trying to return to the title screen, that doesn't work, due to soft-reset not working.
