### ISSUE TITLE
Plz make compact with drastic emulator

### ISSUE THREAD

**Issue by spike74** [DS-Homebrew/TWiLightMenu#772]
Plz can you make this compatible with the drastic ds emulator for android.

**Comment by edo9300** [comment]
Drastic uses the same save files as desmume, so launch the game there, then use the import backup memory option in ddesmume, and copy the dsv file from it's battery folder

**Comment by spike74** [comment]
Ok Thanks mate :)

On 21 September 2019, at 13:59, Edoardo Lolletti <notifications@github.com> wrote:

Drastic uses the same save files as desmume, so launch the game there, then use the import backup memory option in ddesmume, and copy the dsv file from it's battery folder

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/DS-Homebrew/TWiLightMenu/issues/772?email_source=notifications">https://github.com/DS-Homebrew/TWiLightMenu/issues/772?email_source=notifications</a>\u0026email_token=ANIML7UF2OAGCP5AGCNO7YDQKYLD5A5CNFSM4IY6DTLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7IRKUY#issuecomment-533796179", "url": "<a href="https://github.com/DS-Homebrew/TWiLightMenu/issues/772?email_source=notifications">https://github.com/DS-Homebrew/TWiLightMenu/issues/772?email_source=notifications</a>\u0026email_token=ANIML7UF2OAGCP5AGCNO7YDQKYLD5A5CNFSM4IY6DTLKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD7IRKUY#issuecomment-533796179", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]
