### ISSUE TITLE
AP Patch with some games

### ISSUE THREAD

**Issue by Proyecto-N** [DS-Homebrew/TWiLightMenu#775]
Hi, I don't know if it's a bug or what, but I'm playing Kung Fu Panda (EUR) and Ben 10 Ultimate Alien: Cosmic Destruction (EUR) and I'm not sure if they have AP Patch, because they don't appear on the list, and B10CD used to show me a message that said I didn't have it, but my sister started gaming it without my permission and after a few days... I played it and the message didn't appear... I don't know if it happens with more games that is an error of my console.

*Old 3DS

**Comment by RocketRobz** [comment]
If the games work fine without an AP patch, then don't worry about it.
