### ISSUE TITLE
Asks for nds-bootstrap on R4iSDHC

### ISSUE THREAD

**Issue by niansa** [DS-Homebrew/TWiLightMenu#776]
### Your console

Tell us which console do you have:

- [x]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release v9.4.0 (Autoboot)
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu (yellow)
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Game starts

### Actual behaviour

Game does not boot because nds-bootstrap is missing (!?!?!?)
However, as soon as I copy nds-bootstrap to the SD-Card it tells me that I am on wrong edition (no clue what that means)

### Steps to reproduce

1. Setup everything on the flash card
2. Try to start any game
3. Will fail

**Comment by niansa** [comment]
Update: booting TWiLightMenu on 3DS, then from there booting the flash card and then starting a game results in black screen

**Comment by RocketRobz** [comment]
You can't run games with TWiLight Menu++ on that flashcard.

**Comment by niansa** [comment]
Could you add a note about that somewhere, so others don't ask the same?
