### ISSUE TITLE
Run off string when displaying game title in 'recently played game' menu

### ISSUE THREAD

**Issue by elephantdino** [DS-Homebrew/TWiLightMenu#778]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X ]  Release _[v9.5.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Game title in 'recently played' should fit nicely in allocated box.

### Actual behaviour

Game title in 'recently played' runs off (outside)  the 'box' if the title is too long.

### Steps to reproduce

1. Load Legend of Zelda, The - Oracle of Ages (U) [C][!] from roms folder in twilightmenu
2. exit to homescreen
3. launch twilightmenu and observe a run off title in the 'recently played game'

**Comment by RocketRobz** [comment]
Is Oracle of Ages the only ROM you have?

**Comment by elephantdino** [comment]
Yes the bug happens with any other ROM.

**Comment by SleepyLark** [comment]
Still happens (now called the DS Classic menu), could possibly be fixed by #999

**Comment by NightYoshi370** [comment]
Yeah, #999 would be a more preferable issue, since this isn't a bug.
Closing
