### ISSUE TITLE
Old Flashcard R4 Wood, will it work?

### ISSUE THREAD

**Issue by danylopez123** [DS-Homebrew/TWiLightMenu#782]
(Apologizes if i put this in the wrong section, i wasnt seeing more options)

My only Flashcard that im having is the R4 Wood, but this is a very old one so it can only work with a Normal NDS or NDS Lite.

Seeing that this can also work with Flashcard, i was wondering if the R4 Wood im having will it work.
Wood R4 Link: http://www.r4ds.com/wood-r4/wood-r4-v1.62-download.html

**Comment by RocketRobz** [comment]
I think you can only run homebrew on the flashcard with this.

**Comment by danylopez123** [comment]
This flashcard that i was always using in my Fat NDS can also run all NDS games with no compatibility issue, all runs perfect.
As well it can run any Homebrew without freezing and stuff.

I was just wondering if this can still work if you add the Firmware to the SD/MicroSD card because for the game card, because its a very old one, doesn't work for a DSi and neither for any 3DS

**Comment by RocketRobz** [comment]
You can try.

**Comment by danylopez123** [comment]
Ok then, then ill try to put all of the Firmware content from the Wood R4 Flashcard to the MicroSD card.

What was the thing i had to do again to run games using the Flashcard firmware rather than the nds-bootstrap?

**Comment by RocketRobz** [comment]
Go into TWLMenu++ settings, then turn off `Use nds-bootstrap`.

**Comment by danylopez123** [comment]
Ok, so...

I re-downloaded the Wood R4 firmware and put it in the root from my MicroSD card, disabled the use of nds-bootstrap, tried a game that haves some compatibility issues like New Super Mario Bros (EUR) crashing when you go to the Minigames option.

... it didin't worked, still it's using nds-bootstrap

**Comment by RocketRobz** [comment]
How so?

**Comment by danylopez123** [comment]
I dont know... it's the one i downloaded from the link i put in the first post.
That is also what i were using for my Wood R4 Flashcard for my Fat NDS.

All i disable is the "Use nds-bootstrap" and nothing else.

**Comment by RocketRobz** [comment]
I mean what happens when you launch the game?
Does it still show nds-bootstrap not found?

**Comment by danylopez123** [comment]
It doesn't say anything for that, just boots the game still with nds-bootstrap even tho i disabled the option.

**Comment by RocketRobz** [comment]
Try deleting nds-bootstrap.

**Comment by danylopez123** [comment]
I did and... it says:
Start failed. Error 1
nds-bootstrap (Release) not found

And im STILL having the use nds-bootstrap disabled.

**Comment by RocketRobz** [comment]
Is it still shown as disabled when going into TWLMenu++ settings?

**Comment by danylopez123** [comment]
Yes.
Slot-1 SD: Use nds-bootstrap = No

**Comment by RocketRobz** [comment]
Looks like you're changing the setting on the DSi or 3DS.
On flashcard, it's just shown as `Use nds-bootstrap`.
On my side, turning off `Use nds-bootstrap` does make it use the flashcard firmware.

**Comment by danylopez123** [comment]
Oh... dam...
Then i guess i can't make this work... it was a very old Flashcard after all...

Meh... i give up, ill stick the what i have, it's good enough for me.
Ill just use Homebrew from my Flashcard for my Fat NDS.

**Comment by danylopez123** [comment]
Wait... nevermind...
I think i found the fix for it.
You need to select "Launch Slot-1 Card" and it will boot the Flashcard.

But because of the MicroSD card im having for the Flashcard, it's only 1 GB.

At least, ill use this for the Compatibility issues with some NDS games + for Homebrew aplications.
