### ISSUE TITLE
Corrupted Files

### ISSUE THREAD

**Issue by Pootismancer** [DS-Homebrew/TWiLightMenu#784]
I installed a Sonic Colors DS ROM, then tried to launch it. It didn't work so I went to the Home Menu. When I came back, though, I can't launch anything. And I can't delete the corrupted files, either. Is there a solution for this?

**Comment by RocketRobz** [comment]
Your SD card might be dying. Try another SD card.

**Comment by Pootismancer** [comment]
Nevermind, just rebooted the PC. Now I fixed it. Thanks for the tip, though!
