### ISSUE TITLE
Tapping on games in DSi theme to start them

### ISSUE THREAD

**Issue by androidian5980** [DS-Homebrew/TWiLightMenu#786]
**Is your feature request related to a problem? Please describe.**
I first found the problem when I tried launching a game by tapping it instead of pressing A, but nothing happens and acts as if i'm scrolling.

**Describe the solution you'd like**
When a application is tapped on, it should open.

**Comment by androidian5980** [comment]
Wait, thats a bug?

**Comment by RocketRobz** [comment]
Yes. Tapping the game is supposed to make it start, but it's not working for some reason.

**Comment by FlameKat53** [comment]
tapping on the icons is ***super*** sensitive, but it does work at times.

**Comment by hgdagon** [comment]
This used to work. Not as smoothly in the DSi Menu itself, but it did. One of the recent updates broke/removed it.

**Comment by Epicpkmn11** [comment]
I think this was fixed a while ago, its working for me in the latest release. It might be a little too sensitive, but not particularly hard to click

**Comment by NightYoshi370** [comment]
Yep, not happening for me. Closing
