### ISSUE TITLE
Zip Support 

### ISSUE THREAD

**Issue by dusty9** [DS-Homebrew/TWiLightMenu#788]
Twilight menu is amazing! My only issue is no zip support for nes, snes, genesis etc. except gbarunner thats not your project. Well Anyways Currently forced to use retroarch due to space savings. I would love if this had zip support added at least for 3ds.

**Comment by vaguerant** [comment]
It's not what you're asking for, but TWiLightMenu++ does already have lz77 compression support for SNES and Mega Drive/Genesis ROMs (and possibly other things, I'd wait for advice from somebody more knowledgeable).

On the other hand, are you really saving that much by compressing your SNES and Genesis ROMs? One DS ROM can be up to 512MB, and the largest SNES ROM as far as I can tell was 6MB.
