### ISSUE TITLE
Dragon Quest IX, not start after first start.

### ISSUE THREAD

**Issue by franciscomirasg** [DS-Homebrew/TWiLightMenu#789]
I try to start Dragon Quest IX, the first load works fine. But If you exit from the game and you try to load from the last game played or the room menu. The game doesn`t load. It keep a white screen. 
I use:
2DS new, Luma(Latest Version)

**Comment by RocketRobz** [comment]
Try deleting the fatTable and patchOffsetCache files in `sd:/_nds/nds-bootstrap/`.

**Comment by franciscomirasg** [comment]
Now appear the boostraper screen and then keep stuck on white screen

**Comment by RocketRobz** [comment]
Seems like the ROM is corrupted.
Try replacing it with a clean one.
