### ISSUE TITLE
Slot 2 for Twilight

### ISSUE THREAD

**Issue by mrex999** [DS-Homebrew/TWiLightMenu#794]
Is there some way to add slot 2 on Twilight menu? I want to use pal park on my Pokemon Games.

**Comment by RocketRobz** [comment]
That is coming in the future.

**Comment by mrex999** [comment]
Ohhh my gosh, thanks for the quick answer, I'm playing gen 3 emerald and leafgreen on gbarunner2 and it's amazing, but I'm tired of using desmume on my phone, I need to use ftp and I'm tired of using it.

**Comment by Leeo97one** [comment]
Any news on this?

**Comment by BlackBeltBoi02** [comment]
Has the update been made?

**Comment by RocketRobz** [comment]
Due to attempts to implement this, chances are low that it's coming.

**Comment by Zakattack08** [comment]
Has the update been made? I want to use pal park on my Pokemon Games and I found this.

**Comment by RocketRobz** [comment]
> Has the update been made? I want to use pal park on my Pokemon Games and I found this.

Nope. We're still lost on what to do.

**Comment by hullmat998** [comment]
> > Has the update been made? I want to use pal park on my Pokemon Games and I found this.
> 
> Nope. We're still lost on what to do.

Darn. I was just looking for this myself.
 Thanks for giving us Twilight Menu and replying to these necro'ed threads.

**Comment by Zakattack08** [comment]
> Darn. I was just looking for this myself.

I found software that acts like Pokemon bank that's compatible with Twilight Menu Pokemon saves and gba virtual console on 3ds and its called pksm
here it is: https://github.com/FlagBrew/PKSM/releases
