### ISSUE TITLE
Add support for using DSTT flashcard firmware to load retail/commercial ROMs

### ISSUE THREAD

**Issue by veractor** [DS-Homebrew/TWiLightMenu#795]
**Is your feature request related to a problem? Please describe.**
Very little games launch for me at the moment using B4DS on a DSTT flashcard (on a DS Lite). However, other menus on this flashcard launches games just fine.

**Describe the solution you'd like**
Add a DS game forwarder pack for the DSTT flashcard! :)

**Describe alternatives you've considered**
Using the relatively unattractive [YSMenu](https://github.com/DS-Homebrew/Flashcard-Firmware-Archive/raw/master/DSTTi%20TT%20YSMenu%207.06.rar) or the original and slower TTMenu to launch games. It gets the job done, but let's be honest here, I'd prefer a fancier system.

**Additional context**
When I saw on GBATemp news that TWiLightMenu++ now supports using B4DS, I was pleasantly surprised. This is an amazing piece of homebrew, it spices up the entire user experience for me, and now I get to use it on my DS Lite!
However, B4DS has very little support for games at the moment, especially on my DSTT flashcard. This turns the whole experience upside down for me. I could only launch 1 game in my list, and that was Super Mario 64 DS! Even when I tried any other games listed as working on the B4DS list like Chrono Trigger, it still white screens for me.

**Comment by veractor** [comment]
I don't mean loading YSMenu to load up games, I meant using TWLMenu++ to load games directly has little compatibility, and so I have to resort to using YSMenu to do just that. Sorry for the confusion.

**Comment by RocketRobz** [comment]
Nope, can't be done.
TWLMenu++ itself cannot patch the functions in order for the game to work, so B4DS does that.
The right functions are patched. The issue is that some games don't work, depending on your flashcard.
The most stable flashcards for B4DS, are R4i Gold RTS, and R4 Ultra, which both use the R4iDSN DLDI driver.
