### ISSUE TITLE
NES roms doesn't work

### ISSUE THREAD

**Issue by Roulik** [DS-Homebrew/TWiLightMenu#796]
When i try run rom with extension .fds i get black screen

Thanks

**Comment by RocketRobz** [comment]
Was it renamed from .nes?

**Comment by Roulik** [comment]
Yes was .nes and i rename to .fds because as .nes doesn't show

**Comment by RocketRobz** [comment]
.nes shows fine.
What theme are you using?

**Comment by Roulik** [comment]
My theme is dsi sub theme green

**Comment by RocketRobz** [comment]
If you have more than 40 games, switch pages.

**Comment by Roulik** [comment]
Solve it, the rom was Hammerin' Harry (Europe).nes i rename it to Hammerin Harry.nes and now show in menu and runs ok
