### ISSUE TITLE
TWillight Menu settings don't close when pressing B button, but copy the top screen on the bottom screen

### ISSUE THREAD

**Issue by flutterbrony** [DS-Homebrew/TWiLightMenu#797]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch 1.8 and the latest version of hiya]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[10.2]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [x]  3DS HOME Menu
- [ ]  SEGA Saturn
- [x]  R4
- [x]  Acekard/akMenu

### Expected behaviour

When pressing the B button in the settings, it should close TWillight Menu settings, and return to the main TWiLight Menu

### Actual behaviour

It just copy the top screen on the bottom screen

### Steps to reproduce

1. Open TWiLight Menu ++ settings
2. change your settings (or not)
3. Quit the settings by pressing B
4. The top screen is now also on the bottom screen, and you have to restart the console to continue

**Comment by RocketRobz** [comment]
Are you sure you're on the latest?
What's the version number shown?

**Comment by flutterbrony** [comment]
It was 10.2.0, and 10.1.0, but I reinstalled it, and everything works fine now
