### ISSUE TITLE
Red screen when try to start any game

### ISSUE THREAD

**Issue by EtianAM** [DS-Homebrew/TWiLightMenu#799]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[10.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

They game starts normaly

### Actual behaviour

The game do nota start and show a red screen with some stranger codes. Note: The game starts with fordwarders but not un TWLight Menu

### Steps to reproduce

I do not know.
![IMAG0070](https://user-images.githubusercontent.com/42478705/67178023-c65ae380-f396-11e9-9e3f-4b96d88065bb.jpg)

**Comment by RocketRobz** [comment]
Easy fix: Turn off `Update recently played list`

**Comment by kagexice** [comment]
For some reason my screen turns red when i try to boot up dragon quest ix on my old 3ds xl, even though i turned off "update recently played list"

**Comment by RocketRobz** [comment]
Try downgrading nds-bootstrap v0.64.1. If the issue persists, then your ROM is corrupted, and will need to be replaced.

**Comment by kagexice** [comment]
how do i downgrade?

**Comment by RocketRobz** [comment]
Download it from this page, and follow instructions in it: https://github.com/DS-Homebrew/nds-bootstrap/releases/tag/v0.64.1

**Comment by kagexice** [comment]
ok thx! just in case its corrupted, how do i replace it?

**Comment by RocketRobz** [comment]
Re-dumping the ROM from your cartridge usually fixes it.
