### ISSUE TITLE
Error Install Cia

### ISSUE THREAD

**Issue by kaitomugui** [DS-Homebrew/TWiLightMenu#800]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [ ]  Release _[please specify version]_
- [x ]  Nightly _[a2e46919]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

That the cia is installed without problems and you can use TwiMenu

### Actual behaviour

**It is wrong to install the cia, it is not installed from fbi or Twimenu update**
Image:  https://ibb.co/j4x2BTp

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
How are you running FBI?

**Comment by kaitomugui** [comment]
> ¿Cómo estás ejecutando el FBI?

From Hombrew

**Comment by RocketRobz** [comment]
The Homebrew Launcher loader?

**Comment by kaitomugui** [comment]
> The Homebrew Launcher loader?

Yes, Rosalina

**Comment by RocketRobz** [comment]
Try checking your SD card for errors.

**Comment by kaitomugui** [comment]
> Try checking your SD card for errors.

I can install: TWiLight Menu - Game booter.cia

But not TWiLight Menu.cia

**Comment by RocketRobz** [comment]
Try checking anyways.
idk what else is wrong.

**Comment by kaitomugui** [comment]
> Try checking anyways.
> idk what else is wrong.


Try several things:

CTRnandTrasnfer
Twlfix

And nothing

**Comment by RocketRobz** [comment]
Use your PC to check your SD card for errors.

**Comment by kaitomugui** [comment]
> Use your PC to check your SD card for errors.

In My fbi TWL nand does not appea

https://ibb.co/9HbjgH4

**Comment by RocketRobz** [comment]
Ok... what version of Luma are you using?

**Comment by kaitomugui** [comment]
Luma v10.0.1-a2e46919

**Comment by kaitomugui** [comment]
Ready to solve it, I had problems with the TWL partition

**Comment by RocketRobz** [comment]
If you mean you *are* ready, try installing the CIAs again.
