### ISSUE TITLE
No initial splash screen causes 30+ sec of white screen during DSi boot

### ISSUE THREAD

**Issue by neversphere** [DS-Homebrew/TWiLightMenu#801]
### Your console

Tell us which console do you have:

- [X]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [X]  Unlaunch+HiyaCFW _[Unlaunch: 1.8 | HiyaCFW: 1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[10.3.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Indication that Twilight Menu is booting at the 20 sec mark

### Actual behaviour

White screen for a full 30 secs after pressing the power button.

### Steps to reproduce

1. Install Unlaunch and have it auto launch Hiya which is then set to auto launch Twilight Menu
2. Power on DSi

Hiya takes 20 seconds to fully boot but it has a splash screen at around .5 secs so you know it has started. Twilight Menu has no initial splash screen and so you don't know if Hiya/Twilight Menu just crashed or if they are working correctly.

Note: This might be considered a Hiya bug (I don't know when Twilight Menu gains control). It might be Hiya needs to write to the screen before initializing the autorun app.

**Comment by RocketRobz** [comment]
The system menu initializes the FAT driver, which is why it takes long, if using HiyaCFW.

**Comment by neversphere** [comment]
Is there a way to go from unlaunch directly to twilight menu and bypass hiya?

**Comment by neversphere** [comment]
I feel very very foolish now. I assumed TwilightMenu needed Hiya to
initialize something for it.
Thanks!
