### ISSUE TITLE
TWilight Menu++ Won't launch

### ISSUE THREAD

**Issue by Talondronia** [DS-Homebrew/TWiLightMenu#802]
So, I've gotten pretty far in the homebrew thing, as this is my first time ever trying to do it, I've got the Icons for the ROM Loader and the normal TWiLight Menu++ , whenever I try to launch Last-run it load then locks up, the top screen turns black while the bottom one remains completely white, and the Regular Menu application doesn't even show anything, just a permanent white screen, what did I do wrong? any help is appreciated!

Also, if I'm just being impatient, how long does it usually take for TWilight menu++ to load on a fresh install?

**Comment by RocketRobz** [comment]
What guide did you follow?

**Comment by Talondronia** [comment]
I followed dsi.cfw.guide.

**Comment by RocketRobz** [comment]
Try directly booting TWLMenu++, instead of using HiyaCFW.

**Comment by Talondronia** [comment]
Alright, I'll try that and see what happens.

**Comment by Talondronia** [comment]
So what your saying is I need to change the "NO BUTTON" thing in Unlaunch?

or is it something else? because the only thing that lets me boot is HIYA.DSI, attempting to boot directly into TL++ just gives me a "Guru Meditation Error"

**Comment by Talondronia** [comment]
actually, I seem to have gotten SOMEWHERE. I was just using the wrong file.

**Comment by Talondronia** [comment]
I think I got it, as I can now load roms, that was all I wanted to do on this, thanks!
