### ISSUE TITLE
Multiplayer dont work on most games

### ISSUE THREAD

**Issue by Ctuno** [DS-Homebrew/TWiLightMenu#804]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [x]  (No CFW) memory pit
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[10.1 -10.3]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [x]  Acekard/akMenu

### Expected behaviour

open any game and start multiplayer, then connect another console an play. 

### Actual behaviour

when open multiplayer on any game the console don't activate the wifi connection an send an error, in mario kart the console freeze when i open the multiplayer, in call of duty(any) the wifi don't start, in sonic racing wifi don't start neither, in download play from another ds works fine and whit a game cartridge works well too.

![20191030_170817](https://user-images.githubusercontent.com/57196772/67906284-b5019c00-fb39-11e9-986f-1da89e024858.jpg)
![20191030_171358](https://user-images.githubusercontent.com/57196772/67906286-b5019c00-fb39-11e9-940a-8b0a271262c5.jpg)

### Steps to reproduce

1. activate wifi in system menu
2. launch twilight menu ++ 
3. open multiplayer

**Comment by RocketRobz** [comment]
Please follow this guide: http://dsi.cfw.guide/
