### ISSUE TITLE
DS Download play work for DS games

### ISSUE THREAD

**Issue by owenmacpc** [DS-Homebrew/TWiLightMenu#805]
**Is your feature request related to a problem? Please describe.**
Please make DS download play and Wireless Play work.
Mostly when I try to do it gives me an error or it just restarts the games.

**Comment by RocketRobz** [comment]
This should be fixed in the future.
Also, this is an nds-bootstrap issue.

**Comment by owenmacpc** [comment]
How do we fix the nds-bootstrap issue?

**Comment by SleepyLark** [comment]
It's on their todo list, but not really a top priority at the moment.  If you wanted to follow the issue, here's the link to it on the nds-bootstrap GitHub
https://github.com/ahezard/nds-bootstrap/issues/553
Also just for future reference, if you have any problems with a specific game or in-game feature it should be reported to the nds-bootstrap GitHub, not this one
