### ISSUE TITLE
DSi Camera app will not launch

### ISSUE THREAD

**Issue by RyanTheInkling** [DS-Homebrew/TWiLightMenu#806]
When I launch the DSi Camera from TWiLightMenu, it gives me a message saying The System Memory has been damaged. What is causing this error? I am on version 9.5.2

**Comment by RocketRobz** [comment]
TWiLight Menu++ isn't the issue.
Report it on the Unlaunch thread at nesdev.

**Comment by RyanTheInkling** [comment]
thanks
