### ISSUE TITLE
Launching "Last-run ROM" shortcut from the DSi Home Menu results in cracking audio

### ISSUE THREAD

**Issue by Kotziauke** [DS-Homebrew/TWiLightMenu#807]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (non-XL) v1.4.5E
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch v2.0, HiyaCFW v1.32]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v10.3.0 with nds-bootstrap v0.26.1]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

The "Last-run ROM" shortcut from the DSi Home Menu (not TWiLight's Quick Menu) should boot the last-run NDS game in the same way as if it was launched from the TWiLight Menu++ file browser.

### Actual behaviour

Instead, games launched that way tend to have problems with cracking audio (this can be easily heard in _Animal Crossing: Wild World (EUR)_ after waiting ~10s on the title screen).
I understand that this issue is somehow related to the nds-boostrap, but I suspect that it might be caused by the "Last-run ROM" shortcut not initializing something correctly. That's why I decided to report it here.

### Steps to reproduce

1. Make a clean installation of the TWiLight Menu++ on the DSi using the guide on the wiki.
2. Launch TWiLight Menu++ from the DSi Home Menu.
3. Without changing any settings, navigate to _AC:WW_ ROM and boot it.
4. Wait until the game loads to its title screen.
5. Listen to the music for a while to ensure it plays without any problems.
6. Press power button to go back to the DSi Home Menu.
7. Launch TWiLight Menu++ Last-run ROM
8. Wait until the game loads to its title screen.
9. Wait for about 10 seconds to start hearing cracking sounds.

**Comment by FlameKat53** [comment]
when i use last run rom, i just get a guru meditation error, but it might be due to using some things that mess with the nds-bootstrap.ini like the GBARunner2 forwarder i made

**Comment by NightYoshi370** [comment]
Can anyone reproduce this on the latest nightly?

**Comment by SleepyLark** [comment]
The newer versions have removed the option to launch the "Last-run ROM" from the Select Menu, so this issue can't be reproduced and loading from the DS Classic Menu saw no issues.  However, I did notice audio issues and other problems when loading a Slot-1 game [#1008] (the option that replaced "Last-run ROM") so maybe it's related?

**Comment by NightYoshi370** [comment]
Apparently it has to do with DS mode stuff. Since the other issue was closed for that, I'll assume it's the same here unless anyone objects
