### ISSUE TITLE
Pictochat gives a error when launched from TWiLight Menu

### ISSUE THREAD

**Issue by RyanTheInkling** [DS-Homebrew/TWiLightMenu#809]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [x]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [x]  Unlaunch+HiyaCFW _[Unlaunch v2.0 and HiyaCFW v1.3.2]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v10.3.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Pictochat should launch and you can choose a chat room.

### Actual behaviour

Pictochat gives out the error, "Communication error. The Nintendo DS will now shut down."

### Steps to reproduce

1. Get Pictochat installed.
2. Select it from TWiLight Menu.
3. There you go!

**Comment by RocketRobz** [comment]
You need to fix the title ID to `HNEA` for it to work.
To do that, open the .nds file in a hex editor, and write `HNEA` at offset C.
