### ISSUE TITLE
Closing the lid while playing Super Mario 64 causes black screen when reopened.

### ISSUE THREAD

**Issue by gir489** [DS-Homebrew/TWiLightMenu#811]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [X]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release v11.0.0
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

User should open lid and the screen should turn back on.

### Actual behaviour

Both screens are black, but the sound continues to play.

### Steps to reproduce

1. Launch Super Mario 64 DS from TWiLightMenu
2. Launch a save game.
3. Play for at least a few minutes.
4. Close the lid.
5. Leave the console closed for at least a minute.
6. Reopen the console.

It appears to only happen when the 3DS enters [sleep mode](https://en-americas-support.nintendo.com/app/answers/detail/a_id/1026/~/how-to-place-the-system-into-sleep-mode) although I was told this is a known issue when running DS games on the 3DS, I am not sure how accurate that is, I figured I would file a bug anyway...

**Comment by NightYoshi370** [comment]
Switch from TWL CPU speeds to NTR CPU speeds

**Comment by gir489** [comment]
> Switch from TWL CPU speeds to NTR CPU speeds
I would've never thought of that... When should I use TWL? I set it because I thought more clock speed would be better like when I used to have a CFW'd PSP.

**Comment by gir489** [comment]
I set it to NTR but the same thing happens. Black screen, sound still plays...

**Comment by gir489** [comment]
It appears the CPU clock speed has to be set to 67 Mhrz and the Run in mode has to be set to DS not DSi for it to work. Setting it to DSi or changing the clock speed causes this bug to occur.
