### ISSUE TITLE
touch screen does not work in twilight

### ISSUE THREAD

**Issue by champi12** [DS-Homebrew/TWiLightMenu#812]
The touch screen does not respond in the Twilight menu, it works perfectly in the original menu and in the games, but in the twilight it does not respond, it worked perfectly in version 8.3.0 and earlier, but since that version until now it is not so I'm in a Nintendo DSI

**Comment by RocketRobz** [comment]
Are you using HiyaCFW?

**Comment by champi12** [comment]
No, previously it worked for me but now I just stop working if I reinstall Verification 8.3.0 the touch screen responds without inconvenience

**Comment by RocketRobz** [comment]
Follow [this](https://github.com/DS-Homebrew/TWiLightMenu/wiki/How-to-update-TWiLight-Menu) guide, in case if you missed any files.

**Comment by champi12** [comment]
thank you friend apparently I missed 2 files that were not copied to the SD card, now it works perfectly

**Comment by RocketRobz** [comment]
You're welcome!
