### ISSUE TITLE
TWLMenu++ updater crashes console if wifi is disabled

### ISSUE THREAD

**Issue by bkimmett** [DS-Homebrew/TWiLightMenu#813]
Console: New 3DS
CFW: Luma3DS
TWLMenu++ version: Release (updater version 3.1.2)
Theme: DSi Menu

### Expected behaviour

When WiFi is disabled, the TWLMenu updater should display an error message and close, or ask if it can enable WiFi and then do so.

### Actual behaviour

The 3DS crashes and presents a stack dump.

### To reproduce

1. Turn off wifi.
2. Launch TWLMenu++ Updater.
3. The updater will crash when it tries to access the internet, during its startup sequence.

**Comment by RocketRobz** [comment]
Please update the updater. The bug has been fixed.

**Comment by bkimmett** [comment]
TY!
