### ISSUE TITLE
TWiLight Menu on akaio won't boot

### ISSUE THREAD

**Issue by Nikavo** [DS-Homebrew/TWiLightMenu#815]
### Your console

Tell us which console do you have:

- [x]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[v11.0.0: CycloDS iEvolution support!]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [x]  Acekard/akMenu

### Expected behaviour

It should Launch the Twilight Menu

### Actual behaviour

on akaio, i select the boot.nds , and the console freezes

### Steps to reproduce

1. install the twilight menu on akaio (using the acekard 2i card)
2. try launching it 
3. fail.

**Comment by RocketRobz** [comment]
Probably failed because of the arm9 binary placement in memory.
Try a `boot.nds` from a previous version.

**Comment by NightYoshi370** [comment]
This issue was made when a problematic flashcard code got released. This has since been reverted so I'd assume it's fixed. If it isn't, I'll reopen the issue

**Comment by Nikavo** [comment]
It's working normally now, on the akaio flashcard

Em 30 de jan de 2020 19:24, "NightScript" <notifications@github.com>
escreveu:
