### ISSUE TITLE
TWL ARM9 speed doesn't seem to be different from NTR

### ISSUE THREAD

**Issue by FulguroBoy** [DS-Homebrew/TWiLightMenu#817]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _[11.0.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Activating TWL speed for ARM9 CPU should speed up some games (i.e Pokémon Mystery Dungeon: Explorers of Sky)

### Actual behaviour

There's no visible difference in-game (loading times are still the same, clearly visible in PMD)

### Steps to reproduce

1. Change "ARM9 CPU Speed" parameter to "133 MHz (TWL)"
2. Make sure the game you want to boot is booted with TWL speed
3. Boot the game and compare to NTR speed

**Comment by RocketRobz** [comment]
TWL speed does not affect load times.
The loading is handled on arm7.
