### ISSUE TITLE
2nd time TWL doesn't read my games .sav file

### ISSUE THREAD

**Issue by KocoloX** [DS-Homebrew/TWiLightMenu#818]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[11.0.0]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [X]  Acekard/akMenu

### Expected behavior

Games should load my save file.

### Actual behavior

This is the 2nd time I'm having this issue. For some reason, TWL is not reading my save on any game I already completed.

This time, I'm experiencing this issue after I turned off my O3DS with a game playing on TWL (without closing application first, don't know if it's related).

After checking my SD, noticed 3 things:
1) No .sav file where on my  E:\Roms\saves folder (my computer assigns the E: directory to my 3DS SD card).
2) Noticed .bin files on the E:\_nds\nds-bootstrap\fatTable and E:\_nds\nds-bootstrap\patchOffsetCache with the same name and size supposed for the .sav file (512KB).
2) The files on my E:\Roms\saves folder are the same files in my E:\_nds\TWiLightMenu (below to screenshots)
![TWL](https://user-images.githubusercontent.com/57809960/69014784-5410fb00-0964-11ea-8b57-a8c6b7a2a89b.png)

### Steps to reproduce

1. Turn on O3DS
2. Open TWL
3. Start game with a save file
4. turn off O3DS with game running through the power buttong (screen will turn black, after 2-3 second turn off message will appear, after 2-3 seconds light console light will turn off).
5. Turn on O3DS again
6. Open TWL again
7. Start game with a save file (supposedly) and see if your records loads.

**Comment by RocketRobz** [comment]
Try deleting the files that aren't .sav, in `saves`.

**Comment by KocoloX** [comment]
That's the thing, I don't have any .sav file in my saves folder. It's like the folder erased it all.

Should i delete the folders too? just in case.

**Comment by RocketRobz** [comment]
No.

Sounds like your SD card is having issues. Please check it for errors.

**Comment by KocoloX** [comment]
Ran error check but decided to do a clean start.

Uninstalled TWL from SD. Will backup all files from SD, format and put them all back. Re-install TWL and will keep track of everything.

Any recommendations to keep saves backed? Also, to fully uninstall TWL should I manually delete _nds and _gba folders from my SD?

**Comment by NightYoshi370** [comment]
I'm late, but do manually delete _nds, uninstall the CIAs and do everything over

**Comment by KocoloX** [comment]
Thanks for the support @NightYoshi370 

Update on this: Manually did everything over back in November. So far no issues but will keep you posted if something happens.

I'm closing this since everything's working right now.
