### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by Proyecto-N** [DS-Homebrew/TWiLightMenu#819]
Is it possible (as they just did with Nintendo DS Browser) to run the Gericom DS YouTube app? I tried it once, but it never connected to the internet (I tried the Rocket Video Player, but it was very confusing how to create the .rvid file).

**Comment by RocketRobz** [comment]
You need a WEP or Open network to run the app.

**Comment by Proyecto-N** [comment]
Do you know if that is currently possible?

**Comment by RocketRobz** [comment]
Yes. Just connect to one in the WiFi settings.

**Comment by Proyecto-N** [comment]
It's my Old 3DS, apart from the closure of Nintendo WFC servers
