### ISSUE TITLE
Latest updater crashes

### ISSUE THREAD

**Issue by Azzabada** [DS-Homebrew/TWiLightMenu#820]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ x ]  Old 3DS/2DS (XL)
- [ x ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [ x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x ]  Release _[ second to latest version I think, latest updater]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ x ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

Load into menu of updater.

### Actual behaviour

Crashes as soon as I get passed homebrew's load screen

### Steps to reproduce

1. Install latest updater
2. Open updater app (doesn't matter if wifi is on or off)
3. Let Homebrew load into the updater then crash happens.

Crash dump (ignore song, this was the only way I could share it because I'm on a phone) https://drive.google.com/folderview?id=1cHByUhQcIO8lrWIzm0KAmRqs1pkt6vl0

**Comment by semecan** [comment]
You really need to give more information on your system/cfw.
Just had a friend install Twilight Menu Updater on his new 3ds with luma3ds and use it to install twilight menu. After installing twilight menu, he needed to restart his system for it to show up, but other than that everything worked fine.

**Comment by RocketRobz** [comment]
Re-install the latest updater.
Also, the updater has it's own repo. Please post another issue there, when you have one.
