### ISSUE TITLE
O3DS wont boot TWiLightMenu++

### ISSUE THREAD

**Issue by intflorian** [DS-Homebrew/TWiLightMenu#821]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [x]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]   Release _[please specify version]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [ ]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

TWiLightMenu++ should start

### Actual behaviour

Im getting the "An error has occured. Hold down the Power Button to turn off the power, then turn it on and try again."
I tried both Install Method ( Manual & with the Updater), both with the same result.

### Steps to reproduce

1.  Start TWiLightMenu++
![hqdefault 1](https://user-images.githubusercontent.com/57923294/69265978-8cb20e00-0bca-11ea-8e00-523c39ab972a.jpg)

**Comment by RocketRobz** [comment]
Does it happen with other software?

**Comment by intflorian** [comment]
No. I updated my O3DS from A9LH to B9S. I also updated my Luma from 6.x to the newest v10.0.1.

**Comment by RocketRobz** [comment]
Try re-installing TWiLight Menu++.

**Comment by intflorian** [comment]
I tried re-installing 3 times, everytime with the same result. :/

**Comment by RocketRobz** [comment]
Try booting the console without an SD card, and launch the app.

**Comment by intflorian** [comment]
Maybe dumb question: How do I install .cias on the SYSNAND. I mean my SYSNAND is also Luma but how do I get something like FBI installed in the first place without a SD Card?

**Comment by RocketRobz** [comment]
You don't need it for this test.

**Comment by intflorian** [comment]
TWiLightMenu++ is not installed on the SYSNAND

**Comment by RocketRobz** [comment]
Hmm, so you never installed the latest CIAs then.

**Comment by intflorian** [comment]
I installed the latest CIAs on th EMUNAND. I never used or bootes the SYSNAND

**Comment by RocketRobz** [comment]
Please move EmuNAND to SysNAND then.
https://3ds.hacks.guide/move-emunand

**Comment by intflorian** [comment]
That worked! Thank you very much.
