### ISSUE TITLE
Suggestion : Night mode (Blue Light Filter)

### ISSUE THREAD

**Issue by The1stMaster** [DS-Homebrew/TWiLightMenu#823]
Is it possible to implement night mode where the screen becomes yellow with different settings like : low, medium, high, or different temperatures? Rosalina menu which has this feature doesn't work in DS games. I want to thank the developers for their amazing work!

**Comment by RocketRobz** [comment]
That's been tried before, but it only works correctly on the graphics rendered by gl2d.
