### ISSUE TITLE
Right aligned game settings

### ISSUE THREAD

**Issue by eku** [DS-Homebrew/TWiLightMenu#824]
In per game settings the actual values should be right aligned. Currently they are left or right aligned  or even centered.  Doesn't look good at the moment.

**Comment by NightYoshi370** [comment]
I sent this to Robz's DM but I'm posting it here in case anyone else wants to try to implement this:
```cpp
void printSmallRightAlign(bool top, int x, int y, const char *message)
{
    getTextQueue(top).emplace_back(false, x - smallFont.calcWidth(message), y, message);
}
```

This is a function made for right alignment

**Comment by RocketRobz** [comment]
Fixed since some versions ago.
