### ISSUE TITLE
TM++ doesn't load on DSi running CFW

### ISSUE THREAD

**Issue by Fackey** [DS-Homebrew/TWiLightMenu#825]
It just shows a white screen.

**Comment by RocketRobz** [comment]
I don't think anything can be done.
Have Unlaunch directly boot TWLMenu++ instead.

**Comment by Fackey** [comment]
That's what I have it set up to do.

**Comment by RocketRobz** [comment]
Try deleting `settings.ini` at `sd:/_nds/TWiLightMenu/` then.

**Comment by Fackey** [comment]
No dice.

**Comment by Fackey** [comment]
I made a mistake, I did not have it set to launch TM++ from Unlaunch.

**Comment by NightYoshi370** [comment]
Does it work now? If so, please close the issue
