### ISSUE TITLE
Problem with Mario Party DS

### ISSUE THREAD

**Issue by TTomTwo** [DS-Homebrew/TWiLightMenu#827]
Hi. I'm new to the 3DS pirating thing.
I just installed TWLight++ and when I want to play MPDS in download play the game crashes showing me that there was an error and I need to get back to the main menu when it never does. I'm using NEW 3DS XL and I want to play with my old DS Lite and then the problem occurs. Is there any possible reason for this? I used several MPDS roms and there was always the same effect.

**Comment by RocketRobz** [comment]
Download Play doesn't work un MPDS, because it uses cloneboot.
