### ISSUE TITLE
Date does not honour configured locale

### ISSUE THREAD

**Issue by eku** [DS-Homebrew/TWiLightMenu#828]
**Console Configuration:** Old 3DS/2DS (XL) with Luma3DS
**TWiLight Menu++ version:** Release v11.1.0
**TWiLight Menu++ theme:** 3DS HOME Menu

### Expected behavior

In the upper right corner the actual date and time is displayed honoring the configured locale.

### Actual behavior

The date is always displayed as MM/DD.

### Steps to reproduce

1. Configure any language different from English
2. Check date at upper right corner

**Comment by NightYoshi370** [comment]
This isn't a bug. Languages don't have a specified date format

**Comment by Epicpkmn11** [comment]
I think it'd be worth implementing DD/MM for places that use that, it wouldn't be very hard, it just might need to be separate from language

**Comment by eku** [comment]
@NightYoshi370 My formulation regarding "language" was perhaps clumsy. What I meant, in fact: 
In the 3DS settings you can select a region/country and the formatting of time and date should be based on this setting.
