### ISSUE TITLE
No [Screen Aspect Ratio] seting in the [TWLMenu++ settings]

### ISSUE THREAD

**Issue by youyinnn** [DS-Homebrew/TWiLightMenu#829]
I followed all the steps, and can't find the Screen Aspect Ratio in TWLMenu++ settings

TWiLight Menu++: v11.1.0
nds-bootstrap: v0.27.1

plz help

**Comment by SleepyLark** [comment]
Wdym?  You do know that there's multiple pages in the settings menu and that you need to use the L and R button in order to switch the page.  Also widescreen is only for the 3DS

**Comment by NightYoshi370** [comment]
This isn't a bug but rather a support question. Please ask it on our discord server instead

**Comment by youyinnn** [comment]
@SleepyLark I use 2DS, and I know I can switch page, I mean that no "Screen Aspect Ratio" in the page "Game and Apps settings"

![image](https://user-images.githubusercontent.com/23525754/70294945-31b22500-1820-11ea-8801-aebe49e08b17.png)

![image](https://user-images.githubusercontent.com/23525754/70294952-370f6f80-1820-11ea-8035-5343cd57fe93.png)

**Comment by RocketRobz** [comment]
Delete `settings.ini` in `sd:/_nds/TWiLightMenu/`, then select the correct console after launching TWLMenu++.

**Comment by youyinnn** [comment]
@RocketRobz problem fixed, seems like I chose the DS console at the first time I launching TWLMenu++
