### ISSUE TITLE
[Feature Request] Game handbook support

### ISSUE THREAD

**Issue by Nemris** [DS-Homebrew/TWiLightMenu#831]
**Is your feature request related to a problem? Please describe.**

Few physical game handbooks exist, while they seem to be available in .pdf format. However, .pdf requires a separate reader.

**Describe the solution you'd like**

A way to read game handbooks baked into TWiLightMenu++, to avoid needing a separate device for that.

**Additional context**

The .pdf format might be difficult to implement. It _might_ be easier to rebuild all handbooks into the same format used by TWLMenu's own handbook, and support that instead.

**Comment by SleepyLark** [comment]
iirc there are homebrew apps that can read pdf files, however there is a memory restriction so the file can't be super huge.  The only problem is that there's wouldn't really a way to be able to view the manual in-game which kind of defeats the purpose of having a manual if you can't look at it when you're playing.

**Comment by DMSalesman** [comment]
Indeed. It would be interesting if game freezing and manual loading could be delegated to a key combo, but I don't know if a (3)DS has enough memory to juggle both the game and the manual.

**Comment by NightYoshi370** [comment]
https://github.com/DS-Homebrew/twlmenu-extras/tree/master/_nds/TWiLightMenu/manual
I rehosted this a while back. Maybe we could finally put it to use.

**Comment by clach04** [comment]
> https://github.com/DS-Homebrew/twlmenu-extras/tree/master/_nds/TWiLightMenu/manual I rehosted this a while back. Maybe we could finally put it to use.

Current location https://github.com/DS-Homebrew/twlmenu-extras/tree/master/_nds/TWiLightMenu/extras/manuals
