### ISSUE TITLE
Wi-Fi

### ISSUE THREAD

**Issue by Proyecto-N** [DS-Homebrew/TWiLightMenu#833]
Is the Nintendo DS internet connection currently possible on my old 3DS? I want to receive mystery gift, play Mario Kart DS Online, etc., I don't know how, and aren't the servers supposed closed?

**Comment by RocketRobz** [comment]
You can use Wiimmfi.

Also, please ask in the Discord server(s) for future support.
The issue tracker isn't the place for support.
