### ISSUE TITLE
Widescreen not working 

### ISSUE THREAD

**Issue by SwiftSkyVA** [DS-Homebrew/TWiLightMenu#834]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [x]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
- [ ]  (No CFW) Unlaunch only _[please specify version]_
- [ ]  Unlaunch+HiyaCFW _[please specify versions of both]_

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### TWiLight Menu++ version

Tell us which versions you are using:

- [x]  Release _11.1.0_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [x]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

I wanted to play Pokemon Platinum on my 3DS with widescreen. I followed every step on [this](https://github.com/DS-Homebrew/TWiLightMenu/wiki/Playing-in-Widescreen) page,
### Actual behaviour

Widescreen does not work at all. not even a stretched image, just still 4:3.
### Steps to reproduce

[every step on this page](https://github.com/DS-Homebrew/TWiLightMenu/wiki/Playing-in-Widescreen)

**Comment by RocketRobz** [comment]
Is the ROM modified in any way?

**Comment by SwiftSkyVA** [comment]
yeah, i'm using the Renegade Platinum hack. does that affect the widescreen?

**Comment by RocketRobz** [comment]
Yes. ROM hacks don't work with widescreen.

**Comment by SwiftSkyVA** [comment]
I see, thank you.
