### ISSUE TITLE
No touchscreen or sound

### ISSUE THREAD

**Issue by TheOct0** [DS-Homebrew/TWiLightMenu#836]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [X]  DSi (XL)
- [ ]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [X]  Unlaunch+HiyaCFW _[unlaunch v1.9, HiyaCFW is the latest, I'd say?]_ 

### TWiLight Menu++ version

Tell us which versions you are using:

- [X]  Release _[v8.2.3]_
- [ ]  Nightly _[insert here commit hash]_

### TWiLight Menu++ theme

Tell us which theme you are using:

- [X]  DSi Menu
- [ ]  3DS HOME Menu
- [ ]  SEGA Saturn
- [ ]  R4
- [ ]  Acekard/akMenu

### Expected behaviour

The touchscreen should be able to be used for selecting games, browsing folders, TWiLight menu settings, etc. The same goes for any game launched from it.
Also, if I recall correctly, the menu should have sound, and it currently doesn't. Also, games launched through the menu don't have sound either.

### Actual behaviour

Well, touchscreen isn't working, and there isn't any sound either (both in-game and in the menu)

### Steps to reproduce

1. Launch the console
2. Try to use the menu's touchscreen functionality
3. Do the same in-game

### Additional information

When using the original DSi menu, the touchscreen is working just fine, and sound plays when I go in-game.
Also, everything was working just fine yesterday, before I decided to update the menu, so this has to be related to an update.

**Comment by SleepyLark** [comment]
You say you're using the latest update, but you wrote down that the version you're using is v8.2.3 when the latest version is v11.0.0.  Try updating to v11.0.0 and if that works

**Comment by TheOct0** [comment]
Well, I must have messed up some part of the update process, which explains the weird behaviour. I'll try and fix it all up, and report back. Thanks!

**Comment by TheOct0** [comment]
So, as it turns out, updating from v8.2.3 to v11.1.0 just results in an unstable and weird menu. I had to completely reinstall from scratch (even though I was following the update procedure every time). Thanks for your help!
