### ISSUE TITLE
¿Real time save on nds games with TWiLightMenu?

### ISSUE THREAD

**Issue by balderofmidgard** [DS-Homebrew/TWiLightMenu#838]
**Is your feature request related to a problem? Please describe.**
I would like to know if there's a way to save in real time on nds games with TWiLightMenu
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by NightYoshi370** [comment]
There is no way at the moment. Also, this isn't related to TWiLightMenu++ but rather nds-bootstrap.

**Comment by NightYoshi370** [comment]
Also, if you're going to be asking questions, please use our GBATemp thread or our Discord Server.
This place is for issues/suggestions

**Comment by McFly75** [comment]
It seem that there are a dump ram section in the Twilight Menu (Left+Down+Select), so maybe it is possible for the developer to make that into a Save State/Real Time Save function?

**Comment by Epicpkmn11** [comment]
It should be possible, this isn't the proper issue for it though as this would be on nds-bootstrap's side as NightScript said, see DS-Homebrew/nds-bootstrap#143.
