### ISSUE TITLE
No abre los juegos

### ISSUE THREAD

**Issue by fcffffffffff** [DS-Homebrew/TWiLightMenu#840]
tengo una tarjeta sd y cundo intento abrir los juegos no se abren y queda la pantalla en blanco porfavor ayuda

**Comment by RocketRobz** [comment]
English, please.

**Comment by RocketRobz** [comment]
Make sure the games are running in DS mode, and that no cheats are enabled.

**Comment by Ultraman360** [comment]
@fcffffffffff Re-install and put on your microSD card fresh archives.(Re-instala y pon en la SD nuevos archivos del Twilight tal vez funciona asi PD:Soy latino)

**Comment by NightYoshi370** [comment]
Honestly, this is missing too much information and it looks more like a support question. Please use the Discord or the GBAtemp thread

Closing
