### ISSUE TITLE
Black and White screens

### ISSUE THREAD

**Issue by pablomg29** [DS-Homebrew/TWiLightMenu#842]
Today I was trying two games that are Transformers Autobots and Transformers Decepticons, when I started both of this games shows a black screen on the top and a white screen in the tactile screen I cant play neither of this games, there are no cheats activated and the TWLmenu++ is in DS mode.

**Comment by pablomg29** [comment]
Sorry for being dumb but i dont know how to put a lable on this issue

**Comment by RocketRobz** [comment]
What about turning off heap shrink?

**Comment by pablomg29** [comment]
how can i turn off the heap shrink???

**Comment by RocketRobz** [comment]
You do it in the same menu where you press X to see cheats.

**Comment by pablomg29** [comment]
thanks, it worked, another question how can i get the Dsi binaries??

**Comment by RocketRobz** [comment]
You just dump the ROM from an actual cartridge.
The dump will contain the binaries.

**Comment by pablomg29** [comment]
thanks
