### ISSUE TITLE
Widescreen Not Working

### ISSUE THREAD

**Issue by DontCallMeAqua** [DS-Homebrew/TWiLightMenu#844]
I did everything here: https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/

Widescreen isn't working at all on my New 3DS XL

**Comment by NightYoshi370** [comment]
This does not contain any information other than your console.

How's your SD card file structure?
What's the MD5 hash of your file?
What luma version are you using?
What are your settings?

Since this seems to be support related, please ask on our Discord Server or our GBATemp thread.
Closing
