### ISSUE TITLE
Unable to hide custom folders while on the AKMenu theme

### ISSUE THREAD

**Issue by MatLegat** [DS-Homebrew/TWiLightMenu#845]
**Your console configuration:** DSi XL 1.4.5U w/ HiyaCFW + Unlaunch 
**TWiLight Menu++ Version:** v11.1.0
**TWiLight Menu++ Theme:** AKMenu

### Expected behaviour

All folders and files hidden by the user should not be displayed on the list.
User should be able to hide the folder when on the file list itself, just like when in other themes.

### Actual behaviour

Some folders and files hidden by the user are being displayed on the file list when using the AKMenu theme.
Also there is no option for the user to hide a folder by pressing X then Y on AKMenu (like in the DSi theme), neither by using the properties on the START menu.

### Steps to reproduce

1. Hide a file/folder using Windows Explorer (right click ->properties -> hidden -> ok)
2. Hide a folder using anoder TwilightMenu theme (e.g. DSi theme) by pressing X then Y
3. Change to AKMenu theme
4. Observe the "Hidden" folders being displayed anyway on the file list

**Comment by NightYoshi370** [comment]
It isn't a bug: it's an unimplemented feature.
I'll try to fix it but no guarantees

**Comment by chyyran** [comment]
@NightYoshi370 see here: https://github.com/DS-Homebrew/TWiLightMenu/blob/master/romsel_aktheme/arm9/source/windows/mainlist.cpp#L328
