### ISSUE TITLE
Add option to hide GBA ROMs in the settings

### ISSUE THREAD

**Issue by SleepyLark** [DS-Homebrew/TWiLightMenu#849]
**Is your feature request related to a problem? Please describe.**
Since it's now possible to launch GBA games through TWiLight Menu, it makes sense to add the option to hide them in the "Filetype Settings" since it's possible to hide all the other ROM types.

**Describe the solution you'd like**
Add another option in the "Filetype Settings" to hide/show GBA ROMs

**Additional context**
Personally, I've never used this option before for other ROMs, but I figure it made sense to keep things uniformed by adding the option for GBA also.   Of course it's already possible to hide them individually  by pressing X

**Comment by blueingsh** [comment]
this old

**Comment by Epicpkmn11** [comment]
> this old

It's still not added yet, though, is it? Its not in v17.0.0 and I don't see it in the latest commits...

**Comment by RocketRobz** [comment]
It

**Comment by RocketRobz** [comment]
I remember seeing it for some weird reason, so that's why I closed it.
