### ISSUE TITLE
NDS games in a better quality

### ISSUE THREAD

**Issue by CaioMel360** [DS-Homebrew/TWiLightMenu#851]
Hi, I always wondered why when I put a DS game on my 3ds, it didn't look good, I've heard reports that the 3DS had a function that improved the quality of the games, but
I think it's a lie, can this be possible on the Twilight menu? And if possible, is it only in New 3ds? (I even have a nice name for this function, "High Resolution 3D Rendering")

**Comment by RocketRobz** [comment]
The rendering resolution can't be improved, but scale filters can be applied.
https://gbatemp.net/threads/twpatcher-ds-i-mode-screen-filters-and-patches.542694/

**Comment by NightYoshi370** [comment]
This has nothing to do with TWiLight but rather TWL FIRM.
You'd need to mod TWL_FIRM in order to apply those scale filters.

Please redirect any support/questions to either the Discord Server or the GBATemp thread RocketRobz linked
