### ISSUE TITLE
Background graphic flickering in Mega Man Zero Collection

### ISSUE THREAD

**Issue by ArbysSauce** [DS-Homebrew/TWiLightMenu#852]
**Your console configuration:**  DSi XL (HiyaCFW + Unlaunch)
**TWiLight Menu++ Version:** v11.2.0
**TWiLight Menu++ Theme:** 3DS

### Expected behaviour
Graphics in the background of every stage should appear as normal

### Actual behaviour
Background graphics will occasionally flicker in certain spots

### Steps to reproduce

1. Launch Mega Man Zero Collection through TwiLightMenu++
2. Go to Heat Genblem's stage after completing the intro (only stage I tested)
3. Graphic flickering will begin to occur

**Comment by NightYoshi370** [comment]
Not related to TWiLight Menu++
Please go to the nds-bootstrap repository
