### ISSUE TITLE
Dsi in 3ds loading bug Twilight menu

### ISSUE THREAD

**Issue by sachipo** [DS-Homebrew/TWiLightMenu#855]
I have dsi with twilight menu it was working good intill  I messed around with setting and now stuck on a 3ds menu but it’s constantly loading with this on the button screen 

If this takes awhile close and open the console lid

Now loading....

Location 
Sad card

And I can’t get out of it I held power button and a to see if there’s setting that  will fix it but nope everytime I open twilight it does the intro then I’m stuck in that loading screen

**Comment by RocketRobz** [comment]
Delete `settings.ini` at `sd:/_nds/TWiLightMenu/`.

**Comment by sachipo** [comment]
Explain more

**Comment by FlameKat53** [comment]
You just need to delete the file :P

**Comment by sachipo** [comment]
> You just need to delete the file :P

Do I need to use a computer ?

**Comment by FlameKat53** [comment]
You can use anything that can access your SD Card, eg computer or Android phone

**Comment by sachipo** [comment]
Ok thank u

**Comment by NightYoshi370** [comment]
This is more of a support thing rather than an issue, which would be better on our Discord Server.
Closed
