### ISSUE TITLE
Question: JenesisDS Save States

### ISSUE THREAD

**Issue by DJManas** [DS-Homebrew/TWiLightMenu#856]
**Your console configuration:** Nintendo DSi 1.4.5, Unlaunch v 2.0 and SD Card 
**TWiLight Menu++ Version:** 11.2.0, but did not work in 11.1.0 either.  
**TWiLight Menu++ Theme:** AKMenu 

### Expected behaviour

Save state should be saved to SD card.

### Actual behaviour

Does not save. I know it is JenesisDS' problem but want to ask what should I do to use saved states. When I launch SMS game, save and restore, without reseting, it works. When I reset, it does not. It seems like it creates „RAMdisk“ and does not transfer saved state back to SD card. I had tried to create folder saves in my SMS roms directory, but doesn’t work.

JenesisDS version 0.7.4 (tried to redownload, still the same).

Thank you.

### Steps to reproduce

1. Launch genesis / SMS game,
2. Save state,
3. Reset,
4. Launch game again, saved state could not be loaded

**Comment by RocketRobz** [comment]
The ROM runs inside a RAM disk, so there is no way to transfer the saves back to the SD card.
Also, SMS games run in S8DS, so saves should be working there, afaik.

**Comment by DJManas** [comment]
Thanks for pointing me to correct project. I had searched the net and everytime it was written that jEnesisDS supports save states, but that was all...

Is it possible to switch S8DS for jEnesisDS in TWL config as temporary workaround?

**Comment by RocketRobz** [comment]
What's wrong with S8DS?

**Comment by DJManas** [comment]
S8DS works with GG roms.
![image](https://user-images.githubusercontent.com/2048276/71742280-810c6500-2e61-11ea-83b7-315ce18871b3.png)

But when I launch SMS rom through TWL, it automatically launches jEnesisDS. I had tried to copy S8DS.nds to jEnesisDS.nds, but got black screen, when launched any SMS rom.

**Comment by RocketRobz** [comment]
What theme are you using?

**Comment by RocketRobz** [comment]
What's the file extension for your SMS ROMs?
They boot in S8DS for me.

**Comment by DJManas** [comment]
.gen. Tried to move it to different directory, where GG roms are stored, but still launches jenesis

**Comment by RocketRobz** [comment]
That's why jEnesisDS is being loaded then.
Please change `.gen` to `.sms`.

**Comment by DJManas** [comment]
Renamed `.gen` to `.sms`, every rom, I had launched, launched S8DS, but saying that rom file is too big. I will go and search how to convert `.gen` to `.sms` in a correct manner. But i guess I am on right track. Thanks for pushing me to correct direction.

Thank you.
