### ISSUE TITLE
Toggle to forcefully emulate the Slot-2 expansion pak on any ROM

### ISSUE THREAD

**Issue by tomrow** [DS-Homebrew/TWiLightMenu#858]
Is it possible to configure the software to boot a ROM with support for the Slot2 Memory Expansion Pak manually enabled? This would be a big help for homebrew games that support it.

**Comment by RocketRobz** [comment]
The functions would have to be searched in the homebrew, and may vary, depending on some homebrew.
Also, this would be an nds-bootstrap feature.

**Comment by tomrow** [comment]
My apologies.
