### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by CatsLover2006** [DS-Homebrew/TWiLightMenu#859]
**Edit:** Sorry, forgot to add title.

I find it annoying to have to enable widescreen, and then enable _each individual code_ for the games.
So, I was wondering if it would be possible to make widescreen an option for each game, or enable all widescreen codes at once.
**NOTE:** I have already made code for _rungame_ to load games with widescreen per-game. The attached files go in rungame's arm9/source directory, and will allow you to put a _WIDESCREEN_ value into the config to enable/disable widescreen per game.

Note: They are all renamed [original filename].txt in the file browser. Sadly, you can't upload .cpp and .h files directly.
[main.cpp](https://github.com/DS-Homebrew/TWiLightMenu/files/4033167/main.cpp.txt)
[perGameSettings.cpp](https://github.com/DS-Homebrew/TWiLightMenu/files/4033164/perGameSettings.cpp.txt)
[perGameSettings.h](https://github.com/DS-Homebrew/TWiLightMenu/files/4033165/perGameSettings.h.txt)

**Comment by FlameKat53** [comment]
you don't have to manually enable the widescreen cheat though, theres a folder called _nds/TWiLightMenu/widescreen/

**Comment by CatsLover2006** [comment]
What about the games that don't have cheats?

**Comment by FlameKat53** [comment]
if a game doesn't have a widescreen file in the widescreen/ folder, it won't launch in widescreen

**Comment by RocketRobz** [comment]
Widescreen cheats will have to be made.
If the game has 3D graphics, it can most likely work with widescreen.
If the game has 2D graphics, chances of it working with widescreen, are low.

**Comment by RocketRobz** [comment]
Also, you just need `Widescreen.cxi` in `sd:/_nds/TWiLightMenu/TwlBg/`.
Nothing TwlBg-related should be in `sd:/luma/sysmodules/`.

**Comment by CatsLover2006** [comment]
`Widescreen.cxi` was always there. TwlBg, if I had it, it would just be the deblur patch, but it isn’t there.
We can just delete the files in the `widescreen` folder to disable widescreen for that game, right? If so, I’ll just rename the files for the ones I don’t want in widescreen.

**Comment by CatsLover2006** [comment]
Also know that I use the nightlies. The nds_bootstraps, to my testing, are interchangeable.
