### ISSUE TITLE
Games Freezing

### ISSUE THREAD

**Issue by MoozOfDoomz** [DS-Homebrew/TWiLightMenu#860]
At certain points in some games, it will just freeze up and I will have to reset the dsi. Is there anything i'm, doing wrong? 
Console: DSI
Entrypoint: Sd card slot

**Comment by RocketRobz** [comment]
Please bring this over to the Discord server, as the issue tracker isn't the place for support.

**Comment by MoozOfDoomz** [comment]
Alright, sounds good.
