### ISSUE TITLE
Select menu: Open Manual icon is wrong

### ISSUE THREAD

**Issue by gingerbeardman** [DS-Homebrew/TWiLightMenu#863]
**Your console configuration:** DSi XL with Unlaunch 2.0, HiyaCFW 1.3.2
**TWiLight Menu++ Version:** v11.2.0: TWL Christmas release
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

Open Manual should have small icon of its own.

### Actual behaviour

Open Manual icon is one from a game I have.

### Steps to reproduce

1. Use latest TWLM

### Photos

![SELECT menu](https://i.imgur.com/O1LP4mD.jpg)

![Game list](https://i.imgur.com/8M3RDof.jpg)

**Comment by RocketRobz** [comment]
That didn't happen for me, last time I tried to fix it.

**Comment by gingerbeardman** [comment]
Would it help if I zipped up my config?

**Comment by NightYoshi370** [comment]
Well, this issue isn't necessarily *fixed* but it is now invalid since we don't use the SELECT Menu anymore.
Closing

**Comment by gingerbeardman** [comment]
Thanks for the heads-up!

**Comment by gingerbeardman** [comment]
https://github.com/DS-Homebrew/TWiLightMenu/tree/v12.1.0

- the SELECT menu returns?

@NightYoshi370

**Comment by NightYoshi370** [comment]
Seems like it, but could you reproduce the issue?

**Comment by gingerbeardman** [comment]
I'm yet to try. Will do so ASAP.
