### ISSUE TITLE
Why can’t I put normal cheats with widescreen?

### ISSUE THREAD

**Issue by CatsLover2006** [DS-Homebrew/TWiLightMenu#864]
**Your console configuration:**   New 3DS (XL) with Luma3DS 10.0.1
**TWiLight Menu++ Version:**  11.2.0
**TWiLight Menu++ Theme:**  DSi

### Expected behaviour

The Mario Kart Kiosk Demo should boot in widescreen with beta tracks

### Actual behaviour

It booted without the widescreen, but with the tracks.

### Steps to reproduce

1. Enable widescreen
2. Enable ANY cheat (Widescreen 2.0 included)
3. Profit!

**Comment by RocketRobz** [comment]
Not all cheats work.
Even combining certain cheats won't work.

Plus, this is an nds-bootstrap issue.
