### ISSUE TITLE
Start failed. Error 1 nds-bootstrap (Release) not found

### ISSUE THREAD

**Issue by MrLilian** [DS-Homebrew/TWiLightMenu#867]
TWiLightMenu crash when i tried to use GBARunner2.
It notify me "_Start failed. Error 1 nds-bootstrap (Release) not found_"

![image](https://user-images.githubusercontent.com/59798891/72221106-af6ffb80-3557-11ea-996b-a3271087f374.png)

I don't understood why ? My folder "__nds_" does'nt have any problems

![image](https://user-images.githubusercontent.com/59798891/72221047-29ec4b80-3557-11ea-9cae-220c661516ec.png)

**Comment by NightYoshi370** [comment]
You need to download Homebrew bootstrap.
Also, this is the wrong place for support; please go to the Discord server or GBAtemp thread
