### ISSUE TITLE
All NDS roms and Saves wiped out

### ISSUE THREAD

**Issue by luisfqss** [DS-Homebrew/TWiLightMenu#869]
Well, i was trying to launch an Undub rom of Sands of Destruction
Since the beginning the rom wouldn't start, no matter what, so i started changing settings bit by bit, reverting back if didn't work.
The last change i've made was turning on the "debug" screen
When i pressed play, the upper screen turned red- the console froze.
Like always, i  pressed the power button to reboot, but now all my roms and saves from nds folders are gone
Ive tried opening the SD card on windows and it shows the SD's memory is full, but the rom folder shows nothing :(

Nintendo DSi XL with TWMenu ++ 11.2.0 release version
**TWiLight Menu++ AKmenu

### Expected behaviour

Everytime any of the rooms crashed the console should just reboot and work out just fine.

### Actual behaviour
Ive tried to launch Sands of Destruction ROM, changing settings everytime because the rom would not get past the "nds bootstrap" screen
Red crash screen appeared, i pressed the power button to reboot.
When it booted up all my roms and saves disappeared

(before all this chaos i tried to start the rom in nightly mode)

### Steps to reproduce

1. Turn on debug screen on TWmenu Settings.
2. Play Sands of Destruction (or other non-working rom?)
3. ?

My first time posting something here, sorry for any mistakes (and for the shitty english)
If there's any information, anything missing, sorry again

**Comment by RocketRobz** [comment]
Check the SD card for errors.

**Comment by FlameKat53** [comment]
Your SD Card seems corrupted

**Comment by NightYoshi370** [comment]
Doesn't seem like a TWiLight error. The only thing it writes on your SD is the following:

1. Last Ran INI
2. Times Ran INI
3. nds-bootstrap settings
4. TWiLight Menu++ settings
5. Widescreen stuff

It seems like its your SD card that's having issues. Try checking the SD card or trying another one and seeing if it presists. Closing...
