### ISSUE TITLE
Right Thumb Stick Connection

### ISSUE THREAD

**Issue by hungryman0069** [DS-Homebrew/TWiLightMenu#872]
Hi, 

Is the right thumb stick suppose to be detected & usable with twilight? I get no motion out of it at all.

Can I fix this? 

Thanks

**Comment by RocketRobz** [comment]
No. It cannot be used in DS/DSi mode.

**Comment by NightYoshi370** [comment]
Furthermore, please redirect any support questions to the Discord Server or the GBAtemp thread. This is not a place for asking questions, but rather keeping track suggestions/issues

**Comment by hungryman0069** [comment]
I'm sorry I will delete
