### ISSUE TITLE
Random HEX on the right side of screen in Widescreen

### ISSUE THREAD

**Issue by mrizaiah** [DS-Homebrew/TWiLightMenu#874]
Your console
Tell us which console do you have:

[ x] New 3DS/2DS (XL)
CFW and configuration
Tell us which CFW do you have:

[ x] Luma3DS
TWiLight Menu++ version
Tell us which versions you are using:

[x ] Release [Twl 11.2.0]
 Nightly [insert here commit hash]
TWiLight Menu++ theme
Tell us which theme you are using:

[x ] DSi Menu

Expected behaviour
Tell us what should happen
A DS game in widescreen

Tell us what happens instead
Hex on the right side of the top screen. Ran the .Bat file too

![IMG_6396](https://user-images.githubusercontent.com/60085844/72700828-19217400-3b1b-11ea-8214-2935e04d20fc.jpg)

**Comment by NightYoshi370** [comment]
Please redirect support to the discord server. This isn't a bug
