### ISSUE TITLE
Pokemon Hack roms don't run on widescreen mode

### ISSUE THREAD

**Issue by patomenza** [DS-Homebrew/TWiLightMenu#876]
I installed some hacks, like Sacred Gold and Storm Silver, and Blaze Black (which are from Pokemon Heart Gold, Soul Silver and Black respectively) and they don't run on WS mode. I have another roms, and they run fine, but this hacks, don't run on WS.

**Comment by RocketRobz** [comment]
Widescreen cheats need to be made for the ROM hacks, in order for them to run in widescreen.

**Comment by gamemasterplc** [comment]
It would probably work as is if you copy the widescreen file for the original game it is based on and change the header checksum at the end of the copy to the value you get when opening the rom in NDS Header tool.

**Comment by patomenza** [comment]
Thanks for the advices, but after 2 hours looking and learning how to proper introduce wide screen cheats on usercheat.dat, and several tries, I only managed to strech the image on 4:3. Both Pokemon games. 

Also tried to find Pokemon Ranger widescreen cheats, but couldn't find anything. Any ideas what I'm doing wrong? And please, sorry if I'm using this as a Help thread

ps: I looked widescreen cheats on this page: https://gbatemp.net/threads/widescreen-cheats-for-ds-games-on-3ds.543212/

**Comment by RocketRobz** [comment]
You need to put the widescreen cheat in a `.bin` file, and then put it in `sd:/_nds/TWiLightMenu/widescreen/`.

**Comment by patomenza** [comment]
Do you have any bin file to use as an example and replicate it?

**Comment by NightYoshi370** [comment]
Not really a TWiLight Menu++ issue/suggestion, nor a nds-bootstrap one.
As for an example of a .bin file, use the ones already on the repo

Closing...
