### ISSUE TITLE
Error - SCFG Locked! GBA Runnner 2

### ISSUE THREAD

**Issue by IceCloud76** [DS-Homebrew/TWiLightMenu#878]
**Your console configuration: DSi with HiyaCFW and Unlaunch version 1.8
TWiLight Menu++ Version: Release version 11.2.0
TWiLight Menu++ Theme: 3DS**

I recently updated to a new version of TwilightMenu from an old version back in May to the most recent version 11.2.0. I didn't have problems open GBA Runner 2 before, but now when I launch GBA Runner 2, either by directly launching it or by trying to open a GBA rom file on TWLMenu++, it always boots to a white screen with a purple top bar with an error message which reads, "Error SCFG Locked!".

I have already tried switching the nds-bootstrap to the nightly release in the TWLMenu++ settings, but I still get that same error.

I believe this is a TWLMenu++ menu problem, but if I'm wrong, I'll gladly move this issue to GBA Runner 2's issue page.

**Comment by RocketRobz** [comment]
You need to update nds-bootstrap as well.
Switch back to Release, and download the latest [here](https://github.com/ahezard/nds-bootstrap/releases).

**Comment by IceCloud76** [comment]
Thanks so much! It seems I missed the part where I needed to update nds-bootstrap after updating TWLMenu++.
