### ISSUE TITLE
infinite space didnt use top screen and refuse to start game after intro video

### ISSUE THREAD

**Issue by blasev** [DS-Homebrew/TWiLightMenu#880]
How to produce it : play infinite space (usa, eur, undub) all have same problem
I am using latest released unlauncher 2.0, hiya cfw and twilightmenu++ 11.20 on dsi xl with 1.4.1 firmware
I have tried dsi mode and ds mode but the game still not working as it should. The game play top screen at the bottom, and tops screen only showing blank white. after intro video the game cant go any further, refuse to start

reading the nds-bootstrap compatibility list, infinite space work (eur) wok well on bootstrap 0.17.1 

thanks

**Comment by NightYoshi370** [comment]
That's an nds-bootstrap error not a TWiLight Menu++ one. Please open up an issue there
