### ISSUE TITLE
Add a fastforward switch comand

### ISSUE THREAD

**Issue by AntemPM** [DS-Homebrew/TWiLightMenu#882]
All the NDS/i emulators on PC have a fastforward mode and I miss it, it would be great if it could be added here. If it's possible, I propose that these types of commands be executed using the 3ds and 2ds exclusive switches like ZL/ZR.

**Comment by NightYoshi370** [comment]
Not possible.

1. You can't use ZR/ZL in NTR/TWL mode.
2. That would limit it to N3DS users only
3. Not enough resources available.
4. That's being emulated, not ran natively.
5. TWiLight isn't the handler of nds games. That's a job for nds-bootstrap.
