### ISSUE TITLE
Change icon placement in Quick Menu

### ISSUE THREAD

**Issue by NightYoshi370** [DS-Homebrew/TWiLightMenu#884]
**Is your feature request related to a problem? Please describe.**
It's quite confusing to new people where to click for accessing the ROM menu. Turns out it's the arrow button on the bottom right, but that's one of the main features. Meanwhile, GBARunner2/GBA Mode gets an entire entry on the main elements (which GBARunner2 is now shown in the ROM menu so accessing it's menu feels redundant) and the manual isn't represented at all.

**Describe the solution you'd like**
Change the GBA section to the bottom left, the manual to the bottom right and the ROM and have the current file listing in the bottom, replacing where GBARunner2 is right now

**Describe alternatives you've considered**
Just adding the manual

**Additional context**
It will ruin the authenticity at the expense of user experience

**Comment by RocketRobz** [comment]
The bottom left has brightness changing, only shown on DSi consoles, so where would it go?

**Comment by NightYoshi370** [comment]
Oh, brightness settings are there? Huh, I never noticed. That's because I use a O3DS and not a DSi
Maybe have it on the top right? I feel that would make the most sense

**Comment by NightYoshi370** [comment]
Alright, so in the latest nightly, the button layout has changed. Now, Slot-1 is shown on the top and last-ran ROM is shown on the bottom if it's on the SD card. Launching it on a flashcard will have Last-Ran ROM on the top and the bottom will contain the GBA Mode (if you're running a DS Phat/Lite. If not, then it'll show nothing).
So GBARunner2 WAS indeed removed while still being accurate for DS Phat/Lite users. So, now there's two questions left; What's going on with the ROM select option and the manual?

The ROM Select Option won't be necessary, as by a conversation that took place on the Discord Server, Robz said the following: " I'm turning the quick menu into a sub menu that can be accessed by the ROM select menu."

The manual, Robz said was a good idea. I'm assuming that means he'll add it with the new updates.

Since the main point of this was fixed in a way, I'm closing this
