### ISSUE TITLE
Single Page Console Select

### ISSUE THREAD

**Issue by NightScript370** [DS-Homebrew/TWiLightMenu#885]
**Is your feature request related to a problem? Please describe.**
- Annoying to tell which consoles are able to be selected cause the 2 entries are in different pages.
- Doesn't allow Touch Screen controls
- Wastes space cause BMP instead of PNG
- Images look extremely low quality

**Describe the solution you'd like**
A selector based on the D-PAD, with something like this for the bottom page.
![consoleseltext](https://user-images.githubusercontent.com/18664762/73613924-37718000-45af-11ea-9c43-a561f6188507.png)

Top page with nothing selected
![dsivs3ds](https://user-images.githubusercontent.com/18664762/73613931-45270580-45af-11ea-82ab-adce0e552a06.png)

Top page with DSi Selected
![dsi](https://user-images.githubusercontent.com/18664762/73613934-4ce6aa00-45af-11ea-903c-b4ec75d74abc.png)

Top page with 3DS Selected
![3ds](https://user-images.githubusercontent.com/18664762/73613945-71428680-45af-11ea-8117-841cbaee2095.png)

**Describe alternatives you've considered**
We have a top down selector not based on the DPad by Vulpes. It would require more code and wouldn't be as easy but it'd be more accurate to the DSi Settings
![DSiSettings](https://cdn.discordapp.com/attachments/489307733074640926/661825058901065760/Menu_Concept_4.png)

**Additional context**
We'd eventually be forced to go with the alternative for the Initial Setup in the Settings Rewrite planned. This is just for the meantime

**Comment by Epicpkmn11** [comment]
Sorry if I'm just forgetting, but was this removed? If it was then this can probably be closed

**Comment by NightYoshi370** [comment]
It was removed for SD card users, but DSi Based flashcarts such as the CycloDS iEvolution still use it

**Comment by NightScript370** [comment]
Now that it was fully removed, this can be closed
