### ISSUE TITLE
Scroll to the right beyond the last entry

### ISSUE THREAD

**Issue by eku** [DS-Homebrew/TWiLightMenu#887]
**Your console configuration:**  O3DS 
**TWiLight Menu++ Version:** Always latest nightly
**TWiLight Menu++ Theme:** 3DS

### Expected behaviour

Scrolling to the right stops at last entry. Should behave like the rolling to the left, which stops at the beginning.

### Actual behaviour

Scroll to the right beyond the last entry and never stops.

### Steps to reproduce

1. Press and hold the right on the directional pad
2.
3.

**Comment by NightYoshi370** [comment]
I cannot reproduce this. If anyone else can/can't, comment down below

**Comment by eku** [comment]
@NightYoshi370  I can;)
![IMG_20200204_170039](https://user-images.githubusercontent.com/418685/73762563-a77b3400-4770-11ea-8bce-c10031f21d09.jpg)
![IMG_20200204_170053](https://user-images.githubusercontent.com/418685/73762583-ab0ebb00-4770-11ea-97ef-0736f0050f50.jpg)

**Comment by NightYoshi370** [comment]
That...isn't a bug.
That's accurate to how it is in the 3DS

**Comment by eku** [comment]
@NightYoshi370 Your statement is correct, but with 3DS you can arrange the icons/games further to the right. Unfortunately, this is not possible with the 3DS theme of the TWLMenu, which makes the possibility to scroll endlessly to the right rather pointless.

**Comment by NightYoshi370** [comment]
That's doesn't make it a bug. Also, it isn't endless; It's 40 and it's necessary that each page has 40 for the scroll bar to work
