### ISSUE TITLE
SELECT Menu Options

### ISSUE THREAD

**Issue by NightYoshi370** [DS-Homebrew/TWiLightMenu#890]
**Is your feature request related to a problem? Please describe.**
- GBARunner2 is a menu option and a entry in the files
- Last Ran ROM is quite important but it's only accessible via the Quick Menu.

Here's a current list of all the Menu Options:
```
DSi Menu/3DS HOME Menu
TWLMenu++ Settings
Slot-1 card/Switch to flashcard/Switch to SD card
Start GBA mode/Start GBARunner2
Open Manual
```

**Describe the solution you'd like**
- Remove GBARunner2
- Move GBA Mode to the same entry as DSi/3DSHome Menu
- Add Last Ran ROM

The new list would be like this:
```
DSi Menu/3DS Home Menu/GBA Mode
TWiLight Menu++ Settings
Slot-1 card/Switch to flashcard/Switch to SD card
Open Manual
Launch Last ran ROM
```

**Describe alternatives you've considered**
- Potential Access to the Main Menu from the SD card navigation (like hitting back on root)

**Additional context**
This is written purely for the DSi/Saturn theme, but it applies to the 3DS theme too. Also, you'd need to make the icons

**Comment by NightYoshi370** [comment]
Hmm, the latest nightly redirects the Settings, Slot-1 and GBA stuff to a new DS Classic Menu. However, now you have to go to a different menu in order to access this, wasting time. This does give me an idea though;

Why not make hitting select in the DSi/Saturn themes go to the DS Classic Menu instead of having the select menu there in the first place? We could move DSi/3DSHome menu and Manual stuff there instead

**Comment by RocketRobz** [comment]
Which raises the question: How can one switch between the SD card and the flashcard, if there's nothing visible in the DSi menu to do just that?

**Comment by NightYoshi370** [comment]
Hmmm, true. I completely forgot about the flashcard/sd card switch feature. Sorry.
Well, maybe what we could do is add back the other options and have the DS Classic Menu be accessed via pressing B on the root of the SD/Flashcard navigation? Like, when there is no Back folder. That's what the Acekard and R4 theme do
