### ISSUE TITLE
Error booting games from flashcart

### ISSUE THREAD

**Issue by felpsk** [DS-Homebrew/TWiLightMenu#891]
**Your console configuration:**  DS Lite with R4i gold SDHC
**TWiLight Menu++ Version:**  v11.2.0
**TWiLight Menu++ Theme:** 3DS

### Expected behaviour

 Boot game from flashcart.

### Actual behaviour

 Appears an error message saying the flashcart may be unsupported (although I installed the forwarder correspondent to my flashcard) 

### Steps to reproduce

1. Installed the right forwarder for booting with the flashcart.
2. "USe nds-bootstrap" setted to "no".
3. Tried to launch a game (DK Jungle Climber).

**Comment by RocketRobz** [comment]
You have to use nds-bootstrap with that flashcard.
