### ISSUE TITLE
twilight snemulds saving

### ISSUE THREAD

**Issue by Ivar418** [DS-Homebrew/TWiLightMenu#896]
hi im using twilightmenu latest. now when i play a game (super mario world) and get to a save point with the auto save enabled, and also manually do a save state. when i close and come back there is no save file. not in load save state nor in the snes folder. maybey i am doing something wrong. please help

note: .nds games do save

**Comment by RocketRobz** [comment]
It needs to be fixed on nds-bootstrap side.

**Comment by Ivar418** [comment]
okay il report there then. thanks
