### ISSUE TITLE
TWiLightMenu++ icon in Acekard theme has transparency problems

### ISSUE THREAD

**Issue by NightYoshi370** [DS-Homebrew/TWiLightMenu#899]
**Your console configuration:** Old 3DS XL with Luma v10.0.1
**TWiLight Menu++ Version:** Nightly commit ed53956d587c3e3880983b592e1d85ff00feec2a
**TWiLight Menu++ Theme:** Acekard

### Expected behaviour
TWiLightMenu++ icon colors should render as it renders in the other environments

### Actual behaviour
Transparency problems hit, and the first plus + M is messed up.
![](https://cdn.discordapp.com/attachments/489307733074640926/675936463342272543/20200208_212905.jpg)

### Steps to reproduce

1. Switch to the Acekard theme
2. Navigate to where the boot.nds file is

**Comment by RocketRobz** [comment]
A white box would have to be added behind the icon, as well as other icons, if they have the issue as well.

**Comment by Epicpkmn11** [comment]
That's the correct way to render the icon... The first color is supposed to be transparent
