### ISSUE TITLE
change nickname in dsi twilightmenu

### ISSUE THREAD

**Issue by champi12** [DS-Homebrew/TWiLightMenu#905]
![20200214_161621](https://user-images.githubusercontent.com/54597537/74573065-b5397200-4f45-11ea-9634-efc4e3fdf04b.jpg)
I tried to change the nickname that can be put to the console in the settings but when saving the changes I get a black screen and error press the power button to restart the console (excuse my English since I'm in the translator)
![20200214_155605](https://user-images.githubusercontent.com/54597537/74572914-7c010200-4f45-11ea-9b29-096d9ed8cd1c.jpg)

**Comment by RocketRobz** [comment]
In one of the `shared` folders on the SD root, make sure the HWINFO file isn't set to read-only.
You can do this on your PC, or on the DSi with GodMode9i.

**Comment by champi12** [comment]
Thanks friend it worked
