### ISSUE TITLE
Attempting to open the settings menu by pressing select on dsi theme results in a "start failed error-1" " 

### ISSUE THREAD

**Issue by shinogirl** [DS-Homebrew/TWiLightMenu#909]
**Your console configuration:** DSI with Unlaunch
**TWiLight Menu++ Version:** v12.0.0: TWLMenu++ XL/LL edition (Valentine's Day release)
**TWiLight Menu++ Theme:**  DSi

### Expected behaviour
Pressing select anywhere in the dsi themed menu should open the twighlight menu settings. 

### Actual behaviour
Results in a start failed error. 

### Steps to reproduce

1.use dsi theme on a dsi
2.press select
3.observe
(Note it works properly during the twl menu splash screen and in all other themes)

**Comment by RocketRobz** [comment]
You're missing some files.
Do a full reinstall of TWiLight Menu++.
