### ISSUE TITLE
Ds classic menu not showing when ticked to on

### ISSUE THREAD

**Issue by shinogirl** [DS-Homebrew/TWiLightMenu#911]
**Your console configuration:** DSI and Unlaunch
**TWiLight Menu++ Version:** v12.0.0: TWLMenu++ XL/LL edition (Valentine's Day release)
**TWiLight Menu++ Theme:** Any
### Expected behaviour

Classic menu should show on boot 
### Actual behaviour

Boots straight to theme

### Steps to reproduce

1.turn on show ds classic menu
2.reboot

**Comment by NightYoshi370** [comment]
Can you upload your settings.ini file?

**Comment by RocketRobz** [comment]
The issue is likely related to https://github.com/DS-Homebrew/TWiLightMenu/issues/909

**Comment by NightYoshi370** [comment]
Yep, seems like it is. Closing
