### ISSUE TITLE
dsimenu backgrounds not working in v12.0.0

### ISSUE THREAD

**Issue by handlebike** [DS-Homebrew/TWiLightMenu#912]
**Your console configuration:** DSi with unlaunch
**TWiLight Menu++ Version:** v12.0.0 
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

 16 bit bmps placed in _nds/TWiLightMenu/dsimenu/photos should show as the background.

### Actual behaviour

no background displayed. the same photos work in v11.2.0

### Steps to reproduce

1.Install twilightmenu v12.0.0 with photos in _nds/TWiLightMenu/dsimenu/
2.power on console

**Comment by SuperSaiyajinStackZ** [comment]
Convert the Photos to PNG and it should work.

**Comment by handlebike** [comment]
Completely missed that part in the notes. Thanks.
