### ISSUE TITLE
WPA support for Twilightmenu++

### ISSUE THREAD

**Issue by Gataitai** [DS-Homebrew/TWiLightMenu#917]
Currently only an open wifi connection or a WEP encrypted connection wil let you go online ingame in twilightmenu++.

So it would be nice to have WPA or WPA2 encryption capabilities to be able to go online with newer wifi equipment.

**Comment by SuperSaiyajinStackZ** [comment]
It's not easilly possible, since the only WPA/2 Code that exist is in ASM iirc and not C or C++.

**Comment by NightYoshi370** [comment]
Not something that involves TWiLight either way. Use the nds-bootstrap repo.

Closing
