### ISSUE TITLE
The .cia does not appear once I install it

### ISSUE THREAD

**Issue by TheFlintASteel** [DS-Homebrew/TWiLightMenu#919]
I have installed the .cia of the twilitgh menu and the twilitgh booter several times and it does not appear at the beginning of 3ds, I have already tried from the twilitgh updater, from the universalupdater, delete everything and install Manually, but it doesn't work

**Comment by RocketRobz** [comment]
Have you tried rebooting the console?

**Comment by TheFlintASteel** [comment]
Yes I tried

**Comment by NightYoshi370** [comment]
Twilight booter? We don't use that anymore.
We could help you further if you join our Discord Server and check out our #support channel

Closing...
