### ISSUE TITLE
0x0E code support.

### ISSUE THREAD

**Issue by daveboy2000** [DS-Homebrew/TWiLightMenu#920]
**Is your feature request related to a problem? Please describe.**
0x0E cheat codes are used by the current largest usrcheat.dat repository by DeadSkullzJr. It appears these codes are however not supported by TwilightMenu++ from what I can glean from issues reported at their github repository and on GBATemp, however it appears the issue isn't communicated to here. Without support, activating those cheat codes will result in a game failing to start and just showing a white screen, making it look like a bug with the cheat.

**Describe the solution you'd like**
Support for these 0x0E code types, so that the cheats are compatible with TwilightMenu++

**Describe alternatives you've considered**
Not sure if that applies here, this is about a code compatibility issue.

**Additional context**
Some places were the complaint can be seen firsthand:
https://gbatemp.net/threads/deadskullzjrs-nds-cheat-databases.488711/page-33
https://github.com/DeadSkullzJr/NDS-Cheat-Databases/issues/3
https://github.com/DeadSkullzJr/NDS-Cheat-Databases/issues/7

**Comment by SuperSaiyajinStackZ** [comment]
That's a nds-bootstrap issue, not a Twilight Menu one. nds-bootstrap handles games and cheats.

**Comment by daveboy2000** [comment]
Then what would the solution be?

**Comment by NightYoshi370** [comment]
There's already an open issue on the nds-bootstrap GitHub repository (where it should be).
Please use that instead.

Closing...
