### ISSUE TITLE
Card slot got warm

### ISSUE THREAD

**Issue by JonArbuckle48** [DS-Homebrew/TWiLightMenu#930]
I dunno if it was from this, but I had just updated right before and I noticed that cart support was added, so I thought it might be

Here's what happened:
I have a New 3DS XL, and I updated my Twilight Menu++ yesterday, then started playing Final Fantasy 3 for NDS. I closed the 3DS when I was done, and put it down. Later, I picked it up and the cartridge slot was warm-- not even close to hot, but warm enough to be noticeable. I took out the cart (I had Pokemon Super Mystery Dungeon inserted), saved, exited to the home menu, closed it back up, and set it down for a while. When I picked it back up, everything was normal again

I haven't tried to replicate it yet, but I figured I'd say something in case there's like a runaway process constantly reading from the card when in sleep mode or something (not a programmer lol)

**Comment by JonArbuckle48** [comment]
Update: I've played with it for the past few days, it happens after a while when there's any 3DS game in the card slot and play something on twilightmenu, whether or not I put my system in sleep mode. I've taken the card out and the area stays cool

**Comment by RocketRobz** [comment]
Closing, since it could probably be an nds-bootstrap issue.
