### ISSUE TITLE
Volume control without need of volume buttons (in case they dont work)

### ISSUE THREAD

**Issue by AdamBilisic** [DS-Homebrew/TWiLightMenu#931]
**Is your feature request related to a problem? Please describe.**
The problem is that DSi I bought has volume buttons which dont work.

**Describe the solution you'd like**
Having volume control via gui or custom key combination like start + arrow up / stat + arrow down.

Thanks for the great work you do!

**Comment by Epicpkmn11** [comment]
This is already a feature in nds-bootstrap, if you turn on `Precise volume control` from the `Games and Apps` page of TWiLight Menu++'s settings then when playing DS games from SD you can use Select + Up/Down to change, this would be nice to be implemented in TWiLight itself too though.

**Comment by AdamBilisic** [comment]
Thats awesome! But it works only in DS games. Since TWM++ can also run gba/gbc/snes etc could this feature be available also there ?

**Comment by RocketRobz** [comment]
That would require hooking into the emulator's arm7 IRQ.
I don't feel like implementing it though. :P
