### ISSUE TITLE
Cheat Selection Menu Bug

### ISSUE THREAD

**Issue by mikruzer** [DS-Homebrew/TWiLightMenu#932]
### Your console
 
 Tell us which console do you have:
 
     * [ ]   DS Phat/Lite
 
     * [x]   DSi (non-XL) v1.4.5J
 
     * [ ]   Old 3DS/2DS (XL)
 
     * [ ]   New 3DS/2DS (XL)
 
 
 ### CFW and configuration
 
 Tell us which CFW do you have:
 
 DSi:
 
     * [ ]   (No CFW) DSiWarehax (such as Flipnote Lenny, Sudokuhax, etc.)
 
     * [x]   (No CFW) Unlaunch only _[Unlaunch v2.0]_
 
     * [ ]   Unlaunch+HiyaCFW _[please specify version]_
 
 
 3DS/2DS:
 
     * [ ]   Luma3DS
 
     * [ ]   Rei-Six
 
     * [ ]   Other CFW [specify]
 
     * [ ]   Older CFW
 
 
 ### TWiLight Menu++ version
 
 Tell us which versions you are using:
 
     * [x]   Release _[v12.2.1 with nds-bootstrap v0.30.1]_
 
     * [ ]   Nightly _[insert here commit hash]_
 
 
 ### TWiLight Menu++ theme
 
 Tell us which theme you are using:
 
     * [x]   DSi Menu
 
     * [ ]   3DS HOME Menu
 
     * [ ]   SEGA Saturn
 
     * [ ]   R4
 
     * [ ]   Acekard/akMenu
 
 
 ### Expected behaviour
 in cheat menu when you selected cheat that have same name i.e : on pokemon HGSS cheat menu there a cheat called exp multiplier with option are : 2x, 4x and so on. When there an cheat that have same name like 2x  4x even on different sub folder and different cheat code like money multiplier cheat with same name option like 2x and 4x the cheat is also activated 

 ### Actual behaviour

 The cheat will not automatically activate if selected cheat with same name

 ### Steps to reproduce
 
     1. Launch TWiLight Menu++ 
 
     2. Select game with same cheat option i.e exp multiplier with option 2x, 4x 8x and so on
 
     3. Activate the cheat i.e 4x option
 
     4. Open another cheat option which has the same name 
 
     5. The cheat will be activated to

Other notes
 I can make video of it if you don't understand my explanation

**Comment by NightYoshi370** [comment]
Does the same happen on the Acekard theme?

**Comment by mikruzer** [comment]
not try it yet

**Comment by SleepyLark** [comment]
Same issue as #724
