### ISSUE TITLE
Add option to set Game Title Language in Korean

### ISSUE THREAD

**Issue by greato1** [DS-Homebrew/TWiLightMenu#934]
**Is your feature request related to a problem? Please describe.**
I found 2 multi language support DS game that includes Korean.(SpongeBob Yori Daesodong - multi2, Yu-Gi-Oh! 5D's World Championship 2011 - multi3) Currently, can play in Korean only in Korea System 3DS/DSL(i). I want to play in korean Another country system 3ds.

**Describe the solution you'd like**
Add option to set Game Title Language in Korean, please. Even if it is not Korea System 3DS, can play multi language DS games including Korean. Then I will be able to play in Korean.

**Comment by greato1** [comment]
Some people say there are 6 DS languages. But Korea NDSL has Korean language system.

**Comment by R-YaTian** [comment]
Come to think about it. But I need more informations about this.

**Comment by R-YaTian** [comment]
> Some people say there are 6 DS languages. But Korea NDSL has Korean language system.

Tell me if there is English or Japanese in your Korean-NDSL's firmware language setting.

**Comment by greato1** [comment]
Korean-NDSL's firmware language setting: English, Deutsch, French, Spanish, Korean, Japanese. No Italian.

> 
> 
> > Some people say there are 6 DS languages. But Korea NDSL has Korean language system.
> 
> Tell me if there is English or Japanese in your Korean-NDSL's firmware language setting.

English, Deutsch, French, Spanish, **Korean**, Japanese. No Italian.

**Comment by R-YaTian** [comment]
> > > Some people say there are 6 DS languages. But Korea NDSL has Korean language system.
> > 
> > 
> > Tell me if there is English or Japanese in your Korean-NDSL's firmware language setting.
> 
> English, Deutsch, French, Spanish, **Korean**, Japanese. No Italian.
> 
> And korean multi language games are already available in **Korea system 3DS & TWLMenu++** in korean. But I want to play the same on the other country system 3ds.

You should set game language to Italian for your korean SpongeBob Yori Daesodong and Yu-Gi-Oh!2011 roms on per game setting. You can press Y to open per game setting of the roms.

**Comment by greato1** [comment]
> 
> You should set game language to Italian for your korean SpongeBob Yori Daesodong and Yu-Gi-Oh!2011 roms on per game setting. You can press Y to open per game setting of the roms.

I tested another languages with italian. I can see english in Yori-Daesodong.

**Comment by R-YaTian** [comment]
> > You should set game language to Italian for your korean SpongeBob Yori Daesodong and Yu-Gi-Oh!2011 roms on per game setting. You can press Y to open per game setting of the roms.
> 
> I tested another languages with italian. I can see english in Yori-Daesodong.

I will download the two roms for futher test.

**Comment by R-YaTian** [comment]
> > You should set game language to Italian for your korean SpongeBob Yori Daesodong and Yu-Gi-Oh!2011 roms on per game setting. You can press Y to open per game setting of the roms.
> 
> I tested another languages with italian. I can see english in Yori-Daesodong.

If you set game language to Italian, the Yu-Gi-Oh!2011 will be run with Korean, ha.

**Comment by greato1** [comment]
> 
> If you set game language to Italian, the Yu-Gi-Oh!2011 will be run with Korean, ha.

I say can see english in Yori-Daesodong. Not Yu-Gi-Oh

**Comment by R-YaTian** [comment]
> > If you set game language to Italian, the Yu-Gi-Oh!2011 will be run with Korean, ha.
> 
> I said can see english in Yori-Daesodong. Not Yu-Gi-Oh

I see.It seems that there is a region check on the game.
