### ISSUE TITLE
TWiLight Menu doesn't openning

### ISSUE THREAD

**Issue by caramba45** [DS-Homebrew/TWiLightMenu#936]
**Your console configuration:**  Old 3DS with Luma3DS
**TWiLight Menu++ Version:**  Release v12.2.1
**TWiLight Menu++ Theme:** 

### Expected behaviour
The 3DS should run TWiLight Menu with no problems.

### Actual behaviour
I installed TWiLight Menu according to the instruction (via FBI and Universal-Updater). When I started to run the application, the screen turned black and the console stopped responding. The only thing that helped was a reboot. I also installed the previous version of v12.2.0, but nothing has changed.

### Steps to reproduce

1.
2.
3.

**Comment by NightYoshi370** [comment]
Please ask support related questions in the #support channel on our Discord Server (found in the ReadME)
