### ISSUE TITLE
Cheat Panel not displayed on DS Lite

### ISSUE THREAD

**Issue by YoBii** [DS-Homebrew/TWiLightMenu#938]
## Your console

Tell us which console do you have:

 * [x]   DS Phat/Lite

 * [ ]   DSi (non-XL) v1.4.5J

 * [ ]   Old 3DS/2DS (XL)

 * [ ]   New 3DS/2DS (XL)

## CFW and configuration

Tell us which CFW do you have:

None

## TWiLight Menu++ version

Tell us which versions you are using:

 * [x]   Release _[v12.2.1 with nds-bootstrap v0.30.1]_

 * [ ]   Nightly _[insert here commit hash]_

## TWiLight Menu++ theme

Tell us which theme you are using:

 * [ ]   DSi Menu

 * [ ]   3DS HOME Menu

 * [ ]   SEGA Saturn

 * [ ]   R4

 * [x]   Acekard/akMenu

## Expected behaviour

After placing the usrcheat.dat in `/_nds/TWiLightMenu/extras/` the Cheats Panel is supposed to be activated by hovering over game and pressing Y -> X.

## Actual behaviour

There is no cheats panel. Pressing X does nothing.

## Steps to reproduce

 1. Launch TWiLight Menu++ 

 2. Select game

 3. Press Y

 4. Press X

 5. ???

## Notes
I checked the CRC values in the cheat file and they check out.

**Comment by RocketRobz** [comment]
This is normal. You can't use cheats at all on flashcards.
