### ISSUE TITLE
No carga juegos en la flashcard.

### ISSUE THREAD

**Issue by Jandri555** [DS-Homebrew/TWiLightMenu#940]
**Your console configuration:**  Flashcard R4i-SDHC B9S
**TWiLight Menu++ Version:** 12.2.1
**TWiLight Menu++ Theme:** 
Acekard

### Actual behaviour
No carga los juegos, como mucho algunos como "shamu's deep sea adventures" llegan a la pantalla de inicio del juego, pero no detectan el sav y quedan atascados al iniciar la partida.

### Steps to reproduce

1. Inicio la r4, OK.
2. Busco el juego y lo abro, OK.
3. Sale la pantalla de carga de Bootstrap (Si es la primera vez que abro ese juego) y queda bloqueado o llega a la pantalla de inicio del juego y no avanza mas. En el caso de "shamu's deep sea adventures", si saco la r4, el juego sigue en la pantalla de inicio, pero funcionando, como si no hubiera sacado la R4.

**Comment by NightYoshi370** [comment]
Este repositorio no es para recibir soporte con juegos. Por favor ve al repositorio GitHub de nds-bootstrap. Ademas, solo hablamos ingles asi que por favor hablad en ingles a la hora de reportar un problema alli.
