### ISSUE TITLE
Make the creation of the fat table set per-game

### ISSUE THREAD

**Issue by IrisHeartCPU** [DS-Homebrew/TWiLightMenu#943]
**Is your feature request related to a problem? Please describe.**
The fat table can make corruption if enabled and some games do not work or work but badly if disabled.

**Describe the solution you'd like**
Make the creation of the fat table that is created by every game and stored in /_nds/nds-bootstrap/fatTable/ "set per-game" like the widescreen instead of choosing if wanting to create or read it on the settings menu. I think with that, instead of putting on ON or OFF and letting a posibility of making corruption on the microsd if ON, and making some games not work if OFF, that will be useful, because we will select only in what games we want the fat table of 512kb want to be created (the games that need it) and it will reduce the probability of corruption of the MicroSD.

**Comment by NightYoshi370** [comment]
>  we will select only in what games we want the fat table of 512kb want to be created (the games that need it)

I don't think games depend on FAT Table Caching. It's something that bootstrap does on its own. That's why I don't think this is necessary.
