### ISSUE TITLE
Unable to Get past Mansion part in Pokemon Rangers Guardian Signs on 3DS with TWILight Menu

### ISSUE THREAD

**Issue by YousufSSyed** [DS-Homebrew/TWiLightMenu#944]
Save File:
[Save File.zip](https://github.com/DS-Homebrew/TWiLightMenu/files/4357575/Save.File.zip)
ROM Download Location: https://wowroms.com/en/roms/nintendo-ds/pokemon-ranger-guardian-signs/19410.html
(I believe this ROM is clean, not AP patched).

I followed the steps at https://www.cfwaifu.com/twilight-menu-3ds/ **(both with all the software set to release at one time, and another time with them all in nightly, got the same result)** to install TWILight Menu++ on my 3DS already with Homebrew and FBI. From that save file, when I exit the mansion, and Celebi appears teleporting my player, the screen turns black.

**Comment by RocketRobz** [comment]
There's already an issue open here: https://github.com/ahezard/nds-bootstrap/issues/792

**Comment by SleepyLark** [comment]
1.) Remove the link, posting links to ROMs is considered piracy and won't be tolerate 
2.)This is a nds-bootstrap issue, not a Twilight Menu issue

**Comment by YousufSSyed** [comment]
I should've known better than to post that link, so I had removed ASAP. Could this issue be deleted?
