### ISSUE TITLE
{Feature Request} Button Combo To Power Off Quick!

### ISSUE THREAD

**Issue by squidysquid11** [DS-Homebrew/TWiLightMenu#946]
I noticed how powering off from within the twighlight menu and DS games within it often took much longer than powering off from the 3ds menu or a 3ds Game so I'm suggesting similar to what the rosalina menu has, a fast power off option but instead from menu since that would take a LOT of unnecessary effort to create, use a button press combination for example L,R,DOWN D-PAD,START = Power Off 

Also a mini suggestion but could you bring back the orange arrow at the bottom right of the initial DS menu instead of the Instruction guide and maybe instead move that on to the bottom left? 
Just makes it easier to access the roms is all.

**Comment by NightYoshi370** [comment]
> I noticed how powering off from within the twighlight menu and DS games within it often took much longer than powering off from the 3ds menu or a 3ds Game so I'm suggesting similar to what the rosalina menu has, a fast power off option but instead from menu since that would take a LOT of unnecessary effort to create, use a button press combination for example L,R,DOWN D-PAD,START = Power Off

Is that even possible? Power Down a 3DS from Homebrew?

> Also a mini suggestion but could you bring back the orange arrow at the bottom right of the initial DS menu instead of the Instruction guide and maybe instead move that on to the bottom left?
Just makes it easier to access the roms is all.

Press B
