### ISSUE TITLE
Can't turn off WiFi

### ISSUE THREAD

**Issue by goldeneyeonline** [DS-Homebrew/TWiLightMenu#947]
Hi!

I'm on latest version of Twilight Menu++ (12.2.1) booted by unlaunch 2.0 WITHOUT hiya on a DSi non-xl.

Whatever I configure in system settings, I cannot turn off my WiFi in Twilight Menu++.
When in system settings (launched by unlaunch, cannot launch it directly by twilight menu, that button in the menu just takes me to unlaunch, don't know if that is works-as-designed) I turn it off, the LED goes off, but after "back to system menu (which is twilight menu++ right now) it immediately turns back on.

Have checked in games (Mario Kart) and confirm that WiFi is on...

So, how to turn it off?

**Comment by RocketRobz** [comment]
You turn off the LED in TWLMenu++ settings.

**Comment by goldeneyeonline** [comment]
Wow, your fast! :-)

I just tried that, but it just controls the LED doesn't it? Still finding my other console's game in Mario Kart...

Does that mean there is no real "wifi-off" in twilight menu++ on DSi? Guess it still drains battery?

Thanks in advance and keep up the great work on this awesome tool!

**Comment by RocketRobz** [comment]
It is not possible to actually turn off WiFi functionalities.
The same case applies to cartridges.

**Comment by goldeneyeonline** [comment]
Thank you!

That was not the answer I was hoping for but it resolves my confusion :-)

Have a good one!
