### ISSUE TITLE
Game freezes at launch on a black screen

### ISSUE THREAD

**Issue by Banana-Jordan** [DS-Homebrew/TWiLightMenu#948]
**Your console configuration:** New 3DS XL with Luma3DS; 11.13.0-45E
**TWiLight Menu++ Version:** Release [v12.2.1; nds-bootstrap v0.30.1]
**TWiLight Menu++ Theme:**  DSi

### Expected behaviour

It should launch the NDS game. I have this issue only with this game ( Sonic Chronicles: The Dark Brotherhood )and I can play with other games without any issue.

### Actual behaviour

I launch the game, it loades the save file, nds bootstrap, white screen for an second and then it freezes in a black screen.

### Steps to reproduce

1. Launch TWiLight Menu++
2. Select and launch that game
3. Black screen

### Other notes

Already tried to launch the game in DS mode or DSi, instead of the default, same result. I changed 3 times the rom and the save file, to avoid the chance they got corrupted, same result.

**Comment by NightYoshi370** [comment]
Not a TWiLight error. Please report this on the nds-bootstrap repository.
Closing...
