### ISSUE TITLE
White Screen Issue

### ISSUE THREAD

**Issue by MarsTheLad** [DS-Homebrew/TWiLightMenu#949]
**Your console configuration:**
DSi with HiyaCFW + Unlaunch 
**TWiLight Menu++ Version:** 2nd anniversary edition. I'm not actually sure because I started this project months ago.  (think September 2019)
**TWiLight Menu++ Theme:** Dsi

### Expected behaviour

I believe there should be a menu where I can view what games I have and play them 

### Actual behaviour

When I hit any button, the screen turns white. When you press the up or down buttons on the d-pad, you can hear scrollings sounds, and when you press a or b, sometimes you will here the game boot up sound. 

### Steps to reproduce

1. Turn on DSi (With Unlaunch 2.0)
2. Select Twilight++ from the menu
3. Once booted, press the yellow arrow or ds button in the bottom middle, and a white screen will appear. The roms are in the proper roms file, under their console type, but nothing comes up.

**Comment by RocketRobz** [comment]
Please update TWiLight Menu++.

**Comment by MarsTheLad** [comment]
> Please update TWiLight Menu++.

Just did that, but now when I go to boot a game (Or open a rom folder) the loading screen flashes for a second, and then goes straight back to the files list. Is there something I'm missing mere?

**Comment by RocketRobz** [comment]
There's a bug related to updating the recently played list.
Please turn the setting off in TWLMenu++ Settings.

**Comment by MarsTheLad** [comment]
Thanks! Works great now!

**Comment by RocketRobz** [comment]
You're welcome!
