### ISSUE TITLE
Prompt when nds-bootstrap isn't found on the SD card

### ISSUE THREAD

**Issue by NightYoshi370** [DS-Homebrew/TWiLightMenu#951]
**Is your feature request related to a problem? Please describe.**
- When you're on the DSi SD card, homebrew & retail ROMs is launched through nds-bootstrap.
  - Homebrew include emulators, so what's launched through nds-bootstrap are Nintendo DS, Gameboy Advance, Genesis (if you use jEnesisDS) & SNES ROMs.
- If you're on a flashcard, retail ROMs have the option to use nds-bootstrap instead of the flashcard firmware
  - (homebrew is always launched via the kernel on flashcards)

If you do not have nds-bootstrap on your (micro)SD card and attempt to launch one of applications requiring it, it locks you out of TWiLight Menu++ with a message that is extremely vague. Which nds-bootstrap is it talking about? It just says release or nightly, without clarifying homebrew or retail.

**Describe the solution you'd like**
It will check if the nds-bootstrap file exists before attempting to launch it. If you do not have it, it will display a prompt message saying that you do not have "Homebrew/Retail" nds-bootstrap ("Nightly/Release") instead of locking you out. It would then tell you to download it and place it at sd:/_nds/. You could then press B to return to select another file

**Describe alternatives you've considered**
- Expanding the already existing message to say which nds-bootstrap is missing.

**Additional context**
- We get this a ton of times because a dumb video guide forgot to tell users to copy the contents of the `DSi&3DS` folder
- The prompting code is already there; When a Genesis game is over 3 MB and you're using jEnesisDS, it will tell you that you cannot launch it.

**Comment by RocketRobz** [comment]
177634ae and 43f1aec6 sort of implement that.

**Comment by NightYoshi370** [comment]
Well, yeah, sort of.

It allows you to return but it isn't really a prompt of sorts. Plus, it still isn't specifying which nds-bootstrap it's trying to launch: Homebrew or Retail.

**Comment by lifehackerhansol** [comment]
With the above PR the alternative solution is now achieved. Because B4DS and nds-bootstrap is now merged, there is no need for a B4DS prompt.

Based on what I am reading, and the current state of TWiLight Menu++ and nds-bootstrap, it seems the primary solution is also achieved, but that may need further clarification.

**Comment by Kaisaan** [comment]
With what @lifehackerhansol said and with #1521 being merged, I think this should be good to close now.
