### ISSUE TITLE
Folder hiding functionality not hiding folder

### ISSUE THREAD

**Issue by NightYoshi370** [DS-Homebrew/TWiLightMenu#953]
**Your console configuration:** Old 3DS XL with LumaCFW
**TWiLight Menu++ Version:** c03135b6 (nightly)
**TWiLight Menu++ Theme:** DSi theme

The hide folder functionality hasn't worked since we switched to FAT table attributes.

### Steps to reproduce
Try to hide a folder

**Comment by NightYoshi370** [comment]
EDIT: Turns out it is hidding the folder. The issue is that the folder is still visible

**Comment by SleepyLark** [comment]
Is this still happening?  Because I was able to hide a folder just fine on v14.1.0

**Comment by NightYoshi370** [comment]
Can you see the folder in the menu though?

**Comment by SleepyLark** [comment]
Nope, then again I've only tested it on my DSi, so maybe it's only affecting the 3DS?

**Comment by NightYoshi370** [comment]
I highly doubt that. I'll close this since you say it's fixed
