### ISSUE TITLE
Allow users to embed a tiny image on the folder icon

### ISSUE THREAD

**Issue by NightScript370** [DS-Homebrew/TWiLightMenu#954]
**Is your feature request related to a problem? Please describe.**
I feel like it should be easy to select which folder you want based on visual representation instead of literacy comprehension

**Describe the solution you'd like**
A way to add an icon to a folder. Basically, it would scan that dir for a `diricon.png` image and would display the image on-top of the folder. Would have to be small but I'm sure it'd be fine

**Additional context**
I got the inspiration from the badge feature on the 3DS.

**Comment by spellboundtriangle** [comment]
Functionality was added for this with #1800, though with ROMs only. I imagine it wouldn't be too hard to add support for folders as well?

**Comment by Epicpkmn11** [comment]
Added in #1819
