### ISSUE TITLE
Sprites not loading

### ISSUE THREAD

**Issue by FlareRXW** [DS-Homebrew/TWiLightMenu#956]
Console configuration: 
- New 3ds XL (11.13.0-45U) with Luma3ds (10.0.1)
- Twilight Menu++ (v12.2.1) Bootstrap Release (v0.30.1)
- Using the DSi (black) menu theme

What is going on?
When i load a copy of "Mario VS Donkey Kong Mini-Land Mayhem!". The Game loads up fine. however, when i begin to play the game, All of the character sprites dont load. in-game and the cutscenes.

How to replicate:
Launch "Mario VS Donkey Kong: Mini-Land Mayhem!"
Load up a level or start a new game.
Tada! Missing Sprites!

In-Game: Mini-Toys sprites are missing. but you can still interact with them.
Cutscenes: (Beginning cutscene) Donkey Kong, Mario, Palatania are missing. but for some reason, the toads, and the train do load.

**Comment by NightYoshi370** [comment]
Not a TWiLight Menu++ error. Please use the GBARunner2 repository

**Comment by RocketRobz** [comment]
Fixed your comment. :P
