### ISSUE TITLE
white screen stuck in New Nintendo 2DS XL

### ISSUE THREAD

**Issue by edgar7386** [DS-Homebrew/TWiLightMenu#957]
**Your console configuration:**  
**TWiLight Menu++ Version:** 
**TWiLight Menu++ Theme:** 

### Steps to reproduce

1.
2.
3.

**Comment by SleepyLark** [comment]
Tried reinstalling? There's not much we can do if you don't give us any information.  Does it happen when you start the program? Is it only when you play a game (if so that would be an nds-bootstrap issue instead)?

**Comment by NightYoshi370** [comment]
Support is to be done on the discord server. Closing
