### ISSUE TITLE
Akmenu theme breaking

### ISSUE THREAD

**Issue by alanotics** [DS-Homebrew/TWiLightMenu#958]
**Your console configuration:**  
**TWiLight Menu++ Version:** 
**TWiLight Menu++ Theme:** 

### Steps to reproduce

1.
2.
3.

**Comment by alanotics** [comment]
Also it’s a dsi xl

**Comment by NightYoshi370** [comment]
This seems more of a support type of deal. It works just fine for me on my 3DS XL running it from the SD card.
Join the discord server in the ReadME. Then, check out #support-and-questions and explain your issue there.

Closing
