### ISSUE TITLE
Twilight menu do not "see" Megadrive/Genesis ROM in BIN or SMD format at all

### ISSUE THREAD

**Issue by Galenmacil** [DS-Homebrew/TWiLightMenu#959]
### Hardware :
I am using a DSi with Nintendo Firmware 1.4.4u. Twilight Menu is installed on a 16GB SD card (FAT32, 32kb allocation size) located in the DSi SD card slot. Booting is done via UnLaunch. Slot-1 is empty.

### Software:
-TwilightMenu++ "release" v12.2.1
-nds-bootstrap: v0.30.1 (The one included in the TwilightMenu++ Package)

### Problem:
Using TwilightMenu++, I navigate to an unhidden folder on the root of the SD card named "ROMs" then open a subfolder called "SG". I have several .BIN and .SMD ROM image in this folder but I see nothing in TwilightMenu++. Only the "Back to previous folder" is visible.

### More informations:
I see and I can run other ROMs for NES, SNES, GB and GBA just fine.

Note that in the settings of TwilightMenu++ I did set the "show Megadrive/Genesis" ROM to yes/true (Settings.ini line "SHOW_MDGEN = 1")

**Comment by RocketRobz** [comment]
You need to change the filetype to `.gen`.

**Comment by Galenmacil** [comment]
Thanks. It solve my issue. Fastest response to date on GitHub. 15 secs... Thanks. 👍

**Comment by Farhan1379** [comment]
I already changed to .gen file, and the Games shows up on Twilight Menu too but …
The Game is Not Run, do you know how can I fix this Problem?

**Comment by RocketRobz** [comment]
> I already changed to .gen file, and the Games shows up on Twilight Menu too but … The Game is Not Run, do you know how can I fix this Problem?

What happens when you launch the game, exactly?
Also, which game, and what size is it?

**Comment by Farhan1379** [comment]
> I already changed to .gen file, and the Games shows up on Twilight Menu too but … The Game is Not Run, do you know how can I fix this Problem?

Is there any way to fix this problem so I can play SG Games on Twilight menu?

**Comment by GoanimateFan** [comment]
@RocketRobz when i tried out, it completely worked fine but the screen GPU wasn't working very well and there was no sound at all

**Comment by NightScript370** [comment]
That's the emulator itself, and nothing to do with the file format
