### ISSUE TITLE
SNES loading issues and inability to play GBA games

### ISSUE THREAD

**Issue by MarsTheLad** [DS-Homebrew/TWiLightMenu#961]
**Your console configuration:** DSi with HiyaCFW + Unlaunch 2.0
**TWiLight Menu++ Version:** 12.2.1
**TWiLight Menu++ Theme:** Dsi

### Expected behavior

I have 2 issues, one with the snes emulator and one with gba launching.

1. Earthbound should run normally, with no messed up textures or duplicated text boxes. It should also be saved using the save button on the snemulds emulator

2. Mother 3 should boot from the _gba file. 

### Actual behavior

1. I have an Earthbound rom that I have been playing, but the game doesn't save and after the first part of the game (after you leave pokey's house and it turns from night to day) the textures get all screwed up (for example, the floor in ness' house is made of flowers) and the boss fights have duplicate text boxes. I also have installed different versions of the rom, thinking that was the issue, but it seems to be the emulator itself. 

2. I have a GBA rom that refuses to launch because it says "The GBA BIOS is required to run GBA games. Please place the BIOS on the root of the "bios.bin." Where do I find this file and shere exactly do i put it?

### Steps to reproduce
Issue 1:
1. Run a SNES game (In this case Earthbound)
2. Play through a portion of the game and save (in game and through the snemulds that boots when you launch) (I also turned autosave on to try and fix this issue)
3. Turn off the console.
4. reboot and reopen the game to see the file is missing. 

Issue 2: 
1. Go to the _gba folder
2. Launch game

**Comment by RocketRobz** [comment]
1. None of the SNES games save, and that's an nds-bootstrap issue.
2. GBA games cannot be placed in `_gba`. Also, you search for the BIOS yourself.
