### ISSUE TITLE
Pokemon Black 2 / White retail cartridge whitescreen; can't access IR ports of said carts while trying to use Pokewalker through HG

### ISSUE THREAD

**Issue by AmeySV** [DS-Homebrew/TWiLightMenu#962]
**Your console configuration:** N3DS XL , firmware 11.13.0-45U with Luma3DS 10.0.1
**TWiLight Menu++ Version:** Release version 12.2.1 (with bootstrap version 0.30.1)
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

Cartridges (Black 2/White) are recognized on the DS Classic Menu. When booted from same menu, they should load into the games themselves. HeartGold should access IR port of aforementioned cartridges when attempting to connect to the Pokewalker. The connection should be successful.

### Actual behaviour
Cartridges are recognized, but once attempted to boot through DS Classic Menu, simply whitescreen. HeartGold ROM boots, and is otherwise playable, but can't access IR ports of White or Black 2 cartridges when inserted into 3DS. When Pokewalker attempts to connect, "No Trainer found." message shows up on Pokewalker screen.

### Steps to reproduce
First half:
1. Load Black 2 / White cartridge into N3DS XL. Open Twilight Menu ++ through application installed from .cia file (using FBI to install).
2. Click on Black 2 / White cartridge from DS Classic Menu screen.

Second half:
1. Load Black 2 / White cartridge into N3DS XL. Open Twilight Menu ++ through application installed from .cia file (using FBI to install).
2. Click on HeartGold ROM from DS Classic Menu screen.
3. Click "Connect to Pokewalker".
4. Click "Return from a stroll".

**Comment by RocketRobz** [comment]
First half: TWL carts will be supported in the next version.
Second half: To use IR, switch the SELECT button option to the SELECT menu.

**Comment by AmeySV** [comment]
Thank you for the speedy reply!

Switched DSi/Saturn: SELECT to Select Menu in GUI settings, and set Slot-1 microSD access to Off. Still unable to use IR, unfortunately.

**Comment by RocketRobz** [comment]
Make sure `DS Classic Menu` is also set to be hidden.

**Comment by AmeySV** [comment]
Switched DS Classic Menu on startup to No. No change however.

**Comment by RocketRobz** [comment]
If you launched the game straight after setting it to No, then reboot the console.

**Comment by AmeySV** [comment]
Worked like a charm! Thank you so much!

**Comment by RocketRobz** [comment]
You're welcome.
