### ISSUE TITLE
Add cart dumping

### ISSUE THREAD

**Issue by Multimegamander** [DS-Homebrew/TWiLightMenu#963]
**Is your feature request related to a problem? Please describe.**
Dumping carts for TWLMenu++ is kinda confusing for a noob

**Describe the solution you'd like**
It would be cool you took the cart dumping from GM9i, and put it into TWLMenu++, maybe in the menu that pops up when you press select, and instead of SD:/gm9i/out it could be SD:/roms/nds and auto trim the rom, or have an option for trimming idk. I think it would also reduce piracy if there was an easy way as that to add games from cart

**Describe alternatives you've considered**
idk

**Additional context**
**context**

**Comment by Multimegamander** [comment]
I'm installing linux, can't respond for a bit, brb

**Comment by NightYoshi370** [comment]
Outside the scope of TWiLight *Menu*++.
Also, no one expected you to respond as soon as possible, so /shrug

Closing

**Comment by Multimegamander** [comment]
Or maybe a plus icon like on USBLoaderGX
