### ISSUE TITLE
The image of the game nds is not seen on the upper screen

### ISSUE THREAD

**Issue by wuniversales** [DS-Homebrew/TWiLightMenu#965]
This happens with the 3ds theme of TWiLightMenu, at the top no preview of the games is generated.
In its place comes a question.
The cover of the game should appear at the top of the screen (same as appears in the dsi theme).
Good job greetings

PD: My console, nintedo 3ds (Old), latest version of TWiLightMenu (v12.2.1).

**Comment by NightYoshi370** [comment]
Does the question mark thing happen on the DSi theme too?

**Comment by IrisHeartCPU** [comment]
> Does the question mark thing happen on the DSi theme too?

Yes, it happens in the Dsi theme too, in a few games it happens for me in the two themes. No cover, only a question mark [?] on a black background.

**Comment by NightYoshi370** [comment]
TWiLight Menu++ Updater is discontinued, please use Universal Updater instead.

**Comment by SleepyLark** [comment]
Seems like an issue with the images themselves, try redownloading the box art again and making sure there's actually an image for them (the image name will be the same as the game's titleID) or checking to see that the in the right folder and are in .png format.
https://github.com/DS-Homebrew/TWiLightMenu/wiki/Box-art-(game-cover)-display

**Comment by RocketRobz** [comment]
TWiLight Menu++ Updater has got a new release. Try that, and see if it fixes your issue.

**Comment by IrisHeartCPU** [comment]
I tried, and it did nothing

**Comment by chyyran** [comment]
Closing as stale for now.
