### ISSUE TITLE
Top screen doesn't use full width in n3ds

### ISSUE THREAD

**Issue by wuniversales** [DS-Homebrew/TWiLightMenu#966]
Currently the top screen does not use full width in nintendo 3ds (Old)

Why not take advantage of that space for the launcher?

I understand that games are distorted if the screen size is changed, but TWiLightMenu should load in full screen (Games do not).

The CIA application, for example, uses the top screen fully.

Cheers

PD: My console, nintedo 3ds (Old), latest version of TWiLightMenu (v12.2.1).

**Comment by SuperSaiyajinStackZ** [comment]
That would require more Research of TwlBg probably, not even sure if the Full Screen can be even used on TWL Mode.

**Comment by NightYoshi370** [comment]
Not a bug and not something TWiLightMenu handle

**Comment by wuniversales** [comment]
So could you change it to enhancement instead of closing it?

**Comment by NightYoshi370** [comment]
> not something that twilight handles
As such, it has no business having the issue here.

Take it to the TwlBg research thread on GBAtemp
