### ISSUE TITLE
Hotkey combo to return to rom selector while in game for 2DS/3DS

### ISSUE THREAD

**Issue by senorpatricio** [DS-Homebrew/TWiLightMenu#968]
When I am playing a game and want to switch to a different NDS game, I have to go to the home page, then back into Twilight Menu, then select a different game. 

If at all possible, I would like to be able to leave the game and return the the Twilight Menu rom selector screen, without having to exit Twilight Menu at all.

**Comment by RocketRobz** [comment]
You can already do that.
Hold L+R+DOWN+B for 2 seconds.

**Comment by senorpatricio** [comment]
Thanks for the quick response and for such a great application. You've made
my year.

**Comment by senorpatricio** [comment]
This is great. Thank you! Is it documented anywhere?

**Comment by RocketRobz** [comment]
It's documented here: https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/

**Comment by senorpatricio** [comment]
Awesome. Thanks again.
