### ISSUE TITLE
Max boxart filesize is 45kb?

### ISSUE THREAD

**Issue by KirovAir** [DS-Homebrew/TWiLightMenu#969]
Hello,

Since the Valentine 2020 update more boxart sizes are supported (yay!) so I started testing some new bigger boxart sizes. I noticed when trying some larger size boxarts it loads around 50% of them. I noticed all files that didn't load had a filesize > 45kb. (ex: 47kb didn't load)

### Expected behaviour
TwilightMenu should load the boxart.

### Actual behaviour
It displays the previous boxart, or a mangled image.

### Steps to reproduce
1. Use this [non-working boxart](https://www.imgdumper.nl/uploads9/5e84482767cd6/5e84482765d45-D6E7EA3E826FEB6FD947D7661A33C4C4.png) and this [working boxart](https://www.imgdumper.nl/uploads9/5e8448b193ffe/5e8448b19161b-9406E7E12689FC5A6730D3AD39271295.png) as examples.
2. Browse through games.
(In this case the aspect ratio is not 100% the same but the same thing goes for bigger NDS boxarts for example)

Is this done by purpose or by limitations of the hardware/png library? If so I'm gonna arrange some checks when downloading boxart to not exceed this spec. :)

Cheers.

**Comment by RocketRobz** [comment]
Try turning off `Cache box art to RAM.`

**Comment by KirovAir** [comment]
Thanks for the fast reply! 
It works great!
