### ISSUE TITLE
Feature Request: New 2DS & New 3DS: set C-Stick as ABXY

### ISSUE THREAD

**Issue by MuPlayZZ** [DS-Homebrew/TWiLightMenu#970]
Hello RocketRobz!

for games like call of duty, can you set the New 2DS & New 3DS C-Stick as ABXY?

This would be very apprieciated!

**Comment by NightYoshi370** [comment]
Not possible without serious TWLFIRM patches. Also, TWiLight Menu++ is just that; A menu. It isn't the one handling the games.
Closing
