### ISSUE TITLE
I cant select any rom

### ISSUE THREAD

**Issue by pablomg29** [DS-Homebrew/TWiLightMenu#973]
**Your console configuration:** Old 2ds with luma
**TWiLight Menu++ Version:** 13.0 Release version
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

When I open the app I have it to open the menu to select the different roms

### Actual behaviour

When I have downloaded de new version via Twilight menu++ updater it only opens the last rom launched before updating it

### Steps to reproduce

1.
2.
3.

**Comment by NightYoshi370** [comment]
You have it set to run last ran ROM. Hold B while booting into it to skip that or hold SELECT to directly launch the settings app.
We could help you over at our discord server if needed
