### ISSUE TITLE
Failed to appply 4 FRIM patch(es) on start WiLightMenu

### ISSUE THREAD

**Issue by tamvodopad** [DS-Homebrew/TWiLightMenu#974]
**Your console configuration:** New 3DS with Luma3DS
**TWiLight Menu++ Version:** v13.0.0
**TWiLight Menu++ Theme:** 3DS

### Expected behaviour

When I open the app I have it to open the menu to select the different roms

### Actual behaviour

On the first open TWiLightMenu++ app after install  i see error

An error has occurred:

Failed to apply 4 FIRM patch(es)

Press any button to shutdown

### Steps to reproduce

1.
2.
3.

**Comment by RocketRobz** [comment]
What version of LumaCFW are you using?

**Comment by tamvodopad** [comment]
@RocketRobz Luma3DS v10.0.1

**Comment by RocketRobz** [comment]
Closing, since idk how to fix this.

**Comment by donnumski** [comment]
@RocketRobz 
I just got the same problem. When trying to start Twilight Menu on a New 3ds, I get the error: Failed to apply 4 firm patches. This has happened on the last to machines I installed Twilight on.  Luma 3DS v11.0. Can there be a bug on the latest Luma version?
