### ISSUE TITLE
 DS Classic Menu Can Unable to start Flashcard 

### ISSUE THREAD

**Issue by Aeuko** [DS-Homebrew/TWiLightMenu#975]
1.unlaunch_v2.0
2.TWiLightMenu_v13.0.0

 DS Classic Menu start up Flashcard，Up and down white screen

**Comment by RocketRobz** [comment]
Try switching the `Slot-1 Launch Method` to `Reboot`.

**Comment by Aeuko** [comment]
> Try switching the `Slot-1 Launch Method` to `Reboot`.

Tested 10 times，Return to the DS Classic Menu 6 times，Return to the unlaunch menu 3 times，Flashcard 1 times

**Comment by RocketRobz** [comment]
The `Reboot` option isn't stable.
Just keep trying, if the flashcard fails to boot.
