### ISSUE TITLE
Acekard theme deleting ROMs

### ISSUE THREAD

**Issue by RocketRobz** [DS-Homebrew/TWiLightMenu#976]
It seems that whenever a Guru Error occurs when launching a ROM, the ROMs in the folder with the launched ROM gets deleted.

This occurred for 2 users with a 32GB and bigger than 32GB SD card.

**Comment by TotallyNotGuy** [comment]
Happened to me as well, some more details:
-Latest TWiLightMenu and nds-bootstrap
-DSi CFW
-16GB SDHC
-Happened when I tried to launch Black 2 (which worked before)
-The contents of the /roms/nds/ folder got overridden by a perfect copy of /_nds/TWiLightMenu

**Comment by StaticSaga** [comment]
Happened to me as well. I launched aktheme.srldr directly from Unlaunch and I got the same problem. It seems that the original files are deleted and the metadata is copied from _nds/TWiLightMenu.
The culprit _may_ be romsel_aktheme/arm9/source/common/files.cpp:293, it's the only place in akmenu that uses unlink().

**Comment by R-YaTian** [comment]
This also occurred for me with 2GB SD card.

**Comment by StaticSaga** [comment]
Strangely, I'm not able to replicate the bug in NO$GBA.

**Comment by RocketRobz** [comment]
Can anyone see if the bug is fixed in this commit?
https://github.com/DS-Homebrew/TWiLightMenu/commit/5d1e7510003bc59a361628e60b2228a29d3a2b49

**Comment by StaticSaga** [comment]
Checked on my DSi, it works fine now.
