### ISSUE TITLE
Nsmb rom hacks misdetected as DSiWare

### ISSUE THREAD

**Issue by shaer50** [DS-Homebrew/TWiLightMenu#977]
Updated to the latest Twilight Menu ++ and now my NSMB rom hacks won’t load, I get the Nintendo Splash screen then a “saved file corrupt error [file 3], it deletes the save file and try’s to make a new one but gets stuck in this loop. If I go back to the old twilight files it works fine. Any way to fix this??

**Comment by RocketRobz** [comment]
This is an nds-bootstrap issue, not a TWiLight Menu++ issue.

**Comment by shaer50** [comment]
Can I update nds-bootstrap to fix this?

**Comment by RocketRobz** [comment]
What version is it on?

**Comment by shaer50** [comment]
Latest version that came with your new twilight menu. Maybe I could downgrade the nds-bootstrap?

**Comment by RocketRobz** [comment]
Please turn on Logging, relaunch the game, then upload `NDSBTSRP.LOG`.

**Comment by shaer50** [comment]
How do I turn on the logging?

**Comment by RocketRobz** [comment]
In TWLMenu++ Settings, switch to the Games/Apps page, then search for the option.

**Comment by shaer50** [comment]
[NDSBTSRP.LOG](https://github.com/DS-Homebrew/TWiLightMenu/files/4432887/NDSBTSRP.LOG)

**Comment by RocketRobz** [comment]
Try turning off heap shrink in the per-game settings.
Press Y in the ROM menu to open it.

**Comment by shaer50** [comment]
it wont make a .sav file in the saves folder. im only having this issue with the hacked roms i have.  I'll give that heap shrink a try

**Comment by RocketRobz** [comment]
So what theme are you using in TWiLight Menu++?

**Comment by shaer50** [comment]
3ds theme,  where do i press Y? i tried it while im highlighting the rom and i only get a info popup with no options

**Comment by RocketRobz** [comment]
The Y button, ofc.

Can you show a screenshot?

**Comment by shaer50** [comment]
It works on the other NDS games, on the hacked Roma I get this 
![image](https://user-images.githubusercontent.com/63177337/78466385-82526580-76ce-11ea-87dd-d792854ca1fa.jpg)

**Comment by RocketRobz** [comment]
Please update to the latest TWiLight Menu++ nightly, and see if the bug is fixed.

**Comment by shaer50** [comment]
can i do this via the twilight menu update cia and choosing the nightly option or do i need to do it manually via a pc?

**Comment by RocketRobz** [comment]
You can do it via the updater.

**Comment by shaer50** [comment]
You fixed it, I now have pre-game options on all the hacks and the games create a save file and will load and play. Did not have to adjust the heap shrink settings. THANK YOU for the help and super quick responses. Awesome program and works great for the DS games 👍🏻💪🏻
