### ISSUE TITLE
Pressing SELECT on the DSi Style menu opens DS Menu instead of opening settings menu

### ISSUE THREAD

**Issue by YourKalamity** [DS-Homebrew/TWiLightMenu#987]
**Your console configuration:** DSi with Unlaunch
**TWiLight Menu++ Version:** v13.1.0
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

Pressing the SELECT button used to open up the menu in which I can modify the TWiLight Menu settings or launch a Slot 1 card

### Actual behaviour

The DS classic menu appears

### Steps to reproduce

1. Press SELECT from DSi menu
2. 

### Additional Info

I'm not sure if this was intended or not, but if it is, is there another way to launch a Slot-1 Card from TWiLight (and not by holding Y on bootup) and changing the TWiLight settings from the system instead of modifying the files on the SD Card

**Comment by RocketRobz** [comment]
Go into TWLMenu++ Settings by touching the DS icon, then change the SELECT button option.

**Comment by YourKalamity** [comment]
Thank you for your fast response.
