### ISSUE TITLE
Dsi XL wifi always on

### ISSUE THREAD

**Issue by domeus** [DS-Homebrew/TWiLightMenu#990]
Latest twilight menu, dsi xl with unlaunch. When twilight menu booting, wifi turns on. No option/way to disable. On system settings wifi is disabled. Or Im doing something wrong?

Also selecting system settings from twilight menu - unlaunch appear - no system settings. Have to select system settings from unlaunch.

**Comment by RocketRobz** [comment]
You can turn on/off the WiFi LED in TWLMenu++ Settings.

Also, System Settings just fails to boot sometimes.

**Comment by domeus** [comment]
> You can turn on/off the WiFi LED in TWLMenu++ Settings.
> 
> Also, System Settings just fails to boot sometimes.

Ok, thanks. But the wifi is still draining the battery?

**Comment by RocketRobz** [comment]
The WiFi (LED) setting does not change how WiFi works.
It's the same case for outside of Unlaunch/TWLMenu++.

**Comment by domeus** [comment]
> The WiFi (LED) setting does not change how WiFi works.
> It's the same case for outside of Unlaunch/TWLMenu++.

Is there way to disable wifi? Outside of twlmenu wifi is disabled.

**Comment by RocketRobz** [comment]
What games did you try?

**Comment by domeus** [comment]
> What games did you try?

New super mario bros. I have two systems. Wifi is disabled from system settings, but still working in the game. So somehow twlmenu force enables it.

**Comment by RocketRobz** [comment]
Can you try original cartridges, via Launcher?

**Comment by domeus** [comment]
> This isn't a TWLMenu++ issue.
> 
> Can you try original cartridges, via Launcher?

With original cartridges wifi led stays off, and not connecting each others. Wifi led is off on ulaunch, also launcher, but turns on immediately when I launch twlmenu. Its not only led, its also whole wifi chip. So something in twlmenu enables it when it start.

**Comment by kamil9489** [comment]
I have Nintendo DSI with Twilight v13.1.0 and have identical problem with wifi led staying on. Also i can't boot system setting from select menu (must do it always via Unlaunch). The problem with wifi led staying on started from version v11.2. Also i don't have the option in twilight setting to turn off wifi led.

**Comment by RocketRobz** [comment]
@kamil9489 Are you sure you're on v13.1.0? Please check TWLMenu++ Settings to be sure.
WiFi LED should be in the Misc settings page.

**Comment by domeus** [comment]
> @kamil9489 Are you sure you're on v13.1.0? Please check TWLMenu++ Settings to be sure.
> WiFi LED should be in the Misc settings page.

Srry, but that wifi led setting turns off only the LED, not the wifi chip like you said earlier. You can still connect with wifi. So yes, something triggers wifi when twlmenu boots up... Like I said couple of times.

**Comment by RocketRobz** [comment]
@domeus I know, but it seems he only wanted the LED off.

**Comment by kamil9489** [comment]
I recorded problem: https://youtu.be/qb63trtxKW8 maybe this will help for fix.

**Comment by SleepyLark** [comment]
If I turned off wifi in the system settings and the LED is off when I load an actual cartridge through the launcher.  When I launch it through TWL Menu the LED is on because I have the LED option enabled through TWL Menu settings.  So even though the wifi is disabled in the System Settings, TWL menu will still show the LED on if the option is enabled because it over rules it.  So just because the LED is on, doesn't mean the wifi is on

**Comment by domeus** [comment]
> If I turned off wifi in the system settings and the LED is off when I load an actual cartridge through the launcher. When I launch it through TWL Menu the LED is on because I have the LED option enabled through TWL Menu settings. So even though the wifi is disabled in the System Settings, TWL menu will still show the LED on if the option is enabled because it over rules it. So just because the LED is on, doesn't mean the wifi is on

**Comment by domeus** [comment]
> If I turned off wifi in the system settings and the LED is off when I load an actual cartridge through the launcher. When I launch it through TWL Menu the LED is on because I have the LED option enabled through TWL Menu settings. So even though the wifi is disabled in the System Settings, TWL menu will still show the LED on if the option is enabled because it over rules it. So just because the LED is on, doesn't mean the wifi is on

Its not working like that. Option only disables led, but wifi is still enabled. I confirmed that by playing multiplayer between two consoles. Read posts from above.

**Comment by SleepyLark** [comment]
So I tested download play with WiFi off in the system settings and the LED off in TWL menu.  Launching the cartridge through the launcher the system didn't detect anyone, however when launching through TWL menu the system was able to detect even though it was supposed to be turned off in the system settings.  I'm using version 14.1.0. 
Sorry about the confusion, I see the problem now.

**Comment by kamil9489** [comment]
Version v14.2.0 on Nintendo DSI and i can't still disable wifi led on  TWL Menu settings. I'm using DSi Theme if this matters. 
But system setting shortcut started to working on this version (no crashing).

**Comment by jportoles** [comment]
Also seeing this as well. I suspect the culprit is Unlaunch forcing wifi to be enabled on boot regardless the system setting, so this would be on the nocash guy to fix. Disabling the WiFi LED on TWLMenu++ does not prevent WiFi from draining battery (it's cosmetic only).

**Comment by Epicpkmn11** [comment]
Has this been fixed? I tried turning off "Wi-Fi" in TWiLight Settings (which is new I think?) and games don't seem to be able to connect so I assume its really off

**Comment by chyyran** [comment]
Closing as stale for now.

**Comment by clach04** [comment]
For anyone finding this after a google search, this is resolved and working in TWLMenu++ v19.1.1 :)

1. Pressing SELECT to bring up options
2. Then the bottom/middle "options" menu
3. Press L or R to get to "Misc. settings"
4. (Near the bottom of the screen) "WiFi" can be toggled
