### ISSUE TITLE
DS classic menu bugs

### ISSUE THREAD

**Issue by hubert-skowronek** [DS-Homebrew/TWiLightMenu#991]
**Your console configuration:** new 3DS XL, Luma 10.0.1 
**TWiLight Menu++ Version:** 13.1.0 
**TWiLight Menu++ Theme:** DSi

### Expected behaviour

1. DS classic menu should show last game played box picture
2. There shouldn't be that known TWL bug with duplicated bottom bar on the bottom screen, which now is deterministic

### Actual behaviour
1. No picture (black placeholder instead)
2. Duplicated bar on the bottom screen always bugged

### Steps to reproduce

1. Turn on classic DS menu or just turn select if at DSi menu
2. Notice above issues

**Comment by NightYoshi370** [comment]
>There shouldn't be that known TWL bug with duplicated bottom bar on the bottom screen, which now is deterministic
That's an issue with TWL_FIRM and can happen on actual cartridges, not TWiLight Menu++

**Comment by hubert-skowronek** [comment]
@NightYoshi370 should I provide a pic? Because it's happening every time, I had deleted all titles related to TWLMenu from my 3DS and installed cias again and the issue persists

**Comment by NightYoshi370** [comment]
Close and re-open the lid of the DS.

**Comment by hubert-skowronek** [comment]
@NightYoshi370 closing and re-opening the lid "fixed" the issue, but after closing and launching TWLMenu the bar appears again

**Comment by hubert-skowronek** [comment]
The same issue happens on another new 3ds xl with the very same configuration

**Comment by kyoforkshomebrews** [comment]
I noticed the duplication problem too. It didn't happen before some updates ago.

**Comment by NightYoshi370** [comment]
Issue 2 was fixed but what about issue 1?

**Comment by Epicpkmn11** [comment]
> Issue 2 was fixed but what about issue 1?

I don't think its been changed, but isn't it just that it was changed to show the Slot-1 card's boxart instead of the last played game? So not so much a bug as a change... Though it might be nice to show the last played game's boxart if there is nothing in Slot-1

**Comment by chyyran** [comment]
Closing as stale for now, probably should reopen a `request` or `enhancement` for the boxart issue.
