### ISSUE TITLE
German translation: Umlauts are not displayed

### ISSUE THREAD

**Issue by eku** [DS-Homebrew/TWiLightMenu#995]
**Your console configuration:** O3DS
**TWiLight Menu++ Theme:**  3DS

### Expected behaviour

German umlauts are displayed correct.

### Actual behaviour

Instead of an umlaut a question mark is displayed.

### Steps to reproduce

1. Set locale to German
2. Browse through settings
3. There are many other places where a question mark is displayed instead of an umlaut.

Possibly the encoding of the text file is not correct. Is UTF-8 supported in principle?

**Comment by Epicpkmn11** [comment]
Not sure exactly when this was fixed, but umlauts appear to be working for me now so I think this can be closed
