### ISSUE TITLE
Nds Homebrew apps don't working.(for me)

### ISSUE THREAD

**Issue by flitzekexHD** [DS-Homebrew/TWiLightMenu#996]
**Your console configuration:DSi xl with Hiya CFW and Unlaunch  
**TWiLight Menu++ Version:13.1.0 
**TWiLight Menu++ Theme:AKMenu 

### Expected behaviour
The homebrew apps just works fine

### Actual behaviour
The homebrew apps are asking for a dldi patch

<!-- I am a german student and I actually speak German and don't speak English very well yet --!>

**Comment by RocketRobz** [comment]
nds-bootstrap automatically DLDI-patches the homebrew.
If you're still getting that message, then the homebrew is incompatible.
