### ISSUE TITLE
Wireless connection not working and automatic reset

### ISSUE THREAD

**Issue by MasterLuke05** [DS-Homebrew/TWiLightMenu#997]
Ok so my two brothers have twilightmenu++ and they're wireless connection is working fine, but mine doesn't work. I'm using Twilightmenu++ 13.10 on the Nintendo DSi, with a 2gb microSD. Also when I run a ROM the console resets and when I reopen the twilightmenu it opens the ROM. It's not a problem but is pretty annoying. Are there solutions to my problems?

**Comment by SleepyLark** [comment]
Is it like this for every game?  If not, what is the game you're trying to run?
