### ISSUE TITLE
Loading games off FTP

### ISSUE THREAD

**Issue by niansa** [DS-Homebrew/TWiLightMenu#998]
**Is your feature request related to a problem? Please describe.**
I have multiple Nintendo (3)DS and it is very annoying to sync games/gamehacks between them. My idea would be to allow connecting to and downloading from some FTP server (so I can store the games just on my homeserver) on-the-fly. As example into some temporary directory.

**Describe the solution you'd like**
Same menu as the current one but with the ability of FTP

**Describe alternatives you've considered**
Samba? Some special server software? There are no other solutions I guess

**Additional context**
No, I do not have so many games that I can't save them on my SD card. I developing ROM hacks and sometimes like to play my own hacks in free-time. Keeping SD cards in sync is annoying.

**Comment by StaticSaga** [comment]
There are a few DS FTP servers, but they use only DS-mode WiFi, which does not support WPA(2) and it's painfully slow.
I think that we should have a open-source DSi compatible WiFi library before thinking about FTP clients (after that, we could just port a already-available FTP library).

**Comment by niansa** [comment]
Is it fast enough to transfer just around 50 MB?

**Comment by NightYoshi370** [comment]
I don't think this would be a TWiLight Menu++ issue. Rather, from the looks of things, itd have to be from nds-bootstrap.

Also, you should know that we still haven't gotten a working implementation of WPA2 in Homebrew yet. Right now, we're limited to WEP or open. That's why I doubt the feature would ever come

**Comment by niansa** [comment]
What's wrong with open hotspot? Some server for wifi-capable devices could be written that uses open wifi connection (without internet access for sure) to provide access to the client.
Also what about just first downloading the .nds file to some temporary directory first then use nds bootstrap as usual to load the file? .sav file does not even need to be on server!

**Comment by StaticSaga** [comment]
The problem with open hotspot is that for now we only support the DS WiFi chip, which is quite slow. There are a few FTP implementation the card itself is not really fast (800 KB/s), therefore loading heavy games would take quite a while.

**Comment by FormalSnake** [comment]
My Nintendo DSi XL connects to my wpa2 network, and my computer does not have an SD port, making transfers painful, so this feature would be great to put games on my DSi
