### ISSUE TITLE
Word Wrapping on game titles

### ISSUE THREAD

**Issue by Glaceon575** [DS-Homebrew/TWiLightMenu#999]
**Is your feature request related to a problem? Please describe.**
With certain games my rom file names are verbose and sometimes go off the screen to the point where it is difficult to tell the what game is selected. This is probably specific to the DSi theme, but it still could be an option nonetheless

**Describe the solution you'd like**
Just a simple setting for making the text wrap around into the white space instead of being centered.

**Describe alternatives you've considered**
Maybe a choice for a smaller font, but that might be harder to do

This is with v14.0.0 with the DSi Theme, on a DSi XL

**Comment by SleepyLark** [comment]
I had this problem for a lot of GBA/GB ROMs.  Was wondering if maybe it would be possible to have them display the actual game title instead of the file name?  Like being able to use a database file to display the correct ROM name like what USB Loader GX does for the Wii, though I still think it may need word wrapping regardless

**Comment by zenseii** [comment]
Wouldn't it just be enough to make it ignore regions and languages in the end of the name, like (Europe), (USA), (Japan), (En,Fr) etc.

**Comment by Glaceon575** [comment]
> 
> 
> Wouldn't it just be enough to make it ignore regions and languages in the end of the name, like (Europe), (USA), (Japan), (En,Fr) etc.

I think word wrapping would be better, although that would be nice to have terms to not read from filenames. I think the added complexity of implementing that might be a little difficult as I assume the code just reads the filename from the file system. Names might still might go over the limit in length, but an option to ignore text in parentheses might be a stopgap solution if it would be easier for someone familiar with the code to implement
